"""Committed public inventory/summary for the ``classes`` table."""

from __future__ import annotations

from collections import Counter

from ..validators import extract_enum_constants
from .schema import (
    BMITEM_HEADER,
    BMUNIT_HEADER,
    CLASSES_HEADER,
    SCHEMA_ID,
    dependency_graph,
    read_class_attributes,
)


def build_inventory(records):
    graph = dependency_graph()
    classes_enum = extract_enum_constants(CLASSES_HEADER, name_prefix="CLASS_")
    attribute_flags = read_class_attributes(BMUNIT_HEADER)
    weapon_types = extract_enum_constants(BMITEM_HEADER, name_prefix="ITYPE_")

    values = sorted(classes_enum[r.class_name][0] for r in records if r.class_name in classes_enum)
    attribute_counts = Counter()
    for record in records:
        for name in record.attributes:
            attribute_counts[name] += 1
    weapon_type_counts = Counter()
    for record in records:
        for itype_name in record.base_ranks:
            weapon_type_counts[itype_name] += 1
    battle_anim_counts = Counter(r.battle_anim for r in records if r.battle_anim is not None)
    terrain_avoid_counts = Counter(r.terrain_avoid for r in records)
    reserved_counts = Counter(r.reserved_terrain_table for r in records if r.reserved_terrain_table is not None)
    slow_walking_count = sum(1 for r in records if r.slow_walking)
    promoted_count = sum(1 for r in records if r.promotion != "CLASS_NONE")
    no_battle_anim_count = sum(1 for r in records if r.battle_anim is None)

    lines = []
    lines.append("# Generated-data inventory: classes\n")
    lines.append("\n")
    lines.append("_Auto-generated by `python3 -m scripts.generated_data generate --table classes`. "
                  "Do not edit by hand -- see docs/generated_data.md._\n")
    lines.append("\n")
    lines.append("- Schema: `{}`\n".format(SCHEMA_ID))
    lines.append("- Class record count: {}\n".format(len(records)))
    lines.append("- Index range: {}..{}\n".format(values[0] if values else "n/a", values[-1] if values else "n/a"))
    lines.append("- Classes with a `.promotion`: {}\n".format(promoted_count))
    lines.append("- Classes with `slowWalking`: {}\n".format(slow_walking_count))
    lines.append("- Classes with no `battleAnim` (non-combat): {}\n".format(no_battle_anim_count))
    lines.append("- Classes with `reservedTerrainTable` (`._pU50`): {}\n".format(sum(reserved_counts.values())))
    lines.append("- Dependencies: {}\n".format(", ".join(graph.nodes())))
    lines.append("- Dependency graph digest (sha256): `{}`\n".format(graph.digest()))
    lines.append("\n")

    lines.append("## Attribute (`CA_*`) usage\n")
    lines.append("\n")
    lines.append("| Attribute | Class count |\n")
    lines.append("|---|---|\n")
    for name in sorted(attribute_counts, key=lambda n: attribute_flags.get(n, 0)):
        lines.append("| {} | {} |\n".format(name, attribute_counts[name]))
    lines.append("\n")

    lines.append("## `baseRanks` weapon-type histogram\n")
    lines.append("\n")
    lines.append("| Weapon type | Class count |\n")
    lines.append("|---|---|\n")
    for itype_name in sorted(weapon_type_counts, key=lambda n: weapon_types.get(n, (1 << 30, None))[0]):
        lines.append("| {} | {} |\n".format(itype_name, weapon_type_counts[itype_name]))
    lines.append("\n")

    lines.append("## `battleAnim` (`AnimConf_*`) usage\n")
    lines.append("\n")
    if battle_anim_counts:
        lines.append("| Symbol | Class count |\n")
        lines.append("|---|---|\n")
        for symbol, count in sorted(battle_anim_counts.items()):
            lines.append("| {} | {} |\n".format(symbol, count))
    else:
        lines.append("_none_\n")
    lines.append("\n")

    lines.append("## `terrainAvoid` profile usage\n")
    lines.append("\n")
    lines.append("| Symbol | Class count |\n")
    lines.append("|---|---|\n")
    for symbol, count in sorted(terrain_avoid_counts.items()):
        lines.append("| {} | {} |\n".format(symbol, count))
    lines.append("\n")

    lines.append("## `reservedTerrainTable` (`._pU50`) usage\n")
    lines.append("\n")
    if reserved_counts:
        lines.append("| Symbol | Class count |\n")
        lines.append("|---|---|\n")
        for symbol, count in sorted(reserved_counts.items()):
            lines.append("| {} | {} |\n".format(symbol, count))
    else:
        lines.append("_none_\n")

    return "".join(lines)
