"""Committed inventory for typed chapter objectives and AI groups."""

from __future__ import annotations

from .schema import BUNDLE_CAPACITY, GROUP_CAPACITY, GROUP_MEMBER_CAPACITY, OBJECTIVE_CAPACITY, SCHEMA_ID


def build_inventory(records):
    lines = []
    lines.append("# Generated-data inventory: chapterobjectives\n\n")
    lines.append(
        "_Auto-generated by `python3 -m scripts.generated_data generate --table chapterobjectives`. "
        "Do not edit by hand -- see docs/generated_data_tutorial.md._\n\n"
    )
    lines.append("- Schema: `{}`\n".format(SCHEMA_ID))
    lines.append("- Bundle capacity: `{}` chapters\n".format(BUNDLE_CAPACITY))
    lines.append("- Per chapter: `{}` objectives, `{}` AI groups, `{}` members per group\n\n".format(
        OBJECTIVE_CAPACITY, GROUP_CAPACITY, GROUP_MEMBER_CAPACITY
    ))
    lines.append("| Chapter | Bundle symbol | Objectives | AI groups | Members |\n")
    lines.append("|---|---|---:|---:|---:|\n")
    for record in records:
        members = sum(len(group.members) for group in record.groups)
        lines.append(
            "| {} | {} | {} | {} | {} |\n".format(
                record.chapter, record.symbol, len(record.objectives), len(record.groups), members
            )
        )
    if not records:
        lines.append("| _(none)_ | _(default chapters unchanged)_ | 0 | 0 | 0 |\n")
    lines.append("\n")
    lines.append(
        "Objective and AI-group IDs are stable uppercase source IDs. Runtime telemetry carries their "
        "validated FNV-1a value; collisions are rejected before generation.\n"
    )
    return "".join(lines)
