"""Small C89 emission helpers shared across generated-data tables."""

from __future__ import annotations

import os

GENERATED_BANNER = (
    "/* AUTO-GENERATED by scripts/generated_data -- DO NOT EDIT BY HAND.\n"
    " * Source: {source}\n"
    " * Regenerate with: python3 -m scripts.generated_data generate --table {table}\n"
    " */\n"
)


def render_banner(source, table):
    return GENERATED_BANNER.format(source=source, table=table)


def render_u8_array_field(field_name, values, indent="        "):
    """Render ``.field = { v0, v1, ... },`` for a fixed u8 array field."""
    items = ", ".join(str(v) for v in values)
    return "{indent}.{field} = {{ {items} }},\n".format(indent=indent, field=field_name, items=items)


def write_if_changed(path, content):
    """Write ``content`` to ``path`` only if it differs. Returns True if written.

    Preserving mtimes when content is unchanged keeps incremental `make`
    builds from rebuilding downstream objects unnecessarily, and keeps
    `--check` drift detection meaningful (a no-op regenerate must not
    itself look like drift).
    """
    existing = None
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as handle:
            existing = handle.read()
    if existing == content:
        return False
    directory = os.path.dirname(path)
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)
    return True
