	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x07C, hflip=1
	tsa_entry 0x07B, hflip=1
	tsa_entry 0x07A, hflip=1
	tsa_entry 0x079, hflip=1
	tsa_entry 0x05E, hflip=1
	tsa_entry 0x05D, hflip=1
	tsa_entry 0x05C, hflip=1
	tsa_entry 0x05B, hflip=1
	tsa_entry 0x05A, hflip=1
	tsa_entry 0x059, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x058, hflip=1
	tsa_entry 0x057, hflip=1
	tsa_entry 0x056, hflip=1
	tsa_entry 0x055, hflip=1
	tsa_entry 0x054, hflip=1
	tsa_entry 0x053, hflip=1
	tsa_entry 0x052, hflip=1
	tsa_entry 0x051, hflip=1
	tsa_entry 0x050, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04E, hflip=1
	tsa_entry 0x04D, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x078, hflip=1
	tsa_entry 0x077, hflip=1
	tsa_entry 0x076, hflip=1
	tsa_entry 0x075, hflip=1
	tsa_entry 0x074, hflip=1
	tsa_entry 0x073, hflip=1
	tsa_entry 0x072, hflip=1
	tsa_entry 0x071, hflip=1
	tsa_entry 0x070, hflip=1
	tsa_entry 0x06F, hflip=1
	tsa_entry 0x06E, hflip=1
	tsa_entry 0x06D, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x04C, hflip=1
	tsa_entry 0x04B, hflip=1
	tsa_entry 0x04A, hflip=1
	tsa_entry 0x049, hflip=1
	tsa_entry 0x048, hflip=1
	tsa_entry 0x047, hflip=1
	tsa_entry 0x046, hflip=1
	tsa_entry 0x045, hflip=1
	tsa_entry 0x044, hflip=1
	tsa_entry 0x043, hflip=1
	tsa_entry 0x042, hflip=1
	tsa_entry 0x041, hflip=1
	tsa_entry 0x040, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x06C, hflip=1
	tsa_entry 0x06B, hflip=1
	tsa_entry 0x06A, hflip=1
	tsa_entry 0x069, hflip=1
	tsa_entry 0x068, hflip=1
	tsa_entry 0x067, hflip=1
	tsa_entry 0x066, hflip=1
	tsa_entry 0x065, hflip=1
	tsa_entry 0x064, hflip=1
	tsa_entry 0x063, hflip=1
	tsa_entry 0x062, hflip=1
	tsa_entry 0x061, hflip=1
	tsa_entry 0x060, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x000
