"""Small committed public inventory/summary for the ``terrainstats`` table.

Deliberately not "bulky C" -- just symbol/field/mobility metadata and a
dependency digest, so it is cheap to review in a diff and cheap to
drift-check (see ``supports/inventory.py`` for the same convention).
"""

from __future__ import annotations

from .schema import SCHEMA_ID, dependency_graph


def build_inventory(records):
    graph = dependency_graph()
    lines = []
    lines.append("# Generated-data inventory: terrainstats\n")
    lines.append("\n")
    lines.append("_Auto-generated by `python3 -m scripts.generated_data generate --table terrainstats`. "
                  "Do not edit by hand -- see docs/generated_data.md._\n")
    lines.append("\n")
    lines.append("- Schema: `{}`\n".format(SCHEMA_ID))
    lines.append("- Array count: {}\n".format(len(records)))
    lines.append("- Dependencies: {}\n".format(", ".join(graph.nodes())))
    lines.append("- Dependency graph digest (sha256): `{}`\n".format(graph.digest()))
    lines.append("\n")
    lines.append("| Symbol | Field | Mobility | Terrain entries |\n")
    lines.append("|---|---|---|---|\n")
    for record in sorted(records, key=lambda r: r.symbol):
        lines.append(
            "| {} | {} | {} | {} |\n".format(
                record.symbol, record.field, record.mobility or "-", len(record.values)
            )
        )
    return "".join(lines)
