"""Small committed public inventory/summary for the ``supports`` table.

Deliberately not "bulky C" -- just IDs, counts, and a dependency digest, so
it is cheap to review in a diff and cheap to drift-check.
"""

from __future__ import annotations

from .schema import SCHEMA_ID, dependency_graph


def build_inventory(records):
    graph = dependency_graph()
    lines = []
    lines.append("# Generated-data inventory: supports\n")
    lines.append("\n")
    lines.append("_Auto-generated by `python3 -m scripts.generated_data generate --table supports`. "
                  "Do not edit by hand -- see docs/generated_data.md._\n")
    lines.append("\n")
    lines.append("- Schema: `{}`\n".format(SCHEMA_ID))
    lines.append("- Record count: {}\n".format(len(records)))
    lines.append("- Dependencies: {}\n".format(", ".join(graph.nodes())))
    lines.append("- Dependency graph digest (sha256): `{}`\n".format(graph.digest()))
    lines.append("\n")
    lines.append("| Owner | Symbol | Partner count |\n")
    lines.append("|---|---|---|\n")
    for record in sorted(records, key=lambda r: r.owner):
        lines.append("| {} | {} | {} |\n".format(record.owner, record.symbol, record.support_count))
    return "".join(lines)
