"""Small committed public inventory/summary for the ``weapontriangle``
table.

Deliberately not "bulky C" -- just rule/group metadata and a dependency
digest, so it is cheap to review in a diff and cheap to drift-check (see
``movecost/inventory.py`` for the same convention).
"""

from __future__ import annotations

from .schema import EXPECTED_RULE_COUNT, GROUPS, SCHEMA_ID, dependency_graph


def build_inventory(records):
    graph = dependency_graph()
    lines = []
    lines.append("# Generated-data inventory: weapontriangle\n")
    lines.append("\n")
    lines.append("_Auto-generated by `python3 -m scripts.generated_data generate --table weapontriangle`. "
                  "Do not edit by hand -- see docs/generated_data.md._\n")
    lines.append("\n")
    lines.append("- Schema: `{}`\n".format(SCHEMA_ID))
    lines.append("- Rule count: {} (expected {})\n".format(len(records), EXPECTED_RULE_COUNT))
    lines.append("- Groups: physical {}, magic {}\n".format(GROUPS[0], GROUPS[1]))
    lines.append("- Dependencies: {}\n".format(", ".join(graph.nodes())))
    lines.append("- Dependency graph digest (sha256): `{}`\n".format(graph.digest()))
    lines.append("\n")
    lines.append("| Attacker | Defender | Hit Bonus | Atk Bonus |\n")
    lines.append("|---|---|---|---|\n")
    for record in records:
        lines.append(
            "| {} | {} | {} | {} |\n".format(
                record.attacker, record.defender, record.hit_bonus, record.atk_bonus
            )
        )
    return "".join(lines)
