"""Small committed public inventory/summary for the ``eventlists`` table."""

from __future__ import annotations

from .schema import SCHEMA_ID, dependency_graph


def build_inventory(records):
    graph = dependency_graph()
    lines = []
    lines.append("# Generated-data inventory: eventlists\n")
    lines.append("\n")
    lines.append(
        "_Auto-generated by `python3 -m scripts.generated_data generate --table eventlists`. "
        "Do not edit by hand -- see docs/generated_data.md._\n"
    )
    lines.append("\n")
    lines.append("- Schema: `{}`\n".format(SCHEMA_ID))
    lines.append("- Event list count: {}\n".format(len(records.lists)))
    lines.append("- Tutorial entry count: {}\n".format(len(records.tutorial.entries)))
    lines.append("- Manifest symbol: `{}`\n".format(records.manifest.symbol))
    lines.append("- Dependencies: {}\n".format(", ".join(graph.nodes())))
    lines.append("- Dependency graph digest (sha256): `{}`\n".format(graph.digest()))
    lines.append("\n")
    lines.append("| List field | Symbol | Entry count |\n")
    lines.append("|---|---|---|\n")
    for lst in records.lists:
        lines.append("| {} | {} | {} |\n".format(lst.field, lst.symbol, len(lst.entries)))
    lines.append(
        "| {} | {} | {} |\n".format(
            records.tutorial.field, records.tutorial.symbol, len(records.tutorial.entries)
        )
    )
    lines.append("\n")
    lines.append("| Manifest field | Value |\n")
    lines.append("|---|---|\n")
    for field_name, field in records.manifest.fields.items():
        lines.append("| {} | {} |\n".format(field_name, field.value if field.value is not None else "NULL"))
    return "".join(lines)
