"""Small committed public inventory/summary for the ``movecost`` table.

Deliberately not "bulky C" -- just profile/slot/symbol metadata and a
dependency digest, so it is cheap to review in a diff and cheap to
drift-check (see ``supports/inventory.py`` for the same convention).
"""

from __future__ import annotations

from .schema import SLOT_NAMES, SCHEMA_ID, dependency_graph


def build_inventory(records):
    graph = dependency_graph()
    lines = []
    lines.append("# Generated-data inventory: movecost\n")
    lines.append("\n")
    lines.append("_Auto-generated by `python3 -m scripts.generated_data generate --table movecost`. "
                  "Do not edit by hand -- see docs/generated_data.md._\n")
    lines.append("\n")
    lines.append("- Schema: `{}`\n".format(SCHEMA_ID))
    lines.append("- Profile count: {}\n".format(len(records)))
    array_count = sum(1 for r in records for _ in r.symbols())
    lines.append("- Array count: {}\n".format(array_count))
    lines.append("- Dependencies: {}\n".format(", ".join(graph.nodes())))
    lines.append("- Dependency graph digest (sha256): `{}`\n".format(graph.digest()))
    lines.append("\n")
    lines.append("| Profile | Normal | Rain | Snow |\n")
    lines.append("|---|---|---|---|\n")
    for record in sorted(records, key=lambda r: r.profile):
        cells = []
        for slot_name in SLOT_NAMES:
            slot = record.slots.get(slot_name)
            cells.append(slot.symbol if slot is not None else "-")
        lines.append("| {} | {} | {} | {} |\n".format(record.profile, *cells))
    return "".join(lines)
