	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x300, hflip=1, vflip=1
	tsa_entry 0x000, pal=15
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x30F, hflip=1, vflip=1
	tsa_entry 0x300, hflip=1, vflip=1
	tsa_entry 0x000, pal=15
	tsa_entry 0x000, pal=15
	tsa_entry 0x0E0
	tsa_entry 0x0E0
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x00E, pal=13
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000, pal=15
	tsa_entry 0x0F0
	tsa_entry 0x00F
	tsa_entry 0x000, pal=14
	tsa_entry 0x200, hflip=1, vflip=1
	tsa_entry 0x00E
	tsa_entry 0x00E
	tsa_entry 0x100, hflip=1, vflip=1
	tsa_entry 0x000, pal=13
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000, pal=15
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x0F0
	tsa_entry 0x300, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000, pal=13
	tsa_entry 0x0F0
	tsa_entry 0x00E
	tsa_entry 0x300, hflip=1, vflip=1
	tsa_entry 0x0E0
	tsa_entry 0x000
	tsa_entry 0x00E, pal=13
	tsa_entry 0x0E0, pal=14
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x100, hflip=1, vflip=1
	tsa_entry 0x100, hflip=1, vflip=1
	tsa_entry 0x00D
	tsa_entry 0x00D, pal=12
	tsa_entry 0x0C0
	tsa_entry 0x000, hflip=1, vflip=1
	tsa_entry 0x000, pal=11
	tsa_entry 0x000
	tsa_entry 0x00B
	tsa_entry 0x10E, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x00D, hflip=1, vflip=1
	tsa_entry 0x00D, hflip=1, vflip=1
	tsa_entry 0x000, pal=12
	tsa_entry 0x000, pal=12
	tsa_entry 0x000
	tsa_entry 0x0C0
	tsa_entry 0x0B0
	tsa_entry 0x300, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000, pal=10
	tsa_entry 0x0A0
	tsa_entry 0x00A
	tsa_entry 0x000, hflip=1, vflip=1
	tsa_entry 0x0C0
	tsa_entry 0x000
	tsa_entry 0x00C, pal=12
	tsa_entry 0x0C0, pal=11
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x300, vflip=1
	tsa_entry 0x200, vflip=1
	tsa_entry 0x00A
	tsa_entry 0x00A, pal=10
	tsa_entry 0x0A0
	tsa_entry 0x100, vflip=1
	tsa_entry 0x000, pal=9
	tsa_entry 0x000
	tsa_entry 0x009
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x300, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x0F0
	tsa_entry 0x000
	tsa_entry 0x000, pal=14
	tsa_entry 0x300, hflip=1, vflip=1
	tsa_entry 0x00F
	tsa_entry 0x000
	tsa_entry 0x200, hflip=1, vflip=1
	tsa_entry 0x000, pal=14
	tsa_entry 0x000
	tsa_entry 0x00F
	tsa_entry 0x000, pal=12
	tsa_entry 0x200, hflip=1, vflip=1
	tsa_entry 0x00D
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x00C, hflip=1, vflip=1
	tsa_entry 0x10D, hflip=1, vflip=1
	tsa_entry 0x000, pal=11
	tsa_entry 0x000, pal=12
	tsa_entry 0x0B0
	tsa_entry 0x0C0
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x00B, pal=10
	tsa_entry 0x000
	tsa_entry 0x00B
	tsa_entry 0x300, vflip=1
	tsa_entry 0x200, vflip=1
	tsa_entry 0x00B
	tsa_entry 0x000
	tsa_entry 0x000, pal=10
	tsa_entry 0x090
	tsa_entry 0x00B
	tsa_entry 0x000, pal=8
	tsa_entry 0x100, vflip=1
	tsa_entry 0x009
	tsa_entry 0x00A
	tsa_entry 0x000, vflip=1
	tsa_entry 0x000, pal=8
	tsa_entry 0x000
	tsa_entry 0x00A
	tsa_entry 0x000, pal=9
	tsa_entry 0x100, vflip=1
	tsa_entry 0x009
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x308, hflip=1
	tsa_entry 0x008, vflip=1
	tsa_entry 0x000, pal=7
	tsa_entry 0x000, pal=7
	tsa_entry 0x070
	tsa_entry 0x070
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x006, pal=5
	tsa_entry 0x000
	tsa_entry 0x008
	tsa_entry 0x000, vflip=1
	tsa_entry 0x000, vflip=1
	tsa_entry 0x008
	tsa_entry 0x000
	tsa_entry 0x000, pal=7
	tsa_entry 0x070
	tsa_entry 0x007
	tsa_entry 0x000, pal=6
	tsa_entry 0x200, hflip=1
	tsa_entry 0x006
	tsa_entry 0x006
	tsa_entry 0x100, hflip=1
	tsa_entry 0x000, pal=5
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000, pal=15
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000, pal=15
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x300, hflip=1, vflip=1
	tsa_entry 0x0D0
	tsa_entry 0x000
	tsa_entry 0x00D, pal=12
	tsa_entry 0x0E0, pal=14
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000, hflip=1, vflip=1
	tsa_entry 0x200, hflip=1, vflip=1
	tsa_entry 0x00D
	tsa_entry 0x00E, pal=13
	tsa_entry 0x0C0
	tsa_entry 0x100, hflip=1, vflip=1
	tsa_entry 0x000, pal=11
	tsa_entry 0x000
	tsa_entry 0x00C
	tsa_entry 0x30C, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x10A, vflip=1
	tsa_entry 0x30C, vflip=1
	tsa_entry 0x000, pal=9
	tsa_entry 0x000, pal=10
	tsa_entry 0x000
	tsa_entry 0x0B0
	tsa_entry 0x090
	tsa_entry 0x200, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000, pal=7
	tsa_entry 0x0A0
	tsa_entry 0x008
	tsa_entry 0x000, vflip=1
	tsa_entry 0x070
	tsa_entry 0x000
	tsa_entry 0x007, pal=6
	tsa_entry 0x080, pal=7
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x200, hflip=1
	tsa_entry 0x300, hflip=1
	tsa_entry 0x006
	tsa_entry 0x007, pal=6
	tsa_entry 0x050
	tsa_entry 0x200, hflip=1
	tsa_entry 0x000, pal=4
	tsa_entry 0x000
	tsa_entry 0x005
	tsa_entry 0x207, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x105, hflip=1
	tsa_entry 0x106, hflip=1
	tsa_entry 0x000, pal=4
	tsa_entry 0x000, pal=4
	tsa_entry 0x000
	tsa_entry 0x050
	tsa_entry 0x040
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000, pal=2
	tsa_entry 0x030
	tsa_entry 0x002
	tsa_entry 0x100, hflip=1
	tsa_entry 0x040
	tsa_entry 0x000
	tsa_entry 0x004, pal=4
	tsa_entry 0x040, pal=3
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x300
	tsa_entry 0x300
	tsa_entry 0x002
	tsa_entry 0x002, pal=2
	tsa_entry 0x020
	tsa_entry 0x200
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000, pal=14
	tsa_entry 0x000
	tsa_entry 0x00F
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x20F, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000, pal=14
	tsa_entry 0x000, pal=15
	tsa_entry 0x0E0
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x00F, pal=13
	tsa_entry 0x000
	tsa_entry 0x00C
	tsa_entry 0x100, hflip=1, vflip=1
	tsa_entry 0x300, vflip=1
	tsa_entry 0x00D
	tsa_entry 0x000
	tsa_entry 0x000, pal=12
	tsa_entry 0x0B0
	tsa_entry 0x00D
	tsa_entry 0x000, pal=10
	tsa_entry 0x000, hflip=1, vflip=1
	tsa_entry 0x00B
	tsa_entry 0x00D
	tsa_entry 0x200, vflip=1
	tsa_entry 0x000, pal=11
	tsa_entry 0x000
	tsa_entry 0x00A
	tsa_entry 0x000, pal=7
	tsa_entry 0x100, vflip=1
	tsa_entry 0x008
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x308, hflip=1
	tsa_entry 0x009, vflip=1
	tsa_entry 0x000, pal=6
	tsa_entry 0x000, pal=8
	tsa_entry 0x070
	tsa_entry 0x080
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x007, pal=5
	tsa_entry 0x000
	tsa_entry 0x005
	tsa_entry 0x100, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x006
	tsa_entry 0x000
	tsa_entry 0x000, pal=4
	tsa_entry 0x040
	tsa_entry 0x006
	tsa_entry 0x000, pal=2
	tsa_entry 0x000, hflip=1
	tsa_entry 0x004
	tsa_entry 0x005
	tsa_entry 0x200
	tsa_entry 0x000, pal=4
	tsa_entry 0x000
	tsa_entry 0x003
	tsa_entry 0x000
	tsa_entry 0x200
	tsa_entry 0x002
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x002
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x10E, hflip=1, vflip=1
	tsa_entry 0x300, hflip=1, vflip=1
	tsa_entry 0x000, pal=13
	tsa_entry 0x000, pal=15
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x0E0
	tsa_entry 0x300, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000, pal=13
	tsa_entry 0x000
	tsa_entry 0x00E
	tsa_entry 0x000, hflip=1, vflip=1
	tsa_entry 0x0A0
	tsa_entry 0x000
	tsa_entry 0x00B, pal=9
	tsa_entry 0x0C0, pal=11
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x100, vflip=1
	tsa_entry 0x300, vflip=1
	tsa_entry 0x00A
	tsa_entry 0x00C, pal=11
	tsa_entry 0x0A0
	tsa_entry 0x300, vflip=1
	tsa_entry 0x000, pal=9
	tsa_entry 0x000
	tsa_entry 0x00A
	tsa_entry 0x009, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x207, hflip=1
	tsa_entry 0x308, hflip=1
	tsa_entry 0x000, pal=5
	tsa_entry 0x000, pal=7
	tsa_entry 0x000
	tsa_entry 0x080
	tsa_entry 0x060
	tsa_entry 0x300, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000, pal=5
	tsa_entry 0x080
	tsa_entry 0x006
	tsa_entry 0x000, hflip=1
	tsa_entry 0x020
	tsa_entry 0x000
	tsa_entry 0x003
	tsa_entry 0x040, pal=3
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x300
	tsa_entry 0x002
	tsa_entry 0x004, pal=3
	tsa_entry 0x020
	tsa_entry 0x300
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x002
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
