	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x0F1, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x008
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x0D1, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x028
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x0B1, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x003, hflip=1
	tsa_entry 0x032, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x008, hflip=1
	tsa_entry 0x007, hflip=1
	tsa_entry 0x006, hflip=1
	tsa_entry 0x005, hflip=1
	tsa_entry 0x004, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x002, hflip=1
	tsa_entry 0x001, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x012, vflip=1
	tsa_entry 0x013, vflip=1
	tsa_entry 0x014, vflip=1
	tsa_entry 0x0EC, vflip=1
	tsa_entry 0x0ED, vflip=1
	tsa_entry 0x0EE, vflip=1
	tsa_entry 0x0EF, vflip=1
	tsa_entry 0x0F0, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x028, hflip=1
	tsa_entry 0x027, hflip=1
	tsa_entry 0x026, hflip=1
	tsa_entry 0x025, hflip=1
	tsa_entry 0x024, hflip=1
	tsa_entry 0x023, hflip=1
	tsa_entry 0x022, hflip=1
	tsa_entry 0x021, hflip=1
	tsa_entry 0x020, hflip=1
	tsa_entry 0x0C9, vflip=1
	tsa_entry 0x0CA, vflip=1
	tsa_entry 0x0CB, vflip=1
	tsa_entry 0x0CC, vflip=1
	tsa_entry 0x0CD, vflip=1
	tsa_entry 0x0CE, vflip=1
	tsa_entry 0x0CF, vflip=1
	tsa_entry 0x0D0, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x048, hflip=1
	tsa_entry 0x047, hflip=1
	tsa_entry 0x046, hflip=1
	tsa_entry 0x045, hflip=1
	tsa_entry 0x044, hflip=1
	tsa_entry 0x043, hflip=1
	tsa_entry 0x042, hflip=1
	tsa_entry 0x041, hflip=1
	tsa_entry 0x040, hflip=1
	tsa_entry 0x0A9, vflip=1
	tsa_entry 0x0AA, vflip=1
	tsa_entry 0x0AB, vflip=1
	tsa_entry 0x0AC, vflip=1
	tsa_entry 0x0AD, vflip=1
	tsa_entry 0x0AE, vflip=1
	tsa_entry 0x0AF, vflip=1
	tsa_entry 0x0B0, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x068, hflip=1
	tsa_entry 0x067, hflip=1
	tsa_entry 0x066, hflip=1
	tsa_entry 0x065, hflip=1
	tsa_entry 0x064, hflip=1
	tsa_entry 0x063, hflip=1
	tsa_entry 0x062, hflip=1
	tsa_entry 0x061, hflip=1
	tsa_entry 0x060, hflip=1
	tsa_entry 0x089, vflip=1
	tsa_entry 0x08A, vflip=1
	tsa_entry 0x08B, vflip=1
	tsa_entry 0x08C, vflip=1
	tsa_entry 0x08D, vflip=1
	tsa_entry 0x08E, vflip=1
	tsa_entry 0x08F, vflip=1
	tsa_entry 0x090, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x088, hflip=1
	tsa_entry 0x087, hflip=1
	tsa_entry 0x086, hflip=1
	tsa_entry 0x085, hflip=1
	tsa_entry 0x084, hflip=1
	tsa_entry 0x083, hflip=1
	tsa_entry 0x082, hflip=1
	tsa_entry 0x081, hflip=1
	tsa_entry 0x080, hflip=1
	tsa_entry 0x069, vflip=1
	tsa_entry 0x06A, vflip=1
	tsa_entry 0x06B, vflip=1
	tsa_entry 0x06C, vflip=1
	tsa_entry 0x06D, vflip=1
	tsa_entry 0x06E, vflip=1
	tsa_entry 0x06F, vflip=1
	tsa_entry 0x070, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x0A8, hflip=1
	tsa_entry 0x0A7, hflip=1
	tsa_entry 0x0A6, hflip=1
	tsa_entry 0x0A5, hflip=1
	tsa_entry 0x0A4, hflip=1
	tsa_entry 0x0A3, hflip=1
	tsa_entry 0x0A2, hflip=1
	tsa_entry 0x0A1, hflip=1
	tsa_entry 0x0A0, hflip=1
	tsa_entry 0x049, vflip=1
	tsa_entry 0x04A, vflip=1
	tsa_entry 0x04B, vflip=1
	tsa_entry 0x04C, vflip=1
	tsa_entry 0x04D, vflip=1
	tsa_entry 0x04E, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x050, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x0C8, hflip=1
	tsa_entry 0x0C7, hflip=1
	tsa_entry 0x0C6, hflip=1
	tsa_entry 0x0C5, hflip=1
	tsa_entry 0x0C4, hflip=1
	tsa_entry 0x0C3, hflip=1
	tsa_entry 0x0C2, hflip=1
	tsa_entry 0x0C1, hflip=1
	tsa_entry 0x0C0, hflip=1
	tsa_entry 0x029, vflip=1
	tsa_entry 0x02A, vflip=1
	tsa_entry 0x02B, vflip=1
	tsa_entry 0x02C, vflip=1
	tsa_entry 0x02D, vflip=1
	tsa_entry 0x02E, vflip=1
	tsa_entry 0x02F, vflip=1
	tsa_entry 0x030, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x0E8, hflip=1
	tsa_entry 0x0E7, hflip=1
	tsa_entry 0x0E6, hflip=1
	tsa_entry 0x0E5, hflip=1
	tsa_entry 0x0E4, hflip=1
	tsa_entry 0x0E3, hflip=1
	tsa_entry 0x0E2, hflip=1
	tsa_entry 0x0E1, hflip=1
	tsa_entry 0x0E0, hflip=1
	tsa_entry 0x009, vflip=1
	tsa_entry 0x00A, vflip=1
	tsa_entry 0x00B, vflip=1
	tsa_entry 0x00C, vflip=1
	tsa_entry 0x00D, vflip=1
	tsa_entry 0x00E, vflip=1
	tsa_entry 0x00F, vflip=1
	tsa_entry 0x010, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x011, hflip=1
	tsa_entry 0x010, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x00E, hflip=1
	tsa_entry 0x00D, hflip=1
	tsa_entry 0x00C, hflip=1
	tsa_entry 0x00B, hflip=1
	tsa_entry 0x00A, hflip=1
	tsa_entry 0x009, hflip=1
	tsa_entry 0x0E0, vflip=1
	tsa_entry 0x0E1, vflip=1
	tsa_entry 0x0E2, vflip=1
	tsa_entry 0x0E3, vflip=1
	tsa_entry 0x0E4, vflip=1
	tsa_entry 0x0E5, vflip=1
	tsa_entry 0x0E6, vflip=1
	tsa_entry 0x0E7, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x031, hflip=1
	tsa_entry 0x030, hflip=1
	tsa_entry 0x02F, hflip=1
	tsa_entry 0x02E, hflip=1
	tsa_entry 0x02D, hflip=1
	tsa_entry 0x02C, hflip=1
	tsa_entry 0x02B, hflip=1
	tsa_entry 0x02A, hflip=1
	tsa_entry 0x029, hflip=1
	tsa_entry 0x0C0, vflip=1
	tsa_entry 0x0C1, vflip=1
	tsa_entry 0x0C2, vflip=1
	tsa_entry 0x0C3, vflip=1
	tsa_entry 0x0C4, vflip=1
	tsa_entry 0x0C5, vflip=1
	tsa_entry 0x0C6, vflip=1
	tsa_entry 0x0C7, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x051, hflip=1
	tsa_entry 0x050, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04E, hflip=1
	tsa_entry 0x04D, hflip=1
	tsa_entry 0x04C, hflip=1
	tsa_entry 0x04B, hflip=1
	tsa_entry 0x04A, hflip=1
	tsa_entry 0x049, hflip=1
	tsa_entry 0x0A0, vflip=1
	tsa_entry 0x0A1, vflip=1
	tsa_entry 0x0A2, vflip=1
	tsa_entry 0x0A3, vflip=1
	tsa_entry 0x0A4, vflip=1
	tsa_entry 0x0A5, vflip=1
	tsa_entry 0x0A6, vflip=1
	tsa_entry 0x0A7, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x071, hflip=1
	tsa_entry 0x070, hflip=1
	tsa_entry 0x06F, hflip=1
	tsa_entry 0x06E, hflip=1
	tsa_entry 0x06D, hflip=1
	tsa_entry 0x06C, hflip=1
	tsa_entry 0x06B, hflip=1
	tsa_entry 0x06A, hflip=1
	tsa_entry 0x069, hflip=1
	tsa_entry 0x080, vflip=1
	tsa_entry 0x081, vflip=1
	tsa_entry 0x082, vflip=1
	tsa_entry 0x083, vflip=1
	tsa_entry 0x084, vflip=1
	tsa_entry 0x085, vflip=1
	tsa_entry 0x086, vflip=1
	tsa_entry 0x087, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x091, hflip=1
	tsa_entry 0x090, hflip=1
	tsa_entry 0x08F, hflip=1
	tsa_entry 0x08E, hflip=1
	tsa_entry 0x08D, hflip=1
	tsa_entry 0x08C, hflip=1
	tsa_entry 0x08B, hflip=1
	tsa_entry 0x08A, hflip=1
	tsa_entry 0x089, hflip=1
	tsa_entry 0x060, vflip=1
	tsa_entry 0x061, vflip=1
	tsa_entry 0x062, vflip=1
	tsa_entry 0x063, vflip=1
	tsa_entry 0x064, vflip=1
	tsa_entry 0x065, vflip=1
	tsa_entry 0x066, vflip=1
	tsa_entry 0x067, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x0B1, hflip=1
	tsa_entry 0x0B0, hflip=1
	tsa_entry 0x0AF, hflip=1
	tsa_entry 0x0AE, hflip=1
	tsa_entry 0x0AD, hflip=1
	tsa_entry 0x0AC, hflip=1
	tsa_entry 0x0AB, hflip=1
	tsa_entry 0x0AA, hflip=1
	tsa_entry 0x0A9, hflip=1
	tsa_entry 0x040, vflip=1
	tsa_entry 0x041, vflip=1
	tsa_entry 0x042, vflip=1
	tsa_entry 0x043, vflip=1
	tsa_entry 0x044, vflip=1
	tsa_entry 0x045, vflip=1
	tsa_entry 0x046, vflip=1
	tsa_entry 0x047, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x0D1, hflip=1
	tsa_entry 0x0D0, hflip=1
	tsa_entry 0x0CF, hflip=1
	tsa_entry 0x0CE, hflip=1
	tsa_entry 0x0CD, hflip=1
	tsa_entry 0x0CC, hflip=1
	tsa_entry 0x0CB, hflip=1
	tsa_entry 0x0CA, hflip=1
	tsa_entry 0x0C9, hflip=1
	tsa_entry 0x020, vflip=1
	tsa_entry 0x021, vflip=1
	tsa_entry 0x022, vflip=1
	tsa_entry 0x023, vflip=1
	tsa_entry 0x024, vflip=1
	tsa_entry 0x025, vflip=1
	tsa_entry 0x026, vflip=1
	tsa_entry 0x027, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x0F1, hflip=1
	tsa_entry 0x0F0, hflip=1
	tsa_entry 0x0EF, hflip=1
	tsa_entry 0x0EE, hflip=1
	tsa_entry 0x0ED, hflip=1
	tsa_entry 0x0EC, hflip=1
	tsa_entry 0x014, hflip=1
	tsa_entry 0x013, hflip=1
	tsa_entry 0x012, hflip=1
	tsa_entry 0x000, vflip=1
	tsa_entry 0x001, vflip=1
	tsa_entry 0x002, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x004, vflip=1
	tsa_entry 0x005, vflip=1
	tsa_entry 0x006, vflip=1
	tsa_entry 0x007, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x034, hflip=1
	tsa_entry 0x033, hflip=1
	tsa_entry 0x032, hflip=1
	tsa_entry 0x003, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
