	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x008, hflip=1
	tsa_entry 0x007, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x006, hflip=1
	tsa_entry 0x005, hflip=1
	tsa_entry 0x004, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x003, hflip=1
	tsa_entry 0x002, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x001, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x000
	tsa_entry 0x001
	tsa_entry 0x01F
	tsa_entry 0x002
	tsa_entry 0x003
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x07E, hflip=1
	tsa_entry 0x01E, hflip=1
	tsa_entry 0x01D, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01C, hflip=1
	tsa_entry 0x01B, hflip=1
	tsa_entry 0x01A, hflip=1
	tsa_entry 0x019, hflip=1
	tsa_entry 0x018, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x017, hflip=1
	tsa_entry 0x016, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x015, hflip=1
	tsa_entry 0x014, hflip=1
	tsa_entry 0x014
	tsa_entry 0x015
	tsa_entry 0x01F
	tsa_entry 0x016
	tsa_entry 0x017
	tsa_entry 0x01F
	tsa_entry 0x018
	tsa_entry 0x019
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x031, hflip=1
	tsa_entry 0x030, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x02F, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x02E, hflip=1
	tsa_entry 0x02D, hflip=1
	tsa_entry 0x02C, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x02B, hflip=1
	tsa_entry 0x02A, hflip=1
	tsa_entry 0x02A
	tsa_entry 0x02B
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x02C
	tsa_entry 0x02D
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x03F, hflip=1
	tsa_entry 0x03E, hflip=1
	tsa_entry 0x03D, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x03C, hflip=1
	tsa_entry 0x03B, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x03B
	tsa_entry 0x03C
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x04D, hflip=1
	tsa_entry 0x04C, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x04B, hflip=1
	tsa_entry 0x04A, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x049, hflip=1
	tsa_entry 0x048, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x048
	tsa_entry 0x049
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x05C, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x05B, hflip=1
	tsa_entry 0x05A, hflip=1
	tsa_entry 0x059, hflip=1
	tsa_entry 0x058, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x057, hflip=1
	tsa_entry 0x031
	tsa_entry 0x031, hflip=1
	tsa_entry 0x057
	tsa_entry 0x01F
	tsa_entry 0x058
	tsa_entry 0x059
	tsa_entry 0x05A
	tsa_entry 0x05B
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x069, hflip=1
	tsa_entry 0x068, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x067, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x066, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x065, hflip=1
	tsa_entry 0x037
	tsa_entry 0x037, hflip=1
	tsa_entry 0x065
	tsa_entry 0x01F
	tsa_entry 0x066
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x067
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x073, hflip=1
	tsa_entry 0x072, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x071, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x071
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x00A, hflip=1
	tsa_entry 0x009, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x06E, hflip=1
	tsa_entry 0x06D, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x06B, hflip=1
	tsa_entry 0x06A, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x064, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x064, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x06A
	tsa_entry 0x06B
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x079, hflip=1
	tsa_entry 0x078, hflip=1
	tsa_entry 0x077, hflip=1
	tsa_entry 0x076, hflip=1
	tsa_entry 0x075, hflip=1
	tsa_entry 0x074, hflip=1
	tsa_entry 0x074
	tsa_entry 0x075
	tsa_entry 0x076
	tsa_entry 0x077
	tsa_entry 0x078
	tsa_entry 0x079
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x079, hflip=1, vflip=1
	tsa_entry 0x078, hflip=1, vflip=1
	tsa_entry 0x077, hflip=1, vflip=1
	tsa_entry 0x076, hflip=1, vflip=1
	tsa_entry 0x075, hflip=1, vflip=1
	tsa_entry 0x074, hflip=1, vflip=1
	tsa_entry 0x074, vflip=1
	tsa_entry 0x075, vflip=1
	tsa_entry 0x076, vflip=1
	tsa_entry 0x077, vflip=1
	tsa_entry 0x078, vflip=1
	tsa_entry 0x079, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x00A, hflip=1, vflip=1
	tsa_entry 0x009, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x06E, hflip=1, vflip=1
	tsa_entry 0x06D, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x06B, hflip=1, vflip=1
	tsa_entry 0x06A, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x064
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x064, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x06A, vflip=1
	tsa_entry 0x06B, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x073, hflip=1, vflip=1
	tsa_entry 0x072, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x071, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x071, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x069, hflip=1, vflip=1
	tsa_entry 0x068, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x067, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x066, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x065, hflip=1, vflip=1
	tsa_entry 0x037, vflip=1
	tsa_entry 0x037, hflip=1, vflip=1
	tsa_entry 0x065, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x066, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x067, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x05C, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x05B, hflip=1, vflip=1
	tsa_entry 0x05A, hflip=1, vflip=1
	tsa_entry 0x059, hflip=1, vflip=1
	tsa_entry 0x058, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x057, hflip=1, vflip=1
	tsa_entry 0x031, vflip=1
	tsa_entry 0x031, hflip=1, vflip=1
	tsa_entry 0x057, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x058, vflip=1
	tsa_entry 0x059, vflip=1
	tsa_entry 0x05A, vflip=1
	tsa_entry 0x05B, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x04D, hflip=1, vflip=1
	tsa_entry 0x04C, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x04B, hflip=1, vflip=1
	tsa_entry 0x04A, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x049, hflip=1, vflip=1
	tsa_entry 0x048, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x048, vflip=1
	tsa_entry 0x049, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x03F, hflip=1, vflip=1
	tsa_entry 0x03E, hflip=1, vflip=1
	tsa_entry 0x03D, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x03C, hflip=1, vflip=1
	tsa_entry 0x03B, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x03B, vflip=1
	tsa_entry 0x03C, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x031, hflip=1, vflip=1
	tsa_entry 0x030, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x02F, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x02E, hflip=1, vflip=1
	tsa_entry 0x02D, hflip=1, vflip=1
	tsa_entry 0x02C, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x02B, hflip=1, vflip=1
	tsa_entry 0x02A, hflip=1, vflip=1
	tsa_entry 0x02A, vflip=1
	tsa_entry 0x02B, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x02C, vflip=1
	tsa_entry 0x02D, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x07E, hflip=1, vflip=1
	tsa_entry 0x01E, hflip=1, vflip=1
	tsa_entry 0x01D, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01C, hflip=1, vflip=1
	tsa_entry 0x01B, hflip=1, vflip=1
	tsa_entry 0x01A, hflip=1, vflip=1
	tsa_entry 0x019, hflip=1, vflip=1
	tsa_entry 0x018, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x017, hflip=1, vflip=1
	tsa_entry 0x016, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x015, hflip=1, vflip=1
	tsa_entry 0x014, hflip=1, vflip=1
	tsa_entry 0x014, vflip=1
	tsa_entry 0x015, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x016, vflip=1
	tsa_entry 0x017, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x018, vflip=1
	tsa_entry 0x019, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x008, hflip=1, vflip=1
	tsa_entry 0x007, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x006, hflip=1, vflip=1
	tsa_entry 0x005, hflip=1, vflip=1
	tsa_entry 0x004, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x003, hflip=1, vflip=1
	tsa_entry 0x002, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x001, hflip=1, vflip=1
	tsa_entry 0x000, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x000, vflip=1
	tsa_entry 0x001, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x002, vflip=1
	tsa_entry 0x003, vflip=1
