	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F, hflip=1
	tsa_entry 0x01E, hflip=1
	tsa_entry 0x01D, hflip=1
	tsa_entry 0x01C, hflip=1
	tsa_entry 0x01B, hflip=1
	tsa_entry 0x01A, hflip=1
	tsa_entry 0x019, hflip=1
	tsa_entry 0x018, hflip=1
	tsa_entry 0x0F0, vflip=1
	tsa_entry 0x0F1, vflip=1
	tsa_entry 0x0F2, vflip=1
	tsa_entry 0x0F3, vflip=1
	tsa_entry 0x0F4, vflip=1
	tsa_entry 0x0F5, vflip=1
	tsa_entry 0x0F6, vflip=1
	tsa_entry 0x0F7, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x03F, hflip=1
	tsa_entry 0x03E, hflip=1
	tsa_entry 0x03D, hflip=1
	tsa_entry 0x03C, hflip=1
	tsa_entry 0x03B, hflip=1
	tsa_entry 0x03A, hflip=1
	tsa_entry 0x039, hflip=1
	tsa_entry 0x038, hflip=1
	tsa_entry 0x0D0, vflip=1
	tsa_entry 0x0D1, vflip=1
	tsa_entry 0x0D2, vflip=1
	tsa_entry 0x0D3, vflip=1
	tsa_entry 0x0D4, vflip=1
	tsa_entry 0x0D5, vflip=1
	tsa_entry 0x0D6, vflip=1
	tsa_entry 0x0D7, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x05F, hflip=1
	tsa_entry 0x05E, hflip=1
	tsa_entry 0x05D, hflip=1
	tsa_entry 0x05C, hflip=1
	tsa_entry 0x05B, hflip=1
	tsa_entry 0x05A, hflip=1
	tsa_entry 0x059, hflip=1
	tsa_entry 0x058, hflip=1
	tsa_entry 0x0B0, vflip=1
	tsa_entry 0x0B1, vflip=1
	tsa_entry 0x0B2, vflip=1
	tsa_entry 0x0B3, vflip=1
	tsa_entry 0x0B4, vflip=1
	tsa_entry 0x0B5, vflip=1
	tsa_entry 0x0B6, vflip=1
	tsa_entry 0x0B7, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x07F, hflip=1
	tsa_entry 0x07E, hflip=1
	tsa_entry 0x07D, hflip=1
	tsa_entry 0x07C, hflip=1
	tsa_entry 0x07B, hflip=1
	tsa_entry 0x07A, hflip=1
	tsa_entry 0x079, hflip=1
	tsa_entry 0x078, hflip=1
	tsa_entry 0x090, vflip=1
	tsa_entry 0x091, vflip=1
	tsa_entry 0x092, vflip=1
	tsa_entry 0x093, vflip=1
	tsa_entry 0x094, vflip=1
	tsa_entry 0x095, vflip=1
	tsa_entry 0x096, vflip=1
	tsa_entry 0x097, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x09F, hflip=1
	tsa_entry 0x09E, hflip=1
	tsa_entry 0x09D, hflip=1
	tsa_entry 0x09C, hflip=1
	tsa_entry 0x09B, hflip=1
	tsa_entry 0x09A, hflip=1
	tsa_entry 0x099, hflip=1
	tsa_entry 0x098, hflip=1
	tsa_entry 0x070, vflip=1
	tsa_entry 0x071, vflip=1
	tsa_entry 0x072, vflip=1
	tsa_entry 0x073, vflip=1
	tsa_entry 0x074, vflip=1
	tsa_entry 0x075, vflip=1
	tsa_entry 0x076, vflip=1
	tsa_entry 0x077, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x0BF, hflip=1
	tsa_entry 0x0BE, hflip=1
	tsa_entry 0x0BD, hflip=1
	tsa_entry 0x0BC, hflip=1
	tsa_entry 0x0BB, hflip=1
	tsa_entry 0x0BA, hflip=1
	tsa_entry 0x0B9, hflip=1
	tsa_entry 0x0B8, hflip=1
	tsa_entry 0x050, vflip=1
	tsa_entry 0x051, vflip=1
	tsa_entry 0x052, vflip=1
	tsa_entry 0x053, vflip=1
	tsa_entry 0x054, vflip=1
	tsa_entry 0x055, vflip=1
	tsa_entry 0x056, vflip=1
	tsa_entry 0x057, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x0DF, hflip=1
	tsa_entry 0x0DE, hflip=1
	tsa_entry 0x0DD, hflip=1
	tsa_entry 0x0DC, hflip=1
	tsa_entry 0x0DB, hflip=1
	tsa_entry 0x0DA, hflip=1
	tsa_entry 0x0D9, hflip=1
	tsa_entry 0x0D8, hflip=1
	tsa_entry 0x030, vflip=1
	tsa_entry 0x031, vflip=1
	tsa_entry 0x032, vflip=1
	tsa_entry 0x033, vflip=1
	tsa_entry 0x034, vflip=1
	tsa_entry 0x035, vflip=1
	tsa_entry 0x036, vflip=1
	tsa_entry 0x037, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x0FF, hflip=1
	tsa_entry 0x0FE, hflip=1
	tsa_entry 0x0FD, hflip=1
	tsa_entry 0x0FC, hflip=1
	tsa_entry 0x0FB, hflip=1
	tsa_entry 0x0FA, hflip=1
	tsa_entry 0x0F9, hflip=1
	tsa_entry 0x0F8, hflip=1
	tsa_entry 0x010, vflip=1
	tsa_entry 0x011, vflip=1
	tsa_entry 0x012, vflip=1
	tsa_entry 0x013, vflip=1
	tsa_entry 0x014, vflip=1
	tsa_entry 0x015, vflip=1
	tsa_entry 0x016, vflip=1
	tsa_entry 0x017, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x017, hflip=1
	tsa_entry 0x016, hflip=1
	tsa_entry 0x015, hflip=1
	tsa_entry 0x014, hflip=1
	tsa_entry 0x013, hflip=1
	tsa_entry 0x012, hflip=1
	tsa_entry 0x011, hflip=1
	tsa_entry 0x010, hflip=1
	tsa_entry 0x0F8, vflip=1
	tsa_entry 0x0F9, vflip=1
	tsa_entry 0x0FA, vflip=1
	tsa_entry 0x0FB, vflip=1
	tsa_entry 0x0FC, vflip=1
	tsa_entry 0x0FD, vflip=1
	tsa_entry 0x0FE, vflip=1
	tsa_entry 0x0FF, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x037, hflip=1
	tsa_entry 0x036, hflip=1
	tsa_entry 0x035, hflip=1
	tsa_entry 0x034, hflip=1
	tsa_entry 0x033, hflip=1
	tsa_entry 0x032, hflip=1
	tsa_entry 0x031, hflip=1
	tsa_entry 0x030, hflip=1
	tsa_entry 0x0D8, vflip=1
	tsa_entry 0x0D9, vflip=1
	tsa_entry 0x0DA, vflip=1
	tsa_entry 0x0DB, vflip=1
	tsa_entry 0x0DC, vflip=1
	tsa_entry 0x0DD, vflip=1
	tsa_entry 0x0DE, vflip=1
	tsa_entry 0x0DF, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x057, hflip=1
	tsa_entry 0x056, hflip=1
	tsa_entry 0x055, hflip=1
	tsa_entry 0x054, hflip=1
	tsa_entry 0x053, hflip=1
	tsa_entry 0x052, hflip=1
	tsa_entry 0x051, hflip=1
	tsa_entry 0x050, hflip=1
	tsa_entry 0x0B8, vflip=1
	tsa_entry 0x0B9, vflip=1
	tsa_entry 0x0BA, vflip=1
	tsa_entry 0x0BB, vflip=1
	tsa_entry 0x0BC, vflip=1
	tsa_entry 0x0BD, vflip=1
	tsa_entry 0x0BE, vflip=1
	tsa_entry 0x0BF, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x077, hflip=1
	tsa_entry 0x076, hflip=1
	tsa_entry 0x075, hflip=1
	tsa_entry 0x074, hflip=1
	tsa_entry 0x073, hflip=1
	tsa_entry 0x072, hflip=1
	tsa_entry 0x071, hflip=1
	tsa_entry 0x070, hflip=1
	tsa_entry 0x098, vflip=1
	tsa_entry 0x099, vflip=1
	tsa_entry 0x09A, vflip=1
	tsa_entry 0x09B, vflip=1
	tsa_entry 0x09C, vflip=1
	tsa_entry 0x09D, vflip=1
	tsa_entry 0x09E, vflip=1
	tsa_entry 0x09F, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x097, hflip=1
	tsa_entry 0x096, hflip=1
	tsa_entry 0x095, hflip=1
	tsa_entry 0x094, hflip=1
	tsa_entry 0x093, hflip=1
	tsa_entry 0x092, hflip=1
	tsa_entry 0x091, hflip=1
	tsa_entry 0x090, hflip=1
	tsa_entry 0x078, vflip=1
	tsa_entry 0x079, vflip=1
	tsa_entry 0x07A, vflip=1
	tsa_entry 0x07B, vflip=1
	tsa_entry 0x07C, vflip=1
	tsa_entry 0x07D, vflip=1
	tsa_entry 0x07E, vflip=1
	tsa_entry 0x07F, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x0B7, hflip=1
	tsa_entry 0x0B6, hflip=1
	tsa_entry 0x0B5, hflip=1
	tsa_entry 0x0B4, hflip=1
	tsa_entry 0x0B3, hflip=1
	tsa_entry 0x0B2, hflip=1
	tsa_entry 0x0B1, hflip=1
	tsa_entry 0x0B0, hflip=1
	tsa_entry 0x058, vflip=1
	tsa_entry 0x059, vflip=1
	tsa_entry 0x05A, vflip=1
	tsa_entry 0x05B, vflip=1
	tsa_entry 0x05C, vflip=1
	tsa_entry 0x05D, vflip=1
	tsa_entry 0x05E, vflip=1
	tsa_entry 0x05F, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x0D7, hflip=1
	tsa_entry 0x0D6, hflip=1
	tsa_entry 0x0D5, hflip=1
	tsa_entry 0x0D4, hflip=1
	tsa_entry 0x0D3, hflip=1
	tsa_entry 0x0D2, hflip=1
	tsa_entry 0x0D1, hflip=1
	tsa_entry 0x0D0, hflip=1
	tsa_entry 0x038, vflip=1
	tsa_entry 0x039, vflip=1
	tsa_entry 0x03A, vflip=1
	tsa_entry 0x03B, vflip=1
	tsa_entry 0x03C, vflip=1
	tsa_entry 0x03D, vflip=1
	tsa_entry 0x03E, vflip=1
	tsa_entry 0x03F, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x0F7, hflip=1
	tsa_entry 0x0F6, hflip=1
	tsa_entry 0x0F5, hflip=1
	tsa_entry 0x0F4, hflip=1
	tsa_entry 0x0F3, hflip=1
	tsa_entry 0x0F2, hflip=1
	tsa_entry 0x0F1, hflip=1
	tsa_entry 0x0F0, hflip=1
	tsa_entry 0x018, vflip=1
	tsa_entry 0x019, vflip=1
	tsa_entry 0x01A, vflip=1
	tsa_entry 0x01B, vflip=1
	tsa_entry 0x01C, vflip=1
	tsa_entry 0x01D, vflip=1
	tsa_entry 0x01E, vflip=1
	tsa_entry 0x01F, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
