	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x031, hflip=1
	tsa_entry 0x030, hflip=1
	tsa_entry 0x02F, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x00C, hflip=1
	tsa_entry 0x00B, hflip=1
	tsa_entry 0x00A, hflip=1
	tsa_entry 0x009, hflip=1
	tsa_entry 0x008, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x056, hflip=1
	tsa_entry 0x055, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x007, hflip=1
	tsa_entry 0x006, hflip=1
	tsa_entry 0x006
	tsa_entry 0x007
	tsa_entry 0x01F
	tsa_entry 0x055
	tsa_entry 0x056
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x008
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x017, hflip=1
	tsa_entry 0x016, hflip=1
	tsa_entry 0x015, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x028, hflip=1
	tsa_entry 0x027, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x014, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000
	tsa_entry 0x014
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x027
	tsa_entry 0x028
	tsa_entry 0x01F
	tsa_entry 0x015
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x035, hflip=1
	tsa_entry 0x034, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x037, hflip=1
	tsa_entry 0x036, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x036
	tsa_entry 0x037
	tsa_entry 0x01F
	tsa_entry 0x034
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x010, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x040, hflip=1
	tsa_entry 0x03F, hflip=1
	tsa_entry 0x000, hflip=1, vflip=1
	tsa_entry 0x042, hflip=1
	tsa_entry 0x041, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x041
	tsa_entry 0x042
	tsa_entry 0x000, vflip=1
	tsa_entry 0x03F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01A, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x050, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x052, hflip=1
	tsa_entry 0x051, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x03B, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x03B
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x051
	tsa_entry 0x052
	tsa_entry 0x01F
	tsa_entry 0x04F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x05D, hflip=1
	tsa_entry 0x05C, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x04A, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x04A
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x05C
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x00E, hflip=1
	tsa_entry 0x00D, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x03E, hflip=1
	tsa_entry 0x03D, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x019, hflip=1
	tsa_entry 0x018, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x05F, hflip=1
	tsa_entry 0x05E, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x04C, hflip=1
	tsa_entry 0x04B, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x026, hflip=1
	tsa_entry 0x025, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x026
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x06D, hflip=1
	tsa_entry 0x06C, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x045, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x045
	tsa_entry 0x01F
	tsa_entry 0x06C
	tsa_entry 0x06D
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x022, hflip=1
	tsa_entry 0x021, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x058, hflip=1
	tsa_entry 0x057, hflip=1
	tsa_entry 0x057
	tsa_entry 0x058
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x021
	tsa_entry 0x022
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x022, hflip=1, vflip=1
	tsa_entry 0x021, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x058, hflip=1, vflip=1
	tsa_entry 0x057, hflip=1, vflip=1
	tsa_entry 0x057, vflip=1
	tsa_entry 0x058, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x021, vflip=1
	tsa_entry 0x022, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x04C, hflip=1, vflip=1
	tsa_entry 0x04B, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x026, hflip=1, vflip=1
	tsa_entry 0x025, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x026, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x06D, hflip=1, vflip=1
	tsa_entry 0x06C, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x045, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x045, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x06C, vflip=1
	tsa_entry 0x06D, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x03E, hflip=1, vflip=1
	tsa_entry 0x03D, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x019, hflip=1, vflip=1
	tsa_entry 0x018, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x05F, hflip=1, vflip=1
	tsa_entry 0x05E, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x00E, hflip=1, vflip=1
	tsa_entry 0x00D, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x05D, hflip=1, vflip=1
	tsa_entry 0x05C, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x04A, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x04A, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x05C, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01A, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x050, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x052, hflip=1, vflip=1
	tsa_entry 0x051, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x03B, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x03B, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x051, vflip=1
	tsa_entry 0x052, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x010, hflip=1, vflip=1
	tsa_entry 0x00F, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x040, hflip=1, vflip=1
	tsa_entry 0x03F, hflip=1, vflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x042, hflip=1, vflip=1
	tsa_entry 0x041, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x041, vflip=1
	tsa_entry 0x042, vflip=1
	tsa_entry 0x000
	tsa_entry 0x03F, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x035, hflip=1, vflip=1
	tsa_entry 0x034, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x037, hflip=1, vflip=1
	tsa_entry 0x036, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x036, vflip=1
	tsa_entry 0x037, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x034, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x017, hflip=1, vflip=1
	tsa_entry 0x016, hflip=1, vflip=1
	tsa_entry 0x015, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x028, hflip=1, vflip=1
	tsa_entry 0x027, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x014, hflip=1, vflip=1
	tsa_entry 0x000, hflip=1, vflip=1
	tsa_entry 0x000, vflip=1
	tsa_entry 0x014, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x027, vflip=1
	tsa_entry 0x028, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x015, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x031, hflip=1, vflip=1
	tsa_entry 0x030, hflip=1, vflip=1
	tsa_entry 0x02F, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x00C, hflip=1, vflip=1
	tsa_entry 0x00B, hflip=1, vflip=1
	tsa_entry 0x00A, hflip=1, vflip=1
	tsa_entry 0x009, hflip=1, vflip=1
	tsa_entry 0x008, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x056, hflip=1, vflip=1
	tsa_entry 0x055, hflip=1, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x007, hflip=1, vflip=1
	tsa_entry 0x006, hflip=1, vflip=1
	tsa_entry 0x006, vflip=1
	tsa_entry 0x007, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x055, vflip=1
	tsa_entry 0x056, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x008, vflip=1
