	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x377, pal=8, hflip=1
	tsa_entry 0x199, pal=8, vflip=1
	tsa_entry 0x377, pal=8, hflip=1
	tsa_entry 0x099, pal=8, vflip=1
	tsa_entry 0x377, pal=8, hflip=1
	tsa_entry 0x088, pal=8, vflip=1
	tsa_entry 0x377, pal=7, hflip=1
	tsa_entry 0x087, pal=8, vflip=1
	tsa_entry 0x377, pal=7, hflip=1
	tsa_entry 0x077, pal=8, vflip=1
	tsa_entry 0x378, pal=7, hflip=1
	tsa_entry 0x377, pal=7, hflip=1
	tsa_entry 0x378, pal=7, hflip=1
	tsa_entry 0x388, pal=7, hflip=1
	tsa_entry 0x378, pal=7, hflip=1
	tsa_entry 0x388, pal=7, hflip=1
	tsa_entry 0x278, pal=6, hflip=1
	tsa_entry 0x266, pal=5, hflip=1
	tsa_entry 0x378, pal=7, hflip=1
	tsa_entry 0x267, pal=6, hflip=1
	tsa_entry 0x088, pal=7, vflip=1
	tsa_entry 0x277, pal=6, hflip=1
	tsa_entry 0x088, pal=8, vflip=1
	tsa_entry 0x278, pal=6, hflip=1
	tsa_entry 0x078, pal=8, vflip=1
	tsa_entry 0x378, pal=6, hflip=1
	tsa_entry 0x377, pal=8, hflip=1
	tsa_entry 0x388, pal=6, hflip=1
	tsa_entry 0x366, pal=7, hflip=1
	tsa_entry 0x388, pal=6, hflip=1
	tsa_entry 0x266, pal=7, hflip=1
	tsa_entry 0x377, pal=6, hflip=1
	tsa_entry 0x055, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x155, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x156, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x156, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x156, pal=5, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x166, pal=5, hflip=1
	tsa_entry 0x044, pal=3, hflip=1
	tsa_entry 0x266, pal=5, hflip=1
	tsa_entry 0x045, pal=3, hflip=1
	tsa_entry 0x266, pal=5, hflip=1
	tsa_entry 0x055, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x043, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x043, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x033, pal=4, hflip=1
	tsa_entry 0x333, pal=4
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x334, pal=4
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x334, pal=4
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x034, pal=4, hflip=1
	tsa_entry 0x154, pal=4, hflip=1
	tsa_entry 0x033, pal=4, hflip=1
	tsa_entry 0x154, pal=5, hflip=1
	tsa_entry 0x033, pal=4, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x033, pal=4, hflip=1
	tsa_entry 0x155, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x334, pal=3
	tsa_entry 0x043, pal=5, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=5, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=5, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x043, pal=5, hflip=1
	tsa_entry 0x044, pal=3, hflip=1
	tsa_entry 0x033, pal=5, hflip=1
	tsa_entry 0x344, pal=3
	tsa_entry 0x033, pal=5, hflip=1
	tsa_entry 0x344, pal=3
	tsa_entry 0x033, pal=4, hflip=1
	tsa_entry 0x344, pal=3
	tsa_entry 0x033, pal=4, hflip=1
	tsa_entry 0x366, pal=8, hflip=1
	tsa_entry 0x2A9, pal=10, vflip=1
	tsa_entry 0x366, pal=8, hflip=1
	tsa_entry 0x2A8, pal=10, vflip=1
	tsa_entry 0x366, pal=7, hflip=1
	tsa_entry 0x298, pal=10, vflip=1
	tsa_entry 0x266, pal=7, hflip=1
	tsa_entry 0x187, pal=9, vflip=1
	tsa_entry 0x265, pal=6, hflip=1
	tsa_entry 0x076, pal=8, vflip=1
	tsa_entry 0x255, pal=6, hflip=1
	tsa_entry 0x266, pal=7, hflip=1
	tsa_entry 0x165, pal=5, hflip=1
	tsa_entry 0x265, pal=6, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x156, pal=6, hflip=1
	tsa_entry 0x3AA, pal=11, vflip=1
	tsa_entry 0x3BB, pal=10, vflip=1
	tsa_entry 0x3AA, pal=11, vflip=1
	tsa_entry 0x3BB, pal=10, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x2AA, pal=9, vflip=1
	tsa_entry 0x299, pal=10, vflip=1
	tsa_entry 0x1AA, pal=9, vflip=1
	tsa_entry 0x188, pal=9, vflip=1
	tsa_entry 0x199, pal=9, vflip=1
	tsa_entry 0x376, pal=8, hflip=1
	tsa_entry 0x188, pal=9, vflip=1
	tsa_entry 0x266, pal=7, hflip=1
	tsa_entry 0x188, pal=9, vflip=1
	tsa_entry 0x088, pal=8, vflip=1
	tsa_entry 0x088, pal=7, vflip=1
	tsa_entry 0x089, pal=8, vflip=1
	tsa_entry 0x099, pal=7, vflip=1
	tsa_entry 0x199, pal=9, vflip=1
	tsa_entry 0x099, pal=7, vflip=1
	tsa_entry 0x199, pal=9, vflip=1
	tsa_entry 0x199, pal=8, vflip=1
	tsa_entry 0x199, pal=9, vflip=1
	tsa_entry 0x199, pal=8, vflip=1
	tsa_entry 0x199, pal=9, vflip=1
	tsa_entry 0x199, pal=9, vflip=1
	tsa_entry 0x188, pal=9, vflip=1
	tsa_entry 0x199, pal=9, vflip=1
	tsa_entry 0x188, pal=9, vflip=1
	tsa_entry 0x199, pal=9, vflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x277, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x276, pal=6, hflip=1
	tsa_entry 0x267, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x378, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x388, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x389, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x389, pal=6, hflip=1
	tsa_entry 0x166, pal=6, hflip=1
	tsa_entry 0x389, pal=6, hflip=1
	tsa_entry 0x256, pal=6, hflip=1
	tsa_entry 0x166, pal=6, hflip=1
	tsa_entry 0x155, pal=4, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x156, pal=4, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x166, pal=5, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x166, pal=5, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x266, pal=7, hflip=1
	tsa_entry 0x277, pal=6, hflip=1
	tsa_entry 0x366, pal=7, hflip=1
	tsa_entry 0x277, pal=6, hflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x333, pal=3
	tsa_entry 0x334, pal=3
	tsa_entry 0x333, pal=3
	tsa_entry 0x344, pal=3
	tsa_entry 0x333, pal=3
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x333, pal=4
	tsa_entry 0x045, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x056, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x156, pal=5, hflip=1
	tsa_entry 0x055, pal=4, hflip=1
	tsa_entry 0x266, pal=5, hflip=1
	tsa_entry 0x155, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x155, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x154, pal=5, hflip=1
	tsa_entry 0x045, pal=4, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x155, pal=4, hflip=1
	tsa_entry 0x044, pal=3, hflip=1
	tsa_entry 0x033, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x034, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x154, pal=5, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x154, pal=5, hflip=1
	tsa_entry 0x145, pal=5, hflip=1
	tsa_entry 0x154, pal=5, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x154, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x154, pal=4, hflip=1
	tsa_entry 0x044, pal=5, hflip=1
	tsa_entry 0x154, pal=4, hflip=1
	tsa_entry 0x044, pal=5, hflip=1
	tsa_entry 0x154, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x154, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x265, pal=7, hflip=1
	tsa_entry 0x087, pal=9, vflip=1
	tsa_entry 0x265, pal=6, hflip=1
	tsa_entry 0x087, pal=8, vflip=1
	tsa_entry 0x265, pal=6, hflip=1
	tsa_entry 0x077, pal=8, vflip=1
	tsa_entry 0x265, pal=6, hflip=1
	tsa_entry 0x377, pal=7, hflip=1
	tsa_entry 0x265, pal=6, hflip=1
	tsa_entry 0x377, pal=7, hflip=1
	tsa_entry 0x255, pal=6, hflip=1
	tsa_entry 0x376, pal=7, hflip=1
	tsa_entry 0x255, pal=6, hflip=1
	tsa_entry 0x366, pal=7, hflip=1
	tsa_entry 0x255, pal=6, hflip=1
	tsa_entry 0x266, pal=7, hflip=1
	tsa_entry 0x087, pal=8, vflip=1
	tsa_entry 0x199, pal=9, vflip=1
	tsa_entry 0x077, pal=8, vflip=1
	tsa_entry 0x199, pal=9, vflip=1
	tsa_entry 0x377, pal=8, hflip=1
	tsa_entry 0x188, pal=9, vflip=1
	tsa_entry 0x367, pal=8, hflip=1
	tsa_entry 0x188, pal=9, vflip=1
	tsa_entry 0x367, pal=7, hflip=1
	tsa_entry 0x088, pal=8, vflip=1
	tsa_entry 0x367, pal=7, hflip=1
	tsa_entry 0x087, pal=8, vflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x377, pal=7, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x376, pal=7, hflip=1
	tsa_entry 0x389, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x389, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x089, pal=7, vflip=1
	tsa_entry 0x377, pal=7, hflip=1
	tsa_entry 0x099, pal=8, vflip=1
	tsa_entry 0x078, pal=8, vflip=1
	tsa_entry 0x199, pal=9, vflip=1
	tsa_entry 0x188, pal=9, vflip=1
	tsa_entry 0x198, pal=9, vflip=1
	tsa_entry 0x299, pal=9, vflip=1
	tsa_entry 0x188, pal=9, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x187, pal=10, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x376, pal=8, hflip=1
	tsa_entry 0x277, pal=6, hflip=1
	tsa_entry 0x377, pal=8, hflip=1
	tsa_entry 0x378, pal=7, hflip=1
	tsa_entry 0x377, pal=7, hflip=1
	tsa_entry 0x088, pal=7, vflip=1
	tsa_entry 0x388, pal=7, hflip=1
	tsa_entry 0x088, pal=8, vflip=1
	tsa_entry 0x089, pal=8, vflip=1
	tsa_entry 0x088, pal=8, vflip=1
	tsa_entry 0x099, pal=8, vflip=1
	tsa_entry 0x198, pal=9, vflip=1
	tsa_entry 0x199, pal=9, vflip=1
	tsa_entry 0x2A9, pal=9, vflip=1
	tsa_entry 0x199, pal=10, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x277, pal=6, hflip=1
	tsa_entry 0x166, pal=6, hflip=1
	tsa_entry 0x377, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x088, pal=7, vflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x099, pal=7, vflip=1
	tsa_entry 0x377, pal=6, hflip=1
	tsa_entry 0x199, pal=8, vflip=1
	tsa_entry 0x088, pal=7, vflip=1
	tsa_entry 0x199, pal=9, vflip=1
	tsa_entry 0x199, pal=8, vflip=1
	tsa_entry 0x299, pal=10, vflip=1
	tsa_entry 0x2AA, pal=9, vflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x155, pal=4, hflip=1
	tsa_entry 0x165, pal=6, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x266, pal=5, hflip=1
	tsa_entry 0x165, pal=5, hflip=1
	tsa_entry 0x266, pal=5, hflip=1
	tsa_entry 0x156, pal=5, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x267, pal=6, hflip=1
	tsa_entry 0x256, pal=5, hflip=1
	tsa_entry 0x378, pal=6, hflip=1
	tsa_entry 0x156, pal=5, hflip=1
	tsa_entry 0x089, pal=7, vflip=1
	tsa_entry 0x166, pal=5, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x344, pal=3
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x344, pal=3
	tsa_entry 0x044, pal=3, hflip=1
	tsa_entry 0x344, pal=3
	tsa_entry 0x044, pal=3, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=3, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=3, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=3, hflip=1
	tsa_entry 0x055, pal=4, hflip=1
	tsa_entry 0x044, pal=3, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=3, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x043, pal=4, hflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x043, pal=4, hflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x333, pal=3
	tsa_entry 0x333, pal=3
	tsa_entry 0x333, pal=3
	tsa_entry 0x333, pal=3
	tsa_entry 0x333, pal=3
	tsa_entry 0x333, pal=3
	tsa_entry 0x333, pal=3
	tsa_entry 0x154, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x144, pal=5, hflip=1
	tsa_entry 0x256, pal=6, hflip=1
	tsa_entry 0x144, pal=5, hflip=1
	tsa_entry 0x255, pal=6, hflip=1
	tsa_entry 0x033, pal=5, hflip=1
	tsa_entry 0x165, pal=6, hflip=1
	tsa_entry 0x033, pal=4, hflip=1
	tsa_entry 0x154, pal=5, hflip=1
	tsa_entry 0x333, pal=4
	tsa_entry 0x044, pal=5, hflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x043, pal=4, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x266, pal=7, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x266, pal=7, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x266, pal=5, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x256, pal=6, hflip=1
	tsa_entry 0x187, pal=10, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x187, pal=10, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x188, pal=9, vflip=1
	tsa_entry 0x2AA, pal=11, vflip=1
	tsa_entry 0x187, pal=9, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x077, pal=9, vflip=1
	tsa_entry 0x2A9, pal=10, vflip=1
	tsa_entry 0x076, pal=8, vflip=1
	tsa_entry 0x299, pal=10, vflip=1
	tsa_entry 0x376, pal=8, hflip=1
	tsa_entry 0x198, pal=10, vflip=1
	tsa_entry 0x366, pal=7, hflip=1
	tsa_entry 0x198, pal=10, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x2AB, pal=11, vflip=1
	tsa_entry 0x3BB, pal=11, vflip=1
	tsa_entry 0x3BB, pal=11, vflip=1
	tsa_entry 0x3BB, pal=11, vflip=1
	tsa_entry 0x3BA, pal=11, vflip=1
	tsa_entry 0x3BB, pal=11, vflip=1
	tsa_entry 0x3BA, pal=11, vflip=1
	tsa_entry 0x3BB, pal=11, vflip=1
	tsa_entry 0x3AA, pal=11, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x3AA, pal=12, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x29A, pal=10, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x2AB, pal=10, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x3BB, pal=11, vflip=1
	tsa_entry 0x2AB, pal=10, vflip=1
	tsa_entry 0x3BB, pal=11, vflip=1
	tsa_entry 0x2AB, pal=10, vflip=1
	tsa_entry 0x3CC, pal=11, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x3CC, pal=11, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x3CC, pal=11, vflip=1
	tsa_entry 0x2AB, pal=10, vflip=1
	tsa_entry 0x099, pal=7, vflip=1
	tsa_entry 0x266, pal=5, hflip=1
	tsa_entry 0x19A, pal=8, vflip=1
	tsa_entry 0x267, pal=6, hflip=1
	tsa_entry 0x19A, pal=8, vflip=1
	tsa_entry 0x267, pal=6, hflip=1
	tsa_entry 0x19A, pal=9, vflip=1
	tsa_entry 0x268, pal=6, hflip=1
	tsa_entry 0x1AA, pal=9, vflip=1
	tsa_entry 0x378, pal=6, hflip=1
	tsa_entry 0x2AA, pal=9, vflip=1
	tsa_entry 0x089, pal=7, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x099, pal=7, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x19A, pal=8, vflip=1
	tsa_entry 0x156, pal=4, hflip=1
	tsa_entry 0x044, pal=3, hflip=1
	tsa_entry 0x156, pal=4, hflip=1
	tsa_entry 0x044, pal=3, hflip=1
	tsa_entry 0x166, pal=5, hflip=1
	tsa_entry 0x045, pal=4, hflip=1
	tsa_entry 0x156, pal=5, hflip=1
	tsa_entry 0x055, pal=4, hflip=1
	tsa_entry 0x166, pal=6, hflip=1
	tsa_entry 0x155, pal=4, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x156, pal=4, hflip=1
	tsa_entry 0x267, pal=6, hflip=1
	tsa_entry 0x156, pal=4, hflip=1
	tsa_entry 0x378, pal=7, hflip=1
	tsa_entry 0x166, pal=5, hflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x333, pal=3
	tsa_entry 0x333, pal=3
	tsa_entry 0x333, pal=3
	tsa_entry 0x333, pal=3
	tsa_entry 0x333, pal=3
	tsa_entry 0x334, pal=3
	tsa_entry 0x333, pal=3
	tsa_entry 0x334, pal=3
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x334, pal=4
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x054, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x033, pal=4, hflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x033, pal=4, hflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x043, pal=5, hflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x044, pal=5, hflip=1
	tsa_entry 0x333, pal=4
	tsa_entry 0x144, pal=6, hflip=1
	tsa_entry 0x033, pal=4, hflip=1
	tsa_entry 0x254, pal=6, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x255, pal=6, hflip=1
	tsa_entry 0x144, pal=5, hflip=1
	tsa_entry 0x265, pal=6, hflip=1
	tsa_entry 0x265, pal=5, hflip=1
	tsa_entry 0x265, pal=6, hflip=1
	tsa_entry 0x155, pal=6, hflip=1
	tsa_entry 0x155, pal=6, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x156, pal=6, hflip=1
	tsa_entry 0x044, pal=5, hflip=1
	tsa_entry 0x255, pal=6, hflip=1
	tsa_entry 0x033, pal=4, hflip=1
	tsa_entry 0x154, pal=6, hflip=1
	tsa_entry 0x333, pal=4
	tsa_entry 0x154, pal=6, hflip=1
	tsa_entry 0x333, pal=4
	tsa_entry 0x144, pal=6, hflip=1
	tsa_entry 0x333, pal=4
	tsa_entry 0x144, pal=6, hflip=1
	tsa_entry 0x366, pal=7, hflip=1
	tsa_entry 0x198, pal=10, vflip=1
	tsa_entry 0x366, pal=7, hflip=1
	tsa_entry 0x198, pal=10, vflip=1
	tsa_entry 0x376, pal=8, hflip=1
	tsa_entry 0x299, pal=10, vflip=1
	tsa_entry 0x076, pal=9, vflip=1
	tsa_entry 0x2A9, pal=11, vflip=1
	tsa_entry 0x076, pal=9, vflip=1
	tsa_entry 0x2AA, pal=11, vflip=1
	tsa_entry 0x186, pal=10, vflip=1
	tsa_entry 0x3AA, pal=11, vflip=1
	tsa_entry 0x186, pal=10, vflip=1
	tsa_entry 0x3AA, pal=11, vflip=1
	tsa_entry 0x186, pal=10, vflip=1
	tsa_entry 0x3AA, pal=11, vflip=1
	tsa_entry 0x3AA, pal=12, vflip=1
	tsa_entry 0x0CC, pal=13, hflip=1, vflip=1
	tsa_entry 0x0BA, pal=12, hflip=1, vflip=1
	tsa_entry 0x1DC, pal=13, hflip=1, vflip=1
	tsa_entry 0x0BB, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CD, pal=13, hflip=1, vflip=1
	tsa_entry 0x0CB, pal=12, hflip=1, vflip=1
	tsa_entry 0x1CC, pal=13, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=13, hflip=1, vflip=1
	tsa_entry 0x1DC, pal=13, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0DD, pal=13, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x1DD, pal=12, hflip=1, vflip=1
	tsa_entry 0x1CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x1CD, pal=12, hflip=1, vflip=1
	tsa_entry 0x3CC, pal=11, vflip=1
	tsa_entry 0x2BB, pal=10, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x3BB, pal=10, vflip=1
	tsa_entry 0x0CD, pal=12, hflip=1, vflip=1
	tsa_entry 0x3BB, pal=11, vflip=1
	tsa_entry 0x0DD, pal=12, hflip=1, vflip=1
	tsa_entry 0x3BC, pal=12, vflip=1
	tsa_entry 0x0DD, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x1DD, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x1CD, pal=13, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x2AA, pal=9, vflip=1
	tsa_entry 0x2BA, pal=10, vflip=1
	tsa_entry 0x2AA, pal=9, vflip=1
	tsa_entry 0x3BB, pal=10, vflip=1
	tsa_entry 0x2AA, pal=9, vflip=1
	tsa_entry 0x3BC, pal=11, vflip=1
	tsa_entry 0x2AB, pal=9, vflip=1
	tsa_entry 0x3CC, pal=11, vflip=1
	tsa_entry 0x2AB, pal=9, vflip=1
	tsa_entry 0x3CC, pal=11, vflip=1
	tsa_entry 0x2AB, pal=9, vflip=1
	tsa_entry 0x3CC, pal=11, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x3CC, pal=11, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x389, pal=7, hflip=1
	tsa_entry 0x166, pal=5, hflip=1
	tsa_entry 0x389, pal=7, hflip=1
	tsa_entry 0x267, pal=5, hflip=1
	tsa_entry 0x388, pal=7, hflip=1
	tsa_entry 0x267, pal=6, hflip=1
	tsa_entry 0x378, pal=7, hflip=1
	tsa_entry 0x277, pal=6, hflip=1
	tsa_entry 0x378, pal=7, hflip=1
	tsa_entry 0x277, pal=6, hflip=1
	tsa_entry 0x378, pal=7, hflip=1
	tsa_entry 0x277, pal=6, hflip=1
	tsa_entry 0x089, pal=8, vflip=1
	tsa_entry 0x278, pal=6, hflip=1
	tsa_entry 0x099, pal=8, vflip=1
	tsa_entry 0x278, pal=5, hflip=1
	tsa_entry 0x045, pal=5, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x045, pal=5, hflip=1
	tsa_entry 0x255, pal=5, hflip=1
	tsa_entry 0x045, pal=4, hflip=1
	tsa_entry 0x165, pal=5, hflip=1
	tsa_entry 0x045, pal=4, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x045, pal=4, hflip=1
	tsa_entry 0x144, pal=5, hflip=1
	tsa_entry 0x045, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x045, pal=4, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x045, pal=4, hflip=1
	tsa_entry 0x043, pal=4, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x255, pal=6, hflip=1
	tsa_entry 0x055, pal=4, hflip=1
	tsa_entry 0x165, pal=5, hflip=1
	tsa_entry 0x055, pal=4, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x154, pal=4, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x144, pal=5, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x044, pal=5, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x144, pal=6, hflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x144, pal=5, hflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x043, pal=5, hflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x033, pal=5, hflip=1
	tsa_entry 0x332, pal=3
	tsa_entry 0x033, pal=4, hflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x033, pal=4, hflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x043, pal=4, hflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x043, pal=4, hflip=1
	tsa_entry 0x076, pal=9, vflip=1
	tsa_entry 0x3AA, pal=11, vflip=1
	tsa_entry 0x076, pal=9, vflip=1
	tsa_entry 0x3AA, pal=11, vflip=1
	tsa_entry 0x366, pal=8, hflip=1
	tsa_entry 0x2A9, pal=11, vflip=1
	tsa_entry 0x365, pal=8, hflip=1
	tsa_entry 0x2A9, pal=10, vflip=1
	tsa_entry 0x265, pal=7, hflip=1
	tsa_entry 0x298, pal=10, vflip=1
	tsa_entry 0x255, pal=7, hflip=1
	tsa_entry 0x188, pal=9, vflip=1
	tsa_entry 0x255, pal=6, hflip=1
	tsa_entry 0x077, pal=8, vflip=1
	tsa_entry 0x155, pal=6, hflip=1
	tsa_entry 0x366, pal=8, hflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0DC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CB, pal=13, hflip=1, vflip=1
	tsa_entry 0x1CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0BB, pal=12, hflip=1, vflip=1
	tsa_entry 0x1CD, pal=12, hflip=1, vflip=1
	tsa_entry 0x0BB, pal=12, hflip=1, vflip=1
	tsa_entry 0x1CC, pal=13, hflip=1, vflip=1
	tsa_entry 0x3BB, pal=12, vflip=1
	tsa_entry 0x1DC, pal=13, hflip=1, vflip=1
	tsa_entry 0x3BA, pal=12, vflip=1
	tsa_entry 0x1DC, pal=13, hflip=1, vflip=1
	tsa_entry 0x3A9, pal=12, vflip=1
	tsa_entry 0x1DC, pal=13, hflip=1, vflip=1
	tsa_entry 0x3A9, pal=12, vflip=1
	tsa_entry 0x1DC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CD, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0DD, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CD, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x1CD, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0DC, pal=13, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x1CD, pal=13, hflip=1, vflip=1
	tsa_entry 0x0DD, pal=12, hflip=1, vflip=1
	tsa_entry 0x3CC, pal=11, vflip=1
	tsa_entry 0x1AA, pal=9, vflip=1
	tsa_entry 0x0CC, pal=11, hflip=1, vflip=1
	tsa_entry 0x1AB, pal=9, vflip=1
	tsa_entry 0x0CC, pal=11, hflip=1, vflip=1
	tsa_entry 0x1AB, pal=9, vflip=1
	tsa_entry 0x0CC, pal=11, hflip=1, vflip=1
	tsa_entry 0x2AB, pal=10, vflip=1
	tsa_entry 0x3CC, pal=11, vflip=1
	tsa_entry 0x2AB, pal=10, vflip=1
	tsa_entry 0x3CC, pal=11, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x3CC, pal=11, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x3BC, pal=11, vflip=1
	tsa_entry 0x2AB, pal=10, vflip=1
	tsa_entry 0x199, pal=8, vflip=1
	tsa_entry 0x278, pal=5, hflip=1
	tsa_entry 0x199, pal=8, vflip=1
	tsa_entry 0x278, pal=6, hflip=1
	tsa_entry 0x199, pal=8, vflip=1
	tsa_entry 0x278, pal=6, hflip=1
	tsa_entry 0x199, pal=8, vflip=1
	tsa_entry 0x277, pal=6, hflip=1
	tsa_entry 0x099, pal=8, vflip=1
	tsa_entry 0x277, pal=6, hflip=1
	tsa_entry 0x099, pal=8, vflip=1
	tsa_entry 0x378, pal=6, hflip=1
	tsa_entry 0x099, pal=8, vflip=1
	tsa_entry 0x388, pal=7, hflip=1
	tsa_entry 0x19A, pal=9, vflip=1
	tsa_entry 0x089, pal=7, vflip=1
	tsa_entry 0x045, pal=4, hflip=1
	tsa_entry 0x033, pal=4, hflip=1
	tsa_entry 0x045, pal=4, hflip=1
	tsa_entry 0x034, pal=4, hflip=1
	tsa_entry 0x056, pal=4, hflip=1
	tsa_entry 0x044, pal=5, hflip=1
	tsa_entry 0x166, pal=5, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x266, pal=5, hflip=1
	tsa_entry 0x155, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x277, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x387, pal=7, hflip=1
	tsa_entry 0x366, pal=7, hflip=1
	tsa_entry 0x044, pal=5, hflip=1
	tsa_entry 0x165, pal=6, hflip=1
	tsa_entry 0x155, pal=5, hflip=1
	tsa_entry 0x255, pal=6, hflip=1
	tsa_entry 0x255, pal=5, hflip=1
	tsa_entry 0x256, pal=6, hflip=1
	tsa_entry 0x255, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x266, pal=7, hflip=1
	tsa_entry 0x266, pal=7, hflip=1
	tsa_entry 0x377, pal=8, hflip=1
	tsa_entry 0x377, pal=8, hflip=1
	tsa_entry 0x088, pal=8, vflip=1
	tsa_entry 0x088, pal=9, vflip=1
	tsa_entry 0x199, pal=9, vflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x043, pal=4, hflip=1
	tsa_entry 0x333, pal=3
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x322, pal=3
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x332, pal=3
	tsa_entry 0x043, pal=4, hflip=1
	tsa_entry 0x322, pal=3
	tsa_entry 0x333, pal=3
	tsa_entry 0x322, pal=3
	tsa_entry 0x333, pal=4
	tsa_entry 0x222, pal=3
	tsa_entry 0x033, pal=4, hflip=1
	tsa_entry 0x221, pal=3
	tsa_entry 0x043, pal=4, hflip=1
	tsa_entry 0x255, pal=6, hflip=1
	tsa_entry 0x266, pal=7, hflip=1
	tsa_entry 0x154, pal=5, hflip=1
	tsa_entry 0x255, pal=7, hflip=1
	tsa_entry 0x144, pal=5, hflip=1
	tsa_entry 0x266, pal=7, hflip=1
	tsa_entry 0x044, pal=5, hflip=1
	tsa_entry 0x265, pal=7, hflip=1
	tsa_entry 0x044, pal=4, hflip=1
	tsa_entry 0x265, pal=7, hflip=1
	tsa_entry 0x044, pal=5, hflip=1
	tsa_entry 0x265, pal=7, hflip=1
	tsa_entry 0x044, pal=5, hflip=1
	tsa_entry 0x265, pal=6, hflip=1
	tsa_entry 0x044, pal=6, hflip=1
	tsa_entry 0x265, pal=6, hflip=1
	tsa_entry 0x3A8, pal=12, vflip=1
	tsa_entry 0x1DC, pal=13, hflip=1, vflip=1
	tsa_entry 0x398, pal=12, vflip=1
	tsa_entry 0x1DC, pal=13, hflip=1, vflip=1
	tsa_entry 0x298, pal=12, vflip=1
	tsa_entry 0x1DC, pal=13, hflip=1, vflip=1
	tsa_entry 0x298, pal=12, vflip=1
	tsa_entry 0x1DC, pal=13, hflip=1, vflip=1
	tsa_entry 0x298, pal=11, vflip=1
	tsa_entry 0x1CC, pal=13, hflip=1, vflip=1
	tsa_entry 0x298, pal=11, vflip=1
	tsa_entry 0x1CC, pal=13, hflip=1, vflip=1
	tsa_entry 0x187, pal=10, vflip=1
	tsa_entry 0x0CB, pal=12, hflip=1, vflip=1
	tsa_entry 0x187, pal=10, vflip=1
	tsa_entry 0x0BB, pal=12, hflip=1, vflip=1
	tsa_entry 0x1DC, pal=12, hflip=1, vflip=1
	tsa_entry 0x1CD, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CD, pal=13, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CD, pal=13, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CD, pal=12, hflip=1, vflip=1
	tsa_entry 0x3CC, pal=12, vflip=1
	tsa_entry 0x0CD, pal=12, hflip=1, vflip=1
	tsa_entry 0x3BB, pal=12, vflip=1
	tsa_entry 0x0DC, pal=12, hflip=1, vflip=1
	tsa_entry 0x3BB, pal=12, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0BB, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CB, pal=12, hflip=1, vflip=1
	tsa_entry 0x3BC, pal=11, vflip=1
	tsa_entry 0x3BB, pal=10, vflip=1
	tsa_entry 0x3CC, pal=11, vflip=1
	tsa_entry 0x3BB, pal=11, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=13, hflip=1, vflip=1
	tsa_entry 0x1DD, pal=13, hflip=1, vflip=1
	tsa_entry 0x1CC, pal=13, hflip=1, vflip=1
	tsa_entry 0x1DD, pal=13, hflip=1, vflip=1
	tsa_entry 0x1DC, pal=13, hflip=1, vflip=1
	tsa_entry 0x1DD, pal=14, hflip=1, vflip=1
	tsa_entry 0x1DD, pal=13, hflip=1, vflip=1
	tsa_entry 0x1ED, pal=14, hflip=1, vflip=1
	tsa_entry 0x1AA, pal=9, vflip=1
	tsa_entry 0x099, pal=8, vflip=1
	tsa_entry 0x2AB, pal=10, vflip=1
	tsa_entry 0x1AA, pal=9, vflip=1
	tsa_entry 0x3BC, pal=10, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x0CC, pal=11, hflip=1, vflip=1
	tsa_entry 0x3BB, pal=11, vflip=1
	tsa_entry 0x0DD, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x1DD, pal=13, hflip=1, vflip=1
	tsa_entry 0x1DD, pal=12, hflip=1, vflip=1
	tsa_entry 0x1DD, pal=13, hflip=1, vflip=1
	tsa_entry 0x1DD, pal=13, hflip=1, vflip=1
	tsa_entry 0x2EE, pal=14, hflip=1, vflip=1
	tsa_entry 0x2DE, pal=13, hflip=1, vflip=1
	tsa_entry 0x088, pal=8, vflip=1
	tsa_entry 0x088, pal=8, vflip=1
	tsa_entry 0x199, pal=9, vflip=1
	tsa_entry 0x089, pal=9, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x19A, pal=10, vflip=1
	tsa_entry 0x3AA, pal=11, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x3BB, pal=11, vflip=1
	tsa_entry 0x3BB, pal=11, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x1DD, pal=13, hflip=1, vflip=1
	tsa_entry 0x0CD, pal=12, hflip=1, vflip=1
	tsa_entry 0x1DD, pal=13, hflip=1, vflip=1
	tsa_entry 0x1DD, pal=13, hflip=1, vflip=1
	tsa_entry 0x199, pal=9, vflip=1
	tsa_entry 0x1AA, pal=9, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x2AA, pal=9, vflip=1
	tsa_entry 0x2AA, pal=10, vflip=1
	tsa_entry 0x2AA, pal=9, vflip=1
	tsa_entry 0x3BB, pal=11, vflip=1
	tsa_entry 0x2BB, pal=9, vflip=1
	tsa_entry 0x3BB, pal=11, vflip=1
	tsa_entry 0x2BB, pal=10, vflip=1
	tsa_entry 0x3CC, pal=11, vflip=1
	tsa_entry 0x3BB, pal=10, vflip=1
	tsa_entry 0x0CC, pal=11, hflip=1, vflip=1
	tsa_entry 0x3BB, pal=10, vflip=1
	tsa_entry 0x0CC, pal=11, hflip=1, vflip=1
	tsa_entry 0x3BB, pal=11, vflip=1
	tsa_entry 0x221, pal=3
	tsa_entry 0x043, pal=4, hflip=1
	tsa_entry 0x221, pal=2
	tsa_entry 0x033, pal=4, hflip=1
	tsa_entry 0x212, pal=2
	tsa_entry 0x332, pal=3
	tsa_entry 0x121, pal=2
	tsa_entry 0x323, pal=3
	tsa_entry 0x121, pal=2
	tsa_entry 0x222, pal=3
	tsa_entry 0x221, pal=2
	tsa_entry 0x222, pal=2
	tsa_entry 0x222, pal=2
	tsa_entry 0x222, pal=2
	tsa_entry 0x222, pal=2
	tsa_entry 0x332, pal=3
	tsa_entry 0x044, pal=5, hflip=1
	tsa_entry 0x265, pal=6, hflip=1
	tsa_entry 0x044, pal=5, hflip=1
	tsa_entry 0x255, pal=6, hflip=1
	tsa_entry 0x033, pal=4, hflip=1
	tsa_entry 0x255, pal=6, hflip=1
	tsa_entry 0x333, pal=4
	tsa_entry 0x154, pal=6, hflip=1
	tsa_entry 0x333, pal=4
	tsa_entry 0x254, pal=6, hflip=1
	tsa_entry 0x333, pal=4
	tsa_entry 0x155, pal=6, hflip=1
	tsa_entry 0x033, pal=4, hflip=1
	tsa_entry 0x255, pal=6, hflip=1
	tsa_entry 0x033, pal=5, hflip=1
	tsa_entry 0x266, pal=6, hflip=1
	tsa_entry 0x187, pal=10, vflip=1
	tsa_entry 0x3BB, pal=12, vflip=1
	tsa_entry 0x187, pal=10, vflip=1
	tsa_entry 0x3BB, pal=11, vflip=1
	tsa_entry 0x187, pal=10, vflip=1
	tsa_entry 0x3BA, pal=11, vflip=1
	tsa_entry 0x187, pal=9, vflip=1
	tsa_entry 0x3BA, pal=11, vflip=1
	tsa_entry 0x087, pal=9, vflip=1
	tsa_entry 0x3AA, pal=11, vflip=1
	tsa_entry 0x076, pal=9, vflip=1
	tsa_entry 0x2A9, pal=11, vflip=1
	tsa_entry 0x066, pal=9, vflip=1
	tsa_entry 0x2A9, pal=11, vflip=1
	tsa_entry 0x366, pal=9, hflip=1
	tsa_entry 0x3A9, pal=11, vflip=1
	tsa_entry 0x3BC, pal=12, vflip=1
	tsa_entry 0x0CC, pal=13, hflip=1, vflip=1
	tsa_entry 0x3BB, pal=12, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x3BB, pal=12, vflip=1
	tsa_entry 0x0CC, pal=13, hflip=1, vflip=1
	tsa_entry 0x3BB, pal=12, vflip=1
	tsa_entry 0x1CC, pal=13, hflip=1, vflip=1
	tsa_entry 0x3BB, pal=12, vflip=1
	tsa_entry 0x1DC, pal=13, hflip=1, vflip=1
	tsa_entry 0x0BB, pal=12, hflip=1, vflip=1
	tsa_entry 0x1DC, pal=13, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x1DD, pal=13, hflip=1, vflip=1
	tsa_entry 0x0CC, pal=13, hflip=1, vflip=1
	tsa_entry 0x1DD, pal=14, hflip=1, vflip=1
	tsa_entry 0x1DD, pal=13, hflip=1, vflip=1
	tsa_entry 0x2DE, pal=14, hflip=1, vflip=1
	tsa_entry 0x1DD, pal=13, hflip=1, vflip=1
	tsa_entry 0x2EE, pal=14, hflip=1, vflip=1
	tsa_entry 0x2DD, pal=13, hflip=1, vflip=1
	tsa_entry 0x2EE, pal=14, hflip=1, vflip=1
	tsa_entry 0x1DD, pal=13, hflip=1, vflip=1
	tsa_entry 0x2EE, pal=14, hflip=1, vflip=1
	tsa_entry 0x1DD, pal=14, hflip=1, vflip=1
	tsa_entry 0x2EE, pal=14, hflip=1, vflip=1
	tsa_entry 0x2DE, pal=14, hflip=1, vflip=1
	tsa_entry 0x2EE, pal=14, hflip=1, vflip=1
	tsa_entry 0x2EE, pal=14, hflip=1, vflip=1
	tsa_entry 0x3EE, pal=14, hflip=1, vflip=1
	tsa_entry 0x2EE, pal=14, hflip=1, vflip=1
	tsa_entry 0x2EE, pal=14, hflip=1, vflip=1
	tsa_entry 0x2EE, pal=14, hflip=1, vflip=1
	tsa_entry 0x2EE, pal=14, hflip=1, vflip=1
	tsa_entry 0x2EE, pal=14, hflip=1, vflip=1
	tsa_entry 0x2EE, pal=14, hflip=1, vflip=1
	tsa_entry 0x3EE, pal=14, hflip=1, vflip=1
	tsa_entry 0x3EF, pal=15, hflip=1, vflip=1
	tsa_entry 0x3FE, pal=15, hflip=1, vflip=1
	tsa_entry 0x3FF, pal=15, hflip=1, vflip=1
	tsa_entry 0x2FF, pal=15, hflip=1, vflip=1
	tsa_entry 0x3FE, pal=15, hflip=1, vflip=1
	tsa_entry 0x3FE, pal=15, hflip=1, vflip=1
	tsa_entry 0x3FF, pal=15, hflip=1, vflip=1
	tsa_entry 0x3EF, pal=15, hflip=1, vflip=1
	tsa_entry 0x3FF, pal=15, hflip=1, vflip=1
	tsa_entry 0x3FF, pal=14, hflip=1, vflip=1
	tsa_entry 0x3FF, pal=15, hflip=1, vflip=1
	tsa_entry 0x2EE, pal=13, hflip=1, vflip=1
	tsa_entry 0x1DD, pal=13, hflip=1, vflip=1
	tsa_entry 0x2EE, pal=14, hflip=1, vflip=1
	tsa_entry 0x1DE, pal=13, hflip=1, vflip=1
	tsa_entry 0x3EF, pal=14, hflip=1, vflip=1
	tsa_entry 0x1EE, pal=13, hflip=1, vflip=1
	tsa_entry 0x3FF, pal=15, hflip=1, vflip=1
	tsa_entry 0x2EF, pal=14, hflip=1, vflip=1
	tsa_entry 0x3FF, pal=15, hflip=1, vflip=1
	tsa_entry 0x2FE, pal=14, hflip=1, vflip=1
	tsa_entry 0x3FF, pal=15, hflip=1, vflip=1
	tsa_entry 0x3FF, pal=15, hflip=1, vflip=1
	tsa_entry 0x3FF, pal=15, hflip=1, vflip=1
	tsa_entry 0x3FF, pal=15, hflip=1, vflip=1
	tsa_entry 0x3FF, pal=15, hflip=1, vflip=1
	tsa_entry 0x3FF, pal=15, hflip=1, vflip=1
	tsa_entry 0x0CD, pal=12, hflip=1, vflip=1
	tsa_entry 0x3BB, pal=11, vflip=1
	tsa_entry 0x0DD, pal=12, hflip=1, vflip=1
	tsa_entry 0x3BC, pal=11, vflip=1
	tsa_entry 0x1DD, pal=13, hflip=1, vflip=1
	tsa_entry 0x3CC, pal=11, vflip=1
	tsa_entry 0x1EE, pal=13, hflip=1, vflip=1
	tsa_entry 0x3CC, pal=11, vflip=1
	tsa_entry 0x1EE, pal=13, hflip=1, vflip=1
	tsa_entry 0x0CD, pal=11, hflip=1, vflip=1
	tsa_entry 0x2EE, pal=14, hflip=1, vflip=1
	tsa_entry 0x0DD, pal=11, hflip=1, vflip=1
	tsa_entry 0x2FF, pal=14, hflip=1, vflip=1
	tsa_entry 0x0DD, pal=12, hflip=1, vflip=1
	tsa_entry 0x2FF, pal=14, hflip=1, vflip=1
	tsa_entry 0x1DE, pal=12, hflip=1, vflip=1
