	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x001, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x019, hflip=1
	tsa_entry 0x018, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
