	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x012, hflip=1
	tsa_entry 0x011, hflip=1
	tsa_entry 0x010, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x00E, hflip=1
	tsa_entry 0x00D, hflip=1
	tsa_entry 0x00C, hflip=1
	tsa_entry 0x00B, hflip=1
	tsa_entry 0x00A, hflip=1
	tsa_entry 0x009, hflip=1
	tsa_entry 0x008, hflip=1
	tsa_entry 0x007, hflip=1
	tsa_entry 0x006, hflip=1
	tsa_entry 0x005, hflip=1
	tsa_entry 0x004, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x002, hflip=1
	tsa_entry 0x001, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000
	tsa_entry 0x001
	tsa_entry 0x002
	tsa_entry 0x003
	tsa_entry 0x004
	tsa_entry 0x005
	tsa_entry 0x006
	tsa_entry 0x007
	tsa_entry 0x008
	tsa_entry 0x009
	tsa_entry 0x00A
	tsa_entry 0x028, hflip=1
	tsa_entry 0x027, hflip=1
	tsa_entry 0x026, hflip=1
	tsa_entry 0x025, hflip=1
	tsa_entry 0x024, hflip=1
	tsa_entry 0x023, hflip=1
	tsa_entry 0x022, hflip=1
	tsa_entry 0x021, hflip=1
	tsa_entry 0x020, hflip=1
	tsa_entry 0x0C6, hflip=1
	tsa_entry 0x01E, hflip=1
	tsa_entry 0x01D, hflip=1
	tsa_entry 0x01C, hflip=1
	tsa_entry 0x01B, hflip=1
	tsa_entry 0x01A, hflip=1
	tsa_entry 0x019, hflip=1
	tsa_entry 0x018, hflip=1
	tsa_entry 0x017, hflip=1
	tsa_entry 0x016, hflip=1
	tsa_entry 0x016
	tsa_entry 0x017
	tsa_entry 0x018
	tsa_entry 0x019
	tsa_entry 0x01A
	tsa_entry 0x01B
	tsa_entry 0x01C
	tsa_entry 0x01D
	tsa_entry 0x01E
	tsa_entry 0x0C6
	tsa_entry 0x020
	tsa_entry 0x03E, hflip=1
	tsa_entry 0x03D, hflip=1
	tsa_entry 0x03C, hflip=1
	tsa_entry 0x03B, hflip=1
	tsa_entry 0x03A, hflip=1
	tsa_entry 0x039, hflip=1
	tsa_entry 0x038, hflip=1
	tsa_entry 0x037, hflip=1
	tsa_entry 0x036, hflip=1
	tsa_entry 0x035, hflip=1
	tsa_entry 0x034, hflip=1
	tsa_entry 0x033, hflip=1
	tsa_entry 0x032, hflip=1
	tsa_entry 0x031, hflip=1
	tsa_entry 0x030, hflip=1
	tsa_entry 0x02F, hflip=1
	tsa_entry 0x02E, hflip=1
	tsa_entry 0x02D, hflip=1
	tsa_entry 0x02C, hflip=1
	tsa_entry 0x02C
	tsa_entry 0x02D
	tsa_entry 0x02E
	tsa_entry 0x02F
	tsa_entry 0x030
	tsa_entry 0x031
	tsa_entry 0x032
	tsa_entry 0x033
	tsa_entry 0x034
	tsa_entry 0x035
	tsa_entry 0x036
	tsa_entry 0x054, hflip=1
	tsa_entry 0x053, hflip=1
	tsa_entry 0x052, hflip=1
	tsa_entry 0x051, hflip=1
	tsa_entry 0x050, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04E, hflip=1
	tsa_entry 0x04D, hflip=1
	tsa_entry 0x04C, hflip=1
	tsa_entry 0x04B, hflip=1
	tsa_entry 0x04A, hflip=1
	tsa_entry 0x049, hflip=1
	tsa_entry 0x048, hflip=1
	tsa_entry 0x047, hflip=1
	tsa_entry 0x046, hflip=1
	tsa_entry 0x045, hflip=1
	tsa_entry 0x044, hflip=1
	tsa_entry 0x043, hflip=1
	tsa_entry 0x042, hflip=1
	tsa_entry 0x042
	tsa_entry 0x043
	tsa_entry 0x044
	tsa_entry 0x045
	tsa_entry 0x046
	tsa_entry 0x047
	tsa_entry 0x048
	tsa_entry 0x049
	tsa_entry 0x04A
	tsa_entry 0x04B
	tsa_entry 0x04C
	tsa_entry 0x06A, hflip=1
	tsa_entry 0x069, hflip=1
	tsa_entry 0x068, hflip=1
	tsa_entry 0x067, hflip=1
	tsa_entry 0x066, hflip=1
	tsa_entry 0x065, hflip=1
	tsa_entry 0x064, hflip=1
	tsa_entry 0x063, hflip=1
	tsa_entry 0x062, hflip=1
	tsa_entry 0x061, hflip=1
	tsa_entry 0x060, hflip=1
	tsa_entry 0x05F, hflip=1
	tsa_entry 0x05E, hflip=1
	tsa_entry 0x05D, hflip=1
	tsa_entry 0x05C, hflip=1
	tsa_entry 0x05B, hflip=1
	tsa_entry 0x05A, hflip=1
	tsa_entry 0x059, hflip=1
	tsa_entry 0x058, hflip=1
	tsa_entry 0x058
	tsa_entry 0x059
	tsa_entry 0x05A
	tsa_entry 0x05B
	tsa_entry 0x05C
	tsa_entry 0x05D
	tsa_entry 0x05E
	tsa_entry 0x05F
	tsa_entry 0x060
	tsa_entry 0x061
	tsa_entry 0x062
	tsa_entry 0x080, hflip=1
	tsa_entry 0x07F, hflip=1
	tsa_entry 0x07E, hflip=1
	tsa_entry 0x07D, hflip=1
	tsa_entry 0x07C, hflip=1
	tsa_entry 0x07B, hflip=1
	tsa_entry 0x07A, hflip=1
	tsa_entry 0x079, hflip=1
	tsa_entry 0x078, hflip=1
	tsa_entry 0x077, hflip=1
	tsa_entry 0x076, hflip=1
	tsa_entry 0x075, hflip=1
	tsa_entry 0x074, hflip=1
	tsa_entry 0x073, hflip=1
	tsa_entry 0x072, hflip=1
	tsa_entry 0x071, hflip=1
	tsa_entry 0x070, hflip=1
	tsa_entry 0x06F, hflip=1
	tsa_entry 0x06E, hflip=1
	tsa_entry 0x06E
	tsa_entry 0x06F
	tsa_entry 0x070
	tsa_entry 0x071
	tsa_entry 0x072
	tsa_entry 0x073
	tsa_entry 0x074
	tsa_entry 0x075
	tsa_entry 0x076
	tsa_entry 0x077
	tsa_entry 0x078
	tsa_entry 0x096, hflip=1
	tsa_entry 0x095, hflip=1
	tsa_entry 0x094, hflip=1
	tsa_entry 0x093, hflip=1
	tsa_entry 0x092, hflip=1
	tsa_entry 0x091, hflip=1
	tsa_entry 0x090, hflip=1
	tsa_entry 0x08F, hflip=1
	tsa_entry 0x08E, hflip=1
	tsa_entry 0x08D, hflip=1
	tsa_entry 0x08C, hflip=1
	tsa_entry 0x08B, hflip=1
	tsa_entry 0x08A, hflip=1
	tsa_entry 0x089, hflip=1
	tsa_entry 0x088, hflip=1
	tsa_entry 0x087, hflip=1
	tsa_entry 0x086, hflip=1
	tsa_entry 0x085, hflip=1
	tsa_entry 0x084, hflip=1
	tsa_entry 0x084
	tsa_entry 0x085
	tsa_entry 0x086
	tsa_entry 0x087
	tsa_entry 0x088
	tsa_entry 0x089
	tsa_entry 0x08A
	tsa_entry 0x08B
	tsa_entry 0x08C
	tsa_entry 0x08D
	tsa_entry 0x08E
	tsa_entry 0x0AC, hflip=1
	tsa_entry 0x0AB, hflip=1
	tsa_entry 0x0AA, hflip=1
	tsa_entry 0x0A9, hflip=1
	tsa_entry 0x0A8, hflip=1
	tsa_entry 0x0A7, hflip=1
	tsa_entry 0x0A6, hflip=1
	tsa_entry 0x0A5, hflip=1
	tsa_entry 0x0A4, hflip=1
	tsa_entry 0x0A3, hflip=1
	tsa_entry 0x0A2, hflip=1
	tsa_entry 0x0A1, hflip=1
	tsa_entry 0x0A0, hflip=1
	tsa_entry 0x09F, hflip=1
	tsa_entry 0x09E, hflip=1
	tsa_entry 0x09D, hflip=1
	tsa_entry 0x09C, hflip=1
	tsa_entry 0x09B, hflip=1
	tsa_entry 0x09A, hflip=1
	tsa_entry 0x09A
	tsa_entry 0x09B
	tsa_entry 0x09C
	tsa_entry 0x09D
	tsa_entry 0x09E
	tsa_entry 0x09F
	tsa_entry 0x0A0
	tsa_entry 0x0A1
	tsa_entry 0x0A2
	tsa_entry 0x0A3
	tsa_entry 0x0A4
	tsa_entry 0x0C2, hflip=1
	tsa_entry 0x0C1, hflip=1
	tsa_entry 0x0C0, hflip=1
	tsa_entry 0x0BF, hflip=1
	tsa_entry 0x0BE, hflip=1
	tsa_entry 0x0BD, hflip=1
	tsa_entry 0x0BC, hflip=1
	tsa_entry 0x0BB, hflip=1
	tsa_entry 0x0BA, hflip=1
	tsa_entry 0x0B9, hflip=1
	tsa_entry 0x0B8, hflip=1
	tsa_entry 0x0B7, hflip=1
	tsa_entry 0x0B6, hflip=1
	tsa_entry 0x0B5, hflip=1
	tsa_entry 0x0B4, hflip=1
	tsa_entry 0x0B3, hflip=1
	tsa_entry 0x0B2, hflip=1
	tsa_entry 0x0B1, hflip=1
	tsa_entry 0x0B0, hflip=1
	tsa_entry 0x0B0
	tsa_entry 0x0B1
	tsa_entry 0x0B2
	tsa_entry 0x0B3
	tsa_entry 0x0B4
	tsa_entry 0x0B5
	tsa_entry 0x0B6
	tsa_entry 0x0B7
	tsa_entry 0x0B8
	tsa_entry 0x0B9
	tsa_entry 0x0BA
	tsa_entry 0x0C2, hflip=1, vflip=1
	tsa_entry 0x0C1, hflip=1, vflip=1
	tsa_entry 0x0C0, hflip=1, vflip=1
	tsa_entry 0x0BF, hflip=1, vflip=1
	tsa_entry 0x0BE, hflip=1, vflip=1
	tsa_entry 0x0BD, hflip=1, vflip=1
	tsa_entry 0x0BC, hflip=1, vflip=1
	tsa_entry 0x0BB, hflip=1, vflip=1
	tsa_entry 0x0BA, hflip=1, vflip=1
	tsa_entry 0x0B9, hflip=1, vflip=1
	tsa_entry 0x0B8, hflip=1, vflip=1
	tsa_entry 0x0B7, hflip=1, vflip=1
	tsa_entry 0x0B6, hflip=1, vflip=1
	tsa_entry 0x0B5, hflip=1, vflip=1
	tsa_entry 0x0B4, hflip=1, vflip=1
	tsa_entry 0x0B3, hflip=1, vflip=1
	tsa_entry 0x0B2, hflip=1, vflip=1
	tsa_entry 0x0B1, hflip=1, vflip=1
	tsa_entry 0x0B0, hflip=1, vflip=1
	tsa_entry 0x0B0, vflip=1
	tsa_entry 0x0B1, vflip=1
	tsa_entry 0x0B2, vflip=1
	tsa_entry 0x0B3, vflip=1
	tsa_entry 0x0B4, vflip=1
	tsa_entry 0x0B5, vflip=1
	tsa_entry 0x0B6, vflip=1
	tsa_entry 0x0B7, vflip=1
	tsa_entry 0x0B8, vflip=1
	tsa_entry 0x0B9, vflip=1
	tsa_entry 0x0BA, vflip=1
	tsa_entry 0x0AC, hflip=1, vflip=1
	tsa_entry 0x0AB, hflip=1, vflip=1
	tsa_entry 0x0AA, hflip=1, vflip=1
	tsa_entry 0x0A9, hflip=1, vflip=1
	tsa_entry 0x0A8, hflip=1, vflip=1
	tsa_entry 0x0A7, hflip=1, vflip=1
	tsa_entry 0x0A6, hflip=1, vflip=1
	tsa_entry 0x0A5, hflip=1, vflip=1
	tsa_entry 0x0A4, hflip=1, vflip=1
	tsa_entry 0x0A3, hflip=1, vflip=1
	tsa_entry 0x0A2, hflip=1, vflip=1
	tsa_entry 0x0A1, hflip=1, vflip=1
	tsa_entry 0x0A0, hflip=1, vflip=1
	tsa_entry 0x09F, hflip=1, vflip=1
	tsa_entry 0x09E, hflip=1, vflip=1
	tsa_entry 0x09D, hflip=1, vflip=1
	tsa_entry 0x09C, hflip=1, vflip=1
	tsa_entry 0x09B, hflip=1, vflip=1
	tsa_entry 0x09A, hflip=1, vflip=1
	tsa_entry 0x09A, vflip=1
	tsa_entry 0x09B, vflip=1
	tsa_entry 0x09C, vflip=1
	tsa_entry 0x09D, vflip=1
	tsa_entry 0x09E, vflip=1
	tsa_entry 0x09F, vflip=1
	tsa_entry 0x0A0, vflip=1
	tsa_entry 0x0A1, vflip=1
	tsa_entry 0x0A2, vflip=1
	tsa_entry 0x0A3, vflip=1
	tsa_entry 0x0A4, vflip=1
	tsa_entry 0x096, hflip=1, vflip=1
	tsa_entry 0x095, hflip=1, vflip=1
	tsa_entry 0x094, hflip=1, vflip=1
	tsa_entry 0x093, hflip=1, vflip=1
	tsa_entry 0x092, hflip=1, vflip=1
	tsa_entry 0x091, hflip=1, vflip=1
	tsa_entry 0x090, hflip=1, vflip=1
	tsa_entry 0x08F, hflip=1, vflip=1
	tsa_entry 0x08E, hflip=1, vflip=1
	tsa_entry 0x08D, hflip=1, vflip=1
	tsa_entry 0x08C, hflip=1, vflip=1
	tsa_entry 0x08B, hflip=1, vflip=1
	tsa_entry 0x08A, hflip=1, vflip=1
	tsa_entry 0x089, hflip=1, vflip=1
	tsa_entry 0x088, hflip=1, vflip=1
	tsa_entry 0x087, hflip=1, vflip=1
	tsa_entry 0x086, hflip=1, vflip=1
	tsa_entry 0x085, hflip=1, vflip=1
	tsa_entry 0x084, hflip=1, vflip=1
	tsa_entry 0x084, vflip=1
	tsa_entry 0x085, vflip=1
	tsa_entry 0x086, vflip=1
	tsa_entry 0x087, vflip=1
	tsa_entry 0x088, vflip=1
	tsa_entry 0x089, vflip=1
	tsa_entry 0x08A, vflip=1
	tsa_entry 0x08B, vflip=1
	tsa_entry 0x08C, vflip=1
	tsa_entry 0x08D, vflip=1
	tsa_entry 0x08E, vflip=1
	tsa_entry 0x080, hflip=1, vflip=1
	tsa_entry 0x07F, hflip=1, vflip=1
	tsa_entry 0x07E, hflip=1, vflip=1
	tsa_entry 0x07D, hflip=1, vflip=1
	tsa_entry 0x07C, hflip=1, vflip=1
	tsa_entry 0x07B, hflip=1, vflip=1
	tsa_entry 0x07A, hflip=1, vflip=1
	tsa_entry 0x079, hflip=1, vflip=1
	tsa_entry 0x078, hflip=1, vflip=1
	tsa_entry 0x077, hflip=1, vflip=1
	tsa_entry 0x076, hflip=1, vflip=1
	tsa_entry 0x075, hflip=1, vflip=1
	tsa_entry 0x074, hflip=1, vflip=1
	tsa_entry 0x073, hflip=1, vflip=1
	tsa_entry 0x072, hflip=1, vflip=1
	tsa_entry 0x071, hflip=1, vflip=1
	tsa_entry 0x070, hflip=1, vflip=1
	tsa_entry 0x06F, hflip=1, vflip=1
	tsa_entry 0x06E, hflip=1, vflip=1
	tsa_entry 0x06E, vflip=1
	tsa_entry 0x06F, vflip=1
	tsa_entry 0x070, vflip=1
	tsa_entry 0x071, vflip=1
	tsa_entry 0x072, vflip=1
	tsa_entry 0x073, vflip=1
	tsa_entry 0x074, vflip=1
	tsa_entry 0x075, vflip=1
	tsa_entry 0x076, vflip=1
	tsa_entry 0x077, vflip=1
	tsa_entry 0x078, vflip=1
	tsa_entry 0x06A, hflip=1, vflip=1
	tsa_entry 0x069, hflip=1, vflip=1
	tsa_entry 0x068, hflip=1, vflip=1
	tsa_entry 0x067, hflip=1, vflip=1
	tsa_entry 0x066, hflip=1, vflip=1
	tsa_entry 0x065, hflip=1, vflip=1
	tsa_entry 0x064, hflip=1, vflip=1
	tsa_entry 0x063, hflip=1, vflip=1
	tsa_entry 0x062, hflip=1, vflip=1
	tsa_entry 0x061, hflip=1, vflip=1
	tsa_entry 0x060, hflip=1, vflip=1
	tsa_entry 0x05F, hflip=1, vflip=1
	tsa_entry 0x05E, hflip=1, vflip=1
	tsa_entry 0x05D, hflip=1, vflip=1
	tsa_entry 0x05C, hflip=1, vflip=1
	tsa_entry 0x05B, hflip=1, vflip=1
	tsa_entry 0x05A, hflip=1, vflip=1
	tsa_entry 0x059, hflip=1, vflip=1
	tsa_entry 0x058, hflip=1, vflip=1
	tsa_entry 0x058, vflip=1
	tsa_entry 0x059, vflip=1
	tsa_entry 0x05A, vflip=1
	tsa_entry 0x05B, vflip=1
	tsa_entry 0x05C, vflip=1
	tsa_entry 0x05D, vflip=1
	tsa_entry 0x05E, vflip=1
	tsa_entry 0x05F, vflip=1
	tsa_entry 0x060, vflip=1
	tsa_entry 0x061, vflip=1
	tsa_entry 0x062, vflip=1
	tsa_entry 0x054, hflip=1, vflip=1
	tsa_entry 0x053, hflip=1, vflip=1
	tsa_entry 0x052, hflip=1, vflip=1
	tsa_entry 0x051, hflip=1, vflip=1
	tsa_entry 0x050, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04E, hflip=1, vflip=1
	tsa_entry 0x04D, hflip=1, vflip=1
	tsa_entry 0x04C, hflip=1, vflip=1
	tsa_entry 0x04B, hflip=1, vflip=1
	tsa_entry 0x04A, hflip=1, vflip=1
	tsa_entry 0x049, hflip=1, vflip=1
	tsa_entry 0x048, hflip=1, vflip=1
	tsa_entry 0x047, hflip=1, vflip=1
	tsa_entry 0x046, hflip=1, vflip=1
	tsa_entry 0x045, hflip=1, vflip=1
	tsa_entry 0x044, hflip=1, vflip=1
	tsa_entry 0x043, hflip=1, vflip=1
	tsa_entry 0x042, hflip=1, vflip=1
	tsa_entry 0x042, vflip=1
	tsa_entry 0x043, vflip=1
	tsa_entry 0x044, vflip=1
	tsa_entry 0x045, vflip=1
	tsa_entry 0x046, vflip=1
	tsa_entry 0x047, vflip=1
	tsa_entry 0x048, vflip=1
	tsa_entry 0x049, vflip=1
	tsa_entry 0x04A, vflip=1
	tsa_entry 0x04B, vflip=1
	tsa_entry 0x04C, vflip=1
	tsa_entry 0x03E, hflip=1, vflip=1
	tsa_entry 0x03D, hflip=1, vflip=1
	tsa_entry 0x03C, hflip=1, vflip=1
	tsa_entry 0x03B, hflip=1, vflip=1
	tsa_entry 0x03A, hflip=1, vflip=1
	tsa_entry 0x039, hflip=1, vflip=1
	tsa_entry 0x038, hflip=1, vflip=1
	tsa_entry 0x037, hflip=1, vflip=1
	tsa_entry 0x036, hflip=1, vflip=1
	tsa_entry 0x035, hflip=1, vflip=1
	tsa_entry 0x034, hflip=1, vflip=1
	tsa_entry 0x033, hflip=1, vflip=1
	tsa_entry 0x032, hflip=1, vflip=1
	tsa_entry 0x031, hflip=1, vflip=1
	tsa_entry 0x030, hflip=1, vflip=1
	tsa_entry 0x02F, hflip=1, vflip=1
	tsa_entry 0x02E, hflip=1, vflip=1
	tsa_entry 0x02D, hflip=1, vflip=1
	tsa_entry 0x02C, hflip=1, vflip=1
	tsa_entry 0x02C, vflip=1
	tsa_entry 0x02D, vflip=1
	tsa_entry 0x02E, vflip=1
	tsa_entry 0x02F, vflip=1
	tsa_entry 0x030, vflip=1
	tsa_entry 0x031, vflip=1
	tsa_entry 0x032, vflip=1
	tsa_entry 0x033, vflip=1
	tsa_entry 0x034, vflip=1
	tsa_entry 0x035, vflip=1
	tsa_entry 0x036, vflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
