	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x0DB, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x0E2, hflip=1
	tsa_entry 0x0E1, hflip=1
	tsa_entry 0x0E0, hflip=1
	tsa_entry 0x0DF, hflip=1
	tsa_entry 0x0DE, hflip=1
	tsa_entry 0x0DD, hflip=1
	tsa_entry 0x0DC, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x0E9, hflip=1
	tsa_entry 0x0E8, hflip=1
	tsa_entry 0x0E7, hflip=1
	tsa_entry 0x0E6, hflip=1
	tsa_entry 0x0E5, hflip=1
	tsa_entry 0x0E4, hflip=1
	tsa_entry 0x0E3, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x0EF, hflip=1
	tsa_entry 0x0EE, hflip=1
	tsa_entry 0x0ED, hflip=1
	tsa_entry 0x0EC, hflip=1
	tsa_entry 0x0EB, hflip=1
	tsa_entry 0x0EA, hflip=1
	tsa_entry 0x08F, vflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x0F5, hflip=1
	tsa_entry 0x0F4, hflip=1
	tsa_entry 0x0F3, hflip=1
	tsa_entry 0x0F2, hflip=1
	tsa_entry 0x0F1, hflip=1
	tsa_entry 0x0F0, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x0C7, hflip=1
	tsa_entry 0x0C6, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x0F9, hflip=1
	tsa_entry 0x0F8, hflip=1
	tsa_entry 0x0F7, hflip=1
	tsa_entry 0x0F6, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x08F, hflip=1, vflip=1
	tsa_entry 0x0FB, hflip=1
	tsa_entry 0x0FA, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
