	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x00A, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x009, hflip=1
	tsa_entry 0x008, hflip=1
	tsa_entry 0x007, hflip=1
	tsa_entry 0x006, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x01A, hflip=1
	tsa_entry 0x019, hflip=1
	tsa_entry 0x018, hflip=1
	tsa_entry 0x017, hflip=1
	tsa_entry 0x016, hflip=1
	tsa_entry 0x015, hflip=1
	tsa_entry 0x014, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x029, hflip=1
	tsa_entry 0x028, hflip=1
	tsa_entry 0x027, hflip=1
	tsa_entry 0x026, hflip=1
	tsa_entry 0x025, hflip=1
	tsa_entry 0x024, hflip=1
	tsa_entry 0x023, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x037, hflip=1
	tsa_entry 0x036, hflip=1
	tsa_entry 0x035, hflip=1
	tsa_entry 0x034, hflip=1
	tsa_entry 0x033, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x045, hflip=1
	tsa_entry 0x044, hflip=1
	tsa_entry 0x043, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x042, hflip=1
	tsa_entry 0x041, hflip=1
	tsa_entry 0x040, hflip=1
	tsa_entry 0x03F, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x04E, hflip=1
	tsa_entry 0x04D, hflip=1
	tsa_entry 0x04C, hflip=1
	tsa_entry 0x04B, hflip=1
	tsa_entry 0x042, vflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x053, hflip=1
	tsa_entry 0x02B, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
