	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x0A0, hflip=1
	tsa_entry 0x09F, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x09E, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x0AE, hflip=1
	tsa_entry 0x0AD, hflip=1
	tsa_entry 0x05F, hflip=1
	tsa_entry 0x0AC, hflip=1
	tsa_entry 0x0AB, hflip=1
	tsa_entry 0x0AA, hflip=1
	tsa_entry 0x0A9, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x0BB, hflip=1
	tsa_entry 0x0BA, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x0B9, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x0B8, hflip=1
	tsa_entry 0x0B7, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x0C7, hflip=1
	tsa_entry 0x0C6, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x0C5, hflip=1
	tsa_entry 0x0C4, hflip=1
	tsa_entry 0x0C3, hflip=1
	tsa_entry 0x0C2, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x0CE, hflip=1
	tsa_entry 0x0CD, hflip=1
	tsa_entry 0x0CC, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x0D4, hflip=1
	tsa_entry 0x05F, vflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
