	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x017, hflip=1
	tsa_entry 0x016, hflip=1
	tsa_entry 0x015, hflip=1
	tsa_entry 0x014, hflip=1
	tsa_entry 0x013, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x01A, hflip=1
	tsa_entry 0x019, hflip=1
	tsa_entry 0x018, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x01E, hflip=1
	tsa_entry 0x01D, hflip=1
	tsa_entry 0x01C, hflip=1
	tsa_entry 0x01B, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x023, hflip=1
	tsa_entry 0x022, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x021, hflip=1
	tsa_entry 0x020, hflip=1
	tsa_entry 0x038, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x024, hflip=1
	tsa_entry 0x004, vflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
