	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x005, hflip=1
	tsa_entry 0x004, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x002, hflip=1
	tsa_entry 0x001, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x013, hflip=1
	tsa_entry 0x012, hflip=1
	tsa_entry 0x011, hflip=1
	tsa_entry 0x010, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x00E, hflip=1
	tsa_entry 0x00D, hflip=1
	tsa_entry 0x00C, hflip=1
	tsa_entry 0x00B, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x022, hflip=1
	tsa_entry 0x021, hflip=1
	tsa_entry 0x020, hflip=1
	tsa_entry 0x01F, hflip=1
	tsa_entry 0x01E, hflip=1
	tsa_entry 0x01D, hflip=1
	tsa_entry 0x01C, hflip=1
	tsa_entry 0x01B, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x032, hflip=1
	tsa_entry 0x031, hflip=1
	tsa_entry 0x030, hflip=1
	tsa_entry 0x02F, hflip=1
	tsa_entry 0x02E, hflip=1
	tsa_entry 0x02D, hflip=1
	tsa_entry 0x02C, hflip=1
	tsa_entry 0x02B, hflip=1
	tsa_entry 0x02A, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x03E, hflip=1
	tsa_entry 0x03D, hflip=1
	tsa_entry 0x03C, hflip=1
	tsa_entry 0x03B, hflip=1
	tsa_entry 0x03A, hflip=1
	tsa_entry 0x039, hflip=1
	tsa_entry 0x038, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x02A, hflip=1, vflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x04A, hflip=1
	tsa_entry 0x049, hflip=1
	tsa_entry 0x048, hflip=1
	tsa_entry 0x047, hflip=1
	tsa_entry 0x046, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x052
	tsa_entry 0x052, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x051, hflip=1
	tsa_entry 0x050, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x055, hflip=1
	tsa_entry 0x054, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
