	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x07E, hflip=1
	tsa_entry 0x07D, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x087, hflip=1
	tsa_entry 0x086, hflip=1
	tsa_entry 0x085, hflip=1
	tsa_entry 0x084, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x093, hflip=1
	tsa_entry 0x092, hflip=1
	tsa_entry 0x091, hflip=1
	tsa_entry 0x090, hflip=1
	tsa_entry 0x08F, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x0A0, hflip=1
	tsa_entry 0x09F, hflip=1
	tsa_entry 0x09E, hflip=1
	tsa_entry 0x042, hflip=1, vflip=1
	tsa_entry 0x09D, hflip=1
	tsa_entry 0x09C, hflip=1
	tsa_entry 0x09B, hflip=1
	tsa_entry 0x09A, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x0AB, hflip=1
	tsa_entry 0x0AA, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x0A9, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
