	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x05A, hflip=1
	tsa_entry 0x059, hflip=1
	tsa_entry 0x058, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x057, hflip=1
	tsa_entry 0x056, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x066, hflip=1
	tsa_entry 0x065, hflip=1
	tsa_entry 0x064, hflip=1
	tsa_entry 0x063, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x062, hflip=1
	tsa_entry 0x061, hflip=1
	tsa_entry 0x060, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x073, hflip=1
	tsa_entry 0x072, hflip=1
	tsa_entry 0x071, hflip=1
	tsa_entry 0x070, hflip=1
	tsa_entry 0x06F, hflip=1
	tsa_entry 0x06E, hflip=1
	tsa_entry 0x06D, hflip=1
	tsa_entry 0x06C, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x082, hflip=1
	tsa_entry 0x081, hflip=1
	tsa_entry 0x080, hflip=1
	tsa_entry 0x07F, hflip=1
	tsa_entry 0x07E, hflip=1
	tsa_entry 0x07D, hflip=1
	tsa_entry 0x07C, hflip=1
	tsa_entry 0x046, hflip=1, vflip=1
	tsa_entry 0x07B, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x08A, hflip=1
	tsa_entry 0x089, hflip=1
	tsa_entry 0x088, hflip=1
	tsa_entry 0x087, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x058, hflip=1, vflip=1
	tsa_entry 0x093, hflip=1
	tsa_entry 0x092, hflip=1
	tsa_entry 0x091, hflip=1
	tsa_entry 0x042, vflip=1
	tsa_entry 0x090, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x099
	tsa_entry 0x099, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x098, hflip=1
	tsa_entry 0x097, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
