	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x18E, pal=1
	tsa_entry 0x18F, pal=1
	tsa_entry 0x190, pal=1
	tsa_entry 0x191, pal=1
	tsa_entry 0x192, pal=1
	tsa_entry 0x193, pal=1
	tsa_entry 0x194, pal=1
	tsa_entry 0x195, pal=1
	tsa_entry 0x000
	tsa_entry 0x001
	tsa_entry 0x002
	tsa_entry 0x003
	tsa_entry 0x004
	tsa_entry 0x005
	tsa_entry 0x006
	tsa_entry 0x007
	tsa_entry 0x008
	tsa_entry 0x009
	tsa_entry 0x00A
	tsa_entry 0x00B
	tsa_entry 0x00C
	tsa_entry 0x00D
	tsa_entry 0x00E
	tsa_entry 0x00E, hflip=1
	tsa_entry 0x00D, hflip=1
	tsa_entry 0x00C, hflip=1
	tsa_entry 0x00B, hflip=1
	tsa_entry 0x00A, hflip=1
	tsa_entry 0x009, hflip=1
	tsa_entry 0x008, hflip=1
	tsa_entry 0x007, hflip=1
	tsa_entry 0x006, hflip=1
	tsa_entry 0x005, hflip=1
	tsa_entry 0x004, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x002, hflip=1
	tsa_entry 0x001, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x195, pal=1, hflip=1
	tsa_entry 0x194, pal=1, hflip=1
	tsa_entry 0x193, pal=1, hflip=1
	tsa_entry 0x192, pal=1, hflip=1
	tsa_entry 0x191, pal=1, hflip=1
	tsa_entry 0x190, pal=1, hflip=1
	tsa_entry 0x18F, pal=1, hflip=1
	tsa_entry 0x18E, pal=1, hflip=1
	tsa_entry 0x1AA, pal=1
	tsa_entry 0x1AB, pal=1
	tsa_entry 0x1AC, pal=1
	tsa_entry 0x1AD, pal=1
	tsa_entry 0x1AE, pal=1
	tsa_entry 0x1AF, pal=1
	tsa_entry 0x1B0, pal=1
	tsa_entry 0x1B1, pal=1
	tsa_entry 0x00F, pal=1
	tsa_entry 0x010, pal=1
	tsa_entry 0x011, pal=1
	tsa_entry 0x012, pal=1
	tsa_entry 0x013, pal=1
	tsa_entry 0x014, pal=1
	tsa_entry 0x015, pal=1
	tsa_entry 0x016, pal=1
	tsa_entry 0x017, pal=1
	tsa_entry 0x018, pal=1
	tsa_entry 0x019, pal=1
	tsa_entry 0x01A, pal=1
	tsa_entry 0x01B, pal=1
	tsa_entry 0x01C, pal=1
	tsa_entry 0x01D, pal=1
	tsa_entry 0x01D, pal=1, hflip=1
	tsa_entry 0x01C, pal=1, hflip=1
	tsa_entry 0x01B, pal=1, hflip=1
	tsa_entry 0x01A, pal=1, hflip=1
	tsa_entry 0x019, pal=1, hflip=1
	tsa_entry 0x018, pal=1, hflip=1
	tsa_entry 0x017, pal=1, hflip=1
	tsa_entry 0x016, pal=1, hflip=1
	tsa_entry 0x015, pal=1, hflip=1
	tsa_entry 0x014, pal=1, hflip=1
	tsa_entry 0x013, pal=1, hflip=1
	tsa_entry 0x012, pal=1, hflip=1
	tsa_entry 0x011, pal=1, hflip=1
	tsa_entry 0x010, pal=1, hflip=1
	tsa_entry 0x00F, pal=1, hflip=1
	tsa_entry 0x1B1, pal=1, hflip=1
	tsa_entry 0x1B0, pal=1, hflip=1
	tsa_entry 0x1AF, pal=1, hflip=1
	tsa_entry 0x1AE, pal=1, hflip=1
	tsa_entry 0x1AD, pal=1, hflip=1
	tsa_entry 0x1AC, pal=1, hflip=1
	tsa_entry 0x1AB, pal=1, hflip=1
	tsa_entry 0x1AA, pal=1, hflip=1
	tsa_entry 0x1C5, pal=1
	tsa_entry 0x1C6, pal=1
	tsa_entry 0x1C7, pal=1
	tsa_entry 0x1C8, pal=1
	tsa_entry 0x1C9, pal=1
	tsa_entry 0x1CA, pal=1
	tsa_entry 0x1CB, pal=1
	tsa_entry 0x1CC, pal=1
	tsa_entry 0x01E, pal=1
	tsa_entry 0x01F, pal=1
	tsa_entry 0x020, pal=1
	tsa_entry 0x021, pal=1
	tsa_entry 0x022, pal=1
	tsa_entry 0x023, pal=1
	tsa_entry 0x024, pal=1
	tsa_entry 0x025, pal=1
	tsa_entry 0x026, pal=1
	tsa_entry 0x027, pal=1
	tsa_entry 0x028, pal=1
	tsa_entry 0x029, pal=1
	tsa_entry 0x02A, pal=1
	tsa_entry 0x02B, pal=1
	tsa_entry 0x02C, pal=1
	tsa_entry 0x02C, pal=1, hflip=1
	tsa_entry 0x02B, pal=1, hflip=1
	tsa_entry 0x02A, pal=1, hflip=1
	tsa_entry 0x029, pal=1, hflip=1
	tsa_entry 0x028, pal=1, hflip=1
	tsa_entry 0x027, pal=1, hflip=1
	tsa_entry 0x026, pal=1, hflip=1
	tsa_entry 0x025, pal=1, hflip=1
	tsa_entry 0x024, pal=1, hflip=1
	tsa_entry 0x023, pal=1, hflip=1
	tsa_entry 0x022, pal=1, hflip=1
	tsa_entry 0x021, pal=1, hflip=1
	tsa_entry 0x020, pal=1, hflip=1
	tsa_entry 0x01F, pal=1, hflip=1
	tsa_entry 0x01E, pal=1, hflip=1
	tsa_entry 0x1CC, pal=1, hflip=1
	tsa_entry 0x1CB, pal=1, hflip=1
	tsa_entry 0x1CA, pal=1, hflip=1
	tsa_entry 0x1C9, pal=1, hflip=1
	tsa_entry 0x1C8, pal=1, hflip=1
	tsa_entry 0x1C7, pal=1, hflip=1
	tsa_entry 0x1C6, pal=1, hflip=1
	tsa_entry 0x1C5, pal=1, hflip=1
	tsa_entry 0x1DF, pal=1
	tsa_entry 0x1E0, pal=1
	tsa_entry 0x1E1, pal=1
	tsa_entry 0x1E2, pal=1
	tsa_entry 0x1E3, pal=1
	tsa_entry 0x1E4, pal=1
	tsa_entry 0x1E5, pal=1
	tsa_entry 0x1E6, pal=1
	tsa_entry 0x030, pal=1
	tsa_entry 0x031, pal=1
	tsa_entry 0x032, pal=1
	tsa_entry 0x033, pal=1
	tsa_entry 0x034, pal=1
	tsa_entry 0x035, pal=1
	tsa_entry 0x036, pal=1
	tsa_entry 0x037, pal=1
	tsa_entry 0x038, pal=1
	tsa_entry 0x039, pal=1
	tsa_entry 0x03A, pal=1
	tsa_entry 0x03B, pal=1
	tsa_entry 0x03C, pal=1
	tsa_entry 0x03D, pal=1
	tsa_entry 0x03E, pal=1
	tsa_entry 0x03E, pal=1, hflip=1
	tsa_entry 0x03D, pal=1, hflip=1
	tsa_entry 0x03C, pal=1, hflip=1
	tsa_entry 0x03B, pal=1, hflip=1
	tsa_entry 0x03A, pal=1, hflip=1
	tsa_entry 0x039, pal=1, hflip=1
	tsa_entry 0x038, pal=1, hflip=1
	tsa_entry 0x037, pal=1, hflip=1
	tsa_entry 0x036, pal=1, hflip=1
	tsa_entry 0x035, pal=1, hflip=1
	tsa_entry 0x034, pal=1, hflip=1
	tsa_entry 0x033, pal=1, hflip=1
	tsa_entry 0x032, pal=1, hflip=1
	tsa_entry 0x031, pal=1, hflip=1
	tsa_entry 0x030, pal=1, hflip=1
	tsa_entry 0x1E6, pal=1, hflip=1
	tsa_entry 0x1E5, pal=1, hflip=1
	tsa_entry 0x1E4, pal=1, hflip=1
	tsa_entry 0x1E3, pal=1, hflip=1
	tsa_entry 0x1E2, pal=1, hflip=1
	tsa_entry 0x1E1, pal=1, hflip=1
	tsa_entry 0x1E0, pal=1, hflip=1
	tsa_entry 0x1DF, pal=1, hflip=1
	tsa_entry 0x1F8, pal=1
	tsa_entry 0x1F9, pal=1
	tsa_entry 0x1FA, pal=1
	tsa_entry 0x1FB, pal=1
	tsa_entry 0x1FC, pal=1
	tsa_entry 0x1FD, pal=1
	tsa_entry 0x1FE, pal=1
	tsa_entry 0x1FF, pal=1
	tsa_entry 0x03F, pal=1
	tsa_entry 0x040, pal=1
	tsa_entry 0x041, pal=1
	tsa_entry 0x042, pal=1
	tsa_entry 0x043, pal=1
	tsa_entry 0x044, pal=1
	tsa_entry 0x045, pal=1
	tsa_entry 0x046, pal=1
	tsa_entry 0x047, pal=1
	tsa_entry 0x048, pal=1
	tsa_entry 0x049, pal=1
	tsa_entry 0x04A, pal=1
	tsa_entry 0x04B, pal=2
	tsa_entry 0x04C, pal=2
	tsa_entry 0x04D, pal=1
	tsa_entry 0x04D, pal=1, hflip=1
	tsa_entry 0x04C, pal=2, hflip=1
	tsa_entry 0x04B, pal=2, hflip=1
	tsa_entry 0x04A, pal=1, hflip=1
	tsa_entry 0x049, pal=1, hflip=1
	tsa_entry 0x048, pal=1, hflip=1
	tsa_entry 0x047, pal=1, hflip=1
	tsa_entry 0x046, pal=1, hflip=1
	tsa_entry 0x045, pal=1, hflip=1
	tsa_entry 0x044, pal=1, hflip=1
	tsa_entry 0x043, pal=1, hflip=1
	tsa_entry 0x042, pal=1, hflip=1
	tsa_entry 0x041, pal=1, hflip=1
	tsa_entry 0x040, pal=1, hflip=1
	tsa_entry 0x03F, pal=1, hflip=1
	tsa_entry 0x1FF, pal=1, hflip=1
	tsa_entry 0x1FE, pal=1, hflip=1
	tsa_entry 0x1FD, pal=1, hflip=1
	tsa_entry 0x1FC, pal=1, hflip=1
	tsa_entry 0x1FB, pal=1, hflip=1
	tsa_entry 0x1FA, pal=1, hflip=1
	tsa_entry 0x1F9, pal=1, hflip=1
	tsa_entry 0x1F8, pal=1, hflip=1
	tsa_entry 0x19E, pal=1
	tsa_entry 0x19F, pal=1
	tsa_entry 0x1A0, pal=1
	tsa_entry 0x1A1, pal=1
	tsa_entry 0x1A2, pal=1
	tsa_entry 0x1A3, pal=1
	tsa_entry 0x1A4, pal=1
	tsa_entry 0x1A5, pal=1
	tsa_entry 0x050, pal=1
	tsa_entry 0x051, pal=1
	tsa_entry 0x052, pal=1
	tsa_entry 0x053, pal=1
	tsa_entry 0x054, pal=1
	tsa_entry 0x055, pal=1
	tsa_entry 0x056, pal=1
	tsa_entry 0x057, pal=1
	tsa_entry 0x058, pal=1
	tsa_entry 0x059, pal=1
	tsa_entry 0x05A, pal=1
	tsa_entry 0x05B, pal=1
	tsa_entry 0x05C, pal=1
	tsa_entry 0x05D, pal=1
	tsa_entry 0x05E, pal=1
	tsa_entry 0x05E, pal=1, hflip=1
	tsa_entry 0x05D, pal=1, hflip=1
	tsa_entry 0x05C, pal=1, hflip=1
	tsa_entry 0x05B, pal=1, hflip=1
	tsa_entry 0x05A, pal=1, hflip=1
	tsa_entry 0x059, pal=1, hflip=1
	tsa_entry 0x058, pal=1, hflip=1
	tsa_entry 0x057, pal=1, hflip=1
	tsa_entry 0x056, pal=1, hflip=1
	tsa_entry 0x055, pal=1, hflip=1
	tsa_entry 0x054, pal=1, hflip=1
	tsa_entry 0x053, pal=1, hflip=1
	tsa_entry 0x052, pal=1, hflip=1
	tsa_entry 0x051, pal=1, hflip=1
	tsa_entry 0x050, pal=1, hflip=1
	tsa_entry 0x1A5, pal=1, hflip=1
	tsa_entry 0x1A4, pal=1, hflip=1
	tsa_entry 0x1A3, pal=1, hflip=1
	tsa_entry 0x1A2, pal=1, hflip=1
	tsa_entry 0x1A1, pal=1, hflip=1
	tsa_entry 0x1A0, pal=1, hflip=1
	tsa_entry 0x19F, pal=1, hflip=1
	tsa_entry 0x19E, pal=1, hflip=1
	tsa_entry 0x1BA, pal=1
	tsa_entry 0x1BB, pal=1
	tsa_entry 0x1BC, pal=1
	tsa_entry 0x1BD, pal=1
	tsa_entry 0x1BE, pal=1
	tsa_entry 0x1BF, pal=1
	tsa_entry 0x1C0, pal=1
	tsa_entry 0x1C1, pal=1
	tsa_entry 0x065, pal=1
	tsa_entry 0x066, pal=1
	tsa_entry 0x067, pal=1
	tsa_entry 0x068, pal=1
	tsa_entry 0x069, pal=1
	tsa_entry 0x06A, pal=1
	tsa_entry 0x06B, pal=1
	tsa_entry 0x06C, pal=1
	tsa_entry 0x06D, pal=1
	tsa_entry 0x06E, pal=1
	tsa_entry 0x06F, pal=1
	tsa_entry 0x070, pal=1
	tsa_entry 0x071, pal=2
	tsa_entry 0x072, pal=2
	tsa_entry 0x073, pal=2
	tsa_entry 0x073, pal=2, hflip=1
	tsa_entry 0x072, pal=2, hflip=1
	tsa_entry 0x071, pal=2, hflip=1
	tsa_entry 0x070, pal=1, hflip=1
	tsa_entry 0x06F, pal=1, hflip=1
	tsa_entry 0x06E, pal=1, hflip=1
	tsa_entry 0x06D, pal=1, hflip=1
	tsa_entry 0x06C, pal=1, hflip=1
	tsa_entry 0x06B, pal=1, hflip=1
	tsa_entry 0x06A, pal=1, hflip=1
	tsa_entry 0x069, pal=1, hflip=1
	tsa_entry 0x068, pal=1, hflip=1
	tsa_entry 0x067, pal=1, hflip=1
	tsa_entry 0x066, pal=1, hflip=1
	tsa_entry 0x065, pal=1, hflip=1
	tsa_entry 0x1C1, pal=1, hflip=1
	tsa_entry 0x1C0, pal=1, hflip=1
	tsa_entry 0x1BF, pal=1, hflip=1
	tsa_entry 0x1BE, pal=1, hflip=1
	tsa_entry 0x1BD, pal=1, hflip=1
	tsa_entry 0x1BC, pal=1, hflip=1
	tsa_entry 0x1BB, pal=1, hflip=1
	tsa_entry 0x1BA, pal=1, hflip=1
	tsa_entry 0x1D4, pal=2
	tsa_entry 0x1D5, pal=2
	tsa_entry 0x1D6, pal=2
	tsa_entry 0x1D7, pal=2
	tsa_entry 0x1D8, pal=2
	tsa_entry 0x1D9, pal=2
	tsa_entry 0x1DA, pal=2
	tsa_entry 0x1DB, pal=2
	tsa_entry 0x075, pal=2
	tsa_entry 0x076, pal=2
	tsa_entry 0x077, pal=2
	tsa_entry 0x078, pal=2
	tsa_entry 0x079, pal=1
	tsa_entry 0x07A, pal=1
	tsa_entry 0x07B, pal=1
	tsa_entry 0x07C, pal=1
	tsa_entry 0x07D, pal=1
	tsa_entry 0x07E, pal=1
	tsa_entry 0x07F, pal=1
	tsa_entry 0x080, pal=1
	tsa_entry 0x081, pal=2
	tsa_entry 0x082, pal=2
	tsa_entry 0x083, pal=2
	tsa_entry 0x083, pal=2, hflip=1
	tsa_entry 0x082, pal=2, hflip=1
	tsa_entry 0x081, pal=2, hflip=1
	tsa_entry 0x080, pal=1, hflip=1
	tsa_entry 0x07F, pal=1, hflip=1
	tsa_entry 0x07E, pal=1, hflip=1
	tsa_entry 0x07D, pal=1, hflip=1
	tsa_entry 0x07C, pal=1, hflip=1
	tsa_entry 0x07B, pal=1, hflip=1
	tsa_entry 0x07A, pal=1, hflip=1
	tsa_entry 0x079, pal=1, hflip=1
	tsa_entry 0x078, pal=2, hflip=1
	tsa_entry 0x077, pal=2, hflip=1
	tsa_entry 0x076, pal=2, hflip=1
	tsa_entry 0x075, pal=2, hflip=1
	tsa_entry 0x1DB, pal=2, hflip=1
	tsa_entry 0x1DA, pal=2, hflip=1
	tsa_entry 0x1D9, pal=2, hflip=1
	tsa_entry 0x1D8, pal=2, hflip=1
	tsa_entry 0x1D7, pal=2, hflip=1
	tsa_entry 0x1D6, pal=2, hflip=1
	tsa_entry 0x1D5, pal=2, hflip=1
	tsa_entry 0x1D4, pal=2, hflip=1
	tsa_entry 0x1EF, pal=2
	tsa_entry 0x1F0, pal=2
	tsa_entry 0x1F1, pal=2
	tsa_entry 0x1F2, pal=2
	tsa_entry 0x1F3, pal=2
	tsa_entry 0x1F4, pal=2
	tsa_entry 0x1F5, pal=2
	tsa_entry 0x1F6, pal=2
	tsa_entry 0x084, pal=2
	tsa_entry 0x085, pal=2
	tsa_entry 0x086, pal=2
	tsa_entry 0x087, pal=2
	tsa_entry 0x088, pal=2
	tsa_entry 0x089, pal=2
	tsa_entry 0x08A, pal=2
	tsa_entry 0x08B, pal=2
	tsa_entry 0x08C, pal=2
	tsa_entry 0x08D, pal=2
	tsa_entry 0x08E, pal=2
	tsa_entry 0x08F, pal=2
	tsa_entry 0x090, pal=2
	tsa_entry 0x091, pal=2
	tsa_entry 0x092, pal=2
	tsa_entry 0x092, pal=2, hflip=1
	tsa_entry 0x091, pal=2, hflip=1
	tsa_entry 0x090, pal=2, hflip=1
	tsa_entry 0x08F, pal=2, hflip=1
	tsa_entry 0x08E, pal=2, hflip=1
	tsa_entry 0x08D, pal=2, hflip=1
	tsa_entry 0x08C, pal=2, hflip=1
	tsa_entry 0x08B, pal=2, hflip=1
	tsa_entry 0x08A, pal=2, hflip=1
	tsa_entry 0x089, pal=2, hflip=1
	tsa_entry 0x088, pal=2, hflip=1
	tsa_entry 0x087, pal=2, hflip=1
	tsa_entry 0x086, pal=2, hflip=1
	tsa_entry 0x085, pal=2, hflip=1
	tsa_entry 0x084, pal=2, hflip=1
	tsa_entry 0x1F6, pal=2, hflip=1
	tsa_entry 0x1F5, pal=2, hflip=1
	tsa_entry 0x1F4, pal=2, hflip=1
	tsa_entry 0x1F3, pal=2, hflip=1
	tsa_entry 0x1F2, pal=2, hflip=1
	tsa_entry 0x1F1, pal=2, hflip=1
	tsa_entry 0x1F0, pal=2, hflip=1
	tsa_entry 0x1EF, pal=2, hflip=1
	tsa_entry 0x207, pal=3
	tsa_entry 0x208, pal=3
	tsa_entry 0x209, pal=3
	tsa_entry 0x20A, pal=3
	tsa_entry 0x20B, pal=3
	tsa_entry 0x20C, pal=3
	tsa_entry 0x20D, pal=3
	tsa_entry 0x20E, pal=3
	tsa_entry 0x093, pal=3
	tsa_entry 0x094, pal=3
	tsa_entry 0x095, pal=3
	tsa_entry 0x096, pal=3
	tsa_entry 0x097, pal=3
	tsa_entry 0x098, pal=3
	tsa_entry 0x099, pal=3
	tsa_entry 0x09A, pal=3
	tsa_entry 0x09B, pal=3
	tsa_entry 0x09C, pal=3
	tsa_entry 0x09D, pal=3
	tsa_entry 0x09E, pal=3
	tsa_entry 0x09F, pal=3
	tsa_entry 0x0A0, pal=3
	tsa_entry 0x0A1, pal=3
	tsa_entry 0x0A1, pal=3, hflip=1
	tsa_entry 0x0A0, pal=3, hflip=1
	tsa_entry 0x09F, pal=3, hflip=1
	tsa_entry 0x09E, pal=3, hflip=1
	tsa_entry 0x09D, pal=3, hflip=1
	tsa_entry 0x09C, pal=3, hflip=1
	tsa_entry 0x09B, pal=3, hflip=1
	tsa_entry 0x09A, pal=3, hflip=1
	tsa_entry 0x099, pal=3, hflip=1
	tsa_entry 0x098, pal=3, hflip=1
	tsa_entry 0x097, pal=3, hflip=1
	tsa_entry 0x096, pal=3, hflip=1
	tsa_entry 0x095, pal=3, hflip=1
	tsa_entry 0x094, pal=3, hflip=1
	tsa_entry 0x093, pal=3, hflip=1
	tsa_entry 0x20E, pal=3, hflip=1
	tsa_entry 0x20D, pal=3, hflip=1
	tsa_entry 0x20C, pal=3, hflip=1
	tsa_entry 0x20B, pal=3, hflip=1
	tsa_entry 0x20A, pal=3, hflip=1
	tsa_entry 0x209, pal=3, hflip=1
	tsa_entry 0x208, pal=3, hflip=1
	tsa_entry 0x207, pal=3, hflip=1
	tsa_entry 0x196, pal=3
	tsa_entry 0x197, pal=3
	tsa_entry 0x198, pal=3
	tsa_entry 0x199, pal=3
	tsa_entry 0x19A, pal=3
	tsa_entry 0x19B, pal=3
	tsa_entry 0x19C, pal=3
	tsa_entry 0x19D, pal=3
	tsa_entry 0x0A6, pal=3
	tsa_entry 0x0A7, pal=3
	tsa_entry 0x0A8, pal=3
	tsa_entry 0x0A9, pal=3
	tsa_entry 0x0AA, pal=3
	tsa_entry 0x0AB, pal=3
	tsa_entry 0x0AC, pal=3
	tsa_entry 0x0AD, pal=3
	tsa_entry 0x0AE, pal=3
	tsa_entry 0x0AF, pal=3
	tsa_entry 0x0B0, pal=3
	tsa_entry 0x0B1, pal=3
	tsa_entry 0x0B2, pal=3
	tsa_entry 0x0B3, pal=3
	tsa_entry 0x0B4, pal=3
	tsa_entry 0x0B4, pal=3, hflip=1
	tsa_entry 0x0B3, pal=3, hflip=1
	tsa_entry 0x0B2, pal=3, hflip=1
	tsa_entry 0x0B1, pal=3, hflip=1
	tsa_entry 0x0B0, pal=3, hflip=1
	tsa_entry 0x0AF, pal=3, hflip=1
	tsa_entry 0x0AE, pal=3, hflip=1
	tsa_entry 0x0AD, pal=3, hflip=1
	tsa_entry 0x0AC, pal=3, hflip=1
	tsa_entry 0x0AB, pal=3, hflip=1
	tsa_entry 0x0AA, pal=3, hflip=1
	tsa_entry 0x0A9, pal=3, hflip=1
	tsa_entry 0x0A8, pal=3, hflip=1
	tsa_entry 0x0A7, pal=3, hflip=1
	tsa_entry 0x0A6, pal=3, hflip=1
	tsa_entry 0x19D, pal=3, hflip=1
	tsa_entry 0x19C, pal=3, hflip=1
	tsa_entry 0x19B, pal=3, hflip=1
	tsa_entry 0x19A, pal=3, hflip=1
	tsa_entry 0x199, pal=3, hflip=1
	tsa_entry 0x198, pal=3, hflip=1
	tsa_entry 0x197, pal=3, hflip=1
	tsa_entry 0x196, pal=3, hflip=1
	tsa_entry 0x1B2, pal=3
	tsa_entry 0x1B3, pal=3
	tsa_entry 0x1B4, pal=3
	tsa_entry 0x1B5, pal=3
	tsa_entry 0x1B6, pal=3
	tsa_entry 0x1B7, pal=3
	tsa_entry 0x1B8, pal=3
	tsa_entry 0x1B9, pal=3
	tsa_entry 0x0BF, pal=3
	tsa_entry 0x0C0, pal=3
	tsa_entry 0x0C1, pal=3
	tsa_entry 0x0C2, pal=3
	tsa_entry 0x0C3, pal=3
	tsa_entry 0x0C4, pal=3
	tsa_entry 0x0C5, pal=3
	tsa_entry 0x0C6, pal=3
	tsa_entry 0x0C7, pal=3
	tsa_entry 0x0C8, pal=3
	tsa_entry 0x0C9, pal=3
	tsa_entry 0x0CA, pal=3
	tsa_entry 0x0CB, pal=3
	tsa_entry 0x0CC, pal=3
	tsa_entry 0x0CD, pal=3
	tsa_entry 0x0CD, pal=3, hflip=1
	tsa_entry 0x0CC, pal=3, hflip=1
	tsa_entry 0x0CB, pal=3, hflip=1
	tsa_entry 0x0CA, pal=3, hflip=1
	tsa_entry 0x0C9, pal=3, hflip=1
	tsa_entry 0x0C8, pal=3, hflip=1
	tsa_entry 0x0C7, pal=3, hflip=1
	tsa_entry 0x0C6, pal=3, hflip=1
	tsa_entry 0x0C5, pal=3, hflip=1
	tsa_entry 0x0C4, pal=3, hflip=1
	tsa_entry 0x0C3, pal=3, hflip=1
	tsa_entry 0x0C2, pal=3, hflip=1
	tsa_entry 0x0C1, pal=3, hflip=1
	tsa_entry 0x0C0, pal=3, hflip=1
	tsa_entry 0x0BF, pal=3, hflip=1
	tsa_entry 0x1B9, pal=3, hflip=1
	tsa_entry 0x1B8, pal=3, hflip=1
	tsa_entry 0x1B7, pal=3, hflip=1
	tsa_entry 0x1B6, pal=3, hflip=1
	tsa_entry 0x1B5, pal=3, hflip=1
	tsa_entry 0x1B4, pal=3, hflip=1
	tsa_entry 0x1B3, pal=3, hflip=1
	tsa_entry 0x1B2, pal=3, hflip=1
	tsa_entry 0x1CD, pal=3
	tsa_entry 0x1CE, pal=3
	tsa_entry 0x1CF, pal=3
	tsa_entry 0x1D0, pal=3
	tsa_entry 0x1D1, pal=3
	tsa_entry 0x1D2, pal=3
	tsa_entry 0x0E0, pal=3
	tsa_entry 0x1D3, pal=3
	tsa_entry 0x0DA, pal=3
	tsa_entry 0x0DB, pal=3
	tsa_entry 0x0DC, pal=3
	tsa_entry 0x0DD, pal=3
	tsa_entry 0x0DE, pal=3
	tsa_entry 0x0DF, pal=3
	tsa_entry 0x0E0, pal=3
	tsa_entry 0x0E1, pal=3
	tsa_entry 0x0E2, pal=3
	tsa_entry 0x0E3, pal=3
	tsa_entry 0x0E4, pal=3
	tsa_entry 0x0E5, pal=3
	tsa_entry 0x0E6, pal=3
	tsa_entry 0x0E7, pal=3
	tsa_entry 0x0E8, pal=3
	tsa_entry 0x0E8, pal=3, hflip=1
	tsa_entry 0x0E7, pal=3, hflip=1
	tsa_entry 0x0E6, pal=3, hflip=1
	tsa_entry 0x0E5, pal=3, hflip=1
	tsa_entry 0x0E4, pal=3, hflip=1
	tsa_entry 0x0E3, pal=3, hflip=1
	tsa_entry 0x0E2, pal=3, hflip=1
	tsa_entry 0x0E1, pal=3, hflip=1
	tsa_entry 0x0E0, pal=3, hflip=1
	tsa_entry 0x0DF, pal=3, hflip=1
	tsa_entry 0x0DE, pal=3, hflip=1
	tsa_entry 0x0DD, pal=3, hflip=1
	tsa_entry 0x0DC, pal=3, hflip=1
	tsa_entry 0x0DB, pal=3, hflip=1
	tsa_entry 0x0DA, pal=3, hflip=1
	tsa_entry 0x1D3, pal=3, hflip=1
	tsa_entry 0x0E0, pal=3, hflip=1
	tsa_entry 0x1D2, pal=3, hflip=1
	tsa_entry 0x1D1, pal=3, hflip=1
	tsa_entry 0x1D0, pal=3, hflip=1
	tsa_entry 0x1CF, pal=3, hflip=1
	tsa_entry 0x1CE, pal=3, hflip=1
	tsa_entry 0x1CD, pal=3, hflip=1
	tsa_entry 0x1E7, pal=3
	tsa_entry 0x1E8, pal=3
	tsa_entry 0x1E9, pal=3
	tsa_entry 0x1EA, pal=3
	tsa_entry 0x1EB, pal=3
	tsa_entry 0x1EC, pal=3
	tsa_entry 0x1ED, pal=3
	tsa_entry 0x1EE, pal=3
	tsa_entry 0x0EF, pal=3
	tsa_entry 0x0F0, pal=3
	tsa_entry 0x0F1, pal=3
	tsa_entry 0x0F2, pal=3
	tsa_entry 0x0F3, pal=3
	tsa_entry 0x0F4, pal=3
	tsa_entry 0x0F5, pal=3
	tsa_entry 0x0F6, pal=3
	tsa_entry 0x0F7, pal=3
	tsa_entry 0x0F8, pal=3
	tsa_entry 0x0F9, pal=3
	tsa_entry 0x0FA, pal=3
	tsa_entry 0x0FB, pal=3
	tsa_entry 0x0FC, pal=3
	tsa_entry 0x0FD, pal=3
	tsa_entry 0x0FD, pal=3, hflip=1
	tsa_entry 0x0FC, pal=3, hflip=1
	tsa_entry 0x0FB, pal=3, hflip=1
	tsa_entry 0x0FA, pal=3, hflip=1
	tsa_entry 0x0F9, pal=3, hflip=1
	tsa_entry 0x0F8, pal=3, hflip=1
	tsa_entry 0x0F7, pal=3, hflip=1
	tsa_entry 0x0F6, pal=3, hflip=1
	tsa_entry 0x0F5, pal=3, hflip=1
	tsa_entry 0x0F4, pal=3, hflip=1
	tsa_entry 0x0F3, pal=3, hflip=1
	tsa_entry 0x0F2, pal=3, hflip=1
	tsa_entry 0x0F1, pal=3, hflip=1
	tsa_entry 0x0F0, pal=3, hflip=1
	tsa_entry 0x0EF, pal=3, hflip=1
	tsa_entry 0x1EE, pal=3, hflip=1
	tsa_entry 0x1ED, pal=3, hflip=1
	tsa_entry 0x1EC, pal=3, hflip=1
	tsa_entry 0x1EB, pal=3, hflip=1
	tsa_entry 0x1EA, pal=3, hflip=1
	tsa_entry 0x1E9, pal=3, hflip=1
	tsa_entry 0x1E8, pal=3, hflip=1
	tsa_entry 0x1E7, pal=3, hflip=1
	tsa_entry 0x1DC, pal=3
	tsa_entry 0x200, pal=3
	tsa_entry 0x201, pal=3
	tsa_entry 0x202, pal=3
	tsa_entry 0x203, pal=3
	tsa_entry 0x204, pal=3
	tsa_entry 0x205, pal=3
	tsa_entry 0x206, pal=3
	tsa_entry 0x10A, pal=3
	tsa_entry 0x10B, pal=3
	tsa_entry 0x10C, pal=3
	tsa_entry 0x10D, pal=3
	tsa_entry 0x10E, pal=3
	tsa_entry 0x10F, pal=3
	tsa_entry 0x110, pal=3
	tsa_entry 0x111, pal=3
	tsa_entry 0x112, pal=3
	tsa_entry 0x113, pal=3
	tsa_entry 0x114, pal=3
	tsa_entry 0x115, pal=3
	tsa_entry 0x116, pal=3
	tsa_entry 0x117, pal=3
	tsa_entry 0x118, pal=3
	tsa_entry 0x118, pal=3, hflip=1
	tsa_entry 0x117, pal=3, hflip=1
	tsa_entry 0x116, pal=3, hflip=1
	tsa_entry 0x115, pal=3, hflip=1
	tsa_entry 0x114, pal=3, hflip=1
	tsa_entry 0x113, pal=3, hflip=1
	tsa_entry 0x112, pal=3, hflip=1
	tsa_entry 0x111, pal=3, hflip=1
	tsa_entry 0x110, pal=3, hflip=1
	tsa_entry 0x10F, pal=3, hflip=1
	tsa_entry 0x10E, pal=3, hflip=1
	tsa_entry 0x10D, pal=3, hflip=1
	tsa_entry 0x10C, pal=3, hflip=1
	tsa_entry 0x10B, pal=3, hflip=1
	tsa_entry 0x10A, pal=3, hflip=1
	tsa_entry 0x206, pal=3, hflip=1
	tsa_entry 0x205, pal=3, hflip=1
	tsa_entry 0x204, pal=3, hflip=1
	tsa_entry 0x203, pal=3, hflip=1
	tsa_entry 0x202, pal=3, hflip=1
	tsa_entry 0x201, pal=3, hflip=1
	tsa_entry 0x200, pal=3, hflip=1
	tsa_entry 0x1DC, pal=3, hflip=1
	tsa_entry 0x1A6, pal=3
	tsa_entry 0x176, pal=3
	tsa_entry 0x177, pal=3
	tsa_entry 0x178, pal=3
	tsa_entry 0x114, pal=3
	tsa_entry 0x1A7, pal=3
	tsa_entry 0x1A8, pal=3
	tsa_entry 0x1A9, pal=3
	tsa_entry 0x127, pal=3
	tsa_entry 0x128, pal=3
	tsa_entry 0x129, pal=3
	tsa_entry 0x12A, pal=3
	tsa_entry 0x12B, pal=3
	tsa_entry 0x12C, pal=3
	tsa_entry 0x12D, pal=3
	tsa_entry 0x12E, pal=3
	tsa_entry 0x12F, pal=3
	tsa_entry 0x130, pal=3
	tsa_entry 0x131, pal=3
	tsa_entry 0x132, pal=3
	tsa_entry 0x133, pal=3
	tsa_entry 0x134, pal=3
	tsa_entry 0x135, pal=3
	tsa_entry 0x135, pal=3, hflip=1
	tsa_entry 0x134, pal=3, hflip=1
	tsa_entry 0x133, pal=3, hflip=1
	tsa_entry 0x132, pal=3, hflip=1
	tsa_entry 0x131, pal=3, hflip=1
	tsa_entry 0x130, pal=3, hflip=1
	tsa_entry 0x12F, pal=3, hflip=1
	tsa_entry 0x12E, pal=3, hflip=1
	tsa_entry 0x12D, pal=3, hflip=1
	tsa_entry 0x12C, pal=3, hflip=1
	tsa_entry 0x12B, pal=3, hflip=1
	tsa_entry 0x12A, pal=3, hflip=1
	tsa_entry 0x129, pal=3, hflip=1
	tsa_entry 0x128, pal=3, hflip=1
	tsa_entry 0x127, pal=3, hflip=1
	tsa_entry 0x1A9, pal=3, hflip=1
	tsa_entry 0x1A8, pal=3, hflip=1
	tsa_entry 0x1A7, pal=3, hflip=1
	tsa_entry 0x114, pal=3, hflip=1
	tsa_entry 0x178, pal=3, hflip=1
	tsa_entry 0x177, pal=3, hflip=1
	tsa_entry 0x176, pal=3, hflip=1
	tsa_entry 0x1A6, pal=3, hflip=1
	tsa_entry 0x1C2, pal=3
	tsa_entry 0x184, pal=3
	tsa_entry 0x185, pal=3
	tsa_entry 0x186, pal=3
	tsa_entry 0x187, pal=3
	tsa_entry 0x15C, pal=3, hflip=1
	tsa_entry 0x1C3, pal=3
	tsa_entry 0x1C4, pal=3
	tsa_entry 0x145, pal=3
	tsa_entry 0x146, pal=3
	tsa_entry 0x147, pal=3
	tsa_entry 0x148, pal=3
	tsa_entry 0x149, pal=3
	tsa_entry 0x14A, pal=3
	tsa_entry 0x14B, pal=3
	tsa_entry 0x14C, pal=3
	tsa_entry 0x14D, pal=3
	tsa_entry 0x14E, pal=3
	tsa_entry 0x14F, pal=3
	tsa_entry 0x150, pal=3
	tsa_entry 0x151, pal=3
	tsa_entry 0x152, pal=3
	tsa_entry 0x153, pal=3
	tsa_entry 0x153, pal=3, hflip=1
	tsa_entry 0x152, pal=3, hflip=1
	tsa_entry 0x151, pal=3, hflip=1
	tsa_entry 0x150, pal=3, hflip=1
	tsa_entry 0x14F, pal=3, hflip=1
	tsa_entry 0x14E, pal=3, hflip=1
	tsa_entry 0x14D, pal=3, hflip=1
	tsa_entry 0x14C, pal=3, hflip=1
	tsa_entry 0x14B, pal=3, hflip=1
	tsa_entry 0x14A, pal=3, hflip=1
	tsa_entry 0x149, pal=3, hflip=1
	tsa_entry 0x148, pal=3, hflip=1
	tsa_entry 0x147, pal=3, hflip=1
	tsa_entry 0x146, pal=3, hflip=1
	tsa_entry 0x145, pal=3, hflip=1
	tsa_entry 0x1C4, pal=3, hflip=1
	tsa_entry 0x1C3, pal=3, hflip=1
	tsa_entry 0x15C, pal=3
	tsa_entry 0x187, pal=3, hflip=1
	tsa_entry 0x186, pal=3, hflip=1
	tsa_entry 0x185, pal=3, hflip=1
	tsa_entry 0x184, pal=3, hflip=1
	tsa_entry 0x1C2, pal=3, hflip=1
	tsa_entry 0x1DC, pal=3
	tsa_entry 0x1DD, pal=3
	tsa_entry 0x164, pal=3
	tsa_entry 0x0F8, pal=3
	tsa_entry 0x165, pal=3
	tsa_entry 0x166, pal=3
	tsa_entry 0x167, pal=3
	tsa_entry 0x1DE, pal=3
	tsa_entry 0x162, pal=3
	tsa_entry 0x163, pal=3
	tsa_entry 0x164, pal=3
	tsa_entry 0x0F8, pal=3
	tsa_entry 0x165, pal=3
	tsa_entry 0x166, pal=3
	tsa_entry 0x167, pal=3
	tsa_entry 0x168, pal=3
	tsa_entry 0x169, pal=3
	tsa_entry 0x16A, pal=3
	tsa_entry 0x16B, pal=3
	tsa_entry 0x16C, pal=3
	tsa_entry 0x16D, pal=3
	tsa_entry 0x16E, pal=3
	tsa_entry 0x16F, pal=3
	tsa_entry 0x16F, pal=3, hflip=1
	tsa_entry 0x16E, pal=3, hflip=1
	tsa_entry 0x16D, pal=3, hflip=1
	tsa_entry 0x16C, pal=3, hflip=1
	tsa_entry 0x16B, pal=3, hflip=1
	tsa_entry 0x16A, pal=3, hflip=1
	tsa_entry 0x169, pal=3, hflip=1
	tsa_entry 0x168, pal=3, hflip=1
	tsa_entry 0x167, pal=3, hflip=1
	tsa_entry 0x166, pal=3, hflip=1
	tsa_entry 0x165, pal=3, hflip=1
	tsa_entry 0x0F8, pal=3, hflip=1
	tsa_entry 0x164, pal=3, hflip=1
	tsa_entry 0x163, pal=3, hflip=1
	tsa_entry 0x162, pal=3, hflip=1
	tsa_entry 0x1DE, pal=3, hflip=1
	tsa_entry 0x167, pal=3, hflip=1
	tsa_entry 0x166, pal=3, hflip=1
	tsa_entry 0x165, pal=3, hflip=1
	tsa_entry 0x0F8, pal=3, hflip=1
	tsa_entry 0x164, pal=3, hflip=1
	tsa_entry 0x1DD, pal=3, hflip=1
	tsa_entry 0x1DC, pal=3, hflip=1
	tsa_entry 0x1A6, pal=3
	tsa_entry 0x176, pal=3
	tsa_entry 0x177, pal=3
	tsa_entry 0x178, pal=3
	tsa_entry 0x114, pal=3
	tsa_entry 0x179, pal=3
	tsa_entry 0x17A, pal=3
	tsa_entry 0x1F7, pal=3
	tsa_entry 0x175, pal=3
	tsa_entry 0x176, pal=3
	tsa_entry 0x177, pal=3
	tsa_entry 0x178, pal=3
	tsa_entry 0x114, pal=3
	tsa_entry 0x179, pal=3
	tsa_entry 0x17A, pal=3
	tsa_entry 0x17B, pal=3
	tsa_entry 0x17C, pal=3
	tsa_entry 0x17D, pal=3
	tsa_entry 0x17E, pal=3
	tsa_entry 0x17F, pal=3
	tsa_entry 0x180, pal=3
	tsa_entry 0x181, pal=3
	tsa_entry 0x182, pal=3
	tsa_entry 0x182, pal=3, hflip=1
	tsa_entry 0x181, pal=3, hflip=1
	tsa_entry 0x180, pal=3, hflip=1
	tsa_entry 0x17F, pal=3, hflip=1
	tsa_entry 0x17E, pal=3, hflip=1
	tsa_entry 0x17D, pal=3, hflip=1
	tsa_entry 0x17C, pal=3, hflip=1
	tsa_entry 0x17B, pal=3, hflip=1
	tsa_entry 0x17A, pal=3, hflip=1
	tsa_entry 0x179, pal=3, hflip=1
	tsa_entry 0x114, pal=3, hflip=1
	tsa_entry 0x178, pal=3, hflip=1
	tsa_entry 0x177, pal=3, hflip=1
	tsa_entry 0x176, pal=3, hflip=1
	tsa_entry 0x175, pal=3, hflip=1
	tsa_entry 0x1F7, pal=3, hflip=1
	tsa_entry 0x17A, pal=3, hflip=1
	tsa_entry 0x179, pal=3, hflip=1
	tsa_entry 0x114, pal=3, hflip=1
	tsa_entry 0x178, pal=3, hflip=1
	tsa_entry 0x177, pal=3, hflip=1
	tsa_entry 0x176, pal=3, hflip=1
	tsa_entry 0x1A6, pal=3, hflip=1
	tsa_entry 0x1C2, pal=3
	tsa_entry 0x184, pal=3
	tsa_entry 0x185, pal=3
	tsa_entry 0x186, pal=3
	tsa_entry 0x187, pal=3
	tsa_entry 0x15C, pal=3, hflip=1
	tsa_entry 0x15B, pal=3, hflip=1
	tsa_entry 0x20F, pal=3
	tsa_entry 0x183, pal=3
	tsa_entry 0x184, pal=3
	tsa_entry 0x185, pal=3
	tsa_entry 0x186, pal=3
	tsa_entry 0x187, pal=3
	tsa_entry 0x15C, pal=3, hflip=1
	tsa_entry 0x15B, pal=3, hflip=1
	tsa_entry 0x14C, pal=3
	tsa_entry 0x14D, pal=3
	tsa_entry 0x188, pal=3
	tsa_entry 0x189, pal=3
	tsa_entry 0x18A, pal=3
	tsa_entry 0x18B, pal=3
	tsa_entry 0x18C, pal=3
	tsa_entry 0x18D, pal=3
	tsa_entry 0x18D, pal=3, hflip=1
	tsa_entry 0x18C, pal=3, hflip=1
	tsa_entry 0x18B, pal=3, hflip=1
	tsa_entry 0x18A, pal=3, hflip=1
	tsa_entry 0x189, pal=3, hflip=1
	tsa_entry 0x188, pal=3, hflip=1
	tsa_entry 0x14D, pal=3, hflip=1
	tsa_entry 0x14C, pal=3, hflip=1
	tsa_entry 0x15B, pal=3
	tsa_entry 0x15C, pal=3
	tsa_entry 0x187, pal=3, hflip=1
	tsa_entry 0x186, pal=3, hflip=1
	tsa_entry 0x185, pal=3, hflip=1
	tsa_entry 0x184, pal=3, hflip=1
	tsa_entry 0x183, pal=3, hflip=1
	tsa_entry 0x20F, pal=3, hflip=1
	tsa_entry 0x15B, pal=3
	tsa_entry 0x15C, pal=3
	tsa_entry 0x187, pal=3, hflip=1
	tsa_entry 0x186, pal=3, hflip=1
	tsa_entry 0x185, pal=3, hflip=1
	tsa_entry 0x184, pal=3, hflip=1
	tsa_entry 0x1C2, pal=3, hflip=1
