"""Deterministic C header/source + budget report generator.

Consumes a validated ``catalog.LoadedCatalog`` and writes, under a caller-
given output directory (always somewhere under build/ -- never a
committed source directory; see modern.mk's "Localization catalog"
section):

  * ``expansion_msg_ids.h`` -- public ``EXP_MSG_<KEY>`` numeric macros for
    every active message, for future (non-sprint-1) callers that want to
    resolve a message by a stable compile-time name instead of a raw
    numeric ExpansionMsgId.
  * ``expansion_locale_catalog.c`` -- defines the stable-id-indexed catalog
    descriptor table declared in include/expansion_locale.h. Populated
    authored/derived locales point at generated arrays; unpopulated stable
    slots contain null descriptors. This is the
    only generated file the modern linked build actually compiles/links;
    src/expansion_locale.c never `#include`s any generated header (see
    its own file comment), so nothing here is required for legacy (agbcc)
    compilation.
  * a budget JSON report (catalog/index/string/scratch bytes, populated
    descriptors, UTF-8 Unicode scalars/glyph count, and configured limits).

Every write goes through a write-if-unchanged helper so an unrelated
rebuild never touches these files' mtimes, and generating twice from the
same registry/catalog input is always byte-for-byte identical (see
scripts/localization/tests/test_determinism.py).
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Dict, Mapping, Optional

from . import schema
from .catalog import LoadedCatalog, load_catalog

_NON_IDENT_RE = re.compile(r"[^A-Za-z0-9]+")


def _write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def key_to_macro(key: str) -> str:
    ident = _NON_IDENT_RE.sub("_", key).strip("_").upper()
    return f"EXP_MSG_{ident}"


def locale_to_symbol(locale: str) -> str:
    return "gExpansionCatalog_" + _NON_IDENT_RE.sub("_", locale)


def _c_string_literal(text: str) -> str:
    """Encodes text as a C89 string literal.

    Authored LF maps to the engine's 0x01 line-break control. All other UTF-8
    bytes are preserved: printable ASCII stays readable, while non-ASCII bytes
    use fixed three-digit octal escapes so C's greedy ``\\x`` parsing can never
    absorb a following hexadecimal digit and alter the byte stream."""
    out = ['"']
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\001")
        elif 0x20 <= ord(ch) <= 0x7E:
            out.append(ch)
        else:
            for byte in ch.encode("utf-8"):
                out.append(f"\\{byte:03o}")
    out.append('"')
    return "".join(out)


def _assert_ids_in_range(catalog: LoadedCatalog) -> None:
    """Defensive, generator-side re-validation of every registry id
    (active and tombstone) -- independent of catalog.parse_registry's
    own source-of-truth check. This exists purely to fail loudly if a
    future caller ever constructs a LoadedCatalog/RegistryEntry directly
    (e.g. in-process, from a test, or from a not-yet-imagined future
    tool) instead of going through parse_registry()/load_catalog(): the
    generator must never silently emit an id that cannot round-trip
    through the u16 ExpansionMsgId type or that collides with the
    EXPANSION_MSG_ID_INVALID sentinel (include/expansion_locale.h).
    Raises before anything is written, so a rejected catalog never
    produces partial generated output (see generate())."""
    for entry in catalog.entries:
        entry_id = entry.id
        if isinstance(entry_id, bool) or not isinstance(entry_id, int):
            raise schema.SchemaError(
                f"message {entry.key!r} id {entry_id!r} is not an int "
                f"(generator defensive check)"
            )
        if entry_id < schema.MSG_ID_MIN or entry_id > schema.MSG_ID_MAX:
            raise schema.SchemaError(
                f"message {entry.key!r} id {entry_id} outside the assignable "
                f"ExpansionMsgId range [{schema.MSG_ID_MIN}, {schema.MSG_ID_MAX}]; "
                f"{schema.MSG_ID_INVALID} (0x{schema.MSG_ID_INVALID:04X}) is the "
                f"reserved EXPANSION_MSG_ID_INVALID sentinel and can never be "
                f"assigned to a real message (generator defensive check)"
            )


def build_msg_ids_header(catalog: LoadedCatalog) -> str:
    _assert_ids_in_range(catalog)
    lines = [
        "/* Generated by scripts/localization/generate.py -- do not edit. */",
        "/* Stable EXP_MSG_* numeric message ids (issue #18 sprint 1).",
        " * Regenerated from texts/expansion/registry.json; ids are stable",
        " * and append-only there -- see that file's own ordering. */",
        "#ifndef GUARD_EXPANSION_MSG_IDS_H",
        "#define GUARD_EXPANSION_MSG_IDS_H",
        "",
    ]
    for entry in catalog.active_entries:
        lines.append(f"#define {key_to_macro(entry.key)} {entry.id}u")
    lines.append("")
    lines.append(f"#define EXPANSION_MSG_ACTIVE_COUNT {len(catalog.active_entries)}u")
    lines.append("")
    lines.append("#endif /* GUARD_EXPANSION_MSG_IDS_H */")
    lines.append("")
    return "\n".join(lines)


def build_catalog_c(
    catalog: LoadedCatalog,
    emission_profile: str = schema.EMISSION_PROFILE_DEBUG,
) -> str:
    _assert_ids_in_range(catalog)
    emitted_entries = catalog.emitted_active_entries(emission_profile)
    ids = [entry.id for entry in emitted_entries]

    lines = [
        "/* Generated by scripts/localization/generate.py -- do not edit. */",
        "/* Expansion framework UTF-8 locale catalog.",
        " * Source: texts/expansion/registry.json + authored catalog JSON;",
        " * qps-ploc is deterministically derived from English by",
        " * scripts/localization/pseudo.py, never hand-authored.",
        " * The descriptor table is indexed by stable ExpansionLocaleId;",
        " * unpopulated locale slots are explicit null descriptors. */",
        '#include "global.h"',
        '#include "expansion_locale.h"',
        "",
        f"const u16 gExpansionLocaleMsgCount = {len(ids)}u;",
        f"const u16 gExpansionLocaleTombstoneCount = {len(catalog.tombstone_entries)}u;",
        "",
        "const ExpansionMsgId gExpansionLocaleMsgIds[] =",
        "{",
    ]
    for msg_id in ids:
        lines.append(f"    {msg_id}u,")
    lines.append("};")
    lines.append("")

    for locale in catalog.generated_locales:
        symbol = locale_to_symbol(locale)
        strings = catalog.strings_for(locale)
        lines.append(f"const char *const {symbol}[] =")
        lines.append("{")
        for entry in emitted_entries:
            text = strings[entry.key]
            value = "NULL" if text is None else _c_string_literal(text)
            lines.append(f"    {value},")
        lines.append("};")
        lines.append("")

    lines.append(
        "const struct ExpansionLocaleCatalogDescriptor "
        "gExpansionLocaleCatalogs[EXPANSION_LOCALE_COUNT] ="
    )
    lines.append("{")
    for locale in schema.LOCALE_IDS:
        if locale in catalog.generated_locales:
            lines.append(
                "    { gExpansionLocaleMsgIds, %s, %du }, /* %s */"
                % (locale_to_symbol(locale), len(ids), locale)
            )
        else:
            lines.append(f"    {{ NULL, NULL, 0u }}, /* {locale} */")
    lines.append("};")
    lines.append("")
    lines.append(
        f"const u8 gExpansionLocalePopulatedCount = {len(catalog.generated_locales)}u;"
    )
    lines.append("")
    return "\n".join(lines)


def _codepoint_report(catalog: LoadedCatalog, emitted_entries) -> dict:
    used = set()
    per_locale = {}
    for locale in catalog.generated_locales:
        locale_used = set()
        strings = catalog.strings_for(locale)
        for entry in emitted_entries:
            text = strings[entry.key]
            if text is not None:
                locale_used.update(text)
        used.update(locale_used)
        rendered = locale_used - set(schema.ALLOWED_CONTROL_TOKENS)
        per_locale[locale] = {
            "unique_scalar_count": len(locale_used),
            "rendered_scalar_count": len(rendered),
            "utf8_scalars": ["U+%04X" % ord(ch) for ch in sorted(locale_used)],
        }
    control = sorted(ch for ch in used if ch in schema.ALLOWED_CONTROL_TOKENS)
    rendered = sorted(ch for ch in used if ch not in schema.ALLOWED_CONTROL_TOKENS)
    return {
        "allowed_control_tokens": list(schema.ALLOWED_CONTROL_TOKENS),
        "unique_scalar_count": len(used),
        "rendered_scalar_count": len(rendered),
        "utf8_scalars": ["U+%04X" % ord(ch) for ch in sorted(used)],
        "glyphs_used_count": len(rendered),
        "glyphs_used": ["U+%04X" % ord(ch) for ch in rendered],
        "control_tokens_used": [repr(ch) for ch in control],
        "per_locale": per_locale,
    }


def build_budget(
    catalog: LoadedCatalog,
    emission_profile: str = schema.EMISSION_PROFILE_DEBUG,
) -> dict:
    emitted_entries = catalog.emitted_active_entries(emission_profile)
    ids = [entry.id for entry in emitted_entries]

    def encoded_len(text: str) -> int:
        return len(text.encode("utf-8")) + 1

    locale_bytes = {}
    missing_entries = {}
    all_present_text = []
    for locale in catalog.generated_locales:
        strings = catalog.strings_for(locale)
        present = [
            strings[entry.key]
            for entry in emitted_entries
            if strings[entry.key] is not None
        ]
        locale_bytes[locale] = sum(encoded_len(text) for text in present)
        missing_entries[locale] = sum(
            strings[entry.key] is None for entry in emitted_entries
        )
        all_present_text.extend(present)

    max_slot_used = max(
        [encoded_len(text) for text in all_present_text],
        default=0,
    )
    descriptor_bytes = schema.LOCALE_COUNT * schema.C_CATALOG_DESCRIPTOR_SIZE_BYTES
    pointer_table_bytes = (
        len(ids) * schema.C_POINTER_SIZE_BYTES * len(catalog.generated_locales)
    )
    index_bytes = (
        len(ids) * schema.C_MSG_ID_SIZE_BYTES
        + pointer_table_bytes
        + descriptor_bytes
    )

    return {
        "active_message_count": len(emitted_entries),
        "stable_active_message_count": len(catalog.active_entries),
        "omitted_active_message_count": len(catalog.active_entries) - len(emitted_entries),
        "emission_profile": emission_profile,
        "tombstone_count": len(catalog.tombstone_entries),
        "pseudo_policy_counts": {
            policy: sum(
                entry.pseudo_policy == policy for entry in emitted_entries
            )
            for policy in schema.PSEUDO_POLICIES
        },
        "locales_authored": list(catalog.authored_locales),
        "locales_generated": list(catalog.generated_locales),
        "populated_descriptor_count": len(catalog.generated_locales),
        "unpopulated_locale_slots": [
            locale for locale in schema.LOCALE_IDS if locale not in catalog.generated_locales
        ],
        "missing_catalog_entries": missing_entries,
        "catalog_string_bytes": {
            **locale_bytes,
            "total": sum(locale_bytes.values()),
        },
        "catalog_index_bytes": index_bytes,
        "catalog_descriptor_bytes": descriptor_bytes,
        "catalog_pointer_table_bytes": pointer_table_bytes,
        "scratch_budget_bytes": schema.MAX_DECODED_BYTES_MAX,
        "scratch_slot_bytes_used_max": max_slot_used,
        "scratch_headroom_bytes": schema.MAX_DECODED_BYTES_MAX - max_slot_used,
        "codepoints": _codepoint_report(catalog, emitted_entries),
        "limits": {
            "max_width_max": schema.MAX_WIDTH_MAX,
            "max_decoded_bytes_max": schema.MAX_DECODED_BYTES_MAX,
        },
    }


def generate(
    output_dir: Path,
    budget_json_path: Path = None,
    registry_path: Path = None,
    catalog_paths: Optional[Mapping[str, Path]] = None,
    emission_profile: str = schema.EMISSION_PROFILE_DEBUG,
) -> Dict[str, Path]:
    kwargs = {}
    if registry_path is not None:
        kwargs["registry_path"] = registry_path
    if catalog_paths is not None:
        kwargs["catalog_paths"] = catalog_paths
    catalog = load_catalog(**kwargs)

    output_dir = Path(output_dir)
    msg_ids_path = output_dir / "expansion_msg_ids.h"
    catalog_c_path = output_dir / "expansion_locale_catalog.c"

    _write_if_changed(msg_ids_path, build_msg_ids_header(catalog))
    _write_if_changed(
        catalog_c_path,
        build_catalog_c(catalog, emission_profile=emission_profile),
    )

    budget = build_budget(catalog, emission_profile=emission_profile)
    budget_path = Path(budget_json_path) if budget_json_path is not None else output_dir / "budget.json"
    _write_if_changed(budget_path, json.dumps(budget, indent=2, sort_keys=True) + "\n")

    return {"msg_ids_header": msg_ids_path, "catalog_c": catalog_c_path, "budget_json": budget_path}
