"""Small committed public inventory/summary for the ``shops`` table."""

from __future__ import annotations

from .schema import SCHEMA_ID, dependency_graph


def build_inventory(records):
    graph = dependency_graph()
    lines = []
    lines.append("# Generated-data inventory: shops\n")
    lines.append("\n")
    lines.append("_Auto-generated by `python3 -m scripts.generated_data generate --table shops`. "
                  "Do not edit by hand -- see docs/generated_data.md._\n")
    lines.append("\n")
    lines.append("- Schema: `{}`\n".format(SCHEMA_ID))
    lines.append("- Shop count: {}\n".format(len(records)))
    lines.append("- Dependencies: {}\n".format(", ".join(graph.nodes())))
    lines.append("- Dependency graph digest (sha256): `{}`\n".format(graph.digest()))
    lines.append("\n")
    lines.append("| Shop symbol | Item count |\n")
    lines.append("|---|---|\n")
    for record in sorted(records, key=lambda r: r.symbol):
        lines.append("| {} | {} |\n".format(record.symbol, len(record.items)))
    return "".join(lines)
