"""Complete producer-step registrations in the shared command authority.

These are command/control contracts, not a copy of the workflow. Executable
heredocs select canonical programs; the builder payload uses the same inventory.
"""

from . import publisher_shell as shell
from .publisher_inventory import (
    Access, Context, EventKind, Payload, Placement, Program, ProgramKind, Resource,
    ResourceAccess, Scope, WORKFLOW_PATH, normalize_invocation,
)


def register(add, control, scopes):
    scopes.extend((
        Scope('builder_passwd_entry_exists', 'staging', (Resource.PROCESS,)),
        Scope('probe_builder_passwd_entry', 'staging', (Resource.PROCESS,)),
        Scope('builder_passwd_entry_absent', 'staging', (Resource.PROCESS,)),
        Scope('builder_group_pids', 'staging', (Resource.PROCESS,)),
        Scope('builder_uid_pids', 'staging', (Resource.PROCESS,)),
        Scope('builder_cgroup_pids', 'staging', ()),
        Scope('builder_group_is_empty', 'staging', (Resource.PROCESS,)),
        Scope('read_builder_identity', 'staging', (Resource.PROCESS,)),
        Scope('builder_supervisor_identity_matches', 'staging', (Resource.PROCESS,)),
        Scope('probe_builder_uid_occupancy', 'staging', (Resource.PROCESS,)),
        Scope('builder_uid_is_empty', 'staging', (Resource.PROCESS,)),
        Scope('builder_cgroup_is_empty', 'staging', ()),
        Scope('terminate_builder_processes', 'staging', ()),
        Scope('remove_builder_cgroup', 'staging', ()),
        Scope('remove_builder_state', 'staging', ()),
        Scope('cleanup_builder', 'staging', ()),
    ))
    programs = {
        "authority-preflight": Program(
            "authority-preflight", "scripts/workflow_pilot/publisher_inventory.py",
            "scripts/workflow_pilot/publisher_inventory.py", None,
            (ResourceAccess(Resource.CONTROL, Access.READ),), (),
        ),
        "launch": Program(
            "supervisor-launcher", WORKFLOW_PATH,
            '"$BUILDER_ROOT/control/supervisor-launcher.py"', None,
            (ResourceAccess(Resource.CONTROL, Access.READ), ResourceAccess(Resource.NULL, Access.READ)),
            (ResourceAccess(Resource.PROCESS, Access.EXECUTE), ResourceAccess(Resource.NULL, Access.WRITE)),
            redirects=shell.command("true < /dev/null > /dev/null 2>&1").redirects,
        ),
        "metadata": Program(
            "metadata-commit", WORKFLOW_PATH, "-c", None,
            (ResourceAccess(Resource.HANDOFF, Access.READ),), (),
            kind=ProgramKind.INLINE,
            text='import json,sys; value=json.load(open(sys.argv[1], encoding="utf-8")); assert isinstance(value, dict); assert value.get("build_commit") == sys.argv[2]',
            wrappers=normalize_invocation(shell.command(
                '/usr/bin/env -i HOME="$PATCH_RUNTIME_ROOT" PATH=/usr/bin:/bin LC_ALL=C true',
            )).wrappers,
        ),
    }
    contexts = [()]

    def place(parent, kind, name, branch=""):
        contexts.append(contexts[parent] + (Context(kind, name, branch),))

    place(0, 'if', 'probe_builder_passwd_entry.control-1', 'failure')
    place(0, 'if', 'probe_builder_uid_occupancy.control-1', 'success')
    place(0, 'if', 'terminate_builder_processes.control-1', 'success')
    place(3, 'if', 'terminate_builder_processes.control-2', 'failure')
    place(4, 'if', 'terminate_builder_processes.control-3', 'success')
    place(5, 'if', 'terminate_builder_processes.control-5', 'failure')
    place(0, 'if', 'terminate_builder_processes.control-7', 'success')
    place(7, 'if', 'terminate_builder_processes.control-8', 'success')
    place(8, 'loop', 'terminate_builder_processes.control-9')
    place(0, 'if', 'terminate_builder_processes.control-11', 'success')
    place(10, 'loop', 'terminate_builder_processes.control-12')
    place(0, 'if', 'remove_builder_cgroup.control-1', 'success')
    place(0, 'if', 'remove_builder_state.control-1', 'success')
    place(13, 'if', 'remove_builder_state.control-2', 'success')
    place(0, 'if', 'remove_builder_state.control-4', 'success')
    place(0, 'if', 'remove_builder_state.control-6', 'success')
    place(0, 'while', 'staging.control-1', 'body')
    place(17, 'if', 'staging.control-2', 'success')
    place(0, 'loop', 'staging.control-7')
    place(19, 'if', 'staging.control-9', 'failure')
    place(20, 'if', 'staging.control-10', 'failure')
    place(21, 'if', 'staging.control-11', 'success')
    place(21, 'if', 'staging.control-11', 'failure')
    place(0, 'loop', 'staging.control-20')
    place(0, 'loop', 'producer.control-1')
    place(0, 'if', 'probe_builder_passwd_entry.control-1', 'condition')
    place(0, 'if', 'probe_builder_passwd_entry.control-1', 'success')
    place(1, 'case', 'probe_builder_passwd_entry.control-2', '0')
    place(1, 'case', 'probe_builder_passwd_entry.control-2', '1')
    place(0, 'operators', '||', '0')
    place(0, 'operators', '||', '1')
    place(0, 'if', 'builder_cgroup_pids.control-1', 'condition')
    place(32, 'operators', '&&', '0')
    place(32, 'operators', '&&', '1')
    place(0, 'if', 'builder_cgroup_pids.control-1', 'success')
    place(35, 'operators', '||', '0')
    place(35, 'operators', '||', '1')
    place(0, 'case', 'read_builder_identity.control-1', '1')
    place(0, 'case', 'builder_supervisor_identity_matches.control-1', '5')
    place(0, 'case', 'builder_supervisor_identity_matches.control-1', '0')
    place(0, 'case', 'builder_supervisor_identity_matches.control-1', '1')
    place(0, 'case', 'builder_supervisor_identity_matches.control-1', '2')
    place(0, 'case', 'builder_supervisor_identity_matches.control-1', '3')
    place(0, 'case', 'builder_supervisor_identity_matches.control-1', '4')
    place(0, 'if', 'probe_builder_uid_occupancy.control-1', 'condition')
    place(2, 'if', 'probe_builder_uid_occupancy.control-2', 'condition')
    place(2, 'if', 'probe_builder_uid_occupancy.control-2', 'success')
    place(2, 'if', 'probe_builder_uid_occupancy.control-2', 'failure')
    place(0, 'if', 'probe_builder_uid_occupancy.control-1', 'failure')
    place(0, 'if', 'terminate_builder_processes.control-1', 'condition')
    place(50, 'operators', '&&', '0')
    place(0, 'if', 'terminate_builder_processes.control-17', 'condition')
    place(50, 'operators', '&&', '1')
    place(0, 'if', 'terminate_builder_processes.control-11', 'condition')
    place(54, 'operators', '&&', '1')
    place(3, 'if', 'terminate_builder_processes.control-2', 'condition')
    place(5, 'if', 'terminate_builder_processes.control-5', 'condition')
    place(11, 'if', 'terminate_builder_processes.control-13', 'condition')
    place(3, 'if', 'terminate_builder_processes.control-2', 'success')
    place(4, 'if', 'terminate_builder_processes.control-3', 'condition')
    place(5, 'if', 'terminate_builder_processes.control-4', 'condition')
    place(61, 'operators', '&&', '1')
    place(5, 'operators', '||', '0')
    place(5, 'operators', '||', '1')
    place(4, 'if', 'terminate_builder_processes.control-3', 'failure')
    place(7, 'operators', '||', '1')
    place(11, 'if', 'terminate_builder_processes.control-15', 'success')
    place(10, 'if', 'terminate_builder_processes.control-16', 'failure')
    place(0, 'if', 'terminate_builder_processes.control-17', 'success')
    place(69, 'operators', '||', '1')
    place(61, 'operators', '&&', '0')
    place(5, 'if', 'terminate_builder_processes.control-4', 'success')
    place(72, 'operators', '||', '0')
    place(72, 'operators', '||', '1')
    place(6, 'if', 'terminate_builder_processes.control-6', 'success')
    place(75, 'operators', '||', '1')
    place(10, 'if', 'terminate_builder_processes.control-16', 'success')
    place(77, 'operators', '||', '1')
    place(5, 'if', 'terminate_builder_processes.control-5', 'success')
    place(6, 'if', 'terminate_builder_processes.control-6', 'condition')
    place(75, 'operators', '||', '0')
    place(0, 'if', 'terminate_builder_processes.control-7', 'condition')
    place(7, 'if', 'terminate_builder_processes.control-8', 'condition')
    place(8, 'operators', '|', '0')
    place(8, 'operators', '|', '1')
    place(9, 'if', 'terminate_builder_processes.control-10', 'condition')
    place(7, 'operators', '||', '0')
    place(9, 'if', 'terminate_builder_processes.control-10', 'success')
    place(11, 'if', 'terminate_builder_processes.control-13', 'success')
    place(11, 'if', 'terminate_builder_processes.control-14', 'success')
    place(54, 'operators', '&&', '0')
    place(11, 'if', 'terminate_builder_processes.control-14', 'condition')
    place(11, 'if', 'terminate_builder_processes.control-15', 'condition')
    place(10, 'if', 'terminate_builder_processes.control-16', 'condition')
    place(94, 'operators', '&&', '0')
    place(94, 'operators', '&&', '1')
    place(77, 'operators', '||', '0')
    place(69, 'operators', '||', '0')
    place(0, 'if', 'remove_builder_cgroup.control-1', 'condition')
    place(12, 'operators', '||', '0')
    place(12, 'operators', '||', '1')
    place(12, 'if', 'remove_builder_cgroup.control-2', 'failure')
    place(12, 'if', 'remove_builder_cgroup.control-2', 'condition')
    place(103, 'operators', '&&', '0')
    place(103, 'operators', '&&', '1')
    place(12, 'if', 'remove_builder_cgroup.control-2', 'success')
    place(0, 'if', 'remove_builder_state.control-1', 'condition')
    place(13, 'if', 'remove_builder_state.control-2', 'condition')
    place(14, 'if', 'remove_builder_state.control-3', 'condition')
    place(14, 'if', 'remove_builder_state.control-3', 'success')
    place(13, 'if', 'remove_builder_state.control-2', 'failure')
    place(14, 'if', 'remove_builder_state.control-3', 'failure')
    place(15, 'if', 'remove_builder_state.control-5', 'failure')
    place(16, 'if', 'remove_builder_state.control-7', 'failure')
    place(0, 'if', 'remove_builder_state.control-4', 'condition')
    place(15, 'if', 'remove_builder_state.control-5', 'condition')
    place(15, 'if', 'remove_builder_state.control-5', 'success')
    place(0, 'if', 'remove_builder_state.control-6', 'condition')
    place(16, 'if', 'remove_builder_state.control-7', 'condition')
    place(16, 'if', 'remove_builder_state.control-7', 'success')
    place(0, 'if', 'cleanup_builder.control-1', 'condition')
    place(121, 'operators', '|| ||', '0')
    place(121, 'operators', '|| ||', '1')
    place(121, 'operators', '|| ||', '2')
    place(0, 'if', 'cleanup_builder.control-1', 'success')
    place(0, 'if', 'cleanup_builder.control-2', 'condition')
    place(0, 'if', 'cleanup_builder.control-2', 'success')
    place(0, 'while', 'staging.control-1', 'condition')
    place(17, 'if', 'staging.control-2', 'condition')
    place(18, 'if', 'staging.control-3', 'condition')
    place(18, 'if', 'staging.control-3', 'success')
    place(19, 'if', 'staging.control-8', 'success')
    place(22, 'if', 'staging.control-12', 'success')
    place(23, 'if', 'staging.control-13', 'failure')
    place(19, 'if', 'staging.control-16', 'success')
    place(19, 'if', 'staging.control-17', 'success')
    place(0, 'case', 'staging.control-4', '1')
    place(0, 'case', 'staging.control-5', '0')
    place(0, 'case', 'staging.control-6', '1')
    place(24, 'case', 'staging.control-21', '1')
    place(0, 'background', '&')
    place(19, 'if', 'staging.control-8', 'condition')
    place(19, 'if', 'staging.control-9', 'condition')
    place(19, 'if', 'staging.control-9', 'success')
    place(20, 'if', 'staging.control-10', 'condition')
    place(20, 'if', 'staging.control-10', 'success')
    place(21, 'if', 'staging.control-11', 'condition')
    place(147, 'operators', '&& &&', '0')
    place(147, 'operators', '&& &&', '1')
    place(147, 'operators', '&& &&', '2')
    place(22, 'if', 'staging.control-12', 'condition')
    place(23, 'if', 'staging.control-13', 'condition')
    place(23, 'if', 'staging.control-13', 'success')
    place(0, 'if', 'staging.control-14', 'condition')
    place(0, 'if', 'staging.control-14', 'success')
    place(0, 'if', 'staging.control-15', 'success')
    place(0, 'if', 'staging.control-18', 'success')
    place(0, 'if', 'staging.control-19', 'success')
    place(0, 'if', 'staging.control-15', 'condition')
    place(159, 'operators', '||', '0')
    place(159, 'operators', '||', '1')
    place(19, 'if', 'staging.control-16', 'condition')
    place(19, 'if', 'staging.control-17', 'condition')
    place(0, 'if', 'staging.control-18', 'condition')
    place(0, 'if', 'staging.control-19', 'condition')
    place(0, 'loop', 'staging.control-22')
    isolated_results = (
        ('71', 'candidate-preflight'), ('72', 'candidate-venv'),
        ('73', 'candidate-pip'), ('74', 'candidate-build-tools'),
        ('75', 'candidate-make'), ('76', 'candidate-handoff'),
        ('77', 'candidate-unknown'), ('81', 'namespace'),
        ('82', 'mount-audit'), ('83', 'output-validate'),
        ('84', 'export'), ('85', 'post-check'), ('*', 'transport'),
    )
    isolated_transport = len(contexts)
    place(158, 'case', 'staging.isolated-result', str(len(isolated_results) - 1))

    control('producer', 'control-1', 'for source in scripts/modernize/patch_release.py scripts/modernize/bps_patch.py scripts/modernize/verify_rom_header.py; do :; done')
    control('probe_builder_passwd_entry', 'control-1', 'if builder_passwd_entry_exists "$1"; then :; else :; fi')
    control('probe_builder_passwd_entry', 'control-2', 'case "${status}" in 2) ;; *) ;; esac', context=contexts[1])
    control('builder_cgroup_pids', 'control-1', 'if [ "$builder_cgroup_owned" = 1 ] && [ -r "$builder_cgroup/cgroup.procs" ]; then :; fi')
    control('read_builder_identity', 'control-1', 'case "${stat_record}" in *\') \'*) ;; *) ;; esac')
    control('builder_supervisor_identity_matches', 'control-1', 'case "${expected_state}" in stopped) ;; starting) ;; running) ;; zombie) ;; owned) ;; *) ;; esac')
    control('probe_builder_uid_occupancy', 'control-1', 'if output="$(builder_uid_pids "$1")"; then :; else :; fi')
    control('probe_builder_uid_occupancy', 'control-2', 'if [ -z "$output" ]; then :; else :; fi', context=contexts[2])
    control('terminate_builder_processes', 'control-1', 'if [ -n "$builder_session_id" ] && [ -n "$builder_supervisor_pid" ]; then :; fi')
    control('terminate_builder_processes', 'control-2', 'if builder_supervisor_identity_matches zombie; then :; else :; fi', context=contexts[3])
    control('terminate_builder_processes', 'control-3', 'if builder_supervisor_identity_matches "$builder_supervisor_state"; then :; else :; fi', context=contexts[4])
    control('terminate_builder_processes', 'control-4', 'if [ -n "$remaining_group" ] && builder_supervisor_identity_matches "$builder_supervisor_state"; then :; fi', context=contexts[5])
    control('terminate_builder_processes', 'control-5', 'if builder_supervisor_identity_matches zombie; then :; else :; fi', context=contexts[5])
    control('terminate_builder_processes', 'control-6', 'if builder_supervisor_identity_matches owned; then :; fi', context=contexts[6])
    control('terminate_builder_processes', 'control-7', 'if [ "$builder_cgroup_owned" = 1 ]; then :; fi')
    control('terminate_builder_processes', 'control-8', 'if ! builder_cgroup_is_empty; then :; fi', context=contexts[7])
    control('terminate_builder_processes', 'control-9', 'for attempt in $(/usr/bin/seq 1 50); do :; done', context=contexts[8])
    control('terminate_builder_processes', 'control-10', 'if builder_cgroup_is_empty; then :; fi', context=contexts[9])
    control('terminate_builder_processes', 'control-11', 'if [ "$supervisor_authenticated" = 1 ] && [ -n "$builder_supervisor_pid" ]; then :; fi')
    control('terminate_builder_processes', 'control-12', 'for attempt in $(/usr/bin/seq 1 50); do :; done', context=contexts[10])
    control('terminate_builder_processes', 'control-13', 'if builder_supervisor_identity_matches zombie; then :; fi', context=contexts[11])
    control('terminate_builder_processes', 'control-14', 'if [ ! -e "/proc/$builder_supervisor_pid" ]; then :; fi', context=contexts[11])
    control('terminate_builder_processes', 'control-15', 'if ! builder_supervisor_identity_matches owned; then :; fi', context=contexts[11])
    control('terminate_builder_processes', 'control-16', 'if [ "$supervisor_reap_ready" = 1 ] && [ "$builder_supervisor_wait_pid" = "$builder_supervisor_pid" ]; then :; else :; fi', context=contexts[10])
    control('terminate_builder_processes', 'control-17', 'if [ -n "$builder_session_id" ]; then :; fi')
    control('remove_builder_cgroup', 'control-1', 'if [ "$builder_cgroup_owned" = 1 ]; then :; fi')
    control('remove_builder_cgroup', 'control-2', 'if [ "$cleanup_failed" = 0 ] && /usr/bin/sudo /usr/bin/rmdir -- "$builder_cgroup" > /dev/null 2>&1; then :; else :; fi', context=contexts[12])
    control('remove_builder_state', 'control-1', 'if [ "$builder_user_created" = 1 ]; then :; fi')
    control('remove_builder_state', 'control-2', 'if builder_passwd_entry_exists "$builder_user"; then :; else :; fi', context=contexts[13])
    control('remove_builder_state', 'control-3', 'if /usr/bin/sudo /usr/sbin/userdel "$builder_user" > /dev/null 2>&1; then :; else :; fi', context=contexts[14])
    control('remove_builder_state', 'control-4', 'if [ "$builder_root_owned" = 1 ]; then :; fi')
    control('remove_builder_state', 'control-5', 'if /usr/bin/sudo /bin/rm -rf -- "$BUILDER_ROOT" > /dev/null 2>&1; then :; else :; fi', context=contexts[15])
    control('remove_builder_state', 'control-6', 'if [ "$wheelhouse_owned" = 1 ]; then :; fi')
    control('remove_builder_state', 'control-7', 'if /bin/rm -rf -- "$PATCH_WHEELHOUSE" > /dev/null 2>&1; then :; else :; fi', context=contexts[16])
    control('cleanup_builder', 'control-1', 'if [ "$process_cleanup" -ne 0 ] || [ "$cgroup_cleanup" -ne 0 ] || [ "$state_cleanup" -ne 0 ]; then :; fi', count=2)
    control('cleanup_builder', 'control-2', 'if [ "$status" -ne 0 ]; then :; fi')
    control('staging', 'control-1', 'while [ "$builder_uid" -ge 50000 ]; do :; done')
    control('staging', 'control-2', 'if [ "$builder_passwd_probe_state" = absent ]; then :; fi', context=contexts[17])
    control('staging', 'control-3', 'if [ "$builder_uid_occupancy_state" = free ]; then :; fi', context=contexts[18])
    control('staging', 'control-4', 'case "${cgroup_relative}" in /*) ;; *) ;; esac')
    control('staging', 'control-5', 'case /"${cgroup_relative}"/ in */../*) ;; esac')
    control('staging', 'control-6', 'case "${cgroup_parent}" in /sys/fs/cgroup|/sys/fs/cgroup/*) ;; *) ;; esac')
    control('staging', 'control-7', 'for attempt in $(/usr/bin/seq 1 100); do :; done', count=2)
    control('staging', 'control-8', 'if ! /bin/kill -0 "$builder_supervisor_pid" > /dev/null 2>&1; then :; fi', context=contexts[19])
    control('staging', 'control-9', 'if [ "$builder_identity_status" -ne 0 ]; then :; else :; fi', context=contexts[19])
    control('staging', 'control-10', 'if ! [[ "$builder_identity" =~ ^([1-9][0-9]*)[[:space:]]+([1-9][0-9]*)[[:space:]]+([1-9][0-9]*)[[:space:]]+([^[:space:]]+)[[:space:]]+([1-9][0-9]*)$ ]]; then :; else :; fi', context=contexts[20])
    control('staging', 'control-11', 'if [ "${BASH_REMATCH[1]}" = "$builder_supervisor_parent_pid" ] && [ "${BASH_REMATCH[2]}" = "$builder_supervisor_pid" ] && [ "${BASH_REMATCH[3]}" = "$builder_supervisor_pid" ]; then :; else :; fi', context=contexts[21])
    control('staging', 'control-12', 'if [[ "${BASH_REMATCH[4]}" = T* ]]; then :; fi', context=contexts[22])
    control('staging', 'control-13', 'if [ "${BASH_REMATCH[3]}" = "$shell_pgid" ]; then :; else :; fi', context=contexts[23])
    control('staging', 'control-14', 'if [ "$builder_launch_detail" != session-ready ]; then :; fi')
    control('staging', 'control-15', 'if ! builder_supervisor_identity_matches stopped || ! /bin/kill -CONT "$builder_supervisor_pid" > /dev/null 2>&1; then :; fi')
    control('staging', 'control-16', 'if builder_supervisor_identity_matches running; then :; fi', context=contexts[19])
    control('staging', 'control-17', 'if builder_supervisor_identity_matches zombie; then :; fi', context=contexts[19])
    control('staging', 'control-18', 'if [ "$builder_launch_detail" != session-started ]; then :; fi')
    control('staging', 'control-19', 'if [ "$builder_status" -ne 0 ]; then :; fi')
    control('staging', 'control-20', 'for source in "${target_source}" "${metadata_source}"; do :; done')
    control('staging', 'control-21', 'case "$(/usr/bin/realpath "$source")" in "${handoff_root}"/*) ;; *) ;; esac', context=contexts[24])
    control('staging', 'control-22', 'for input in "${PATCH_INPUT_ROOT}"/target.gba "${PATCH_INPUT_ROOT}"/metadata.json; do :; done')
    control(
        'staging', 'isolated-result',
        'case "$builder_status" in ' + ' '.join(
            status + ') ;;' for status, _detail in isolated_results
        ) + ' esac',
        context=contexts[158],
    )
    for arm, (_status, detail) in enumerate(isolated_results):
        add(
            'staging', 'isolated-' + detail, 'builder_isolated_detail=' + detail,
            Resource.SHELL, Access.WRITE, event=EventKind.STATE_WRITE,
            context=contexts[158] + (Context('case', 'staging.isolated-result', str(arm)),),
        )

    def row(scope, name, text, places, resource=Resource.HOST, access=Access.INSPECT, **options):
        placements = tuple(Placement(contexts[index], count) for index, count in places)
        program = options.get("program")
        if program is not None:
            resource, access = program.inputs[0].resource, program.inputs[0].access
            options["extra"] = program.inputs[1:] + program.outputs
        add(scope, name, text, resource, access,
            count=sum(p.occurrences for p in placements), placements=placements, **options)

    row('producer', 'strict-shell', 'set -euo pipefail', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('producer', 'authority-preflight', '/usr/bin/python3 -I -S scripts/workflow_pilot/publisher_inventory.py --repository-root . --commit "$PATCH_COMMIT"', ((0, 1),), program=programs['authority-preflight'])
    row('producer', 'git-environment', 'unset GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_CEILING_DIRECTORIES GIT_COMMON_DIR GIT_DIR GIT_EXEC_PATH GIT_INDEX_FILE GIT_NAMESPACE GIT_OBJECT_DIRECTORY GIT_REPLACE_REF_BASE GIT_WORK_TREE', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('producer', 'command-4', 'ACTUAL_SHA="$(/usr/bin/git rev-parse HEAD)"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('producer', 'command-5', 'printf \'patch.producer.sha=%s\\n\' "$ACTUAL_SHA"', ((0, 1),))
    row('producer', 'command-6', '[[ "$PATCH_COMMIT" =~ ^[0-9a-f]{40}$ ]]', ((0, 1),))
    row('producer', 'command-7', 'test "$PATCH_COMMIT" != 0000000000000000000000000000000000000000', ((0, 1),))
    row('producer', 'command-8', 'test "$ACTUAL_SHA" = "$PATCH_COMMIT"', ((0, 1),))
    row('producer', 'command-9', 'test "$(/usr/bin/git rev-parse --verify "$PATCH_COMMIT^{commit}")" = "$PATCH_COMMIT"', ((0, 1),))
    row('producer', 'command-10', 'test "$(/usr/bin/git cat-file -t "$PATCH_COMMIT")" = commit', ((0, 1),))
    row('producer', 'command-11', '/bin/rm -rf -- "$PATCH_RUNTIME_ROOT" "$PATCH_TOOL_ROOT" > /dev/null 2>&1', ((0, 1),), resource=Resource.CONTROL, access=Access.REMOVE)
    row('producer', 'command-12', '/usr/bin/install -d -m 0700 "$PATCH_RUNTIME_ROOT" "$PATCH_TOOL_ROOT" "$PATCH_TOOL_ROOT/scripts" "$PATCH_TOOL_ROOT/scripts/modernize"', ((0, 1),), resource=Resource.CONTROL, access=Access.CREATE)
    row('producer', 'command-13', 'test -f "$source"', ((25, 1),))
    row('producer', 'command-14', 'test ! -L "$source"', ((25, 1),))
    row('producer', 'command-15', 'test "$(/usr/bin/stat -c %F "$source")" = "regular file"', ((25, 1),))
    row('producer', 'command-16', 'test "$(/usr/bin/stat -c %h "$source")" = 1', ((25, 1),))
    row('producer', 'command-17', '/usr/bin/install -m 0444 "$source" "$PATCH_TOOL_ROOT/$source"', ((25, 1),), resource=Resource.CONTROL, access=Access.CREATE, extra=(ResourceAccess(Resource.CONTROL, Access.READ),))
    row('producer', 'command-18', '/bin/chmod 0555 "$PATCH_TOOL_ROOT" "$PATCH_TOOL_ROOT/scripts" "$PATCH_TOOL_ROOT/scripts/modernize"', ((0, 1),), resource=Resource.CONTROL, access=Access.WRITE)
    row('staging', 'git-environment', 'unset GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_CEILING_DIRECTORIES GIT_COMMON_DIR GIT_DIR GIT_EXEC_PATH GIT_INDEX_FILE GIT_NAMESPACE GIT_OBJECT_DIRECTORY GIT_REPLACE_REF_BASE GIT_WORK_TREE', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'program-source', '/usr/bin/git show "$PATCH_COMMIT:scripts/workflow_pilot/publisher_programs.py" > "$PATCH_RUNTIME_ROOT/publisher-programs.py"', ((0, 1),), resource=Resource.CONTROL, access=Access.WRITE, extra=(ResourceAccess(Resource.CONTROL, Access.READ),))
    row('staging', 'candidate-source', '/usr/bin/git show "$PATCH_COMMIT:scripts/workflow_pilot/publisher_candidate.py" > "$PATCH_RUNTIME_ROOT/candidate-launcher.py"', ((0, 1),), resource=Resource.CONTROL, access=Access.WRITE, extra=(ResourceAccess(Resource.CONTROL, Access.READ),))
    row('staging', 'authority-source', '/usr/bin/git show "$PATCH_COMMIT:scripts/workflow_pilot/publisher_inventory.py" > "$PATCH_RUNTIME_ROOT/publisher-inventory.py"', ((0, 1),), resource=Resource.CONTROL, access=Access.WRITE, extra=(ResourceAccess(Resource.CONTROL, Access.READ),))
    row('staging', 'command-3', 'builder_user=ci-patch-builder', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-4', 'builder_uid=""', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-5', 'builder_gid=""', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-6', 'builder_cgroup=""', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-7', 'builder_cgroup_owned=0', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-8', 'builder_session_authenticated=0', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-9', 'builder_session_id=""', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-10', 'builder_supervisor_parent_pid="$$"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-11', 'builder_supervisor_pid=""', ((0, 2),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-12', 'builder_supervisor_starttime=""', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-13', 'builder_supervisor_state=""', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-14', 'builder_supervisor_wait_pid=""', ((0, 2),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-15', 'builder_passwd_probe_state=""', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-16', 'builder_root_owned=0', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-17', 'builder_uid_occupancy_state=""', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-18', 'builder_user_created=0', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-19', 'wheelhouse_owned=0', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-20', 'shell_pgid="$(/usr/bin/ps -o pgid= -p "$$" 2>/dev/null | /usr/bin/tr -d \' \' 2>/dev/null)"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('builder_passwd_entry_exists', 'command-1', '/usr/bin/getent passwd "$1" > /dev/null 2>&1', ((0, 1),))
    row('probe_builder_passwd_entry', 'command-1', 'local status', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('probe_builder_passwd_entry', 'command-2', 'builder_passwd_entry_exists "$1"', ((26, 1),))
    row('probe_builder_passwd_entry', 'command-3', 'builder_passwd_probe_state=present', ((27, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('probe_builder_passwd_entry', 'command-4', 'return 0', ((27, 1), (28, 1)))
    row('probe_builder_passwd_entry', 'command-5', 'status="$?"', ((1, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('probe_builder_passwd_entry', 'command-6', 'builder_passwd_probe_state=absent', ((28, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('probe_builder_passwd_entry', 'command-7', 'builder_passwd_probe_state=error', ((29, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('probe_builder_passwd_entry', 'command-8', 'return "$status"', ((29, 1),))
    row('builder_passwd_entry_absent', 'command-1', 'probe_builder_passwd_entry "$1"', ((30, 1),))
    row('builder_passwd_entry_absent', 'command-2', 'return "$?"', ((31, 1),))
    row('builder_passwd_entry_absent', 'command-3', 'test "$builder_passwd_probe_state" = absent', ((0, 1),))
    row('builder_group_pids', 'command-1', 'local output', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('builder_group_pids', 'command-2', 'output="$(\n /usr/bin/ps -eo pgid=,pid= 2>/dev/null | /usr/bin/awk -v pgid="$1" \'$1 == pgid {print $2}\' 2>/dev/null\n )"', ((30, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('builder_group_pids', 'command-3', 'return 1', ((31, 1),))
    row('builder_group_pids', 'command-4', 'printf \'%s\' "$output"', ((0, 1),))
    row('builder_uid_pids', 'command-1', 'local output', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('builder_uid_pids', 'command-2', 'output="$(\n /usr/bin/ps -eo uid=,pid= 2>/dev/null | /usr/bin/awk -v uid="$1" \'$1 == uid {print $2}\' 2>/dev/null\n )"', ((30, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('builder_uid_pids', 'command-3', 'return 1', ((31, 1),))
    row('builder_uid_pids', 'command-4', 'printf \'%s\' "$output"', ((0, 1),))
    row('builder_cgroup_pids', 'command-1', 'local output', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('builder_cgroup_pids', 'command-2', '[ "$builder_cgroup_owned" = 1 ]', ((33, 1),))
    row('builder_cgroup_pids', 'command-3', '[ -r "$builder_cgroup/cgroup.procs" ]', ((34, 1),))
    row('builder_cgroup_pids', 'command-4', 'output="$(/bin/cat "$builder_cgroup/cgroup.procs" 2>/dev/null)"', ((36, 1),), resource=Resource.CGROUP_RAW, access=Access.READ)
    row('builder_cgroup_pids', 'command-5', 'return 1', ((37, 1),))
    row('builder_cgroup_pids', 'command-6', 'printf \'%s\' "$output"', ((35, 1),))
    row('builder_group_is_empty', 'command-1', 'local output', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('builder_group_is_empty', 'command-2', 'output="$(builder_group_pids "$1")"', ((30, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('builder_group_is_empty', 'command-3', 'return 1', ((31, 1),))
    row('builder_group_is_empty', 'command-4', 'test -z "$output"', ((0, 1),))
    row('read_builder_identity', 'command-1', 'local process_identity', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('read_builder_identity', 'command-2', 'local process_pgid', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('read_builder_identity', 'command-3', 'local process_sid', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('read_builder_identity', 'command-4', 'local process_stat', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('read_builder_identity', 'command-5', 'local stat_record', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('read_builder_identity', 'command-6', 'local stat_tail', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('read_builder_identity', 'command-7', 'process_identity="$(\n /usr/bin/ps -o sid=,pgid=,stat= -p "$1" 2>/dev/null | /usr/bin/awk \'NF == 3 {print $1 " " $2 " " $3}\' 2>/dev/null\n )"', ((30, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('read_builder_identity', 'command-8', 'return 1', ((31, 9), (38, 1)))
    row('read_builder_identity', 'command-9', '[[ "$process_identity" =~ ^([1-9][0-9]*)[[:space:]]+([1-9][0-9]*)[[:space:]]+([^[:space:]]+)$ ]]', ((30, 1),))
    row('read_builder_identity', 'command-10', 'process_sid="${BASH_REMATCH[1]}"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('read_builder_identity', 'command-11', 'process_pgid="${BASH_REMATCH[2]}"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('read_builder_identity', 'command-12', 'process_stat="${BASH_REMATCH[3]}"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('read_builder_identity', 'command-13', 'stat_record="$(/bin/cat "/proc/$1/stat" 2>/dev/null)"', ((30, 1),), resource=Resource.PROCESS, access=Access.READ)
    row('read_builder_identity', 'command-14', 'stat_tail="${stat_record##*) }"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('read_builder_identity', 'command-15', 'set -- $stat_tail', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('read_builder_identity', 'command-16', 'test "$#" -ge 20', ((30, 1),))
    row('read_builder_identity', 'command-17', 'test "$2" = "$builder_supervisor_parent_pid"', ((30, 1),))
    row('read_builder_identity', 'command-18', 'test "$3" = "$process_pgid"', ((30, 1),))
    row('read_builder_identity', 'command-19', 'test "$4" = "$process_sid"', ((30, 1),))
    row('read_builder_identity', 'command-20', 'test "${process_stat:0:1}" = "$1"', ((30, 1),))
    row('read_builder_identity', 'command-21', '[[ "${20}" =~ ^[1-9][0-9]*$ ]]', ((30, 1),))
    row('read_builder_identity', 'command-22', 'printf \'%s %s %s %s %s\' "$2" "$4" "$3" "$process_stat" "${20}"', ((0, 1),))
    row('builder_supervisor_identity_matches', 'command-1', 'local expected_state="$1"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('builder_supervisor_identity_matches', 'command-2', 'local identity', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('builder_supervisor_identity_matches', 'command-3', 'test "$builder_session_authenticated" = 1', ((30, 1),))
    row('builder_supervisor_identity_matches', 'command-4', 'return 1', ((31, 12), (39, 1)))
    row('builder_supervisor_identity_matches', 'command-5', '[[ "$builder_session_id" =~ ^[1-9][0-9]*$ ]]', ((30, 1),))
    row('builder_supervisor_identity_matches', 'command-6', 'test "$builder_session_id" != "$shell_pgid"', ((30, 1),))
    row('builder_supervisor_identity_matches', 'command-7', 'test -n "$builder_supervisor_pid"', ((30, 1),))
    row('builder_supervisor_identity_matches', 'command-8', 'test "$builder_session_id" = "$builder_supervisor_pid"', ((30, 1),))
    row('builder_supervisor_identity_matches', 'command-9', 'test "$builder_supervisor_wait_pid" = "$builder_supervisor_pid"', ((30, 1),))
    row('builder_supervisor_identity_matches', 'command-10', 'identity="$(read_builder_identity "$builder_supervisor_pid")"', ((30, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('builder_supervisor_identity_matches', 'command-11', '[[ "$identity" =~ ^([1-9][0-9]*)[[:space:]]+([1-9][0-9]*)[[:space:]]+([1-9][0-9]*)[[:space:]]+([^[:space:]]+)[[:space:]]+([1-9][0-9]*)$ ]]', ((30, 1),))
    row('builder_supervisor_identity_matches', 'command-12', 'test "${BASH_REMATCH[1]}" = "$builder_supervisor_parent_pid"', ((30, 1),))
    row('builder_supervisor_identity_matches', 'command-13', 'test "${BASH_REMATCH[2]}" = "$builder_session_id"', ((30, 1),))
    row('builder_supervisor_identity_matches', 'command-14', 'test "${BASH_REMATCH[3]}" = "$builder_session_id"', ((30, 1),))
    row('builder_supervisor_identity_matches', 'command-15', 'test "${BASH_REMATCH[5]}" = "$builder_supervisor_starttime"', ((30, 1),))
    row('builder_supervisor_identity_matches', 'command-16', '[[ "${BASH_REMATCH[4]}" = T* ]]', ((40, 1),))
    row('builder_supervisor_identity_matches', 'command-17', '[[ "${BASH_REMATCH[4]}" != Z* ]]', ((41, 1),))
    row('builder_supervisor_identity_matches', 'command-18', '[[ "${BASH_REMATCH[4]}" != T* && "${BASH_REMATCH[4]}" != Z* ]]', ((42, 1),))
    row('builder_supervisor_identity_matches', 'command-19', '[[ "${BASH_REMATCH[4]}" = Z* ]]', ((43, 1),))
    row('builder_supervisor_identity_matches', 'command-20', 'true', ((44, 1),))
    row('probe_builder_uid_occupancy', 'command-1', 'local output', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('probe_builder_uid_occupancy', 'command-2', 'local status', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('probe_builder_uid_occupancy', 'command-3', 'output="$(builder_uid_pids "$1")"', ((45, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('probe_builder_uid_occupancy', 'command-4', '[ -z "$output" ]', ((46, 1),))
    row('probe_builder_uid_occupancy', 'command-5', 'builder_uid_occupancy_state=free', ((47, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('probe_builder_uid_occupancy', 'command-6', 'builder_uid_occupancy_state=occupied', ((48, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('probe_builder_uid_occupancy', 'command-7', 'return 0', ((2, 1),))
    row('probe_builder_uid_occupancy', 'command-8', 'status="$?"', ((49, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('probe_builder_uid_occupancy', 'command-9', 'builder_uid_occupancy_state=error', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('probe_builder_uid_occupancy', 'command-10', 'return "$status"', ((0, 1),))
    row('builder_uid_is_empty', 'command-1', 'probe_builder_uid_occupancy "$1"', ((30, 1),))
    row('builder_uid_is_empty', 'command-2', 'return "$?"', ((31, 1),))
    row('builder_uid_is_empty', 'command-3', 'test "$builder_uid_occupancy_state" = free', ((0, 1),))
    row('builder_cgroup_is_empty', 'command-1', 'local output', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('builder_cgroup_is_empty', 'command-2', 'output="$(builder_cgroup_pids)"', ((30, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('builder_cgroup_is_empty', 'command-3', 'return 1', ((31, 1),))
    row('builder_cgroup_is_empty', 'command-4', 'test -z "$output"', ((0, 1),))
    row('terminate_builder_processes', 'command-1', 'cleanup_failed=0', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('terminate_builder_processes', 'command-2', 'supervisor_authenticated=0', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('terminate_builder_processes', 'command-3', '[ -n "$builder_session_id" ]', ((51, 1), (52, 1)))
    row('terminate_builder_processes', 'command-4', '[ -n "$builder_supervisor_pid" ]', ((53, 1), (55, 1)))
    row('terminate_builder_processes', 'command-5', 'builder_supervisor_identity_matches zombie', ((56, 1), (57, 1), (58, 1)))
    row('terminate_builder_processes', 'command-6', 'supervisor_authenticated=1', ((59, 1), (5, 1)), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('terminate_builder_processes', 'command-7', 'builder_supervisor_identity_matches "$builder_supervisor_state"', ((60, 1), (62, 1)))
    row('terminate_builder_processes', 'command-8', 'remaining_group=""', ((5, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('terminate_builder_processes', 'command-9', 'remaining_group="$(builder_group_pids "$builder_session_id")"', ((63, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('terminate_builder_processes', 'command-10', 'cleanup_failed=1', ((64, 1), (65, 1), (66, 1), (67, 1), (68, 1), (70, 1), (31, 1)), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('terminate_builder_processes', 'command-11', '[ -n "$remaining_group" ]', ((71, 1),))
    row('terminate_builder_processes', 'command-12', '/usr/bin/sudo /bin/kill -TERM -- "-$builder_session_id" > /dev/null 2>&1', ((73, 1),), resource=Resource.PROCESS, access=Access.WRITE)
    row('terminate_builder_processes', 'command-13', 'true', ((74, 1), (76, 1), (78, 1)))
    row('terminate_builder_processes', 'command-14', '/bin/sleep 1', ((72, 1),))
    row('terminate_builder_processes', 'command-15', ':', ((79, 1),))
    row('terminate_builder_processes', 'command-16', 'builder_supervisor_identity_matches owned', ((80, 1),))
    row('terminate_builder_processes', 'command-17', '/usr/bin/sudo /bin/kill -KILL -- "-$builder_session_id" > /dev/null 2>&1', ((81, 1),), resource=Resource.PROCESS, access=Access.WRITE)
    row('terminate_builder_processes', 'command-18', '/bin/sleep 0.1', ((75, 1), (9, 1), (11, 1)))
    row('terminate_builder_processes', 'command-19', '[ "$builder_cgroup_owned" = 1 ]', ((82, 1),))
    row('terminate_builder_processes', 'command-20', '! builder_cgroup_is_empty', ((83, 1),))
    row('terminate_builder_processes', 'command-21', "printf '1\\n'", ((84, 1),))
    row('terminate_builder_processes', 'command-22', '/usr/bin/sudo /usr/bin/tee "$builder_cgroup/cgroup.kill" > /dev/null 2>&1', ((85, 1),), resource=Resource.CGROUP_RAW, access=Access.WRITE)
    row('terminate_builder_processes', 'command-23', 'builder_cgroup_is_empty', ((86, 1), (87, 1)))
    row('terminate_builder_processes', 'command-24', 'break', ((88, 1), (89, 1), (90, 1), (67, 1)))
    row('terminate_builder_processes', 'command-25', '[ "$supervisor_authenticated" = 1 ]', ((91, 1),))
    row('terminate_builder_processes', 'command-26', 'supervisor_reap_ready=0', ((10, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('terminate_builder_processes', 'command-27', 'supervisor_reap_ready=1', ((89, 1), (90, 1)), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('terminate_builder_processes', 'command-28', '[ ! -e "/proc/$builder_supervisor_pid" ]', ((92, 1),))
    row('terminate_builder_processes', 'command-29', '! builder_supervisor_identity_matches owned', ((93, 1),))
    row('terminate_builder_processes', 'command-30', '[ "$supervisor_reap_ready" = 1 ]', ((95, 1),))
    row('terminate_builder_processes', 'command-31', '[ "$builder_supervisor_wait_pid" = "$builder_supervisor_pid" ]', ((96, 1),))
    row('terminate_builder_processes', 'command-32', 'wait "$builder_supervisor_wait_pid" > /dev/null 2>&1', ((97, 1),))
    row('terminate_builder_processes', 'command-33', 'builder_supervisor_pid=""', ((77, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('terminate_builder_processes', 'command-34', 'builder_supervisor_wait_pid=""', ((77, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('terminate_builder_processes', 'command-35', 'builder_group_is_empty "$builder_session_id"', ((98, 1),))
    row('terminate_builder_processes', 'command-36', 'builder_uid_is_empty "$builder_uid"', ((30, 1),))
    row('terminate_builder_processes', 'command-37', 'return "$cleanup_failed"', ((0, 1),))
    row('remove_builder_cgroup', 'command-1', 'cleanup_failed=0', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('remove_builder_cgroup', 'command-2', '[ "$builder_cgroup_owned" = 1 ]', ((99, 1),))
    row('remove_builder_cgroup', 'command-3', 'builder_cgroup_is_empty', ((100, 1),))
    row('remove_builder_cgroup', 'command-4', 'cleanup_failed=1', ((101, 1), (102, 1), (31, 1)), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('remove_builder_cgroup', 'command-5', '[ "$cleanup_failed" = 0 ]', ((104, 1),))
    row('remove_builder_cgroup', 'command-6', '/usr/bin/sudo /usr/bin/rmdir -- "$builder_cgroup" > /dev/null 2>&1', ((105, 1),), resource=Resource.CGROUP_RAW, access=Access.REMOVE)
    row('remove_builder_cgroup', 'command-7', 'builder_cgroup_owned=0', ((106, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('remove_builder_cgroup', 'command-8', 'test ! -e "$builder_cgroup"', ((30, 1),))
    row('remove_builder_cgroup', 'command-9', 'return "$cleanup_failed"', ((0, 1),))
    row('remove_builder_state', 'command-1', 'cleanup_failed=0', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('remove_builder_state', 'command-2', '[ "$builder_user_created" = 1 ]', ((107, 1),))
    row('remove_builder_state', 'command-3', 'builder_passwd_entry_exists "$builder_user"', ((108, 1),))
    row('remove_builder_state', 'command-4', '/usr/bin/sudo /usr/sbin/userdel "$builder_user" > /dev/null 2>&1', ((109, 1),), resource=Resource.PROCESS, access=Access.REMOVE)
    row('remove_builder_state', 'command-5', 'builder_user_created=0', ((110, 1), (111, 1)), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('remove_builder_state', 'command-6', 'cleanup_failed=1', ((112, 1), (113, 1), (114, 1), (31, 3)), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('remove_builder_state', 'command-7', '[ "$builder_root_owned" = 1 ]', ((115, 1),))
    row('remove_builder_state', 'command-8', '/usr/bin/sudo /bin/rm -rf -- "$BUILDER_ROOT" > /dev/null 2>&1', ((116, 1),), resource=Resource.CONTROL, access=Access.REMOVE)
    row('remove_builder_state', 'command-9', 'builder_root_owned=0', ((117, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('remove_builder_state', 'command-10', '[ "$wheelhouse_owned" = 1 ]', ((118, 1),))
    row('remove_builder_state', 'command-11', '/bin/rm -rf -- "$PATCH_WHEELHOUSE" > /dev/null 2>&1', ((119, 1),), resource=Resource.CONTROL, access=Access.REMOVE)
    row('remove_builder_state', 'command-12', 'wheelhouse_owned=0', ((120, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('remove_builder_state', 'command-13', 'builder_passwd_entry_absent "$builder_user"', ((30, 1),))
    row('remove_builder_state', 'command-14', 'test ! -e "$BUILDER_ROOT"', ((30, 1),))
    row('remove_builder_state', 'command-15', 'test ! -e "$PATCH_WHEELHOUSE"', ((30, 1),))
    row('remove_builder_state', 'command-16', 'return "$cleanup_failed"', ((0, 1),))
    row('cleanup_builder', 'command-1', 'status="$?"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('cleanup_builder', 'command-2', 'trap - EXIT INT TERM', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('cleanup_builder', 'command-3', 'set +e', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('cleanup_builder', 'command-4', 'terminate_builder_processes', ((0, 1),))
    row('cleanup_builder', 'command-5', 'process_cleanup="$?"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('cleanup_builder', 'command-6', 'remove_builder_cgroup', ((0, 1),))
    row('cleanup_builder', 'command-7', 'cgroup_cleanup="$?"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('cleanup_builder', 'command-8', 'remove_builder_state', ((0, 1),))
    row('cleanup_builder', 'command-9', 'state_cleanup="$?"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('cleanup_builder', 'command-10', '[ "$process_cleanup" -ne 0 ]', ((122, 2),))
    row('cleanup_builder', 'command-11', '[ "$cgroup_cleanup" -ne 0 ]', ((123, 2),))
    row('cleanup_builder', 'command-12', '[ "$state_cleanup" -ne 0 ]', ((124, 2),))
    row('cleanup_builder', 'command-13', 'printf \'candidate build cleanup failed: process=%d cgroup=%d state=%d primary=%d\\n\' "$process_cleanup" "$cgroup_cleanup" "$state_cleanup" "$status" >&2', ((125, 1),))
    row('cleanup_builder', 'command-14', '[ "$status" -ne 0 ]', ((126, 1),))
    row('cleanup_builder', 'command-15', 'exit "$status"', ((127, 1),))
    row('cleanup_builder', 'command-16', 'exit 1', ((125, 1),))
    row('cleanup_builder', 'command-17', 'exit 0', ((0, 1),))
    row('staging', 'command-21', 'trap cleanup_builder EXIT', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-22', "trap 'exit 130' INT", ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-23', "trap 'exit 143' TERM", ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-24', 'test ! -e "$BUILDER_ROOT"', ((0, 2),))
    row('staging', 'command-25', 'test -d "$PATCH_WHEELHOUSE"', ((0, 1),))
    row('staging', 'command-26', 'test ! -L "$PATCH_WHEELHOUSE"', ((0, 1),))
    row('staging', 'command-27', 'wheelhouse_owned=1', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-28', 'builder_passwd_entry_absent "$builder_user"', ((0, 2),))
    row('staging', 'command-29', '/usr/bin/install -d -m 0700 "$BUILDER_ROOT"', ((0, 1),), resource=Resource.CONTROL, access=Access.CREATE)
    row('staging', 'command-30', 'builder_root_owned=1', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-31', '/usr/bin/install -d -m 0700 "$BUILDER_ROOT/control" "$BUILDER_ROOT/handoff" "$BUILDER_ROOT/source" "$BUILDER_ROOT/wheelhouse"', ((0, 1),), resource=Resource.CONTROL, access=Access.CREATE)
    row('staging', 'command-32', '/bin/cp -a -- "$GITHUB_WORKSPACE_PATH/." "$BUILDER_ROOT/source/"', ((0, 1),), resource=Resource.CANDIDATE, access=Access.WRITE)
    row('staging', 'command-33', '/bin/cp -a -- "$PATCH_WHEELHOUSE/." "$BUILDER_ROOT/wheelhouse/"', ((0, 1),), resource=Resource.CONTROL, access=Access.WRITE)
    row('staging', 'command-34', 'builder_uid=60000', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-35', '[ "$builder_uid" -ge 50000 ]', ((128, 1),))
    row('staging', 'command-36', 'probe_builder_passwd_entry "$builder_uid"', ((17, 1),))
    row('staging', 'command-37', '[ "$builder_passwd_probe_state" = absent ]', ((129, 1),))
    row('staging', 'command-38', 'probe_builder_uid_occupancy "$builder_uid"', ((18, 1),))
    row('staging', 'command-39', '[ "$builder_uid_occupancy_state" = free ]', ((130, 1),))
    row('staging', 'command-40', 'break', ((131, 1), (132, 1), (133, 1), (134, 1), (135, 1), (136, 1)))
    row('staging', 'command-41', 'builder_uid="$((builder_uid - 1))"', ((17, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-42', 'test "$builder_uid" -ge 50000', ((0, 1),))
    row('staging', 'command-43', '/usr/bin/sudo /usr/sbin/useradd --no-create-home --no-user-group --gid nogroup --uid "$builder_uid" --home-dir "$BUILDER_ROOT/home" --shell /usr/sbin/nologin "$builder_user"', ((0, 1),), resource=Resource.PROCESS, access=Access.CREATE)
    row('staging', 'command-44', 'builder_user_created=1', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-45', 'test "$(/usr/bin/id -u "$builder_user")" = "$builder_uid"', ((0, 1),))
    row('staging', 'command-46', 'builder_gid="$(/usr/bin/id -g "$builder_user")"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-47', 'builder_uid_is_empty "$builder_uid"', ((0, 3),))
    row('staging', 'command-48', '/usr/bin/tee "$BUILDER_ROOT/control/builder-isolation.sh" > /dev/null <<\'BUILDER_ISOLATION\'\nBUILDER_ISOLATION\n', ((0, 1),), resource=Resource.CONTROL, access=Access.WRITE, payloads=(Payload('BUILDER_ISOLATION', 'builder'),))
    row('staging', 'command-49', '/usr/bin/tee "$BUILDER_ROOT/control/candidate-build.sh" > /dev/null <<\'CANDIDATE_BUILD\'\nCANDIDATE_BUILD\n', ((0, 1),), resource=Resource.CONTROL, access=Access.WRITE, payloads=(Payload('CANDIDATE_BUILD', 'shell'),))
    row('staging', 'command-51', '/usr/bin/tee "$BUILDER_ROOT/control/supervisor-launcher.py" > /dev/null <<\'SUPERVISOR_LAUNCHER\'\nSUPERVISOR_LAUNCHER\n', ((0, 1),), resource=Resource.CONTROL, access=Access.WRITE, payloads=(Payload('SUPERVISOR_LAUNCHER', 'python'),))
    row('staging', 'command-52', '/bin/chmod 0500 "$BUILDER_ROOT/control/builder-isolation.sh"', ((0, 1),), resource=Resource.CONTROL, access=Access.WRITE)
    row('staging', 'command-53', '/bin/chmod 0400 "$BUILDER_ROOT/control/candidate-build.sh"', ((0, 1),), resource=Resource.CONTROL, access=Access.WRITE)
    row('staging', 'command-54', '/bin/chmod 0400 "$PATCH_RUNTIME_ROOT/candidate-launcher.py"', ((0, 1),), resource=Resource.CONTROL, access=Access.WRITE)
    row('staging', 'command-55', '/bin/chmod 0400 "$BUILDER_ROOT/control/supervisor-launcher.py"', ((0, 1),), resource=Resource.CONTROL, access=Access.WRITE)
    row('staging', 'command-56', '/usr/bin/sudo /bin/chown -R "$builder_uid:$builder_gid" "$BUILDER_ROOT/wheelhouse"', ((0, 1),), resource=Resource.CONTROL, access=Access.WRITE)
    row('staging', 'command-57', '/usr/bin/sudo /usr/bin/unshare --fork --kill-child=KILL --mount --pid --mount-proc --net --ipc --uts /bin/true', ((0, 1),), resource=Resource.PROCESS, access=Access.EXECUTE)
    row('staging', 'command-58', 'test -r /sys/fs/cgroup/cgroup.controllers', ((0, 1),))
    row('staging', 'command-59', 'cgroup_relative="$(/usr/bin/awk -F: \'$1 == "0" && $2 == "" {print $3}\' /proc/self/cgroup)"', ((0, 1),), resource=Resource.CGROUP_RAW, access=Access.READ)
    row('staging', 'command-60', 'echo "invalid cgroup v2 membership" >&2', ((137, 1),))
    row('staging', 'command-61', 'exit 1', ((137, 1), (138, 1), (139, 1), (140, 1)))
    row('staging', 'command-62', 'echo "unsafe cgroup v2 membership" >&2', ((138, 1),))
    row('staging', 'command-63', 'cgroup_parent="$(/usr/bin/realpath -m "/sys/fs/cgroup$cgroup_relative")"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-64', 'echo "cgroup v2 membership escaped mount" >&2', ((139, 1),))
    row('staging', 'command-65', 'test -d "$cgroup_parent"', ((0, 1),))
    row('staging', 'command-66', 'builder_cgroup="$cgroup_parent/ci-patch-builder"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-67', 'test ! -e "$builder_cgroup"', ((0, 3),))
    row('staging', 'command-68', '/usr/bin/sudo /usr/bin/mkdir -- "$builder_cgroup"', ((0, 1),), resource=Resource.CGROUP_RAW, access=Access.CREATE)
    row('staging', 'command-69', 'builder_cgroup_owned=1', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-70', 'test -f "$builder_cgroup/cgroup.kill"', ((0, 1),))
    row('staging', 'command-71', 'test -f "$builder_cgroup/cgroup.procs"', ((0, 1),))
    row('staging', 'command-72', 'test -r "$builder_cgroup/cgroup.procs"', ((0, 1),))
    row('staging', 'command-73', 'builder_cgroup_is_empty', ((0, 2),))
    row('staging', 'command-74', 'host_uid="$(/usr/bin/id -u)"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-75', 'host_gid="$(/usr/bin/id -g)"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-76', 'builder_isolation_script="$(/bin/cat "$BUILDER_ROOT/control/builder-isolation.sh")"', ((0, 1),), resource=Resource.CONTROL, access=Access.READ)
    row('staging', 'command-77', 'test -n "$builder_isolation_script"', ((0, 1),))
    row('staging', 'command-78', '[[ "$shell_pgid" =~ ^[1-9][0-9]*$ ]]', ((0, 1),))
    row('staging', 'command-79', 'set +m', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-80', '/usr/bin/python3 -I -S "$BUILDER_ROOT/control/supervisor-launcher.py" "$$" -- /usr/bin/timeout --signal=TERM --kill-after=30s 55m /usr/bin/sudo /usr/bin/unshare --fork --kill-child=KILL --mount --pid --mount-proc --net --ipc --uts /bin/bash -c "$builder_isolation_script" builder-isolation "$builder_cgroup" "$builder_uid" "$builder_gid" "$BUILDER_ROOT" "$RUNNER_TEMP" "$BUILDER_ROOT/control/candidate-build.sh" "$PATCH_RUNTIME_ROOT/candidate-launcher.py" "$host_uid" "$host_gid" < /dev/null > /dev/null 2>&1', ((141, 1),), program=programs['launch'])
    row('staging', 'command-81', 'builder_supervisor_pid="$!"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-82', 'builder_supervisor_wait_pid="$builder_supervisor_pid"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-83', 'builder_launch_detail=session-timeout', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-84', '! /bin/kill -0 "$builder_supervisor_pid" > /dev/null 2>&1', ((142, 1),))
    row('staging', 'command-85', 'builder_launch_detail=session-exit', ((132, 1), (136, 1)), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-86', 'set +e', ((19, 1), (0, 1)), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-87', 'builder_identity="$(read_builder_identity "$builder_supervisor_pid")"', ((19, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-88', 'builder_identity_status="$?"', ((19, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-89', 'set -e', ((19, 1), (0, 1)), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-90', '[ "$builder_identity_status" -ne 0 ]', ((143, 1),))
    row('staging', 'command-91', 'builder_launch_detail=session-query', ((144, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-92', '! [[ "$builder_identity" =~ ^([1-9][0-9]*)[[:space:]]+([1-9][0-9]*)[[:space:]]+([1-9][0-9]*)[[:space:]]+([^[:space:]]+)[[:space:]]+([1-9][0-9]*)$ ]]', ((145, 1),))
    row('staging', 'command-93', 'builder_launch_detail=session-format', ((146, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-94', '[ "${BASH_REMATCH[1]}" = "$builder_supervisor_parent_pid" ]', ((148, 1),))
    row('staging', 'command-95', '[ "${BASH_REMATCH[2]}" = "$builder_supervisor_pid" ]', ((149, 1),))
    row('staging', 'command-96', '[ "${BASH_REMATCH[3]}" = "$builder_supervisor_pid" ]', ((150, 1),))
    row('staging', 'command-97', '[[ "${BASH_REMATCH[4]}" = T* ]]', ((151, 1),))
    row('staging', 'command-98', 'builder_session_id="$builder_supervisor_pid"', ((133, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-99', 'builder_supervisor_starttime="${BASH_REMATCH[5]}"', ((133, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-100', 'builder_supervisor_state=stopped', ((133, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-101', 'builder_session_authenticated=1', ((133, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-102', 'builder_launch_detail=session-ready', ((133, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-103', 'builder_launch_detail=session-state', ((22, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-104', '[ "${BASH_REMATCH[3]}" = "$shell_pgid" ]', ((152, 1),))
    row('staging', 'command-105', 'builder_launch_detail=session-parent', ((153, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-106', 'builder_launch_detail=session-mismatch', ((134, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-107', '/bin/sleep 0.01', ((19, 2),))
    row('staging', 'command-108', '[ "$builder_launch_detail" != session-ready ]', ((154, 1),))
    row('staging', 'command-109', 'builder_status=125', ((155, 1), (156, 1), (157, 1), (isolated_transport, 1)), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-110', 'printf \'candidate build failed: stage=launch detail=%s exit=%d\\n\' "$builder_launch_detail" "$builder_status" >&2', ((155, 1), (157, 1)))
    row('staging', 'command-111', 'exit "$builder_status"', ((155, 1), (156, 1), (157, 1), (158, 1)))
    row('staging', 'command-112', '! builder_supervisor_identity_matches stopped', ((160, 1),))
    row('staging', 'command-113', '! /bin/kill -CONT "$builder_supervisor_pid" > /dev/null 2>&1', ((161, 1),), resource=Resource.PROCESS, access=Access.WRITE)
    row('staging', 'command-114', 'printf \'candidate build failed: stage=launch detail=session-resume exit=%d\\n\' "$builder_status" >&2', ((156, 1),))
    row('staging', 'command-115', 'builder_supervisor_state=starting', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-116', 'builder_launch_detail=session-start-timeout', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-117', 'builder_supervisor_identity_matches running', ((162, 1),))
    row('staging', 'command-118', 'builder_supervisor_state=running', ((135, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-119', 'builder_launch_detail=session-started', ((135, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-120', 'builder_supervisor_identity_matches zombie', ((163, 1),))
    row('staging', 'command-121', '[ "$builder_launch_detail" != session-started ]', ((164, 1),))
    row('staging', 'command-122', 'wait "$builder_supervisor_pid"', ((0, 1),))
    row('staging', 'command-123', 'builder_status="$?"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-124', '[ "$builder_status" -ne 0 ]', ((165, 1),))
    row('staging', 'command-125', 'printf \'candidate build failed: stage=isolated detail=%s exit=%d\\n\' "$builder_isolated_detail" "$builder_status" >&2', ((158, 1),))
    row('staging', 'command-126', "printf 'candidate build status: success\\n'", ((0, 1),))
    row('staging', 'command-127', 'builder_group_is_empty "$builder_session_id"', ((0, 2),))
    row('staging', 'command-128', 'remove_builder_cgroup', ((0, 2),))
    row('staging', 'command-129', 'handoff_root="$BUILDER_ROOT/handoff"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-130', 'test -d "$handoff_root"', ((0, 1),))
    row('staging', 'command-131', 'test ! -L "$handoff_root"', ((0, 1),))
    row('staging', 'command-132', 'test "$(/usr/bin/realpath "$handoff_root")" = "$handoff_root"', ((0, 1),))
    row('staging', 'command-133', 'test "$(/usr/bin/stat -c %u "$handoff_root")" = "$host_uid"', ((0, 1),))
    row('staging', 'command-134', 'handoff_names="$(/usr/bin/find "$handoff_root" -mindepth 1 -maxdepth 1 -printf \'%f\\n\' | LC_ALL=C /usr/bin/sort)"', ((0, 1),), resource=Resource.HANDOFF, access=Access.READ)
    row('staging', 'command-135', 'test "$handoff_names" = "$(printf \'metadata.json\\ntarget.gba\')"', ((0, 1),))
    row('staging', 'command-136', 'target_source="$handoff_root/target.gba"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-137', 'metadata_source="$handoff_root/metadata.json"', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-138', 'test -f "$source"', ((24, 1),))
    row('staging', 'command-139', 'test ! -L "$source"', ((24, 1),))
    row('staging', 'command-140', 'test "$(/usr/bin/stat -c %F "$source")" = "regular file"', ((24, 1),))
    row('staging', 'command-141', 'test "$(/usr/bin/stat -c %h "$source")" = 1', ((24, 1),))
    row('staging', 'command-142', 'test "$(/usr/bin/stat -c %u "$source")" = "$host_uid"', ((24, 1),))
    row('staging', 'command-143', 'echo "builder output escaped isolated handoff" >&2', ((140, 1),))
    row('staging', 'command-144', 'test "$(/usr/bin/stat -c %s "$target_source")" = 33554432', ((0, 1),))
    row('staging', 'command-145', 'metadata_size="$(/usr/bin/stat -c %s "$metadata_source")"', ((0, 1),), resource=Resource.HANDOFF, access=Access.INSPECT)
    row('staging', 'command-146', 'test "$metadata_size" -gt 0', ((0, 1),))
    row('staging', 'command-147', 'test "$metadata_size" -le 1048576', ((0, 1),))
    row('staging', 'command-148', '/bin/rm -rf -- "$PATCH_INPUT_ROOT"', ((0, 1),), resource=Resource.HANDOFF, access=Access.REMOVE)
    row('staging', 'command-149', '/usr/bin/install -d -m 0700 "$PATCH_INPUT_ROOT"', ((0, 1),), resource=Resource.HANDOFF, access=Access.CREATE)
    row('staging', 'command-150', '/usr/bin/install -m 0400 "$target_source" "$PATCH_INPUT_ROOT/target.gba"', ((0, 1),), resource=Resource.HANDOFF, access=Access.WRITE, extra=(ResourceAccess(Resource.HANDOFF, Access.READ),))
    row('staging', 'command-151', '/usr/bin/install -m 0400 "$metadata_source" "$PATCH_INPUT_ROOT/metadata.json"', ((0, 1),), resource=Resource.HANDOFF, access=Access.WRITE, extra=(ResourceAccess(Resource.HANDOFF, Access.READ),))
    row('staging', 'command-152', '/usr/bin/find "$GITHUB_WORKSPACE_PATH" -mindepth 1 -delete', ((0, 1),), resource=Resource.HOST, access=Access.REMOVE)
    row('staging', 'command-153', 'test -z "$(/usr/bin/find "$GITHUB_WORKSPACE_PATH" -mindepth 1 -print -quit)"', ((0, 1),))
    row('staging', 'command-154', 'terminate_builder_processes', ((0, 1),))
    row('staging', 'command-155', 'remove_builder_state', ((0, 1),))
    row('staging', 'command-156', 'trap - EXIT INT TERM', ((0, 1),), resource=Resource.SHELL, access=Access.WRITE, event=EventKind.STATE_WRITE)
    row('staging', 'command-157', 'test ! -e "$PATCH_WHEELHOUSE"', ((0, 1),))
    row('staging', 'command-158', 'input_names="$(/usr/bin/find "$PATCH_INPUT_ROOT" -mindepth 1 -maxdepth 1 -printf \'%f\\n\' | LC_ALL=C /usr/bin/sort)"', ((0, 1),), resource=Resource.HANDOFF, access=Access.READ)
    row('staging', 'command-159', 'test "$input_names" = "$(printf \'metadata.json\\ntarget.gba\')"', ((0, 1),))
    row('staging', 'command-160', 'test -f "$input"', ((166, 1),))
    row('staging', 'command-161', 'test ! -L "$input"', ((166, 1),))
    row('staging', 'command-162', 'test "$(/usr/bin/stat -c %F "$input")" = "regular file"', ((166, 1),))
    row('staging', 'command-163', 'test "$(/usr/bin/stat -c %h "$input")" = 1', ((166, 1),))
    row('staging', 'command-164', 'test "$(/usr/bin/stat -c %a "$input")" = 400', ((166, 1),))
    row('staging', 'command-165', '/usr/bin/env -i HOME="$PATCH_RUNTIME_ROOT" PATH=/usr/bin:/bin LC_ALL=C /usr/bin/python3 -I -S -c \'import json,sys; value=json.load(open(sys.argv[1], encoding="utf-8")); assert isinstance(value, dict); assert value.get("build_commit") == sys.argv[2]\' "$PATCH_INPUT_ROOT/metadata.json" "$PATCH_COMMIT"', ((0, 1),), program=programs['metadata'])
