	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x1FF
	tsa_entry 0x001
	tsa_entry 0x002, pal=10
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x003
	tsa_entry 0x004
	tsa_entry 0x005
	tsa_entry 0x006, pal=1
	tsa_entry 0x007, pal=1
	tsa_entry 0x008, pal=3
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x009
	tsa_entry 0x00A
	tsa_entry 0x00B, pal=5
	tsa_entry 0x00C
	tsa_entry 0x00D, pal=1
	tsa_entry 0x00E, pal=1
	tsa_entry 0x00F, pal=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x010, pal=2
	tsa_entry 0x011, pal=1
	tsa_entry 0x012
	tsa_entry 0x013
	tsa_entry 0x014, pal=5
	tsa_entry 0x015, pal=1
	tsa_entry 0x016, pal=5
	tsa_entry 0x017
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x018, pal=2
	tsa_entry 0x019, pal=1
	tsa_entry 0x01A, pal=1
	tsa_entry 0x01B, pal=5
	tsa_entry 0x01C, pal=1
	tsa_entry 0x01D, pal=10
	tsa_entry 0x01E, pal=1
	tsa_entry 0x01F, pal=5
	tsa_entry 0x020
	tsa_entry 0x021, pal=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x022, pal=1
	tsa_entry 0x023, pal=1
	tsa_entry 0x024
	tsa_entry 0x025, pal=5
	tsa_entry 0x026, pal=3
	tsa_entry 0x027, pal=2
	tsa_entry 0x028, pal=4
	tsa_entry 0x029
	tsa_entry 0x02A
	tsa_entry 0x02B
	tsa_entry 0x02C
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x02D, pal=1
	tsa_entry 0x02E, pal=1
	tsa_entry 0x02F, pal=1
	tsa_entry 0x030, pal=2
	tsa_entry 0x031, pal=5
	tsa_entry 0x032, pal=7
	tsa_entry 0x033, pal=6
	tsa_entry 0x034, pal=3
	tsa_entry 0x035
	tsa_entry 0x036
	tsa_entry 0x037
	tsa_entry 0x038, pal=10
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x039, pal=10
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x03A
	tsa_entry 0x03B, pal=2
	tsa_entry 0x03C, pal=1
	tsa_entry 0x03D
	tsa_entry 0x03E
	tsa_entry 0x03F, pal=8
	tsa_entry 0x040, pal=7
	tsa_entry 0x041, pal=7
	tsa_entry 0x042, pal=5
	tsa_entry 0x043, pal=5
	tsa_entry 0x044, pal=6
	tsa_entry 0x045, pal=3
	tsa_entry 0x046, pal=10
	tsa_entry 0x047, pal=10
	tsa_entry 0x048, pal=6
	tsa_entry 0x049, pal=3
	tsa_entry 0x04A, pal=7
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x04B
	tsa_entry 0x04C, pal=1
	tsa_entry 0x04D, pal=2
	tsa_entry 0x04E, pal=2
	tsa_entry 0x04F
	tsa_entry 0x050
	tsa_entry 0x051
	tsa_entry 0x052
	tsa_entry 0x053
	tsa_entry 0x054, pal=1
	tsa_entry 0x055
	tsa_entry 0x056
	tsa_entry 0x057, pal=2
	tsa_entry 0x058, pal=5
	tsa_entry 0x059, pal=5
	tsa_entry 0x05A, pal=5
	tsa_entry 0x05B, pal=5
	tsa_entry 0x05C, pal=6
	tsa_entry 0x05D, pal=6
	tsa_entry 0x05E, pal=6
	tsa_entry 0x05F, pal=6
	tsa_entry 0x060, pal=7
	tsa_entry 0x061, pal=7
	tsa_entry 0x062, pal=7
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x063, pal=8
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x064, pal=10
	tsa_entry 0x065
	tsa_entry 0x066
	tsa_entry 0x067
	tsa_entry 0x068, pal=1
	tsa_entry 0x069, pal=1
	tsa_entry 0x06A, pal=1
	tsa_entry 0x06B, pal=2
	tsa_entry 0x06C, pal=1
	tsa_entry 0x06D, pal=1
	tsa_entry 0x06E
	tsa_entry 0x06F
	tsa_entry 0x070, pal=8
	tsa_entry 0x071, pal=7
	tsa_entry 0x072, pal=2
	tsa_entry 0x073, pal=5
	tsa_entry 0x074, pal=5
	tsa_entry 0x075, pal=5
	tsa_entry 0x076, pal=5
	tsa_entry 0x077, pal=5
	tsa_entry 0x078, pal=5
	tsa_entry 0x079, pal=4
	tsa_entry 0x07A, pal=5
	tsa_entry 0x07B, pal=4
	tsa_entry 0x07C, pal=9
	tsa_entry 0x07D, pal=8
	tsa_entry 0x07E, pal=8
	tsa_entry 0x07F, pal=8
	tsa_entry 0x080, pal=8
	tsa_entry 0x081, pal=8
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x082
	tsa_entry 0x083
	tsa_entry 0x084
	tsa_entry 0x085, pal=1
	tsa_entry 0x086, pal=1
	tsa_entry 0x087, pal=1
	tsa_entry 0x088, pal=1
	tsa_entry 0x089, pal=1
	tsa_entry 0x08A, pal=1
	tsa_entry 0x08B
	tsa_entry 0x08C, pal=1
	tsa_entry 0x08D, pal=1
	tsa_entry 0x08E, pal=4
	tsa_entry 0x08F, pal=3
	tsa_entry 0x090, pal=7
	tsa_entry 0x091, pal=3
	tsa_entry 0x092, pal=1
	tsa_entry 0x093, pal=5
	tsa_entry 0x094, pal=5
	tsa_entry 0x095, pal=4
	tsa_entry 0x096, pal=6
	tsa_entry 0x097, pal=4
	tsa_entry 0x098, pal=6
	tsa_entry 0x099, pal=6
	tsa_entry 0x09A, pal=8
	tsa_entry 0x09B, pal=8
	tsa_entry 0x09C, pal=8
	tsa_entry 0x09D, pal=8
	tsa_entry 0x09E, pal=8
	tsa_entry 0x09F, pal=8
	tsa_entry 0x000
	tsa_entry 0x0A0, pal=1
	tsa_entry 0x0A1
	tsa_entry 0x0A2
	tsa_entry 0x0A3, pal=1
	tsa_entry 0x0A4, pal=1
	tsa_entry 0x0A5, pal=1
	tsa_entry 0x0A6, pal=2
	tsa_entry 0x0A7, pal=2
	tsa_entry 0x0A8, pal=1
	tsa_entry 0x0A9
	tsa_entry 0x0AA
	tsa_entry 0x0AB, pal=5
	tsa_entry 0x0AC, pal=4
	tsa_entry 0x0AD, pal=4
	tsa_entry 0x0AE, pal=3
	tsa_entry 0x0AF, pal=5
	tsa_entry 0x0B0, pal=3
	tsa_entry 0x0B1, pal=1
	tsa_entry 0x0B2, pal=5
	tsa_entry 0x0B3, pal=5
	tsa_entry 0x0B4, pal=10
	tsa_entry 0x0B5, pal=6
	tsa_entry 0x0B6, pal=3
	tsa_entry 0x0B7, pal=6
	tsa_entry 0x0B8, pal=6
	tsa_entry 0x0B9, pal=7
	tsa_entry 0x0BA, pal=7
	tsa_entry 0x0BB, pal=8
	tsa_entry 0x0BC, pal=8
	tsa_entry 0x0BD, pal=9
	tsa_entry 0x0BE, pal=9
	tsa_entry 0x0BF
	tsa_entry 0x0C0
	tsa_entry 0x000
	tsa_entry 0x0C1, pal=2
	tsa_entry 0x0C2, pal=1
	tsa_entry 0x0C3, pal=1
	tsa_entry 0x0C4, pal=2
	tsa_entry 0x0C5, pal=2
	tsa_entry 0x0C6, pal=2
	tsa_entry 0x0C7, pal=2
	tsa_entry 0x0C8, pal=6
	tsa_entry 0x0C9, pal=6
	tsa_entry 0x0CA, pal=4
	tsa_entry 0x0CB, pal=3
	tsa_entry 0x0CC, pal=6
	tsa_entry 0x0CD, pal=1
	tsa_entry 0x0CE, pal=6
	tsa_entry 0x0CF, pal=5
	tsa_entry 0x0D0
	tsa_entry 0x0D1, pal=5
	tsa_entry 0x0D2, pal=7
	tsa_entry 0x0D3, pal=6
	tsa_entry 0x0D4, pal=6
	tsa_entry 0x0D5, pal=6
	tsa_entry 0x0D6, pal=6
	tsa_entry 0x0D7, pal=7
	tsa_entry 0x0D8, pal=8
	tsa_entry 0x0D9, pal=10
	tsa_entry 0x0DA, pal=9
	tsa_entry 0x0DB, pal=8
	tsa_entry 0x0DC, pal=8
	tsa_entry 0x0DD, pal=9
	tsa_entry 0x0DE
	tsa_entry 0x0DF
	tsa_entry 0x0E0
	tsa_entry 0x0E1, pal=2
	tsa_entry 0x0E2, pal=10
	tsa_entry 0x0E3, pal=2
	tsa_entry 0x0E4, pal=2
	tsa_entry 0x0E5, pal=2
	tsa_entry 0x0E6
	tsa_entry 0x0E7, pal=2
	tsa_entry 0x0E8, pal=7
	tsa_entry 0x0E9, pal=6
	tsa_entry 0x0EA, pal=4
	tsa_entry 0x0EB
	tsa_entry 0x0EC, pal=6
	tsa_entry 0x0ED, pal=4
	tsa_entry 0x0EE, pal=6
	tsa_entry 0x0EF, pal=5
	tsa_entry 0x0F0, pal=4
	tsa_entry 0x0F1, pal=4
	tsa_entry 0x0F2, pal=5
	tsa_entry 0x0F3, pal=7
	tsa_entry 0x0F4, pal=6
	tsa_entry 0x0F5, pal=4
	tsa_entry 0x0F6, pal=4
	tsa_entry 0x0F7, pal=9
	tsa_entry 0x0F8, pal=7
	tsa_entry 0x0F9, pal=6
	tsa_entry 0x0FA, pal=9
	tsa_entry 0x0FB, pal=9
	tsa_entry 0x0FC, pal=8
	tsa_entry 0x0FD, pal=8
	tsa_entry 0x0FE
	tsa_entry 0x0FF
	tsa_entry 0x100
	tsa_entry 0x101
	tsa_entry 0x102, pal=1
	tsa_entry 0x103, pal=7
	tsa_entry 0x104, pal=1
	tsa_entry 0x105, pal=1
	tsa_entry 0x106
	tsa_entry 0x107
	tsa_entry 0x108, pal=2
	tsa_entry 0x109, pal=2
	tsa_entry 0x10A, pal=4
	tsa_entry 0x10B, pal=4
	tsa_entry 0x10C, pal=6
	tsa_entry 0x10D, pal=4
	tsa_entry 0x10E, pal=5
	tsa_entry 0x10F, pal=8
	tsa_entry 0x110, pal=7
	tsa_entry 0x111, pal=5
	tsa_entry 0x112, pal=5
	tsa_entry 0x113, pal=5
	tsa_entry 0x114, pal=5
	tsa_entry 0x115, pal=5
	tsa_entry 0x116, pal=7
	tsa_entry 0x117, pal=7
	tsa_entry 0x118, pal=7
	tsa_entry 0x119, pal=7
	tsa_entry 0x11A, pal=8
	tsa_entry 0x11B, pal=8
	tsa_entry 0x11C, pal=8
	tsa_entry 0x11D, pal=8
	tsa_entry 0x000
	tsa_entry 0x11E, pal=1
	tsa_entry 0x11F
	tsa_entry 0x120
	tsa_entry 0x121, pal=1
	tsa_entry 0x122, pal=2
	tsa_entry 0x123, pal=1
	tsa_entry 0x124
	tsa_entry 0x125
	tsa_entry 0x126, pal=2
	tsa_entry 0x127, pal=2
	tsa_entry 0x128, pal=1
	tsa_entry 0x129, pal=5
	tsa_entry 0x12A, pal=9
	tsa_entry 0x12B, pal=8
	tsa_entry 0x12C, pal=4
	tsa_entry 0x12D, pal=4
	tsa_entry 0x12E, pal=5
	tsa_entry 0x12F, pal=5
	tsa_entry 0x130, pal=5
	tsa_entry 0x131, pal=5
	tsa_entry 0x132, pal=5
	tsa_entry 0x133, pal=6
	tsa_entry 0x134, pal=6
	tsa_entry 0x135, pal=2
	tsa_entry 0x136, pal=9
	tsa_entry 0x137, pal=7
	tsa_entry 0x138, pal=7
	tsa_entry 0x139, pal=7
	tsa_entry 0x13A, pal=7
	tsa_entry 0x13B, pal=8
	tsa_entry 0x13C, pal=8
	tsa_entry 0x000
	tsa_entry 0x13D
	tsa_entry 0x13E
	tsa_entry 0x13F
	tsa_entry 0x140, pal=1
	tsa_entry 0x141, pal=2
	tsa_entry 0x142, pal=2
	tsa_entry 0x143, pal=2
	tsa_entry 0x144, pal=9
	tsa_entry 0x145, pal=9
	tsa_entry 0x146, pal=2
	tsa_entry 0x147, pal=3
	tsa_entry 0x148, pal=7
	tsa_entry 0x149, pal=6
	tsa_entry 0x14A, pal=3
	tsa_entry 0x14B, pal=4
	tsa_entry 0x14C, pal=1
	tsa_entry 0x14D, pal=4
	tsa_entry 0x14E, pal=4
	tsa_entry 0x14F, pal=4
	tsa_entry 0x150, pal=4
	tsa_entry 0x151, pal=4
	tsa_entry 0x152, pal=8
	tsa_entry 0x153, pal=9
	tsa_entry 0x154, pal=8
	tsa_entry 0x155, pal=9
	tsa_entry 0x156, pal=7
	tsa_entry 0x157, pal=8
	tsa_entry 0x158, pal=8
	tsa_entry 0x159, pal=8
	tsa_entry 0x15A, pal=4
	tsa_entry 0x15B, pal=6
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x15C
	tsa_entry 0x15D
	tsa_entry 0x15E, pal=1
	tsa_entry 0x15F, pal=2
	tsa_entry 0x160, pal=1
	tsa_entry 0x161, pal=1
	tsa_entry 0x162, pal=2
	tsa_entry 0x163, pal=2
	tsa_entry 0x164, pal=2
	tsa_entry 0x165, pal=3
	tsa_entry 0x166, pal=10
	tsa_entry 0x167, pal=4
	tsa_entry 0x168, pal=2
	tsa_entry 0x169, pal=2
	tsa_entry 0x16A, pal=2
	tsa_entry 0x16B, pal=2
	tsa_entry 0x16C, pal=5
	tsa_entry 0x16D, pal=4
	tsa_entry 0x16E, pal=4
	tsa_entry 0x16F, pal=5
	tsa_entry 0x170, pal=6
	tsa_entry 0x171, pal=9
	tsa_entry 0x172, pal=7
	tsa_entry 0x173, pal=7
	tsa_entry 0x174, pal=9
	tsa_entry 0x175, pal=8
	tsa_entry 0x176, pal=7
	tsa_entry 0x177, pal=8
	tsa_entry 0x178, pal=8
	tsa_entry 0x179, pal=8
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x17A
	tsa_entry 0x17B
	tsa_entry 0x17C, pal=2
	tsa_entry 0x17D, pal=2
	tsa_entry 0x17E, pal=1
	tsa_entry 0x17F, pal=2
	tsa_entry 0x180, pal=2
	tsa_entry 0x181, pal=2
	tsa_entry 0x182, pal=7
	tsa_entry 0x183, pal=10
	tsa_entry 0x184, pal=3
	tsa_entry 0x185, pal=2
	tsa_entry 0x186, pal=2
	tsa_entry 0x187, pal=2
	tsa_entry 0x188, pal=2
	tsa_entry 0x189, pal=4
	tsa_entry 0x18A, pal=5
	tsa_entry 0x18B, pal=5
	tsa_entry 0x18C, pal=4
	tsa_entry 0x18D, pal=6
	tsa_entry 0x18E, pal=6
	tsa_entry 0x18F, pal=9
	tsa_entry 0x190, pal=7
	tsa_entry 0x191, pal=7
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x192, pal=8
	tsa_entry 0x193, pal=8
	tsa_entry 0x194, pal=10
	tsa_entry 0x195, pal=10
	tsa_entry 0x000
	tsa_entry 0x196
	tsa_entry 0x197
	tsa_entry 0x198
	tsa_entry 0x199, pal=1
	tsa_entry 0x19A, pal=8
	tsa_entry 0x19B, pal=8
	tsa_entry 0x19C, pal=4
	tsa_entry 0x19D, pal=4
	tsa_entry 0x19E, pal=2
	tsa_entry 0x19F, pal=7
	tsa_entry 0x1A0, pal=3
	tsa_entry 0x1A1, pal=4
	tsa_entry 0x1A2, pal=2
	tsa_entry 0x1A3, pal=2
	tsa_entry 0x1A4, pal=4
	tsa_entry 0x1A5, pal=4
	tsa_entry 0x1A6, pal=4
	tsa_entry 0x1A7, pal=4
	tsa_entry 0x1A8, pal=4
	tsa_entry 0x1A9, pal=5
	tsa_entry 0x1AA, pal=6
	tsa_entry 0x1AB, pal=6
	tsa_entry 0x1AC, pal=8
	tsa_entry 0x1AD, pal=2
	tsa_entry 0x1AE
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x1AF, pal=8
	tsa_entry 0x1B0, pal=8
	tsa_entry 0x1B1, pal=10
