	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x177, pal=2
	tsa_entry 0x001, pal=10
	tsa_entry 0x002, pal=7
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x003, pal=3
	tsa_entry 0x004, pal=10
	tsa_entry 0x005, pal=10
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x006, pal=2
	tsa_entry 0x007, pal=2
	tsa_entry 0x008, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x00A, pal=9
	tsa_entry 0x00B, pal=9
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x00C, pal=5
	tsa_entry 0x00D, pal=2
	tsa_entry 0x00E, pal=3
	tsa_entry 0x00F, pal=3
	tsa_entry 0x010, pal=3
	tsa_entry 0x011
	tsa_entry 0x012, pal=9
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x014, pal=9
	tsa_entry 0x015, pal=2
	tsa_entry 0x016, pal=3
	tsa_entry 0x017, pal=3
	tsa_entry 0x018, pal=3
	tsa_entry 0x019, pal=4
	tsa_entry 0x01A, pal=4
	tsa_entry 0x01B, pal=2
	tsa_entry 0x01C, pal=3
	tsa_entry 0x01D, pal=5
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x01E, pal=5
	tsa_entry 0x01F, pal=5
	tsa_entry 0x020, pal=3
	tsa_entry 0x021, pal=3
	tsa_entry 0x022, pal=3
	tsa_entry 0x023, pal=3
	tsa_entry 0x024, pal=3
	tsa_entry 0x025, pal=3
	tsa_entry 0x026, pal=4
	tsa_entry 0x027, pal=3
	tsa_entry 0x028, pal=2
	tsa_entry 0x029, pal=5
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x02A, pal=1
	tsa_entry 0x02B, pal=2
	tsa_entry 0x02C, pal=2
	tsa_entry 0x02D, pal=9
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x02E, pal=5
	tsa_entry 0x02F, pal=1
	tsa_entry 0x030, pal=3
	tsa_entry 0x031, pal=3
	tsa_entry 0x032, pal=3
	tsa_entry 0x033, pal=3
	tsa_entry 0x034, pal=4
	tsa_entry 0x035, pal=3
	tsa_entry 0x036, pal=5
	tsa_entry 0x037, pal=3
	tsa_entry 0x038, pal=5
	tsa_entry 0x039, pal=9
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x03A, pal=6
	tsa_entry 0x03B, pal=7
	tsa_entry 0x03C, pal=9
	tsa_entry 0x03D, pal=10
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x03E, pal=5
	tsa_entry 0x03F, pal=3
	tsa_entry 0x040, pal=5
	tsa_entry 0x041, pal=1
	tsa_entry 0x042, pal=3
	tsa_entry 0x043, pal=3
	tsa_entry 0x044, pal=4
	tsa_entry 0x045, pal=3
	tsa_entry 0x046, pal=4
	tsa_entry 0x047, pal=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x048
	tsa_entry 0x049, pal=6
	tsa_entry 0x04A, pal=7
	tsa_entry 0x04B, pal=7
	tsa_entry 0x04C, pal=10
	tsa_entry 0x04D
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x04E, pal=1
	tsa_entry 0x04F, pal=5
	tsa_entry 0x050, pal=2
	tsa_entry 0x051, pal=1
	tsa_entry 0x052, pal=2
	tsa_entry 0x053, pal=2
	tsa_entry 0x054, pal=2
	tsa_entry 0x055, pal=2
	tsa_entry 0x056, pal=10
	tsa_entry 0x057, pal=3
	tsa_entry 0x058, pal=4
	tsa_entry 0x059, pal=4
	tsa_entry 0x05A, pal=2
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x05B
	tsa_entry 0x05C, pal=6
	tsa_entry 0x05D, pal=7
	tsa_entry 0x05E, pal=7
	tsa_entry 0x05F, pal=7
	tsa_entry 0x060, pal=10
	tsa_entry 0x061, pal=8
	tsa_entry 0x062, pal=9
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x063, pal=5
	tsa_entry 0x064, pal=2
	tsa_entry 0x065, pal=1
	tsa_entry 0x066, pal=2
	tsa_entry 0x067, pal=2
	tsa_entry 0x068, pal=3
	tsa_entry 0x069, pal=3
	tsa_entry 0x06A, pal=2
	tsa_entry 0x06B, pal=3
	tsa_entry 0x06C, pal=1
	tsa_entry 0x06D, pal=1
	tsa_entry 0x06E, pal=2
	tsa_entry 0x000
	tsa_entry 0x06F, pal=6
	tsa_entry 0x070, pal=6
	tsa_entry 0x071, pal=6
	tsa_entry 0x072, pal=7
	tsa_entry 0x073, pal=7
	tsa_entry 0x074, pal=7
	tsa_entry 0x075, pal=7
	tsa_entry 0x076, pal=9
	tsa_entry 0x077, pal=9
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x078, pal=5
	tsa_entry 0x079, pal=2
	tsa_entry 0x07A, pal=2
	tsa_entry 0x07B, pal=2
	tsa_entry 0x07C, pal=2
	tsa_entry 0x07D, pal=2
	tsa_entry 0x07E, pal=2
	tsa_entry 0x07F, pal=2
	tsa_entry 0x080, pal=4
	tsa_entry 0x081, pal=1
	tsa_entry 0x082, pal=2
	tsa_entry 0x083, pal=5
	tsa_entry 0x084, pal=9
	tsa_entry 0x085, pal=6
	tsa_entry 0x086, pal=6
	tsa_entry 0x087, pal=6
	tsa_entry 0x088, pal=6
	tsa_entry 0x089, pal=8
	tsa_entry 0x08A, pal=7
	tsa_entry 0x08B, pal=10
	tsa_entry 0x08C, pal=10
	tsa_entry 0x08D, pal=9
	tsa_entry 0x08E
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x08F, pal=2
	tsa_entry 0x090, pal=5
	tsa_entry 0x000
	tsa_entry 0x091, pal=9
	tsa_entry 0x092, pal=2
	tsa_entry 0x093, pal=2
	tsa_entry 0x094, pal=3
	tsa_entry 0x095, pal=3
	tsa_entry 0x096, pal=3
	tsa_entry 0x097, pal=5
	tsa_entry 0x098
	tsa_entry 0x099, pal=6
	tsa_entry 0x09A, pal=6
	tsa_entry 0x09B, pal=6
	tsa_entry 0x09C, pal=6
	tsa_entry 0x09D, pal=6
	tsa_entry 0x09E, pal=6
	tsa_entry 0x09F, pal=7
	tsa_entry 0x0A0
	tsa_entry 0x0A1, pal=7
	tsa_entry 0x0A2, pal=6
	tsa_entry 0x0A3, pal=8
	tsa_entry 0x0A4, pal=9
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x0A5, pal=1
	tsa_entry 0x0A6, pal=1
	tsa_entry 0x0A7, pal=3
	tsa_entry 0x0A8, pal=2
	tsa_entry 0x0A9, pal=2
	tsa_entry 0x0AA, pal=3
	tsa_entry 0x0AB, pal=2
	tsa_entry 0x0AC, pal=1
	tsa_entry 0x0AD, pal=4
	tsa_entry 0x0AE, pal=4
	tsa_entry 0x0AF, pal=4
	tsa_entry 0x0B0, pal=5
	tsa_entry 0x0B1, pal=5
	tsa_entry 0x0B2, pal=6
	tsa_entry 0x0B3, pal=9
	tsa_entry 0x0B4, pal=10
	tsa_entry 0x0B5, pal=6
	tsa_entry 0x0B6, pal=7
	tsa_entry 0x0B7, pal=9
	tsa_entry 0x0B8, pal=8
	tsa_entry 0x0B9, pal=10
	tsa_entry 0x0BA, pal=9
	tsa_entry 0x0BB, pal=9
	tsa_entry 0x0BC
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x0BD, pal=5
	tsa_entry 0x0BE, pal=10
	tsa_entry 0x0BF, pal=10
	tsa_entry 0x0C0, pal=2
	tsa_entry 0x0C1, pal=3
	tsa_entry 0x0C2, pal=1
	tsa_entry 0x0C3, pal=2
	tsa_entry 0x0C4, pal=4
	tsa_entry 0x0C5, pal=4
	tsa_entry 0x0C6, pal=4
	tsa_entry 0x0C7, pal=5
	tsa_entry 0x0C8, pal=10
	tsa_entry 0x0C9, pal=6
	tsa_entry 0x0CA, pal=10
	tsa_entry 0x0CB, pal=6
	tsa_entry 0x0CC, pal=7
	tsa_entry 0x0CD, pal=7
	tsa_entry 0x0CE, pal=7
	tsa_entry 0x0CF, pal=7
	tsa_entry 0x0D0, pal=8
	tsa_entry 0x0D1, pal=9
	tsa_entry 0x0D2, pal=9
	tsa_entry 0x0D3, pal=9
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x0D4, pal=2
	tsa_entry 0x0D5, pal=3
	tsa_entry 0x0D6, pal=2
	tsa_entry 0x0D7, pal=1
	tsa_entry 0x0D8, pal=1
	tsa_entry 0x0D9, pal=5
	tsa_entry 0x0DA, pal=2
	tsa_entry 0x0DB, pal=4
	tsa_entry 0x0DC, pal=4
	tsa_entry 0x0DD, pal=4
	tsa_entry 0x0DE, pal=4
	tsa_entry 0x0DF, pal=5
	tsa_entry 0x0E0, pal=6
	tsa_entry 0x0E1, pal=6
	tsa_entry 0x0E2, pal=6
	tsa_entry 0x0E3, pal=6
	tsa_entry 0x0E4, pal=6
	tsa_entry 0x0E5, pal=7
	tsa_entry 0x0E6, pal=9
	tsa_entry 0x0E7, pal=8
	tsa_entry 0x0E8, pal=8
	tsa_entry 0x0E9, pal=9
	tsa_entry 0x0EA, pal=9
	tsa_entry 0x0EB, pal=9
	tsa_entry 0x0EC, pal=9
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x0ED, pal=1
	tsa_entry 0x0EE, pal=2
	tsa_entry 0x0EF, pal=1
	tsa_entry 0x0F0, pal=1
	tsa_entry 0x0F1, pal=2
	tsa_entry 0x0F2, pal=1
	tsa_entry 0x0F3, pal=3
	tsa_entry 0x0F4, pal=5
	tsa_entry 0x0F5, pal=4
	tsa_entry 0x0F6, pal=4
	tsa_entry 0x0F7, pal=4
	tsa_entry 0x0F8, pal=4
	tsa_entry 0x0F9, pal=5
	tsa_entry 0x0FA, pal=6
	tsa_entry 0x0FB, pal=6
	tsa_entry 0x0FC, pal=6
	tsa_entry 0x0FD, pal=7
	tsa_entry 0x0FE, pal=7
	tsa_entry 0x0FF, pal=9
	tsa_entry 0x100, pal=9
	tsa_entry 0x101, pal=8
	tsa_entry 0x102, pal=8
	tsa_entry 0x103, pal=9
	tsa_entry 0x104, pal=9
	tsa_entry 0x105, pal=9
	tsa_entry 0x106, pal=10
	tsa_entry 0x107, pal=10
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x08E, hflip=1
	tsa_entry 0x108
	tsa_entry 0x109, pal=1
	tsa_entry 0x10A, pal=2
	tsa_entry 0x10B, pal=2
	tsa_entry 0x10C
	tsa_entry 0x10D, pal=2
	tsa_entry 0x10E, pal=1
	tsa_entry 0x10F, pal=3
	tsa_entry 0x110, pal=3
	tsa_entry 0x111, pal=5
	tsa_entry 0x112, pal=4
	tsa_entry 0x113, pal=4
	tsa_entry 0x114, pal=4
	tsa_entry 0x115, pal=3
	tsa_entry 0x116, pal=5
	tsa_entry 0x117, pal=6
	tsa_entry 0x118, pal=6
	tsa_entry 0x119, pal=6
	tsa_entry 0x11A, pal=7
	tsa_entry 0x11B, pal=9
	tsa_entry 0x11C, pal=6
	tsa_entry 0x11D, pal=8
	tsa_entry 0x11E, pal=8
	tsa_entry 0x11F, pal=8
	tsa_entry 0x120, pal=9
	tsa_entry 0x121, pal=9
	tsa_entry 0x122, pal=10
	tsa_entry 0x123, pal=10
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x124
	tsa_entry 0x125
	tsa_entry 0x126, pal=2
	tsa_entry 0x127, pal=2
	tsa_entry 0x128, pal=10
	tsa_entry 0x129
	tsa_entry 0x12A, pal=4
	tsa_entry 0x12B, pal=2
	tsa_entry 0x12C, pal=2
	tsa_entry 0x12D, pal=1
	tsa_entry 0x12E, pal=4
	tsa_entry 0x12F, pal=4
	tsa_entry 0x130, pal=4
	tsa_entry 0x131, pal=4
	tsa_entry 0x132, pal=3
	tsa_entry 0x133, pal=3
	tsa_entry 0x134, pal=6
	tsa_entry 0x135, pal=10
	tsa_entry 0x136, pal=6
	tsa_entry 0x137, pal=7
	tsa_entry 0x138, pal=7
	tsa_entry 0x139, pal=7
	tsa_entry 0x13A, pal=7
	tsa_entry 0x13B, pal=8
	tsa_entry 0x13C, pal=8
	tsa_entry 0x13D, pal=9
	tsa_entry 0x13E, pal=9
	tsa_entry 0x13F, pal=9
	tsa_entry 0x140, pal=10
	tsa_entry 0x141, pal=9
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x142
	tsa_entry 0x143
	tsa_entry 0x144, pal=2
	tsa_entry 0x145, pal=10
	tsa_entry 0x146
	tsa_entry 0x147, pal=4
	tsa_entry 0x148, pal=10
	tsa_entry 0x149, pal=2
	tsa_entry 0x178, pal=1
	tsa_entry 0x14A, pal=10
	tsa_entry 0x14B, pal=4
	tsa_entry 0x14C, pal=4
	tsa_entry 0x14D, pal=4
	tsa_entry 0x14E, pal=3
	tsa_entry 0x14F, pal=3
	tsa_entry 0x150, pal=6
	tsa_entry 0x151, pal=6
	tsa_entry 0x152, pal=6
	tsa_entry 0x153, pal=5
	tsa_entry 0x154, pal=7
	tsa_entry 0x155, pal=7
	tsa_entry 0x156, pal=8
	tsa_entry 0x170, pal=8, hflip=1
	tsa_entry 0x157, pal=8
	tsa_entry 0x158, pal=9
	tsa_entry 0x159, pal=9
	tsa_entry 0x15A, pal=9
	tsa_entry 0x15B, pal=10
	tsa_entry 0x15C, pal=10
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x15D, pal=6
	tsa_entry 0x15E, pal=2
	tsa_entry 0x15F, pal=10
	tsa_entry 0x160, pal=10
	tsa_entry 0x161, pal=10
	tsa_entry 0x162, pal=3
	tsa_entry 0x163, pal=1
	tsa_entry 0x164, pal=10
	tsa_entry 0x165, pal=10
	tsa_entry 0x166, pal=4
	tsa_entry 0x167, pal=3
	tsa_entry 0x168, pal=3
	tsa_entry 0x169, pal=6
	tsa_entry 0x16A, pal=6
	tsa_entry 0x16B, pal=6
	tsa_entry 0x000
	tsa_entry 0x16C, pal=7
	tsa_entry 0x16D, pal=7
	tsa_entry 0x16E, pal=8
	tsa_entry 0x16F, pal=8
	tsa_entry 0x170, pal=8
	tsa_entry 0x171, pal=9
	tsa_entry 0x172, pal=9
	tsa_entry 0x173, pal=9
	tsa_entry 0x174, pal=10
	tsa_entry 0x175, pal=10
	tsa_entry 0x176, pal=8
	tsa_entry 0x000
