	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x0BE
	tsa_entry 0x001
	tsa_entry 0x002
	tsa_entry 0x003, pal=1
	tsa_entry 0x004, pal=1
	tsa_entry 0x004, pal=1, hflip=1
	tsa_entry 0x003, pal=1, hflip=1
	tsa_entry 0x002, hflip=1
	tsa_entry 0x001, hflip=1
	tsa_entry 0x0BE, hflip=1
	tsa_entry 0x3FF, hflip=1
	tsa_entry 0x3FF, hflip=1
	tsa_entry 0x3FF, hflip=1
	tsa_entry 0x3FF, hflip=1
	tsa_entry 0x3FF, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x015
	tsa_entry 0x016, pal=1
	tsa_entry 0x017, pal=1
	tsa_entry 0x018, pal=1
	tsa_entry 0x019, pal=1
	tsa_entry 0x01A, pal=1
	tsa_entry 0x01A, pal=1, hflip=1
	tsa_entry 0x019, pal=1, hflip=1
	tsa_entry 0x018, pal=1, hflip=1
	tsa_entry 0x017, pal=1, hflip=1
	tsa_entry 0x016, pal=1, hflip=1
	tsa_entry 0x015, hflip=1
	tsa_entry 0x3FF, hflip=1
	tsa_entry 0x3FF, hflip=1
	tsa_entry 0x3FF, hflip=1
	tsa_entry 0x3FF, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x029
	tsa_entry 0x02A
	tsa_entry 0x02B, pal=1
	tsa_entry 0x02C, pal=1
	tsa_entry 0x02D, pal=1
	tsa_entry 0x02E, pal=3
	tsa_entry 0x02F, pal=3
	tsa_entry 0x030, pal=3
	tsa_entry 0x030, pal=3, hflip=1
	tsa_entry 0x02F, pal=3, hflip=1
	tsa_entry 0x02E, pal=3, hflip=1
	tsa_entry 0x02D, pal=1, hflip=1
	tsa_entry 0x02C, pal=1, hflip=1
	tsa_entry 0x02B, pal=1, hflip=1
	tsa_entry 0x02A, hflip=1
	tsa_entry 0x029, hflip=1
	tsa_entry 0x3FF, hflip=1
	tsa_entry 0x3FF, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x040
	tsa_entry 0x041, pal=1
	tsa_entry 0x042, pal=1
	tsa_entry 0x043, pal=1
	tsa_entry 0x044, pal=3
	tsa_entry 0x045
	tsa_entry 0x046
	tsa_entry 0x047
	tsa_entry 0x047, hflip=1
	tsa_entry 0x046, hflip=1
	tsa_entry 0x045, hflip=1
	tsa_entry 0x044, pal=3, hflip=1
	tsa_entry 0x043, pal=1, hflip=1
	tsa_entry 0x042, pal=1, hflip=1
	tsa_entry 0x041, pal=1, hflip=1
	tsa_entry 0x040, hflip=1
	tsa_entry 0x3FF, hflip=1
	tsa_entry 0x3FF, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x057
	tsa_entry 0x058, pal=1
	tsa_entry 0x059, pal=1
	tsa_entry 0x05A, pal=3
	tsa_entry 0x014
	tsa_entry 0x05B
	tsa_entry 0x05C
	tsa_entry 0x05D
	tsa_entry 0x05E
	tsa_entry 0x05E, hflip=1
	tsa_entry 0x05D, hflip=1
	tsa_entry 0x05C, hflip=1
	tsa_entry 0x05B, hflip=1
	tsa_entry 0x014, hflip=1
	tsa_entry 0x05A, pal=3, hflip=1
	tsa_entry 0x059, pal=1, hflip=1
	tsa_entry 0x058, pal=1, hflip=1
	tsa_entry 0x057, hflip=1
	tsa_entry 0x3FF, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x06D, pal=1
	tsa_entry 0x06E, pal=1
	tsa_entry 0x06F, pal=1
	tsa_entry 0x070, pal=1
	tsa_entry 0x071
	tsa_entry 0x072
	tsa_entry 0x073
	tsa_entry 0x074
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x074, hflip=1
	tsa_entry 0x073, hflip=1
	tsa_entry 0x072, hflip=1
	tsa_entry 0x071, hflip=1
	tsa_entry 0x070, pal=1, hflip=1
	tsa_entry 0x06F, pal=1, hflip=1
	tsa_entry 0x06E, pal=1, hflip=1
	tsa_entry 0x06D, pal=1, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x081, pal=1
	tsa_entry 0x082, pal=1
	tsa_entry 0x083, pal=1
	tsa_entry 0x084, pal=3
	tsa_entry 0x085
	tsa_entry 0x086
	tsa_entry 0x087
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x087, hflip=1
	tsa_entry 0x086, hflip=1
	tsa_entry 0x085, hflip=1
	tsa_entry 0x084, pal=3, hflip=1
	tsa_entry 0x083, pal=1, hflip=1
	tsa_entry 0x082, pal=1, hflip=1
	tsa_entry 0x081, pal=1, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x092, pal=1
	tsa_entry 0x093, pal=1
	tsa_entry 0x094, pal=1
	tsa_entry 0x095
	tsa_entry 0x096
	tsa_entry 0x097
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x097, hflip=1
	tsa_entry 0x096, hflip=1
	tsa_entry 0x095, hflip=1
	tsa_entry 0x094, pal=1, hflip=1
	tsa_entry 0x093, pal=1, hflip=1
	tsa_entry 0x092, pal=1, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x0A2, pal=1
	tsa_entry 0x0A3, pal=1
	tsa_entry 0x0A4, pal=3
	tsa_entry 0x0A5
	tsa_entry 0x0A6
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x0A6, hflip=1
	tsa_entry 0x0A5, hflip=1
	tsa_entry 0x0A4, pal=3, hflip=1
	tsa_entry 0x0A3, pal=1, hflip=1
	tsa_entry 0x0A2, pal=1, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x028, pal=1
	tsa_entry 0x0B0, pal=1
	tsa_entry 0x0B1, pal=3
	tsa_entry 0x0B2
	tsa_entry 0x0B3
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x0B3, hflip=1
	tsa_entry 0x0B2, hflip=1
	tsa_entry 0x0B1, pal=3, hflip=1
	tsa_entry 0x0B0, pal=1, hflip=1
	tsa_entry 0x028, pal=1, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x028, pal=1, vflip=1
	tsa_entry 0x0B0, pal=1, vflip=1
	tsa_entry 0x0B1, pal=3, vflip=1
	tsa_entry 0x0B2, vflip=1
	tsa_entry 0x0B3, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x0B3, hflip=1, vflip=1
	tsa_entry 0x0B2, hflip=1, vflip=1
	tsa_entry 0x0B1, pal=3, hflip=1, vflip=1
	tsa_entry 0x0B0, pal=1, hflip=1, vflip=1
	tsa_entry 0x028, pal=1, hflip=1, vflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x0A2, pal=1, vflip=1
	tsa_entry 0x0A3, pal=1, vflip=1
	tsa_entry 0x0A4, pal=3, vflip=1
	tsa_entry 0x0A5, vflip=1
	tsa_entry 0x0A6, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x0A6, hflip=1, vflip=1
	tsa_entry 0x0A5, hflip=1, vflip=1
	tsa_entry 0x0A4, pal=3, hflip=1, vflip=1
	tsa_entry 0x0A3, pal=1, hflip=1, vflip=1
	tsa_entry 0x0A2, pal=1, hflip=1, vflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x092, pal=1, vflip=1
	tsa_entry 0x093, pal=1, vflip=1
	tsa_entry 0x094, pal=1, vflip=1
	tsa_entry 0x095, vflip=1
	tsa_entry 0x096, vflip=1
	tsa_entry 0x097, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x097, hflip=1, vflip=1
	tsa_entry 0x096, hflip=1, vflip=1
	tsa_entry 0x095, hflip=1, vflip=1
	tsa_entry 0x094, pal=1, hflip=1, vflip=1
	tsa_entry 0x093, pal=1, hflip=1, vflip=1
	tsa_entry 0x092, pal=1, hflip=1, vflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x081, pal=1, vflip=1
	tsa_entry 0x082, pal=1, vflip=1
	tsa_entry 0x083, pal=1, vflip=1
	tsa_entry 0x084, pal=3, vflip=1
	tsa_entry 0x085, vflip=1
	tsa_entry 0x086, vflip=1
	tsa_entry 0x087, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x087, hflip=1, vflip=1
	tsa_entry 0x086, hflip=1, vflip=1
	tsa_entry 0x085, hflip=1, vflip=1
	tsa_entry 0x084, pal=3, hflip=1, vflip=1
	tsa_entry 0x083, pal=1, hflip=1, vflip=1
	tsa_entry 0x082, pal=1, hflip=1, vflip=1
	tsa_entry 0x081, pal=1, hflip=1, vflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x06D, pal=1, vflip=1
	tsa_entry 0x06E, pal=1, vflip=1
	tsa_entry 0x06F, pal=1, vflip=1
	tsa_entry 0x070, pal=1, vflip=1
	tsa_entry 0x071, vflip=1
	tsa_entry 0x072, vflip=1
	tsa_entry 0x073, vflip=1
	tsa_entry 0x074, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x074, hflip=1, vflip=1
	tsa_entry 0x073, hflip=1, vflip=1
	tsa_entry 0x072, hflip=1, vflip=1
	tsa_entry 0x071, hflip=1, vflip=1
	tsa_entry 0x070, pal=1, hflip=1, vflip=1
	tsa_entry 0x06F, pal=1, hflip=1, vflip=1
	tsa_entry 0x06E, pal=1, hflip=1, vflip=1
	tsa_entry 0x06D, pal=1, hflip=1, vflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF, vflip=1
	tsa_entry 0x057, vflip=1
	tsa_entry 0x058, pal=1, vflip=1
	tsa_entry 0x059, pal=1, vflip=1
	tsa_entry 0x05A, pal=3, vflip=1
	tsa_entry 0x014, vflip=1
	tsa_entry 0x05B, vflip=1
	tsa_entry 0x05C, vflip=1
	tsa_entry 0x05D, vflip=1
	tsa_entry 0x05E, vflip=1
	tsa_entry 0x05E, hflip=1, vflip=1
	tsa_entry 0x05D, hflip=1, vflip=1
	tsa_entry 0x05C, hflip=1, vflip=1
	tsa_entry 0x05B, hflip=1, vflip=1
	tsa_entry 0x014, hflip=1, vflip=1
	tsa_entry 0x05A, pal=3, hflip=1, vflip=1
	tsa_entry 0x059, pal=1, hflip=1, vflip=1
	tsa_entry 0x058, pal=1, hflip=1, vflip=1
	tsa_entry 0x057, hflip=1, vflip=1
	tsa_entry 0x3FF, hflip=1, vflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF, vflip=1
	tsa_entry 0x3FF, vflip=1
	tsa_entry 0x040, vflip=1
	tsa_entry 0x041, pal=1, vflip=1
	tsa_entry 0x042, pal=1, vflip=1
	tsa_entry 0x043, pal=1, vflip=1
	tsa_entry 0x044, pal=3, vflip=1
	tsa_entry 0x045, vflip=1
	tsa_entry 0x046, vflip=1
	tsa_entry 0x047, vflip=1
	tsa_entry 0x047, hflip=1, vflip=1
	tsa_entry 0x046, hflip=1, vflip=1
	tsa_entry 0x045, hflip=1, vflip=1
	tsa_entry 0x044, pal=3, hflip=1, vflip=1
	tsa_entry 0x043, pal=1, hflip=1, vflip=1
	tsa_entry 0x042, pal=1, hflip=1, vflip=1
	tsa_entry 0x041, pal=1, hflip=1, vflip=1
	tsa_entry 0x040, hflip=1, vflip=1
	tsa_entry 0x3FF, hflip=1, vflip=1
	tsa_entry 0x3FF, hflip=1, vflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF, vflip=1
	tsa_entry 0x3FF, vflip=1
	tsa_entry 0x029, vflip=1
	tsa_entry 0x02A, vflip=1
	tsa_entry 0x02B, pal=1, vflip=1
	tsa_entry 0x02C, pal=1, vflip=1
	tsa_entry 0x02D, pal=1, vflip=1
	tsa_entry 0x02E, pal=3, vflip=1
	tsa_entry 0x02F, pal=3, vflip=1
	tsa_entry 0x030, pal=3, vflip=1
	tsa_entry 0x030, pal=3, hflip=1, vflip=1
	tsa_entry 0x02F, pal=3, hflip=1, vflip=1
	tsa_entry 0x02E, pal=3, hflip=1, vflip=1
	tsa_entry 0x02D, pal=1, hflip=1, vflip=1
	tsa_entry 0x02C, pal=1, hflip=1, vflip=1
	tsa_entry 0x02B, pal=1, hflip=1, vflip=1
	tsa_entry 0x02A, hflip=1, vflip=1
	tsa_entry 0x029, hflip=1, vflip=1
	tsa_entry 0x3FF, hflip=1, vflip=1
	tsa_entry 0x3FF, hflip=1, vflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF, vflip=1
	tsa_entry 0x3FF, vflip=1
	tsa_entry 0x3FF, vflip=1
	tsa_entry 0x3FF, vflip=1
	tsa_entry 0x015, vflip=1
	tsa_entry 0x016, pal=1, vflip=1
	tsa_entry 0x017, pal=1, vflip=1
	tsa_entry 0x018, pal=1, vflip=1
	tsa_entry 0x019, pal=1, vflip=1
	tsa_entry 0x01A, pal=1, vflip=1
	tsa_entry 0x01A, pal=1, hflip=1, vflip=1
	tsa_entry 0x019, pal=1, hflip=1, vflip=1
	tsa_entry 0x018, pal=1, hflip=1, vflip=1
	tsa_entry 0x017, pal=1, hflip=1, vflip=1
	tsa_entry 0x016, pal=1, hflip=1, vflip=1
	tsa_entry 0x015, hflip=1, vflip=1
	tsa_entry 0x3FF, hflip=1, vflip=1
	tsa_entry 0x3FF, hflip=1, vflip=1
	tsa_entry 0x3FF, hflip=1, vflip=1
	tsa_entry 0x3FF, hflip=1, vflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF, vflip=1
	tsa_entry 0x3FF, vflip=1
	tsa_entry 0x3FF, vflip=1
	tsa_entry 0x3FF, vflip=1
	tsa_entry 0x3FF, vflip=1
	tsa_entry 0x0BE, vflip=1
	tsa_entry 0x001, vflip=1
	tsa_entry 0x002, vflip=1
	tsa_entry 0x003, pal=1, vflip=1
	tsa_entry 0x004, pal=1, vflip=1
	tsa_entry 0x004, pal=1, hflip=1, vflip=1
	tsa_entry 0x003, pal=1, hflip=1, vflip=1
	tsa_entry 0x002, hflip=1, vflip=1
	tsa_entry 0x001, hflip=1, vflip=1
	tsa_entry 0x0BE, hflip=1, vflip=1
	tsa_entry 0x3FF, hflip=1, vflip=1
	tsa_entry 0x3FF, hflip=1, vflip=1
	tsa_entry 0x3FF, hflip=1, vflip=1
	tsa_entry 0x3FF, hflip=1, vflip=1
	tsa_entry 0x3FF, hflip=1, vflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
