	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x173, pal=1
	tsa_entry 0x001, pal=1
	tsa_entry 0x002, pal=8
	tsa_entry 0x003, pal=7
	tsa_entry 0x004, pal=8
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x009, pal=1
	tsa_entry 0x00A, pal=8
	tsa_entry 0x00B, pal=8
	tsa_entry 0x00C, pal=8
	tsa_entry 0x00D, pal=8
	tsa_entry 0x00E, pal=8
	tsa_entry 0x00F, pal=8
	tsa_entry 0x010, pal=8
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x015, pal=4
	tsa_entry 0x016, pal=7
	tsa_entry 0x017, pal=6
	tsa_entry 0x018, pal=1
	tsa_entry 0x019, pal=8
	tsa_entry 0x01A, pal=8
	tsa_entry 0x01B, pal=8
	tsa_entry 0x01C, pal=8
	tsa_entry 0x01D, pal=7
	tsa_entry 0x01E, pal=8
	tsa_entry 0x01F, pal=8
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x025, pal=1
	tsa_entry 0x026, pal=8
	tsa_entry 0x027, pal=8
	tsa_entry 0x028, pal=6
	tsa_entry 0x029, pal=6
	tsa_entry 0x02A, pal=8
	tsa_entry 0x02B, pal=7
	tsa_entry 0x02C, pal=8
	tsa_entry 0x02D, pal=8
	tsa_entry 0x02E, pal=8
	tsa_entry 0x02F, pal=8
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x034, pal=4
	tsa_entry 0x035, pal=8
	tsa_entry 0x036
	tsa_entry 0x037, pal=2
	tsa_entry 0x038, pal=6
	tsa_entry 0x039, pal=6
	tsa_entry 0x03A, pal=8
	tsa_entry 0x03B, pal=1
	tsa_entry 0x03C, pal=7
	tsa_entry 0x03D, pal=8
	tsa_entry 0x03E, pal=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x042, pal=8
	tsa_entry 0x043, pal=8
	tsa_entry 0x044
	tsa_entry 0x045, pal=6
	tsa_entry 0x046, pal=6
	tsa_entry 0x047, pal=7
	tsa_entry 0x048, pal=8
	tsa_entry 0x049, pal=6
	tsa_entry 0x04A, pal=8
	tsa_entry 0x04B, pal=8
	tsa_entry 0x04C, pal=8
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x051, pal=10
	tsa_entry 0x052, pal=1
	tsa_entry 0x053, pal=6
	tsa_entry 0x054, pal=6
	tsa_entry 0x055, pal=6
	tsa_entry 0x056, pal=2
	tsa_entry 0x057, pal=6
	tsa_entry 0x058, pal=8
	tsa_entry 0x059, pal=8
	tsa_entry 0x05A, pal=1
	tsa_entry 0x05B, pal=8
	tsa_entry 0x005
	tsa_entry 0x006
	tsa_entry 0x007
	tsa_entry 0x008, pal=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x061, pal=1
	tsa_entry 0x062, pal=1
	tsa_entry 0x063
	tsa_entry 0x064
	tsa_entry 0x065, pal=6
	tsa_entry 0x066, pal=7
	tsa_entry 0x067
	tsa_entry 0x068, pal=1
	tsa_entry 0x069, pal=8
	tsa_entry 0x06A, pal=8
	tsa_entry 0x06B, pal=1
	tsa_entry 0x011
	tsa_entry 0x012
	tsa_entry 0x013
	tsa_entry 0x014
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x070, pal=1
	tsa_entry 0x071, pal=1
	tsa_entry 0x072, pal=1
	tsa_entry 0x073, pal=1
	tsa_entry 0x074, pal=6
	tsa_entry 0x075, pal=6
	tsa_entry 0x076, pal=7
	tsa_entry 0x077, pal=1
	tsa_entry 0x078, pal=1
	tsa_entry 0x079, pal=8
	tsa_entry 0x07A, pal=10
	tsa_entry 0x020
	tsa_entry 0x021
	tsa_entry 0x022
	tsa_entry 0x023, pal=1
	tsa_entry 0x024, pal=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x07D, pal=4
	tsa_entry 0x07E, pal=1
	tsa_entry 0x07F, pal=1
	tsa_entry 0x080, pal=7
	tsa_entry 0x081, pal=2
	tsa_entry 0x082, pal=6
	tsa_entry 0x083, pal=6
	tsa_entry 0x084, pal=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x030, pal=1
	tsa_entry 0x031, pal=1
	tsa_entry 0x032, pal=1
	tsa_entry 0x033, pal=1
	tsa_entry 0x005, pal=10, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x087, pal=1
	tsa_entry 0x088, pal=2
	tsa_entry 0x089, pal=6
	tsa_entry 0x08A, pal=1
	tsa_entry 0x08B, pal=6
	tsa_entry 0x08C, pal=6
	tsa_entry 0x08D, pal=6
	tsa_entry 0x08E, pal=7
	tsa_entry 0x08F, pal=6
	tsa_entry 0x090, pal=6
	tsa_entry 0x091, pal=4
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x03F, pal=1
	tsa_entry 0x040, pal=1
	tsa_entry 0x041, pal=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x092, pal=4
	tsa_entry 0x093, pal=10
	tsa_entry 0x094, pal=5
	tsa_entry 0x095, pal=6
	tsa_entry 0x096, pal=6
	tsa_entry 0x097, pal=6
	tsa_entry 0x098, pal=8
	tsa_entry 0x099, pal=8
	tsa_entry 0x09A, pal=1
	tsa_entry 0x09B, pal=5
	tsa_entry 0x09C, pal=8
	tsa_entry 0x09D, pal=5
	tsa_entry 0x09E, pal=5
	tsa_entry 0x09F, pal=5
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x04E, pal=1
	tsa_entry 0x04F, pal=1
	tsa_entry 0x050, pal=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x0A1, pal=1
	tsa_entry 0x0A2, pal=4
	tsa_entry 0x0A3, pal=5
	tsa_entry 0x0A4, pal=2
	tsa_entry 0x0A5, pal=5
	tsa_entry 0x0A6, pal=9
	tsa_entry 0x0A7, pal=2
	tsa_entry 0x0A8, pal=3
	tsa_entry 0x0A9, pal=3
	tsa_entry 0x0AA, pal=7
	tsa_entry 0x0AB, pal=7
	tsa_entry 0x0AC, pal=10
	tsa_entry 0x0AD, pal=8
	tsa_entry 0x0AE, pal=8
	tsa_entry 0x0AF, pal=8
	tsa_entry 0x0B0, pal=2
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x05E, pal=1
	tsa_entry 0x05F, pal=1
	tsa_entry 0x060, pal=2
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x0B5, pal=4
	tsa_entry 0x0B6, pal=4
	tsa_entry 0x0B7, pal=1
	tsa_entry 0x0B8, pal=5
	tsa_entry 0x0B9, pal=5
	tsa_entry 0x0BA, pal=7
	tsa_entry 0x0BB, pal=2
	tsa_entry 0x0BC, pal=2
	tsa_entry 0x0BD, pal=3
	tsa_entry 0x0BE, pal=2
	tsa_entry 0x0BF, pal=7
	tsa_entry 0x0C0, pal=7
	tsa_entry 0x0C1, pal=5
	tsa_entry 0x0C2, pal=5
	tsa_entry 0x0C3, pal=8
	tsa_entry 0x0C4, pal=6
	tsa_entry 0x0C5, pal=2
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x06E, pal=1
	tsa_entry 0x06F, pal=2
	tsa_entry 0x0CA, pal=2
	tsa_entry 0x0CB, pal=4
	tsa_entry 0x015, pal=4, hflip=1
	tsa_entry 0x0CC, pal=4
	tsa_entry 0x0CD, pal=4
	tsa_entry 0x0CE, pal=4
	tsa_entry 0x0CF, pal=1
	tsa_entry 0x0D0, pal=2
	tsa_entry 0x0D1, pal=1
	tsa_entry 0x0D2, pal=3
	tsa_entry 0x0D3
	tsa_entry 0x0D4, pal=5
	tsa_entry 0x0D5, pal=5
	tsa_entry 0x0D6, pal=6
	tsa_entry 0x0D7, pal=6
	tsa_entry 0x0D8, pal=1
	tsa_entry 0x0D9, pal=6
	tsa_entry 0x0DA, pal=7
	tsa_entry 0x0DB, pal=5
	tsa_entry 0x0DC, pal=7
	tsa_entry 0x0DD, pal=5
	tsa_entry 0x0DE, pal=7
	tsa_entry 0x0DF, pal=6
	tsa_entry 0x0E0, pal=7
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x07C, pal=2
	tsa_entry 0x0E5, pal=2
	tsa_entry 0x0E6, pal=2
	tsa_entry 0x0E7, pal=2
	tsa_entry 0x0E8, pal=2
	tsa_entry 0x0E9, pal=3
	tsa_entry 0x0EA, pal=2
	tsa_entry 0x0EB, pal=2
	tsa_entry 0x0EC, pal=2
	tsa_entry 0x0ED, pal=4
	tsa_entry 0x0EE, pal=4
	tsa_entry 0x0EF, pal=10
	tsa_entry 0x0F0, pal=1
	tsa_entry 0x0F1, pal=8
	tsa_entry 0x0F2, pal=5
	tsa_entry 0x0F3, pal=6
	tsa_entry 0x0F4, pal=1
	tsa_entry 0x0F5, pal=3
	tsa_entry 0x0F6, pal=7
	tsa_entry 0x0F7, pal=7
	tsa_entry 0x0F8, pal=7
	tsa_entry 0x0F9, pal=7
	tsa_entry 0x0FA, pal=10
	tsa_entry 0x0FB, pal=4
	tsa_entry 0x0FC, pal=6
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x085, pal=2
	tsa_entry 0x086, pal=2
	tsa_entry 0x102, pal=2
	tsa_entry 0x103, pal=2
	tsa_entry 0x104, pal=3
	tsa_entry 0x105, pal=3
	tsa_entry 0x106, pal=3
	tsa_entry 0x107, pal=3
	tsa_entry 0x108, pal=2
	tsa_entry 0x109, pal=4
	tsa_entry 0x10A, pal=4
	tsa_entry 0x10B, pal=10
	tsa_entry 0x10C, pal=5
	tsa_entry 0x10D, pal=5
	tsa_entry 0x10E, pal=5
	tsa_entry 0x10F, pal=5
	tsa_entry 0x110, pal=6
	tsa_entry 0x111, pal=6
	tsa_entry 0x112, pal=6
	tsa_entry 0x113, pal=5
	tsa_entry 0x114, pal=8
	tsa_entry 0x115, pal=5
	tsa_entry 0x116, pal=8
	tsa_entry 0x117, pal=10
	tsa_entry 0x118, pal=10
	tsa_entry 0x119, pal=4
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x121, pal=2
	tsa_entry 0x122, pal=3
	tsa_entry 0x123, pal=3
	tsa_entry 0x124, pal=3
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x125, pal=5
	tsa_entry 0x126, pal=5
	tsa_entry 0x127, pal=5
	tsa_entry 0x128, pal=5
	tsa_entry 0x129, pal=10
	tsa_entry 0x12A, pal=3
	tsa_entry 0x12B, pal=6
	tsa_entry 0x12C, pal=8
	tsa_entry 0x12D, pal=9
	tsa_entry 0x12E, pal=6
	tsa_entry 0x12F, pal=6
	tsa_entry 0x130, pal=3
	tsa_entry 0x131, pal=10
	tsa_entry 0x132, pal=10
	tsa_entry 0x133, pal=7
	tsa_entry 0x134, pal=9
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x13D, pal=3
	tsa_entry 0x13E, pal=2
	tsa_entry 0x13F, pal=4
	tsa_entry 0x140, pal=3
	tsa_entry 0x141, pal=3
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x142, pal=4
	tsa_entry 0x143, pal=4
	tsa_entry 0x144, pal=4
	tsa_entry 0x145, pal=10
	tsa_entry 0x146, pal=10
	tsa_entry 0x147, pal=3
	tsa_entry 0x148, pal=6
	tsa_entry 0x149, pal=2
	tsa_entry 0x14A, pal=8
	tsa_entry 0x14B, pal=6
	tsa_entry 0x14C, pal=7
	tsa_entry 0x14D, pal=3
	tsa_entry 0x14E, pal=10
	tsa_entry 0x14F, pal=10
	tsa_entry 0x150, pal=9
	tsa_entry 0x151, pal=4
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x15A, pal=4
	tsa_entry 0x15B, pal=1
	tsa_entry 0x15C, pal=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x005, pal=3, vflip=1
	tsa_entry 0x15D, pal=4
	tsa_entry 0x15E, pal=10
	tsa_entry 0x15F, pal=10
	tsa_entry 0x160, pal=10
	tsa_entry 0x161, pal=2
	tsa_entry 0x162, pal=6
	tsa_entry 0x163, pal=2
	tsa_entry 0x164, pal=6
	tsa_entry 0x08F, pal=6
	tsa_entry 0x165, pal=8
	tsa_entry 0x166, pal=10
	tsa_entry 0x167, pal=10
	tsa_entry 0x168, pal=9
	tsa_entry 0x169, pal=8
	tsa_entry 0x16A, pal=8
