	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x19D, pal=2
	tsa_entry 0x001, pal=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x002, pal=6
	tsa_entry 0x003, pal=1
	tsa_entry 0x004, pal=1
	tsa_entry 0x005, pal=1
	tsa_entry 0x006, pal=6
	tsa_entry 0x007, pal=6
	tsa_entry 0x008, pal=6
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x009, pal=1
	tsa_entry 0x00A, pal=1
	tsa_entry 0x00B, pal=1
	tsa_entry 0x00C, pal=1
	tsa_entry 0x00D, pal=6
	tsa_entry 0x00E, pal=1
	tsa_entry 0x00F, pal=1
	tsa_entry 0x010, pal=2
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x011, pal=6
	tsa_entry 0x012, pal=1
	tsa_entry 0x013, pal=2
	tsa_entry 0x014, pal=4
	tsa_entry 0x015, pal=4
	tsa_entry 0x016, pal=4
	tsa_entry 0x017, pal=6
	tsa_entry 0x018, pal=1
	tsa_entry 0x019, pal=6
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x01A
	tsa_entry 0x01B, pal=1
	tsa_entry 0x01C, pal=3
	tsa_entry 0x01D, pal=1
	tsa_entry 0x01E, pal=10
	tsa_entry 0x01F, pal=10
	tsa_entry 0x020, pal=10
	tsa_entry 0x021, pal=5
	tsa_entry 0x022, pal=6
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x023, pal=6
	tsa_entry 0x024
	tsa_entry 0x025, pal=2
	tsa_entry 0x026, pal=5
	tsa_entry 0x027, pal=2
	tsa_entry 0x028, pal=5
	tsa_entry 0x029, pal=10
	tsa_entry 0x02A, pal=4
	tsa_entry 0x02B, pal=3
	tsa_entry 0x02C, pal=3
	tsa_entry 0x02D, pal=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x02E
	tsa_entry 0x02F, pal=5
	tsa_entry 0x030, pal=2
	tsa_entry 0x031, pal=2
	tsa_entry 0x032, pal=2
	tsa_entry 0x033, pal=5
	tsa_entry 0x034, pal=2
	tsa_entry 0x035
	tsa_entry 0x036, pal=6
	tsa_entry 0x037, pal=3
	tsa_entry 0x038, pal=10
	tsa_entry 0x039, pal=10
	tsa_entry 0x03A, pal=4
	tsa_entry 0x03B, pal=4
	tsa_entry 0x03C, pal=2
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x03D
	tsa_entry 0x03E, pal=6
	tsa_entry 0x03F, pal=5
	tsa_entry 0x040, pal=2
	tsa_entry 0x041, pal=2
	tsa_entry 0x042, pal=4
	tsa_entry 0x043, pal=4
	tsa_entry 0x044, pal=6
	tsa_entry 0x045, pal=3
	tsa_entry 0x046, pal=10
	tsa_entry 0x047, pal=8
	tsa_entry 0x048, pal=4
	tsa_entry 0x049, pal=4
	tsa_entry 0x04A, pal=10
	tsa_entry 0x04B, pal=4
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x04C
	tsa_entry 0x04D
	tsa_entry 0x04E, pal=9
	tsa_entry 0x04F, pal=5
	tsa_entry 0x050, pal=2
	tsa_entry 0x051, pal=4
	tsa_entry 0x052, pal=2
	tsa_entry 0x053, pal=1
	tsa_entry 0x054, pal=5
	tsa_entry 0x055, pal=5
	tsa_entry 0x056, pal=3
	tsa_entry 0x057, pal=8
	tsa_entry 0x058, pal=4
	tsa_entry 0x059, pal=4
	tsa_entry 0x05A, pal=6
	tsa_entry 0x05B, pal=6
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x05C
	tsa_entry 0x05D, pal=1
	tsa_entry 0x05E
	tsa_entry 0x05F, pal=10
	tsa_entry 0x060, pal=2
	tsa_entry 0x061, pal=4
	tsa_entry 0x062, pal=4
	tsa_entry 0x063, pal=4
	tsa_entry 0x064, pal=4
	tsa_entry 0x065
	tsa_entry 0x066
	tsa_entry 0x067, pal=4
	tsa_entry 0x068, pal=4
	tsa_entry 0x069, pal=4
	tsa_entry 0x06A, pal=9
	tsa_entry 0x06B, pal=8
	tsa_entry 0x06C, pal=8
	tsa_entry 0x06D, pal=1
	tsa_entry 0x06E, pal=2
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x06F
	tsa_entry 0x070, pal=2
	tsa_entry 0x071, pal=1
	tsa_entry 0x072
	tsa_entry 0x073
	tsa_entry 0x074, pal=3
	tsa_entry 0x075, pal=5
	tsa_entry 0x076, pal=5
	tsa_entry 0x077, pal=3
	tsa_entry 0x078
	tsa_entry 0x079, pal=1
	tsa_entry 0x07A, pal=2
	tsa_entry 0x07B, pal=4
	tsa_entry 0x07C, pal=4
	tsa_entry 0x07D, pal=4
	tsa_entry 0x07E, pal=10
	tsa_entry 0x07F, pal=10
	tsa_entry 0x080, pal=9
	tsa_entry 0x081, pal=8
	tsa_entry 0x082, pal=9
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x083, pal=2
	tsa_entry 0x084
	tsa_entry 0x085
	tsa_entry 0x086, pal=2
	tsa_entry 0x087, pal=1
	tsa_entry 0x088, pal=9
	tsa_entry 0x089, pal=9
	tsa_entry 0x08A, pal=1
	tsa_entry 0x08B
	tsa_entry 0x08C
	tsa_entry 0x08D
	tsa_entry 0x08E, pal=1
	tsa_entry 0x08F, pal=2
	tsa_entry 0x090, pal=5
	tsa_entry 0x091, pal=5
	tsa_entry 0x092, pal=6
	tsa_entry 0x093, pal=6
	tsa_entry 0x094, pal=6
	tsa_entry 0x095, pal=6
	tsa_entry 0x096, pal=4
	tsa_entry 0x097, pal=6
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x098, pal=2
	tsa_entry 0x099, pal=7
	tsa_entry 0x09A, pal=3
	tsa_entry 0x09B
	tsa_entry 0x09C
	tsa_entry 0x09D
	tsa_entry 0x09E
	tsa_entry 0x09F
	tsa_entry 0x0A0, pal=9
	tsa_entry 0x0A1, pal=9
	tsa_entry 0x0A2, pal=9
	tsa_entry 0x0A3
	tsa_entry 0x0A4, pal=5
	tsa_entry 0x0A5, pal=4
	tsa_entry 0x0A6, pal=5
	tsa_entry 0x0A7, pal=9
	tsa_entry 0x0A8, pal=4
	tsa_entry 0x0A9, pal=3
	tsa_entry 0x0AA, pal=10
	tsa_entry 0x0AB, pal=4
	tsa_entry 0x0AC, pal=6
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x0AD, pal=5
	tsa_entry 0x0AE, pal=7
	tsa_entry 0x0AF, pal=1
	tsa_entry 0x0B0, pal=1
	tsa_entry 0x0B1, pal=1
	tsa_entry 0x0B2, pal=7
	tsa_entry 0x0B3, pal=7
	tsa_entry 0x0B4
	tsa_entry 0x0B5, pal=9
	tsa_entry 0x0B6, pal=1
	tsa_entry 0x0B7
	tsa_entry 0x0B8
	tsa_entry 0x0B9, pal=7
	tsa_entry 0x0BA, pal=4
	tsa_entry 0x0BB, pal=5
	tsa_entry 0x0BC, pal=4
	tsa_entry 0x0BD, pal=2
	tsa_entry 0x0BE, pal=5
	tsa_entry 0x0BF, pal=5
	tsa_entry 0x0C0, pal=6
	tsa_entry 0x0C1, pal=6
	tsa_entry 0x0C2, pal=6
	tsa_entry 0x0C3, pal=3
	tsa_entry 0x0C4, pal=2
	tsa_entry 0x0C5
	tsa_entry 0x0C6, pal=7
	tsa_entry 0x0C7, pal=10
	tsa_entry 0x0C8, pal=10
	tsa_entry 0x0C9, pal=4
	tsa_entry 0x0CA, pal=3
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x0CB, pal=5
	tsa_entry 0x0CC
	tsa_entry 0x0CD, pal=1
	tsa_entry 0x0CE, pal=1
	tsa_entry 0x0CF, pal=1
	tsa_entry 0x0D0
	tsa_entry 0x0D1
	tsa_entry 0x0D2, pal=5
	tsa_entry 0x0D3, pal=3
	tsa_entry 0x0D4
	tsa_entry 0x0D5
	tsa_entry 0x0D6, pal=5
	tsa_entry 0x0D7, pal=10
	tsa_entry 0x0D8, pal=3
	tsa_entry 0x0D9, pal=2
	tsa_entry 0x0DA, pal=2
	tsa_entry 0x0DB, pal=4
	tsa_entry 0x0DC, pal=5
	tsa_entry 0x0DD, pal=5
	tsa_entry 0x0DE, pal=6
	tsa_entry 0x0DF, pal=7
	tsa_entry 0x0E0, pal=7
	tsa_entry 0x0E1, pal=6
	tsa_entry 0x0E2, pal=7
	tsa_entry 0x0E3, pal=7
	tsa_entry 0x0E4, pal=8
	tsa_entry 0x0E5, pal=8
	tsa_entry 0x0E6, pal=2
	tsa_entry 0x0E7, pal=8
	tsa_entry 0x0E8, pal=8
	tsa_entry 0x0E9, pal=10
	tsa_entry 0x000
	tsa_entry 0x0EA, pal=4
	tsa_entry 0x0EB, pal=1
	tsa_entry 0x0EC
	tsa_entry 0x0ED, pal=1
	tsa_entry 0x0EE, pal=1
	tsa_entry 0x0EF
	tsa_entry 0x0F0, pal=8
	tsa_entry 0x0F1, pal=5
	tsa_entry 0x0F2
	tsa_entry 0x0F3, pal=6
	tsa_entry 0x0F4
	tsa_entry 0x0F5, pal=2
	tsa_entry 0x0F6, pal=2
	tsa_entry 0x0F7, pal=3
	tsa_entry 0x0F8, pal=5
	tsa_entry 0x0F9, pal=4
	tsa_entry 0x0FA, pal=4
	tsa_entry 0x0FB, pal=5
	tsa_entry 0x0FC, pal=5
	tsa_entry 0x0FD, pal=5
	tsa_entry 0x0FE, pal=9
	tsa_entry 0x0FF, pal=6
	tsa_entry 0x100, pal=6
	tsa_entry 0x101, pal=6
	tsa_entry 0x102, pal=6
	tsa_entry 0x103, pal=8
	tsa_entry 0x104, pal=8
	tsa_entry 0x105, pal=8
	tsa_entry 0x106, pal=9
	tsa_entry 0x107
	tsa_entry 0x108, pal=8
	tsa_entry 0x000
	tsa_entry 0x109
	tsa_entry 0x10A
	tsa_entry 0x10B
	tsa_entry 0x10C, pal=1
	tsa_entry 0x10D, pal=1
	tsa_entry 0x10E, pal=3
	tsa_entry 0x10F, pal=2
	tsa_entry 0x110, pal=2
	tsa_entry 0x111, pal=2
	tsa_entry 0x112, pal=5
	tsa_entry 0x113, pal=2
	tsa_entry 0x114, pal=2
	tsa_entry 0x115, pal=2
	tsa_entry 0x116, pal=4
	tsa_entry 0x117, pal=5
	tsa_entry 0x118, pal=4
	tsa_entry 0x119
	tsa_entry 0x11A, pal=6
	tsa_entry 0x11B, pal=5
	tsa_entry 0x11C, pal=6
	tsa_entry 0x11D, pal=6
	tsa_entry 0x11E, pal=6
	tsa_entry 0x11F, pal=6
	tsa_entry 0x120, pal=6
	tsa_entry 0x121, pal=7
	tsa_entry 0x122, pal=7
	tsa_entry 0x123, pal=8
	tsa_entry 0x124, pal=8
	tsa_entry 0x125
	tsa_entry 0x126, pal=1
	tsa_entry 0x127, pal=1
	tsa_entry 0x000
	tsa_entry 0x128
	tsa_entry 0x129, pal=7
	tsa_entry 0x12A
	tsa_entry 0x12B, pal=1
	tsa_entry 0x12C, pal=1
	tsa_entry 0x12D, pal=2
	tsa_entry 0x12E, pal=2
	tsa_entry 0x12F, pal=2
	tsa_entry 0x130, pal=2
	tsa_entry 0x131, pal=2
	tsa_entry 0x132, pal=2
	tsa_entry 0x133, pal=2
	tsa_entry 0x134
	tsa_entry 0x135, pal=3
	tsa_entry 0x136, pal=6
	tsa_entry 0x137
	tsa_entry 0x138, pal=8
	tsa_entry 0x139
	tsa_entry 0x13A, pal=8
	tsa_entry 0x13B, pal=6
	tsa_entry 0x13C, pal=7
	tsa_entry 0x13D, pal=6
	tsa_entry 0x13E, pal=7
	tsa_entry 0x13F, pal=7
	tsa_entry 0x140, pal=7
	tsa_entry 0x141, pal=9
	tsa_entry 0x142, pal=8
	tsa_entry 0x143, pal=8
	tsa_entry 0x144
	tsa_entry 0x145, pal=1
	tsa_entry 0x146, pal=9
	tsa_entry 0x147, pal=10
	tsa_entry 0x148
	tsa_entry 0x149, pal=8
	tsa_entry 0x14A
	tsa_entry 0x14B, pal=1
	tsa_entry 0x14C
	tsa_entry 0x14D, pal=2
	tsa_entry 0x14E, pal=2
	tsa_entry 0x14F, pal=2
	tsa_entry 0x150, pal=2
	tsa_entry 0x151, pal=2
	tsa_entry 0x152, pal=1
	tsa_entry 0x153
	tsa_entry 0x154, pal=4
	tsa_entry 0x155
	tsa_entry 0x156, pal=4
	tsa_entry 0x157, pal=10
	tsa_entry 0x158, pal=8
	tsa_entry 0x159
	tsa_entry 0x15A
	tsa_entry 0x15B, pal=8
	tsa_entry 0x15C, pal=6
	tsa_entry 0x15D, pal=6
	tsa_entry 0x15E, pal=8
	tsa_entry 0x15F, pal=8
	tsa_entry 0x160, pal=7
	tsa_entry 0x161, pal=7
	tsa_entry 0x162, pal=7
	tsa_entry 0x163, pal=7
	tsa_entry 0x164, pal=8
	tsa_entry 0x165
	tsa_entry 0x166, pal=1
	tsa_entry 0x000
	tsa_entry 0x167, pal=6
	tsa_entry 0x168
	tsa_entry 0x169, pal=9
	tsa_entry 0x16A
	tsa_entry 0x16B, pal=3
	tsa_entry 0x16C, pal=5
	tsa_entry 0x16C, pal=5
	tsa_entry 0x16D, pal=2
	tsa_entry 0x16E, pal=2
	tsa_entry 0x16F, pal=2
	tsa_entry 0x170, pal=1
	tsa_entry 0x171, pal=3
	tsa_entry 0x172, pal=2
	tsa_entry 0x173
	tsa_entry 0x174, pal=4
	tsa_entry 0x175, pal=5
	tsa_entry 0x176, pal=5
	tsa_entry 0x177, pal=5
	tsa_entry 0x178, pal=2
	tsa_entry 0x179, pal=7
	tsa_entry 0x17A, pal=6
	tsa_entry 0x17B, pal=6
	tsa_entry 0x17C, pal=6
	tsa_entry 0x17D, pal=7
	tsa_entry 0x17E, pal=7
	tsa_entry 0x17F, pal=6
	tsa_entry 0x180, pal=7
	tsa_entry 0x181, pal=8
	tsa_entry 0x182, pal=8
	tsa_entry 0x183, pal=6
	tsa_entry 0x184, pal=1
