	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x005
	tsa_entry 0x006
	tsa_entry 0x007
	tsa_entry 0x008
	tsa_entry 0x009, pal=1
	tsa_entry 0x00A
	tsa_entry 0x00B
	tsa_entry 0x00C
	tsa_entry 0x00D, pal=1
	tsa_entry 0x00E
	tsa_entry 0x00F
	tsa_entry 0x010
	tsa_entry 0x011
	tsa_entry 0x012
	tsa_entry 0x013, pal=1
	tsa_entry 0x013, pal=1, hflip=1
	tsa_entry 0x012, hflip=1
	tsa_entry 0x011, hflip=1
	tsa_entry 0x010, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x00E, hflip=1
	tsa_entry 0x00D, pal=1, hflip=1
	tsa_entry 0x00C, hflip=1
	tsa_entry 0x00B, hflip=1
	tsa_entry 0x00A, hflip=1
	tsa_entry 0x009, pal=1, hflip=1
	tsa_entry 0x008, hflip=1
	tsa_entry 0x007, hflip=1
	tsa_entry 0x006, hflip=1
	tsa_entry 0x005, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x01B
	tsa_entry 0x01C
	tsa_entry 0x01D
	tsa_entry 0x009, pal=1
	tsa_entry 0x01E
	tsa_entry 0x01F
	tsa_entry 0x020
	tsa_entry 0x021
	tsa_entry 0x022, pal=3
	tsa_entry 0x023, pal=3
	tsa_entry 0x024, pal=3
	tsa_entry 0x017, pal=1
	tsa_entry 0x025
	tsa_entry 0x026, pal=3
	tsa_entry 0x027
	tsa_entry 0x027, hflip=1
	tsa_entry 0x026, pal=3, hflip=1
	tsa_entry 0x025, hflip=1
	tsa_entry 0x017, pal=1, hflip=1
	tsa_entry 0x024, pal=3, hflip=1
	tsa_entry 0x023, pal=3, hflip=1
	tsa_entry 0x022, pal=3, hflip=1
	tsa_entry 0x021, hflip=1
	tsa_entry 0x020, hflip=1
	tsa_entry 0x01F, hflip=1
	tsa_entry 0x01E, hflip=1
	tsa_entry 0x009, pal=1, hflip=1
	tsa_entry 0x01D, hflip=1
	tsa_entry 0x01C, hflip=1
	tsa_entry 0x01B, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x031
	tsa_entry 0x032
	tsa_entry 0x033
	tsa_entry 0x034
	tsa_entry 0x035
	tsa_entry 0x036
	tsa_entry 0x037
	tsa_entry 0x038
	tsa_entry 0x039, pal=3
	tsa_entry 0x03A, pal=3
	tsa_entry 0x03B
	tsa_entry 0x03C, pal=1
	tsa_entry 0x03D, pal=3
	tsa_entry 0x03E, pal=3
	tsa_entry 0x03F
	tsa_entry 0x03F, hflip=1
	tsa_entry 0x03E, pal=3, hflip=1
	tsa_entry 0x03D, pal=3, hflip=1
	tsa_entry 0x03C, pal=1, hflip=1
	tsa_entry 0x03B, hflip=1
	tsa_entry 0x03A, pal=3, hflip=1
	tsa_entry 0x039, pal=3, hflip=1
	tsa_entry 0x038, hflip=1
	tsa_entry 0x037, hflip=1
	tsa_entry 0x036, hflip=1
	tsa_entry 0x035, hflip=1
	tsa_entry 0x034, hflip=1
	tsa_entry 0x033, hflip=1
	tsa_entry 0x032, hflip=1
	tsa_entry 0x031, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x048
	tsa_entry 0x049, pal=3
	tsa_entry 0x04A, pal=1
	tsa_entry 0x04B
	tsa_entry 0x04C
	tsa_entry 0x04D
	tsa_entry 0x04E
	tsa_entry 0x04F
	tsa_entry 0x050
	tsa_entry 0x051
	tsa_entry 0x052
	tsa_entry 0x053
	tsa_entry 0x054
	tsa_entry 0x055
	tsa_entry 0x056
	tsa_entry 0x056, hflip=1
	tsa_entry 0x055, hflip=1
	tsa_entry 0x054, hflip=1
	tsa_entry 0x053, hflip=1
	tsa_entry 0x052, hflip=1
	tsa_entry 0x051, hflip=1
	tsa_entry 0x050, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04E, hflip=1
	tsa_entry 0x04D, hflip=1
	tsa_entry 0x04C, hflip=1
	tsa_entry 0x04B, hflip=1
	tsa_entry 0x04A, pal=1, hflip=1
	tsa_entry 0x049, pal=3, hflip=1
	tsa_entry 0x048, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x05F, pal=3
	tsa_entry 0x060, pal=1
	tsa_entry 0x061
	tsa_entry 0x062, pal=3
	tsa_entry 0x063
	tsa_entry 0x064
	tsa_entry 0x065
	tsa_entry 0x066
	tsa_entry 0x04F
	tsa_entry 0x067
	tsa_entry 0x068
	tsa_entry 0x069
	tsa_entry 0x06A
	tsa_entry 0x06B, pal=1
	tsa_entry 0x06C
	tsa_entry 0x06C, hflip=1
	tsa_entry 0x06B, pal=1, hflip=1
	tsa_entry 0x06A, hflip=1
	tsa_entry 0x069, hflip=1
	tsa_entry 0x068, hflip=1
	tsa_entry 0x067, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x066, hflip=1
	tsa_entry 0x065, hflip=1
	tsa_entry 0x064, hflip=1
	tsa_entry 0x063, hflip=1
	tsa_entry 0x062, pal=3, hflip=1
	tsa_entry 0x061, hflip=1
	tsa_entry 0x060, pal=1, hflip=1
	tsa_entry 0x05F, pal=3, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x075, pal=1
	tsa_entry 0x076, pal=1
	tsa_entry 0x077, pal=3
	tsa_entry 0x078
	tsa_entry 0x079
	tsa_entry 0x07A
	tsa_entry 0x07B, pal=1
	tsa_entry 0x07C
	tsa_entry 0x07D
	tsa_entry 0x04F
	tsa_entry 0x07E
	tsa_entry 0x07F
	tsa_entry 0x080
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x080, hflip=1
	tsa_entry 0x07F, hflip=1
	tsa_entry 0x07E, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x07D, hflip=1
	tsa_entry 0x07C, hflip=1
	tsa_entry 0x07B, pal=1, hflip=1
	tsa_entry 0x07A, hflip=1
	tsa_entry 0x079, hflip=1
	tsa_entry 0x078, hflip=1
	tsa_entry 0x077, pal=3, hflip=1
	tsa_entry 0x076, pal=1, hflip=1
	tsa_entry 0x075, pal=1, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x088
	tsa_entry 0x089, pal=1
	tsa_entry 0x08A, pal=1
	tsa_entry 0x08B, pal=3
	tsa_entry 0x08C, pal=3
	tsa_entry 0x08D
	tsa_entry 0x08E
	tsa_entry 0x08F
	tsa_entry 0x090
	tsa_entry 0x091
	tsa_entry 0x087, vflip=1
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x087, hflip=1, vflip=1
	tsa_entry 0x091, hflip=1
	tsa_entry 0x090, hflip=1
	tsa_entry 0x08F, hflip=1
	tsa_entry 0x08E, hflip=1
	tsa_entry 0x08D, hflip=1
	tsa_entry 0x08C, pal=3, hflip=1
	tsa_entry 0x08B, pal=3, hflip=1
	tsa_entry 0x08A, pal=1, hflip=1
	tsa_entry 0x089, pal=1, hflip=1
	tsa_entry 0x088, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x098
	tsa_entry 0x099
	tsa_entry 0x09A
	tsa_entry 0x09B
	tsa_entry 0x09C
	tsa_entry 0x09D, pal=3
	tsa_entry 0x09E, pal=3
	tsa_entry 0x09F, pal=3
	tsa_entry 0x0A0
	tsa_entry 0x0A1
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x0A1, hflip=1
	tsa_entry 0x0A0, hflip=1
	tsa_entry 0x09F, pal=3, hflip=1
	tsa_entry 0x09E, pal=3, hflip=1
	tsa_entry 0x09D, pal=3, hflip=1
	tsa_entry 0x09C, hflip=1
	tsa_entry 0x09B, hflip=1
	tsa_entry 0x09A, hflip=1
	tsa_entry 0x099, hflip=1
	tsa_entry 0x098, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x0A7
	tsa_entry 0x0A8
	tsa_entry 0x0A9
	tsa_entry 0x0AA
	tsa_entry 0x087, hflip=1
	tsa_entry 0x0AB
	tsa_entry 0x0AC
	tsa_entry 0x0AD
	tsa_entry 0x0AE
	tsa_entry 0x0AF
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x0AF, hflip=1
	tsa_entry 0x0AE, hflip=1
	tsa_entry 0x0AD, hflip=1
	tsa_entry 0x0AC, hflip=1
	tsa_entry 0x0AB, hflip=1
	tsa_entry 0x087
	tsa_entry 0x0AA, hflip=1
	tsa_entry 0x0A9, hflip=1
	tsa_entry 0x0A8, hflip=1
	tsa_entry 0x0A7, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x0B4, pal=1
	tsa_entry 0x0B5, pal=1
	tsa_entry 0x0B6, pal=1
	tsa_entry 0x0B7
	tsa_entry 0x0B8
	tsa_entry 0x0B9
	tsa_entry 0x0BA
	tsa_entry 0x0BB
	tsa_entry 0x0BC
	tsa_entry 0x0BD
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x0BD, hflip=1
	tsa_entry 0x0BC, hflip=1
	tsa_entry 0x0BB, hflip=1
	tsa_entry 0x0BA, hflip=1
	tsa_entry 0x0B9, hflip=1
	tsa_entry 0x0B8, hflip=1
	tsa_entry 0x0B7, hflip=1
	tsa_entry 0x0B6, pal=1, hflip=1
	tsa_entry 0x0B5, pal=1, hflip=1
	tsa_entry 0x0B4, pal=1, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x0B4, pal=1, vflip=1
	tsa_entry 0x0B5, pal=1, vflip=1
	tsa_entry 0x0B6, pal=1, vflip=1
	tsa_entry 0x0B7, vflip=1
	tsa_entry 0x0B8, vflip=1
	tsa_entry 0x0B9, vflip=1
	tsa_entry 0x0BA, vflip=1
	tsa_entry 0x0BB, vflip=1
	tsa_entry 0x0BC, vflip=1
	tsa_entry 0x0BD, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x0BD, hflip=1, vflip=1
	tsa_entry 0x0BC, hflip=1, vflip=1
	tsa_entry 0x0BB, hflip=1, vflip=1
	tsa_entry 0x0BA, hflip=1, vflip=1
	tsa_entry 0x0B9, hflip=1, vflip=1
	tsa_entry 0x0B8, hflip=1, vflip=1
	tsa_entry 0x0B7, hflip=1, vflip=1
	tsa_entry 0x0B6, pal=1, hflip=1, vflip=1
	tsa_entry 0x0B5, pal=1, hflip=1, vflip=1
	tsa_entry 0x0B4, pal=1, hflip=1, vflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x0A7, vflip=1
	tsa_entry 0x0A8, vflip=1
	tsa_entry 0x0A9, vflip=1
	tsa_entry 0x0AA, vflip=1
	tsa_entry 0x087, hflip=1, vflip=1
	tsa_entry 0x0AB, vflip=1
	tsa_entry 0x0AC, vflip=1
	tsa_entry 0x0AD, vflip=1
	tsa_entry 0x0AE, vflip=1
	tsa_entry 0x0AF, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x0AF, hflip=1, vflip=1
	tsa_entry 0x0AE, hflip=1, vflip=1
	tsa_entry 0x0AD, hflip=1, vflip=1
	tsa_entry 0x0AC, hflip=1, vflip=1
	tsa_entry 0x0AB, hflip=1, vflip=1
	tsa_entry 0x087, vflip=1
	tsa_entry 0x0AA, hflip=1, vflip=1
	tsa_entry 0x0A9, hflip=1, vflip=1
	tsa_entry 0x0A8, hflip=1, vflip=1
	tsa_entry 0x0A7, hflip=1, vflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x098, vflip=1
	tsa_entry 0x099, vflip=1
	tsa_entry 0x09A, vflip=1
	tsa_entry 0x09B, vflip=1
	tsa_entry 0x09C, vflip=1
	tsa_entry 0x09D, pal=3, vflip=1
	tsa_entry 0x09E, pal=3, vflip=1
	tsa_entry 0x09F, pal=3, vflip=1
	tsa_entry 0x0A0, vflip=1
	tsa_entry 0x0A1, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x0A1, hflip=1, vflip=1
	tsa_entry 0x0A0, hflip=1, vflip=1
	tsa_entry 0x09F, pal=3, hflip=1, vflip=1
	tsa_entry 0x09E, pal=3, hflip=1, vflip=1
	tsa_entry 0x09D, pal=3, hflip=1, vflip=1
	tsa_entry 0x09C, hflip=1, vflip=1
	tsa_entry 0x09B, hflip=1, vflip=1
	tsa_entry 0x09A, hflip=1, vflip=1
	tsa_entry 0x099, hflip=1, vflip=1
	tsa_entry 0x098, hflip=1, vflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x088, vflip=1
	tsa_entry 0x089, pal=1, vflip=1
	tsa_entry 0x08A, pal=1, vflip=1
	tsa_entry 0x08B, pal=3, vflip=1
	tsa_entry 0x08C, pal=3, vflip=1
	tsa_entry 0x08D, vflip=1
	tsa_entry 0x08E, vflip=1
	tsa_entry 0x08F, vflip=1
	tsa_entry 0x090, vflip=1
	tsa_entry 0x091, vflip=1
	tsa_entry 0x087
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x087, hflip=1
	tsa_entry 0x091, hflip=1, vflip=1
	tsa_entry 0x090, hflip=1, vflip=1
	tsa_entry 0x08F, hflip=1, vflip=1
	tsa_entry 0x08E, hflip=1, vflip=1
	tsa_entry 0x08D, hflip=1, vflip=1
	tsa_entry 0x08C, pal=3, hflip=1, vflip=1
	tsa_entry 0x08B, pal=3, hflip=1, vflip=1
	tsa_entry 0x08A, pal=1, hflip=1, vflip=1
	tsa_entry 0x089, pal=1, hflip=1, vflip=1
	tsa_entry 0x088, hflip=1, vflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x075, pal=1, vflip=1
	tsa_entry 0x076, pal=1, vflip=1
	tsa_entry 0x077, pal=3, vflip=1
	tsa_entry 0x078, vflip=1
	tsa_entry 0x079, vflip=1
	tsa_entry 0x07A, vflip=1
	tsa_entry 0x07B, pal=1, vflip=1
	tsa_entry 0x07C, vflip=1
	tsa_entry 0x07D, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x07E, vflip=1
	tsa_entry 0x07F, vflip=1
	tsa_entry 0x080, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x080, hflip=1, vflip=1
	tsa_entry 0x07F, hflip=1, vflip=1
	tsa_entry 0x07E, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x07D, hflip=1, vflip=1
	tsa_entry 0x07C, hflip=1, vflip=1
	tsa_entry 0x07B, pal=1, hflip=1, vflip=1
	tsa_entry 0x07A, hflip=1, vflip=1
	tsa_entry 0x079, hflip=1, vflip=1
	tsa_entry 0x078, hflip=1, vflip=1
	tsa_entry 0x077, pal=3, hflip=1, vflip=1
	tsa_entry 0x076, pal=1, hflip=1, vflip=1
	tsa_entry 0x075, pal=1, hflip=1, vflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x05F, pal=3, vflip=1
	tsa_entry 0x060, pal=1, vflip=1
	tsa_entry 0x061, vflip=1
	tsa_entry 0x062, pal=3, vflip=1
	tsa_entry 0x063, vflip=1
	tsa_entry 0x064, vflip=1
	tsa_entry 0x065, vflip=1
	tsa_entry 0x066, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x067, vflip=1
	tsa_entry 0x068, vflip=1
	tsa_entry 0x069, vflip=1
	tsa_entry 0x06A, vflip=1
	tsa_entry 0x06B, pal=1, vflip=1
	tsa_entry 0x06C, vflip=1
	tsa_entry 0x06C, hflip=1, vflip=1
	tsa_entry 0x06B, pal=1, hflip=1, vflip=1
	tsa_entry 0x06A, hflip=1, vflip=1
	tsa_entry 0x069, hflip=1, vflip=1
	tsa_entry 0x068, hflip=1, vflip=1
	tsa_entry 0x067, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x066, hflip=1, vflip=1
	tsa_entry 0x065, hflip=1, vflip=1
	tsa_entry 0x064, hflip=1, vflip=1
	tsa_entry 0x063, hflip=1, vflip=1
	tsa_entry 0x062, pal=3, hflip=1, vflip=1
	tsa_entry 0x061, hflip=1, vflip=1
	tsa_entry 0x060, pal=1, hflip=1, vflip=1
	tsa_entry 0x05F, pal=3, hflip=1, vflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x048, vflip=1
	tsa_entry 0x049, pal=3, vflip=1
	tsa_entry 0x04A, pal=1, vflip=1
	tsa_entry 0x04B, vflip=1
	tsa_entry 0x04C, vflip=1
	tsa_entry 0x04D, vflip=1
	tsa_entry 0x04E, vflip=1
	tsa_entry 0x04F, vflip=1
	tsa_entry 0x050, vflip=1
	tsa_entry 0x051, vflip=1
	tsa_entry 0x052, vflip=1
	tsa_entry 0x053, vflip=1
	tsa_entry 0x054, vflip=1
	tsa_entry 0x055, vflip=1
	tsa_entry 0x056, vflip=1
	tsa_entry 0x056, hflip=1, vflip=1
	tsa_entry 0x055, hflip=1, vflip=1
	tsa_entry 0x054, hflip=1, vflip=1
	tsa_entry 0x053, hflip=1, vflip=1
	tsa_entry 0x052, hflip=1, vflip=1
	tsa_entry 0x051, hflip=1, vflip=1
	tsa_entry 0x050, hflip=1, vflip=1
	tsa_entry 0x04F, hflip=1, vflip=1
	tsa_entry 0x04E, hflip=1, vflip=1
	tsa_entry 0x04D, hflip=1, vflip=1
	tsa_entry 0x04C, hflip=1, vflip=1
	tsa_entry 0x04B, hflip=1, vflip=1
	tsa_entry 0x04A, pal=1, hflip=1, vflip=1
	tsa_entry 0x049, pal=3, hflip=1, vflip=1
	tsa_entry 0x048, hflip=1, vflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x031, vflip=1
	tsa_entry 0x032, vflip=1
	tsa_entry 0x033, vflip=1
	tsa_entry 0x034, vflip=1
	tsa_entry 0x035, vflip=1
	tsa_entry 0x036, vflip=1
	tsa_entry 0x037, vflip=1
	tsa_entry 0x038, vflip=1
	tsa_entry 0x039, pal=3, vflip=1
	tsa_entry 0x03A, pal=3, vflip=1
	tsa_entry 0x03B, vflip=1
	tsa_entry 0x03C, pal=1, vflip=1
	tsa_entry 0x03D, pal=3, vflip=1
	tsa_entry 0x03E, pal=3, vflip=1
	tsa_entry 0x03F, vflip=1
	tsa_entry 0x03F, hflip=1, vflip=1
	tsa_entry 0x03E, pal=3, hflip=1, vflip=1
	tsa_entry 0x03D, pal=3, hflip=1, vflip=1
	tsa_entry 0x03C, pal=1, hflip=1, vflip=1
	tsa_entry 0x03B, hflip=1, vflip=1
	tsa_entry 0x03A, pal=3, hflip=1, vflip=1
	tsa_entry 0x039, pal=3, hflip=1, vflip=1
	tsa_entry 0x038, hflip=1, vflip=1
	tsa_entry 0x037, hflip=1, vflip=1
	tsa_entry 0x036, hflip=1, vflip=1
	tsa_entry 0x035, hflip=1, vflip=1
	tsa_entry 0x034, hflip=1, vflip=1
	tsa_entry 0x033, hflip=1, vflip=1
	tsa_entry 0x032, hflip=1, vflip=1
	tsa_entry 0x031, hflip=1, vflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x01B, vflip=1
	tsa_entry 0x01C, vflip=1
	tsa_entry 0x01D, vflip=1
	tsa_entry 0x009, pal=1, vflip=1
	tsa_entry 0x01E, vflip=1
	tsa_entry 0x01F, vflip=1
	tsa_entry 0x020, vflip=1
	tsa_entry 0x021, vflip=1
	tsa_entry 0x022, pal=3, vflip=1
	tsa_entry 0x023, pal=3, vflip=1
	tsa_entry 0x024, pal=3, vflip=1
	tsa_entry 0x017, pal=1, vflip=1
	tsa_entry 0x025, vflip=1
	tsa_entry 0x026, pal=3, vflip=1
	tsa_entry 0x027, vflip=1
	tsa_entry 0x027, hflip=1, vflip=1
	tsa_entry 0x026, pal=3, hflip=1, vflip=1
	tsa_entry 0x025, hflip=1, vflip=1
	tsa_entry 0x017, pal=1, hflip=1, vflip=1
	tsa_entry 0x024, pal=3, hflip=1, vflip=1
	tsa_entry 0x023, pal=3, hflip=1, vflip=1
	tsa_entry 0x022, pal=3, hflip=1, vflip=1
	tsa_entry 0x021, hflip=1, vflip=1
	tsa_entry 0x020, hflip=1, vflip=1
	tsa_entry 0x01F, hflip=1, vflip=1
	tsa_entry 0x01E, hflip=1, vflip=1
	tsa_entry 0x009, pal=1, hflip=1, vflip=1
	tsa_entry 0x01D, hflip=1, vflip=1
	tsa_entry 0x01C, hflip=1, vflip=1
	tsa_entry 0x01B, hflip=1, vflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x005, vflip=1
	tsa_entry 0x006, vflip=1
	tsa_entry 0x007, vflip=1
	tsa_entry 0x008, vflip=1
	tsa_entry 0x009, pal=1, vflip=1
	tsa_entry 0x00A, vflip=1
	tsa_entry 0x00B, vflip=1
	tsa_entry 0x00C, vflip=1
	tsa_entry 0x00D, pal=1, vflip=1
	tsa_entry 0x00E, vflip=1
	tsa_entry 0x00F, vflip=1
	tsa_entry 0x010, vflip=1
	tsa_entry 0x011, vflip=1
	tsa_entry 0x012, vflip=1
	tsa_entry 0x013, pal=1, vflip=1
	tsa_entry 0x013, pal=1, hflip=1, vflip=1
	tsa_entry 0x012, hflip=1, vflip=1
	tsa_entry 0x011, hflip=1, vflip=1
	tsa_entry 0x010, hflip=1, vflip=1
	tsa_entry 0x00F, hflip=1, vflip=1
	tsa_entry 0x00E, hflip=1, vflip=1
	tsa_entry 0x00D, pal=1, hflip=1, vflip=1
	tsa_entry 0x00C, hflip=1, vflip=1
	tsa_entry 0x00B, hflip=1, vflip=1
	tsa_entry 0x00A, hflip=1, vflip=1
	tsa_entry 0x009, pal=1, hflip=1, vflip=1
	tsa_entry 0x008, hflip=1, vflip=1
	tsa_entry 0x007, hflip=1, vflip=1
	tsa_entry 0x006, hflip=1, vflip=1
	tsa_entry 0x005, hflip=1, vflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
