	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x0DB
	tsa_entry 0x001
	tsa_entry 0x002
	tsa_entry 0x003
	tsa_entry 0x004
	tsa_entry 0x005
	tsa_entry 0x006
	tsa_entry 0x007
	tsa_entry 0x008
	tsa_entry 0x009
	tsa_entry 0x00A
	tsa_entry 0x00B
	tsa_entry 0x00C
	tsa_entry 0x00D
	tsa_entry 0x00E
	tsa_entry 0x00E, hflip=1
	tsa_entry 0x00D, hflip=1
	tsa_entry 0x00C, hflip=1
	tsa_entry 0x00B, hflip=1
	tsa_entry 0x00A, hflip=1
	tsa_entry 0x009, hflip=1
	tsa_entry 0x008, hflip=1
	tsa_entry 0x007, hflip=1
	tsa_entry 0x006, hflip=1
	tsa_entry 0x005, hflip=1
	tsa_entry 0x004, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x002, hflip=1
	tsa_entry 0x001, hflip=1
	tsa_entry 0x0DB, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x00F
	tsa_entry 0x010
	tsa_entry 0x011
	tsa_entry 0x012
	tsa_entry 0x013
	tsa_entry 0x014
	tsa_entry 0x015
	tsa_entry 0x016
	tsa_entry 0x017
	tsa_entry 0x018
	tsa_entry 0x019
	tsa_entry 0x01A
	tsa_entry 0x01B
	tsa_entry 0x01C
	tsa_entry 0x01D
	tsa_entry 0x01D, hflip=1
	tsa_entry 0x01C, hflip=1
	tsa_entry 0x01B, hflip=1
	tsa_entry 0x01A, hflip=1
	tsa_entry 0x019, hflip=1
	tsa_entry 0x018, hflip=1
	tsa_entry 0x017, hflip=1
	tsa_entry 0x016, hflip=1
	tsa_entry 0x015, hflip=1
	tsa_entry 0x014, hflip=1
	tsa_entry 0x013, hflip=1
	tsa_entry 0x012, hflip=1
	tsa_entry 0x011, hflip=1
	tsa_entry 0x010, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x01E
	tsa_entry 0x01F
	tsa_entry 0x020
	tsa_entry 0x021
	tsa_entry 0x022
	tsa_entry 0x023
	tsa_entry 0x024
	tsa_entry 0x025
	tsa_entry 0x026
	tsa_entry 0x027
	tsa_entry 0x028
	tsa_entry 0x029
	tsa_entry 0x02A
	tsa_entry 0x02B
	tsa_entry 0x02C
	tsa_entry 0x02C, hflip=1
	tsa_entry 0x02B, hflip=1
	tsa_entry 0x02A, hflip=1
	tsa_entry 0x029, hflip=1
	tsa_entry 0x028, hflip=1
	tsa_entry 0x027, hflip=1
	tsa_entry 0x026, hflip=1
	tsa_entry 0x025, hflip=1
	tsa_entry 0x024, hflip=1
	tsa_entry 0x023, hflip=1
	tsa_entry 0x022, hflip=1
	tsa_entry 0x021, hflip=1
	tsa_entry 0x020, hflip=1
	tsa_entry 0x01F, hflip=1
	tsa_entry 0x01E, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x02D
	tsa_entry 0x02E
	tsa_entry 0x02F
	tsa_entry 0x030
	tsa_entry 0x031
	tsa_entry 0x032
	tsa_entry 0x033
	tsa_entry 0x034
	tsa_entry 0x035
	tsa_entry 0x036
	tsa_entry 0x037
	tsa_entry 0x038
	tsa_entry 0x039
	tsa_entry 0x03A
	tsa_entry 0x03B
	tsa_entry 0x03B, hflip=1
	tsa_entry 0x03A, hflip=1
	tsa_entry 0x039, hflip=1
	tsa_entry 0x038, hflip=1
	tsa_entry 0x037, hflip=1
	tsa_entry 0x036, hflip=1
	tsa_entry 0x035, hflip=1
	tsa_entry 0x034, hflip=1
	tsa_entry 0x033, hflip=1
	tsa_entry 0x032, hflip=1
	tsa_entry 0x031, hflip=1
	tsa_entry 0x030, hflip=1
	tsa_entry 0x02F, hflip=1
	tsa_entry 0x02E, hflip=1
	tsa_entry 0x02D, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x03C
	tsa_entry 0x03D
	tsa_entry 0x03E
	tsa_entry 0x03F
	tsa_entry 0x040
	tsa_entry 0x041
	tsa_entry 0x042
	tsa_entry 0x043
	tsa_entry 0x044
	tsa_entry 0x045
	tsa_entry 0x046
	tsa_entry 0x047
	tsa_entry 0x048
	tsa_entry 0x049
	tsa_entry 0x04A
	tsa_entry 0x04A, hflip=1
	tsa_entry 0x049, hflip=1
	tsa_entry 0x048, hflip=1
	tsa_entry 0x047, hflip=1
	tsa_entry 0x046, hflip=1
	tsa_entry 0x045, hflip=1
	tsa_entry 0x044, hflip=1
	tsa_entry 0x043, hflip=1
	tsa_entry 0x042, hflip=1
	tsa_entry 0x041, hflip=1
	tsa_entry 0x040, hflip=1
	tsa_entry 0x03F, hflip=1
	tsa_entry 0x03E, hflip=1
	tsa_entry 0x03D, hflip=1
	tsa_entry 0x03C, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x04B
	tsa_entry 0x04C
	tsa_entry 0x04D
	tsa_entry 0x04E
	tsa_entry 0x04F
	tsa_entry 0x050
	tsa_entry 0x051
	tsa_entry 0x052
	tsa_entry 0x053
	tsa_entry 0x054
	tsa_entry 0x055
	tsa_entry 0x056
	tsa_entry 0x057
	tsa_entry 0x058
	tsa_entry 0x059
	tsa_entry 0x059, hflip=1
	tsa_entry 0x058, hflip=1
	tsa_entry 0x057, hflip=1
	tsa_entry 0x056, hflip=1
	tsa_entry 0x055, hflip=1
	tsa_entry 0x054, hflip=1
	tsa_entry 0x053, hflip=1
	tsa_entry 0x052, hflip=1
	tsa_entry 0x051, hflip=1
	tsa_entry 0x050, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04E, hflip=1
	tsa_entry 0x04D, hflip=1
	tsa_entry 0x04C, hflip=1
	tsa_entry 0x04B, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x05A
	tsa_entry 0x05B
	tsa_entry 0x05C
	tsa_entry 0x05D
	tsa_entry 0x05E
	tsa_entry 0x05F
	tsa_entry 0x060
	tsa_entry 0x061
	tsa_entry 0x062
	tsa_entry 0x063
	tsa_entry 0x064
	tsa_entry 0x065
	tsa_entry 0x066
	tsa_entry 0x067
	tsa_entry 0x068
	tsa_entry 0x068, hflip=1
	tsa_entry 0x067, hflip=1
	tsa_entry 0x066, hflip=1
	tsa_entry 0x065, hflip=1
	tsa_entry 0x064, hflip=1
	tsa_entry 0x063, hflip=1
	tsa_entry 0x062, hflip=1
	tsa_entry 0x061, hflip=1
	tsa_entry 0x060, hflip=1
	tsa_entry 0x05F, hflip=1
	tsa_entry 0x05E, hflip=1
	tsa_entry 0x05D, hflip=1
	tsa_entry 0x05C, hflip=1
	tsa_entry 0x05B, hflip=1
	tsa_entry 0x05A, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x069
	tsa_entry 0x06A
	tsa_entry 0x06B
	tsa_entry 0x06C
	tsa_entry 0x06D
	tsa_entry 0x06E
	tsa_entry 0x06F
	tsa_entry 0x070
	tsa_entry 0x071
	tsa_entry 0x072
	tsa_entry 0x073
	tsa_entry 0x074
	tsa_entry 0x075
	tsa_entry 0x076
	tsa_entry 0x077
	tsa_entry 0x077, hflip=1
	tsa_entry 0x076, hflip=1
	tsa_entry 0x075, hflip=1
	tsa_entry 0x074, hflip=1
	tsa_entry 0x073, hflip=1
	tsa_entry 0x072, hflip=1
	tsa_entry 0x071, hflip=1
	tsa_entry 0x070, hflip=1
	tsa_entry 0x06F, hflip=1
	tsa_entry 0x06E, hflip=1
	tsa_entry 0x06D, hflip=1
	tsa_entry 0x06C, hflip=1
	tsa_entry 0x06B, hflip=1
	tsa_entry 0x06A, hflip=1
	tsa_entry 0x069, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x078
	tsa_entry 0x079
	tsa_entry 0x07A
	tsa_entry 0x07B
	tsa_entry 0x07C
	tsa_entry 0x07D
	tsa_entry 0x07E
	tsa_entry 0x07F
	tsa_entry 0x080
	tsa_entry 0x081
	tsa_entry 0x082
	tsa_entry 0x083
	tsa_entry 0x084
	tsa_entry 0x085
	tsa_entry 0x086
	tsa_entry 0x086, hflip=1
	tsa_entry 0x085, hflip=1
	tsa_entry 0x084, hflip=1
	tsa_entry 0x083, hflip=1
	tsa_entry 0x082, hflip=1
	tsa_entry 0x081, hflip=1
	tsa_entry 0x080, hflip=1
	tsa_entry 0x07F, hflip=1
	tsa_entry 0x07E, hflip=1
	tsa_entry 0x07D, hflip=1
	tsa_entry 0x07C, hflip=1
	tsa_entry 0x07B, hflip=1
	tsa_entry 0x07A, hflip=1
	tsa_entry 0x079, hflip=1
	tsa_entry 0x078, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x087
	tsa_entry 0x088
	tsa_entry 0x089
	tsa_entry 0x08A
	tsa_entry 0x08B
	tsa_entry 0x08C
	tsa_entry 0x08D
	tsa_entry 0x08E
	tsa_entry 0x08F
	tsa_entry 0x090
	tsa_entry 0x091
	tsa_entry 0x092
	tsa_entry 0x093
	tsa_entry 0x094
	tsa_entry 0x095
	tsa_entry 0x095, hflip=1
	tsa_entry 0x094, hflip=1
	tsa_entry 0x093, hflip=1
	tsa_entry 0x092, hflip=1
	tsa_entry 0x091, hflip=1
	tsa_entry 0x090, hflip=1
	tsa_entry 0x08F, hflip=1
	tsa_entry 0x08E, hflip=1
	tsa_entry 0x08D, hflip=1
	tsa_entry 0x08C, hflip=1
	tsa_entry 0x08B, hflip=1
	tsa_entry 0x08A, hflip=1
	tsa_entry 0x089, hflip=1
	tsa_entry 0x088, hflip=1
	tsa_entry 0x087, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x096
	tsa_entry 0x097
	tsa_entry 0x098
	tsa_entry 0x099
	tsa_entry 0x09A
	tsa_entry 0x09B
	tsa_entry 0x09C
	tsa_entry 0x09D
	tsa_entry 0x09E
	tsa_entry 0x09F
	tsa_entry 0x0A0
	tsa_entry 0x0A1
	tsa_entry 0x0A2
	tsa_entry 0x0A3
	tsa_entry 0x0A4
	tsa_entry 0x0A4, hflip=1
	tsa_entry 0x0A3, hflip=1
	tsa_entry 0x0A2, hflip=1
	tsa_entry 0x0A1, hflip=1
	tsa_entry 0x0A0, hflip=1
	tsa_entry 0x09F, hflip=1
	tsa_entry 0x09E, hflip=1
	tsa_entry 0x09D, hflip=1
	tsa_entry 0x09C, hflip=1
	tsa_entry 0x09B, hflip=1
	tsa_entry 0x09A, hflip=1
	tsa_entry 0x099, hflip=1
	tsa_entry 0x098, hflip=1
	tsa_entry 0x097, hflip=1
	tsa_entry 0x096, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x00F
	tsa_entry 0x010
	tsa_entry 0x0A5
	tsa_entry 0x0A6
	tsa_entry 0x0A7
	tsa_entry 0x0A8
	tsa_entry 0x015
	tsa_entry 0x016
	tsa_entry 0x017
	tsa_entry 0x018
	tsa_entry 0x019
	tsa_entry 0x01A
	tsa_entry 0x01B
	tsa_entry 0x0A9
	tsa_entry 0x0AA
	tsa_entry 0x0AA, hflip=1
	tsa_entry 0x0A9, hflip=1
	tsa_entry 0x01B, hflip=1
	tsa_entry 0x01A, hflip=1
	tsa_entry 0x019, hflip=1
	tsa_entry 0x018, hflip=1
	tsa_entry 0x017, hflip=1
	tsa_entry 0x016, hflip=1
	tsa_entry 0x015, hflip=1
	tsa_entry 0x0A8, hflip=1
	tsa_entry 0x0A7, hflip=1
	tsa_entry 0x0A6, hflip=1
	tsa_entry 0x0A5, hflip=1
	tsa_entry 0x010, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x01E
	tsa_entry 0x01F
	tsa_entry 0x020
	tsa_entry 0x0AB
	tsa_entry 0x0AC
	tsa_entry 0x023
	tsa_entry 0x024
	tsa_entry 0x0AD
	tsa_entry 0x0AE
	tsa_entry 0x027
	tsa_entry 0x028
	tsa_entry 0x0AF
	tsa_entry 0x0B0
	tsa_entry 0x02B
	tsa_entry 0x0B1
	tsa_entry 0x0B1, hflip=1
	tsa_entry 0x02B, hflip=1
	tsa_entry 0x0B0, hflip=1
	tsa_entry 0x0AF, hflip=1
	tsa_entry 0x028, hflip=1
	tsa_entry 0x027, hflip=1
	tsa_entry 0x0AE, hflip=1
	tsa_entry 0x0AD, hflip=1
	tsa_entry 0x024, hflip=1
	tsa_entry 0x023, hflip=1
	tsa_entry 0x0AC, hflip=1
	tsa_entry 0x0AB, hflip=1
	tsa_entry 0x020, hflip=1
	tsa_entry 0x01F, hflip=1
	tsa_entry 0x01E, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x0B2
	tsa_entry 0x02E
	tsa_entry 0x02F
	tsa_entry 0x030
	tsa_entry 0x031
	tsa_entry 0x032
	tsa_entry 0x033
	tsa_entry 0x034
	tsa_entry 0x035
	tsa_entry 0x036
	tsa_entry 0x0B3
	tsa_entry 0x0B4
	tsa_entry 0x0B5
	tsa_entry 0x03A
	tsa_entry 0x0B6
	tsa_entry 0x0B6, hflip=1
	tsa_entry 0x03A, hflip=1
	tsa_entry 0x0B5, hflip=1
	tsa_entry 0x0B4, hflip=1
	tsa_entry 0x0B3, hflip=1
	tsa_entry 0x036, hflip=1
	tsa_entry 0x035, hflip=1
	tsa_entry 0x034, hflip=1
	tsa_entry 0x033, hflip=1
	tsa_entry 0x032, hflip=1
	tsa_entry 0x031, hflip=1
	tsa_entry 0x030, hflip=1
	tsa_entry 0x02F, hflip=1
	tsa_entry 0x02E, hflip=1
	tsa_entry 0x0B2, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x03C
	tsa_entry 0x03D
	tsa_entry 0x03E
	tsa_entry 0x0B7
	tsa_entry 0x0B8
	tsa_entry 0x041
	tsa_entry 0x042
	tsa_entry 0x043
	tsa_entry 0x044
	tsa_entry 0x045
	tsa_entry 0x0B9
	tsa_entry 0x0BA
	tsa_entry 0x0BB
	tsa_entry 0x049
	tsa_entry 0x0BC
	tsa_entry 0x0BC, hflip=1
	tsa_entry 0x049, hflip=1
	tsa_entry 0x0BB, hflip=1
	tsa_entry 0x0BA, hflip=1
	tsa_entry 0x0B9, hflip=1
	tsa_entry 0x045, hflip=1
	tsa_entry 0x044, hflip=1
	tsa_entry 0x043, hflip=1
	tsa_entry 0x042, hflip=1
	tsa_entry 0x041, hflip=1
	tsa_entry 0x0B8, hflip=1
	tsa_entry 0x0B7, hflip=1
	tsa_entry 0x03E, hflip=1
	tsa_entry 0x03D, hflip=1
	tsa_entry 0x03C, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x0BD
	tsa_entry 0x0BE
	tsa_entry 0x0BF
	tsa_entry 0x0C0
	tsa_entry 0x0C1
	tsa_entry 0x050
	tsa_entry 0x051
	tsa_entry 0x0C2
	tsa_entry 0x053
	tsa_entry 0x054
	tsa_entry 0x055
	tsa_entry 0x056
	tsa_entry 0x057
	tsa_entry 0x058
	tsa_entry 0x0C3
	tsa_entry 0x0C3, hflip=1
	tsa_entry 0x058, hflip=1
	tsa_entry 0x057, hflip=1
	tsa_entry 0x056, hflip=1
	tsa_entry 0x055, hflip=1
	tsa_entry 0x054, hflip=1
	tsa_entry 0x053, hflip=1
	tsa_entry 0x0C2, hflip=1
	tsa_entry 0x051, hflip=1
	tsa_entry 0x050, hflip=1
	tsa_entry 0x0C1, hflip=1
	tsa_entry 0x0C0, hflip=1
	tsa_entry 0x0BF, hflip=1
	tsa_entry 0x0BE, hflip=1
	tsa_entry 0x0BD, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x0C4
	tsa_entry 0x0C5
	tsa_entry 0x05C
	tsa_entry 0x05D
	tsa_entry 0x05E
	tsa_entry 0x05F
	tsa_entry 0x060
	tsa_entry 0x0C6
	tsa_entry 0x062
	tsa_entry 0x063
	tsa_entry 0x064
	tsa_entry 0x065
	tsa_entry 0x066
	tsa_entry 0x067
	tsa_entry 0x0C7
	tsa_entry 0x0C7, hflip=1
	tsa_entry 0x067, hflip=1
	tsa_entry 0x066, hflip=1
	tsa_entry 0x065, hflip=1
	tsa_entry 0x064, hflip=1
	tsa_entry 0x063, hflip=1
	tsa_entry 0x062, hflip=1
	tsa_entry 0x0C6, hflip=1
	tsa_entry 0x060, hflip=1
	tsa_entry 0x05F, hflip=1
	tsa_entry 0x05E, hflip=1
	tsa_entry 0x05D, hflip=1
	tsa_entry 0x05C, hflip=1
	tsa_entry 0x0C5, hflip=1
	tsa_entry 0x0C4, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x0C8
	tsa_entry 0x06A
	tsa_entry 0x06B
	tsa_entry 0x06C
	tsa_entry 0x06D
	tsa_entry 0x06E
	tsa_entry 0x06F
	tsa_entry 0x070
	tsa_entry 0x071
	tsa_entry 0x072
	tsa_entry 0x073
	tsa_entry 0x074
	tsa_entry 0x075
	tsa_entry 0x076
	tsa_entry 0x0C9
	tsa_entry 0x0C9, hflip=1
	tsa_entry 0x076, hflip=1
	tsa_entry 0x075, hflip=1
	tsa_entry 0x074, hflip=1
	tsa_entry 0x073, hflip=1
	tsa_entry 0x072, hflip=1
	tsa_entry 0x071, hflip=1
	tsa_entry 0x070, hflip=1
	tsa_entry 0x06F, hflip=1
	tsa_entry 0x06E, hflip=1
	tsa_entry 0x06D, hflip=1
	tsa_entry 0x06C, hflip=1
	tsa_entry 0x06B, hflip=1
	tsa_entry 0x06A, hflip=1
	tsa_entry 0x0C8, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x078
	tsa_entry 0x079
	tsa_entry 0x07A
	tsa_entry 0x07B
	tsa_entry 0x0CA
	tsa_entry 0x07D
	tsa_entry 0x07E
	tsa_entry 0x07F
	tsa_entry 0x080
	tsa_entry 0x081
	tsa_entry 0x082
	tsa_entry 0x083
	tsa_entry 0x084
	tsa_entry 0x085
	tsa_entry 0x0CB
	tsa_entry 0x0CB, hflip=1
	tsa_entry 0x085, hflip=1
	tsa_entry 0x084, hflip=1
	tsa_entry 0x083, hflip=1
	tsa_entry 0x082, hflip=1
	tsa_entry 0x081, hflip=1
	tsa_entry 0x080, hflip=1
	tsa_entry 0x07F, hflip=1
	tsa_entry 0x07E, hflip=1
	tsa_entry 0x07D, hflip=1
	tsa_entry 0x0CA, hflip=1
	tsa_entry 0x07B, hflip=1
	tsa_entry 0x07A, hflip=1
	tsa_entry 0x079, hflip=1
	tsa_entry 0x078, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x0CC
	tsa_entry 0x0CD
	tsa_entry 0x0CE
	tsa_entry 0x0CF
	tsa_entry 0x0D0
	tsa_entry 0x0D1
	tsa_entry 0x0D2
	tsa_entry 0x0D3
	tsa_entry 0x0D4
	tsa_entry 0x0D5
	tsa_entry 0x0D6
	tsa_entry 0x0D7
	tsa_entry 0x0D8
	tsa_entry 0x0D9
	tsa_entry 0x0DA
	tsa_entry 0x0DA, hflip=1
	tsa_entry 0x0D9, hflip=1
	tsa_entry 0x0D8, hflip=1
	tsa_entry 0x0D7, hflip=1
	tsa_entry 0x0D6, hflip=1
	tsa_entry 0x0D5, hflip=1
	tsa_entry 0x0D4, hflip=1
	tsa_entry 0x0D3, hflip=1
	tsa_entry 0x0D2, hflip=1
	tsa_entry 0x0D1, hflip=1
	tsa_entry 0x0D0, hflip=1
	tsa_entry 0x0CF, hflip=1
	tsa_entry 0x0CE, hflip=1
	tsa_entry 0x0CD, hflip=1
	tsa_entry 0x0CC, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
