	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x31D, pal=1
	tsa_entry 0x127, pal=1
	tsa_entry 0x08F, pal=1, hflip=1
	tsa_entry 0x08E, pal=1, hflip=1
	tsa_entry 0x11B, pal=1
	tsa_entry 0x12A
	tsa_entry 0x12B
	tsa_entry 0x12C
	tsa_entry 0x12D
	tsa_entry 0x12C
	tsa_entry 0x12D
	tsa_entry 0x12C
	tsa_entry 0x12C, hflip=1
	tsa_entry 0x12D, hflip=1
	tsa_entry 0x12C, hflip=1
	tsa_entry 0x12D, hflip=1
	tsa_entry 0x12C, hflip=1
	tsa_entry 0x12B, hflip=1
	tsa_entry 0x12A, hflip=1
	tsa_entry 0x10F, pal=1, hflip=1
	tsa_entry 0x10E, pal=1, hflip=1
	tsa_entry 0x0CD, pal=1, hflip=1
	tsa_entry 0x114, pal=1
	tsa_entry 0x079, pal=1
	tsa_entry 0x07A, pal=1
	tsa_entry 0x115, pal=1
	tsa_entry 0x116, pal=1
	tsa_entry 0x10B, pal=1
	tsa_entry 0x117, pal=1
	tsa_entry 0x118, pal=1
	tsa_entry 0x119, pal=1
	tsa_entry 0x08F, pal=1, hflip=1
	tsa_entry 0x136, pal=1
	tsa_entry 0x137, pal=1
	tsa_entry 0x138, pal=1
	tsa_entry 0x139
	tsa_entry 0x13A
	tsa_entry 0x12D
	tsa_entry 0x12C
	tsa_entry 0x12D
	tsa_entry 0x12C
	tsa_entry 0x12C
	tsa_entry 0x12C, hflip=1
	tsa_entry 0x12C, hflip=1
	tsa_entry 0x12D, hflip=1
	tsa_entry 0x12C, hflip=1
	tsa_entry 0x12D, hflip=1
	tsa_entry 0x13A, hflip=1
	tsa_entry 0x139, hflip=1
	tsa_entry 0x138, pal=1, hflip=1
	tsa_entry 0x137, pal=1, hflip=1
	tsa_entry 0x136, pal=1, hflip=1
	tsa_entry 0x13B, pal=1
	tsa_entry 0x069, pal=1
	tsa_entry 0x06A, pal=1
	tsa_entry 0x13C, pal=1
	tsa_entry 0x13D, pal=1
	tsa_entry 0x134, pal=1
	tsa_entry 0x13E, pal=1
	tsa_entry 0x13F, pal=1
	tsa_entry 0x140, pal=1
	tsa_entry 0x0CD, pal=1
	tsa_entry 0x127, pal=1
	tsa_entry 0x128, pal=1
	tsa_entry 0x129, pal=1
	tsa_entry 0x12A
	tsa_entry 0x12B
	tsa_entry 0x12C
	tsa_entry 0x12D
	tsa_entry 0x12C
	tsa_entry 0x12D
	tsa_entry 0x12C
	tsa_entry 0x12C, hflip=1
	tsa_entry 0x12D, hflip=1
	tsa_entry 0x12C, hflip=1
	tsa_entry 0x12D, hflip=1
	tsa_entry 0x12C, hflip=1
	tsa_entry 0x12B, hflip=1
	tsa_entry 0x12A, hflip=1
	tsa_entry 0x129, pal=1, hflip=1
	tsa_entry 0x128, pal=1, hflip=1
	tsa_entry 0x127, pal=1, hflip=1
	tsa_entry 0x12E, pal=1
	tsa_entry 0x12F, pal=1
	tsa_entry 0x130, pal=1
	tsa_entry 0x131, pal=1
	tsa_entry 0x132, pal=1
	tsa_entry 0x133, pal=1
	tsa_entry 0x134, pal=1
	tsa_entry 0x133, pal=1
	tsa_entry 0x135, pal=1
	tsa_entry 0x100, pal=1
	tsa_entry 0x08F, pal=1, hflip=1
	tsa_entry 0x08E, pal=1, hflip=1
	tsa_entry 0x11B, pal=1
	tsa_entry 0x11C
	tsa_entry 0x11D
	tsa_entry 0x11E
	tsa_entry 0x11E
	tsa_entry 0x11E
	tsa_entry 0x11E
	tsa_entry 0x11E
	tsa_entry 0x11E, hflip=1
	tsa_entry 0x11E, hflip=1
	tsa_entry 0x11E, hflip=1
	tsa_entry 0x11E, hflip=1
	tsa_entry 0x11E, hflip=1
	tsa_entry 0x11D, hflip=1
	tsa_entry 0x11C, hflip=1
	tsa_entry 0x11B, pal=1, hflip=1
	tsa_entry 0x08E, pal=1
	tsa_entry 0x08F, pal=1
	tsa_entry 0x11F, pal=1
	tsa_entry 0x120, pal=1
	tsa_entry 0x121, pal=1
	tsa_entry 0x122, pal=1
	tsa_entry 0x123, pal=1
	tsa_entry 0x10B, pal=1, vflip=1
	tsa_entry 0x124, pal=1
	tsa_entry 0x125, pal=1
	tsa_entry 0x126, pal=1
	tsa_entry 0x05A, pal=1
	tsa_entry 0x0CD, pal=1
	tsa_entry 0x10E, pal=1
	tsa_entry 0x10F, pal=1
	tsa_entry 0x110
	tsa_entry 0x111
	tsa_entry 0x112
	tsa_entry 0x112
	tsa_entry 0x113
	tsa_entry 0x112
	tsa_entry 0x113
	tsa_entry 0x113, hflip=1
	tsa_entry 0x112, hflip=1
	tsa_entry 0x113, hflip=1
	tsa_entry 0x112, hflip=1
	tsa_entry 0x112, hflip=1
	tsa_entry 0x111, hflip=1
	tsa_entry 0x110, hflip=1
	tsa_entry 0x10F, pal=1, hflip=1
	tsa_entry 0x10E, pal=1, hflip=1
	tsa_entry 0x0CD, pal=1, hflip=1
	tsa_entry 0x114, pal=1
	tsa_entry 0x079, pal=1
	tsa_entry 0x07A, pal=1
	tsa_entry 0x115, pal=1
	tsa_entry 0x116, pal=1
	tsa_entry 0x10B, pal=1
	tsa_entry 0x117, pal=1
	tsa_entry 0x118, pal=1
	tsa_entry 0x119, pal=1
	tsa_entry 0x054, pal=1
	tsa_entry 0x100, pal=1
	tsa_entry 0x101, pal=1
	tsa_entry 0x102, pal=1
	tsa_entry 0x103
	tsa_entry 0x104
	tsa_entry 0x0F5
	tsa_entry 0x0F5
	tsa_entry 0x0F5
	tsa_entry 0x0F5
	tsa_entry 0x0F5
	tsa_entry 0x0F5, hflip=1
	tsa_entry 0x0F5, hflip=1
	tsa_entry 0x0F5, hflip=1
	tsa_entry 0x0F5, hflip=1
	tsa_entry 0x0F5, hflip=1
	tsa_entry 0x104, hflip=1
	tsa_entry 0x103, hflip=1
	tsa_entry 0x090, pal=1
	tsa_entry 0x091, pal=1
	tsa_entry 0x100, pal=1, hflip=1
	tsa_entry 0x105, pal=1
	tsa_entry 0x106, pal=1
	tsa_entry 0x107, pal=1
	tsa_entry 0x108, pal=1
	tsa_entry 0x109, pal=1
	tsa_entry 0x0FB, pal=1
	tsa_entry 0x10A, pal=1
	tsa_entry 0x10B, pal=1
	tsa_entry 0x10C, pal=1
	tsa_entry 0x03B, pal=1
	tsa_entry 0x0F0, pal=1
	tsa_entry 0x0F1, pal=1
	tsa_entry 0x0F2, pal=1
	tsa_entry 0x0F3
	tsa_entry 0x0F4
	tsa_entry 0x0D2
	tsa_entry 0x0F5
	tsa_entry 0x0D2
	tsa_entry 0x0D2
	tsa_entry 0x0D2
	tsa_entry 0x0D2, hflip=1
	tsa_entry 0x0D2, hflip=1
	tsa_entry 0x0D2, hflip=1
	tsa_entry 0x0F5, hflip=1
	tsa_entry 0x0D2, hflip=1
	tsa_entry 0x0F4, hflip=1
	tsa_entry 0x0F3, hflip=1
	tsa_entry 0x07C, pal=1, hflip=1
	tsa_entry 0x07B, pal=1, hflip=1
	tsa_entry 0x0F0, pal=1, hflip=1
	tsa_entry 0x0F6, pal=1
	tsa_entry 0x0F7, pal=1
	tsa_entry 0x0F8, pal=1
	tsa_entry 0x0F9, pal=1
	tsa_entry 0x0FA, pal=1
	tsa_entry 0x0FB, pal=1
	tsa_entry 0x0FC, pal=1
	tsa_entry 0x0FD, pal=1
	tsa_entry 0x0FE, pal=1
	tsa_entry 0x06B, pal=1
	tsa_entry 0x08F, pal=1, hflip=1
	tsa_entry 0x0DE, pal=1
	tsa_entry 0x0DF, pal=1
	tsa_entry 0x0E0
	tsa_entry 0x0E1
	tsa_entry 0x0E2
	tsa_entry 0x0E3
	tsa_entry 0x0E4
	tsa_entry 0x0E4
	tsa_entry 0x0E4
	tsa_entry 0x0E4, hflip=1
	tsa_entry 0x0E4, hflip=1
	tsa_entry 0x0E4, hflip=1
	tsa_entry 0x0E3, hflip=1
	tsa_entry 0x0E2, hflip=1
	tsa_entry 0x0E1, hflip=1
	tsa_entry 0x0E0, hflip=1
	tsa_entry 0x091, pal=1, hflip=1
	tsa_entry 0x090, pal=1, hflip=1
	tsa_entry 0x0E5, pal=1
	tsa_entry 0x0E6, pal=1
	tsa_entry 0x0E7, pal=1
	tsa_entry 0x0E8, pal=1
	tsa_entry 0x0E9, pal=1
	tsa_entry 0x0EA, pal=1
	tsa_entry 0x0EB, pal=1
	tsa_entry 0x0EC, pal=1
	tsa_entry 0x0ED, pal=1
	tsa_entry 0x0EE, pal=1
	tsa_entry 0x0CC, pal=1
	tsa_entry 0x0CD, pal=1
	tsa_entry 0x090, pal=1
	tsa_entry 0x091, pal=1
	tsa_entry 0x0CE, pal=1
	tsa_entry 0x0CF
	tsa_entry 0x0D0
	tsa_entry 0x0D1
	tsa_entry 0x0D2
	tsa_entry 0x0D2
	tsa_entry 0x0D3
	tsa_entry 0x0D3, hflip=1
	tsa_entry 0x0D2, hflip=1
	tsa_entry 0x0D2, hflip=1
	tsa_entry 0x0D1, hflip=1
	tsa_entry 0x0D0, hflip=1
	tsa_entry 0x0CF, hflip=1
	tsa_entry 0x0CE, pal=1, hflip=1
	tsa_entry 0x090, pal=1
	tsa_entry 0x091, pal=1
	tsa_entry 0x0D4, pal=1
	tsa_entry 0x0CC, pal=1, hflip=1
	tsa_entry 0x0D5, pal=1
	tsa_entry 0x0D6, pal=1
	tsa_entry 0x0D7, pal=1
	tsa_entry 0x0D8, pal=1
	tsa_entry 0x0D9, pal=1
	tsa_entry 0x0DA, pal=1
	tsa_entry 0x0DB, pal=1
	tsa_entry 0x0DC, pal=1
	tsa_entry 0x0BA, pal=1
	tsa_entry 0x0BB, pal=1
	tsa_entry 0x07B, pal=1
	tsa_entry 0x07C, pal=1
	tsa_entry 0x0BC, pal=1
	tsa_entry 0x0BD, pal=1
	tsa_entry 0x0BE
	tsa_entry 0x0BF
	tsa_entry 0x0C0
	tsa_entry 0x0C1
	tsa_entry 0x0C2
	tsa_entry 0x0C2, hflip=1
	tsa_entry 0x0C1, hflip=1
	tsa_entry 0x0C0, hflip=1
	tsa_entry 0x0BF, hflip=1
	tsa_entry 0x0BE, hflip=1
	tsa_entry 0x0BD, pal=1, hflip=1
	tsa_entry 0x0BC, pal=1, hflip=1
	tsa_entry 0x07C, pal=1, hflip=1
	tsa_entry 0x07B, pal=1, hflip=1
	tsa_entry 0x0BB, pal=1, hflip=1
	tsa_entry 0x0BA, pal=1, hflip=1
	tsa_entry 0x0C3, pal=1
	tsa_entry 0x0C4, pal=1
	tsa_entry 0x0C5, pal=1
	tsa_entry 0x0C6, pal=1
	tsa_entry 0x0C7, pal=1
	tsa_entry 0x0C8, pal=1
	tsa_entry 0x0C9, pal=1
	tsa_entry 0x0CA, pal=1
	tsa_entry 0x0A4, pal=1
	tsa_entry 0x0A4, pal=1, hflip=1
	tsa_entry 0x0A5, pal=1
	tsa_entry 0x0A6, pal=1
	tsa_entry 0x0A7, pal=1
	tsa_entry 0x0A8, pal=1
	tsa_entry 0x0A9
	tsa_entry 0x0AA
	tsa_entry 0x0AB
	tsa_entry 0x0AC
	tsa_entry 0x0AD
	tsa_entry 0x0AD, hflip=1
	tsa_entry 0x0AC, hflip=1
	tsa_entry 0x0AB, hflip=1
	tsa_entry 0x0AA, hflip=1
	tsa_entry 0x0AE
	tsa_entry 0x0AF, pal=1
	tsa_entry 0x0A7, pal=1, hflip=1
	tsa_entry 0x0A6, pal=1, hflip=1
	tsa_entry 0x0A5, pal=1, hflip=1
	tsa_entry 0x0A4, pal=1
	tsa_entry 0x0B0, pal=1
	tsa_entry 0x0B1, pal=1
	tsa_entry 0x0B2, pal=1
	tsa_entry 0x0B3, pal=1
	tsa_entry 0x0B4, pal=1
	tsa_entry 0x0B5, pal=1
	tsa_entry 0x0B6, pal=1
	tsa_entry 0x0B7, pal=1
	tsa_entry 0x0B8, pal=1
	tsa_entry 0x08E, pal=1
	tsa_entry 0x08F, pal=1
	tsa_entry 0x090, pal=1
	tsa_entry 0x091, pal=1
	tsa_entry 0x06B, pal=1
	tsa_entry 0x092, pal=1
	tsa_entry 0x093, pal=1
	tsa_entry 0x094
	tsa_entry 0x095
	tsa_entry 0x096
	tsa_entry 0x097
	tsa_entry 0x097, hflip=1
	tsa_entry 0x096, hflip=1
	tsa_entry 0x095, hflip=1
	tsa_entry 0x098
	tsa_entry 0x055, pal=1
	tsa_entry 0x059, pal=1
	tsa_entry 0x06B, pal=1, hflip=1
	tsa_entry 0x090, pal=1
	tsa_entry 0x091, pal=1
	tsa_entry 0x099, pal=1
	tsa_entry 0x09A, pal=1
	tsa_entry 0x09B, pal=1
	tsa_entry 0x09C, pal=1
	tsa_entry 0x09D, pal=1
	tsa_entry 0x09E, pal=1
	tsa_entry 0x09F, pal=1
	tsa_entry 0x0A0, pal=1
	tsa_entry 0x0A1, pal=1
	tsa_entry 0x0A2, pal=1
	tsa_entry 0x079, pal=1
	tsa_entry 0x07A, pal=1
	tsa_entry 0x07B, pal=1
	tsa_entry 0x07C, pal=1
	tsa_entry 0x07D, pal=1
	tsa_entry 0x05B, pal=1
	tsa_entry 0x07E, pal=1
	tsa_entry 0x07F, pal=1
	tsa_entry 0x080
	tsa_entry 0x081
	tsa_entry 0x082
	tsa_entry 0x082, hflip=1
	tsa_entry 0x081, hflip=1
	tsa_entry 0x080, hflip=1
	tsa_entry 0x055, pal=1
	tsa_entry 0x059, pal=1
	tsa_entry 0x05A, pal=1
	tsa_entry 0x083, pal=1
	tsa_entry 0x07C, pal=1, hflip=1
	tsa_entry 0x07B, pal=1, hflip=1
	tsa_entry 0x058, pal=1, hflip=1
	tsa_entry 0x084, pal=1
	tsa_entry 0x085, pal=1
	tsa_entry 0x086, pal=1
	tsa_entry 0x087, pal=1
	tsa_entry 0x088, pal=1
	tsa_entry 0x089, pal=1
	tsa_entry 0x08A, pal=1
	tsa_entry 0x08B, pal=1
	tsa_entry 0x08C, pal=1
	tsa_entry 0x069, pal=1
	tsa_entry 0x06A, pal=1
	tsa_entry 0x057, pal=1, hflip=1
	tsa_entry 0x056, pal=1, hflip=1
	tsa_entry 0x06B, pal=1
	tsa_entry 0x05A, pal=1
	tsa_entry 0x054, pal=1
	tsa_entry 0x055, pal=1
	tsa_entry 0x059, pal=1
	tsa_entry 0x06C, pal=1
	tsa_entry 0x054, pal=1
	tsa_entry 0x055, pal=1
	tsa_entry 0x059, pal=1
	tsa_entry 0x05A, pal=1
	tsa_entry 0x054, pal=1
	tsa_entry 0x055, pal=1
	tsa_entry 0x059, pal=1
	tsa_entry 0x06D, pal=1
	tsa_entry 0x056, pal=1
	tsa_entry 0x057, pal=1
	tsa_entry 0x06E, pal=1
	tsa_entry 0x06F, pal=1
	tsa_entry 0x070, pal=1
	tsa_entry 0x071, pal=1
	tsa_entry 0x072, pal=1
	tsa_entry 0x073, pal=1
	tsa_entry 0x074, pal=1
	tsa_entry 0x075, pal=1
	tsa_entry 0x076, pal=1
	tsa_entry 0x077, pal=1
	tsa_entry 0x054, pal=1
	tsa_entry 0x055, pal=1
	tsa_entry 0x056, pal=1
	tsa_entry 0x057, pal=1
	tsa_entry 0x058, pal=1
	tsa_entry 0x059, pal=1
	tsa_entry 0x05A, pal=1
	tsa_entry 0x05B, pal=1
	tsa_entry 0x043, pal=1
	tsa_entry 0x044, pal=1
	tsa_entry 0x05C, pal=1
	tsa_entry 0x059, pal=1
	tsa_entry 0x05A, pal=1
	tsa_entry 0x054, pal=1
	tsa_entry 0x055, pal=1
	tsa_entry 0x054, pal=1
	tsa_entry 0x05A, pal=1
	tsa_entry 0x05D, pal=1
	tsa_entry 0x03D, pal=1
	tsa_entry 0x03E, pal=1
	tsa_entry 0x05E, pal=1
	tsa_entry 0x05F, pal=1
	tsa_entry 0x060, pal=1
	tsa_entry 0x061, pal=1
	tsa_entry 0x062, pal=1
	tsa_entry 0x063, pal=1
	tsa_entry 0x064, pal=1
	tsa_entry 0x065, pal=1
	tsa_entry 0x066, pal=1
	tsa_entry 0x067, pal=1
	tsa_entry 0x03B, pal=1
	tsa_entry 0x03C, pal=1
	tsa_entry 0x03D, pal=1
	tsa_entry 0x03E, pal=1
	tsa_entry 0x03F
	tsa_entry 0x040, pal=1
	tsa_entry 0x041, pal=1
	tsa_entry 0x042
	tsa_entry 0x043, pal=1
	tsa_entry 0x044, pal=1
	tsa_entry 0x045, pal=1
	tsa_entry 0x046, pal=1
	tsa_entry 0x047, pal=1
	tsa_entry 0x03B, pal=1
	tsa_entry 0x03C, pal=1
	tsa_entry 0x048, pal=1
	tsa_entry 0x049, pal=1
	tsa_entry 0x04A, pal=1
	tsa_entry 0x037, pal=1
	tsa_entry 0x04B, pal=1
	tsa_entry 0x037, pal=1
	tsa_entry 0x04B, pal=1
	tsa_entry 0x04C, pal=1
	tsa_entry 0x04D, pal=1
	tsa_entry 0x04E, pal=1
	tsa_entry 0x04F, pal=1
	tsa_entry 0x050, pal=1
	tsa_entry 0x051, pal=1
	tsa_entry 0x052, pal=1
	tsa_entry 0x021
	tsa_entry 0x011, pal=1
	tsa_entry 0x012, pal=1
	tsa_entry 0x011, pal=1
	tsa_entry 0x013, pal=1
	tsa_entry 0x014, pal=1
	tsa_entry 0x031, pal=1
	tsa_entry 0x032
	tsa_entry 0x012, pal=1
	tsa_entry 0x011, pal=1
	tsa_entry 0x013, pal=1
	tsa_entry 0x014, pal=1
	tsa_entry 0x033
	tsa_entry 0x02C, pal=1
	tsa_entry 0x012, pal=1
	tsa_entry 0x011, pal=1
	tsa_entry 0x034, pal=1
	tsa_entry 0x035
	tsa_entry 0x036
	tsa_entry 0x02B
	tsa_entry 0x02C, pal=1
	tsa_entry 0x02B
	tsa_entry 0x02C, pal=1
	tsa_entry 0x012, pal=1
	tsa_entry 0x011, pal=1
	tsa_entry 0x037, pal=1
	tsa_entry 0x038, pal=1
	tsa_entry 0x039, pal=1
	tsa_entry 0x03A
	tsa_entry 0x00E
	tsa_entry 0x00F
	tsa_entry 0x000, pal=1
	tsa_entry 0x001, pal=1
	tsa_entry 0x000, pal=1
	tsa_entry 0x002, pal=1
	tsa_entry 0x003, pal=1
	tsa_entry 0x023
	tsa_entry 0x024
	tsa_entry 0x001, pal=1
	tsa_entry 0x000, pal=1
	tsa_entry 0x002, pal=1
	tsa_entry 0x003, pal=1
	tsa_entry 0x025, pal=1
	tsa_entry 0x007, pal=1
	tsa_entry 0x001, pal=1
	tsa_entry 0x000, pal=1
	tsa_entry 0x026, pal=1
	tsa_entry 0x027, pal=1
	tsa_entry 0x028
	tsa_entry 0x029, pal=1
	tsa_entry 0x02A, pal=1
	tsa_entry 0x000, pal=1
	tsa_entry 0x01E, pal=1
	tsa_entry 0x003, pal=1
	tsa_entry 0x00B, pal=1
	tsa_entry 0x02B
	tsa_entry 0x02C, pal=1
	tsa_entry 0x02D
	tsa_entry 0x02E
	tsa_entry 0x02F
	tsa_entry 0x020
	tsa_entry 0x011, pal=1
	tsa_entry 0x012, pal=1
	tsa_entry 0x011, pal=1
	tsa_entry 0x013, pal=1
	tsa_entry 0x014, pal=1
	tsa_entry 0x015, pal=1
	tsa_entry 0x016, pal=1
	tsa_entry 0x012, pal=1
	tsa_entry 0x011, pal=1
	tsa_entry 0x013, pal=1
	tsa_entry 0x014, pal=1
	tsa_entry 0x017, pal=1
	tsa_entry 0x018, pal=1
	tsa_entry 0x012, pal=1
	tsa_entry 0x011, pal=1
	tsa_entry 0x013, pal=1
	tsa_entry 0x019, pal=1
	tsa_entry 0x01A
	tsa_entry 0x01B
	tsa_entry 0x01C, pal=1
	tsa_entry 0x00C, pal=1
	tsa_entry 0x01C, pal=1
	tsa_entry 0x00C, pal=1
	tsa_entry 0x01D, pal=1
	tsa_entry 0x018, pal=1
	tsa_entry 0x01E, pal=1
	tsa_entry 0x01F, pal=1
	tsa_entry 0x00E
	tsa_entry 0x020
	tsa_entry 0x021
	tsa_entry 0x000, pal=1
	tsa_entry 0x001, pal=1
	tsa_entry 0x000, pal=1
	tsa_entry 0x002, pal=1
	tsa_entry 0x003, pal=1
	tsa_entry 0x004, pal=1
	tsa_entry 0x005, pal=1
	tsa_entry 0x001, pal=1
	tsa_entry 0x000, pal=1
	tsa_entry 0x002, pal=1
	tsa_entry 0x003, pal=1
	tsa_entry 0x006, pal=1
	tsa_entry 0x007, pal=1
	tsa_entry 0x001, pal=1
	tsa_entry 0x000, pal=1
	tsa_entry 0x002, pal=1
	tsa_entry 0x003, pal=1
	tsa_entry 0x008, pal=1
	tsa_entry 0x009
	tsa_entry 0x001, pal=1
	tsa_entry 0x00A, pal=1
	tsa_entry 0x002, pal=1
	tsa_entry 0x00A, pal=1
	tsa_entry 0x00B, pal=1
	tsa_entry 0x007, pal=1
	tsa_entry 0x001, pal=1
	tsa_entry 0x00C, pal=1
	tsa_entry 0x00D
	tsa_entry 0x00E
	tsa_entry 0x00F
