	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x31D, pal=1
	tsa_entry 0x1E9, pal=4, hflip=1
	tsa_entry 0x1E8, pal=4, hflip=1
	tsa_entry 0x1E7, pal=4, hflip=1
	tsa_entry 0x1E6, pal=5, hflip=1
	tsa_entry 0x1E5, pal=5, hflip=1
	tsa_entry 0x1E4, pal=4, hflip=1
	tsa_entry 0x1E1, pal=4, hflip=1
	tsa_entry 0x1DF, pal=4, hflip=1
	tsa_entry 0x1E1, pal=4, hflip=1
	tsa_entry 0x1E1, pal=4, hflip=1
	tsa_entry 0x1DF, pal=4, hflip=1
	tsa_entry 0x1E0, pal=5, hflip=1
	tsa_entry 0x1E5, pal=5, hflip=1
	tsa_entry 0x1E4, pal=4, hflip=1
	tsa_entry 0x1E1, pal=4, hflip=1
	tsa_entry 0x1DF, pal=4, hflip=1
	tsa_entry 0x1E0, pal=5, hflip=1
	tsa_entry 0x1E2, pal=4, hflip=1
	tsa_entry 0x1E2, pal=4, hflip=1
	tsa_entry 0x1E4, pal=4, hflip=1
	tsa_entry 0x1E1, pal=4, hflip=1
	tsa_entry 0x1E4, pal=4, hflip=1
	tsa_entry 0x1E1, pal=4, hflip=1
	tsa_entry 0x1E3, pal=4, hflip=1
	tsa_entry 0x1E2, pal=4, hflip=1
	tsa_entry 0x1E2, pal=4, hflip=1
	tsa_entry 0x1E1, pal=4, hflip=1
	tsa_entry 0x1DF, pal=4, hflip=1
	tsa_entry 0x1E0, pal=5, hflip=1
	tsa_entry 0x1DF, pal=4, hflip=1
	tsa_entry 0x1DE, pal=5, hflip=1
	tsa_entry 0x1DD, pal=5, hflip=1
	tsa_entry 0x1DC, pal=5, hflip=1
	tsa_entry 0x1DA, pal=5, hflip=1
	tsa_entry 0x1D9, pal=5, hflip=1
	tsa_entry 0x1D8, pal=5, hflip=1
	tsa_entry 0x1D7, pal=5, hflip=1
	tsa_entry 0x1D5, pal=5, hflip=1
	tsa_entry 0x1D7, pal=5, hflip=1
	tsa_entry 0x1D7, pal=5, hflip=1
	tsa_entry 0x1D5, pal=5, hflip=1
	tsa_entry 0x1D6, pal=5, hflip=1
	tsa_entry 0x1D9, pal=5, hflip=1
	tsa_entry 0x1D8, pal=5, hflip=1
	tsa_entry 0x1D7, pal=5, hflip=1
	tsa_entry 0x1DB, pal=5, hflip=1
	tsa_entry 0x1D6, pal=5, hflip=1
	tsa_entry 0x1DA, pal=5, hflip=1
	tsa_entry 0x1D9, pal=5, hflip=1
	tsa_entry 0x1D8, pal=5, hflip=1
	tsa_entry 0x1D7, pal=5, hflip=1
	tsa_entry 0x1D8, pal=5, hflip=1
	tsa_entry 0x1D7, pal=5, hflip=1
	tsa_entry 0x1DA, pal=5, hflip=1
	tsa_entry 0x1D9, pal=5, hflip=1
	tsa_entry 0x1D8, pal=5, hflip=1
	tsa_entry 0x1D7, pal=5, hflip=1
	tsa_entry 0x1D5, pal=5, hflip=1
	tsa_entry 0x1D6, pal=5, hflip=1
	tsa_entry 0x1D5, pal=5, hflip=1
	tsa_entry 0x1D4, pal=5, hflip=1
	tsa_entry 0x1D3, pal=5, hflip=1
	tsa_entry 0x1D2, pal=5, hflip=1
	tsa_entry 0x1D1, pal=5, hflip=1
	tsa_entry 0x1D0, pal=5, hflip=1
	tsa_entry 0x1CF, pal=5, hflip=1
	tsa_entry 0x1CE, pal=5, hflip=1
	tsa_entry 0x1CD, pal=5, hflip=1
	tsa_entry 0x1CC, pal=5, hflip=1
	tsa_entry 0x1CB, pal=5, hflip=1
	tsa_entry 0x1CA, pal=5, hflip=1
	tsa_entry 0x1C9, pal=4, hflip=1
	tsa_entry 0x1C8, pal=4, hflip=1
	tsa_entry 0x1C7, pal=4, hflip=1
	tsa_entry 0x1C6, pal=3, hflip=1
	tsa_entry 0x1C5, pal=3, hflip=1
	tsa_entry 0x1C4, pal=4, hflip=1
	tsa_entry 0x1C3, pal=5, hflip=1
	tsa_entry 0x1BF, pal=5, hflip=1
	tsa_entry 0x1BF, pal=5, hflip=1
	tsa_entry 0x1C2, pal=5, hflip=1
	tsa_entry 0x1C0, pal=5, hflip=1
	tsa_entry 0x1BF, pal=5, hflip=1
	tsa_entry 0x1C2, pal=5, hflip=1
	tsa_entry 0x1C1, pal=5, hflip=1
	tsa_entry 0x1C0, pal=5, hflip=1
	tsa_entry 0x1BF, pal=5, hflip=1
	tsa_entry 0x1BE, pal=5, hflip=1
	tsa_entry 0x1BD, pal=5, hflip=1
	tsa_entry 0x1BC, pal=5, hflip=1
	tsa_entry 0x1BB, pal=5, hflip=1
	tsa_entry 0x1BA, pal=5, hflip=1
	tsa_entry 0x1B9, pal=5, hflip=1
	tsa_entry 0x1B8, pal=5, hflip=1
	tsa_entry 0x1B7, pal=2, hflip=1
	tsa_entry 0x10D, pal=1, hflip=1
	tsa_entry 0x1B6, pal=2, hflip=1
	tsa_entry 0x1B5, pal=4, hflip=1
	tsa_entry 0x1B4, pal=4, hflip=1
	tsa_entry 0x1B3, pal=4, hflip=1
	tsa_entry 0x1B2, pal=4, hflip=1
	tsa_entry 0x1B1, pal=4, hflip=1
	tsa_entry 0x1B0, pal=1, hflip=1
	tsa_entry 0x1AF, pal=1, hflip=1
	tsa_entry 0x0E7, pal=1, hflip=1
	tsa_entry 0x0E6, pal=1, hflip=1
	tsa_entry 0x1AE, pal=3, hflip=1
	tsa_entry 0x1AD, pal=3, hflip=1
	tsa_entry 0x1AC, pal=3, hflip=1
	tsa_entry 0x1AB, pal=3, hflip=1
	tsa_entry 0x1AA, pal=3, hflip=1
	tsa_entry 0x1A9, pal=3, hflip=1
	tsa_entry 0x1A8, pal=3, hflip=1
	tsa_entry 0x1A7, pal=3, hflip=1
	tsa_entry 0x1A6, pal=3, hflip=1
	tsa_entry 0x1A5, pal=3, hflip=1
	tsa_entry 0x1A4, pal=3, hflip=1
	tsa_entry 0x1A3, pal=3, hflip=1
	tsa_entry 0x1A2, pal=3, hflip=1
	tsa_entry 0x1A1, pal=3, hflip=1
	tsa_entry 0x1A0, pal=5, hflip=1
	tsa_entry 0x19F, pal=5, hflip=1
	tsa_entry 0x19E, pal=5, hflip=1
	tsa_entry 0x19D, pal=5, hflip=1
	tsa_entry 0x19C, pal=2, hflip=1
	tsa_entry 0x19B, pal=1, hflip=1
	tsa_entry 0x19A, pal=2, hflip=1
	tsa_entry 0x199, pal=4, hflip=1
	tsa_entry 0x199, pal=4, hflip=1
	tsa_entry 0x198, pal=4, hflip=1
	tsa_entry 0x197, pal=4, hflip=1
	tsa_entry 0x196, pal=4, hflip=1
	tsa_entry 0x195, pal=1, hflip=1
	tsa_entry 0x194, pal=1, hflip=1
	tsa_entry 0x0E7, pal=1, hflip=1
	tsa_entry 0x0E6, pal=1, hflip=1
	tsa_entry 0x193, pal=3, hflip=1
	tsa_entry 0x192, pal=1, hflip=1
	tsa_entry 0x191, pal=3, hflip=1
	tsa_entry 0x18B, pal=3
	tsa_entry 0x18C, pal=3
	tsa_entry 0x190, pal=3, hflip=1
	tsa_entry 0x18F, hflip=1
	tsa_entry 0x134, pal=3, hflip=1
	tsa_entry 0x133, pal=3, hflip=1
	tsa_entry 0x18E, hflip=1
	tsa_entry 0x18D, pal=3, hflip=1
	tsa_entry 0x18C, pal=3, hflip=1
	tsa_entry 0x18B, pal=3, hflip=1
	tsa_entry 0x18A, hflip=1
	tsa_entry 0x12C, pal=5, vflip=1
	tsa_entry 0x0F4, pal=2, hflip=1
	tsa_entry 0x189, pal=5, hflip=1
	tsa_entry 0x188, pal=5, hflip=1
	tsa_entry 0x187, pal=5, hflip=1
	tsa_entry 0x186, pal=4, hflip=1
	tsa_entry 0x185, pal=4, hflip=1
	tsa_entry 0x184, pal=4, hflip=1
	tsa_entry 0x183, pal=4, hflip=1
	tsa_entry 0x182, pal=4, hflip=1
	tsa_entry 0x181, pal=4, hflip=1
	tsa_entry 0x180, pal=4, hflip=1
	tsa_entry 0x17F, pal=4, hflip=1
	tsa_entry 0x17E, pal=1, hflip=1
	tsa_entry 0x17D, pal=1, hflip=1
	tsa_entry 0x13B, pal=1, hflip=1
	tsa_entry 0x17C, pal=3, hflip=1
	tsa_entry 0x17B, pal=3, hflip=1
	tsa_entry 0x17A, pal=3, hflip=1
	tsa_entry 0x179, pal=1, hflip=1
	tsa_entry 0x178, pal=1, hflip=1
	tsa_entry 0x115, pal=3, hflip=1
	tsa_entry 0x177, pal=3, hflip=1
	tsa_entry 0x118, pal=3, hflip=1
	tsa_entry 0x117, pal=4, hflip=1
	tsa_entry 0x176, hflip=1
	tsa_entry 0x115, pal=3, hflip=1
	tsa_entry 0x175, pal=3, hflip=1
	tsa_entry 0x174, pal=4, hflip=1
	tsa_entry 0x173, hflip=1
	tsa_entry 0x172, pal=5, hflip=1
	tsa_entry 0x171, pal=5, hflip=1
	tsa_entry 0x170, pal=5, hflip=1
	tsa_entry 0x16F, pal=5, hflip=1
	tsa_entry 0x16E, pal=2, hflip=1
	tsa_entry 0x10D, pal=1, hflip=1
	tsa_entry 0x10C, pal=2, hflip=1
	tsa_entry 0x10B, pal=4, hflip=1
	tsa_entry 0x10A, pal=1, hflip=1
	tsa_entry 0x0EC, pal=4, hflip=1
	tsa_entry 0x16D, pal=1, hflip=1
	tsa_entry 0x0EA, pal=1, hflip=1
	tsa_entry 0x16C, pal=4, hflip=1
	tsa_entry 0x16B, pal=1, hflip=1
	tsa_entry 0x0E7, pal=1, hflip=1
	tsa_entry 0x0E6, pal=1, hflip=1
	tsa_entry 0x16A, pal=3, hflip=1
	tsa_entry 0x169, pal=3, hflip=1
	tsa_entry 0x168, hflip=1
	tsa_entry 0x167, pal=3, hflip=1
	tsa_entry 0x166, pal=3, hflip=1
	tsa_entry 0x115, pal=3, hflip=1
	tsa_entry 0x165, pal=3, hflip=1
	tsa_entry 0x0FC, pal=4, hflip=1
	tsa_entry 0x0FB, pal=4, hflip=1
	tsa_entry 0x164, hflip=1
	tsa_entry 0x115, pal=3, hflip=1
	tsa_entry 0x163, pal=3, hflip=1
	tsa_entry 0x162, pal=3, hflip=1
	tsa_entry 0x161, hflip=1
	tsa_entry 0x160, pal=5, hflip=1
	tsa_entry 0x15F, pal=5, hflip=1
	tsa_entry 0x15E, pal=5, hflip=1
	tsa_entry 0x15D, pal=5, hflip=1
	tsa_entry 0x15C, pal=2, hflip=1
	tsa_entry 0x0F0, hflip=1
	tsa_entry 0x0EF, pal=1, hflip=1
	tsa_entry 0x15B, pal=4, hflip=1
	tsa_entry 0x0ED, pal=1, hflip=1
	tsa_entry 0x0EC, pal=4, hflip=1
	tsa_entry 0x15A, pal=1, hflip=1
	tsa_entry 0x159, pal=1, hflip=1
	tsa_entry 0x158, pal=4, hflip=1
	tsa_entry 0x157, pal=1, hflip=1
	tsa_entry 0x0E7, pal=1, hflip=1
	tsa_entry 0x0E6, pal=1, hflip=1
	tsa_entry 0x156, pal=3, hflip=1
	tsa_entry 0x155, pal=3, hflip=1
	tsa_entry 0x154, pal=3, hflip=1
	tsa_entry 0x153, pal=3, hflip=1
	tsa_entry 0x152, pal=3, hflip=1
	tsa_entry 0x151, pal=3, hflip=1
	tsa_entry 0x150, hflip=1
	tsa_entry 0x14F, hflip=1
	tsa_entry 0x14E, hflip=1
	tsa_entry 0x14D, hflip=1
	tsa_entry 0x14C, pal=3, hflip=1
	tsa_entry 0x14B, pal=3, hflip=1
	tsa_entry 0x14A, pal=3, hflip=1
	tsa_entry 0x149, hflip=1
	tsa_entry 0x148, pal=5, hflip=1
	tsa_entry 0x147, pal=5, hflip=1
	tsa_entry 0x0F4, pal=2, hflip=1
	tsa_entry 0x110, pal=5, hflip=1
	tsa_entry 0x146, pal=2, hflip=1
	tsa_entry 0x145, pal=4, hflip=1
	tsa_entry 0x144, pal=4, hflip=1
	tsa_entry 0x143, pal=4, hflip=1
	tsa_entry 0x142, pal=1, hflip=1
	tsa_entry 0x141, pal=1, hflip=1
	tsa_entry 0x140, pal=1, hflip=1
	tsa_entry 0x13F, pal=4, hflip=1
	tsa_entry 0x13E, pal=4, hflip=1
	tsa_entry 0x13D, pal=4, hflip=1
	tsa_entry 0x13C, pal=1, hflip=1
	tsa_entry 0x13B, pal=1, hflip=1
	tsa_entry 0x13A, pal=3, hflip=1
	tsa_entry 0x139, pal=3, hflip=1
	tsa_entry 0x138, pal=3, hflip=1
	tsa_entry 0x137, pal=4, hflip=1
	tsa_entry 0x136, pal=1, hflip=1
	tsa_entry 0x115, pal=3, hflip=1
	tsa_entry 0x135, hflip=1
	tsa_entry 0x134, pal=3, hflip=1
	tsa_entry 0x133, pal=3, hflip=1
	tsa_entry 0x132, hflip=1
	tsa_entry 0x115, pal=3, hflip=1
	tsa_entry 0x131, hflip=1
	tsa_entry 0x130, pal=1, hflip=1
	tsa_entry 0x12F, pal=1, hflip=1
	tsa_entry 0x12E, pal=2, hflip=1
	tsa_entry 0x12D, pal=2, hflip=1
	tsa_entry 0x12C, pal=5, hflip=1
	tsa_entry 0x0B8, pal=2, hflip=1
	tsa_entry 0x12B, pal=2, hflip=1
	tsa_entry 0x12A, pal=2, hflip=1
	tsa_entry 0x129, pal=4, hflip=1
	tsa_entry 0x128, pal=4, hflip=1
	tsa_entry 0x127, pal=1, hflip=1
	tsa_entry 0x126, pal=4, hflip=1
	tsa_entry 0x125, pal=1, hflip=1
	tsa_entry 0x124, pal=1, hflip=1
	tsa_entry 0x123, pal=4, hflip=1
	tsa_entry 0x122, pal=4, hflip=1
	tsa_entry 0x121, pal=1, hflip=1
	tsa_entry 0x120, pal=1, hflip=1
	tsa_entry 0x11F, pal=3, hflip=1
	tsa_entry 0x11E, pal=3, hflip=1
	tsa_entry 0x11D, pal=3, hflip=1
	tsa_entry 0x11C, pal=3, hflip=1
	tsa_entry 0x11B, pal=3, hflip=1
	tsa_entry 0x11A, pal=3, hflip=1
	tsa_entry 0x119, pal=3, hflip=1
	tsa_entry 0x118, pal=3, hflip=1
	tsa_entry 0x117, pal=4, hflip=1
	tsa_entry 0x116, hflip=1
	tsa_entry 0x115, pal=3, hflip=1
	tsa_entry 0x114, pal=3, hflip=1
	tsa_entry 0x113, pal=3, hflip=1
	tsa_entry 0x112, hflip=1
	tsa_entry 0x111, pal=5, hflip=1
	tsa_entry 0x110, pal=5, hflip=1
	tsa_entry 0x0F4, pal=2, hflip=1
	tsa_entry 0x10F, pal=2, hflip=1
	tsa_entry 0x10E, pal=2, hflip=1
	tsa_entry 0x10D, pal=1, hflip=1
	tsa_entry 0x10C, pal=2, hflip=1
	tsa_entry 0x10B, pal=4, hflip=1
	tsa_entry 0x10A, pal=1, hflip=1
	tsa_entry 0x0EC, pal=4, hflip=1
	tsa_entry 0x109, pal=1, hflip=1
	tsa_entry 0x108, pal=1, hflip=1
	tsa_entry 0x107, pal=1, hflip=1
	tsa_entry 0x106, pal=1, hflip=1
	tsa_entry 0x105, pal=1, hflip=1
	tsa_entry 0x104, pal=1, hflip=1
	tsa_entry 0x103, pal=3, hflip=1
	tsa_entry 0x102, pal=1, hflip=1
	tsa_entry 0x101, pal=3, hflip=1
	tsa_entry 0x100, pal=3, hflip=1
	tsa_entry 0x0FF, pal=3, hflip=1
	tsa_entry 0x0FE, pal=3, hflip=1
	tsa_entry 0x0FD, pal=3, hflip=1
	tsa_entry 0x0FC, pal=4, hflip=1
	tsa_entry 0x0FB, pal=4, hflip=1
	tsa_entry 0x0FA, hflip=1
	tsa_entry 0x0F9, pal=3, hflip=1
	tsa_entry 0x0F8, pal=3, hflip=1
	tsa_entry 0x0F7, pal=3, hflip=1
	tsa_entry 0x0F6, hflip=1
	tsa_entry 0x0F5, pal=5, hflip=1
	tsa_entry 0x0F4, pal=2, hflip=1
	tsa_entry 0x0F3, pal=5, hflip=1
	tsa_entry 0x0F2, pal=2, hflip=1
	tsa_entry 0x0F1, pal=2, hflip=1
	tsa_entry 0x0F0, hflip=1
	tsa_entry 0x0EF, pal=1, hflip=1
	tsa_entry 0x0EE, pal=4, hflip=1
	tsa_entry 0x0ED, pal=1, hflip=1
	tsa_entry 0x0EC, pal=4, hflip=1
	tsa_entry 0x0EB, pal=1, hflip=1
	tsa_entry 0x0EA, pal=1, hflip=1
	tsa_entry 0x0E9, pal=1, hflip=1
	tsa_entry 0x0E8, pal=1, hflip=1
	tsa_entry 0x0E7, pal=1, hflip=1
	tsa_entry 0x0E6, pal=1, hflip=1
	tsa_entry 0x0E5, pal=3, hflip=1
	tsa_entry 0x0E4, pal=3, hflip=1
	tsa_entry 0x0E3, pal=3, hflip=1
	tsa_entry 0x0E2, pal=1, hflip=1
	tsa_entry 0x0E1, pal=3, hflip=1
	tsa_entry 0x0E0, pal=3, hflip=1
	tsa_entry 0x0DF, hflip=1
	tsa_entry 0x0DE, hflip=1
	tsa_entry 0x0DD, hflip=1
	tsa_entry 0x0DC, hflip=1
	tsa_entry 0x0DB, pal=3, hflip=1
	tsa_entry 0x0DA, pal=3, hflip=1
	tsa_entry 0x0D9, pal=3, hflip=1
	tsa_entry 0x0D8, hflip=1
	tsa_entry 0x0D7, pal=2, hflip=1
	tsa_entry 0x0D6, pal=2, hflip=1
	tsa_entry 0x0D5, pal=2, hflip=1
	tsa_entry 0x0D4, pal=3, hflip=1
	tsa_entry 0x0D3, pal=2, hflip=1
	tsa_entry 0x0D2, pal=4, hflip=1
	tsa_entry 0x0D1, pal=4, hflip=1
	tsa_entry 0x0D0, pal=4, hflip=1
	tsa_entry 0x0CF, pal=4, hflip=1
	tsa_entry 0x0CE, pal=4, hflip=1
	tsa_entry 0x0CD, pal=4, hflip=1
	tsa_entry 0x0CC, pal=1, hflip=1
	tsa_entry 0x0CB, pal=4, hflip=1
	tsa_entry 0x0CA, pal=4, hflip=1
	tsa_entry 0x0C9, pal=1, hflip=1
	tsa_entry 0x0C8, pal=1, hflip=1
	tsa_entry 0x0C7, pal=3, hflip=1
	tsa_entry 0x0C6, pal=3, hflip=1
	tsa_entry 0x0C5, pal=1, hflip=1
	tsa_entry 0x0C4, pal=1, hflip=1
	tsa_entry 0x0C3, pal=1, hflip=1
	tsa_entry 0x0C2, hflip=1
	tsa_entry 0x0C1, hflip=1
	tsa_entry 0x0C0, pal=3, hflip=1
	tsa_entry 0x0BF, pal=3, hflip=1
	tsa_entry 0x0BE, hflip=1
	tsa_entry 0x0BD, hflip=1
	tsa_entry 0x0BC, pal=1, hflip=1
	tsa_entry 0x0BB, pal=1, hflip=1
	tsa_entry 0x0BA, pal=1, hflip=1
	tsa_entry 0x0B9, pal=4, hflip=1
	tsa_entry 0x0B8, pal=2, hflip=1
	tsa_entry 0x0B7, pal=2, hflip=1
	tsa_entry 0x0B6, pal=2, hflip=1
	tsa_entry 0x0B5, pal=2, hflip=1
	tsa_entry 0x0B4, pal=1, hflip=1
	tsa_entry 0x0B3, pal=1, hflip=1
	tsa_entry 0x0B2, pal=2, hflip=1
	tsa_entry 0x0B1, pal=2, hflip=1
	tsa_entry 0x0B0, pal=2, hflip=1
	tsa_entry 0x0AF, pal=2, hflip=1
	tsa_entry 0x0AE, pal=4, hflip=1
	tsa_entry 0x0AD, pal=4, hflip=1
	tsa_entry 0x0AC, pal=1, hflip=1
	tsa_entry 0x0AB, pal=1, hflip=1
	tsa_entry 0x0AA, hflip=1
	tsa_entry 0x0A9, pal=3, hflip=1
	tsa_entry 0x0A8, pal=3, hflip=1
	tsa_entry 0x0A7, pal=1, hflip=1
	tsa_entry 0x0A6, hflip=1
	tsa_entry 0x0A5, hflip=1
	tsa_entry 0x0A4, hflip=1
	tsa_entry 0x0A3, hflip=1
	tsa_entry 0x0A2, pal=1, hflip=1
	tsa_entry 0x0A1, pal=1, hflip=1
	tsa_entry 0x0A0, hflip=1
	tsa_entry 0x09F, hflip=1
	tsa_entry 0x09E, hflip=1
	tsa_entry 0x09D, hflip=1
	tsa_entry 0x09C, hflip=1
	tsa_entry 0x09B, pal=2, hflip=1
	tsa_entry 0x09A, pal=2, hflip=1
	tsa_entry 0x099, pal=2, hflip=1
	tsa_entry 0x098, pal=2, hflip=1
	tsa_entry 0x097, pal=2, hflip=1
	tsa_entry 0x096, pal=2, hflip=1
	tsa_entry 0x095, pal=2, hflip=1
	tsa_entry 0x094, pal=2, hflip=1
	tsa_entry 0x093, pal=2, hflip=1
	tsa_entry 0x092, pal=2, hflip=1
	tsa_entry 0x091, pal=2, hflip=1
	tsa_entry 0x090, pal=2, hflip=1
	tsa_entry 0x08F, pal=2, hflip=1
	tsa_entry 0x08E, pal=1, hflip=1
	tsa_entry 0x08D, pal=1, hflip=1
	tsa_entry 0x08C, pal=1, hflip=1
	tsa_entry 0x08B, pal=3, hflip=1
	tsa_entry 0x08A, pal=1, hflip=1
	tsa_entry 0x089, pal=1, hflip=1
	tsa_entry 0x088, pal=1, hflip=1
	tsa_entry 0x087, hflip=1
	tsa_entry 0x086, hflip=1
	tsa_entry 0x085, hflip=1
	tsa_entry 0x084, pal=3, hflip=1
	tsa_entry 0x083, pal=3, hflip=1
	tsa_entry 0x082, hflip=1
	tsa_entry 0x081, hflip=1
	tsa_entry 0x068, hflip=1
	tsa_entry 0x080, hflip=1
	tsa_entry 0x06A, hflip=1
	tsa_entry 0x07F, pal=2, hflip=1
	tsa_entry 0x07E, pal=2, hflip=1
	tsa_entry 0x07D, pal=6, hflip=1
	tsa_entry 0x00C, pal=6, hflip=1
	tsa_entry 0x07C, pal=2, hflip=1
	tsa_entry 0x07B, hflip=1
	tsa_entry 0x07A, hflip=1
	tsa_entry 0x079, hflip=1
	tsa_entry 0x078, pal=4, hflip=1
	tsa_entry 0x077, pal=2, hflip=1
	tsa_entry 0x076, pal=1, hflip=1
	tsa_entry 0x075, pal=4, hflip=1
	tsa_entry 0x074, pal=1, hflip=1
	tsa_entry 0x073, pal=4, hflip=1
	tsa_entry 0x072, pal=1, hflip=1
	tsa_entry 0x071, pal=1, hflip=1
	tsa_entry 0x070, pal=3, hflip=1
	tsa_entry 0x06F, pal=1, hflip=1
	tsa_entry 0x069, hflip=1
	tsa_entry 0x06A, hflip=1
	tsa_entry 0x069, hflip=1
	tsa_entry 0x069, hflip=1
	tsa_entry 0x06E, hflip=1
	tsa_entry 0x06D, hflip=1
	tsa_entry 0x06C, hflip=1
	tsa_entry 0x06B, hflip=1
	tsa_entry 0x069, hflip=1
	tsa_entry 0x06A, hflip=1
	tsa_entry 0x069, hflip=1
	tsa_entry 0x068, hflip=1
	tsa_entry 0x067, pal=2, hflip=1
	tsa_entry 0x066, pal=2, hflip=1
	tsa_entry 0x065, pal=6, hflip=1
	tsa_entry 0x064, pal=6, hflip=1
	tsa_entry 0x063, pal=6, hflip=1
	tsa_entry 0x062, pal=2, hflip=1
	tsa_entry 0x061, hflip=1
	tsa_entry 0x060, pal=1, hflip=1
	tsa_entry 0x05F, pal=1, hflip=1
	tsa_entry 0x05E, pal=2, hflip=1
	tsa_entry 0x05D, hflip=1
	tsa_entry 0x05C, pal=2, hflip=1
	tsa_entry 0x05B, pal=1, hflip=1
	tsa_entry 0x05A, pal=1, hflip=1
	tsa_entry 0x059, hflip=1
	tsa_entry 0x058, pal=1, hflip=1
	tsa_entry 0x057, pal=1, hflip=1
	tsa_entry 0x056, pal=1, hflip=1
	tsa_entry 0x055, pal=1, hflip=1
	tsa_entry 0x054, pal=1, hflip=1
	tsa_entry 0x053, pal=1, hflip=1
	tsa_entry 0x052, pal=1, hflip=1
	tsa_entry 0x051, pal=1, hflip=1
	tsa_entry 0x050, pal=1, hflip=1
	tsa_entry 0x04F, pal=1, hflip=1
	tsa_entry 0x04E, pal=1, hflip=1
	tsa_entry 0x04D, pal=1, hflip=1
	tsa_entry 0x04C, pal=1, hflip=1
	tsa_entry 0x04B, pal=1, hflip=1
	tsa_entry 0x04A, pal=1, hflip=1
	tsa_entry 0x049, pal=2, hflip=1
	tsa_entry 0x048, pal=6, hflip=1
	tsa_entry 0x047, pal=6, hflip=1
	tsa_entry 0x046, pal=6, hflip=1
	tsa_entry 0x045, pal=6, hflip=1
	tsa_entry 0x044, pal=2, hflip=1
	tsa_entry 0x043, pal=1, hflip=1
	tsa_entry 0x042, pal=2, hflip=1
	tsa_entry 0x041, pal=2, hflip=1
	tsa_entry 0x040, pal=1, hflip=1
	tsa_entry 0x03F, pal=4, hflip=1
	tsa_entry 0x03E, pal=1, hflip=1
	tsa_entry 0x03D, pal=1, hflip=1
	tsa_entry 0x03C, pal=1, hflip=1
	tsa_entry 0x03B, hflip=1
	tsa_entry 0x03A, pal=1, hflip=1
	tsa_entry 0x039, pal=1, hflip=1
	tsa_entry 0x038, hflip=1
	tsa_entry 0x00C, pal=6, hflip=1
	tsa_entry 0x00C, pal=6, hflip=1
	tsa_entry 0x037, pal=6, hflip=1
	tsa_entry 0x00C, pal=6, hflip=1
	tsa_entry 0x036, pal=1, hflip=1
	tsa_entry 0x035, pal=1, hflip=1
	tsa_entry 0x034, pal=1, hflip=1
	tsa_entry 0x033, pal=6, hflip=1
	tsa_entry 0x032, pal=6, hflip=1
	tsa_entry 0x031, pal=6, hflip=1
	tsa_entry 0x030, pal=6, hflip=1
	tsa_entry 0x02F, pal=6, hflip=1
	tsa_entry 0x02E, pal=6, hflip=1
	tsa_entry 0x02D, pal=6, hflip=1
	tsa_entry 0x02C, pal=6, hflip=1
	tsa_entry 0x02B, pal=6, hflip=1
	tsa_entry 0x02A, pal=6, hflip=1
	tsa_entry 0x029, pal=6, hflip=1
	tsa_entry 0x028, pal=2, hflip=1
	tsa_entry 0x027, pal=2, hflip=1
	tsa_entry 0x026, pal=2, hflip=1
	tsa_entry 0x025, pal=1, hflip=1
	tsa_entry 0x024, pal=4, hflip=1
	tsa_entry 0x023, pal=1, hflip=1
	tsa_entry 0x022, pal=2, hflip=1
	tsa_entry 0x021, pal=4, hflip=1
	tsa_entry 0x020, hflip=1
	tsa_entry 0x01F, pal=1, hflip=1
	tsa_entry 0x00C, pal=6, hflip=1
	tsa_entry 0x00C, pal=6, hflip=1
	tsa_entry 0x01E, pal=6, hflip=1
	tsa_entry 0x01D, pal=6, hflip=1
	tsa_entry 0x01C, pal=6, hflip=1
	tsa_entry 0x01B, pal=6, hflip=1
	tsa_entry 0x01A, pal=6, hflip=1
	tsa_entry 0x019, pal=1, hflip=1
	tsa_entry 0x018, pal=1, hflip=1
	tsa_entry 0x017, pal=6, hflip=1
	tsa_entry 0x016, pal=6, hflip=1
	tsa_entry 0x006, pal=6, hflip=1
	tsa_entry 0x016, pal=6, hflip=1
	tsa_entry 0x006, pal=6, hflip=1
	tsa_entry 0x015, pal=6, hflip=1
	tsa_entry 0x00C, pal=6, hflip=1
	tsa_entry 0x00C, pal=6, hflip=1
	tsa_entry 0x00C, pal=6, hflip=1
	tsa_entry 0x00C, pal=6, hflip=1
	tsa_entry 0x00C, pal=6, hflip=1
	tsa_entry 0x014, pal=1, hflip=1
	tsa_entry 0x00C, pal=6, hflip=1
	tsa_entry 0x00C, pal=6, hflip=1
	tsa_entry 0x013, pal=2, hflip=1
	tsa_entry 0x012, pal=4, hflip=1
	tsa_entry 0x011, pal=1, hflip=1
	tsa_entry 0x010, pal=2, hflip=1
	tsa_entry 0x00F, pal=4, hflip=1
	tsa_entry 0x00E, pal=1, hflip=1
	tsa_entry 0x00D, pal=1, hflip=1
	tsa_entry 0x00C, pal=6, hflip=1
	tsa_entry 0x00B, pal=6, hflip=1
	tsa_entry 0x00A, pal=6, hflip=1
	tsa_entry 0x009, pal=6, hflip=1
	tsa_entry 0x008, pal=6, hflip=1
	tsa_entry 0x007, pal=6, hflip=1
	tsa_entry 0x006, pal=6, hflip=1
	tsa_entry 0x006, pal=6, hflip=1
	tsa_entry 0x005, pal=6, hflip=1
	tsa_entry 0x004, pal=6, hflip=1
	tsa_entry 0x003, pal=6, hflip=1
	tsa_entry 0x002, pal=6, hflip=1
	tsa_entry 0x001, pal=6, hflip=1
	tsa_entry 0x000, pal=6, hflip=1
