	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x31D, pal=1
	tsa_entry 0x213, pal=4
	tsa_entry 0x214, pal=4
	tsa_entry 0x215, pal=4
	tsa_entry 0x216, pal=4
	tsa_entry 0x217, pal=4
	tsa_entry 0x218, pal=4
	tsa_entry 0x219, pal=4
	tsa_entry 0x21A, pal=4
	tsa_entry 0x21B, pal=4
	tsa_entry 0x21C, pal=4
	tsa_entry 0x21D, pal=4
	tsa_entry 0x21E, pal=4
	tsa_entry 0x21F, pal=4
	tsa_entry 0x220, pal=4
	tsa_entry 0x221, pal=4
	tsa_entry 0x222, pal=4
	tsa_entry 0x223, pal=4
	tsa_entry 0x224, pal=4
	tsa_entry 0x225, pal=4
	tsa_entry 0x226, pal=4
	tsa_entry 0x227, pal=4
	tsa_entry 0x228, pal=5
	tsa_entry 0x229, pal=5
	tsa_entry 0x22A, pal=5
	tsa_entry 0x22B, pal=5
	tsa_entry 0x22C, pal=5
	tsa_entry 0x22D, pal=5
	tsa_entry 0x22E, pal=5
	tsa_entry 0x22F, pal=5
	tsa_entry 0x230, pal=5
	tsa_entry 0x1F5, pal=4
	tsa_entry 0x1F6, pal=4
	tsa_entry 0x1F7, pal=4
	tsa_entry 0x1F8, pal=5
	tsa_entry 0x1F9, pal=5
	tsa_entry 0x1FA, pal=5
	tsa_entry 0x1FB, pal=4
	tsa_entry 0x1FC, pal=4
	tsa_entry 0x1FD, pal=4
	tsa_entry 0x1FE, pal=4
	tsa_entry 0x1FF, pal=4
	tsa_entry 0x200, pal=4
	tsa_entry 0x201, pal=4
	tsa_entry 0x202, pal=4
	tsa_entry 0x203, pal=4
	tsa_entry 0x204, pal=4
	tsa_entry 0x205, pal=4
	tsa_entry 0x206, pal=4
	tsa_entry 0x207, pal=4
	tsa_entry 0x208, pal=4
	tsa_entry 0x209, pal=4
	tsa_entry 0x20A, pal=4
	tsa_entry 0x20B, pal=5
	tsa_entry 0x20C, pal=5
	tsa_entry 0x20D, pal=5
	tsa_entry 0x20E, pal=2
	tsa_entry 0x20F, pal=5
	tsa_entry 0x210, pal=5
	tsa_entry 0x211, pal=5
	tsa_entry 0x212, pal=2
	tsa_entry 0x1D7, pal=4
	tsa_entry 0x1D8, pal=4
	tsa_entry 0x1D9, pal=4
	tsa_entry 0x1DA, pal=5
	tsa_entry 0x1DB, pal=5
	tsa_entry 0x1DC, pal=4
	tsa_entry 0x1DD, pal=4
	tsa_entry 0x1DE, pal=4
	tsa_entry 0x1DF, pal=4
	tsa_entry 0x1E0, pal=5
	tsa_entry 0x1E1, pal=4
	tsa_entry 0x1E2, pal=4
	tsa_entry 0x1E3, pal=4
	tsa_entry 0x1E4, pal=4
	tsa_entry 0x1E5, pal=4
	tsa_entry 0x1E6, pal=4
	tsa_entry 0x1E7, pal=4
	tsa_entry 0x1E8, pal=4
	tsa_entry 0x1E9, pal=4
	tsa_entry 0x1EA, pal=4
	tsa_entry 0x1EB, pal=4
	tsa_entry 0x1EC, pal=4
	tsa_entry 0x1ED, pal=4
	tsa_entry 0x1EE, pal=4
	tsa_entry 0x1EF, pal=4
	tsa_entry 0x1F0, pal=5
	tsa_entry 0x1F1, pal=5
	tsa_entry 0x1F2, pal=5
	tsa_entry 0x1F3, pal=5
	tsa_entry 0x1F4, pal=5
	tsa_entry 0x1BA, pal=4
	tsa_entry 0x1BB, pal=4
	tsa_entry 0x1BC, pal=4
	tsa_entry 0x1BD, pal=4
	tsa_entry 0x1BE, pal=4
	tsa_entry 0x1BF, pal=4
	tsa_entry 0x1C0, pal=4
	tsa_entry 0x1C1, pal=4
	tsa_entry 0x1C2, pal=4
	tsa_entry 0x1C3, pal=4
	tsa_entry 0x1C4, pal=4
	tsa_entry 0x1C5, pal=4
	tsa_entry 0x1C6, pal=4
	tsa_entry 0x1C7, pal=4
	tsa_entry 0x1C8, pal=4
	tsa_entry 0x1C9, pal=4
	tsa_entry 0x1CA, pal=4
	tsa_entry 0x1CB, pal=4
	tsa_entry 0x1CC, pal=4
	tsa_entry 0x1CD, pal=4
	tsa_entry 0x1CE, pal=4
	tsa_entry 0x1CF, pal=4
	tsa_entry 0x1D0, pal=4
	tsa_entry 0x1D1, pal=4
	tsa_entry 0x1D2, pal=4
	tsa_entry 0x1D3, pal=5
	tsa_entry 0x1D4, pal=5
	tsa_entry 0x1D5, pal=5
	tsa_entry 0x1D6, pal=5
	tsa_entry 0x19C, pal=5
	tsa_entry 0x19D, pal=4
	tsa_entry 0x19E, pal=4
	tsa_entry 0x19F, pal=4
	tsa_entry 0x1A0, pal=4
	tsa_entry 0x1A1, pal=4
	tsa_entry 0x1A2, pal=4
	tsa_entry 0x1A3, pal=4
	tsa_entry 0x1A4, pal=4
	tsa_entry 0x1A5, pal=4
	tsa_entry 0x1A6, pal=4
	tsa_entry 0x1A7, pal=4
	tsa_entry 0x1A8, pal=4
	tsa_entry 0x1A9, pal=4
	tsa_entry 0x1AA, pal=4
	tsa_entry 0x1AB, pal=4
	tsa_entry 0x1AC, pal=4
	tsa_entry 0x1AD, pal=4
	tsa_entry 0x1AE, pal=4
	tsa_entry 0x1AF, pal=4
	tsa_entry 0x1B0, pal=4
	tsa_entry 0x1B1, pal=4
	tsa_entry 0x1B2, pal=4
	tsa_entry 0x1B3, pal=4
	tsa_entry 0x1B4, pal=4
	tsa_entry 0x1B5, pal=4
	tsa_entry 0x1B6, pal=5
	tsa_entry 0x1B7, pal=5
	tsa_entry 0x1B8, pal=5
	tsa_entry 0x1B9, pal=5
	tsa_entry 0x19C, pal=5
	tsa_entry 0x17F, pal=4
	tsa_entry 0x180, pal=4
	tsa_entry 0x181, pal=4
	tsa_entry 0x182, pal=4
	tsa_entry 0x183, pal=4
	tsa_entry 0x184, pal=4
	tsa_entry 0x185, pal=4
	tsa_entry 0x186, pal=4
	tsa_entry 0x187, pal=4
	tsa_entry 0x188, pal=4
	tsa_entry 0x189, pal=4
	tsa_entry 0x18A, pal=4
	tsa_entry 0x18B, pal=4
	tsa_entry 0x18C, pal=4
	tsa_entry 0x18D, pal=4
	tsa_entry 0x18E, pal=4
	tsa_entry 0x18F, pal=4
	tsa_entry 0x190, pal=4
	tsa_entry 0x191, pal=4
	tsa_entry 0x192, pal=4
	tsa_entry 0x193, pal=4
	tsa_entry 0x194, pal=4
	tsa_entry 0x195, pal=4
	tsa_entry 0x196, pal=4
	tsa_entry 0x197, pal=4
	tsa_entry 0x198, pal=5
	tsa_entry 0x199, pal=5
	tsa_entry 0x19A, pal=5
	tsa_entry 0x19B, pal=5
	tsa_entry 0x19C, pal=5
	tsa_entry 0x161, pal=4
	tsa_entry 0x162, pal=4
	tsa_entry 0x163, pal=5
	tsa_entry 0x164, pal=3
	tsa_entry 0x165, pal=3
	tsa_entry 0x166, pal=3
	tsa_entry 0x167, pal=4
	tsa_entry 0x168, pal=3
	tsa_entry 0x169, pal=3
	tsa_entry 0x16A, pal=4
	tsa_entry 0x16B, pal=4
	tsa_entry 0x16C, pal=4
	tsa_entry 0x16D, pal=4
	tsa_entry 0x16E, pal=4
	tsa_entry 0x16F, pal=4
	tsa_entry 0x170, pal=4
	tsa_entry 0x171, pal=4
	tsa_entry 0x172, pal=4
	tsa_entry 0x173, pal=4
	tsa_entry 0x174, pal=4
	tsa_entry 0x175, pal=4
	tsa_entry 0x176, pal=4
	tsa_entry 0x177, pal=4
	tsa_entry 0x178, pal=4
	tsa_entry 0x179, pal=4
	tsa_entry 0x17A, pal=4
	tsa_entry 0x17B, pal=4
	tsa_entry 0x17C, pal=5
	tsa_entry 0x17D, pal=5
	tsa_entry 0x17E, pal=5
	tsa_entry 0x143, pal=3
	tsa_entry 0x144, pal=3
	tsa_entry 0x145
	tsa_entry 0x146
	tsa_entry 0x147, pal=3
	tsa_entry 0x148, pal=3
	tsa_entry 0x149, pal=3
	tsa_entry 0x14A, pal=3
	tsa_entry 0x14B, pal=3
	tsa_entry 0x14C, pal=3
	tsa_entry 0x14D, pal=4
	tsa_entry 0x14E, pal=4
	tsa_entry 0x14F, pal=4
	tsa_entry 0x150, pal=4
	tsa_entry 0x151, pal=4
	tsa_entry 0x152, pal=4
	tsa_entry 0x153, pal=4
	tsa_entry 0x154, pal=4
	tsa_entry 0x155, pal=4
	tsa_entry 0x156, pal=4
	tsa_entry 0x157, pal=4
	tsa_entry 0x158, pal=4
	tsa_entry 0x159, pal=4
	tsa_entry 0x15A, pal=4
	tsa_entry 0x15B, pal=4
	tsa_entry 0x15C, pal=4
	tsa_entry 0x15D, pal=4
	tsa_entry 0x15E, pal=4
	tsa_entry 0x15F, pal=5
	tsa_entry 0x160, pal=5
	tsa_entry 0x125
	tsa_entry 0x126
	tsa_entry 0x127, pal=3
	tsa_entry 0x128
	tsa_entry 0x129, pal=3
	tsa_entry 0x12A, pal=3
	tsa_entry 0x12B, pal=3
	tsa_entry 0x12C, pal=3
	tsa_entry 0x12D, pal=3
	tsa_entry 0x12E
	tsa_entry 0x12F, pal=2
	tsa_entry 0x130, pal=4
	tsa_entry 0x131
	tsa_entry 0x132, pal=4
	tsa_entry 0x133, pal=4
	tsa_entry 0x134, pal=4
	tsa_entry 0x135, pal=4
	tsa_entry 0x136, pal=4
	tsa_entry 0x137, pal=4
	tsa_entry 0x138, pal=4
	tsa_entry 0x139, pal=4
	tsa_entry 0x13A, pal=4
	tsa_entry 0x13B, pal=4
	tsa_entry 0x13C, pal=4
	tsa_entry 0x13D, pal=4
	tsa_entry 0x13E, pal=4
	tsa_entry 0x13F, pal=4
	tsa_entry 0x140, pal=4
	tsa_entry 0x141, pal=4
	tsa_entry 0x142, pal=4
	tsa_entry 0x107
	tsa_entry 0x108, pal=3
	tsa_entry 0x109, pal=3
	tsa_entry 0x10A, pal=3
	tsa_entry 0x10B
	tsa_entry 0x10C
	tsa_entry 0x10D, pal=3
	tsa_entry 0x10E, pal=3
	tsa_entry 0x10F
	tsa_entry 0x110
	tsa_entry 0x111, pal=4
	tsa_entry 0x112, pal=2
	tsa_entry 0x113, pal=4
	tsa_entry 0x114, pal=4
	tsa_entry 0x115, pal=4
	tsa_entry 0x116, pal=4
	tsa_entry 0x117, pal=4
	tsa_entry 0x118, pal=2
	tsa_entry 0x119, pal=4
	tsa_entry 0x11A, pal=4
	tsa_entry 0x11B, pal=4
	tsa_entry 0x11C, pal=1
	tsa_entry 0x11D, pal=2
	tsa_entry 0x11E, pal=4
	tsa_entry 0x11F, pal=4
	tsa_entry 0x120, pal=5
	tsa_entry 0x121, pal=5
	tsa_entry 0x122, pal=5
	tsa_entry 0x123, pal=5
	tsa_entry 0x124, pal=5
	tsa_entry 0x0E9, pal=4
	tsa_entry 0x0EA, pal=4
	tsa_entry 0x0EB, pal=4
	tsa_entry 0x0EC
	tsa_entry 0x0ED
	tsa_entry 0x0EE
	tsa_entry 0x0EF
	tsa_entry 0x0F0
	tsa_entry 0x0F1, pal=2
	tsa_entry 0x0F2, pal=4
	tsa_entry 0x0F3, pal=2
	tsa_entry 0x0F4, pal=4
	tsa_entry 0x0F5, pal=1
	tsa_entry 0x0F6, pal=4
	tsa_entry 0x0F7, pal=4
	tsa_entry 0x0F8, pal=4
	tsa_entry 0x0F9, pal=4
	tsa_entry 0x0FA, pal=4
	tsa_entry 0x0FB, pal=4
	tsa_entry 0x0FC, pal=4
	tsa_entry 0x0FD, pal=4
	tsa_entry 0x0FE, pal=5
	tsa_entry 0x0FF, pal=2
	tsa_entry 0x100, pal=4
	tsa_entry 0x101, pal=4
	tsa_entry 0x102, pal=4
	tsa_entry 0x103, pal=2
	tsa_entry 0x104, pal=5
	tsa_entry 0x105, pal=5
	tsa_entry 0x106, pal=2
	tsa_entry 0x0CB, pal=4
	tsa_entry 0x0CC, pal=4
	tsa_entry 0x0CD, pal=4
	tsa_entry 0x0CE, pal=4
	tsa_entry 0x0CF
	tsa_entry 0x0D0
	tsa_entry 0x0D1
	tsa_entry 0x0D2, pal=1
	tsa_entry 0x0D3, pal=2
	tsa_entry 0x0D4, pal=1
	tsa_entry 0x0D5, pal=1
	tsa_entry 0x0D6, pal=1
	tsa_entry 0x0D7, pal=4
	tsa_entry 0x0D8, pal=4
	tsa_entry 0x0D9, pal=1
	tsa_entry 0x0DA, pal=1
	tsa_entry 0x0DB, pal=1
	tsa_entry 0x0DC, pal=1
	tsa_entry 0x0DD, pal=1
	tsa_entry 0x0DE, pal=1
	tsa_entry 0x0DF, pal=4
	tsa_entry 0x0E0, pal=2
	tsa_entry 0x0E1, pal=2
	tsa_entry 0x0E2, pal=5
	tsa_entry 0x0E3, pal=5
	tsa_entry 0x0E4, pal=2
	tsa_entry 0x0E5, pal=5
	tsa_entry 0x0E6, pal=5
	tsa_entry 0x0E7, pal=5
	tsa_entry 0x0E8, pal=5
	tsa_entry 0x0AD, pal=4
	tsa_entry 0x0AE, pal=4
	tsa_entry 0x0AF, pal=4
	tsa_entry 0x0B0
	tsa_entry 0x0B1
	tsa_entry 0x0B2
	tsa_entry 0x0B3, pal=2
	tsa_entry 0x0B4, pal=4
	tsa_entry 0x0B5, pal=2
	tsa_entry 0x0B6, pal=2
	tsa_entry 0x0B7, pal=1
	tsa_entry 0x0B8, pal=1
	tsa_entry 0x0B9, pal=4
	tsa_entry 0x0BA, pal=1
	tsa_entry 0x0BB, pal=1
	tsa_entry 0x0BC, pal=1
	tsa_entry 0x0BD, pal=2
	tsa_entry 0x0BE, pal=2
	tsa_entry 0x0BF, pal=1
	tsa_entry 0x0C0, pal=1
	tsa_entry 0x0C1, pal=4
	tsa_entry 0x0C2, pal=2
	tsa_entry 0x0C3, pal=5
	tsa_entry 0x0C4, pal=5
	tsa_entry 0x0C5, pal=2
	tsa_entry 0x0C6, pal=5
	tsa_entry 0x0C7, pal=5
	tsa_entry 0x0C8, pal=2
	tsa_entry 0x0C9, pal=5
	tsa_entry 0x0CA, pal=2
	tsa_entry 0x08F, pal=2
	tsa_entry 0x090, pal=4
	tsa_entry 0x091
	tsa_entry 0x092
	tsa_entry 0x093, pal=1
	tsa_entry 0x094
	tsa_entry 0x095
	tsa_entry 0x096, pal=3
	tsa_entry 0x097, pal=4
	tsa_entry 0x098, pal=4
	tsa_entry 0x099, pal=2
	tsa_entry 0x09A, pal=1
	tsa_entry 0x09B
	tsa_entry 0x09C, pal=4
	tsa_entry 0x09D, pal=4
	tsa_entry 0x09E, pal=3
	tsa_entry 0x09F, pal=1
	tsa_entry 0x0A0, pal=3
	tsa_entry 0x0A1, pal=3
	tsa_entry 0x0A2
	tsa_entry 0x0A3, pal=4
	tsa_entry 0x0A4, pal=4
	tsa_entry 0x0A5, pal=2
	tsa_entry 0x0A6, pal=2
	tsa_entry 0x0A7, pal=5
	tsa_entry 0x0A8, pal=5
	tsa_entry 0x0A9, pal=2
	tsa_entry 0x0AA, pal=2
	tsa_entry 0x0AB, pal=2
	tsa_entry 0x0AC, pal=2
	tsa_entry 0x071, pal=2
	tsa_entry 0x072
	tsa_entry 0x073
	tsa_entry 0x074
	tsa_entry 0x075
	tsa_entry 0x076
	tsa_entry 0x077
	tsa_entry 0x078, pal=3
	tsa_entry 0x079
	tsa_entry 0x07A
	tsa_entry 0x07B
	tsa_entry 0x07C
	tsa_entry 0x07D, pal=3
	tsa_entry 0x07E
	tsa_entry 0x07F
	tsa_entry 0x080
	tsa_entry 0x081
	tsa_entry 0x082
	tsa_entry 0x083, pal=1
	tsa_entry 0x084
	tsa_entry 0x085
	tsa_entry 0x086, pal=4
	tsa_entry 0x087, pal=4
	tsa_entry 0x088, pal=5
	tsa_entry 0x089, pal=5
	tsa_entry 0x08A, pal=5
	tsa_entry 0x08B, pal=2
	tsa_entry 0x08C, pal=2
	tsa_entry 0x08D, pal=2
	tsa_entry 0x08E, pal=2
	tsa_entry 0x053, pal=2
	tsa_entry 0x054
	tsa_entry 0x055
	tsa_entry 0x056
	tsa_entry 0x057
	tsa_entry 0x058
	tsa_entry 0x059
	tsa_entry 0x05A, pal=3
	tsa_entry 0x05B, pal=3
	tsa_entry 0x05C
	tsa_entry 0x05D
	tsa_entry 0x05E
	tsa_entry 0x05F
	tsa_entry 0x060
	tsa_entry 0x061
	tsa_entry 0x062
	tsa_entry 0x063, pal=1
	tsa_entry 0x064, pal=1
	tsa_entry 0x065, pal=1
	tsa_entry 0x066, pal=1
	tsa_entry 0x067
	tsa_entry 0x068, pal=2
	tsa_entry 0x069, pal=2
	tsa_entry 0x06A, pal=4
	tsa_entry 0x06B, pal=4
	tsa_entry 0x06C, pal=4
	tsa_entry 0x06D, pal=2
	tsa_entry 0x06E, pal=2
	tsa_entry 0x06F, pal=2
	tsa_entry 0x070, pal=2
	tsa_entry 0x035
	tsa_entry 0x036
	tsa_entry 0x037
	tsa_entry 0x038
	tsa_entry 0x039
	tsa_entry 0x03A
	tsa_entry 0x03B, pal=3
	tsa_entry 0x03C, pal=3
	tsa_entry 0x03D, pal=3
	tsa_entry 0x03E
	tsa_entry 0x03F
	tsa_entry 0x040
	tsa_entry 0x041
	tsa_entry 0x042, pal=2
	tsa_entry 0x043, pal=1
	tsa_entry 0x044
	tsa_entry 0x045, pal=1
	tsa_entry 0x046, pal=1
	tsa_entry 0x047, pal=1
	tsa_entry 0x048, pal=1
	tsa_entry 0x049
	tsa_entry 0x04A, pal=2
	tsa_entry 0x04B
	tsa_entry 0x04C
	tsa_entry 0x04D, pal=3
	tsa_entry 0x04E, pal=4
	tsa_entry 0x04F, pal=2
	tsa_entry 0x050, pal=2
	tsa_entry 0x051, pal=2
	tsa_entry 0x052, pal=2
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x01B
	tsa_entry 0x01C
	tsa_entry 0x01D
	tsa_entry 0x01E
	tsa_entry 0x01F
	tsa_entry 0x020
	tsa_entry 0x021, pal=2
	tsa_entry 0x022
	tsa_entry 0x023
	tsa_entry 0x024, pal=1
	tsa_entry 0x025
	tsa_entry 0x026
	tsa_entry 0x027
	tsa_entry 0x028, pal=1
	tsa_entry 0x029
	tsa_entry 0x02A
	tsa_entry 0x02B
	tsa_entry 0x02C, pal=1
	tsa_entry 0x02D
	tsa_entry 0x02E
	tsa_entry 0x02F, pal=3
	tsa_entry 0x030, pal=2
	tsa_entry 0x031, pal=2
	tsa_entry 0x032, pal=2
	tsa_entry 0x032, pal=2
	tsa_entry 0x033, pal=2
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x001
	tsa_entry 0x002
	tsa_entry 0x000
	tsa_entry 0x003, pal=1
	tsa_entry 0x004
	tsa_entry 0x005, pal=1
	tsa_entry 0x006, pal=1
	tsa_entry 0x007
	tsa_entry 0x008, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x00A, pal=1
	tsa_entry 0x00B, pal=1
	tsa_entry 0x00C, pal=1
	tsa_entry 0x00D, pal=1
	tsa_entry 0x00E, pal=1
	tsa_entry 0x00F, pal=1
	tsa_entry 0x010, pal=1
	tsa_entry 0x011, pal=1
	tsa_entry 0x012, pal=1
	tsa_entry 0x013, pal=2
	tsa_entry 0x014, pal=2
	tsa_entry 0x015
	tsa_entry 0x016, pal=4
	tsa_entry 0x017, pal=2
	tsa_entry 0x018, pal=2
	tsa_entry 0x019, pal=2
	tsa_entry 0x01A, pal=2
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x001
	tsa_entry 0x002
	tsa_entry 0x001, hflip=1
	tsa_entry 0x003, pal=1
	tsa_entry 0x004
	tsa_entry 0x006, pal=1
	tsa_entry 0x008, pal=1, hflip=1, vflip=1
	tsa_entry 0x007, hflip=1, vflip=1
	tsa_entry 0x006, pal=1, hflip=1, vflip=1
	tsa_entry 0x004
	tsa_entry 0x00F, pal=1
	tsa_entry 0x010, pal=1
	tsa_entry 0x011, pal=1
	tsa_entry 0x012, pal=1
	tsa_entry 0x00E, pal=1
	tsa_entry 0x00F, pal=1
	tsa_entry 0x010, pal=1
	tsa_entry 0x011, pal=1
	tsa_entry 0x010, pal=1
	tsa_entry 0x011, pal=1
	tsa_entry 0x012, pal=1
	tsa_entry 0x00A, pal=1
	tsa_entry 0x015
	tsa_entry 0x016, pal=4
	tsa_entry 0x017, pal=2
	tsa_entry 0x019, pal=2
	tsa_entry 0x01A, pal=2
