"""Committed inventory for typed autoplay strategies and assignments."""

from __future__ import annotations

from .schema import ASSIGNMENT_CAPACITY, SCHEMA_ID, STRATEGY_CAPACITY


def build_inventory(records):
    strategies = records["strategies"]
    chapters = records["chapters"]
    lines = [
        "# Generated-data inventory: autoplaystrategies\n\n",
        "_Auto-generated by `python3 -m scripts.generated_data generate --table autoplaystrategies`. "
        "Do not edit by hand -- see docs/generated_data_tutorial.md._\n\n",
        "- Schema: `{}`\n".format(SCHEMA_ID),
        "- Registry capacity: `{}` strategies\n".format(STRATEGY_CAPACITY),
        "- Per chapter: `{}` group and `{}` unit assignments\n\n".format(
            ASSIGNMENT_CAPACITY, ASSIGNMENT_CAPACITY
        ),
        "| Strategy | Callback | Objective capabilities | Action capabilities |\n",
        "|---|---|---|---|\n",
    ]
    for strategy in strategies:
        lines.append(
            "| {} | {} | {} | {} |\n".format(
                strategy.id,
                strategy.callback,
                ", ".join(strategy.objectives) or "_(none)_",
                ", ".join(strategy.actions),
            )
        )
    if not strategies:
        lines.append("| _(none)_ | _(default profiles disabled)_ | _(none)_ | _(none)_ |\n")
    lines.extend(
        [
            "\n| Chapter | Bundle symbol | Chapter | Group | Unit assignments |\n",
            "|---|---|---:|---:|---:|\n",
        ]
    )
    for chapter in chapters:
        lines.append(
            "| {} | {} | {} | {} | {} |\n".format(
                chapter.chapter,
                chapter.symbol,
                "yes" if chapter.chapter_assignment else "no",
                len(chapter.group_assignments),
                len(chapter.unit_assignments),
            )
        )
    if not chapters:
        lines.append("| _(none)_ | _(existing AI unchanged)_ | no | 0 | 0 |\n")
    return "".join(lines)
