	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x105, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x0C4
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x0C0
	tsa_entry 0x001, vflip=1
	tsa_entry 0x001, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x004, hflip=1
	tsa_entry 0x0B9
	tsa_entry 0x0BA
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x0B3
	tsa_entry 0x0B4
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x183, pal=7, hflip=1, vflip=1
	tsa_entry 0x083, pal=5, vflip=1
	tsa_entry 0x383, pal=6, hflip=1
	tsa_entry 0x000
	tsa_entry 0x08E, pal=7, vflip=1
	tsa_entry 0x092, pal=8, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x28D, pal=6
	tsa_entry 0x294, pal=12
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x18C, pal=11, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x190, pal=8, hflip=1
	tsa_entry 0x000
	tsa_entry 0x188, pal=12, hflip=1
	tsa_entry 0x000
	tsa_entry 0x08D, pal=9, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x283, pal=5, hflip=1, vflip=1
	tsa_entry 0x383, pal=8, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x08E, pal=15
	tsa_entry 0x28F, pal=14, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x288, pal=14
	tsa_entry 0x190, pal=13, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x390, pal=5, vflip=1
	tsa_entry 0x38A, pal=4
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x38B, pal=15
	tsa_entry 0x000
	tsa_entry 0x38A, pal=13, vflip=1
	tsa_entry 0x291, pal=11, hflip=1, vflip=1
	tsa_entry 0x08B, pal=11, hflip=1
	tsa_entry 0x000
	tsa_entry 0x38C, pal=12
	tsa_entry 0x096, pal=13, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x292, pal=4, vflip=1
	tsa_entry 0x000
	tsa_entry 0x292, pal=12, vflip=1
	tsa_entry 0x190, pal=4, hflip=1, vflip=1
	tsa_entry 0x093, pal=10, hflip=1, vflip=1
	tsa_entry 0x28B, pal=5, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x095, pal=5, vflip=1
	tsa_entry 0x189, pal=12, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x38A, pal=4, vflip=1
	tsa_entry 0x192, pal=6, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x389, pal=15
	tsa_entry 0x282, pal=14, vflip=1
	tsa_entry 0x182, pal=11, hflip=1, vflip=1
	tsa_entry 0x289, pal=12, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x28D, pal=7
	tsa_entry 0x292, pal=6, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x083, pal=4, hflip=1, vflip=1
	tsa_entry 0x183, pal=8, vflip=1
	tsa_entry 0x381, pal=5, vflip=1
	tsa_entry 0x000
	tsa_entry 0x183, pal=8, hflip=1, vflip=1
	tsa_entry 0x383, pal=9
	tsa_entry 0x383, pal=4, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x183, pal=4
	tsa_entry 0x381, pal=5, vflip=1
	tsa_entry 0x083, pal=6
	tsa_entry 0x000
	tsa_entry 0x282, pal=10, vflip=1
	tsa_entry 0x382, pal=10, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x094, pal=7
	tsa_entry 0x09A, pal=13
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x38B, pal=11
	tsa_entry 0x389, pal=14, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x196, pal=14, hflip=1
	tsa_entry 0x000
	tsa_entry 0x289, pal=10, hflip=1, vflip=1
	tsa_entry 0x28D, pal=10, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x395, pal=15
	tsa_entry 0x094, pal=10
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x38B, pal=15
	tsa_entry 0x395, pal=15
	tsa_entry 0x094, pal=10
	tsa_entry 0x000
	tsa_entry 0x28B, pal=12, vflip=1
	tsa_entry 0x08D, pal=12
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x094, pal=14
	tsa_entry 0x000
	tsa_entry 0x092, pal=8, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x389, pal=15
	tsa_entry 0x282, pal=14, vflip=1
	tsa_entry 0x182, pal=11, hflip=1, vflip=1
	tsa_entry 0x395, pal=12, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x395, pal=12, hflip=1
	tsa_entry 0x000
	tsa_entry 0x395, pal=11, vflip=1
	tsa_entry 0x000
	tsa_entry 0x08F, pal=11
	tsa_entry 0x000
	tsa_entry 0x28C, pal=12, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x38A, pal=4
	tsa_entry 0x000
	tsa_entry 0x182, pal=12, hflip=1, vflip=1
	tsa_entry 0x382, pal=12, vflip=1
	tsa_entry 0x08B, pal=11, hflip=1
	tsa_entry 0x000
	tsa_entry 0x08B, pal=11, hflip=1
	tsa_entry 0x000
	tsa_entry 0x28D, pal=8
	tsa_entry 0x282, pal=10
	tsa_entry 0x28E, pal=5
	tsa_entry 0x000
	tsa_entry 0x28E, pal=5
	tsa_entry 0x000
	tsa_entry 0x090, pal=14, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x38D, pal=11, vflip=1
	tsa_entry 0x194, pal=9, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x38D, pal=11, vflip=1
	tsa_entry 0x292, pal=6, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x390, pal=5, vflip=1
	tsa_entry 0x282, pal=10
	tsa_entry 0x090, pal=5, vflip=1
	tsa_entry 0x000
	tsa_entry 0x090, pal=5, vflip=1
	tsa_entry 0x000
	tsa_entry 0x18F, pal=14, vflip=1
	tsa_entry 0x196, pal=14, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x08D, pal=13, hflip=1
	tsa_entry 0x000
	tsa_entry 0x197, pal=6
	tsa_entry 0x082, pal=14, vflip=1
	tsa_entry 0x28F, pal=8, vflip=1
	tsa_entry 0x000
	tsa_entry 0x093, pal=10, hflip=1, vflip=1
	tsa_entry 0x28B, pal=5, vflip=1
	tsa_entry 0x28F, pal=14, vflip=1
	tsa_entry 0x000
	tsa_entry 0x193, pal=11, vflip=1
	tsa_entry 0x38B, pal=14, hflip=1, vflip=1
	tsa_entry 0x289, pal=10, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x095, pal=9
	tsa_entry 0x18A, pal=14, hflip=1, vflip=1
	tsa_entry 0x289, pal=10, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x396, pal=10, hflip=1, vflip=1
	tsa_entry 0x289, pal=12, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x295, pal=12
	tsa_entry 0x282, pal=11, hflip=1
	tsa_entry 0x291, pal=11, vflip=1
	tsa_entry 0x000
	tsa_entry 0x291, pal=11, vflip=1
	tsa_entry 0x000
	tsa_entry 0x193, pal=11, vflip=1
	tsa_entry 0x000
	tsa_entry 0x195, pal=11, hflip=1, vflip=1
	tsa_entry 0x292, pal=6, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x381, pal=5, vflip=1
	tsa_entry 0x381, pal=5, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
