	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x309, hflip=1, vflip=1
	tsa_entry 0x01A
	tsa_entry 0x01B
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x020
	tsa_entry 0x021
	tsa_entry 0x006, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x034, pal=1
	tsa_entry 0x036, pal=1
	tsa_entry 0x037, pal=1
	tsa_entry 0x006, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x034, pal=1
	tsa_entry 0x035, pal=1
	tsa_entry 0x006, pal=1
	tsa_entry 0x02B, pal=1
	tsa_entry 0x02C, pal=1
	tsa_entry 0x02C, pal=1
	tsa_entry 0x02C, pal=1
	tsa_entry 0x02C, pal=1
	tsa_entry 0x02C, pal=1
	tsa_entry 0x02C, pal=1
	tsa_entry 0x02D, pal=1
	tsa_entry 0x00A, pal=1
	tsa_entry 0x006, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x00A, pal=1
	tsa_entry 0x006, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x07E, pal=1
	tsa_entry 0x05B, vflip=1
	tsa_entry 0x05B, vflip=1
	tsa_entry 0x05A, hflip=1, vflip=1
	tsa_entry 0x059, hflip=1, vflip=1
	tsa_entry 0x059, hflip=1, vflip=1
	tsa_entry 0x060
	tsa_entry 0x006, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x05D, pal=1
	tsa_entry 0x05E
	tsa_entry 0x05E
	tsa_entry 0x05F
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x00A
	tsa_entry 0x006, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x05D, pal=1
	tsa_entry 0x05E
	tsa_entry 0x05E
	tsa_entry 0x05F
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x00A
	tsa_entry 0x006, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x05D, pal=1
	tsa_entry 0x05E
	tsa_entry 0x05E
	tsa_entry 0x05F
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x00A
	tsa_entry 0x006, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x05D, pal=1
	tsa_entry 0x05E
	tsa_entry 0x05E
	tsa_entry 0x05F
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x00A
	tsa_entry 0x006, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x05D, pal=1
	tsa_entry 0x05E
	tsa_entry 0x05E
	tsa_entry 0x05F
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x00A
	tsa_entry 0x006, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x05D, pal=1
	tsa_entry 0x05E
	tsa_entry 0x05E
	tsa_entry 0x05F
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x00A
	tsa_entry 0x058, pal=1
	tsa_entry 0x059, pal=1
	tsa_entry 0x059, pal=1
	tsa_entry 0x05A, pal=1
	tsa_entry 0x05B
	tsa_entry 0x05B
	tsa_entry 0x05C
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x00A
	tsa_entry 0x006
	tsa_entry 0x02B
	tsa_entry 0x02C
	tsa_entry 0x02C
	tsa_entry 0x02C
	tsa_entry 0x02C
	tsa_entry 0x02C
	tsa_entry 0x02C
	tsa_entry 0x02D
	tsa_entry 0x00A
	tsa_entry 0x006
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x00A
	tsa_entry 0x061
	tsa_entry 0x062
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x004
	tsa_entry 0x005
	tsa_entry 0x000
