	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x31D, pal=1
	tsa_entry 0x224
	tsa_entry 0x225
	tsa_entry 0x226
	tsa_entry 0x227
	tsa_entry 0x228
	tsa_entry 0x229
	tsa_entry 0x22A
	tsa_entry 0x22B
	tsa_entry 0x22C
	tsa_entry 0x22D, pal=1
	tsa_entry 0x22E
	tsa_entry 0x22F, pal=1
	tsa_entry 0x230
	tsa_entry 0x231, pal=1
	tsa_entry 0x232
	tsa_entry 0x233
	tsa_entry 0x234
	tsa_entry 0x235
	tsa_entry 0x236
	tsa_entry 0x237
	tsa_entry 0x238
	tsa_entry 0x239
	tsa_entry 0x23A
	tsa_entry 0x23B
	tsa_entry 0x23C
	tsa_entry 0x23D
	tsa_entry 0x23E
	tsa_entry 0x23F
	tsa_entry 0x240
	tsa_entry 0x241
	tsa_entry 0x208, pal=1
	tsa_entry 0x209
	tsa_entry 0x20A
	tsa_entry 0x20B, pal=1
	tsa_entry 0x20C, pal=1
	tsa_entry 0x20D
	tsa_entry 0x20E
	tsa_entry 0x20F
	tsa_entry 0x210
	tsa_entry 0x211, pal=1
	tsa_entry 0x212, pal=1
	tsa_entry 0x213, pal=1
	tsa_entry 0x214, pal=1
	tsa_entry 0x215, pal=1
	tsa_entry 0x216
	tsa_entry 0x217
	tsa_entry 0x218
	tsa_entry 0x219
	tsa_entry 0x21A
	tsa_entry 0x21B
	tsa_entry 0x1A8
	tsa_entry 0x21C
	tsa_entry 0x21D
	tsa_entry 0x21E
	tsa_entry 0x21F
	tsa_entry 0x1A8
	tsa_entry 0x220
	tsa_entry 0x221
	tsa_entry 0x222
	tsa_entry 0x223
	tsa_entry 0x1EA
	tsa_entry 0x1EB
	tsa_entry 0x1EC
	tsa_entry 0x1ED, pal=1
	tsa_entry 0x1EE, pal=1
	tsa_entry 0x1EF, pal=1
	tsa_entry 0x1F0, pal=1
	tsa_entry 0x1F1, pal=1
	tsa_entry 0x1F2
	tsa_entry 0x1F3, pal=1
	tsa_entry 0x1F4, pal=1
	tsa_entry 0x1F5, pal=1
	tsa_entry 0x1F6, pal=1
	tsa_entry 0x1F7, pal=1
	tsa_entry 0x1F8, pal=1
	tsa_entry 0x1F9
	tsa_entry 0x1FA
	tsa_entry 0x1FB
	tsa_entry 0x1FC
	tsa_entry 0x1FD
	tsa_entry 0x1FE
	tsa_entry 0x1FF
	tsa_entry 0x200
	tsa_entry 0x201
	tsa_entry 0x202
	tsa_entry 0x203
	tsa_entry 0x204
	tsa_entry 0x205
	tsa_entry 0x206
	tsa_entry 0x207
	tsa_entry 0x1CC
	tsa_entry 0x1CD
	tsa_entry 0x1CE, pal=3
	tsa_entry 0x1CF, pal=3
	tsa_entry 0x1D0
	tsa_entry 0x1D1
	tsa_entry 0x1D2, pal=1
	tsa_entry 0x1D3, pal=1
	tsa_entry 0x1D4
	tsa_entry 0x1D5
	tsa_entry 0x1D6
	tsa_entry 0x1D7, pal=1
	tsa_entry 0x1D8, pal=1
	tsa_entry 0x1D9, pal=1
	tsa_entry 0x1DA, pal=1
	tsa_entry 0x1DB
	tsa_entry 0x1DC
	tsa_entry 0x1DD
	tsa_entry 0x1DE
	tsa_entry 0x1DF
	tsa_entry 0x1E0
	tsa_entry 0x1E1
	tsa_entry 0x1E2
	tsa_entry 0x1E3
	tsa_entry 0x1E4
	tsa_entry 0x1E5
	tsa_entry 0x1E6
	tsa_entry 0x1E7
	tsa_entry 0x1E8
	tsa_entry 0x1E9
	tsa_entry 0x196, pal=3
	tsa_entry 0x196, pal=3
	tsa_entry 0x196, pal=3
	tsa_entry 0x1B1, pal=3
	tsa_entry 0x1B2
	tsa_entry 0x1B3
	tsa_entry 0x1B4
	tsa_entry 0x1B5
	tsa_entry 0x1B6
	tsa_entry 0x1B7
	tsa_entry 0x1B8
	tsa_entry 0x1B9
	tsa_entry 0x1BA
	tsa_entry 0x1BB
	tsa_entry 0x1BC
	tsa_entry 0x1BD
	tsa_entry 0x1BE
	tsa_entry 0x1BF
	tsa_entry 0x1C0
	tsa_entry 0x1C1
	tsa_entry 0x1C2
	tsa_entry 0x1C3
	tsa_entry 0x1C4
	tsa_entry 0x1C5
	tsa_entry 0x1C6
	tsa_entry 0x1C7
	tsa_entry 0x1C8
	tsa_entry 0x1C9
	tsa_entry 0x1CA
	tsa_entry 0x1CB
	tsa_entry 0x196, pal=3
	tsa_entry 0x196, pal=3
	tsa_entry 0x196, pal=3
	tsa_entry 0x197, pal=3
	tsa_entry 0x198
	tsa_entry 0x199
	tsa_entry 0x19A
	tsa_entry 0x19B
	tsa_entry 0x19C
	tsa_entry 0x19D
	tsa_entry 0x19E
	tsa_entry 0x19F
	tsa_entry 0x1A0
	tsa_entry 0x1A1
	tsa_entry 0x1A2
	tsa_entry 0x1A3
	tsa_entry 0x1A4
	tsa_entry 0x1A5
	tsa_entry 0x1A6
	tsa_entry 0x1A7
	tsa_entry 0x1A8
	tsa_entry 0x1A9
	tsa_entry 0x1AA
	tsa_entry 0x1AB
	tsa_entry 0x1AC
	tsa_entry 0x1A8
	tsa_entry 0x1AD
	tsa_entry 0x1AE
	tsa_entry 0x1AF
	tsa_entry 0x1B0
	tsa_entry 0x178, pal=3
	tsa_entry 0x179, pal=3
	tsa_entry 0x17A, pal=3
	tsa_entry 0x17B, pal=3
	tsa_entry 0x17C
	tsa_entry 0x17D
	tsa_entry 0x17E
	tsa_entry 0x17F
	tsa_entry 0x180
	tsa_entry 0x181
	tsa_entry 0x182
	tsa_entry 0x183
	tsa_entry 0x184
	tsa_entry 0x185
	tsa_entry 0x186
	tsa_entry 0x187
	tsa_entry 0x188
	tsa_entry 0x189
	tsa_entry 0x18A
	tsa_entry 0x18B
	tsa_entry 0x18C
	tsa_entry 0x18D
	tsa_entry 0x18E
	tsa_entry 0x18F
	tsa_entry 0x190
	tsa_entry 0x191
	tsa_entry 0x192
	tsa_entry 0x193
	tsa_entry 0x194
	tsa_entry 0x195
	tsa_entry 0x15A, pal=3
	tsa_entry 0x15B, pal=3
	tsa_entry 0x15C, pal=3
	tsa_entry 0x15D, pal=3
	tsa_entry 0x15E
	tsa_entry 0x15F
	tsa_entry 0x160
	tsa_entry 0x161
	tsa_entry 0x162
	tsa_entry 0x163
	tsa_entry 0x164
	tsa_entry 0x165
	tsa_entry 0x166
	tsa_entry 0x167
	tsa_entry 0x168
	tsa_entry 0x169
	tsa_entry 0x16A
	tsa_entry 0x16B
	tsa_entry 0x16C
	tsa_entry 0x16D
	tsa_entry 0x16E
	tsa_entry 0x16F
	tsa_entry 0x170
	tsa_entry 0x171
	tsa_entry 0x172
	tsa_entry 0x173
	tsa_entry 0x174
	tsa_entry 0x175
	tsa_entry 0x176
	tsa_entry 0x177
	tsa_entry 0x13C, pal=3
	tsa_entry 0x13D, pal=3
	tsa_entry 0x13E, pal=3
	tsa_entry 0x13F, pal=3
	tsa_entry 0x140, pal=3
	tsa_entry 0x141
	tsa_entry 0x142
	tsa_entry 0x143
	tsa_entry 0x144
	tsa_entry 0x145
	tsa_entry 0x146
	tsa_entry 0x147
	tsa_entry 0x148
	tsa_entry 0x149
	tsa_entry 0x14A
	tsa_entry 0x14B
	tsa_entry 0x14C
	tsa_entry 0x14D
	tsa_entry 0x14E
	tsa_entry 0x14F
	tsa_entry 0x150
	tsa_entry 0x151
	tsa_entry 0x152
	tsa_entry 0x153
	tsa_entry 0x154
	tsa_entry 0x155
	tsa_entry 0x156
	tsa_entry 0x157
	tsa_entry 0x158
	tsa_entry 0x159
	tsa_entry 0x11E, pal=3
	tsa_entry 0x11F, pal=3
	tsa_entry 0x120, pal=3
	tsa_entry 0x121, pal=3
	tsa_entry 0x122, pal=3
	tsa_entry 0x123, pal=3
	tsa_entry 0x124, pal=3
	tsa_entry 0x125
	tsa_entry 0x126
	tsa_entry 0x127
	tsa_entry 0x128
	tsa_entry 0x129
	tsa_entry 0x12A
	tsa_entry 0x12B
	tsa_entry 0x12C
	tsa_entry 0x12D
	tsa_entry 0x12E
	tsa_entry 0x12F
	tsa_entry 0x130
	tsa_entry 0x131
	tsa_entry 0x132
	tsa_entry 0x133
	tsa_entry 0x134
	tsa_entry 0x135
	tsa_entry 0x136
	tsa_entry 0x137
	tsa_entry 0x138
	tsa_entry 0x139
	tsa_entry 0x13A
	tsa_entry 0x13B
	tsa_entry 0x104, pal=3
	tsa_entry 0x105, pal=3
	tsa_entry 0x106, pal=3
	tsa_entry 0x107, pal=3
	tsa_entry 0x108, pal=3
	tsa_entry 0x109, pal=3
	tsa_entry 0x0D9, pal=3
	tsa_entry 0x0D9, pal=3
	tsa_entry 0x0D9, pal=3
	tsa_entry 0x0D9, pal=3
	tsa_entry 0x10A
	tsa_entry 0x10B
	tsa_entry 0x10C
	tsa_entry 0x10D
	tsa_entry 0x10E
	tsa_entry 0x10F
	tsa_entry 0x110
	tsa_entry 0x111
	tsa_entry 0x112
	tsa_entry 0x113
	tsa_entry 0x114
	tsa_entry 0x115
	tsa_entry 0x116
	tsa_entry 0x117
	tsa_entry 0x118
	tsa_entry 0x119
	tsa_entry 0x11A
	tsa_entry 0x11B
	tsa_entry 0x11C
	tsa_entry 0x11D
	tsa_entry 0x0E6, pal=3
	tsa_entry 0x0E7, pal=3
	tsa_entry 0x0E8, pal=3
	tsa_entry 0x0E9, pal=3
	tsa_entry 0x0EA, pal=3
	tsa_entry 0x0EB, pal=3
	tsa_entry 0x0EC, pal=3
	tsa_entry 0x0ED, pal=3
	tsa_entry 0x0EE, pal=3
	tsa_entry 0x0EF, pal=3
	tsa_entry 0x0F0, pal=3
	tsa_entry 0x0F1, pal=3
	tsa_entry 0x0F2, pal=3
	tsa_entry 0x0F3
	tsa_entry 0x0F4
	tsa_entry 0x0F5
	tsa_entry 0x0F6
	tsa_entry 0x0F7
	tsa_entry 0x0F8
	tsa_entry 0x0F9
	tsa_entry 0x0FA
	tsa_entry 0x0FB
	tsa_entry 0x0FC
	tsa_entry 0x0FD
	tsa_entry 0x0FE
	tsa_entry 0x0FF
	tsa_entry 0x100
	tsa_entry 0x101
	tsa_entry 0x102
	tsa_entry 0x103
	tsa_entry 0x0CA, pal=3
	tsa_entry 0x0CB, pal=3
	tsa_entry 0x0CC, pal=3
	tsa_entry 0x0CD, pal=3
	tsa_entry 0x0CE, pal=3
	tsa_entry 0x0CF, pal=3
	tsa_entry 0x0D0, pal=3
	tsa_entry 0x0D1, pal=3
	tsa_entry 0x0D2, pal=3
	tsa_entry 0x0D3, pal=3
	tsa_entry 0x0D4, pal=3
	tsa_entry 0x0D5, pal=3
	tsa_entry 0x0D6, pal=3
	tsa_entry 0x0D7, pal=3
	tsa_entry 0x0D7, pal=3
	tsa_entry 0x0D8, pal=3
	tsa_entry 0x0D9, pal=3
	tsa_entry 0x0D9, pal=3
	tsa_entry 0x0DA
	tsa_entry 0x0DB
	tsa_entry 0x0DC
	tsa_entry 0x0DD
	tsa_entry 0x0DE
	tsa_entry 0x0DF
	tsa_entry 0x0E0
	tsa_entry 0x0E1
	tsa_entry 0x0E2
	tsa_entry 0x0E3
	tsa_entry 0x0E4
	tsa_entry 0x0E5
	tsa_entry 0x0AC, pal=3
	tsa_entry 0x0AD, pal=3
	tsa_entry 0x0AE, pal=3
	tsa_entry 0x0AF, pal=3
	tsa_entry 0x0B0, pal=3
	tsa_entry 0x0B1, pal=3
	tsa_entry 0x0B2, pal=3
	tsa_entry 0x0B3, pal=3
	tsa_entry 0x0B4, pal=3
	tsa_entry 0x0B5, pal=3
	tsa_entry 0x0B6, pal=3
	tsa_entry 0x0B7, pal=3
	tsa_entry 0x0B8, pal=3
	tsa_entry 0x0B9, pal=3
	tsa_entry 0x0BA, pal=3
	tsa_entry 0x0BB, pal=3
	tsa_entry 0x0BC, pal=3
	tsa_entry 0x0BD, pal=3
	tsa_entry 0x0BE, pal=3
	tsa_entry 0x0BF, pal=3
	tsa_entry 0x0C0, pal=3
	tsa_entry 0x0C1, pal=3
	tsa_entry 0x0C2, pal=3
	tsa_entry 0x0C3, pal=3
	tsa_entry 0x0C4, pal=3
	tsa_entry 0x0C5, pal=3
	tsa_entry 0x0C6, pal=3
	tsa_entry 0x0C7, pal=3
	tsa_entry 0x0C8, pal=3
	tsa_entry 0x0C9, pal=3
	tsa_entry 0x08E, pal=3
	tsa_entry 0x08F, pal=3
	tsa_entry 0x090, pal=3
	tsa_entry 0x091, pal=3
	tsa_entry 0x092, pal=3
	tsa_entry 0x093, pal=3
	tsa_entry 0x094, pal=3
	tsa_entry 0x095, pal=3
	tsa_entry 0x096, pal=3
	tsa_entry 0x097, pal=3
	tsa_entry 0x098, pal=3
	tsa_entry 0x099, pal=3
	tsa_entry 0x09A, pal=3
	tsa_entry 0x09B, pal=3
	tsa_entry 0x09C, pal=3
	tsa_entry 0x09D, pal=3
	tsa_entry 0x09E, pal=3
	tsa_entry 0x09F, pal=3
	tsa_entry 0x0A0, pal=3
	tsa_entry 0x0A1, pal=3
	tsa_entry 0x0A2, pal=3
	tsa_entry 0x0A3, pal=3
	tsa_entry 0x0A4, pal=3
	tsa_entry 0x0A5, pal=3
	tsa_entry 0x0A6, pal=3
	tsa_entry 0x0A7, pal=3
	tsa_entry 0x0A8, pal=3
	tsa_entry 0x0A9, pal=3
	tsa_entry 0x0AA, pal=3
	tsa_entry 0x0AB, pal=3
	tsa_entry 0x02F, pal=3
	tsa_entry 0x02F, pal=3
	tsa_entry 0x02F, pal=3
	tsa_entry 0x074, pal=3
	tsa_entry 0x075, pal=3
	tsa_entry 0x076, pal=3
	tsa_entry 0x077, pal=3
	tsa_entry 0x078, pal=3
	tsa_entry 0x079, pal=3
	tsa_entry 0x07A, pal=3
	tsa_entry 0x07B, pal=3
	tsa_entry 0x078, pal=3
	tsa_entry 0x07C, pal=3
	tsa_entry 0x07D, pal=3
	tsa_entry 0x07E, pal=3
	tsa_entry 0x07F, pal=3
	tsa_entry 0x080, pal=3
	tsa_entry 0x081, pal=3
	tsa_entry 0x082, pal=3
	tsa_entry 0x083, pal=3
	tsa_entry 0x084, pal=3
	tsa_entry 0x085, pal=3
	tsa_entry 0x086, pal=3
	tsa_entry 0x087, pal=3
	tsa_entry 0x088, pal=3
	tsa_entry 0x089, pal=3
	tsa_entry 0x08A, pal=3
	tsa_entry 0x08B, pal=3
	tsa_entry 0x08C, pal=3
	tsa_entry 0x08D, pal=3
	tsa_entry 0x057, pal=3
	tsa_entry 0x02F, pal=3
	tsa_entry 0x058, pal=3
	tsa_entry 0x059, pal=3
	tsa_entry 0x05A, pal=3
	tsa_entry 0x05B, pal=3
	tsa_entry 0x05C, pal=3
	tsa_entry 0x05D, pal=3
	tsa_entry 0x05E, pal=3
	tsa_entry 0x05F, pal=3
	tsa_entry 0x060, pal=3
	tsa_entry 0x061, pal=3
	tsa_entry 0x062, pal=3
	tsa_entry 0x063, pal=3
	tsa_entry 0x064, pal=3
	tsa_entry 0x065, pal=3
	tsa_entry 0x066, pal=3
	tsa_entry 0x067, pal=3
	tsa_entry 0x068, pal=3
	tsa_entry 0x069, pal=3
	tsa_entry 0x06A, pal=3
	tsa_entry 0x06B, pal=3
	tsa_entry 0x06C, pal=3
	tsa_entry 0x06D, pal=3
	tsa_entry 0x06E, pal=3
	tsa_entry 0x06F, pal=3
	tsa_entry 0x070, pal=3
	tsa_entry 0x071, pal=3
	tsa_entry 0x072, pal=3
	tsa_entry 0x073, pal=3
	tsa_entry 0x039, pal=3
	tsa_entry 0x03A, pal=3
	tsa_entry 0x03B, pal=3
	tsa_entry 0x03C, pal=3
	tsa_entry 0x03D, pal=3
	tsa_entry 0x03E, pal=3
	tsa_entry 0x03F, pal=3
	tsa_entry 0x040, pal=3
	tsa_entry 0x041, pal=3
	tsa_entry 0x042, pal=3
	tsa_entry 0x043, pal=3
	tsa_entry 0x044, pal=3
	tsa_entry 0x045, pal=3
	tsa_entry 0x046, pal=3
	tsa_entry 0x047, pal=3
	tsa_entry 0x048, pal=3
	tsa_entry 0x049, pal=3
	tsa_entry 0x04A, pal=3
	tsa_entry 0x04B, pal=3
	tsa_entry 0x04C, pal=3
	tsa_entry 0x04D, pal=3
	tsa_entry 0x04E, pal=3
	tsa_entry 0x04F, pal=3
	tsa_entry 0x050, pal=3
	tsa_entry 0x051, pal=3
	tsa_entry 0x052, pal=3
	tsa_entry 0x053, pal=3
	tsa_entry 0x054, pal=3
	tsa_entry 0x055, pal=3
	tsa_entry 0x056, pal=3
	tsa_entry 0x01E, pal=3
	tsa_entry 0x01F, pal=3
	tsa_entry 0x020, pal=3
	tsa_entry 0x021, pal=3
	tsa_entry 0x022, pal=3
	tsa_entry 0x023, pal=3
	tsa_entry 0x024, pal=3
	tsa_entry 0x025, pal=3
	tsa_entry 0x026, pal=3
	tsa_entry 0x027, pal=3
	tsa_entry 0x028, pal=3
	tsa_entry 0x029, pal=3
	tsa_entry 0x02A, pal=3
	tsa_entry 0x02B, pal=3
	tsa_entry 0x02C, pal=3
	tsa_entry 0x02D, pal=3
	tsa_entry 0x02E, pal=3
	tsa_entry 0x02F, pal=3
	tsa_entry 0x030, pal=3
	tsa_entry 0x031, pal=3
	tsa_entry 0x032, pal=3
	tsa_entry 0x033, pal=3
	tsa_entry 0x034, pal=3
	tsa_entry 0x035, pal=3
	tsa_entry 0x02F, pal=3
	tsa_entry 0x02F, pal=3
	tsa_entry 0x036, pal=3
	tsa_entry 0x037, pal=3
	tsa_entry 0x02F, pal=3
	tsa_entry 0x038, pal=3
	tsa_entry 0x000, pal=3
	tsa_entry 0x001, pal=3
	tsa_entry 0x002, pal=3
	tsa_entry 0x003, pal=3
	tsa_entry 0x004, pal=3
	tsa_entry 0x005, pal=3
	tsa_entry 0x006, pal=3
	tsa_entry 0x007, pal=3
	tsa_entry 0x008, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x00A, pal=3
	tsa_entry 0x00B, pal=3
	tsa_entry 0x00C, pal=3
	tsa_entry 0x00D, pal=3
	tsa_entry 0x00E, pal=3
	tsa_entry 0x00F, pal=3
	tsa_entry 0x010, pal=3
	tsa_entry 0x011, pal=3
	tsa_entry 0x012, pal=3
	tsa_entry 0x013, pal=3
	tsa_entry 0x014, pal=3
	tsa_entry 0x015, pal=3
	tsa_entry 0x016, pal=3
	tsa_entry 0x017, pal=3
	tsa_entry 0x018, pal=3
	tsa_entry 0x019, pal=3
	tsa_entry 0x01A, pal=3
	tsa_entry 0x01B, pal=3
	tsa_entry 0x01C, pal=3
	tsa_entry 0x01D, pal=3
	tsa_entry 0x000
