	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x31D, pal=1
	tsa_entry 0x0F4
	tsa_entry 0x0F5
	tsa_entry 0x036, vflip=1
	tsa_entry 0x037, vflip=1
	tsa_entry 0x038, vflip=1
	tsa_entry 0x039, vflip=1
	tsa_entry 0x03A, vflip=1
	tsa_entry 0x03B, vflip=1
	tsa_entry 0x03C, vflip=1
	tsa_entry 0x03D, vflip=1
	tsa_entry 0x03E, vflip=1
	tsa_entry 0x03F, vflip=1
	tsa_entry 0x040, vflip=1
	tsa_entry 0x041, vflip=1
	tsa_entry 0x042, vflip=1
	tsa_entry 0x043, vflip=1
	tsa_entry 0x044, vflip=1
	tsa_entry 0x045, vflip=1
	tsa_entry 0x046, vflip=1
	tsa_entry 0x047, vflip=1
	tsa_entry 0x048, vflip=1
	tsa_entry 0x049, vflip=1
	tsa_entry 0x04A, vflip=1
	tsa_entry 0x04B, vflip=1
	tsa_entry 0x04C, vflip=1
	tsa_entry 0x04D, vflip=1
	tsa_entry 0x0F6
	tsa_entry 0x0F7
	tsa_entry 0x0F5, hflip=1
	tsa_entry 0x0F4, hflip=1
	tsa_entry 0x0F0
	tsa_entry 0x0F1
	tsa_entry 0x050, vflip=1
	tsa_entry 0x051, vflip=1
	tsa_entry 0x052, vflip=1
	tsa_entry 0x053, vflip=1
	tsa_entry 0x054, vflip=1
	tsa_entry 0x055, vflip=1
	tsa_entry 0x056, vflip=1
	tsa_entry 0x057, vflip=1
	tsa_entry 0x058, vflip=1
	tsa_entry 0x059, vflip=1
	tsa_entry 0x05A, vflip=1
	tsa_entry 0x05B, vflip=1
	tsa_entry 0x05C, vflip=1
	tsa_entry 0x05D, vflip=1
	tsa_entry 0x05E, vflip=1
	tsa_entry 0x05F, vflip=1
	tsa_entry 0x060, vflip=1
	tsa_entry 0x061, vflip=1
	tsa_entry 0x062, vflip=1
	tsa_entry 0x063, vflip=1
	tsa_entry 0x064, vflip=1
	tsa_entry 0x065, vflip=1
	tsa_entry 0x066, vflip=1
	tsa_entry 0x067, vflip=1
	tsa_entry 0x0F2
	tsa_entry 0x0F3
	tsa_entry 0x0F1, hflip=1
	tsa_entry 0x0F0, hflip=1
	tsa_entry 0x081, hflip=1, vflip=1
	tsa_entry 0x080, hflip=1, vflip=1
	tsa_entry 0x06A, vflip=1
	tsa_entry 0x06B, vflip=1
	tsa_entry 0x052, vflip=1
	tsa_entry 0x06C, vflip=1
	tsa_entry 0x06D, vflip=1
	tsa_entry 0x06E, vflip=1
	tsa_entry 0x06F, vflip=1
	tsa_entry 0x070, vflip=1
	tsa_entry 0x071, vflip=1
	tsa_entry 0x072, vflip=1
	tsa_entry 0x073, vflip=1
	tsa_entry 0x074, vflip=1
	tsa_entry 0x075, vflip=1
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x077, vflip=1
	tsa_entry 0x078, vflip=1
	tsa_entry 0x079, vflip=1
	tsa_entry 0x07A, vflip=1
	tsa_entry 0x07B, vflip=1
	tsa_entry 0x07C, vflip=1
	tsa_entry 0x07D, vflip=1
	tsa_entry 0x07E, vflip=1
	tsa_entry 0x07F, vflip=1
	tsa_entry 0x080, vflip=1
	tsa_entry 0x081, vflip=1
	tsa_entry 0x097, hflip=1, vflip=1
	tsa_entry 0x096, hflip=1, vflip=1
	tsa_entry 0x084, vflip=1
	tsa_entry 0x085, vflip=1
	tsa_entry 0x086, vflip=1
	tsa_entry 0x087, vflip=1
	tsa_entry 0x088, vflip=1
	tsa_entry 0x089, vflip=1
	tsa_entry 0x08A, vflip=1
	tsa_entry 0x08B, vflip=1
	tsa_entry 0x08C, vflip=1
	tsa_entry 0x08D, vflip=1
	tsa_entry 0x08E, vflip=1
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x08F, vflip=1
	tsa_entry 0x090, vflip=1
	tsa_entry 0x091, vflip=1
	tsa_entry 0x092, vflip=1
	tsa_entry 0x093, vflip=1
	tsa_entry 0x094, vflip=1
	tsa_entry 0x095, vflip=1
	tsa_entry 0x096, vflip=1
	tsa_entry 0x097, vflip=1
	tsa_entry 0x098, vflip=1
	tsa_entry 0x099, vflip=1
	tsa_entry 0x09A, vflip=1
	tsa_entry 0x09B, vflip=1
	tsa_entry 0x09C, vflip=1
	tsa_entry 0x09D, vflip=1
	tsa_entry 0x09E, vflip=1
	tsa_entry 0x09F, vflip=1
	tsa_entry 0x0A0, vflip=1
	tsa_entry 0x0A1, vflip=1
	tsa_entry 0x0A2, vflip=1
	tsa_entry 0x0A3, vflip=1
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x08F, vflip=1
	tsa_entry 0x0A4, vflip=1
	tsa_entry 0x0A5, vflip=1
	tsa_entry 0x0A6, vflip=1
	tsa_entry 0x0A7, vflip=1
	tsa_entry 0x0A8, vflip=1
	tsa_entry 0x0A9, vflip=1
	tsa_entry 0x0AA, vflip=1
	tsa_entry 0x0AB, vflip=1
	tsa_entry 0x09A, vflip=1
	tsa_entry 0x0AC, vflip=1
	tsa_entry 0x0AD, vflip=1
	tsa_entry 0x0AE, vflip=1
	tsa_entry 0x0AF, vflip=1
	tsa_entry 0x0B0, vflip=1
	tsa_entry 0x0B1, vflip=1
	tsa_entry 0x0B2, vflip=1
	tsa_entry 0x0B3, vflip=1
	tsa_entry 0x0B4, vflip=1
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x0B5, vflip=1
	tsa_entry 0x0B6, vflip=1
	tsa_entry 0x0B7, vflip=1
	tsa_entry 0x0B8, vflip=1
	tsa_entry 0x0B9, vflip=1
	tsa_entry 0x0BA, vflip=1
	tsa_entry 0x0BB, vflip=1
	tsa_entry 0x0BC, vflip=1
	tsa_entry 0x0BD, vflip=1
	tsa_entry 0x0BE, vflip=1
	tsa_entry 0x0BF, vflip=1
	tsa_entry 0x0C0, vflip=1
	tsa_entry 0x0C1, vflip=1
	tsa_entry 0x0C2, vflip=1
	tsa_entry 0x0C3, vflip=1
	tsa_entry 0x0C4, vflip=1
	tsa_entry 0x0C5, vflip=1
	tsa_entry 0x0C6, vflip=1
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x0C7, vflip=1
	tsa_entry 0x0C8, vflip=1
	tsa_entry 0x0C9, vflip=1
	tsa_entry 0x0CA, vflip=1
	tsa_entry 0x0CB, vflip=1
	tsa_entry 0x0CC, vflip=1
	tsa_entry 0x0CD, vflip=1
	tsa_entry 0x0CE, vflip=1
	tsa_entry 0x0CF, vflip=1
	tsa_entry 0x0D0, vflip=1
	tsa_entry 0x0D1, vflip=1
	tsa_entry 0x0D2, vflip=1
	tsa_entry 0x0D3, vflip=1
	tsa_entry 0x0D4, vflip=1
	tsa_entry 0x0D5, vflip=1
	tsa_entry 0x0D6, vflip=1
	tsa_entry 0x0D7, vflip=1
	tsa_entry 0x0D8, vflip=1
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x0D9, vflip=1
	tsa_entry 0x0DA, vflip=1
	tsa_entry 0x0DB, vflip=1
	tsa_entry 0x0DC, vflip=1
	tsa_entry 0x0DD, vflip=1
	tsa_entry 0x0DE, vflip=1
	tsa_entry 0x0DF, vflip=1
	tsa_entry 0x0E0, vflip=1
	tsa_entry 0x0E1, vflip=1
	tsa_entry 0x0E2, vflip=1
	tsa_entry 0x0E3, vflip=1
	tsa_entry 0x0E4, vflip=1
	tsa_entry 0x0E5, vflip=1
	tsa_entry 0x0E6, vflip=1
	tsa_entry 0x0E7, vflip=1
	tsa_entry 0x0E8, vflip=1
	tsa_entry 0x0E9, vflip=1
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x0EA, vflip=1
	tsa_entry 0x0EB, vflip=1
	tsa_entry 0x0EC, vflip=1
	tsa_entry 0x0ED, vflip=1
	tsa_entry 0x0EE, vflip=1
	tsa_entry 0x0EF, vflip=1
	tsa_entry 0x0DF
	tsa_entry 0x0E0
	tsa_entry 0x0E1
	tsa_entry 0x0E2
	tsa_entry 0x0E3
	tsa_entry 0x0E4
	tsa_entry 0x0E5
	tsa_entry 0x0E6
	tsa_entry 0x0E7
	tsa_entry 0x0E8
	tsa_entry 0x0E9
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x0EA
	tsa_entry 0x0EB
	tsa_entry 0x0EC
	tsa_entry 0x0ED
	tsa_entry 0x0EE
	tsa_entry 0x0EF
	tsa_entry 0x0CE
	tsa_entry 0x0CF
	tsa_entry 0x0D0
	tsa_entry 0x0D1
	tsa_entry 0x0D2
	tsa_entry 0x0D3
	tsa_entry 0x0D4
	tsa_entry 0x0D5
	tsa_entry 0x0D6
	tsa_entry 0x0D7
	tsa_entry 0x0D8
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x0D9
	tsa_entry 0x0DA
	tsa_entry 0x0DB
	tsa_entry 0x0DC
	tsa_entry 0x0DD
	tsa_entry 0x0DE
	tsa_entry 0x0BC
	tsa_entry 0x0BD
	tsa_entry 0x0BE
	tsa_entry 0x0BF
	tsa_entry 0x0C0
	tsa_entry 0x0C1
	tsa_entry 0x0C2
	tsa_entry 0x0C3
	tsa_entry 0x0C4
	tsa_entry 0x0C5
	tsa_entry 0x0C6
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x0C7
	tsa_entry 0x0C8
	tsa_entry 0x0C9
	tsa_entry 0x0CA
	tsa_entry 0x0CB
	tsa_entry 0x0CC
	tsa_entry 0x0CD
	tsa_entry 0x0AB
	tsa_entry 0x09A
	tsa_entry 0x0AC
	tsa_entry 0x0AD
	tsa_entry 0x0AE
	tsa_entry 0x0AF
	tsa_entry 0x0B0
	tsa_entry 0x0B1
	tsa_entry 0x0B2
	tsa_entry 0x0B3
	tsa_entry 0x0B4
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x0B5
	tsa_entry 0x0B6
	tsa_entry 0x0B7
	tsa_entry 0x0B8
	tsa_entry 0x0B9
	tsa_entry 0x0BA
	tsa_entry 0x0BB
	tsa_entry 0x098
	tsa_entry 0x099
	tsa_entry 0x09A
	tsa_entry 0x09B
	tsa_entry 0x09C
	tsa_entry 0x09D
	tsa_entry 0x09E
	tsa_entry 0x09F
	tsa_entry 0x0A0
	tsa_entry 0x0A1
	tsa_entry 0x0A2
	tsa_entry 0x0A3
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x08F
	tsa_entry 0x0A4
	tsa_entry 0x0A5
	tsa_entry 0x0A6
	tsa_entry 0x0A7
	tsa_entry 0x0A8
	tsa_entry 0x0A9
	tsa_entry 0x0AA
	tsa_entry 0x082
	tsa_entry 0x083
	tsa_entry 0x084
	tsa_entry 0x085
	tsa_entry 0x086
	tsa_entry 0x087
	tsa_entry 0x088
	tsa_entry 0x089
	tsa_entry 0x08A
	tsa_entry 0x08B
	tsa_entry 0x08C
	tsa_entry 0x08D
	tsa_entry 0x08E
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x08F
	tsa_entry 0x090
	tsa_entry 0x091
	tsa_entry 0x092
	tsa_entry 0x093
	tsa_entry 0x094
	tsa_entry 0x095
	tsa_entry 0x096
	tsa_entry 0x097
	tsa_entry 0x068
	tsa_entry 0x069
	tsa_entry 0x06A
	tsa_entry 0x06B
	tsa_entry 0x052
	tsa_entry 0x06C
	tsa_entry 0x06D
	tsa_entry 0x06E
	tsa_entry 0x06F
	tsa_entry 0x070
	tsa_entry 0x071
	tsa_entry 0x072
	tsa_entry 0x073
	tsa_entry 0x074
	tsa_entry 0x075
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x076
	tsa_entry 0x077
	tsa_entry 0x078
	tsa_entry 0x079
	tsa_entry 0x07A
	tsa_entry 0x07B
	tsa_entry 0x07C
	tsa_entry 0x07D
	tsa_entry 0x07E
	tsa_entry 0x07F
	tsa_entry 0x080
	tsa_entry 0x081
	tsa_entry 0x04E
	tsa_entry 0x04F
	tsa_entry 0x050
	tsa_entry 0x051
	tsa_entry 0x052
	tsa_entry 0x053
	tsa_entry 0x054
	tsa_entry 0x055
	tsa_entry 0x056
	tsa_entry 0x057
	tsa_entry 0x058
	tsa_entry 0x059
	tsa_entry 0x05A
	tsa_entry 0x05B
	tsa_entry 0x05C
	tsa_entry 0x05D
	tsa_entry 0x05E
	tsa_entry 0x05F
	tsa_entry 0x060
	tsa_entry 0x061
	tsa_entry 0x062
	tsa_entry 0x063
	tsa_entry 0x064
	tsa_entry 0x065
	tsa_entry 0x066
	tsa_entry 0x067
	tsa_entry 0x051, hflip=1
	tsa_entry 0x050, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x04E, hflip=1
	tsa_entry 0x034
	tsa_entry 0x035
	tsa_entry 0x036
	tsa_entry 0x037
	tsa_entry 0x038
	tsa_entry 0x039
	tsa_entry 0x03A
	tsa_entry 0x03B
	tsa_entry 0x03C
	tsa_entry 0x03D
	tsa_entry 0x03E
	tsa_entry 0x03F
	tsa_entry 0x040
	tsa_entry 0x041
	tsa_entry 0x042
	tsa_entry 0x043
	tsa_entry 0x044
	tsa_entry 0x045
	tsa_entry 0x046
	tsa_entry 0x047
	tsa_entry 0x048
	tsa_entry 0x049
	tsa_entry 0x04A
	tsa_entry 0x04B
	tsa_entry 0x04C
	tsa_entry 0x04D
	tsa_entry 0x037, hflip=1
	tsa_entry 0x036, hflip=1
	tsa_entry 0x035, hflip=1
	tsa_entry 0x034, hflip=1
	tsa_entry 0x01A
	tsa_entry 0x01B
	tsa_entry 0x01C
	tsa_entry 0x01D
	tsa_entry 0x01E
	tsa_entry 0x01F
	tsa_entry 0x020
	tsa_entry 0x021
	tsa_entry 0x022
	tsa_entry 0x023
	tsa_entry 0x024
	tsa_entry 0x025
	tsa_entry 0x026
	tsa_entry 0x027
	tsa_entry 0x028
	tsa_entry 0x029
	tsa_entry 0x02A
	tsa_entry 0x02B
	tsa_entry 0x02C
	tsa_entry 0x02D
	tsa_entry 0x02E
	tsa_entry 0x02F
	tsa_entry 0x030
	tsa_entry 0x031
	tsa_entry 0x032
	tsa_entry 0x033
	tsa_entry 0x01D, hflip=1
	tsa_entry 0x01C, hflip=1
	tsa_entry 0x01B, hflip=1
	tsa_entry 0x01A, hflip=1
	tsa_entry 0x0F8
	tsa_entry 0x001
	tsa_entry 0x002
	tsa_entry 0x003
	tsa_entry 0x004
	tsa_entry 0x005
	tsa_entry 0x006
	tsa_entry 0x007
	tsa_entry 0x008
	tsa_entry 0x009
	tsa_entry 0x00A
	tsa_entry 0x00B
	tsa_entry 0x00C
	tsa_entry 0x00D
	tsa_entry 0x00E
	tsa_entry 0x00F
	tsa_entry 0x010
	tsa_entry 0x011
	tsa_entry 0x012
	tsa_entry 0x013
	tsa_entry 0x014
	tsa_entry 0x015
	tsa_entry 0x016
	tsa_entry 0x017
	tsa_entry 0x018
	tsa_entry 0x019
	tsa_entry 0x003, hflip=1
	tsa_entry 0x002, hflip=1
	tsa_entry 0x001, hflip=1
	tsa_entry 0x0F8, hflip=1
