	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x10A
	tsa_entry 0x02F, pal=2
	tsa_entry 0x030, pal=2
	tsa_entry 0x031, pal=2
	tsa_entry 0x032, pal=2
	tsa_entry 0x033, pal=2
	tsa_entry 0x034, pal=2
	tsa_entry 0x035, pal=2
	tsa_entry 0x036, pal=2
	tsa_entry 0x037, pal=2
	tsa_entry 0x038, pal=2
	tsa_entry 0x039, pal=2
	tsa_entry 0x00F, pal=2
	tsa_entry 0x010, pal=1
	tsa_entry 0x011, pal=2
	tsa_entry 0x012, pal=2
	tsa_entry 0x013, pal=1
	tsa_entry 0x014, pal=2
	tsa_entry 0x015, pal=2
	tsa_entry 0x016, pal=1
	tsa_entry 0x017, pal=2
	tsa_entry 0x018, pal=1
	tsa_entry 0x019, pal=1
	tsa_entry 0x000
