	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x31D
	tsa_entry 0x02F
	tsa_entry 0x030
	tsa_entry 0x031
	tsa_entry 0x032
	tsa_entry 0x033
	tsa_entry 0x034
	tsa_entry 0x035
	tsa_entry 0x036
	tsa_entry 0x037
	tsa_entry 0x038
	tsa_entry 0x039
	tsa_entry 0x03A
	tsa_entry 0x03B
	tsa_entry 0x03B
	tsa_entry 0x03B
	tsa_entry 0x03B, hflip=1
	tsa_entry 0x03B, hflip=1
	tsa_entry 0x03B, hflip=1
	tsa_entry 0x03A, hflip=1
	tsa_entry 0x039, hflip=1
	tsa_entry 0x038, hflip=1
	tsa_entry 0x037, hflip=1
	tsa_entry 0x036, hflip=1
	tsa_entry 0x035, hflip=1
	tsa_entry 0x034, hflip=1
	tsa_entry 0x033, hflip=1
	tsa_entry 0x032, hflip=1
	tsa_entry 0x031, hflip=1
	tsa_entry 0x030, hflip=1
	tsa_entry 0x02F, hflip=1
	tsa_entry 0x020
	tsa_entry 0x021
	tsa_entry 0x022
	tsa_entry 0x023
	tsa_entry 0x024
	tsa_entry 0x025
	tsa_entry 0x026
	tsa_entry 0x027
	tsa_entry 0x028
	tsa_entry 0x029
	tsa_entry 0x02A
	tsa_entry 0x02B
	tsa_entry 0x02C
	tsa_entry 0x02C
	tsa_entry 0x02C
	tsa_entry 0x02C, hflip=1
	tsa_entry 0x02C, hflip=1
	tsa_entry 0x02C, hflip=1
	tsa_entry 0x02B, hflip=1
	tsa_entry 0x02A, hflip=1
	tsa_entry 0x029, hflip=1
	tsa_entry 0x028, hflip=1
	tsa_entry 0x027, hflip=1
	tsa_entry 0x026, hflip=1
	tsa_entry 0x025, hflip=1
	tsa_entry 0x024, hflip=1
	tsa_entry 0x023, hflip=1
	tsa_entry 0x022, hflip=1
	tsa_entry 0x021, hflip=1
	tsa_entry 0x020, hflip=1
	tsa_entry 0x011
	tsa_entry 0x012
	tsa_entry 0x013
	tsa_entry 0x014
	tsa_entry 0x015
	tsa_entry 0x016
	tsa_entry 0x017
	tsa_entry 0x018
	tsa_entry 0x019
	tsa_entry 0x01A
	tsa_entry 0x01B
	tsa_entry 0x01C
	tsa_entry 0x01D
	tsa_entry 0x01D
	tsa_entry 0x01D
	tsa_entry 0x01D, hflip=1
	tsa_entry 0x01D, hflip=1
	tsa_entry 0x01D, hflip=1
	tsa_entry 0x01C, hflip=1
	tsa_entry 0x01B, hflip=1
	tsa_entry 0x01A, hflip=1
	tsa_entry 0x019, hflip=1
	tsa_entry 0x018, hflip=1
	tsa_entry 0x017, hflip=1
	tsa_entry 0x016, hflip=1
	tsa_entry 0x015, hflip=1
	tsa_entry 0x014, hflip=1
	tsa_entry 0x013, hflip=1
	tsa_entry 0x012, hflip=1
	tsa_entry 0x011, hflip=1
	tsa_entry 0x002
	tsa_entry 0x003
	tsa_entry 0x004
	tsa_entry 0x005
	tsa_entry 0x006
	tsa_entry 0x007
	tsa_entry 0x008
	tsa_entry 0x009
	tsa_entry 0x00A
	tsa_entry 0x00B
	tsa_entry 0x00C
	tsa_entry 0x00D
	tsa_entry 0x00E
	tsa_entry 0x00E
	tsa_entry 0x00E
	tsa_entry 0x00E, hflip=1
	tsa_entry 0x00E, hflip=1
	tsa_entry 0x00E, hflip=1
	tsa_entry 0x00D, hflip=1
	tsa_entry 0x00C, hflip=1
	tsa_entry 0x00B, hflip=1
	tsa_entry 0x00A, hflip=1
	tsa_entry 0x009, hflip=1
	tsa_entry 0x008, hflip=1
	tsa_entry 0x007, hflip=1
	tsa_entry 0x006, hflip=1
	tsa_entry 0x005, hflip=1
	tsa_entry 0x004, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x002, hflip=1
	tsa_entry 0x000
	tsa_entry 0x355, pal=5
	tsa_entry 0x2DF
	tsa_entry 0x2BE
	tsa_entry 0x29D
	tsa_entry 0x27C
	tsa_entry 0x25B
	tsa_entry 0x219
	tsa_entry 0x1F8
	tsa_entry 0x1D7
	tsa_entry 0x1B6
	tsa_entry 0x195
	tsa_entry 0x173
	tsa_entry 0x132
	tsa_entry 0x111
	tsa_entry 0x0F0
	tsa_entry 0x000
