	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x31B, vflip=1
	tsa_entry 0x01A
	tsa_entry 0x01B
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x030, pal=2
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x01C
	tsa_entry 0x020
	tsa_entry 0x021
	tsa_entry 0x006
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x03E
	tsa_entry 0x040
	tsa_entry 0x042
	tsa_entry 0x044
	tsa_entry 0x02F, pal=2
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x03E, pal=3
	tsa_entry 0x040, pal=3
	tsa_entry 0x042, pal=3
	tsa_entry 0x044, pal=3
	tsa_entry 0x045, pal=3
	tsa_entry 0x006
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x03E
	tsa_entry 0x040
	tsa_entry 0x042
	tsa_entry 0x02F, pal=2
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x03E, pal=3
	tsa_entry 0x040, pal=3
	tsa_entry 0x042, pal=3
	tsa_entry 0x043, pal=3
	tsa_entry 0x006
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x03E
	tsa_entry 0x040
	tsa_entry 0x02F, pal=2
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x03E, pal=3
	tsa_entry 0x040, pal=3
	tsa_entry 0x041, pal=3
	tsa_entry 0x006
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x03E
	tsa_entry 0x02F, pal=2
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x03E, pal=3
	tsa_entry 0x03F, pal=3
	tsa_entry 0x006
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x02F, pal=2
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x00A, pal=3
	tsa_entry 0x006
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x02F, pal=2
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x00A, pal=3
	tsa_entry 0x006
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x02F, pal=2
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x00A, pal=3
	tsa_entry 0x006
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x02F, pal=2
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x00A, pal=3
	tsa_entry 0x006
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x02F, pal=2
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x00A, pal=3
	tsa_entry 0x006
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x009
	tsa_entry 0x02F, pal=2
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x00A, pal=3
	tsa_entry 0x061
	tsa_entry 0x062
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x02E, pal=2
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x003
	tsa_entry 0x004
	tsa_entry 0x005
