	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x30A
	tsa_entry 0x060, pal=1
	tsa_entry 0x061, pal=1
	tsa_entry 0x062, pal=1
	tsa_entry 0x063, pal=1
	tsa_entry 0x064, pal=1
	tsa_entry 0x065, pal=1
	tsa_entry 0x066, pal=1
	tsa_entry 0x067, pal=1
	tsa_entry 0x068, pal=1
	tsa_entry 0x069, pal=1
	tsa_entry 0x06A, pal=1
	tsa_entry 0x040, pal=1
	tsa_entry 0x041, pal=1
	tsa_entry 0x042, pal=1
	tsa_entry 0x043, pal=1
	tsa_entry 0x044, pal=1
	tsa_entry 0x045, pal=1
	tsa_entry 0x046, pal=1
	tsa_entry 0x047, pal=1
	tsa_entry 0x048, pal=1
	tsa_entry 0x049, pal=1
	tsa_entry 0x04A, pal=1
	tsa_entry 0x020, pal=1
	tsa_entry 0x021, pal=1
	tsa_entry 0x022, pal=1
	tsa_entry 0x023, pal=1
	tsa_entry 0x024, pal=1
	tsa_entry 0x025, pal=1
	tsa_entry 0x026, pal=1
	tsa_entry 0x027, pal=1
	tsa_entry 0x028, pal=1
	tsa_entry 0x029, pal=1
	tsa_entry 0x02A, pal=1
	tsa_entry 0x000, pal=1
	tsa_entry 0x001, pal=1
	tsa_entry 0x002, pal=1
	tsa_entry 0x003, pal=1
	tsa_entry 0x004, pal=1
	tsa_entry 0x005, pal=1
	tsa_entry 0x006, pal=1
	tsa_entry 0x007, pal=1
	tsa_entry 0x008, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x00A, pal=1
	tsa_entry 0x000
