	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x111, pal=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x07F, vflip=1
	tsa_entry 0x001, vflip=1
	tsa_entry 0x001, hflip=1, vflip=1
	tsa_entry 0x07F, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x005, vflip=1
	tsa_entry 0x006, vflip=1
	tsa_entry 0x007, vflip=1
	tsa_entry 0x008, vflip=1
	tsa_entry 0x009, vflip=1
	tsa_entry 0x009, hflip=1, vflip=1
	tsa_entry 0x008, hflip=1, vflip=1
	tsa_entry 0x007, hflip=1, vflip=1
	tsa_entry 0x006, hflip=1, vflip=1
	tsa_entry 0x005, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x010, vflip=1
	tsa_entry 0x011, vflip=1
	tsa_entry 0x012, vflip=1
	tsa_entry 0x013, vflip=1
	tsa_entry 0x014, vflip=1
	tsa_entry 0x014, vflip=1
	tsa_entry 0x014, hflip=1, vflip=1
	tsa_entry 0x014, hflip=1, vflip=1
	tsa_entry 0x013, hflip=1, vflip=1
	tsa_entry 0x012, hflip=1, vflip=1
	tsa_entry 0x011, hflip=1, vflip=1
	tsa_entry 0x010, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x010, vflip=1
	tsa_entry 0x01C, vflip=1
	tsa_entry 0x01D, vflip=1
	tsa_entry 0x01E, vflip=1
	tsa_entry 0x01F, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x01F, hflip=1, vflip=1
	tsa_entry 0x01E, hflip=1, vflip=1
	tsa_entry 0x01D, hflip=1, vflip=1
	tsa_entry 0x01C, hflip=1, vflip=1
	tsa_entry 0x010, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x026, vflip=1
	tsa_entry 0x027, vflip=1
	tsa_entry 0x028, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x029, vflip=1
	tsa_entry 0x02A, vflip=1
	tsa_entry 0x02A, hflip=1, vflip=1
	tsa_entry 0x029, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x028, hflip=1, vflip=1
	tsa_entry 0x027, hflip=1, vflip=1
	tsa_entry 0x026, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x033, vflip=1
	tsa_entry 0x034, vflip=1
	tsa_entry 0x035, vflip=1
	tsa_entry 0x036, vflip=1
	tsa_entry 0x000
	tsa_entry 0x037, vflip=1
	tsa_entry 0x038, vflip=1
	tsa_entry 0x039, vflip=1
	tsa_entry 0x039, hflip=1, vflip=1
	tsa_entry 0x038, hflip=1, vflip=1
	tsa_entry 0x037, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x036, hflip=1, vflip=1
	tsa_entry 0x035, hflip=1, vflip=1
	tsa_entry 0x034, hflip=1, vflip=1
	tsa_entry 0x033, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x042, vflip=1
	tsa_entry 0x043, vflip=1
	tsa_entry 0x044, vflip=1
	tsa_entry 0x000
	tsa_entry 0x045, vflip=1
	tsa_entry 0x046, vflip=1
	tsa_entry 0x000
	tsa_entry 0x047, vflip=1
	tsa_entry 0x047, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x046, hflip=1, vflip=1
	tsa_entry 0x045, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x044, hflip=1, vflip=1
	tsa_entry 0x043, hflip=1, vflip=1
	tsa_entry 0x042, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x051, vflip=1
	tsa_entry 0x052, vflip=1
	tsa_entry 0x053, vflip=1
	tsa_entry 0x000
	tsa_entry 0x054, vflip=1
	tsa_entry 0x055, vflip=1
	tsa_entry 0x056, vflip=1
	tsa_entry 0x057, vflip=1
	tsa_entry 0x057, hflip=1, vflip=1
	tsa_entry 0x056, hflip=1, vflip=1
	tsa_entry 0x055, hflip=1, vflip=1
	tsa_entry 0x054, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x053, hflip=1, vflip=1
	tsa_entry 0x052, hflip=1, vflip=1
	tsa_entry 0x051, hflip=1, vflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x051
	tsa_entry 0x052
	tsa_entry 0x053
	tsa_entry 0x000
	tsa_entry 0x054
	tsa_entry 0x055
	tsa_entry 0x056
	tsa_entry 0x057
	tsa_entry 0x057, hflip=1
	tsa_entry 0x056, hflip=1
	tsa_entry 0x055, hflip=1
	tsa_entry 0x054, hflip=1
	tsa_entry 0x000
	tsa_entry 0x053, hflip=1
	tsa_entry 0x052, hflip=1
	tsa_entry 0x051, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x042
	tsa_entry 0x043
	tsa_entry 0x044
	tsa_entry 0x000
	tsa_entry 0x045
	tsa_entry 0x046
	tsa_entry 0x000
	tsa_entry 0x047
	tsa_entry 0x047, hflip=1
	tsa_entry 0x000
	tsa_entry 0x046, hflip=1
	tsa_entry 0x045, hflip=1
	tsa_entry 0x000
	tsa_entry 0x044, hflip=1
	tsa_entry 0x043, hflip=1
	tsa_entry 0x042, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x033
	tsa_entry 0x034
	tsa_entry 0x035
	tsa_entry 0x036
	tsa_entry 0x000
	tsa_entry 0x037
	tsa_entry 0x038
	tsa_entry 0x039
	tsa_entry 0x039, hflip=1
	tsa_entry 0x038, hflip=1
	tsa_entry 0x037, hflip=1
	tsa_entry 0x000
	tsa_entry 0x036, hflip=1
	tsa_entry 0x035, hflip=1
	tsa_entry 0x034, hflip=1
	tsa_entry 0x033, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x026
	tsa_entry 0x027
	tsa_entry 0x028
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x029
	tsa_entry 0x02A
	tsa_entry 0x02A, hflip=1
	tsa_entry 0x029, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x028, hflip=1
	tsa_entry 0x027, hflip=1
	tsa_entry 0x026, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x010
	tsa_entry 0x01C
	tsa_entry 0x01D
	tsa_entry 0x01E
	tsa_entry 0x01F
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x01F, hflip=1
	tsa_entry 0x01E, hflip=1
	tsa_entry 0x01D, hflip=1
	tsa_entry 0x01C, hflip=1
	tsa_entry 0x010, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x010
	tsa_entry 0x011
	tsa_entry 0x012
	tsa_entry 0x013
	tsa_entry 0x014
	tsa_entry 0x014
	tsa_entry 0x014, hflip=1
	tsa_entry 0x014, hflip=1
	tsa_entry 0x013, hflip=1
	tsa_entry 0x012, hflip=1
	tsa_entry 0x011, hflip=1
	tsa_entry 0x010, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x005
	tsa_entry 0x006
	tsa_entry 0x007
	tsa_entry 0x008
	tsa_entry 0x009
	tsa_entry 0x009, hflip=1
	tsa_entry 0x008, hflip=1
	tsa_entry 0x007, hflip=1
	tsa_entry 0x006, hflip=1
	tsa_entry 0x005, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x07F
	tsa_entry 0x001
	tsa_entry 0x001, hflip=1
	tsa_entry 0x07F, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
