	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x21B, vflip=1
	tsa_entry 0x205, hflip=1
	tsa_entry 0x042, hflip=1
	tsa_entry 0x041, hflip=1
	tsa_entry 0x040, hflip=1
	tsa_entry 0x066, hflip=1
	tsa_entry 0x065, hflip=1
	tsa_entry 0x064, hflip=1
	tsa_entry 0x063, hflip=1
	tsa_entry 0x0AA, hflip=1
	tsa_entry 0x0A9, hflip=1
	tsa_entry 0x0A8, hflip=1
	tsa_entry 0x0A7, hflip=1
	tsa_entry 0x0AE, hflip=1
	tsa_entry 0x0AD, hflip=1
	tsa_entry 0x0AC, hflip=1
	tsa_entry 0x0AB, hflip=1
	tsa_entry 0x0F2, hflip=1
	tsa_entry 0x0F1, hflip=1
	tsa_entry 0x0F0, hflip=1
	tsa_entry 0x0EF, hflip=1
	tsa_entry 0x01E, hflip=1
	tsa_entry 0x01D, hflip=1
	tsa_entry 0x01C, hflip=1
	tsa_entry 0x01B, hflip=1
	tsa_entry 0x07E, hflip=1
	tsa_entry 0x07D, hflip=1
	tsa_entry 0x07C, hflip=1
	tsa_entry 0x07B, hflip=1
	tsa_entry 0x1E5, hflip=1
	tsa_entry 0x022, hflip=1
	tsa_entry 0x021, hflip=1
	tsa_entry 0x020, hflip=1
	tsa_entry 0x046, hflip=1
	tsa_entry 0x045, hflip=1
	tsa_entry 0x044, hflip=1
	tsa_entry 0x043, hflip=1
	tsa_entry 0x08A, hflip=1
	tsa_entry 0x089, hflip=1
	tsa_entry 0x088, hflip=1
	tsa_entry 0x087, hflip=1
	tsa_entry 0x08E, hflip=1
	tsa_entry 0x08D, hflip=1
	tsa_entry 0x08C, hflip=1
	tsa_entry 0x08B, hflip=1
	tsa_entry 0x0D2, hflip=1
	tsa_entry 0x0D1, hflip=1
	tsa_entry 0x0D0, hflip=1
	tsa_entry 0x0CF, hflip=1
	tsa_entry 0x0F6, hflip=1
	tsa_entry 0x0F5, hflip=1
	tsa_entry 0x0F4, hflip=1
	tsa_entry 0x0F3, hflip=1
	tsa_entry 0x05E, hflip=1
	tsa_entry 0x05D, hflip=1
	tsa_entry 0x05C, hflip=1
	tsa_entry 0x05B, hflip=1
	tsa_entry 0x1C5, hflip=1
	tsa_entry 0x002, hflip=1
	tsa_entry 0x001, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x026, hflip=1
	tsa_entry 0x025, hflip=1
	tsa_entry 0x024, hflip=1
	tsa_entry 0x023, hflip=1
	tsa_entry 0x06A, hflip=1
	tsa_entry 0x069, hflip=1
	tsa_entry 0x068, hflip=1
	tsa_entry 0x067, hflip=1
	tsa_entry 0x06E, hflip=1
	tsa_entry 0x06D, hflip=1
	tsa_entry 0x06C, hflip=1
	tsa_entry 0x06B, hflip=1
	tsa_entry 0x0B2, hflip=1
	tsa_entry 0x0B1, hflip=1
	tsa_entry 0x0B0, hflip=1
	tsa_entry 0x0AF, hflip=1
	tsa_entry 0x0D6, hflip=1
	tsa_entry 0x0D5, hflip=1
	tsa_entry 0x0D4, hflip=1
	tsa_entry 0x0D3, hflip=1
	tsa_entry 0x03E, hflip=1
	tsa_entry 0x03D, hflip=1
	tsa_entry 0x03C, hflip=1
	tsa_entry 0x03B, hflip=1
	tsa_entry 0x1A2
	tsa_entry 0x1A3
	tsa_entry 0x1A4
	tsa_entry 0x1A5
	tsa_entry 0x006, hflip=1
	tsa_entry 0x005, hflip=1
	tsa_entry 0x004, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x04A, hflip=1
	tsa_entry 0x049, hflip=1
	tsa_entry 0x048, hflip=1
	tsa_entry 0x047, hflip=1
	tsa_entry 0x04E, hflip=1
	tsa_entry 0x04D, hflip=1
	tsa_entry 0x04C, hflip=1
	tsa_entry 0x04B, hflip=1
	tsa_entry 0x092, hflip=1
	tsa_entry 0x091, hflip=1
	tsa_entry 0x090, hflip=1
	tsa_entry 0x08F, hflip=1
	tsa_entry 0x0B6, hflip=1
	tsa_entry 0x0B5, hflip=1
	tsa_entry 0x0B4, hflip=1
	tsa_entry 0x0B3, hflip=1
	tsa_entry 0x0FA, hflip=1
	tsa_entry 0x0F9, hflip=1
	tsa_entry 0x0F8, hflip=1
	tsa_entry 0x0F7, hflip=1
	tsa_entry 0x182
	tsa_entry 0x183
	tsa_entry 0x184
	tsa_entry 0x185
	tsa_entry 0x186
	tsa_entry 0x187
	tsa_entry 0x188
	tsa_entry 0x189
	tsa_entry 0x02A, hflip=1
	tsa_entry 0x029, hflip=1
	tsa_entry 0x028, hflip=1
	tsa_entry 0x027, hflip=1
	tsa_entry 0x02E, hflip=1
	tsa_entry 0x02D, hflip=1
	tsa_entry 0x02C, hflip=1
	tsa_entry 0x02B, hflip=1
	tsa_entry 0x072, hflip=1
	tsa_entry 0x071, hflip=1
	tsa_entry 0x070, hflip=1
	tsa_entry 0x06F, hflip=1
	tsa_entry 0x096, hflip=1
	tsa_entry 0x095, hflip=1
	tsa_entry 0x094, hflip=1
	tsa_entry 0x093, hflip=1
	tsa_entry 0x0DA, hflip=1
	tsa_entry 0x0D9, hflip=1
	tsa_entry 0x0D8, hflip=1
	tsa_entry 0x0D7, hflip=1
	tsa_entry 0x162
	tsa_entry 0x163
	tsa_entry 0x164
	tsa_entry 0x165
	tsa_entry 0x166
	tsa_entry 0x167
	tsa_entry 0x168
	tsa_entry 0x169
	tsa_entry 0x00A, hflip=1
	tsa_entry 0x009, hflip=1
	tsa_entry 0x008, hflip=1
	tsa_entry 0x007, hflip=1
	tsa_entry 0x00E, hflip=1
	tsa_entry 0x00D, hflip=1
	tsa_entry 0x00C, hflip=1
	tsa_entry 0x00B, hflip=1
	tsa_entry 0x052, hflip=1
	tsa_entry 0x051, hflip=1
	tsa_entry 0x050, hflip=1
	tsa_entry 0x04F, hflip=1
	tsa_entry 0x076, hflip=1
	tsa_entry 0x075, hflip=1
	tsa_entry 0x074, hflip=1
	tsa_entry 0x073, hflip=1
	tsa_entry 0x0BA, hflip=1
	tsa_entry 0x0B9, hflip=1
	tsa_entry 0x0B8, hflip=1
	tsa_entry 0x0B7, hflip=1
	tsa_entry 0x142
	tsa_entry 0x143
	tsa_entry 0x144
	tsa_entry 0x145
	tsa_entry 0x146
	tsa_entry 0x147
	tsa_entry 0x148
	tsa_entry 0x149
	tsa_entry 0x14A
	tsa_entry 0x14B
	tsa_entry 0x14C
	tsa_entry 0x14D
	tsa_entry 0x14E
	tsa_entry 0x14F
	tsa_entry 0x150
	tsa_entry 0x151
	tsa_entry 0x032, hflip=1
	tsa_entry 0x031, hflip=1
	tsa_entry 0x030, hflip=1
	tsa_entry 0x02F, hflip=1
	tsa_entry 0x056, hflip=1
	tsa_entry 0x055, hflip=1
	tsa_entry 0x054, hflip=1
	tsa_entry 0x053, hflip=1
	tsa_entry 0x09A, hflip=1
	tsa_entry 0x099, hflip=1
	tsa_entry 0x098, hflip=1
	tsa_entry 0x097, hflip=1
	tsa_entry 0x122
	tsa_entry 0x123
	tsa_entry 0x124
	tsa_entry 0x125
	tsa_entry 0x126
	tsa_entry 0x127
	tsa_entry 0x128
	tsa_entry 0x129
	tsa_entry 0x12A
	tsa_entry 0x12B
	tsa_entry 0x12C
	tsa_entry 0x12D
	tsa_entry 0x12E
	tsa_entry 0x12F
	tsa_entry 0x130
	tsa_entry 0x131
	tsa_entry 0x012, hflip=1
	tsa_entry 0x011, hflip=1
	tsa_entry 0x010, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x036, hflip=1
	tsa_entry 0x035, hflip=1
	tsa_entry 0x034, hflip=1
	tsa_entry 0x033, hflip=1
	tsa_entry 0x07A, hflip=1
	tsa_entry 0x079, hflip=1
	tsa_entry 0x078, hflip=1
	tsa_entry 0x077, hflip=1
	tsa_entry 0x102
	tsa_entry 0x103
	tsa_entry 0x104
	tsa_entry 0x105
	tsa_entry 0x106
	tsa_entry 0x107
	tsa_entry 0x108
	tsa_entry 0x109
	tsa_entry 0x10A
	tsa_entry 0x10B
	tsa_entry 0x10C
	tsa_entry 0x10D
	tsa_entry 0x10E
	tsa_entry 0x10F
	tsa_entry 0x110
	tsa_entry 0x111
	tsa_entry 0x112
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x016, hflip=1
	tsa_entry 0x015, hflip=1
	tsa_entry 0x014, hflip=1
	tsa_entry 0x013, hflip=1
	tsa_entry 0x05A, hflip=1
	tsa_entry 0x059, hflip=1
	tsa_entry 0x058, hflip=1
	tsa_entry 0x057, hflip=1
	tsa_entry 0x0E2
	tsa_entry 0x0E3
	tsa_entry 0x0E4
	tsa_entry 0x0E5
	tsa_entry 0x0E6
	tsa_entry 0x0E7
	tsa_entry 0x0E8
	tsa_entry 0x0E9
	tsa_entry 0x0EA
	tsa_entry 0x0EB
	tsa_entry 0x0EC
	tsa_entry 0x0ED
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x03A, hflip=1
	tsa_entry 0x039, hflip=1
	tsa_entry 0x038, hflip=1
	tsa_entry 0x037, hflip=1
	tsa_entry 0x0C2
	tsa_entry 0x0C3
	tsa_entry 0x0C4
	tsa_entry 0x0C5
	tsa_entry 0x0C6
	tsa_entry 0x0C7
	tsa_entry 0x0C8
	tsa_entry 0x0C9
	tsa_entry 0x0CA
	tsa_entry 0x0CB
	tsa_entry 0x0CC
	tsa_entry 0x0CD
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01F
	tsa_entry 0x01A, hflip=1
	tsa_entry 0x019, hflip=1
	tsa_entry 0x018, hflip=1
	tsa_entry 0x017, hflip=1
	tsa_entry 0x000
