	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x113, pal=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x0F3, pal=15, hflip=1
	tsa_entry 0x1F4, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x0EB, pal=14, hflip=1, vflip=1
	tsa_entry 0x2ED, pal=14, hflip=1, vflip=1
	tsa_entry 0x0EF, pal=15
	tsa_entry 0x2F1, pal=15
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x0DF, pal=14
	tsa_entry 0x2E1, pal=14
	tsa_entry 0x0E3, pal=14, hflip=1
	tsa_entry 0x2E5, pal=14, hflip=1
	tsa_entry 0x0E7, pal=14, vflip=1
	tsa_entry 0x2E9, pal=14, vflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x1F7, pal=13
	tsa_entry 0x3D2, pal=13
	tsa_entry 0x1D4, pal=13, hflip=1
	tsa_entry 0x3D6, pal=13, hflip=1
	tsa_entry 0x1D8, pal=13, vflip=1
	tsa_entry 0x3DA, pal=13, vflip=1
	tsa_entry 0x1DC, pal=13, hflip=1, vflip=1
	tsa_entry 0x3DE, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=12
	tsa_entry 0x1C4, pal=12, hflip=1
	tsa_entry 0x3C6, pal=12, hflip=1
	tsa_entry 0x1C8, pal=12, vflip=1
	tsa_entry 0x3CA, pal=12, vflip=1
	tsa_entry 0x1CC, pal=12, hflip=1, vflip=1
	tsa_entry 0x3CE, pal=12, hflip=1, vflip=1
	tsa_entry 0x3D0, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3B1, pal=15, hflip=1
	tsa_entry 0x3B2, pal=11
	tsa_entry 0x1B4, pal=11, hflip=1
	tsa_entry 0x3B6, pal=11, hflip=1
	tsa_entry 0x1B8, pal=11, vflip=1
	tsa_entry 0x3BA, pal=11, vflip=1
	tsa_entry 0x1BC, pal=11, hflip=1, vflip=1
	tsa_entry 0x3BE, pal=11, hflip=1, vflip=1
	tsa_entry 0x1C0, pal=12
	tsa_entry 0x2F7, pal=12
	tsa_entry 0x3F7, pal=9, hflip=1, vflip=1
	tsa_entry 0x1A0, pal=10
	tsa_entry 0x3A2, pal=10
	tsa_entry 0x1A4, pal=10, hflip=1
	tsa_entry 0x3A6, pal=10, hflip=1
	tsa_entry 0x1A8, pal=10, vflip=1
	tsa_entry 0x3AA, pal=10, vflip=1
	tsa_entry 0x1AC, pal=10, hflip=1, vflip=1
	tsa_entry 0x3AE, pal=10, hflip=1, vflip=1
	tsa_entry 0x3B0, pal=15, hflip=1
	tsa_entry 0x1F7, pal=8, hflip=1, vflip=1
	tsa_entry 0x38E, pal=8, hflip=1, vflip=1
	tsa_entry 0x190, pal=9
	tsa_entry 0x392, pal=9
	tsa_entry 0x194, pal=9, hflip=1
	tsa_entry 0x396, pal=9, hflip=1
	tsa_entry 0x198, pal=9, vflip=1
	tsa_entry 0x39A, pal=9, vflip=1
	tsa_entry 0x19C, pal=9, hflip=1, vflip=1
	tsa_entry 0x39E, pal=15, hflip=1
	tsa_entry 0x3F7, pal=7, vflip=1
	tsa_entry 0x17C, pal=7, hflip=1, vflip=1
	tsa_entry 0x37E, pal=7, hflip=1, vflip=1
	tsa_entry 0x180, pal=8
	tsa_entry 0x382, pal=8
	tsa_entry 0x184, pal=8, hflip=1
	tsa_entry 0x386, pal=8, hflip=1
	tsa_entry 0x188, pal=8, vflip=1
	tsa_entry 0x38A, pal=8, vflip=1
	tsa_entry 0x38C, pal=15, hflip=1
	tsa_entry 0x1F7, pal=6, vflip=1
	tsa_entry 0x36A, pal=6, vflip=1
	tsa_entry 0x16C, pal=6, hflip=1, vflip=1
	tsa_entry 0x36E, pal=6, hflip=1, vflip=1
	tsa_entry 0x170, pal=7
	tsa_entry 0x372, pal=7
	tsa_entry 0x174, pal=7, hflip=1
	tsa_entry 0x376, pal=7, hflip=1
	tsa_entry 0x178, pal=7, vflip=1
	tsa_entry 0x37A, pal=15, hflip=1
	tsa_entry 0x3F7, pal=5, hflip=1
	tsa_entry 0x158, pal=5, vflip=1
	tsa_entry 0x35A, pal=5, vflip=1
	tsa_entry 0x15C, pal=5, hflip=1, vflip=1
	tsa_entry 0x35E, pal=5, hflip=1, vflip=1
	tsa_entry 0x160, pal=6
	tsa_entry 0x362, pal=6
	tsa_entry 0x164, pal=6, hflip=1
	tsa_entry 0x366, pal=6, hflip=1
	tsa_entry 0x368, pal=15, hflip=1
	tsa_entry 0x1F7, pal=4, hflip=1
	tsa_entry 0x346, pal=4, hflip=1
	tsa_entry 0x148, pal=4, vflip=1
	tsa_entry 0x34A, pal=4, vflip=1
	tsa_entry 0x14C, pal=4, hflip=1, vflip=1
	tsa_entry 0x34E, pal=4, hflip=1, vflip=1
	tsa_entry 0x150, pal=5
	tsa_entry 0x352, pal=5
	tsa_entry 0x154, pal=5, hflip=1
	tsa_entry 0x356, pal=15, hflip=1
	tsa_entry 0x333, pal=15, hflip=1
	tsa_entry 0x134, pal=3, hflip=1
	tsa_entry 0x336, pal=3, hflip=1
	tsa_entry 0x138, pal=3, vflip=1
	tsa_entry 0x33A, pal=3, vflip=1
	tsa_entry 0x13C, pal=3, hflip=1, vflip=1
	tsa_entry 0x33E, pal=3, hflip=1, vflip=1
	tsa_entry 0x140, pal=4
	tsa_entry 0x342, pal=4
	tsa_entry 0x0F7, pal=4, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x1F7, pal=2, hflip=1
	tsa_entry 0x326, pal=2, hflip=1
	tsa_entry 0x128, pal=2, vflip=1
	tsa_entry 0x32A, pal=2, vflip=1
	tsa_entry 0x12C, pal=2, hflip=1, vflip=1
	tsa_entry 0x32E, pal=2, hflip=1, vflip=1
	tsa_entry 0x130, pal=3
	tsa_entry 0x332, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=1, hflip=1
	tsa_entry 0x118, pal=1, vflip=1
	tsa_entry 0x31A, pal=1, vflip=1
	tsa_entry 0x11C, pal=1, hflip=1, vflip=1
	tsa_entry 0x31E, pal=1, hflip=1, vflip=1
	tsa_entry 0x120, pal=2
	tsa_entry 0x322, pal=2
	tsa_entry 0x324, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x00B, hflip=1, vflip=1
	tsa_entry 0x20D, hflip=1, vflip=1
	tsa_entry 0x00F, pal=1
	tsa_entry 0x211, pal=1
	tsa_entry 0x013, pal=1, hflip=1
	tsa_entry 0x215, pal=1, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x003, hflip=1
	tsa_entry 0x205, hflip=1
	tsa_entry 0x007, vflip=1
	tsa_entry 0x209, vflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x1F6
	tsa_entry 0x201
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x3F7, pal=15, hflip=1
	tsa_entry 0x000
