	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x31D, pal=1
	tsa_entry 0x23B, pal=1
	tsa_entry 0x23C, pal=1
	tsa_entry 0x23D, pal=1
	tsa_entry 0x23E, pal=1
	tsa_entry 0x23F, pal=1
	tsa_entry 0x240, pal=1
	tsa_entry 0x241, pal=1
	tsa_entry 0x242, pal=1
	tsa_entry 0x243, pal=1
	tsa_entry 0x244, pal=3
	tsa_entry 0x245, pal=3
	tsa_entry 0x246, pal=3
	tsa_entry 0x247, pal=3
	tsa_entry 0x248, pal=3
	tsa_entry 0x249, pal=3
	tsa_entry 0x24A, pal=3
	tsa_entry 0x24B, pal=3
	tsa_entry 0x24C, pal=2
	tsa_entry 0x24D, pal=3
	tsa_entry 0x24E, pal=3
	tsa_entry 0x24F, pal=3
	tsa_entry 0x250, pal=3
	tsa_entry 0x251, pal=1
	tsa_entry 0x252, pal=1
	tsa_entry 0x253, pal=1
	tsa_entry 0x254, pal=1
	tsa_entry 0x255, pal=1
	tsa_entry 0x256, pal=3
	tsa_entry 0x257, pal=3
	tsa_entry 0x258, pal=3
	tsa_entry 0x21D, pal=3
	tsa_entry 0x21E, pal=3
	tsa_entry 0x21F, pal=3
	tsa_entry 0x220, pal=1
	tsa_entry 0x221, pal=1
	tsa_entry 0x222, pal=3
	tsa_entry 0x223, pal=3
	tsa_entry 0x224, pal=3
	tsa_entry 0x225, pal=3
	tsa_entry 0x226, pal=3
	tsa_entry 0x227, pal=3
	tsa_entry 0x228, pal=2
	tsa_entry 0x229, pal=2
	tsa_entry 0x22A, pal=2
	tsa_entry 0x22B, pal=2
	tsa_entry 0x22C, pal=3
	tsa_entry 0x22D
	tsa_entry 0x22E, pal=2
	tsa_entry 0x22F, pal=2
	tsa_entry 0x230, pal=3
	tsa_entry 0x231, pal=3
	tsa_entry 0x232, pal=3
	tsa_entry 0x233, pal=1
	tsa_entry 0x234, pal=1
	tsa_entry 0x235, pal=3
	tsa_entry 0x236, pal=3
	tsa_entry 0x237, pal=3
	tsa_entry 0x238, pal=3
	tsa_entry 0x239, pal=3
	tsa_entry 0x23A, pal=3
	tsa_entry 0x1FF, pal=3
	tsa_entry 0x200, pal=3
	tsa_entry 0x201, pal=3
	tsa_entry 0x202, pal=3
	tsa_entry 0x203, pal=2
	tsa_entry 0x204, pal=2
	tsa_entry 0x205, pal=2
	tsa_entry 0x206, pal=3
	tsa_entry 0x207, pal=2
	tsa_entry 0x208
	tsa_entry 0x209
	tsa_entry 0x20A
	tsa_entry 0x20B, pal=2
	tsa_entry 0x20C
	tsa_entry 0x20D, pal=2
	tsa_entry 0x20E, pal=2
	tsa_entry 0x20F, pal=2
	tsa_entry 0x210
	tsa_entry 0x211
	tsa_entry 0x212, pal=2
	tsa_entry 0x213, pal=3
	tsa_entry 0x214, pal=3
	tsa_entry 0x215, pal=3
	tsa_entry 0x216, pal=3
	tsa_entry 0x217, pal=3
	tsa_entry 0x218, pal=3
	tsa_entry 0x219
	tsa_entry 0x21A, pal=3
	tsa_entry 0x21B, pal=3
	tsa_entry 0x21C, pal=3
	tsa_entry 0x1E1, pal=3
	tsa_entry 0x1E2, pal=3
	tsa_entry 0x1E3, pal=3
	tsa_entry 0x1E4, pal=3
	tsa_entry 0x1E5, pal=2
	tsa_entry 0x1E6
	tsa_entry 0x1E7, pal=1
	tsa_entry 0x1E8, pal=2
	tsa_entry 0x1E9
	tsa_entry 0x1EA
	tsa_entry 0x1EB
	tsa_entry 0x1EC
	tsa_entry 0x1ED
	tsa_entry 0x1EE, pal=2
	tsa_entry 0x1EF
	tsa_entry 0x1F0, pal=2
	tsa_entry 0x1F1, pal=2
	tsa_entry 0x1F2, pal=2
	tsa_entry 0x1F3
	tsa_entry 0x1F4
	tsa_entry 0x1F5, pal=3
	tsa_entry 0x1F6, pal=3
	tsa_entry 0x1F7, pal=3
	tsa_entry 0x1F8, pal=2
	tsa_entry 0x1F9, pal=3
	tsa_entry 0x1FA, pal=3
	tsa_entry 0x1FB
	tsa_entry 0x1FC
	tsa_entry 0x1FD, pal=1
	tsa_entry 0x1FE, pal=3
	tsa_entry 0x1C3, pal=3
	tsa_entry 0x1C4, pal=3
	tsa_entry 0x1C5, pal=3
	tsa_entry 0x1C6, pal=3
	tsa_entry 0x1C7, pal=3
	tsa_entry 0x1C8, pal=3
	tsa_entry 0x1C9, pal=1
	tsa_entry 0x1CA, pal=3
	tsa_entry 0x1CB, pal=2
	tsa_entry 0x1CC, pal=3
	tsa_entry 0x1CD
	tsa_entry 0x1CE
	tsa_entry 0x1CF
	tsa_entry 0x1D0
	tsa_entry 0x1D1
	tsa_entry 0x1D2
	tsa_entry 0x1D3
	tsa_entry 0x1D4
	tsa_entry 0x1D5, pal=2
	tsa_entry 0x1D6, pal=2
	tsa_entry 0x1D7
	tsa_entry 0x1D8, pal=3
	tsa_entry 0x1D9, pal=3
	tsa_entry 0x1DA, pal=3
	tsa_entry 0x1DB, pal=3
	tsa_entry 0x1DC, pal=3
	tsa_entry 0x1DD, pal=3
	tsa_entry 0x1DE, pal=3
	tsa_entry 0x1DF, pal=3
	tsa_entry 0x1E0, pal=3
	tsa_entry 0x1A5, pal=3
	tsa_entry 0x1A6, pal=3
	tsa_entry 0x1A7, pal=3
	tsa_entry 0x1A8
	tsa_entry 0x1A9, pal=2
	tsa_entry 0x1AA, pal=3
	tsa_entry 0x1AB, pal=3
	tsa_entry 0x1AC, pal=3
	tsa_entry 0x1AD, pal=2
	tsa_entry 0x1AE
	tsa_entry 0x1AF, pal=2
	tsa_entry 0x1B0
	tsa_entry 0x1B1
	tsa_entry 0x1B2
	tsa_entry 0x1B3
	tsa_entry 0x1B4
	tsa_entry 0x1B5
	tsa_entry 0x1B6
	tsa_entry 0x1B7
	tsa_entry 0x1B8
	tsa_entry 0x1B9, pal=3
	tsa_entry 0x1BA, pal=3
	tsa_entry 0x1BB, pal=3
	tsa_entry 0x1BC, pal=3
	tsa_entry 0x1BD, pal=3
	tsa_entry 0x1BE, pal=3
	tsa_entry 0x1BF, pal=3
	tsa_entry 0x1C0, pal=3
	tsa_entry 0x1C1, pal=3
	tsa_entry 0x1C2, pal=3
	tsa_entry 0x187, pal=3
	tsa_entry 0x188, pal=3
	tsa_entry 0x189, pal=2
	tsa_entry 0x18A
	tsa_entry 0x18B, pal=3
	tsa_entry 0x18C, pal=2
	tsa_entry 0x18D, pal=3
	tsa_entry 0x18E, pal=2
	tsa_entry 0x18F
	tsa_entry 0x190, pal=2
	tsa_entry 0x191
	tsa_entry 0x192
	tsa_entry 0x193, pal=2
	tsa_entry 0x194, pal=3
	tsa_entry 0x195, pal=2
	tsa_entry 0x196
	tsa_entry 0x197
	tsa_entry 0x198
	tsa_entry 0x199
	tsa_entry 0x19A, pal=2
	tsa_entry 0x19B
	tsa_entry 0x19C
	tsa_entry 0x19D, pal=3
	tsa_entry 0x19E, pal=3
	tsa_entry 0x19F, pal=3
	tsa_entry 0x1A0, pal=2
	tsa_entry 0x1A1, pal=3
	tsa_entry 0x1A2, pal=3
	tsa_entry 0x1A3, pal=3
	tsa_entry 0x1A4, pal=3
	tsa_entry 0x169, pal=3
	tsa_entry 0x16A, pal=3
	tsa_entry 0x16B, pal=3
	tsa_entry 0x16C
	tsa_entry 0x16D
	tsa_entry 0x16E
	tsa_entry 0x16F
	tsa_entry 0x170
	tsa_entry 0x171, pal=2
	tsa_entry 0x172, pal=2
	tsa_entry 0x173, pal=2
	tsa_entry 0x174
	tsa_entry 0x175, pal=2
	tsa_entry 0x176, pal=2
	tsa_entry 0x177
	tsa_entry 0x178
	tsa_entry 0x179, pal=3
	tsa_entry 0x17A
	tsa_entry 0x17B
	tsa_entry 0x17C
	tsa_entry 0x17D
	tsa_entry 0x17E, pal=3
	tsa_entry 0x17F, pal=3
	tsa_entry 0x180
	tsa_entry 0x181
	tsa_entry 0x182
	tsa_entry 0x183, pal=3
	tsa_entry 0x184, pal=3
	tsa_entry 0x185, pal=3
	tsa_entry 0x186, pal=3
	tsa_entry 0x14B, pal=3
	tsa_entry 0x14C, pal=3
	tsa_entry 0x14D, pal=3
	tsa_entry 0x14E
	tsa_entry 0x14F
	tsa_entry 0x150
	tsa_entry 0x151, pal=2
	tsa_entry 0x152, pal=2
	tsa_entry 0x153
	tsa_entry 0x154
	tsa_entry 0x155, pal=1
	tsa_entry 0x156, pal=2
	tsa_entry 0x157, pal=2
	tsa_entry 0x158
	tsa_entry 0x159, pal=2
	tsa_entry 0x15A
	tsa_entry 0x15B
	tsa_entry 0x15C
	tsa_entry 0x15D
	tsa_entry 0x15E
	tsa_entry 0x15F, pal=2
	tsa_entry 0x160, pal=2
	tsa_entry 0x161, pal=3
	tsa_entry 0x162
	tsa_entry 0x163, pal=3
	tsa_entry 0x164, pal=3
	tsa_entry 0x165
	tsa_entry 0x166, pal=2
	tsa_entry 0x167, pal=3
	tsa_entry 0x168, pal=3
	tsa_entry 0x12D, pal=3
	tsa_entry 0x12E, pal=3
	tsa_entry 0x12F, pal=3
	tsa_entry 0x130, pal=3
	tsa_entry 0x131
	tsa_entry 0x132, pal=2
	tsa_entry 0x133, pal=2
	tsa_entry 0x134
	tsa_entry 0x135
	tsa_entry 0x136
	tsa_entry 0x137
	tsa_entry 0x138
	tsa_entry 0x139
	tsa_entry 0x13A
	tsa_entry 0x13B
	tsa_entry 0x13C
	tsa_entry 0x13D, pal=2
	tsa_entry 0x13E, pal=2
	tsa_entry 0x13F
	tsa_entry 0x140, pal=3
	tsa_entry 0x141, pal=3
	tsa_entry 0x142, pal=3
	tsa_entry 0x143
	tsa_entry 0x144, pal=3
	tsa_entry 0x145, pal=3
	tsa_entry 0x146, pal=3
	tsa_entry 0x147
	tsa_entry 0x148
	tsa_entry 0x149, pal=3
	tsa_entry 0x14A, pal=3
	tsa_entry 0x10F, pal=3
	tsa_entry 0x110, pal=3
	tsa_entry 0x111, pal=3
	tsa_entry 0x112
	tsa_entry 0x113
	tsa_entry 0x114
	tsa_entry 0x115, pal=2
	tsa_entry 0x116, pal=2
	tsa_entry 0x117
	tsa_entry 0x118
	tsa_entry 0x119
	tsa_entry 0x11A
	tsa_entry 0x11B
	tsa_entry 0x11C
	tsa_entry 0x11D
	tsa_entry 0x11E, pal=2
	tsa_entry 0x11F, pal=2
	tsa_entry 0x120, pal=2
	tsa_entry 0x121
	tsa_entry 0x122
	tsa_entry 0x123
	tsa_entry 0x124, pal=3
	tsa_entry 0x125
	tsa_entry 0x126, pal=3
	tsa_entry 0x127
	tsa_entry 0x128
	tsa_entry 0x129
	tsa_entry 0x12A, pal=2
	tsa_entry 0x12B, pal=3
	tsa_entry 0x12C, pal=1
	tsa_entry 0x0F1, pal=3
	tsa_entry 0x0F2, pal=3
	tsa_entry 0x0F3
	tsa_entry 0x0F4
	tsa_entry 0x0F5
	tsa_entry 0x0F6
	tsa_entry 0x0F7, pal=2
	tsa_entry 0x0F8, pal=2
	tsa_entry 0x0F9
	tsa_entry 0x0FA
	tsa_entry 0x0FB
	tsa_entry 0x0FC
	tsa_entry 0x0FD
	tsa_entry 0x0FE, pal=2
	tsa_entry 0x0FF, pal=2
	tsa_entry 0x100, pal=2
	tsa_entry 0x101
	tsa_entry 0x102
	tsa_entry 0x103
	tsa_entry 0x104
	tsa_entry 0x105
	tsa_entry 0x106
	tsa_entry 0x107
	tsa_entry 0x108
	tsa_entry 0x109, pal=1
	tsa_entry 0x10A
	tsa_entry 0x10B
	tsa_entry 0x10C, pal=3
	tsa_entry 0x10D, pal=3
	tsa_entry 0x10E, pal=1
	tsa_entry 0x0D3, pal=3
	tsa_entry 0x0D4, pal=3
	tsa_entry 0x0D5, pal=1
	tsa_entry 0x0D6
	tsa_entry 0x0D7
	tsa_entry 0x0D8
	tsa_entry 0x0D9, pal=2
	tsa_entry 0x0DA
	tsa_entry 0x0DB
	tsa_entry 0x0DC
	tsa_entry 0x0DD
	tsa_entry 0x0DE
	tsa_entry 0x0DF, pal=2
	tsa_entry 0x0E0
	tsa_entry 0x0E1
	tsa_entry 0x0E2
	tsa_entry 0x0E3
	tsa_entry 0x0E4, pal=2
	tsa_entry 0x0E5, pal=1
	tsa_entry 0x0E6, pal=2
	tsa_entry 0x0E7
	tsa_entry 0x0E8, pal=2
	tsa_entry 0x0E9, pal=1
	tsa_entry 0x0EA, pal=2
	tsa_entry 0x0EB
	tsa_entry 0x0EC
	tsa_entry 0x0ED, pal=2
	tsa_entry 0x0EE, pal=2
	tsa_entry 0x0EF, pal=2
	tsa_entry 0x0F0, pal=1
	tsa_entry 0x0B5, pal=3
	tsa_entry 0x0B6, pal=2
	tsa_entry 0x0B7, pal=1
	tsa_entry 0x0B8
	tsa_entry 0x0B9
	tsa_entry 0x0BA
	tsa_entry 0x0BB
	tsa_entry 0x0BC
	tsa_entry 0x0BD, pal=3
	tsa_entry 0x0BE, pal=3
	tsa_entry 0x0BF
	tsa_entry 0x0C0, pal=2
	tsa_entry 0x0C1, pal=2
	tsa_entry 0x0C2
	tsa_entry 0x0C3
	tsa_entry 0x0C4
	tsa_entry 0x0C5
	tsa_entry 0x0C6, pal=1
	tsa_entry 0x0C7, pal=1
	tsa_entry 0x0C8, pal=1
	tsa_entry 0x0C9, pal=1
	tsa_entry 0x0CA, pal=2
	tsa_entry 0x0CB
	tsa_entry 0x0CC
	tsa_entry 0x0CD
	tsa_entry 0x0CE, pal=2
	tsa_entry 0x0CF, pal=1
	tsa_entry 0x0D0, pal=2
	tsa_entry 0x0D1, pal=3
	tsa_entry 0x0D2, pal=1
	tsa_entry 0x097, pal=3
	tsa_entry 0x098, pal=3
	tsa_entry 0x099, pal=2
	tsa_entry 0x09A, pal=2
	tsa_entry 0x09B
	tsa_entry 0x09C
	tsa_entry 0x09D, pal=3
	tsa_entry 0x09E
	tsa_entry 0x09F
	tsa_entry 0x0A0
	tsa_entry 0x0A1
	tsa_entry 0x0A2
	tsa_entry 0x0A3
	tsa_entry 0x0A4
	tsa_entry 0x0A5
	tsa_entry 0x0A6, pal=2
	tsa_entry 0x0A7, pal=1
	tsa_entry 0x0A8, pal=1
	tsa_entry 0x0A9, pal=1
	tsa_entry 0x0AA, pal=1
	tsa_entry 0x0AB, pal=2
	tsa_entry 0x0AC
	tsa_entry 0x0AD
	tsa_entry 0x0AE
	tsa_entry 0x0AF
	tsa_entry 0x0B0
	tsa_entry 0x0B1, pal=1
	tsa_entry 0x0B2, pal=1
	tsa_entry 0x0B3, pal=2
	tsa_entry 0x0B4, pal=3
	tsa_entry 0x079, pal=3
	tsa_entry 0x07A, pal=2
	tsa_entry 0x07B, pal=2
	tsa_entry 0x07C
	tsa_entry 0x07D
	tsa_entry 0x07E
	tsa_entry 0x07F, pal=2
	tsa_entry 0x080
	tsa_entry 0x081
	tsa_entry 0x082
	tsa_entry 0x083
	tsa_entry 0x084, pal=2
	tsa_entry 0x085
	tsa_entry 0x086
	tsa_entry 0x087, pal=2
	tsa_entry 0x088, pal=3
	tsa_entry 0x089, pal=3
	tsa_entry 0x08A, pal=3
	tsa_entry 0x08B, pal=3
	tsa_entry 0x08C, pal=1
	tsa_entry 0x08D
	tsa_entry 0x08E, pal=2
	tsa_entry 0x08F, pal=1
	tsa_entry 0x090, pal=1
	tsa_entry 0x091, pal=2
	tsa_entry 0x092, pal=1
	tsa_entry 0x093, pal=2
	tsa_entry 0x094, pal=2
	tsa_entry 0x095, pal=3
	tsa_entry 0x096, pal=3
	tsa_entry 0x05B, pal=3
	tsa_entry 0x05C
	tsa_entry 0x05D, pal=3
	tsa_entry 0x05E, pal=3
	tsa_entry 0x05F, pal=3
	tsa_entry 0x060
	tsa_entry 0x061
	tsa_entry 0x062, pal=2
	tsa_entry 0x063
	tsa_entry 0x064
	tsa_entry 0x065
	tsa_entry 0x066
	tsa_entry 0x067
	tsa_entry 0x068, pal=3
	tsa_entry 0x069, pal=3
	tsa_entry 0x06A, pal=1
	tsa_entry 0x06B, pal=1
	tsa_entry 0x06C, pal=1
	tsa_entry 0x06D, pal=3
	tsa_entry 0x06E, pal=3
	tsa_entry 0x06F
	tsa_entry 0x070
	tsa_entry 0x071, pal=2
	tsa_entry 0x072
	tsa_entry 0x073, pal=2
	tsa_entry 0x074
	tsa_entry 0x075, pal=2
	tsa_entry 0x076, pal=3
	tsa_entry 0x077, pal=1
	tsa_entry 0x078, pal=1
	tsa_entry 0x03D, pal=3
	tsa_entry 0x03E, pal=2
	tsa_entry 0x03F, pal=3
	tsa_entry 0x040, pal=3
	tsa_entry 0x041, pal=3
	tsa_entry 0x042, pal=3
	tsa_entry 0x043
	tsa_entry 0x044, pal=2
	tsa_entry 0x045
	tsa_entry 0x046, pal=2
	tsa_entry 0x047
	tsa_entry 0x048, pal=3
	tsa_entry 0x049, pal=3
	tsa_entry 0x04A, pal=3
	tsa_entry 0x04B, pal=3
	tsa_entry 0x04C, pal=1
	tsa_entry 0x04D, pal=3
	tsa_entry 0x04E, pal=1
	tsa_entry 0x04F, pal=1
	tsa_entry 0x050, pal=1
	tsa_entry 0x051, pal=2
	tsa_entry 0x052, pal=1
	tsa_entry 0x053, pal=2
	tsa_entry 0x054, pal=2
	tsa_entry 0x055, pal=2
	tsa_entry 0x056, pal=2
	tsa_entry 0x057, pal=3
	tsa_entry 0x058, pal=3
	tsa_entry 0x059, pal=1
	tsa_entry 0x05A, pal=1
	tsa_entry 0x01F, pal=3
	tsa_entry 0x020, pal=3
	tsa_entry 0x021, pal=3
	tsa_entry 0x022, pal=3
	tsa_entry 0x023, pal=3
	tsa_entry 0x024, pal=3
	tsa_entry 0x025, pal=2
	tsa_entry 0x026, pal=2
	tsa_entry 0x027, pal=1
	tsa_entry 0x028, pal=3
	tsa_entry 0x029, pal=3
	tsa_entry 0x02A, pal=3
	tsa_entry 0x02B, pal=3
	tsa_entry 0x02C, pal=3
	tsa_entry 0x02D, pal=3
	tsa_entry 0x02E, pal=3
	tsa_entry 0x02F, pal=3
	tsa_entry 0x030, pal=3
	tsa_entry 0x031, pal=1
	tsa_entry 0x032, pal=1
	tsa_entry 0x033, pal=1
	tsa_entry 0x034, pal=3
	tsa_entry 0x035, pal=3
	tsa_entry 0x036, pal=3
	tsa_entry 0x037, pal=3
	tsa_entry 0x038, pal=3
	tsa_entry 0x039, pal=3
	tsa_entry 0x03A, pal=1
	tsa_entry 0x03B, pal=3
	tsa_entry 0x03C, pal=3
	tsa_entry 0x001, pal=3
	tsa_entry 0x002, pal=3
	tsa_entry 0x003, pal=1
	tsa_entry 0x004, pal=1
	tsa_entry 0x005, pal=1
	tsa_entry 0x006, pal=1
	tsa_entry 0x007, pal=3
	tsa_entry 0x008, pal=3
	tsa_entry 0x009, pal=3
	tsa_entry 0x00A, pal=3
	tsa_entry 0x00B, pal=3
	tsa_entry 0x00C, pal=3
	tsa_entry 0x00D, pal=3
	tsa_entry 0x00E, pal=3
	tsa_entry 0x00F, pal=3
	tsa_entry 0x010, pal=3
	tsa_entry 0x011, pal=3
	tsa_entry 0x012, pal=3
	tsa_entry 0x013, pal=3
	tsa_entry 0x014, pal=1
	tsa_entry 0x015, pal=1
	tsa_entry 0x016, pal=1
	tsa_entry 0x017, pal=3
	tsa_entry 0x018, pal=3
	tsa_entry 0x019, pal=3
	tsa_entry 0x01A, pal=3
	tsa_entry 0x01B, pal=1
	tsa_entry 0x01C, pal=3
	tsa_entry 0x01D, pal=3
	tsa_entry 0x01E, pal=3
