	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x303
	tsa_entry 0x000, vflip=1
	tsa_entry 0x001, vflip=1
	tsa_entry 0x002, vflip=1
	tsa_entry 0x003, vflip=1
	tsa_entry 0x004, vflip=1
	tsa_entry 0x005, vflip=1
	tsa_entry 0x006, vflip=1
	tsa_entry 0x007, vflip=1
	tsa_entry 0x004
	tsa_entry 0x005
	tsa_entry 0x006
	tsa_entry 0x007
	tsa_entry 0x000
	tsa_entry 0x001
	tsa_entry 0x002
	tsa_entry 0x003
	tsa_entry 0x000
