	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x31D, pal=1
	tsa_entry 0x23A
	tsa_entry 0x23B
	tsa_entry 0x23C
	tsa_entry 0x23D
	tsa_entry 0x23E
	tsa_entry 0x23F, pal=4
	tsa_entry 0x240, pal=4
	tsa_entry 0x241, pal=5
	tsa_entry 0x242, pal=5
	tsa_entry 0x243, pal=5
	tsa_entry 0x244, pal=5
	tsa_entry 0x245, pal=5
	tsa_entry 0x246, pal=5
	tsa_entry 0x247, pal=5
	tsa_entry 0x248, pal=5
	tsa_entry 0x249, pal=5
	tsa_entry 0x24A, pal=5
	tsa_entry 0x24B, pal=5
	tsa_entry 0x24C, pal=6
	tsa_entry 0x24D, pal=5
	tsa_entry 0x24E, pal=6
	tsa_entry 0x24F, pal=6
	tsa_entry 0x250, pal=6
	tsa_entry 0x251, pal=6
	tsa_entry 0x252, pal=6
	tsa_entry 0x253, pal=7
	tsa_entry 0x254, pal=7
	tsa_entry 0x255, pal=7
	tsa_entry 0x256
	tsa_entry 0x257
	tsa_entry 0x21C
	tsa_entry 0x21D
	tsa_entry 0x21E
	tsa_entry 0x21F
	tsa_entry 0x220
	tsa_entry 0x221, pal=4
	tsa_entry 0x222, pal=4
	tsa_entry 0x223, pal=4
	tsa_entry 0x224, pal=5
	tsa_entry 0x225, pal=5
	tsa_entry 0x226, pal=5
	tsa_entry 0x227, pal=5
	tsa_entry 0x228, pal=5
	tsa_entry 0x229, pal=5
	tsa_entry 0x22A, pal=5
	tsa_entry 0x22B, pal=5
	tsa_entry 0x22C, pal=5
	tsa_entry 0x22D, pal=5
	tsa_entry 0x22E, pal=6
	tsa_entry 0x22F, pal=6
	tsa_entry 0x230, pal=6
	tsa_entry 0x231, pal=6
	tsa_entry 0x232, pal=6
	tsa_entry 0x233, pal=6
	tsa_entry 0x234, pal=7
	tsa_entry 0x235, pal=7
	tsa_entry 0x236, pal=7
	tsa_entry 0x237, pal=7
	tsa_entry 0x238, pal=3
	tsa_entry 0x239
	tsa_entry 0x1FE
	tsa_entry 0x1FF
	tsa_entry 0x200
	tsa_entry 0x201
	tsa_entry 0x202, pal=4
	tsa_entry 0x203, pal=2
	tsa_entry 0x204, pal=4
	tsa_entry 0x205, pal=4
	tsa_entry 0x206, pal=5
	tsa_entry 0x207, pal=5
	tsa_entry 0x208, pal=5
	tsa_entry 0x209, pal=5
	tsa_entry 0x20A, pal=5
	tsa_entry 0x20B, pal=5
	tsa_entry 0x20C, pal=5
	tsa_entry 0x20D, pal=5
	tsa_entry 0x20E, pal=5
	tsa_entry 0x20F, pal=5
	tsa_entry 0x210, pal=5
	tsa_entry 0x211, pal=5
	tsa_entry 0x212, pal=5
	tsa_entry 0x213, pal=6
	tsa_entry 0x214, pal=6
	tsa_entry 0x215, pal=6
	tsa_entry 0x216, pal=4
	tsa_entry 0x217, pal=7
	tsa_entry 0x218, pal=7
	tsa_entry 0x219, pal=7
	tsa_entry 0x21A, pal=7
	tsa_entry 0x21B
	tsa_entry 0x1E0
	tsa_entry 0x1E1
	tsa_entry 0x1E2
	tsa_entry 0x1E3
	tsa_entry 0x1E4, pal=4
	tsa_entry 0x1E5, pal=4
	tsa_entry 0x1E6, pal=4
	tsa_entry 0x1E7, pal=4
	tsa_entry 0x1E8, pal=5
	tsa_entry 0x1E9, pal=5
	tsa_entry 0x1EA, pal=5
	tsa_entry 0x1EB, pal=5
	tsa_entry 0x1EC, pal=5
	tsa_entry 0x1ED, pal=5
	tsa_entry 0x1EE, pal=5
	tsa_entry 0x1EF, pal=5
	tsa_entry 0x1F0, pal=5
	tsa_entry 0x1F1, pal=5
	tsa_entry 0x1F2, pal=5
	tsa_entry 0x1F3, pal=5
	tsa_entry 0x1F4, pal=5
	tsa_entry 0x1F5, pal=6
	tsa_entry 0x1F6, pal=6
	tsa_entry 0x1F7, pal=6
	tsa_entry 0x1F8, pal=4
	tsa_entry 0x1F9, pal=7
	tsa_entry 0x1FA, pal=1
	tsa_entry 0x1FB, pal=1
	tsa_entry 0x1FC, pal=3
	tsa_entry 0x1FD, pal=7
	tsa_entry 0x1C2
	tsa_entry 0x1C3
	tsa_entry 0x1C4
	tsa_entry 0x1C5
	tsa_entry 0x1C6, pal=2
	tsa_entry 0x1C7, pal=4
	tsa_entry 0x1C8, pal=4
	tsa_entry 0x1C9, pal=4
	tsa_entry 0x1CA, pal=5
	tsa_entry 0x1CB, pal=5
	tsa_entry 0x1CC, pal=5
	tsa_entry 0x1CD, pal=5
	tsa_entry 0x1CE, pal=5
	tsa_entry 0x1CF, pal=5
	tsa_entry 0x1D0, pal=5
	tsa_entry 0x1D1, pal=5
	tsa_entry 0x1D2, pal=6
	tsa_entry 0x1D3, pal=6
	tsa_entry 0x1D4, pal=6
	tsa_entry 0x1D5, pal=6
	tsa_entry 0x1D6, pal=6
	tsa_entry 0x1D7, pal=6
	tsa_entry 0x1D8, pal=6
	tsa_entry 0x1D9, pal=4
	tsa_entry 0x1DA, pal=4
	tsa_entry 0x1DB, pal=4
	tsa_entry 0x1DC, pal=1
	tsa_entry 0x1DD
	tsa_entry 0x1DE, pal=3
	tsa_entry 0x1DF, pal=3
	tsa_entry 0x1A4
	tsa_entry 0x1A5
	tsa_entry 0x1A6
	tsa_entry 0x1A7
	tsa_entry 0x1A8, pal=4
	tsa_entry 0x1A9, pal=4
	tsa_entry 0x1AA, pal=4
	tsa_entry 0x1AB, pal=5
	tsa_entry 0x1AC, pal=5
	tsa_entry 0x1AD, pal=5
	tsa_entry 0x1AE, pal=5
	tsa_entry 0x1AF, pal=6
	tsa_entry 0x1B0, pal=6
	tsa_entry 0x1B1, pal=6
	tsa_entry 0x1B2, pal=6
	tsa_entry 0x1B3, pal=6
	tsa_entry 0x1B4, pal=6
	tsa_entry 0x1B5, pal=6
	tsa_entry 0x1B6, pal=6
	tsa_entry 0x1B7, pal=6
	tsa_entry 0x1B8, pal=6
	tsa_entry 0x1B9, pal=6
	tsa_entry 0x1BA, pal=4
	tsa_entry 0x1BB, pal=4
	tsa_entry 0x1BC, pal=4
	tsa_entry 0x1BD, pal=2
	tsa_entry 0x1BE, pal=2
	tsa_entry 0x1BF
	tsa_entry 0x1C0, pal=3
	tsa_entry 0x1C1
	tsa_entry 0x186
	tsa_entry 0x187
	tsa_entry 0x188
	tsa_entry 0x189
	tsa_entry 0x18A, pal=4
	tsa_entry 0x18B, pal=4
	tsa_entry 0x18C, pal=4
	tsa_entry 0x18D, pal=5
	tsa_entry 0x18E, pal=6
	tsa_entry 0x18F, pal=6
	tsa_entry 0x190, pal=6
	tsa_entry 0x191, pal=6
	tsa_entry 0x192, pal=6
	tsa_entry 0x193, pal=6
	tsa_entry 0x194, pal=6
	tsa_entry 0x195, pal=6
	tsa_entry 0x196, pal=6
	tsa_entry 0x197, pal=6
	tsa_entry 0x198, pal=6
	tsa_entry 0x199, pal=6
	tsa_entry 0x19A, pal=6
	tsa_entry 0x19B, pal=6
	tsa_entry 0x19C, pal=4
	tsa_entry 0x19D, pal=7
	tsa_entry 0x19E, pal=7
	tsa_entry 0x19F, pal=2
	tsa_entry 0x1A0, pal=2
	tsa_entry 0x1A1
	tsa_entry 0x1A2
	tsa_entry 0x1A3
	tsa_entry 0x168
	tsa_entry 0x169
	tsa_entry 0x16A
	tsa_entry 0x16B
	tsa_entry 0x16C, pal=2
	tsa_entry 0x16D, pal=4
	tsa_entry 0x16E, pal=4
	tsa_entry 0x16F, pal=6
	tsa_entry 0x170, pal=5
	tsa_entry 0x171, pal=5
	tsa_entry 0x172, pal=5
	tsa_entry 0x173, pal=5
	tsa_entry 0x174, pal=5
	tsa_entry 0x175, pal=5
	tsa_entry 0x176, pal=5
	tsa_entry 0x177, pal=5
	tsa_entry 0x178, pal=5
	tsa_entry 0x179, pal=4
	tsa_entry 0x17A, pal=4
	tsa_entry 0x17B, pal=4
	tsa_entry 0x17C, pal=4
	tsa_entry 0x17D, pal=4
	tsa_entry 0x17E, pal=4
	tsa_entry 0x17F, pal=7
	tsa_entry 0x180, pal=2
	tsa_entry 0x181, pal=2
	tsa_entry 0x182, pal=2
	tsa_entry 0x183
	tsa_entry 0x184
	tsa_entry 0x185, pal=7
	tsa_entry 0x14A
	tsa_entry 0x14B
	tsa_entry 0x14C
	tsa_entry 0x14D, pal=1
	tsa_entry 0x14E, pal=1
	tsa_entry 0x14F, pal=4
	tsa_entry 0x150, pal=4
	tsa_entry 0x151, pal=4
	tsa_entry 0x152, pal=4
	tsa_entry 0x153, pal=4
	tsa_entry 0x154, pal=4
	tsa_entry 0x155, pal=5
	tsa_entry 0x156, pal=4
	tsa_entry 0x157, pal=4
	tsa_entry 0x158, pal=5
	tsa_entry 0x159, pal=4
	tsa_entry 0x15A, pal=4
	tsa_entry 0x15B, pal=4
	tsa_entry 0x15C, pal=4
	tsa_entry 0x15D, pal=4
	tsa_entry 0x15E, pal=6
	tsa_entry 0x15F, pal=7
	tsa_entry 0x160, pal=7
	tsa_entry 0x161, pal=7
	tsa_entry 0x162, pal=2
	tsa_entry 0x163, pal=2
	tsa_entry 0x164, pal=2
	tsa_entry 0x165
	tsa_entry 0x166, pal=3
	tsa_entry 0x167
	tsa_entry 0x12C
	tsa_entry 0x12D
	tsa_entry 0x12E, pal=1
	tsa_entry 0x12F, pal=1
	tsa_entry 0x130, pal=2
	tsa_entry 0x131, pal=2
	tsa_entry 0x132, pal=2
	tsa_entry 0x133, pal=1
	tsa_entry 0x134, pal=5
	tsa_entry 0x135, pal=4
	tsa_entry 0x136, pal=4
	tsa_entry 0x137, pal=4
	tsa_entry 0x138, pal=6
	tsa_entry 0x139, pal=4
	tsa_entry 0x13A, pal=4
	tsa_entry 0x13B, pal=4
	tsa_entry 0x13C, pal=4
	tsa_entry 0x13D, pal=6
	tsa_entry 0x13E, pal=4
	tsa_entry 0x13F, pal=4
	tsa_entry 0x140, pal=2
	tsa_entry 0x141, pal=7
	tsa_entry 0x142, pal=4
	tsa_entry 0x143, pal=2
	tsa_entry 0x144, pal=2
	tsa_entry 0x145, pal=2
	tsa_entry 0x146
	tsa_entry 0x147
	tsa_entry 0x148, pal=3
	tsa_entry 0x149, pal=3
	tsa_entry 0x10E, pal=3
	tsa_entry 0x10F
	tsa_entry 0x110, pal=1
	tsa_entry 0x111
	tsa_entry 0x112, pal=1
	tsa_entry 0x113, pal=1
	tsa_entry 0x114, pal=2
	tsa_entry 0x115, pal=2
	tsa_entry 0x116, pal=1
	tsa_entry 0x117, pal=4
	tsa_entry 0x118, pal=4
	tsa_entry 0x119, pal=4
	tsa_entry 0x11A, pal=4
	tsa_entry 0x11B, pal=4
	tsa_entry 0x11C, pal=4
	tsa_entry 0x11D, pal=4
	tsa_entry 0x11E, pal=4
	tsa_entry 0x11F, pal=2
	tsa_entry 0x120, pal=2
	tsa_entry 0x121, pal=2
	tsa_entry 0x122, pal=2
	tsa_entry 0x123, pal=2
	tsa_entry 0x124, pal=2
	tsa_entry 0x125, pal=2
	tsa_entry 0x126, pal=2
	tsa_entry 0x127, pal=2
	tsa_entry 0x128
	tsa_entry 0x129, pal=3
	tsa_entry 0x12A, pal=3
	tsa_entry 0x12B, pal=3
	tsa_entry 0x0F0
	tsa_entry 0x0F1
	tsa_entry 0x0F2
	tsa_entry 0x0F3, pal=1
	tsa_entry 0x0F4, pal=1
	tsa_entry 0x0F5
	tsa_entry 0x0F6, pal=2
	tsa_entry 0x0F7, pal=2
	tsa_entry 0x0F8, pal=2
	tsa_entry 0x0F9, pal=1
	tsa_entry 0x0FA, pal=2
	tsa_entry 0x0FB, pal=2
	tsa_entry 0x0FC, pal=4
	tsa_entry 0x0FD, pal=2
	tsa_entry 0x0FE, pal=2
	tsa_entry 0x0FF, pal=2
	tsa_entry 0x100, pal=2
	tsa_entry 0x101, pal=2
	tsa_entry 0x102, pal=2
	tsa_entry 0x103, pal=2
	tsa_entry 0x104, pal=2
	tsa_entry 0x105, pal=2
	tsa_entry 0x106, pal=2
	tsa_entry 0x107, pal=2
	tsa_entry 0x108, pal=2
	tsa_entry 0x109
	tsa_entry 0x10A
	tsa_entry 0x10B, pal=3
	tsa_entry 0x10C
	tsa_entry 0x10D, pal=3
	tsa_entry 0x0D2
	tsa_entry 0x0D3
	tsa_entry 0x0D4
	tsa_entry 0x0D5
	tsa_entry 0x0D6
	tsa_entry 0x0D7
	tsa_entry 0x0D8, pal=2
	tsa_entry 0x0D9, pal=2
	tsa_entry 0x0DA, pal=2
	tsa_entry 0x0DB, pal=1
	tsa_entry 0x0DC, pal=1
	tsa_entry 0x0DD, pal=1
	tsa_entry 0x0DE, pal=2
	tsa_entry 0x0DF, pal=1
	tsa_entry 0x0E0, pal=1
	tsa_entry 0x0E1, pal=1
	tsa_entry 0x0E2, pal=1
	tsa_entry 0x0E3, pal=1
	tsa_entry 0x0E4, pal=2
	tsa_entry 0x0E5, pal=2
	tsa_entry 0x0E6, pal=2
	tsa_entry 0x0E7, pal=2
	tsa_entry 0x0E8, pal=2
	tsa_entry 0x0E9, pal=2
	tsa_entry 0x0EA, pal=1
	tsa_entry 0x0EB, pal=1
	tsa_entry 0x0EC, pal=3
	tsa_entry 0x0ED, pal=3
	tsa_entry 0x0EE, pal=3
	tsa_entry 0x0EF, pal=3
	tsa_entry 0x0B4
	tsa_entry 0x0B5
	tsa_entry 0x0B6
	tsa_entry 0x0B7
	tsa_entry 0x0B8
	tsa_entry 0x0B9
	tsa_entry 0x0BA
	tsa_entry 0x0BB
	tsa_entry 0x0BC, pal=1
	tsa_entry 0x0BD, pal=1
	tsa_entry 0x0BE, pal=1
	tsa_entry 0x0BF, pal=2
	tsa_entry 0x0C0, pal=1
	tsa_entry 0x0C1, pal=1
	tsa_entry 0x0C2, pal=1
	tsa_entry 0x0C3, pal=1
	tsa_entry 0x0C4, pal=2
	tsa_entry 0x0C5, pal=2
	tsa_entry 0x0C6, pal=1
	tsa_entry 0x0C7, pal=2
	tsa_entry 0x0C8, pal=2
	tsa_entry 0x0C9, pal=1
	tsa_entry 0x0CA, pal=2
	tsa_entry 0x0CB, pal=1
	tsa_entry 0x0CC, pal=1
	tsa_entry 0x0CD, pal=1
	tsa_entry 0x0CE, pal=3
	tsa_entry 0x0CF, pal=3
	tsa_entry 0x0D0, pal=3
	tsa_entry 0x0D1, pal=3
	tsa_entry 0x096
	tsa_entry 0x097
	tsa_entry 0x098
	tsa_entry 0x099
	tsa_entry 0x09A
	tsa_entry 0x09B
	tsa_entry 0x09C
	tsa_entry 0x09D
	tsa_entry 0x09E, pal=1
	tsa_entry 0x09F, pal=1
	tsa_entry 0x0A0, pal=1
	tsa_entry 0x0A1, pal=1
	tsa_entry 0x0A2, pal=1
	tsa_entry 0x0A3, pal=1
	tsa_entry 0x0A4, pal=1
	tsa_entry 0x0A5, pal=1
	tsa_entry 0x0A6, pal=2
	tsa_entry 0x0A7, pal=1
	tsa_entry 0x0A8, pal=1
	tsa_entry 0x0A9, pal=1
	tsa_entry 0x0AA, pal=2
	tsa_entry 0x0AB, pal=1
	tsa_entry 0x0AC, pal=1
	tsa_entry 0x0AD, pal=1
	tsa_entry 0x0AE, pal=1
	tsa_entry 0x0AF, pal=3
	tsa_entry 0x0B0, pal=3
	tsa_entry 0x0B1, pal=3
	tsa_entry 0x0B2, pal=3
	tsa_entry 0x0B3, pal=3
	tsa_entry 0x078
	tsa_entry 0x079
	tsa_entry 0x07A
	tsa_entry 0x07B
	tsa_entry 0x07C
	tsa_entry 0x07D
	tsa_entry 0x07E
	tsa_entry 0x07F
	tsa_entry 0x080
	tsa_entry 0x081, pal=1
	tsa_entry 0x082, pal=1
	tsa_entry 0x083, pal=1
	tsa_entry 0x084, pal=1
	tsa_entry 0x085, pal=1
	tsa_entry 0x086, pal=1
	tsa_entry 0x087, pal=1
	tsa_entry 0x088, pal=1
	tsa_entry 0x089, pal=1
	tsa_entry 0x08A, pal=1
	tsa_entry 0x08B, pal=2
	tsa_entry 0x08C, pal=2
	tsa_entry 0x08D, pal=2
	tsa_entry 0x08E, pal=3
	tsa_entry 0x08F, pal=3
	tsa_entry 0x090, pal=3
	tsa_entry 0x091, pal=3
	tsa_entry 0x092, pal=3
	tsa_entry 0x093, pal=3
	tsa_entry 0x094, pal=3
	tsa_entry 0x095, pal=3
	tsa_entry 0x05A
	tsa_entry 0x05B
	tsa_entry 0x05C
	tsa_entry 0x05D
	tsa_entry 0x05E
	tsa_entry 0x05F
	tsa_entry 0x060
	tsa_entry 0x061
	tsa_entry 0x062
	tsa_entry 0x063, pal=1
	tsa_entry 0x064, pal=1
	tsa_entry 0x065, pal=1
	tsa_entry 0x066, pal=1
	tsa_entry 0x067, pal=1
	tsa_entry 0x068, pal=1
	tsa_entry 0x069, pal=1
	tsa_entry 0x06A, pal=1
	tsa_entry 0x06B, pal=1
	tsa_entry 0x06C, pal=1
	tsa_entry 0x06D, pal=1
	tsa_entry 0x06E, pal=3
	tsa_entry 0x06F, pal=3
	tsa_entry 0x070, pal=3
	tsa_entry 0x071, pal=3
	tsa_entry 0x072, pal=3
	tsa_entry 0x073, pal=3
	tsa_entry 0x074, pal=3
	tsa_entry 0x075, pal=3
	tsa_entry 0x076, pal=3
	tsa_entry 0x077, pal=3
	tsa_entry 0x03C
	tsa_entry 0x03D
	tsa_entry 0x03E
	tsa_entry 0x03F
	tsa_entry 0x040
	tsa_entry 0x041
	tsa_entry 0x042
	tsa_entry 0x043
	tsa_entry 0x044
	tsa_entry 0x045, pal=1
	tsa_entry 0x046, pal=1
	tsa_entry 0x047, pal=1
	tsa_entry 0x048, pal=1
	tsa_entry 0x049, pal=1
	tsa_entry 0x04A, pal=1
	tsa_entry 0x04B, pal=1
	tsa_entry 0x04C, pal=1
	tsa_entry 0x04D, pal=1
	tsa_entry 0x04E, pal=1
	tsa_entry 0x04F, pal=1
	tsa_entry 0x050, pal=3
	tsa_entry 0x051, pal=3
	tsa_entry 0x052, pal=3
	tsa_entry 0x053, pal=3
	tsa_entry 0x054, pal=3
	tsa_entry 0x055, pal=3
	tsa_entry 0x056, pal=3
	tsa_entry 0x057, pal=3
	tsa_entry 0x058, pal=3
	tsa_entry 0x059, pal=3
	tsa_entry 0x01E
	tsa_entry 0x01F
	tsa_entry 0x020
	tsa_entry 0x021
	tsa_entry 0x022
	tsa_entry 0x023
	tsa_entry 0x024
	tsa_entry 0x025
	tsa_entry 0x026
	tsa_entry 0x027, pal=1
	tsa_entry 0x028, pal=1
	tsa_entry 0x029, pal=1
	tsa_entry 0x02A, pal=1
	tsa_entry 0x02B, pal=1
	tsa_entry 0x02C, pal=1
	tsa_entry 0x02D, pal=1
	tsa_entry 0x02E, pal=1
	tsa_entry 0x02F, pal=3
	tsa_entry 0x030, pal=1
	tsa_entry 0x031, pal=1
	tsa_entry 0x032, pal=1
	tsa_entry 0x033, pal=3
	tsa_entry 0x034, pal=3
	tsa_entry 0x035, pal=3
	tsa_entry 0x036, pal=3
	tsa_entry 0x037, pal=3
	tsa_entry 0x038, pal=3
	tsa_entry 0x039, pal=3
	tsa_entry 0x03A, pal=3
	tsa_entry 0x03B, pal=3
	tsa_entry 0x000
	tsa_entry 0x001
	tsa_entry 0x002
	tsa_entry 0x003
	tsa_entry 0x004
	tsa_entry 0x005
	tsa_entry 0x006
	tsa_entry 0x007
	tsa_entry 0x008, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x00A, pal=1
	tsa_entry 0x00B, pal=1
	tsa_entry 0x00C, pal=1
	tsa_entry 0x00D, pal=1
	tsa_entry 0x00E, pal=1
	tsa_entry 0x00F, pal=3
	tsa_entry 0x010, pal=3
	tsa_entry 0x011, pal=3
	tsa_entry 0x012, pal=3
	tsa_entry 0x013, pal=1
	tsa_entry 0x014, pal=1
	tsa_entry 0x015, pal=1
	tsa_entry 0x016, pal=3
	tsa_entry 0x017, pal=3
	tsa_entry 0x018, pal=3
	tsa_entry 0x019, pal=3
	tsa_entry 0x01A, pal=3
	tsa_entry 0x01B, pal=3
	tsa_entry 0x01C
	tsa_entry 0x01D
	tsa_entry 0x000
