	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x11D
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x050, vflip=1
	tsa_entry 0x051, vflip=1
	tsa_entry 0x052, vflip=1
	tsa_entry 0x053, vflip=1
	tsa_entry 0x053, vflip=1
	tsa_entry 0x053, vflip=1
	tsa_entry 0x053, vflip=1
	tsa_entry 0x053, vflip=1
	tsa_entry 0x054, vflip=1
	tsa_entry 0x006, vflip=1
	tsa_entry 0x006, vflip=1
	tsa_entry 0x006, vflip=1
	tsa_entry 0x006, vflip=1
	tsa_entry 0x006, vflip=1
	tsa_entry 0x006, vflip=1
	tsa_entry 0x006, vflip=1
	tsa_entry 0x006, vflip=1
	tsa_entry 0x006, vflip=1
	tsa_entry 0x006, vflip=1
	tsa_entry 0x006, vflip=1
	tsa_entry 0x006, vflip=1
	tsa_entry 0x054, hflip=1, vflip=1
	tsa_entry 0x053, vflip=1
	tsa_entry 0x053, vflip=1
	tsa_entry 0x053, vflip=1
	tsa_entry 0x053, vflip=1
	tsa_entry 0x053, vflip=1
	tsa_entry 0x052, hflip=1, vflip=1
	tsa_entry 0x051, hflip=1, vflip=1
	tsa_entry 0x050, hflip=1, vflip=1
	tsa_entry 0x000
