	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x002, pal=1
	tsa_entry 0x001, pal=1
	tsa_entry 0x001, pal=1
	tsa_entry 0x001, pal=1
	tsa_entry 0x009, pal=1, hflip=1
	tsa_entry 0x008, pal=1, hflip=1
	tsa_entry 0x007, pal=1, hflip=1
	tsa_entry 0x006, pal=1, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x044, pal=1
	tsa_entry 0x046, pal=1
	tsa_entry 0x048, pal=1
	tsa_entry 0x04A, pal=1
	tsa_entry 0x04C, pal=1
	tsa_entry 0x04E, pal=1
	tsa_entry 0x050, pal=1
	tsa_entry 0x00A, pal=1, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x045, pal=1
	tsa_entry 0x047, pal=1
	tsa_entry 0x049, pal=1
	tsa_entry 0x04B, pal=1
	tsa_entry 0x04D, pal=1
	tsa_entry 0x04F, pal=1
	tsa_entry 0x051, pal=1
	tsa_entry 0x004, pal=1, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x00E, pal=1, hflip=1
	tsa_entry 0x00D, pal=1
	tsa_entry 0x00D, pal=1
	tsa_entry 0x00D, pal=1
	tsa_entry 0x00D, pal=1
	tsa_entry 0x00D, pal=1
	tsa_entry 0x00C, pal=1
	tsa_entry 0x00B, pal=1, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
