	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x003
	tsa_entry 0x003, pal=1, hflip=1
	tsa_entry 0x010
	tsa_entry 0x010, pal=1, hflip=1
	tsa_entry 0x011
	tsa_entry 0x011, pal=1, hflip=1
	tsa_entry 0x00F
	tsa_entry 0x00F, pal=1, hflip=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x013
	tsa_entry 0x013, pal=1, hflip=1
	tsa_entry 0x022
	tsa_entry 0x022, pal=1, hflip=1
	tsa_entry 0x022
	tsa_entry 0x022, pal=1, hflip=1
	tsa_entry 0x022
	tsa_entry 0x022, pal=1, hflip=1
	tsa_entry 0x023
	tsa_entry 0x023, pal=1, hflip=1
	tsa_entry 0x022
	tsa_entry 0x022, pal=1, hflip=1
	tsa_entry 0x024
	tsa_entry 0x024, pal=1, hflip=1
