	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x012, pal=1
	tsa_entry 0x012, pal=1
	tsa_entry 0x012, pal=1
	tsa_entry 0x012, pal=1
	tsa_entry 0x012, pal=1
	tsa_entry 0x013, pal=1
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x014, pal=1
	tsa_entry 0x014, pal=1
	tsa_entry 0x014, pal=1
	tsa_entry 0x014, pal=1
	tsa_entry 0x014, pal=1
	tsa_entry 0x015, pal=1
	tsa_entry 0x016, pal=1
	tsa_entry 0x016, pal=1
	tsa_entry 0x017, pal=1
	tsa_entry 0x017, pal=1
	tsa_entry 0x018, pal=1
	tsa_entry 0x018, pal=1
	tsa_entry 0x018, pal=1
	tsa_entry 0x019, pal=1
	tsa_entry 0x01A, pal=1
	tsa_entry 0x014, pal=1
	tsa_entry 0x014, pal=1
	tsa_entry 0x014, pal=1
	tsa_entry 0x014, pal=1
	tsa_entry 0x014, pal=1
	tsa_entry 0x01B, pal=1
	tsa_entry 0x01C, pal=1
	tsa_entry 0x052
	tsa_entry 0x054
	tsa_entry 0x056
	tsa_entry 0x058
	tsa_entry 0x05A
	tsa_entry 0x05C
	tsa_entry 0x05E
	tsa_entry 0x060
	tsa_entry 0x014, pal=1
	tsa_entry 0x014, pal=1
	tsa_entry 0x014, pal=1
	tsa_entry 0x014, pal=1
	tsa_entry 0x014, pal=1
	tsa_entry 0x01E, pal=1
	tsa_entry 0x01F, pal=1
	tsa_entry 0x053
	tsa_entry 0x055
	tsa_entry 0x057
	tsa_entry 0x059
	tsa_entry 0x05B
	tsa_entry 0x05D
	tsa_entry 0x05F
	tsa_entry 0x061
	tsa_entry 0x025, pal=1
	tsa_entry 0x026, pal=1
	tsa_entry 0x027, pal=1
	tsa_entry 0x028, pal=1
	tsa_entry 0x029, pal=1
	tsa_entry 0x02A, pal=1
	tsa_entry 0x02B, pal=1
	tsa_entry 0x02C, pal=1
	tsa_entry 0x02C, pal=1
	tsa_entry 0x02C, pal=1
	tsa_entry 0x02C, pal=1
	tsa_entry 0x02D, pal=1
	tsa_entry 0x02D, pal=1
	tsa_entry 0x02D, pal=1
	tsa_entry 0x02E, pal=1
	tsa_entry 0x02F, pal=1
	tsa_entry 0x030, pal=1
	tsa_entry 0x031, pal=1
	tsa_entry 0x032, pal=1
	tsa_entry 0x033, pal=1
	tsa_entry 0x034, pal=1
	tsa_entry 0x005, pal=1
	tsa_entry 0x005, pal=1
	tsa_entry 0x005, pal=1
	tsa_entry 0x005, pal=1
	tsa_entry 0x005, pal=1
	tsa_entry 0x005, pal=1
	tsa_entry 0x005, pal=1
	tsa_entry 0x005, pal=1
	tsa_entry 0x035, pal=1
	tsa_entry 0x036, pal=1
	tsa_entry 0x037, pal=1
	tsa_entry 0x038, pal=1
	tsa_entry 0x039, pal=1
	tsa_entry 0x03A, pal=1
	tsa_entry 0x03B, pal=1
	tsa_entry 0x03C, pal=1
	tsa_entry 0x03D, pal=1
	tsa_entry 0x03E, pal=1
	tsa_entry 0x03F, pal=1
	tsa_entry 0x040, pal=1
	tsa_entry 0x041, pal=1
	tsa_entry 0x042, pal=1
	tsa_entry 0x042, pal=1
	tsa_entry 0x043, pal=1
	tsa_entry 0x000
