.PHONY: ownership-probe-check ownership-probe-test

ownership-probe-check:
	/usr/bin/python3 -I -S -B scripts/validation_ownership/isolated_launcher.py

ownership-probe-test:
	python3 -m unittest scripts.validation_ownership.tests.test_foundation scripts.validation_ownership.tests.test_metadata_transport scripts.validation_ownership.tests.test_producer scripts.validation_ownership.tests.test_content_publication scripts.validation_ownership.tests.test_dependency scripts.validation_ownership.tests.test_private_install scripts.validation_ownership.tests.test_text_producer scripts.validation_ownership.tests.test_header_effects scripts.validation_ownership.tests.test_header_pipeline scripts.validation_ownership.tests.test_read_epochs scripts.validation_ownership.tests.test_source_phases scripts.validation_ownership.tests.test_source_effects scripts.validation_ownership.tests.test_source_journal scripts.validation_ownership.tests.test_source_directories scripts.validation_ownership.tests.test_file_ownership -v
