"""Small committed public inventory/summary for the ``units`` table.

Deliberately not "bulky C" -- just IDs, counts, and a dependency digest, so
it is cheap to review in a diff and cheap to drift-check.
"""

from __future__ import annotations

from .schema import SCHEMA_ID, dependency_graph


def build_inventory(records):
    graph = dependency_graph()
    total_units = sum(len(g.units) for g in records)
    lines = []
    lines.append("# Generated-data inventory: units\n")
    lines.append("\n")
    lines.append("_Auto-generated by `python3 -m scripts.generated_data generate --table units`. "
                  "Do not edit by hand -- see docs/generated_data.md._\n")
    lines.append("\n")
    lines.append("- Schema: `{}`\n".format(SCHEMA_ID))
    lines.append("- Group count: {}\n".format(len(records)))
    lines.append("- Total unit count: {}\n".format(total_units))
    lines.append("- Dependencies: {}\n".format(", ".join(graph.nodes())))
    lines.append("- Dependency graph digest (sha256): `{}`\n".format(graph.digest()))
    lines.append("\n")
    lines.append("| Group symbol | Unit count | REDA count |\n")
    lines.append("|---|---|---|\n")
    for group in sorted(records, key=lambda g: g.symbol):
        reda_total = sum(len(u.redas) for u in group.units)
        lines.append("| {} | {} | {} |\n".format(group.symbol, len(group.units), reda_total))
    return "".join(lines)
