	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x000, hflip=1
	tsa_entry 0x001, hflip=1
	tsa_entry 0x001, hflip=1
	tsa_entry 0x001, hflip=1
	tsa_entry 0x001
	tsa_entry 0x001
	tsa_entry 0x001, hflip=1
	tsa_entry 0x001, hflip=1
	tsa_entry 0x001, hflip=1
	tsa_entry 0x001
	tsa_entry 0x001
	tsa_entry 0x001, hflip=1
	tsa_entry 0x001, hflip=1
	tsa_entry 0x001, hflip=1
	tsa_entry 0x001
	tsa_entry 0x001
	tsa_entry 0x001, hflip=1
	tsa_entry 0x001, hflip=1
	tsa_entry 0x001
	tsa_entry 0x001
	tsa_entry 0x001
	tsa_entry 0x001, hflip=1
	tsa_entry 0x001, hflip=1
	tsa_entry 0x001
	tsa_entry 0x001
	tsa_entry 0x001
	tsa_entry 0x001, hflip=1
	tsa_entry 0x001, hflip=1
	tsa_entry 0x001
	tsa_entry 0x001
	tsa_entry 0x001
	tsa_entry 0x002, hflip=1
	tsa_entry 0x003
	tsa_entry 0x003, hflip=1
	tsa_entry 0x002
	tsa_entry 0x002
	tsa_entry 0x002, hflip=1
	tsa_entry 0x003
	tsa_entry 0x003, hflip=1
	tsa_entry 0x002
	tsa_entry 0x002
	tsa_entry 0x002, hflip=1
	tsa_entry 0x003
	tsa_entry 0x003, hflip=1
	tsa_entry 0x002
	tsa_entry 0x002
	tsa_entry 0x002
	tsa_entry 0x002, hflip=1
	tsa_entry 0x003
	tsa_entry 0x003, hflip=1
	tsa_entry 0x002
	tsa_entry 0x002
	tsa_entry 0x002, hflip=1
	tsa_entry 0x003
	tsa_entry 0x003, hflip=1
	tsa_entry 0x002
	tsa_entry 0x002
	tsa_entry 0x002, hflip=1
	tsa_entry 0x003
	tsa_entry 0x003, hflip=1
	tsa_entry 0x002
	tsa_entry 0x005
	tsa_entry 0x006
	tsa_entry 0x006, hflip=1
	tsa_entry 0x005, hflip=1
	tsa_entry 0x004
	tsa_entry 0x005
	tsa_entry 0x006
	tsa_entry 0x006, hflip=1
	tsa_entry 0x005, hflip=1
	tsa_entry 0x004
	tsa_entry 0x005
	tsa_entry 0x006
	tsa_entry 0x006, hflip=1
	tsa_entry 0x005, hflip=1
	tsa_entry 0x004
	tsa_entry 0x004, hflip=1
	tsa_entry 0x005
	tsa_entry 0x006
	tsa_entry 0x006, hflip=1
	tsa_entry 0x005, hflip=1
	tsa_entry 0x004, hflip=1
	tsa_entry 0x005
	tsa_entry 0x006
	tsa_entry 0x006, hflip=1
	tsa_entry 0x005, hflip=1
	tsa_entry 0x004, hflip=1
	tsa_entry 0x005
	tsa_entry 0x006
	tsa_entry 0x006, hflip=1
	tsa_entry 0x005, hflip=1
	tsa_entry 0x008
	tsa_entry 0x009
	tsa_entry 0x009, hflip=1
	tsa_entry 0x008, hflip=1
	tsa_entry 0x007
	tsa_entry 0x008
	tsa_entry 0x009
	tsa_entry 0x009, hflip=1
	tsa_entry 0x008, hflip=1
	tsa_entry 0x007
	tsa_entry 0x008
	tsa_entry 0x009
	tsa_entry 0x009, hflip=1
	tsa_entry 0x008, hflip=1
	tsa_entry 0x007
	tsa_entry 0x007, hflip=1
	tsa_entry 0x008
	tsa_entry 0x009
	tsa_entry 0x009, hflip=1
	tsa_entry 0x008, hflip=1
	tsa_entry 0x007, hflip=1
	tsa_entry 0x008
	tsa_entry 0x009
	tsa_entry 0x009, hflip=1
	tsa_entry 0x008, hflip=1
	tsa_entry 0x007, hflip=1
	tsa_entry 0x008
	tsa_entry 0x009
	tsa_entry 0x009, hflip=1
	tsa_entry 0x008, hflip=1
	tsa_entry 0x00B
	tsa_entry 0x00C
	tsa_entry 0x00C, hflip=1
	tsa_entry 0x00B, hflip=1
	tsa_entry 0x00A
	tsa_entry 0x00B
	tsa_entry 0x00C
	tsa_entry 0x00C, hflip=1
	tsa_entry 0x00B, hflip=1
	tsa_entry 0x00A
	tsa_entry 0x00B
	tsa_entry 0x00C
	tsa_entry 0x00C, hflip=1
	tsa_entry 0x00B, hflip=1
	tsa_entry 0x00A
	tsa_entry 0x00A, hflip=1
	tsa_entry 0x00B
	tsa_entry 0x00C
	tsa_entry 0x00C, hflip=1
	tsa_entry 0x00B, hflip=1
	tsa_entry 0x00A, hflip=1
	tsa_entry 0x00B
	tsa_entry 0x00C
	tsa_entry 0x00C, hflip=1
	tsa_entry 0x00B, hflip=1
	tsa_entry 0x00A, hflip=1
	tsa_entry 0x00B
	tsa_entry 0x00C
	tsa_entry 0x00C, hflip=1
	tsa_entry 0x00B, hflip=1
	tsa_entry 0x00D
	tsa_entry 0x00E
	tsa_entry 0x00E, hflip=1
	tsa_entry 0x00D, hflip=1
	tsa_entry 0x00A
	tsa_entry 0x00D
	tsa_entry 0x00E
	tsa_entry 0x00E, hflip=1
	tsa_entry 0x00D, hflip=1
	tsa_entry 0x00A
	tsa_entry 0x00D
	tsa_entry 0x00E
	tsa_entry 0x00E, hflip=1
	tsa_entry 0x00D, hflip=1
	tsa_entry 0x00A
	tsa_entry 0x00A, hflip=1
	tsa_entry 0x00D
	tsa_entry 0x00E
	tsa_entry 0x00E, hflip=1
	tsa_entry 0x00D, hflip=1
	tsa_entry 0x00A, hflip=1
	tsa_entry 0x00D
	tsa_entry 0x00E
	tsa_entry 0x00E, hflip=1
	tsa_entry 0x00D, hflip=1
	tsa_entry 0x00A, hflip=1
	tsa_entry 0x00D
	tsa_entry 0x00E
	tsa_entry 0x00E, hflip=1
	tsa_entry 0x00D, hflip=1
	tsa_entry 0x00F
	tsa_entry 0x00F
	tsa_entry 0x00F
	tsa_entry 0x00F
	tsa_entry 0x00F
	tsa_entry 0x00F
	tsa_entry 0x00F
	tsa_entry 0x00F
	tsa_entry 0x00F
	tsa_entry 0x00F
	tsa_entry 0x00F
	tsa_entry 0x00F
	tsa_entry 0x00F
	tsa_entry 0x00F
	tsa_entry 0x00F
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x00F, hflip=1
	tsa_entry 0x010, pal=3
	tsa_entry 0x011, pal=3
	tsa_entry 0x012, pal=3
	tsa_entry 0x013, pal=3
	tsa_entry 0x014, pal=3
	tsa_entry 0x015, pal=3
	tsa_entry 0x016, pal=3
	tsa_entry 0x017, pal=3
	tsa_entry 0x018, pal=3
	tsa_entry 0x019, pal=3
	tsa_entry 0x01A, pal=3
	tsa_entry 0x01B, pal=3
	tsa_entry 0x01C, pal=3
	tsa_entry 0x01D, pal=3
	tsa_entry 0x01E, pal=3
	tsa_entry 0x01E, pal=3, hflip=1
	tsa_entry 0x01D, pal=3, hflip=1
	tsa_entry 0x01C, pal=3, hflip=1
	tsa_entry 0x01B, pal=3, hflip=1
	tsa_entry 0x01A, pal=3, hflip=1
	tsa_entry 0x019, pal=3, hflip=1
	tsa_entry 0x018, pal=3, hflip=1
	tsa_entry 0x017, pal=3, hflip=1
	tsa_entry 0x016, pal=3, hflip=1
	tsa_entry 0x015, pal=3, hflip=1
	tsa_entry 0x014, pal=3, hflip=1
	tsa_entry 0x013, pal=3, hflip=1
	tsa_entry 0x012, pal=3, hflip=1
	tsa_entry 0x011, pal=3, hflip=1
	tsa_entry 0x010, pal=3, hflip=1
	tsa_entry 0x01F, pal=3
	tsa_entry 0x020, pal=3
	tsa_entry 0x021, pal=3
	tsa_entry 0x022, pal=3
	tsa_entry 0x023, pal=3
	tsa_entry 0x024, pal=3
	tsa_entry 0x025, pal=3
	tsa_entry 0x026, pal=3
	tsa_entry 0x027, pal=3
	tsa_entry 0x028, pal=3
	tsa_entry 0x029, pal=3
	tsa_entry 0x02A, pal=3
	tsa_entry 0x02B, pal=3
	tsa_entry 0x02C, pal=3
	tsa_entry 0x02D, pal=3
	tsa_entry 0x02D, pal=3, hflip=1
	tsa_entry 0x02C, pal=3, hflip=1
	tsa_entry 0x02B, pal=3, hflip=1
	tsa_entry 0x02A, pal=3, hflip=1
	tsa_entry 0x029, pal=3, hflip=1
	tsa_entry 0x028, pal=3, hflip=1
	tsa_entry 0x027, pal=3, hflip=1
	tsa_entry 0x026, pal=3, hflip=1
	tsa_entry 0x025, pal=3, hflip=1
	tsa_entry 0x024, pal=3, hflip=1
	tsa_entry 0x023, pal=3, hflip=1
	tsa_entry 0x022, pal=3, hflip=1
	tsa_entry 0x021, pal=3, hflip=1
	tsa_entry 0x020, pal=3, hflip=1
	tsa_entry 0x01F, pal=3, hflip=1
	tsa_entry 0x02E, pal=3
	tsa_entry 0x02F, pal=3
	tsa_entry 0x030, pal=3
	tsa_entry 0x031, pal=3
	tsa_entry 0x032, pal=3
	tsa_entry 0x033, pal=3
	tsa_entry 0x034, pal=3
	tsa_entry 0x035, pal=3
	tsa_entry 0x036, pal=3
	tsa_entry 0x037, pal=3
	tsa_entry 0x038, pal=3
	tsa_entry 0x039, pal=3
	tsa_entry 0x03A, pal=3
	tsa_entry 0x03B, pal=3
	tsa_entry 0x03C, pal=3
	tsa_entry 0x03C, pal=3, hflip=1
	tsa_entry 0x03B, pal=3, hflip=1
	tsa_entry 0x03A, pal=3, hflip=1
	tsa_entry 0x039, pal=3, hflip=1
	tsa_entry 0x038, pal=3, hflip=1
	tsa_entry 0x037, pal=3, hflip=1
	tsa_entry 0x036, pal=3, hflip=1
	tsa_entry 0x035, pal=3, hflip=1
	tsa_entry 0x034, pal=3, hflip=1
	tsa_entry 0x033, pal=3, hflip=1
	tsa_entry 0x032, pal=3, hflip=1
	tsa_entry 0x031, pal=3, hflip=1
	tsa_entry 0x030, pal=3, hflip=1
	tsa_entry 0x02F, pal=3, hflip=1
	tsa_entry 0x02E, pal=3, hflip=1
	tsa_entry 0x03D, pal=2
	tsa_entry 0x03E, pal=2
	tsa_entry 0x03F, pal=2
	tsa_entry 0x040, pal=2
	tsa_entry 0x041, pal=2
	tsa_entry 0x042, pal=2
	tsa_entry 0x043, pal=2
	tsa_entry 0x044, pal=2
	tsa_entry 0x045, pal=2
	tsa_entry 0x046, pal=2
	tsa_entry 0x047, pal=2
	tsa_entry 0x048, pal=2
	tsa_entry 0x049, pal=2
	tsa_entry 0x049, pal=2
	tsa_entry 0x049, pal=2
	tsa_entry 0x049, pal=2, hflip=1
	tsa_entry 0x049, pal=2, hflip=1
	tsa_entry 0x049, pal=2, hflip=1
	tsa_entry 0x048, pal=2, hflip=1
	tsa_entry 0x047, pal=2, hflip=1
	tsa_entry 0x046, pal=2, hflip=1
	tsa_entry 0x045, pal=2, hflip=1
	tsa_entry 0x044, pal=2, hflip=1
	tsa_entry 0x043, pal=2, hflip=1
	tsa_entry 0x042, pal=2, hflip=1
	tsa_entry 0x041, pal=2, hflip=1
	tsa_entry 0x040, pal=2, hflip=1
	tsa_entry 0x03F, pal=2, hflip=1
	tsa_entry 0x03E, pal=2, hflip=1
	tsa_entry 0x03D, pal=2, hflip=1
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
