	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x13D, pal=4
	tsa_entry 0x13D, pal=4
	tsa_entry 0x13D, pal=4
	tsa_entry 0x002, pal=4
	tsa_entry 0x003, pal=4
	tsa_entry 0x004, pal=4
	tsa_entry 0x005, pal=4
	tsa_entry 0x006, pal=4
	tsa_entry 0x13D, pal=4
	tsa_entry 0x13D, pal=4
	tsa_entry 0x009, pal=4
	tsa_entry 0x00A, pal=4
	tsa_entry 0x13D, pal=4
	tsa_entry 0x13D, pal=4
	tsa_entry 0x13D, pal=4
	tsa_entry 0x13D, pal=4
	tsa_entry 0x13D, pal=4
	tsa_entry 0x13D, pal=4
	tsa_entry 0x00C, pal=4
	tsa_entry 0x00D, pal=4
	tsa_entry 0x13D, pal=4
	tsa_entry 0x13D, pal=4
	tsa_entry 0x13D, pal=4
	tsa_entry 0x00E, pal=4
	tsa_entry 0x00F, pal=4
	tsa_entry 0x010, pal=4
	tsa_entry 0x00A, pal=4
	tsa_entry 0x13D, pal=4
	tsa_entry 0x13D, pal=4
	tsa_entry 0x13D, pal=4
	tsa_entry 0x011, pal=1
	tsa_entry 0x012, pal=3
	tsa_entry 0x013
	tsa_entry 0x014, pal=1
	tsa_entry 0x015, pal=1
	tsa_entry 0x016, pal=1
	tsa_entry 0x017, pal=1
	tsa_entry 0x018
	tsa_entry 0x019, pal=1
	tsa_entry 0x01A
	tsa_entry 0x01B, pal=3
	tsa_entry 0x01C
	tsa_entry 0x01D, pal=3
	tsa_entry 0x01E
	tsa_entry 0x01F, pal=1
	tsa_entry 0x020
	tsa_entry 0x021, pal=1
	tsa_entry 0x022
	tsa_entry 0x023, pal=1
	tsa_entry 0x024, pal=1
	tsa_entry 0x025, pal=3
	tsa_entry 0x026, pal=1
	tsa_entry 0x027, pal=3
	tsa_entry 0x028, pal=1
	tsa_entry 0x029
	tsa_entry 0x02A, pal=1
	tsa_entry 0x02B, pal=1
	tsa_entry 0x02C, pal=3
	tsa_entry 0x02D
	tsa_entry 0x02E, pal=3
	tsa_entry 0x02F, pal=2
	tsa_entry 0x030, pal=3
	tsa_entry 0x031
	tsa_entry 0x032, pal=1
	tsa_entry 0x033
	tsa_entry 0x034, pal=1
	tsa_entry 0x035
	tsa_entry 0x036
	tsa_entry 0x037, pal=1
	tsa_entry 0x038, pal=3
	tsa_entry 0x039, pal=1
	tsa_entry 0x03A
	tsa_entry 0x03B, pal=3
	tsa_entry 0x03C, pal=1
	tsa_entry 0x03D, pal=3
	tsa_entry 0x03E
	tsa_entry 0x03F, pal=1
	tsa_entry 0x040
	tsa_entry 0x041, pal=1
	tsa_entry 0x042
	tsa_entry 0x043, pal=3
	tsa_entry 0x044, pal=3
	tsa_entry 0x045, pal=3
	tsa_entry 0x046, pal=1
	tsa_entry 0x047, pal=1
	tsa_entry 0x048, pal=1
	tsa_entry 0x049, pal=1
	tsa_entry 0x04A, pal=3
	tsa_entry 0x04B, pal=3
	tsa_entry 0x04C, pal=3
	tsa_entry 0x04D, pal=1
	tsa_entry 0x04E, pal=3
	tsa_entry 0x04F, pal=3
	tsa_entry 0x050, pal=1
	tsa_entry 0x051, pal=1
	tsa_entry 0x052, pal=1
	tsa_entry 0x053
	tsa_entry 0x054, pal=3
	tsa_entry 0x055, pal=1
	tsa_entry 0x056
	tsa_entry 0x057
	tsa_entry 0x058
	tsa_entry 0x059
	tsa_entry 0x05A, pal=1
	tsa_entry 0x05B, pal=3
	tsa_entry 0x05C
	tsa_entry 0x05D, pal=1
	tsa_entry 0x05E
	tsa_entry 0x05F, pal=1
	tsa_entry 0x060
	tsa_entry 0x061
	tsa_entry 0x062
	tsa_entry 0x063, pal=3
	tsa_entry 0x064, pal=1
	tsa_entry 0x065, pal=1
	tsa_entry 0x066, pal=1
	tsa_entry 0x067
	tsa_entry 0x068
	tsa_entry 0x069, pal=3
	tsa_entry 0x06A, pal=3
	tsa_entry 0x06B, pal=1
	tsa_entry 0x06C, pal=2
	tsa_entry 0x06D
	tsa_entry 0x06E, pal=1
	tsa_entry 0x06F
	tsa_entry 0x070, pal=1
	tsa_entry 0x071, pal=1
	tsa_entry 0x072
	tsa_entry 0x073, pal=2
	tsa_entry 0x074, pal=1
	tsa_entry 0x075, pal=3
	tsa_entry 0x076
	tsa_entry 0x077
	tsa_entry 0x078
	tsa_entry 0x079, pal=3
	tsa_entry 0x07A, pal=3
	tsa_entry 0x07B, pal=2
	tsa_entry 0x07C, pal=1
	tsa_entry 0x07D
	tsa_entry 0x07E
	tsa_entry 0x07F
	tsa_entry 0x080
	tsa_entry 0x081
	tsa_entry 0x082, pal=1
	tsa_entry 0x083, pal=1
	tsa_entry 0x084
	tsa_entry 0x085
	tsa_entry 0x086
	tsa_entry 0x087
	tsa_entry 0x088
	tsa_entry 0x089, pal=3
	tsa_entry 0x08A, pal=2
	tsa_entry 0x08B, pal=3
	tsa_entry 0x08C
	tsa_entry 0x08D, pal=1
	tsa_entry 0x08E, pal=1
	tsa_entry 0x08F, pal=1
	tsa_entry 0x090, pal=2
	tsa_entry 0x091, pal=2
	tsa_entry 0x092, pal=2
	tsa_entry 0x093, pal=3
	tsa_entry 0x094, pal=3
	tsa_entry 0x095, pal=3
	tsa_entry 0x096, pal=3
	tsa_entry 0x097, pal=3
	tsa_entry 0x098, pal=3
	tsa_entry 0x099, pal=1
	tsa_entry 0x09A
	tsa_entry 0x09B, pal=2
	tsa_entry 0x09C, pal=3
	tsa_entry 0x09D
	tsa_entry 0x09E, pal=3
	tsa_entry 0x09F, pal=3
	tsa_entry 0x0A0, pal=1
	tsa_entry 0x0A1
	tsa_entry 0x0A2
	tsa_entry 0x0A3, pal=3
	tsa_entry 0x0A4
	tsa_entry 0x0A5, pal=3
	tsa_entry 0x0A6, pal=3
	tsa_entry 0x0A7, pal=3
	tsa_entry 0x0A8, pal=3
	tsa_entry 0x0A9, pal=2
	tsa_entry 0x0AA, pal=3
	tsa_entry 0x0AB, pal=1
	tsa_entry 0x0AC, pal=1
	tsa_entry 0x0AD
	tsa_entry 0x0AE, pal=2
	tsa_entry 0x0AF, pal=2
	tsa_entry 0x0B0, pal=3
	tsa_entry 0x0B1, pal=2
	tsa_entry 0x0B2, pal=3
	tsa_entry 0x0B3, pal=3
	tsa_entry 0x0B4, pal=3
	tsa_entry 0x0B5
	tsa_entry 0x0B6
	tsa_entry 0x0B7, pal=2
	tsa_entry 0x0B8, pal=3
	tsa_entry 0x0B9, pal=3
	tsa_entry 0x0BA, pal=3
	tsa_entry 0x0BB
	tsa_entry 0x0BC, pal=3
	tsa_entry 0x0BD, pal=3
	tsa_entry 0x0BE, pal=1
	tsa_entry 0x0BF, pal=1
	tsa_entry 0x0C0
	tsa_entry 0x0C1, pal=3
	tsa_entry 0x0C2, pal=2
	tsa_entry 0x0C3, pal=3
	tsa_entry 0x0C4, pal=3
	tsa_entry 0x0C5, pal=2
	tsa_entry 0x0C6, pal=2
	tsa_entry 0x0C7, pal=2
	tsa_entry 0x0C8, pal=2
	tsa_entry 0x0C9, pal=2
	tsa_entry 0x0CA, pal=1
	tsa_entry 0x0CB, pal=1
	tsa_entry 0x0CC, pal=2
	tsa_entry 0x0CD, pal=2
	tsa_entry 0x0CE, pal=2
	tsa_entry 0x0CF, pal=2
	tsa_entry 0x0D0, pal=2
	tsa_entry 0x0D1, pal=2
	tsa_entry 0x0D2, pal=2
	tsa_entry 0x0D3, pal=2
	tsa_entry 0x0D4, pal=2
	tsa_entry 0x0D5, pal=2
	tsa_entry 0x0D6, pal=2
	tsa_entry 0x0D7, pal=2
	tsa_entry 0x0D8, pal=2
	tsa_entry 0x0D9, pal=2
	tsa_entry 0x0DA, pal=2
	tsa_entry 0x0DB, pal=2
	tsa_entry 0x0DC, pal=1
	tsa_entry 0x0DD, pal=1
	tsa_entry 0x0DE, pal=1
	tsa_entry 0x0DF, pal=2
	tsa_entry 0x0E0, pal=2
	tsa_entry 0x0E1, pal=2
	tsa_entry 0x0E2, pal=2
	tsa_entry 0x0E3, pal=3
	tsa_entry 0x0E4, pal=2
	tsa_entry 0x0E5, pal=2
	tsa_entry 0x0E6, pal=2
	tsa_entry 0x0E7, pal=2
	tsa_entry 0x0E8, pal=2
	tsa_entry 0x0E9, pal=3
	tsa_entry 0x0EA, pal=3
	tsa_entry 0x0EB, pal=3
	tsa_entry 0x0EC, pal=2
	tsa_entry 0x0ED, pal=2
	tsa_entry 0x0EE, pal=2
	tsa_entry 0x0EF, pal=3
	tsa_entry 0x0F0, pal=3
	tsa_entry 0x0F1, pal=2
	tsa_entry 0x0F2, pal=2
	tsa_entry 0x0F3, pal=2
	tsa_entry 0x0F4, pal=3
	tsa_entry 0x0F5, pal=2
	tsa_entry 0x0F6, pal=2
	tsa_entry 0x0F7
	tsa_entry 0x0F8, pal=2
	tsa_entry 0x0F9, pal=2
	tsa_entry 0x0FA, pal=2
	tsa_entry 0x0FB, pal=2
	tsa_entry 0x0FC, pal=3
	tsa_entry 0x0FD, pal=2
	tsa_entry 0x0FE, pal=2
	tsa_entry 0x0FF, pal=2
	tsa_entry 0x100, pal=2
	tsa_entry 0x101, pal=2
	tsa_entry 0x102, pal=2
	tsa_entry 0x103, pal=3
	tsa_entry 0x104, pal=2
	tsa_entry 0x105
	tsa_entry 0x106, pal=1
	tsa_entry 0x107, pal=1
	tsa_entry 0x108, pal=1
	tsa_entry 0x109, pal=2
	tsa_entry 0x10A, pal=3
	tsa_entry 0x10B, pal=3
	tsa_entry 0x10C, pal=3
	tsa_entry 0x10D, pal=2
	tsa_entry 0x10E, pal=3
	tsa_entry 0x10F, pal=2
	tsa_entry 0x110, pal=2
	tsa_entry 0x111, pal=3
	tsa_entry 0x112, pal=3
	tsa_entry 0x113
	tsa_entry 0x114, pal=2
	tsa_entry 0x115, pal=3
	tsa_entry 0x116, pal=2
	tsa_entry 0x117, pal=2
	tsa_entry 0x118, pal=1
	tsa_entry 0x119, pal=1
	tsa_entry 0x11A, pal=1
	tsa_entry 0x11B, pal=2
	tsa_entry 0x11C, pal=2
	tsa_entry 0x11D, pal=3
	tsa_entry 0x11E, pal=2
	tsa_entry 0x11F, pal=2
	tsa_entry 0x120, pal=2
	tsa_entry 0x121, pal=2
	tsa_entry 0x122, pal=2
	tsa_entry 0x123
	tsa_entry 0x124, pal=2
	tsa_entry 0x125, pal=1
	tsa_entry 0x126, pal=1
	tsa_entry 0x127, pal=2
	tsa_entry 0x128, pal=2
	tsa_entry 0x129, pal=3
	tsa_entry 0x12A, pal=2
	tsa_entry 0x12B, pal=2
	tsa_entry 0x12C, pal=3
	tsa_entry 0x12D, pal=3
	tsa_entry 0x12E, pal=2
	tsa_entry 0x12F, pal=3
	tsa_entry 0x130, pal=2
	tsa_entry 0x131, pal=2
	tsa_entry 0x132, pal=2
	tsa_entry 0x133, pal=3
	tsa_entry 0x134, pal=2
	tsa_entry 0x135, pal=2
	tsa_entry 0x136, pal=1
	tsa_entry 0x137, pal=1
	tsa_entry 0x138, pal=1
	tsa_entry 0x139, pal=2
	tsa_entry 0x13A, pal=2
	tsa_entry 0x13B, pal=3
	tsa_entry 0x13C, pal=2
	tsa_entry 0x001, pal=4
	tsa_entry 0x001, pal=4
	tsa_entry 0x001, pal=4
	tsa_entry 0x008, pal=4
	tsa_entry 0x007, pal=4
	tsa_entry 0x007, pal=4
	tsa_entry 0x007, pal=4
	tsa_entry 0x007, pal=4
	tsa_entry 0x008, pal=4, hflip=1
	tsa_entry 0x001, pal=4
	tsa_entry 0x001, pal=4
	tsa_entry 0x001, pal=4
	tsa_entry 0x001, pal=4
	tsa_entry 0x001, pal=4
	tsa_entry 0x001, pal=4
	tsa_entry 0x001, pal=4
	tsa_entry 0x001, pal=4
	tsa_entry 0x001, pal=4
	tsa_entry 0x001, pal=4
	tsa_entry 0x001, pal=4
	tsa_entry 0x001, pal=4
	tsa_entry 0x001, pal=4
	tsa_entry 0x007, pal=4
	tsa_entry 0x007, pal=4
	tsa_entry 0x007, pal=4
	tsa_entry 0x007, pal=4
	tsa_entry 0x00B, pal=4
	tsa_entry 0x001, pal=4
	tsa_entry 0x001, pal=4
	tsa_entry 0x001, pal=4
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
