	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x01B, pal=6
	tsa_entry 0x092, pal=6
	tsa_entry 0x073, pal=6
	tsa_entry 0x035, pal=6
	tsa_entry 0x035, pal=6
	tsa_entry 0x035, pal=6
	tsa_entry 0x167
	tsa_entry 0x167
	tsa_entry 0x167
	tsa_entry 0x001
	tsa_entry 0x002
	tsa_entry 0x167
	tsa_entry 0x003, pal=1
	tsa_entry 0x004
	tsa_entry 0x005, pal=1
	tsa_entry 0x006, pal=1
	tsa_entry 0x007
	tsa_entry 0x008, pal=1
	tsa_entry 0x009, pal=1
	tsa_entry 0x00A, pal=1
	tsa_entry 0x00B, pal=1
	tsa_entry 0x00C, pal=1
	tsa_entry 0x00D, pal=1
	tsa_entry 0x00E, pal=1
	tsa_entry 0x00F, pal=1
	tsa_entry 0x010, pal=1
	tsa_entry 0x011, pal=1
	tsa_entry 0x012, pal=1
	tsa_entry 0x013, pal=2
	tsa_entry 0x014, pal=2
	tsa_entry 0x015
	tsa_entry 0x016, pal=4
	tsa_entry 0x017, pal=2
	tsa_entry 0x018, pal=2
	tsa_entry 0x019, pal=2
	tsa_entry 0x01A, pal=2
	tsa_entry 0x167
	tsa_entry 0x167
	tsa_entry 0x167
	tsa_entry 0x167
	tsa_entry 0x01C
	tsa_entry 0x01D
	tsa_entry 0x01E
	tsa_entry 0x01F
	tsa_entry 0x020
	tsa_entry 0x021
	tsa_entry 0x022, pal=2
	tsa_entry 0x023
	tsa_entry 0x024
	tsa_entry 0x025, pal=1
	tsa_entry 0x026
	tsa_entry 0x027
	tsa_entry 0x028
	tsa_entry 0x029, pal=1
	tsa_entry 0x02A
	tsa_entry 0x02B
	tsa_entry 0x02C
	tsa_entry 0x02D, pal=1
	tsa_entry 0x02E
	tsa_entry 0x02F
	tsa_entry 0x030, pal=3
	tsa_entry 0x031, pal=2
	tsa_entry 0x032, pal=2
	tsa_entry 0x033, pal=2
	tsa_entry 0x033, pal=2
	tsa_entry 0x034, pal=2
	tsa_entry 0x036
	tsa_entry 0x037
	tsa_entry 0x038
	tsa_entry 0x039
	tsa_entry 0x03A
	tsa_entry 0x03B
	tsa_entry 0x03C, pal=3
	tsa_entry 0x03D, pal=3
	tsa_entry 0x03E, pal=3
	tsa_entry 0x03F
	tsa_entry 0x040
	tsa_entry 0x041
	tsa_entry 0x042
	tsa_entry 0x043, pal=2
	tsa_entry 0x044, pal=1
	tsa_entry 0x045
	tsa_entry 0x046, pal=1
	tsa_entry 0x047, pal=1
	tsa_entry 0x048, pal=1
	tsa_entry 0x049, pal=1
	tsa_entry 0x04A
	tsa_entry 0x04B, pal=2
	tsa_entry 0x04C
	tsa_entry 0x04D
	tsa_entry 0x04E, pal=3
	tsa_entry 0x04F, pal=4
	tsa_entry 0x050, pal=2
	tsa_entry 0x051, pal=2
	tsa_entry 0x052, pal=2
	tsa_entry 0x053, pal=2
	tsa_entry 0x055, pal=2
	tsa_entry 0x056
	tsa_entry 0x057
	tsa_entry 0x058
	tsa_entry 0x059
	tsa_entry 0x05A
	tsa_entry 0x05B
	tsa_entry 0x05C, pal=3
	tsa_entry 0x05D, pal=3
	tsa_entry 0x05E
	tsa_entry 0x05F
	tsa_entry 0x060
	tsa_entry 0x061
	tsa_entry 0x062
	tsa_entry 0x063
	tsa_entry 0x064
	tsa_entry 0x065, pal=1
	tsa_entry 0x066, pal=1
	tsa_entry 0x067, pal=1
	tsa_entry 0x068, pal=1
	tsa_entry 0x069
	tsa_entry 0x06A, pal=2
	tsa_entry 0x06B, pal=2
	tsa_entry 0x06C, pal=4
	tsa_entry 0x06D, pal=4
	tsa_entry 0x06E, pal=4
	tsa_entry 0x06F, pal=2
	tsa_entry 0x070, pal=2
	tsa_entry 0x071, pal=2
	tsa_entry 0x072, pal=2
	tsa_entry 0x074, pal=2
	tsa_entry 0x075
	tsa_entry 0x076
	tsa_entry 0x077
	tsa_entry 0x078
	tsa_entry 0x079
	tsa_entry 0x07A
	tsa_entry 0x07B, pal=3
	tsa_entry 0x07C
	tsa_entry 0x07D
	tsa_entry 0x07E
	tsa_entry 0x07F
	tsa_entry 0x080, pal=3
	tsa_entry 0x081
	tsa_entry 0x082
	tsa_entry 0x083
	tsa_entry 0x084
	tsa_entry 0x085
	tsa_entry 0x086, pal=1
	tsa_entry 0x087
	tsa_entry 0x088
	tsa_entry 0x089, pal=4
	tsa_entry 0x08A, pal=4
	tsa_entry 0x08B, pal=5
	tsa_entry 0x08C, pal=5
	tsa_entry 0x08D, pal=5
	tsa_entry 0x08E, pal=2
	tsa_entry 0x08F, pal=2
	tsa_entry 0x090, pal=2
	tsa_entry 0x091, pal=2
	tsa_entry 0x093, pal=2
	tsa_entry 0x094, pal=4
	tsa_entry 0x095
	tsa_entry 0x096
	tsa_entry 0x097, pal=1
	tsa_entry 0x098
	tsa_entry 0x099
	tsa_entry 0x09A, pal=3
	tsa_entry 0x09B, pal=4
	tsa_entry 0x09C, pal=4
	tsa_entry 0x09D, pal=2
	tsa_entry 0x09E, pal=1
	tsa_entry 0x09F
	tsa_entry 0x0A0, pal=4
	tsa_entry 0x0A1, pal=4
	tsa_entry 0x0A2, pal=3
	tsa_entry 0x0A3, pal=1
	tsa_entry 0x0A4, pal=3
	tsa_entry 0x0A5, pal=3
	tsa_entry 0x0A6
	tsa_entry 0x0A7, pal=4
	tsa_entry 0x0A8, pal=4
	tsa_entry 0x0A9, pal=2
	tsa_entry 0x0AA, pal=2
	tsa_entry 0x0AB, pal=5
	tsa_entry 0x0AC, pal=5
	tsa_entry 0x0AD, pal=2
	tsa_entry 0x0AE, pal=2
	tsa_entry 0x0AF, pal=2
	tsa_entry 0x0B0, pal=2
	tsa_entry 0x0B2, pal=4
	tsa_entry 0x0B3, pal=4
	tsa_entry 0x0B4, pal=4
	tsa_entry 0x0B5
	tsa_entry 0x0B6
	tsa_entry 0x0B7
	tsa_entry 0x0B8, pal=2
	tsa_entry 0x0B9, pal=4
	tsa_entry 0x0BA, pal=2
	tsa_entry 0x0BB, pal=2
	tsa_entry 0x0BC, pal=1
	tsa_entry 0x0BD, pal=1
	tsa_entry 0x0BE, pal=4
	tsa_entry 0x0BF, pal=1
	tsa_entry 0x0C0, pal=1
	tsa_entry 0x0C1, pal=1
	tsa_entry 0x0C2, pal=2
	tsa_entry 0x0C3, pal=2
	tsa_entry 0x0C4, pal=1
	tsa_entry 0x0C5, pal=1
	tsa_entry 0x0C6, pal=4
	tsa_entry 0x0C7, pal=2
	tsa_entry 0x0C8, pal=5
	tsa_entry 0x0C9, pal=5
	tsa_entry 0x0CA, pal=2
	tsa_entry 0x0CB, pal=5
	tsa_entry 0x0CC, pal=5
	tsa_entry 0x0CD, pal=2
	tsa_entry 0x0CE, pal=5
	tsa_entry 0x0CF, pal=2
	tsa_entry 0x0D1, pal=4
	tsa_entry 0x0D2, pal=4
	tsa_entry 0x0D3, pal=4
	tsa_entry 0x0D4, pal=4
	tsa_entry 0x0D5
	tsa_entry 0x0D6
	tsa_entry 0x0D7
	tsa_entry 0x0D8, pal=1
	tsa_entry 0x0D9, pal=2
	tsa_entry 0x0DA, pal=1
	tsa_entry 0x0DB, pal=1
	tsa_entry 0x0DC, pal=1
	tsa_entry 0x0DD, pal=4
	tsa_entry 0x0DE, pal=4
	tsa_entry 0x0DF, pal=1
	tsa_entry 0x0E0, pal=1
	tsa_entry 0x0E1, pal=1
	tsa_entry 0x0E2, pal=1
	tsa_entry 0x0E3, pal=1
	tsa_entry 0x0E4, pal=1
	tsa_entry 0x0E5, pal=4
	tsa_entry 0x0E6, pal=2
	tsa_entry 0x0E7, pal=2
	tsa_entry 0x0E8, pal=5
	tsa_entry 0x0E9, pal=5
	tsa_entry 0x0EA, pal=2
	tsa_entry 0x0EB, pal=5
	tsa_entry 0x0EC, pal=5
	tsa_entry 0x0ED, pal=5
	tsa_entry 0x0EE, pal=5
	tsa_entry 0x0EF, pal=4
	tsa_entry 0x0F0, pal=4
	tsa_entry 0x0F1, pal=4
	tsa_entry 0x0F2
	tsa_entry 0x0F3
	tsa_entry 0x0F4
	tsa_entry 0x0F5
	tsa_entry 0x0F6
	tsa_entry 0x0F7, pal=2
	tsa_entry 0x0F8, pal=4
	tsa_entry 0x0F9, pal=2
	tsa_entry 0x0FA, pal=4
	tsa_entry 0x0FB, pal=1
	tsa_entry 0x0FC, pal=4
	tsa_entry 0x0FD, pal=4
	tsa_entry 0x0FE, pal=4
	tsa_entry 0x0FF, pal=4
	tsa_entry 0x100, pal=4
	tsa_entry 0x101, pal=4
	tsa_entry 0x102, pal=4
	tsa_entry 0x103, pal=4
	tsa_entry 0x104, pal=5
	tsa_entry 0x105, pal=2
	tsa_entry 0x106, pal=4
	tsa_entry 0x107, pal=4
	tsa_entry 0x108, pal=4
	tsa_entry 0x109, pal=2
	tsa_entry 0x10A, pal=5
	tsa_entry 0x10B, pal=5
	tsa_entry 0x10C, pal=2
	tsa_entry 0x10D
	tsa_entry 0x10E, pal=3
	tsa_entry 0x10F, pal=3
	tsa_entry 0x110, pal=3
	tsa_entry 0x111
	tsa_entry 0x112
	tsa_entry 0x113, pal=3
	tsa_entry 0x114, pal=3
	tsa_entry 0x115
	tsa_entry 0x116
	tsa_entry 0x117, pal=4
	tsa_entry 0x118, pal=2
	tsa_entry 0x119, pal=4
	tsa_entry 0x11A, pal=4
	tsa_entry 0x11B, pal=4
	tsa_entry 0x11C, pal=4
	tsa_entry 0x11D, pal=4
	tsa_entry 0x11E, pal=2
	tsa_entry 0x11F, pal=4
	tsa_entry 0x120, pal=4
	tsa_entry 0x121, pal=4
	tsa_entry 0x122, pal=1
	tsa_entry 0x123, pal=2
	tsa_entry 0x124, pal=4
	tsa_entry 0x125, pal=4
	tsa_entry 0x126, pal=5
	tsa_entry 0x127, pal=5
	tsa_entry 0x128, pal=5
	tsa_entry 0x129, pal=5
	tsa_entry 0x12A, pal=5
	tsa_entry 0x12B, pal=4
	tsa_entry 0x12C, pal=4
	tsa_entry 0x12D, pal=5
	tsa_entry 0x12E
	tsa_entry 0x12F, pal=3
	tsa_entry 0x130, pal=3
	tsa_entry 0x131, pal=4
	tsa_entry 0x132, pal=3
	tsa_entry 0x133, pal=3
	tsa_entry 0x134, pal=4
	tsa_entry 0x135, pal=2
	tsa_entry 0x136, pal=4
	tsa_entry 0x137
	tsa_entry 0x138, pal=4
	tsa_entry 0x139, pal=4
	tsa_entry 0x13A, pal=4
	tsa_entry 0x13B, pal=4
	tsa_entry 0x13C, pal=4
	tsa_entry 0x13D, pal=4
	tsa_entry 0x13E, pal=4
	tsa_entry 0x13F, pal=4
	tsa_entry 0x140, pal=4
	tsa_entry 0x141, pal=4
	tsa_entry 0x142, pal=4
	tsa_entry 0x143, pal=4
	tsa_entry 0x144, pal=4
	tsa_entry 0x145, pal=4
	tsa_entry 0x146, pal=4
	tsa_entry 0x147, pal=4
	tsa_entry 0x148, pal=4
	tsa_entry 0x149, pal=4
	tsa_entry 0x14A, pal=4
	tsa_entry 0x14B, pal=4
	tsa_entry 0x14C, pal=4
	tsa_entry 0x14D, pal=4
	tsa_entry 0x14E, pal=4
	tsa_entry 0x14F, pal=4
	tsa_entry 0x150, pal=4
	tsa_entry 0x151, pal=4
	tsa_entry 0x152, pal=4
	tsa_entry 0x153, pal=4
	tsa_entry 0x154, pal=4
	tsa_entry 0x155, pal=4
	tsa_entry 0x156, pal=4
	tsa_entry 0x157, pal=4
	tsa_entry 0x158, pal=4
	tsa_entry 0x159, pal=4
	tsa_entry 0x15A, pal=4
	tsa_entry 0x15B, pal=4
	tsa_entry 0x15C, pal=4
	tsa_entry 0x15D, pal=4
	tsa_entry 0x15E, pal=4
	tsa_entry 0x15F, pal=4
	tsa_entry 0x160, pal=4
	tsa_entry 0x161, pal=4
	tsa_entry 0x162, pal=4
	tsa_entry 0x163, pal=4
	tsa_entry 0x164, pal=4
	tsa_entry 0x165, pal=4
	tsa_entry 0x166, pal=4
	tsa_entry 0x0D0, pal=6
	tsa_entry 0x054, pal=6
	tsa_entry 0x0B1, pal=6
	tsa_entry 0x054, pal=6
	tsa_entry 0x0B1, pal=6
	tsa_entry 0x054, pal=6
	tsa_entry 0x0B1, pal=6
	tsa_entry 0x0B1, pal=6
	tsa_entry 0x054, pal=6
	tsa_entry 0x054, pal=6
	tsa_entry 0x0D0, pal=6
	tsa_entry 0x0D0, pal=6
	tsa_entry 0x054, pal=6
	tsa_entry 0x0B1, pal=6
	tsa_entry 0x054, pal=6
	tsa_entry 0x0B1, pal=6
	tsa_entry 0x054, pal=6
	tsa_entry 0x0D0, pal=6
	tsa_entry 0x054, pal=6
	tsa_entry 0x054, pal=6
	tsa_entry 0x0B1, pal=6
	tsa_entry 0x054, pal=6
	tsa_entry 0x054, pal=6
	tsa_entry 0x0B1, pal=6
	tsa_entry 0x0B1, pal=6
	tsa_entry 0x054, pal=6
	tsa_entry 0x054, pal=6
	tsa_entry 0x054, pal=6
	tsa_entry 0x054, pal=6
	tsa_entry 0x0B1, pal=6
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
