	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x002, pal=6
	tsa_entry 0x002, pal=6
	tsa_entry 0x002, pal=6
	tsa_entry 0x002, pal=6
	tsa_entry 0x003, pal=6
	tsa_entry 0x004, pal=6
	tsa_entry 0x005, pal=6
	tsa_entry 0x002, pal=6
	tsa_entry 0x002, pal=6
	tsa_entry 0x003, pal=6
	tsa_entry 0x006, pal=6
	tsa_entry 0x007, pal=6
	tsa_entry 0x001, pal=6
	tsa_entry 0x008, pal=6
	tsa_entry 0x009, pal=6
	tsa_entry 0x00A, pal=6
	tsa_entry 0x001, pal=6
	tsa_entry 0x001, pal=6
	tsa_entry 0x001, pal=6
	tsa_entry 0x001, pal=6
	tsa_entry 0x001, pal=6
	tsa_entry 0x001, pal=6
	tsa_entry 0x001, pal=6
	tsa_entry 0x001, pal=6
	tsa_entry 0x001, pal=6
	tsa_entry 0x001, pal=6
	tsa_entry 0x001, pal=6
	tsa_entry 0x00B, pal=6
	tsa_entry 0x002, pal=6
	tsa_entry 0x002, pal=6
	tsa_entry 0x00E, pal=3
	tsa_entry 0x00F, pal=3
	tsa_entry 0x010
	tsa_entry 0x011, pal=4
	tsa_entry 0x012
	tsa_entry 0x013, pal=3
	tsa_entry 0x014, pal=3
	tsa_entry 0x015
	tsa_entry 0x016, pal=3
	tsa_entry 0x017, pal=3
	tsa_entry 0x018, pal=5
	tsa_entry 0x019, pal=5
	tsa_entry 0x01A, pal=1
	tsa_entry 0x01B, pal=5
	tsa_entry 0x01C, pal=4
	tsa_entry 0x01D, pal=1
	tsa_entry 0x01E, pal=1
	tsa_entry 0x01F, pal=1
	tsa_entry 0x020, pal=1
	tsa_entry 0x021, pal=1
	tsa_entry 0x022, pal=1
	tsa_entry 0x023, pal=1
	tsa_entry 0x024, pal=1
	tsa_entry 0x025, pal=2
	tsa_entry 0x026, pal=2
	tsa_entry 0x027, pal=2
	tsa_entry 0x028, pal=2
	tsa_entry 0x029, pal=2
	tsa_entry 0x02A, pal=3
	tsa_entry 0x02B, pal=2
	tsa_entry 0x02C, pal=3
	tsa_entry 0x02D
	tsa_entry 0x02E, pal=5
	tsa_entry 0x02F, pal=3
	tsa_entry 0x030
	tsa_entry 0x031
	tsa_entry 0x032, pal=3
	tsa_entry 0x033
	tsa_entry 0x034, pal=5
	tsa_entry 0x035, pal=5
	tsa_entry 0x036, pal=5
	tsa_entry 0x037, pal=5
	tsa_entry 0x038, pal=5
	tsa_entry 0x039, pal=5
	tsa_entry 0x03A, pal=5
	tsa_entry 0x03B, pal=1
	tsa_entry 0x03C, pal=1
	tsa_entry 0x03D, pal=1
	tsa_entry 0x03E, pal=1
	tsa_entry 0x03F, pal=1
	tsa_entry 0x040, pal=1
	tsa_entry 0x041, pal=1
	tsa_entry 0x042, pal=2
	tsa_entry 0x043, pal=2
	tsa_entry 0x044, pal=2
	tsa_entry 0x045, pal=2
	tsa_entry 0x046
	tsa_entry 0x047, pal=3
	tsa_entry 0x048, pal=2
	tsa_entry 0x049, pal=2
	tsa_entry 0x04A
	tsa_entry 0x04B, pal=3
	tsa_entry 0x04C
	tsa_entry 0x04D, pal=3
	tsa_entry 0x04E
	tsa_entry 0x04F
	tsa_entry 0x050
	tsa_entry 0x051
	tsa_entry 0x052
	tsa_entry 0x053, pal=5
	tsa_entry 0x054, pal=5
	tsa_entry 0x055, pal=5
	tsa_entry 0x056, pal=5
	tsa_entry 0x057, pal=5
	tsa_entry 0x058, pal=5
	tsa_entry 0x059, pal=5
	tsa_entry 0x05A, pal=1
	tsa_entry 0x05B, pal=2
	tsa_entry 0x05C, pal=2
	tsa_entry 0x05D, pal=1
	tsa_entry 0x05E, pal=4
	tsa_entry 0x05F, pal=4
	tsa_entry 0x060, pal=4
	tsa_entry 0x061, pal=4
	tsa_entry 0x062, pal=4
	tsa_entry 0x063
	tsa_entry 0x064, pal=3
	tsa_entry 0x065, pal=3
	tsa_entry 0x066, pal=2
	tsa_entry 0x067, pal=5
	tsa_entry 0x068, pal=3
	tsa_entry 0x069, pal=3
	tsa_entry 0x06A, pal=3
	tsa_entry 0x06B
	tsa_entry 0x06C
	tsa_entry 0x06D, pal=3
	tsa_entry 0x06E
	tsa_entry 0x06F, pal=3
	tsa_entry 0x070, pal=3
	tsa_entry 0x071, pal=4
	tsa_entry 0x072, pal=4
	tsa_entry 0x073, pal=3
	tsa_entry 0x074, pal=5
	tsa_entry 0x075, pal=3
	tsa_entry 0x076, pal=3
	tsa_entry 0x077, pal=5
	tsa_entry 0x078, pal=5
	tsa_entry 0x079, pal=5
	tsa_entry 0x07A, pal=1
	tsa_entry 0x07B, pal=4
	tsa_entry 0x07C, pal=3
	tsa_entry 0x07D, pal=5
	tsa_entry 0x07E, pal=5
	tsa_entry 0x07F, pal=4
	tsa_entry 0x080, pal=5
	tsa_entry 0x081, pal=3
	tsa_entry 0x082, pal=5
	tsa_entry 0x083, pal=3
	tsa_entry 0x084, pal=5
	tsa_entry 0x085, pal=5
	tsa_entry 0x086, pal=3
	tsa_entry 0x087, pal=3
	tsa_entry 0x088, pal=3
	tsa_entry 0x089, pal=3
	tsa_entry 0x08A, pal=3
	tsa_entry 0x08B, pal=3
	tsa_entry 0x08C, pal=3
	tsa_entry 0x08D
	tsa_entry 0x08E, pal=3
	tsa_entry 0x08F, pal=4
	tsa_entry 0x090, pal=1
	tsa_entry 0x091, pal=4
	tsa_entry 0x092, pal=5
	tsa_entry 0x093, pal=2
	tsa_entry 0x094, pal=2
	tsa_entry 0x095, pal=2
	tsa_entry 0x096, pal=5
	tsa_entry 0x097, pal=5
	tsa_entry 0x098, pal=5
	tsa_entry 0x099, pal=4
	tsa_entry 0x09A, pal=3
	tsa_entry 0x09B, pal=5
	tsa_entry 0x09C, pal=5
	tsa_entry 0x09D, pal=5
	tsa_entry 0x09E, pal=2
	tsa_entry 0x09F, pal=5
	tsa_entry 0x0A0, pal=5
	tsa_entry 0x0A1, pal=5
	tsa_entry 0x0A2, pal=2
	tsa_entry 0x0A3, pal=2
	tsa_entry 0x0A4, pal=3
	tsa_entry 0x0A5, pal=3
	tsa_entry 0x0A6, pal=3
	tsa_entry 0x0A7, pal=3
	tsa_entry 0x0A8, pal=3
	tsa_entry 0x0A9, pal=3
	tsa_entry 0x0AA
	tsa_entry 0x0AB, pal=3
	tsa_entry 0x0AC
	tsa_entry 0x0AD
	tsa_entry 0x0AE
	tsa_entry 0x0AF
	tsa_entry 0x0B0
	tsa_entry 0x0B1, pal=3
	tsa_entry 0x0B2, pal=3
	tsa_entry 0x0B3
	tsa_entry 0x0B4, pal=3
	tsa_entry 0x0B5, pal=3
	tsa_entry 0x0B6, pal=3
	tsa_entry 0x0B7, pal=5
	tsa_entry 0x0B8, pal=5
	tsa_entry 0x0B9, pal=5
	tsa_entry 0x0BA, pal=4
	tsa_entry 0x0BB, pal=5
	tsa_entry 0x0BC, pal=5
	tsa_entry 0x0BD, pal=5
	tsa_entry 0x0BE, pal=5
	tsa_entry 0x0BF, pal=2
	tsa_entry 0x0C0, pal=3
	tsa_entry 0x0C1
	tsa_entry 0x0C2, pal=3
	tsa_entry 0x0C3, pal=3
	tsa_entry 0x0C4, pal=3
	tsa_entry 0x0C5, pal=3
	tsa_entry 0x0C6, pal=3
	tsa_entry 0x0C7, pal=3
	tsa_entry 0x0C8, pal=3
	tsa_entry 0x0C9, pal=3
	tsa_entry 0x0CA, pal=5
	tsa_entry 0x0CB, pal=3
	tsa_entry 0x0CC, pal=4
	tsa_entry 0x0CD, pal=4
	tsa_entry 0x0CE, pal=4
	tsa_entry 0x0CF, pal=5
	tsa_entry 0x0D0, pal=5
	tsa_entry 0x0D1, pal=3
	tsa_entry 0x0D2, pal=4
	tsa_entry 0x0D3, pal=4
	tsa_entry 0x0D4, pal=4
	tsa_entry 0x0D5, pal=5
	tsa_entry 0x0D6
	tsa_entry 0x0D7, pal=5
	tsa_entry 0x0D8, pal=5
	tsa_entry 0x0D9, pal=5
	tsa_entry 0x0DA, pal=5
	tsa_entry 0x0DB, pal=5
	tsa_entry 0x0DC, pal=1
	tsa_entry 0x0DD, pal=5
	tsa_entry 0x0DE, pal=1
	tsa_entry 0x0DF, pal=5
	tsa_entry 0x0E0, pal=3
	tsa_entry 0x0E1
	tsa_entry 0x0E2
	tsa_entry 0x0E3, pal=3
	tsa_entry 0x0E4, pal=3
	tsa_entry 0x0E5, pal=3
	tsa_entry 0x0E6, pal=3
	tsa_entry 0x0E7, pal=3
	tsa_entry 0x0E8, pal=3
	tsa_entry 0x0E9, pal=2
	tsa_entry 0x0EA, pal=3
	tsa_entry 0x0EB, pal=4
	tsa_entry 0x0EC, pal=4
	tsa_entry 0x0ED, pal=5
	tsa_entry 0x0EE, pal=3
	tsa_entry 0x0EF, pal=4
	tsa_entry 0x0F0, pal=4
	tsa_entry 0x0F1, pal=5
	tsa_entry 0x0F2, pal=4
	tsa_entry 0x0F3, pal=5
	tsa_entry 0x0F4, pal=5
	tsa_entry 0x0F5, pal=5
	tsa_entry 0x0F6, pal=4
	tsa_entry 0x0F7, pal=5
	tsa_entry 0x0F8, pal=5
	tsa_entry 0x0F9, pal=5
	tsa_entry 0x0FA, pal=1
	tsa_entry 0x0FB, pal=5
	tsa_entry 0x0FC, pal=5
	tsa_entry 0x0FD, pal=3
	tsa_entry 0x0FE, pal=5
	tsa_entry 0x0FF
	tsa_entry 0x100
	tsa_entry 0x101, pal=3
	tsa_entry 0x102, pal=3
	tsa_entry 0x103, pal=3
	tsa_entry 0x104, pal=3
	tsa_entry 0x105, pal=3
	tsa_entry 0x106, pal=3
	tsa_entry 0x107, pal=3
	tsa_entry 0x108, pal=1
	tsa_entry 0x109, pal=5
	tsa_entry 0x10A, pal=5
	tsa_entry 0x10B, pal=3
	tsa_entry 0x10C, pal=3
	tsa_entry 0x10D, pal=3
	tsa_entry 0x10E, pal=4
	tsa_entry 0x10F, pal=5
	tsa_entry 0x110, pal=5
	tsa_entry 0x111, pal=4
	tsa_entry 0x112, pal=5
	tsa_entry 0x113, pal=5
	tsa_entry 0x114, pal=5
	tsa_entry 0x115, pal=5
	tsa_entry 0x116, pal=5
	tsa_entry 0x117, pal=3
	tsa_entry 0x118, pal=2
	tsa_entry 0x119, pal=4
	tsa_entry 0x11A, pal=5
	tsa_entry 0x11B, pal=5
	tsa_entry 0x11C, pal=5
	tsa_entry 0x11D
	tsa_entry 0x11E, pal=3
	tsa_entry 0x11F, pal=3
	tsa_entry 0x120, pal=3
	tsa_entry 0x121, pal=3
	tsa_entry 0x122, pal=3
	tsa_entry 0x123, pal=5
	tsa_entry 0x124, pal=3
	tsa_entry 0x125, pal=3
	tsa_entry 0x126, pal=5
	tsa_entry 0x127, pal=5
	tsa_entry 0x128, pal=5
	tsa_entry 0x129, pal=5
	tsa_entry 0x12A, pal=5
	tsa_entry 0x12B, pal=5
	tsa_entry 0x12C, pal=4
	tsa_entry 0x12D, pal=5
	tsa_entry 0x12E, pal=5
	tsa_entry 0x12F, pal=5
	tsa_entry 0x130, pal=5
	tsa_entry 0x131, pal=5
	tsa_entry 0x132, pal=4
	tsa_entry 0x133, pal=5
	tsa_entry 0x134, pal=5
	tsa_entry 0x135, pal=5
	tsa_entry 0x136, pal=5
	tsa_entry 0x137, pal=5
	tsa_entry 0x138, pal=4
	tsa_entry 0x139, pal=5
	tsa_entry 0x00D, pal=6
	tsa_entry 0x00D, pal=6
	tsa_entry 0x00D, pal=6
	tsa_entry 0x00D, pal=6
	tsa_entry 0x00D, pal=6
	tsa_entry 0x00D, pal=6
	tsa_entry 0x00D, pal=6
	tsa_entry 0x00D, pal=6
	tsa_entry 0x00D, pal=6
	tsa_entry 0x00D, pal=6
	tsa_entry 0x00D, pal=6
	tsa_entry 0x00D, pal=6
	tsa_entry 0x00D, pal=6
	tsa_entry 0x13A, pal=6
	tsa_entry 0x00C, pal=6
	tsa_entry 0x00C, pal=6
	tsa_entry 0x00C, pal=6
	tsa_entry 0x00C, pal=6
	tsa_entry 0x00C, pal=6
	tsa_entry 0x00C, pal=6
	tsa_entry 0x00C, pal=6
	tsa_entry 0x00C, pal=6
	tsa_entry 0x00C, pal=6
	tsa_entry 0x00C, pal=6
	tsa_entry 0x00C, pal=6
	tsa_entry 0x00C, pal=6
	tsa_entry 0x00C, pal=6
	tsa_entry 0x00C, pal=6
	tsa_entry 0x00C, pal=6
	tsa_entry 0x00C, pal=6
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
	tsa_entry 0x3FF
