"""Committed whole-bundle inventory/report for the ``chapterbundle`` table.

Unlike the per-symbol-table inventories (units/shops/traps/eventscripts/
eventlists), this report covers every table the bundle composes: per-table
record counts and a stable digest (so drift in *any* composed table's
JSON is visible as a one-line diff here too), one overall bundle digest,
and an explicit authored-vs-reference-only classification. The bundle,
its five core tables/support-owner set, and its optional objective/strategy
owners are authored data; character/class/item ``dependencies`` are
reference-only (this slice does not claim to author them).
"""

from __future__ import annotations

import hashlib
import json
import os

from .schema import (
    BUNDLE_TABLE_NAMES,
    SCHEMA_ID,
    _source_path,
    full_dependency_graph,
    source_display_path,
)


def _digest(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _source_display_and_digest(record, source):
    source_path = _source_path(source, record.repository_root)
    with open(source_path, "r", encoding="utf-8") as handle:
        digest = _digest(handle.read())
    return source_display_path(source_path, record.repository_root), digest


def _objective_source_entries(record, source):
    from ..chapterobjectives import schema as objectives_schema

    source_path = _source_path(source, record.repository_root)
    loaded = objectives_schema.load_records(source_path)
    return tuple(
        _source_display_and_digest(record, path)
        for path in loaded.source_paths
    )


def _strategy_source_entries(record, source):
    from ..autoplaystrategies import schema as strategies_schema

    source_path = _source_path(source, record.repository_root)
    loaded = strategies_schema.load_records(source_path)
    return tuple(
        _source_display_and_digest(record, path)
        for path in loaded["source_paths"]
    )


def _aggregate_digest(entries):
    return _digest(json.dumps(sorted(entries), separators=(",", ":")))


def _dependent_source_entries(record):
    entries = []
    for table_name in BUNDLE_TABLE_NAMES:
        table = record.tables_by_name.get(table_name)
        if table is not None:
            entries.append(_source_display_and_digest(record, table.source))
    entries.append(_source_display_and_digest(record, record.support_owners.source))
    if record.chapter_objectives is not None:
        entries.extend(_objective_source_entries(record, record.chapter_objectives.source))
    if record.autoplay_strategies is not None:
        entries.extend(_strategy_source_entries(record, record.autoplay_strategies.source))
    return tuple(sorted(entries))


def _build_single_inventory(records):
    graph = full_dependency_graph()
    lines = []
    lines.append("# Generated-data inventory: chapterbundle\n")
    lines.append("\n")
    lines.append(
        "_Auto-generated by `python3 -m scripts.generated_data generate --table chapterbundle`. "
        "Do not edit by hand -- see docs/generated_data.md._\n"
    )
    lines.append("\n")
    lines.append("- Schema: `{}`\n".format(SCHEMA_ID))
    lines.append("- Chapter: `{}` (`{}`, chapter_settings index {}, mapEventDataId {})\n".format(
        records.chapter.id, records.chapter.internal_name,
        records.chapter.chapter_settings_index, records.chapter.map_event_data_id,
    ))
    source, digest = _source_display_and_digest(records, records.source_path)
    lines.append("- Bundle source: `{}` (sha256: `{}`)\n".format(source, digest))
    lines.append("- Manifest: `{}` (table `{}`)\n".format(records.manifest.symbol, records.manifest.table))
    lines.append("- Full multi-table dependency graph digest (sha256): `{}`\n".format(graph.digest()))
    lines.append("- Full multi-table topological order: {}\n".format(", ".join(graph.topo_order())))
    lines.append("\n")

    lines.append("## Composed tables (authored)\n")
    lines.append("\n")
    lines.append("| Table | Source | Symbol count | Source digest (sha256) |\n")
    lines.append("|---|---|---|---|\n")
    for table_name in BUNDLE_TABLE_NAMES:
        table = records.tables_by_name.get(table_name)
        if table is None:
            continue
        source, digest = _source_display_and_digest(records, table.source)
        lines.append(
            "| {} | {} | {} | {} |\n".format(
                table_name, source, len(table.symbols), digest
            )
        )
    source, digest = _source_display_and_digest(records, records.support_owners.source)
    lines.append(
        "| supportOwners | {} | {} required | {} |\n".format(
            source, len(records.support_owners.required), digest,
        )
    )
    if records.chapter_objectives is not None:
        objectives = records.chapter_objectives
        entries = _objective_source_entries(records, objectives.source)
        lines.append(
            "| chapterobjectives | {} | {} | {} |\n".format(
                ", ".join(source for source, _digest_value in entries),
                len(objectives.symbols),
                _aggregate_digest(entries),
            )
        )
    if records.autoplay_strategies is not None:
        strategies = records.autoplay_strategies
        entries = _strategy_source_entries(records, strategies.source)
        lines.append(
            "| autoplaystrategies | {} | {} | {} |\n".format(
                ", ".join(source for source, _digest_value in entries),
                len(strategies.symbols),
                _aggregate_digest(entries),
            )
        )
    lines.append("\n")

    lines.append("## External references (authored citations into hand source, out of typed-macro scope)\n")
    lines.append("\n")
    lines.append("| Table | Symbol | File |\n")
    lines.append("|---|---|---|\n")
    for ref in sorted(records.external_references, key=lambda r: (r.table, r.symbol)):
        lines.append(
            "| {} | {} | {} |\n".format(
                ref.table,
                ref.symbol,
                source_display_path(ref.file, records.repository_root),
            )
        )
    lines.append("\n")

    lines.append(
        "## Dependencies (**reference-only** -- referenced by Chapter 2's units/shops/support "
        "data, not claimed as authored by this bundle)\n"
    )
    lines.append("\n")
    lines.append("- Characters: {} ({})\n".format(
        len(records.dependencies.characters), ", ".join(records.dependencies.characters)
    ))
    lines.append("- Classes: {} ({})\n".format(
        len(records.dependencies.classes), ", ".join(records.dependencies.classes)
    ))
    lines.append("- Items: {} ({})\n".format(
        len(records.dependencies.items), ", ".join(records.dependencies.items)
    ))
    lines.append("\n")

    bundle_blob = json.dumps(
        {
            "chapter": records.chapter.id,
            "manifest": records.manifest.symbol,
            "tables": {
                name: sorted(records.tables_by_name[name].symbols)
                for name in BUNDLE_TABLE_NAMES if name in records.tables_by_name
            },
            "supportOwners": sorted(records.support_owners.required),
            "chapterObjectives": (
                sorted(records.chapter_objectives.symbols)
                if records.chapter_objectives is not None else []
            ),
            "autoplayStrategies": (
                sorted(records.autoplay_strategies.symbols)
                if records.autoplay_strategies is not None else []
            ),
            "dependencies": {
                "characters": sorted(records.dependencies.characters),
                "classes": sorted(records.dependencies.classes),
                "items": sorted(records.dependencies.items),
            },
        },
        sort_keys=True,
    )
    lines.append("- Bundle digest (sha256): `{}`\n".format(_digest(bundle_blob)))
    return "".join(lines)


def build_inventory(records):
    if len(records) == 1:
        return _build_single_inventory(records[0])

    graph = full_dependency_graph()
    lines = [
        "# Generated-data inventory: chapterbundle\n",
        "\n",
        "_Auto-generated by `python3 -m scripts.generated_data generate --table chapterbundle`. "
        "Do not edit by hand -- see docs/generated_data.md._\n",
        "\n",
        "- Schema: `{}`\n".format(SCHEMA_ID),
        "- Authored chapter bundles: `{}`\n".format(len(records)),
        "- Full multi-table dependency graph digest (sha256): `{}`\n".format(graph.digest()),
        "- Full multi-table topological order: {}\n".format(", ".join(graph.topo_order())),
        "\n",
        "| Chapter | Bundle source | Source digest (sha256) | Dependent sources digest (sha256) | "
        "Manifest | Unit symbols | Objective symbols | Strategy symbols |\n",
        "|---|---|---|---|---|---|---|---|\n",
    ]
    for record in records:
        unit_groups = record.tables_by_name.get("units")
        objectives = record.chapter_objectives
        dependent_entries = _dependent_source_entries(record)
        lines.append(
            "| {} | {} | {} | {} | {} | {} | {} | {} |\n".format(
                record.chapter.id,
                source_display_path(record.source_path, record.repository_root),
                _source_display_and_digest(record, record.source_path)[1],
                _aggregate_digest(dependent_entries),
                record.manifest.symbol,
                ", ".join(sorted(unit_groups.symbols)) if unit_groups is not None else "-",
                ", ".join(sorted(objectives.symbols)) if objectives is not None else "-",
                ", ".join(sorted(record.autoplay_strategies.symbols))
                if record.autoplay_strategies is not None else "-",
            )
        )
    return "".join(lines)
