"""Committed whole-bundle inventory/report for the ``chapterbundle`` table.

Unlike the per-symbol-table inventories (units/shops/traps/eventscripts/
eventlists), this report covers every table the bundle composes: per-table
record counts and a stable digest (so drift in *any* composed table's
JSON is visible as a one-line diff here too), one overall bundle digest,
and an explicit authored-vs-reference-only classification -- the bundle
itself, and the 5 tables/support-owner set it composes, are Chapter 2's
own authored data; the character/class/item ``dependencies`` are called
out as reference-only (this slice does not claim to author them).
"""

from __future__ import annotations

import hashlib
import json
import os

from .schema import BUNDLE_TABLE_NAMES, SCHEMA_ID, full_dependency_graph


def _digest(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _table_digest(source_path):
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
    full_path = source_path if os.path.isabs(source_path) else os.path.join(repo_root, source_path)
    with open(full_path, "r", encoding="utf-8") as handle:
        return _digest(handle.read())


def build_inventory(records):
    graph = full_dependency_graph()
    lines = []
    lines.append("# Generated-data inventory: chapterbundle\n")
    lines.append("\n")
    lines.append(
        "_Auto-generated by `python3 -m scripts.generated_data generate --table chapterbundle`. "
        "Do not edit by hand -- see docs/generated_data.md._\n"
    )
    lines.append("\n")
    lines.append("- Schema: `{}`\n".format(SCHEMA_ID))
    lines.append("- Chapter: `{}` (`{}`, chapter_settings index {}, mapEventDataId {})\n".format(
        records.chapter.id, records.chapter.internal_name,
        records.chapter.chapter_settings_index, records.chapter.map_event_data_id,
    ))
    lines.append("- Manifest: `{}` (table `{}`)\n".format(records.manifest.symbol, records.manifest.table))
    lines.append("- Full multi-table dependency graph digest (sha256): `{}`\n".format(graph.digest()))
    lines.append("- Full multi-table topological order: {}\n".format(", ".join(graph.topo_order())))
    lines.append("\n")

    lines.append("## Composed tables (authored)\n")
    lines.append("\n")
    lines.append("| Table | Source | Symbol count | Source digest (sha256) |\n")
    lines.append("|---|---|---|---|\n")
    for table_name in BUNDLE_TABLE_NAMES:
        table = records.tables_by_name.get(table_name)
        if table is None:
            continue
        lines.append(
            "| {} | {} | {} | {} |\n".format(
                table_name, table.source, len(table.symbols), _table_digest(table.source)
            )
        )
    lines.append(
        "| supportOwners | {} | {} required | {} |\n".format(
            records.support_owners.source, len(records.support_owners.required),
            _table_digest(records.support_owners.source),
        )
    )
    lines.append("\n")

    lines.append("## External references (authored citations into hand source, out of typed-macro scope)\n")
    lines.append("\n")
    lines.append("| Table | Symbol | File |\n")
    lines.append("|---|---|---|\n")
    for ref in sorted(records.external_references, key=lambda r: (r.table, r.symbol)):
        lines.append("| {} | {} | {} |\n".format(ref.table, ref.symbol, ref.file))
    lines.append("\n")

    lines.append(
        "## Dependencies (**reference-only** -- referenced by Chapter 2's units/shops/support "
        "data, not claimed as authored by this bundle)\n"
    )
    lines.append("\n")
    lines.append("- Characters: {} ({})\n".format(
        len(records.dependencies.characters), ", ".join(records.dependencies.characters)
    ))
    lines.append("- Classes: {} ({})\n".format(
        len(records.dependencies.classes), ", ".join(records.dependencies.classes)
    ))
    lines.append("- Items: {} ({})\n".format(
        len(records.dependencies.items), ", ".join(records.dependencies.items)
    ))
    lines.append("\n")

    bundle_blob = json.dumps(
        {
            "chapter": records.chapter.id,
            "manifest": records.manifest.symbol,
            "tables": {
                name: sorted(records.tables_by_name[name].symbols)
                for name in BUNDLE_TABLE_NAMES if name in records.tables_by_name
            },
            "supportOwners": sorted(records.support_owners.required),
            "dependencies": {
                "characters": sorted(records.dependencies.characters),
                "classes": sorted(records.dependencies.classes),
                "items": sorted(records.dependencies.items),
            },
        },
        sort_keys=True,
    )
    lines.append("- Bundle digest (sha256): `{}`\n".format(_digest(bundle_blob)))
    return "".join(lines)
