	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x160, pal=1
	tsa_entry 0x161
	tsa_entry 0x162, pal=1
	tsa_entry 0x163, pal=1
	tsa_entry 0x164, pal=7
	tsa_entry 0x165
	tsa_entry 0x166, pal=7
	tsa_entry 0x167
	tsa_entry 0x168, pal=7
	tsa_entry 0x169, pal=7
	tsa_entry 0x16A, pal=7
	tsa_entry 0x16B, pal=4
	tsa_entry 0x16C
	tsa_entry 0x16D, pal=5
	tsa_entry 0x16E, pal=5
	tsa_entry 0x16F, pal=5
	tsa_entry 0x170, pal=5
	tsa_entry 0x171, pal=5
	tsa_entry 0x172, pal=5
	tsa_entry 0x173, pal=1
	tsa_entry 0x174, pal=5
	tsa_entry 0x175, pal=7
	tsa_entry 0x176, pal=7
	tsa_entry 0x177
	tsa_entry 0x178, pal=1
	tsa_entry 0x179, pal=1
	tsa_entry 0x17A, pal=7
	tsa_entry 0x17B, pal=7
	tsa_entry 0x17C
	tsa_entry 0x17D, pal=7
