	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x3C0, pal=5
	tsa_entry 0x3C1
	tsa_entry 0x3C2, pal=2
	tsa_entry 0x3C3, pal=1
	tsa_entry 0x3C4, pal=7
	tsa_entry 0x3C5, pal=1
	tsa_entry 0x3C6, pal=4
	tsa_entry 0x3C7
	tsa_entry 0x3C8, pal=1
	tsa_entry 0x3C9, pal=7
	tsa_entry 0x3CA, pal=4
	tsa_entry 0x3CB
	tsa_entry 0x3CC
	tsa_entry 0x3CD, pal=4
	tsa_entry 0x3CE, pal=6
	tsa_entry 0x3CF, pal=7
	tsa_entry 0x3D0, pal=7
	tsa_entry 0x3D1
	tsa_entry 0x3D2, pal=3
	tsa_entry 0x3D3
	tsa_entry 0x3D4, pal=7
	tsa_entry 0x3D5
	tsa_entry 0x3D6, pal=1
	tsa_entry 0x3D7, pal=5
	tsa_entry 0x3D8, pal=5
	tsa_entry 0x3D9, pal=5
	tsa_entry 0x3DA, pal=5
	tsa_entry 0x3DB, pal=2
	tsa_entry 0x3DC
	tsa_entry 0x3DD, pal=4
