	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x080, pal=7
	tsa_entry 0x081, pal=4
	tsa_entry 0x082, pal=7
	tsa_entry 0x083, pal=7
	tsa_entry 0x084, pal=4
	tsa_entry 0x085, pal=5
	tsa_entry 0x086, pal=5
	tsa_entry 0x087, pal=5
	tsa_entry 0x088, pal=7
	tsa_entry 0x089, pal=7
	tsa_entry 0x08A, pal=1
	tsa_entry 0x08B, pal=4
	tsa_entry 0x08C, pal=5
	tsa_entry 0x08D
	tsa_entry 0x08E
	tsa_entry 0x08F, pal=7
	tsa_entry 0x090
	tsa_entry 0x091, pal=5
	tsa_entry 0x092
	tsa_entry 0x093
	tsa_entry 0x094, pal=1
	tsa_entry 0x095, pal=4
	tsa_entry 0x096, pal=7
	tsa_entry 0x097, pal=7
	tsa_entry 0x098, pal=4
	tsa_entry 0x099, pal=7
	tsa_entry 0x09A, pal=4
	tsa_entry 0x09B
	tsa_entry 0x09C, pal=4
	tsa_entry 0x09D
