	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x300, pal=1
	tsa_entry 0x301, pal=7
	tsa_entry 0x302, pal=4
	tsa_entry 0x303, pal=1
	tsa_entry 0x304, pal=1
	tsa_entry 0x305, pal=4
	tsa_entry 0x306
	tsa_entry 0x307
	tsa_entry 0x308, pal=4
	tsa_entry 0x309, pal=7
	tsa_entry 0x30A, pal=3
	tsa_entry 0x30B
	tsa_entry 0x30C, pal=7
	tsa_entry 0x30D, pal=7
	tsa_entry 0x30E, pal=7
	tsa_entry 0x30F, pal=2
	tsa_entry 0x310, pal=2
	tsa_entry 0x311, pal=3
	tsa_entry 0x312, pal=3
	tsa_entry 0x313
	tsa_entry 0x314, pal=2
	tsa_entry 0x315, pal=7
	tsa_entry 0x316, pal=5
	tsa_entry 0x317, pal=5
	tsa_entry 0x318, pal=5
	tsa_entry 0x319, pal=5
	tsa_entry 0x31A, pal=5
	tsa_entry 0x31B, pal=5
	tsa_entry 0x31C, pal=5
	tsa_entry 0x31D, pal=5
