	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x0C0, pal=7
	tsa_entry 0x0C1
	tsa_entry 0x0C2, pal=7
	tsa_entry 0x0C3
	tsa_entry 0x0C4, pal=5
	tsa_entry 0x0C5, pal=5
	tsa_entry 0x0C6, pal=1
	tsa_entry 0x0C7, pal=1
	tsa_entry 0x0C8, pal=5
	tsa_entry 0x0C9, pal=5
	tsa_entry 0x0CA, pal=5
	tsa_entry 0x0CB, pal=5
	tsa_entry 0x0CC, pal=5
	tsa_entry 0x0CD, pal=5
	tsa_entry 0x0CE, pal=5
	tsa_entry 0x0CF, pal=7
	tsa_entry 0x0D0, pal=1
	tsa_entry 0x0D1, pal=5
	tsa_entry 0x0D2, pal=5
	tsa_entry 0x0D3, pal=5
	tsa_entry 0x0D4, pal=5
	tsa_entry 0x0D5, pal=5
	tsa_entry 0x0D6, pal=5
	tsa_entry 0x0D7, pal=1
	tsa_entry 0x0D8
	tsa_entry 0x0D9, pal=2
	tsa_entry 0x0DA, pal=4
	tsa_entry 0x0DB, pal=1
	tsa_entry 0x0DC, pal=7
	tsa_entry 0x0DD, pal=7
