	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x000, pal=4
	tsa_entry 0x001
	tsa_entry 0x002
	tsa_entry 0x003, pal=7
	tsa_entry 0x004, pal=7
	tsa_entry 0x005, pal=4
	tsa_entry 0x006, pal=4
	tsa_entry 0x007, pal=7
	tsa_entry 0x008
	tsa_entry 0x009, pal=7
	tsa_entry 0x00A
	tsa_entry 0x00B
	tsa_entry 0x00C, pal=1
	tsa_entry 0x00D, pal=5
	tsa_entry 0x00E, pal=1
	tsa_entry 0x00F, pal=5
	tsa_entry 0x010, pal=5
	tsa_entry 0x011, pal=5
	tsa_entry 0x012, pal=5
	tsa_entry 0x013, pal=7
	tsa_entry 0x014
	tsa_entry 0x015, pal=4
	tsa_entry 0x016, pal=7
	tsa_entry 0x017, pal=4
	tsa_entry 0x018, pal=4
	tsa_entry 0x019, pal=4
	tsa_entry 0x01A, pal=7
	tsa_entry 0x01B, pal=7
	tsa_entry 0x01C, pal=7
	tsa_entry 0x01D, pal=7
