	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x2A0, pal=4
	tsa_entry 0x2A1, pal=4
	tsa_entry 0x2A2, pal=7
	tsa_entry 0x2A3, pal=7
	tsa_entry 0x2A4
	tsa_entry 0x2A5, pal=5
	tsa_entry 0x2A6, pal=1
	tsa_entry 0x2A7, pal=4
	tsa_entry 0x2A8, pal=5
	tsa_entry 0x2A9, pal=5
	tsa_entry 0x2AA, pal=7
	tsa_entry 0x2AB, pal=2
	tsa_entry 0x2AC, pal=5
	tsa_entry 0x2AD, pal=5
	tsa_entry 0x2AE, pal=5
	tsa_entry 0x2AF, pal=5
	tsa_entry 0x2B0, pal=4
	tsa_entry 0x2B1, pal=6
	tsa_entry 0x2B2, pal=6
	tsa_entry 0x2B3
	tsa_entry 0x2B4, pal=7
	tsa_entry 0x2B5, pal=6
	tsa_entry 0x2B6, pal=6
	tsa_entry 0x2B7, pal=6
	tsa_entry 0x2B8, pal=1
	tsa_entry 0x2B9, pal=7
	tsa_entry 0x2BA, pal=7
	tsa_entry 0x2BB, pal=4
	tsa_entry 0x2BC, pal=7
	tsa_entry 0x2BD, pal=7
