	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x220, pal=4
	tsa_entry 0x221, pal=4
	tsa_entry 0x222, pal=5
	tsa_entry 0x223, pal=5
	tsa_entry 0x224, pal=4
	tsa_entry 0x225, pal=5
	tsa_entry 0x226, pal=4
	tsa_entry 0x227, pal=5
	tsa_entry 0x228, pal=1
	tsa_entry 0x229, pal=4
	tsa_entry 0x22A, pal=5
	tsa_entry 0x22B, pal=5
	tsa_entry 0x22C, pal=4
	tsa_entry 0x22D, pal=5
	tsa_entry 0x22E, pal=5
	tsa_entry 0x22F, pal=6
	tsa_entry 0x230, pal=6
	tsa_entry 0x231
	tsa_entry 0x232, pal=2
	tsa_entry 0x233
	tsa_entry 0x234, pal=7
	tsa_entry 0x235, pal=7
	tsa_entry 0x236, pal=7
	tsa_entry 0x237, pal=3
	tsa_entry 0x238, pal=7
	tsa_entry 0x239, pal=7
	tsa_entry 0x23A
	tsa_entry 0x23B, pal=6
	tsa_entry 0x23C, pal=7
	tsa_entry 0x23D, pal=6
