	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x100, pal=7
	tsa_entry 0x101, pal=6
	tsa_entry 0x102, pal=3
	tsa_entry 0x103, pal=6
	tsa_entry 0x104, pal=4
	tsa_entry 0x105, pal=7
	tsa_entry 0x106, pal=4
	tsa_entry 0x107, pal=2
	tsa_entry 0x108, pal=2
	tsa_entry 0x109, pal=6
	tsa_entry 0x10A, pal=6
	tsa_entry 0x10B, pal=5
	tsa_entry 0x10C, pal=5
	tsa_entry 0x10D, pal=5
	tsa_entry 0x10E, pal=5
	tsa_entry 0x10F, pal=5
	tsa_entry 0x110, pal=5
	tsa_entry 0x111, pal=5
	tsa_entry 0x112, pal=5
	tsa_entry 0x113, pal=2
	tsa_entry 0x114, pal=5
	tsa_entry 0x115, pal=2
	tsa_entry 0x116
	tsa_entry 0x117, pal=7
	tsa_entry 0x118
	tsa_entry 0x119
	tsa_entry 0x11A, pal=1
	tsa_entry 0x11B
	tsa_entry 0x11C, pal=4
	tsa_entry 0x11D
