	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x220, pal=1
	tsa_entry 0x221, pal=7
	tsa_entry 0x222, pal=1
	tsa_entry 0x223, pal=1
	tsa_entry 0x224
	tsa_entry 0x225, pal=5
	tsa_entry 0x226, pal=5
	tsa_entry 0x227, pal=5
	tsa_entry 0x228, pal=4
	tsa_entry 0x229, pal=4
	tsa_entry 0x22A, pal=1
	tsa_entry 0x22B, pal=7
	tsa_entry 0x22C, pal=5
	tsa_entry 0x22D, pal=7
	tsa_entry 0x22E, pal=6
	tsa_entry 0x22F, pal=6
	tsa_entry 0x230, pal=6
	tsa_entry 0x231, pal=3
	tsa_entry 0x232, pal=4
	tsa_entry 0x233, pal=1
	tsa_entry 0x234, pal=7
	tsa_entry 0x235, pal=7
	tsa_entry 0x236, pal=7
	tsa_entry 0x237, pal=2
	tsa_entry 0x238, pal=4
	tsa_entry 0x239, pal=4
	tsa_entry 0x23A, pal=2
	tsa_entry 0x23B, pal=7
	tsa_entry 0x23C, pal=7
	tsa_entry 0x23D, pal=2
