	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x380, pal=7
	tsa_entry 0x381, pal=7
	tsa_entry 0x382
	tsa_entry 0x383
	tsa_entry 0x384, pal=5
	tsa_entry 0x385, pal=5
	tsa_entry 0x386, pal=7
	tsa_entry 0x387, pal=7
	tsa_entry 0x388
	tsa_entry 0x389
	tsa_entry 0x38A, pal=5
	tsa_entry 0x38B, pal=4
	tsa_entry 0x38C, pal=5
	tsa_entry 0x38D, pal=5
	tsa_entry 0x38E, pal=5
	tsa_entry 0x38F, pal=5
	tsa_entry 0x390, pal=5
	tsa_entry 0x391, pal=5
	tsa_entry 0x392, pal=1
	tsa_entry 0x393, pal=5
	tsa_entry 0x394, pal=5
	tsa_entry 0x395, pal=2
	tsa_entry 0x396, pal=2
	tsa_entry 0x397, pal=4
	tsa_entry 0x398
	tsa_entry 0x399, pal=2
	tsa_entry 0x39A, pal=4
	tsa_entry 0x39B, pal=7
	tsa_entry 0x39C, pal=7
	tsa_entry 0x39D, pal=4
