	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x2C0
	tsa_entry 0x2C1, pal=4
	tsa_entry 0x2C2, pal=7
	tsa_entry 0x2C3, pal=4
	tsa_entry 0x2C4, pal=4
	tsa_entry 0x2C5
	tsa_entry 0x2C6, pal=5
	tsa_entry 0x2C7, pal=5
	tsa_entry 0x2C8, pal=5
	tsa_entry 0x2C9, pal=5
	tsa_entry 0x2CA, pal=5
	tsa_entry 0x2CB, pal=4
	tsa_entry 0x2CC, pal=1
	tsa_entry 0x2CD, pal=5
	tsa_entry 0x2CE, pal=5
	tsa_entry 0x2CF, pal=4
	tsa_entry 0x2D0, pal=5
	tsa_entry 0x2D1, pal=6
	tsa_entry 0x2D2, pal=1
	tsa_entry 0x2D3, pal=3
	tsa_entry 0x2D4, pal=3
	tsa_entry 0x2D5, pal=7
	tsa_entry 0x2D6, pal=7
	tsa_entry 0x2D7, pal=6
	tsa_entry 0x2D8, pal=3
	tsa_entry 0x2D9, pal=7
	tsa_entry 0x2DA, pal=4
	tsa_entry 0x2DB, pal=4
	tsa_entry 0x2DC, pal=7
	tsa_entry 0x2DD, pal=4
