	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x1E0, pal=5
	tsa_entry 0x1E1, pal=5
	tsa_entry 0x1E2, pal=5
	tsa_entry 0x1E3, pal=5
	tsa_entry 0x1E4, pal=1
	tsa_entry 0x1E5, pal=6
	tsa_entry 0x1E6
	tsa_entry 0x1E7
	tsa_entry 0x1E8, pal=3
	tsa_entry 0x1E9, pal=7
	tsa_entry 0x1EA, pal=7
	tsa_entry 0x1EB
	tsa_entry 0x1EC, pal=5
	tsa_entry 0x1ED, pal=4
	tsa_entry 0x1EE, pal=2
	tsa_entry 0x1EF, pal=4
	tsa_entry 0x1F0, pal=7
	tsa_entry 0x1F1, pal=2
	tsa_entry 0x1F2, pal=7
	tsa_entry 0x1F3
	tsa_entry 0x1F4, pal=2
	tsa_entry 0x1F5
	tsa_entry 0x1F6, pal=3
	tsa_entry 0x1F7, pal=7
	tsa_entry 0x1F8, pal=7
	tsa_entry 0x1F9, pal=3
	tsa_entry 0x1FA, pal=3
	tsa_entry 0x1FB, pal=3
	tsa_entry 0x1FC, pal=3
	tsa_entry 0x1FD, pal=3
