	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x020, pal=1
	tsa_entry 0x021, pal=7
	tsa_entry 0x022, pal=4
	tsa_entry 0x023
	tsa_entry 0x024
	tsa_entry 0x025, pal=7
	tsa_entry 0x026, pal=1
	tsa_entry 0x027
	tsa_entry 0x028, pal=1
	tsa_entry 0x029, pal=7
	tsa_entry 0x02A, pal=1
	tsa_entry 0x02B, pal=2
	tsa_entry 0x02C, pal=7
	tsa_entry 0x02D, pal=2
	tsa_entry 0x02E, pal=1
	tsa_entry 0x02F, pal=6
	tsa_entry 0x030, pal=7
	tsa_entry 0x031
	tsa_entry 0x032, pal=7
	tsa_entry 0x033, pal=1
	tsa_entry 0x034, pal=4
	tsa_entry 0x035, pal=5
	tsa_entry 0x036, pal=4
	tsa_entry 0x037, pal=7
	tsa_entry 0x038, pal=2
	tsa_entry 0x039, pal=3
	tsa_entry 0x03A, pal=3
	tsa_entry 0x03B, pal=7
	tsa_entry 0x03C, pal=7
	tsa_entry 0x03D, pal=7
