	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x060, pal=7
	tsa_entry 0x061, pal=3
	tsa_entry 0x062, pal=3
	tsa_entry 0x063, pal=3
	tsa_entry 0x064, pal=3
	tsa_entry 0x065
	tsa_entry 0x066, pal=7
	tsa_entry 0x067, pal=7
	tsa_entry 0x068, pal=7
	tsa_entry 0x069, pal=1
	tsa_entry 0x06A, pal=2
	tsa_entry 0x06B, pal=2
	tsa_entry 0x06C, pal=1
	tsa_entry 0x06D, pal=7
	tsa_entry 0x06E, pal=4
	tsa_entry 0x06F, pal=4
	tsa_entry 0x070, pal=7
	tsa_entry 0x071
	tsa_entry 0x072, pal=4
	tsa_entry 0x073, pal=7
	tsa_entry 0x074
	tsa_entry 0x075, pal=5
	tsa_entry 0x076, pal=1
	tsa_entry 0x077, pal=6
	tsa_entry 0x078, pal=6
	tsa_entry 0x079, pal=3
	tsa_entry 0x07A, pal=6
	tsa_entry 0x07B
	tsa_entry 0x07C, pal=6
	tsa_entry 0x07D, pal=4
