	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x3A0, pal=1
	tsa_entry 0x3A1, pal=7
	tsa_entry 0x3A2, pal=1
	tsa_entry 0x3A3, pal=1
	tsa_entry 0x3A4, pal=2
	tsa_entry 0x3A5, pal=7
	tsa_entry 0x3A6, pal=7
	tsa_entry 0x3A7, pal=3
	tsa_entry 0x3A8, pal=3
	tsa_entry 0x3A9, pal=6
	tsa_entry 0x3AA, pal=3
	tsa_entry 0x3AB, pal=3
	tsa_entry 0x3AC, pal=3
	tsa_entry 0x3AD, pal=6
	tsa_entry 0x3AE, pal=6
	tsa_entry 0x3AF, pal=2
	tsa_entry 0x3B0
	tsa_entry 0x3B1, pal=4
	tsa_entry 0x3B2, pal=7
	tsa_entry 0x3B3, pal=2
	tsa_entry 0x3B4, pal=5
	tsa_entry 0x3B5, pal=5
	tsa_entry 0x3B6, pal=1
	tsa_entry 0x3B7, pal=7
	tsa_entry 0x3B8, pal=5
	tsa_entry 0x3B9, pal=5
	tsa_entry 0x3BA, pal=4
	tsa_entry 0x3BB, pal=5
	tsa_entry 0x3BC, pal=4
	tsa_entry 0x3BD, pal=5
