	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x1A0, pal=5
	tsa_entry 0x1A1, pal=7
	tsa_entry 0x1A2, pal=5
	tsa_entry 0x1A3, pal=4
	tsa_entry 0x1A4, pal=4
	tsa_entry 0x1A5, pal=5
	tsa_entry 0x1A6, pal=5
	tsa_entry 0x1A7, pal=6
	tsa_entry 0x1A8
	tsa_entry 0x1A9, pal=3
	tsa_entry 0x1AA, pal=6
	tsa_entry 0x1AB
	tsa_entry 0x1AC, pal=7
	tsa_entry 0x1AD, pal=7
	tsa_entry 0x1AE, pal=5
	tsa_entry 0x1AF, pal=6
	tsa_entry 0x1B0, pal=7
	tsa_entry 0x1B1, pal=7
	tsa_entry 0x1B2, pal=7
	tsa_entry 0x1B3, pal=7
	tsa_entry 0x1B4
	tsa_entry 0x1B5, pal=3
	tsa_entry 0x1B6, pal=7
	tsa_entry 0x1B7, pal=7
	tsa_entry 0x1B8, pal=7
	tsa_entry 0x1B9, pal=6
	tsa_entry 0x1BA, pal=2
	tsa_entry 0x1BB, pal=2
	tsa_entry 0x1BC, pal=7
	tsa_entry 0x1BD, pal=7
