	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x340
	tsa_entry 0x341, pal=5
	tsa_entry 0x342, pal=1
	tsa_entry 0x343, pal=4
	tsa_entry 0x344, pal=4
	tsa_entry 0x345, pal=2
	tsa_entry 0x346, pal=2
	tsa_entry 0x347
	tsa_entry 0x348, pal=2
	tsa_entry 0x349
	tsa_entry 0x34A, pal=7
	tsa_entry 0x34B, pal=7
	tsa_entry 0x34C, pal=2
	tsa_entry 0x34D
	tsa_entry 0x34E, pal=7
	tsa_entry 0x34F, pal=2
	tsa_entry 0x350, pal=2
	tsa_entry 0x351, pal=6
	tsa_entry 0x352, pal=7
	tsa_entry 0x353, pal=6
	tsa_entry 0x354, pal=3
	tsa_entry 0x355, pal=1
	tsa_entry 0x356
	tsa_entry 0x357, pal=7
	tsa_entry 0x358, pal=5
	tsa_entry 0x359, pal=5
	tsa_entry 0x35A, pal=5
	tsa_entry 0x35B, pal=1
	tsa_entry 0x35C, pal=5
	tsa_entry 0x35D, pal=5
