	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x0C0, pal=7
	tsa_entry 0x0C1, pal=7
	tsa_entry 0x0C2
	tsa_entry 0x0C3, pal=7
	tsa_entry 0x0C4, pal=7
	tsa_entry 0x0C5, pal=1
	tsa_entry 0x0C6, pal=7
	tsa_entry 0x0C7, pal=7
	tsa_entry 0x0C8, pal=1
	tsa_entry 0x0C9
	tsa_entry 0x0CA
	tsa_entry 0x0CB, pal=1
	tsa_entry 0x0CC, pal=5
	tsa_entry 0x0CD, pal=5
	tsa_entry 0x0CE, pal=1
	tsa_entry 0x0CF, pal=4
	tsa_entry 0x0D0, pal=1
	tsa_entry 0x0D1, pal=4
	tsa_entry 0x0D2, pal=1
	tsa_entry 0x0D3, pal=7
	tsa_entry 0x0D4, pal=4
	tsa_entry 0x0D5, pal=7
	tsa_entry 0x0D6
	tsa_entry 0x0D7
	tsa_entry 0x0D8, pal=3
	tsa_entry 0x0D9, pal=3
	tsa_entry 0x0DA
	tsa_entry 0x0DB
	tsa_entry 0x0DC, pal=3
	tsa_entry 0x0DD
