	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x340, pal=2
	tsa_entry 0x341, pal=7
	tsa_entry 0x342, pal=4
	tsa_entry 0x343
	tsa_entry 0x344, pal=5
	tsa_entry 0x345, pal=2
	tsa_entry 0x346, pal=1
	tsa_entry 0x347, pal=5
	tsa_entry 0x348
	tsa_entry 0x349, pal=4
	tsa_entry 0x34A, pal=5
	tsa_entry 0x34B, pal=7
	tsa_entry 0x34C
	tsa_entry 0x34D, pal=7
	tsa_entry 0x34E, pal=5
	tsa_entry 0x34F, pal=5
	tsa_entry 0x350, pal=1
	tsa_entry 0x351, pal=1
	tsa_entry 0x352
	tsa_entry 0x353, pal=7
	tsa_entry 0x354, pal=7
	tsa_entry 0x355, pal=2
	tsa_entry 0x356, pal=7
	tsa_entry 0x357, pal=7
	tsa_entry 0x358, pal=7
	tsa_entry 0x359
	tsa_entry 0x35A, pal=7
	tsa_entry 0x35B, pal=4
	tsa_entry 0x35C
	tsa_entry 0x35D
