	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x100, pal=2
	tsa_entry 0x101, pal=2
	tsa_entry 0x102, pal=7
	tsa_entry 0x103, pal=7
	tsa_entry 0x104, pal=1
	tsa_entry 0x105, pal=1
	tsa_entry 0x106
	tsa_entry 0x107, pal=1
	tsa_entry 0x108, pal=4
	tsa_entry 0x109, pal=2
	tsa_entry 0x10A
	tsa_entry 0x10B, pal=4
	tsa_entry 0x10C, pal=4
	tsa_entry 0x10D
	tsa_entry 0x10E
	tsa_entry 0x10F, pal=1
	tsa_entry 0x110, pal=5
	tsa_entry 0x111, pal=5
	tsa_entry 0x112, pal=4
	tsa_entry 0x113
	tsa_entry 0x114, pal=1
	tsa_entry 0x115, pal=7
	tsa_entry 0x116, pal=7
	tsa_entry 0x117, pal=6
	tsa_entry 0x118, pal=7
	tsa_entry 0x119, pal=7
	tsa_entry 0x11A, pal=3
	tsa_entry 0x11B, pal=7
	tsa_entry 0x11C, pal=3
	tsa_entry 0x11D, pal=3
