	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x080, pal=7
	tsa_entry 0x081, pal=7
	tsa_entry 0x082, pal=6
	tsa_entry 0x083, pal=4
	tsa_entry 0x084, pal=2
	tsa_entry 0x085, pal=7
	tsa_entry 0x086, pal=4
	tsa_entry 0x087, pal=4
	tsa_entry 0x088, pal=1
	tsa_entry 0x089, pal=5
	tsa_entry 0x08A, pal=4
	tsa_entry 0x08B, pal=7
	tsa_entry 0x08C, pal=7
	tsa_entry 0x08D
	tsa_entry 0x08E, pal=5
	tsa_entry 0x08F, pal=6
	tsa_entry 0x090, pal=4
	tsa_entry 0x091, pal=2
	tsa_entry 0x092, pal=5
	tsa_entry 0x093, pal=5
	tsa_entry 0x094, pal=5
	tsa_entry 0x095, pal=5
	tsa_entry 0x096, pal=5
	tsa_entry 0x097, pal=7
	tsa_entry 0x098
	tsa_entry 0x099, pal=7
	tsa_entry 0x09A, pal=7
	tsa_entry 0x09B, pal=6
	tsa_entry 0x09C, pal=6
	tsa_entry 0x09D, pal=2
