	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x020, pal=7
	tsa_entry 0x021, pal=7
	tsa_entry 0x022, pal=7
	tsa_entry 0x023, pal=7
	tsa_entry 0x024, pal=4
	tsa_entry 0x025
	tsa_entry 0x026, pal=7
	tsa_entry 0x027, pal=7
	tsa_entry 0x028, pal=4
	tsa_entry 0x029, pal=7
	tsa_entry 0x02A, pal=7
	tsa_entry 0x02B, pal=1
	tsa_entry 0x02C
	tsa_entry 0x02D
	tsa_entry 0x02E
	tsa_entry 0x02F, pal=7
	tsa_entry 0x030, pal=1
	tsa_entry 0x031, pal=4
	tsa_entry 0x032, pal=1
	tsa_entry 0x033
	tsa_entry 0x034, pal=4
	tsa_entry 0x035, pal=7
	tsa_entry 0x036, pal=4
	tsa_entry 0x037, pal=7
	tsa_entry 0x038, pal=7
	tsa_entry 0x039, pal=7
	tsa_entry 0x03A, pal=7
	tsa_entry 0x03B, pal=7
	tsa_entry 0x03C, pal=7
	tsa_entry 0x03D, pal=7
