	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x3E0, pal=7
	tsa_entry 0x3E1, pal=5
	tsa_entry 0x3E2
	tsa_entry 0x3E3, pal=7
	tsa_entry 0x3E4
	tsa_entry 0x3E5, pal=7
	tsa_entry 0x3E6, pal=7
	tsa_entry 0x3E7, pal=7
	tsa_entry 0x3E8, pal=1
	tsa_entry 0x3E9, pal=7
	tsa_entry 0x3EA, pal=1
	tsa_entry 0x3EB
	tsa_entry 0x3EC, pal=4
	tsa_entry 0x3ED, pal=2
	tsa_entry 0x3EE, pal=5
	tsa_entry 0x3EF, pal=5
	tsa_entry 0x3F0, pal=5
	tsa_entry 0x3F1, pal=5
	tsa_entry 0x3F2, pal=1
	tsa_entry 0x3F3, pal=1
	tsa_entry 0x3F4, pal=4
	tsa_entry 0x3F5, pal=4
	tsa_entry 0x3F6, pal=7
	tsa_entry 0x3F7, pal=1
	tsa_entry 0x3F8, pal=4
	tsa_entry 0x3F9, pal=7
	tsa_entry 0x3FA, pal=7
	tsa_entry 0x3FB, pal=7
	tsa_entry 0x3FC, pal=4
	tsa_entry 0x3FD, pal=7
