	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x260, pal=7
	tsa_entry 0x261
	tsa_entry 0x262, pal=7
	tsa_entry 0x263
	tsa_entry 0x264, pal=2
	tsa_entry 0x265, pal=4
	tsa_entry 0x266, pal=4
	tsa_entry 0x267, pal=5
	tsa_entry 0x268, pal=5
	tsa_entry 0x269, pal=4
	tsa_entry 0x26A, pal=4
	tsa_entry 0x26B
	tsa_entry 0x26C, pal=4
	tsa_entry 0x26D, pal=5
	tsa_entry 0x26E, pal=5
	tsa_entry 0x26F, pal=5
	tsa_entry 0x270, pal=5
	tsa_entry 0x271, pal=1
	tsa_entry 0x272, pal=6
	tsa_entry 0x273, pal=7
	tsa_entry 0x274, pal=7
	tsa_entry 0x275, pal=6
	tsa_entry 0x276, pal=7
	tsa_entry 0x277
	tsa_entry 0x278, pal=6
	tsa_entry 0x279, pal=2
	tsa_entry 0x27A, pal=7
	tsa_entry 0x27B, pal=7
	tsa_entry 0x27C, pal=1
	tsa_entry 0x27D
