	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x180, pal=2
	tsa_entry 0x181
	tsa_entry 0x182, pal=2
	tsa_entry 0x183, pal=5
	tsa_entry 0x184, pal=7
	tsa_entry 0x185
	tsa_entry 0x186, pal=1
	tsa_entry 0x187, pal=1
	tsa_entry 0x188, pal=7
	tsa_entry 0x189, pal=3
	tsa_entry 0x18A, pal=3
	tsa_entry 0x18B, pal=7
	tsa_entry 0x18C, pal=3
	tsa_entry 0x18D, pal=1
	tsa_entry 0x18E, pal=5
	tsa_entry 0x18F, pal=5
	tsa_entry 0x190, pal=6
	tsa_entry 0x191, pal=6
	tsa_entry 0x192, pal=7
	tsa_entry 0x193, pal=3
	tsa_entry 0x194, pal=3
	tsa_entry 0x195, pal=3
	tsa_entry 0x196, pal=7
	tsa_entry 0x197, pal=3
	tsa_entry 0x198, pal=7
	tsa_entry 0x199, pal=7
	tsa_entry 0x19A, pal=3
	tsa_entry 0x19B, pal=7
	tsa_entry 0x19C
	tsa_entry 0x19D
