	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x320, pal=7
	tsa_entry 0x321
	tsa_entry 0x322, pal=7
	tsa_entry 0x323, pal=4
	tsa_entry 0x324, pal=2
	tsa_entry 0x325, pal=1
	tsa_entry 0x326, pal=4
	tsa_entry 0x327, pal=7
	tsa_entry 0x328, pal=5
	tsa_entry 0x329, pal=4
	tsa_entry 0x32A, pal=7
	tsa_entry 0x32B, pal=7
	tsa_entry 0x32C, pal=7
	tsa_entry 0x32D, pal=2
	tsa_entry 0x32E, pal=4
	tsa_entry 0x32F, pal=5
	tsa_entry 0x330, pal=4
	tsa_entry 0x331, pal=4
	tsa_entry 0x332, pal=6
	tsa_entry 0x333, pal=6
	tsa_entry 0x334, pal=6
	tsa_entry 0x335, pal=7
	tsa_entry 0x336, pal=1
	tsa_entry 0x337, pal=2
	tsa_entry 0x338, pal=6
	tsa_entry 0x339, pal=7
	tsa_entry 0x33A, pal=4
	tsa_entry 0x33B, pal=7
	tsa_entry 0x33C, pal=2
	tsa_entry 0x33D, pal=7
