	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x0E0, pal=7
	tsa_entry 0x0E1, pal=4
	tsa_entry 0x0E2, pal=7
	tsa_entry 0x0E3, pal=5
	tsa_entry 0x0E4, pal=5
	tsa_entry 0x0E5, pal=5
	tsa_entry 0x0E6, pal=4
	tsa_entry 0x0E7, pal=5
	tsa_entry 0x0E8, pal=5
	tsa_entry 0x0E9, pal=4
	tsa_entry 0x0EA, pal=1
	tsa_entry 0x0EB, pal=5
	tsa_entry 0x0EC, pal=2
	tsa_entry 0x0ED, pal=1
	tsa_entry 0x0EE, pal=5
	tsa_entry 0x0EF, pal=7
	tsa_entry 0x0F0, pal=5
	tsa_entry 0x0F1, pal=1
	tsa_entry 0x0F2, pal=7
	tsa_entry 0x0F3
	tsa_entry 0x0F4, pal=5
	tsa_entry 0x0F5, pal=5
	tsa_entry 0x0F6, pal=1
	tsa_entry 0x0F7, pal=4
	tsa_entry 0x0F8, pal=5
	tsa_entry 0x0F9, pal=5
	tsa_entry 0x0FA, pal=2
	tsa_entry 0x0FB, pal=4
	tsa_entry 0x0FC
	tsa_entry 0x0FD, pal=7
