	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x280, pal=7
	tsa_entry 0x281, pal=1
	tsa_entry 0x282, pal=5
	tsa_entry 0x283
	tsa_entry 0x284, pal=2
	tsa_entry 0x285, pal=2
	tsa_entry 0x286, pal=1
	tsa_entry 0x287, pal=1
	tsa_entry 0x288, pal=4
	tsa_entry 0x289, pal=2
	tsa_entry 0x28A, pal=7
	tsa_entry 0x28B, pal=5
	tsa_entry 0x28C, pal=4
	tsa_entry 0x28D, pal=5
	tsa_entry 0x28E, pal=1
	tsa_entry 0x28F, pal=4
	tsa_entry 0x290, pal=2
	tsa_entry 0x291, pal=5
	tsa_entry 0x292, pal=6
	tsa_entry 0x293, pal=2
	tsa_entry 0x294, pal=2
	tsa_entry 0x295, pal=2
	tsa_entry 0x296, pal=6
	tsa_entry 0x297, pal=4
	tsa_entry 0x298, pal=3
	tsa_entry 0x299, pal=3
	tsa_entry 0x29A, pal=3
	tsa_entry 0x29B, pal=3
	tsa_entry 0x29C, pal=3
	tsa_entry 0x29D, pal=3
