	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x1A0, pal=5
	tsa_entry 0x1A1, pal=5
	tsa_entry 0x1A2, pal=5
	tsa_entry 0x1A3, pal=5
	tsa_entry 0x1A4, pal=6
	tsa_entry 0x1A5, pal=3
	tsa_entry 0x1A6, pal=3
	tsa_entry 0x1A7, pal=3
	tsa_entry 0x1A8, pal=3
	tsa_entry 0x1A9, pal=3
	tsa_entry 0x1AA, pal=7
	tsa_entry 0x1AB, pal=5
	tsa_entry 0x1AC, pal=5
	tsa_entry 0x1AD, pal=5
	tsa_entry 0x1AE, pal=5
	tsa_entry 0x1AF, pal=1
	tsa_entry 0x1B0, pal=5
	tsa_entry 0x1B1, pal=2
	tsa_entry 0x1B2, pal=2
	tsa_entry 0x1B3, pal=2
	tsa_entry 0x1B4, pal=6
	tsa_entry 0x1B5, pal=7
	tsa_entry 0x1B6, pal=7
	tsa_entry 0x1B7, pal=6
	tsa_entry 0x1B8, pal=3
	tsa_entry 0x1B9, pal=3
	tsa_entry 0x1BA, pal=3
	tsa_entry 0x1BB, pal=3
	tsa_entry 0x1BC, pal=3
	tsa_entry 0x1BD, pal=7
