	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x040, pal=7
	tsa_entry 0x041, pal=3
	tsa_entry 0x042, pal=3
	tsa_entry 0x043, pal=3
	tsa_entry 0x044
	tsa_entry 0x045, pal=6
	tsa_entry 0x046, pal=7
	tsa_entry 0x047, pal=7
	tsa_entry 0x048
	tsa_entry 0x049, pal=6
	tsa_entry 0x04A, pal=7
	tsa_entry 0x04B
	tsa_entry 0x04C
	tsa_entry 0x04D, pal=4
	tsa_entry 0x04E, pal=4
	tsa_entry 0x04F, pal=4
	tsa_entry 0x050, pal=4
	tsa_entry 0x051, pal=7
	tsa_entry 0x052, pal=4
	tsa_entry 0x053, pal=4
	tsa_entry 0x054
	tsa_entry 0x055
	tsa_entry 0x056, pal=2
	tsa_entry 0x057, pal=6
	tsa_entry 0x058, pal=3
	tsa_entry 0x059, pal=3
	tsa_entry 0x05A, pal=3
	tsa_entry 0x05B, pal=6
	tsa_entry 0x05C, pal=7
	tsa_entry 0x05D, pal=1
