	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x140, pal=7
	tsa_entry 0x141, pal=4
	tsa_entry 0x142, pal=7
	tsa_entry 0x143
	tsa_entry 0x144, pal=7
	tsa_entry 0x145, pal=1
	tsa_entry 0x146, pal=7
	tsa_entry 0x147, pal=4
	tsa_entry 0x148, pal=7
	tsa_entry 0x149, pal=7
	tsa_entry 0x14A, pal=7
	tsa_entry 0x14B, pal=5
	tsa_entry 0x14C, pal=5
	tsa_entry 0x14D, pal=5
	tsa_entry 0x14E, pal=4
	tsa_entry 0x14F, pal=5
	tsa_entry 0x150, pal=5
	tsa_entry 0x151, pal=5
	tsa_entry 0x152, pal=5
	tsa_entry 0x153, pal=4
	tsa_entry 0x154, pal=5
	tsa_entry 0x155, pal=5
	tsa_entry 0x156
	tsa_entry 0x157
	tsa_entry 0x158, pal=2
	tsa_entry 0x159, pal=7
	tsa_entry 0x15A
	tsa_entry 0x15B, pal=2
	tsa_entry 0x15C, pal=7
	tsa_entry 0x15D, pal=6
