	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x1C0, pal=5
	tsa_entry 0x1C1, pal=5
	tsa_entry 0x1C2, pal=4
	tsa_entry 0x1C3, pal=5
	tsa_entry 0x1C4, pal=6
	tsa_entry 0x1C5, pal=3
	tsa_entry 0x1C6, pal=3
	tsa_entry 0x1C7, pal=3
	tsa_entry 0x1C8
	tsa_entry 0x1C9, pal=2
	tsa_entry 0x1CA, pal=2
	tsa_entry 0x1CB
	tsa_entry 0x1CC, pal=4
	tsa_entry 0x1CD, pal=5
	tsa_entry 0x1CE, pal=5
	tsa_entry 0x1CF, pal=5
	tsa_entry 0x1D0, pal=4
	tsa_entry 0x1D1, pal=2
	tsa_entry 0x1D2, pal=3
	tsa_entry 0x1D3, pal=7
	tsa_entry 0x1D4, pal=7
	tsa_entry 0x1D5, pal=7
	tsa_entry 0x1D6, pal=7
	tsa_entry 0x1D7, pal=3
	tsa_entry 0x1D8, pal=7
	tsa_entry 0x1D9, pal=7
	tsa_entry 0x1DA, pal=3
	tsa_entry 0x1DB, pal=3
	tsa_entry 0x1DC, pal=3
	tsa_entry 0x1DD
