	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x120, pal=7
	tsa_entry 0x121, pal=4
	tsa_entry 0x122, pal=1
	tsa_entry 0x123, pal=7
	tsa_entry 0x124, pal=7
	tsa_entry 0x125, pal=1
	tsa_entry 0x126, pal=1
	tsa_entry 0x127, pal=1
	tsa_entry 0x128, pal=7
	tsa_entry 0x129, pal=7
	tsa_entry 0x12A, pal=1
	tsa_entry 0x12B, pal=4
	tsa_entry 0x12C, pal=7
	tsa_entry 0x12D, pal=4
	tsa_entry 0x12E, pal=4
	tsa_entry 0x12F
	tsa_entry 0x130, pal=1
	tsa_entry 0x131, pal=3
	tsa_entry 0x132, pal=1
	tsa_entry 0x133, pal=2
	tsa_entry 0x134, pal=4
	tsa_entry 0x135, pal=2
	tsa_entry 0x136, pal=1
	tsa_entry 0x137, pal=7
	tsa_entry 0x138, pal=1
	tsa_entry 0x139, pal=7
	tsa_entry 0x13A, pal=3
	tsa_entry 0x13B, pal=2
	tsa_entry 0x13C, pal=3
	tsa_entry 0x13D, pal=3
