	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x000, pal=7
	tsa_entry 0x001, pal=7
	tsa_entry 0x002, pal=4
	tsa_entry 0x003, pal=4
	tsa_entry 0x004
	tsa_entry 0x005
	tsa_entry 0x006, pal=7
	tsa_entry 0x007, pal=4
	tsa_entry 0x008, pal=4
	tsa_entry 0x009, pal=4
	tsa_entry 0x00A, pal=4
	tsa_entry 0x00B, pal=4
	tsa_entry 0x00C, pal=7
	tsa_entry 0x00D, pal=4
	tsa_entry 0x00E, pal=7
	tsa_entry 0x00F, pal=4
	tsa_entry 0x010, pal=7
	tsa_entry 0x011, pal=7
	tsa_entry 0x012, pal=3
	tsa_entry 0x013, pal=4
	tsa_entry 0x014, pal=7
	tsa_entry 0x015, pal=7
	tsa_entry 0x016, pal=7
	tsa_entry 0x017
	tsa_entry 0x018, pal=7
	tsa_entry 0x019, pal=7
	tsa_entry 0x01A, pal=4
	tsa_entry 0x01B, pal=7
	tsa_entry 0x01C, pal=7
	tsa_entry 0x01D, pal=4
