	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x200, pal=7
	tsa_entry 0x201, pal=7
	tsa_entry 0x202, pal=7
	tsa_entry 0x203, pal=4
	tsa_entry 0x204, pal=7
	tsa_entry 0x205, pal=5
	tsa_entry 0x206, pal=1
	tsa_entry 0x207, pal=7
	tsa_entry 0x208, pal=5
	tsa_entry 0x209, pal=5
	tsa_entry 0x20A, pal=5
	tsa_entry 0x20B, pal=4
	tsa_entry 0x20C, pal=7
	tsa_entry 0x20D, pal=7
	tsa_entry 0x20E, pal=5
	tsa_entry 0x20F, pal=1
	tsa_entry 0x210, pal=3
	tsa_entry 0x211
	tsa_entry 0x212, pal=3
	tsa_entry 0x213
	tsa_entry 0x214, pal=1
	tsa_entry 0x215, pal=7
	tsa_entry 0x216, pal=7
	tsa_entry 0x217
	tsa_entry 0x218, pal=7
	tsa_entry 0x219, pal=3
	tsa_entry 0x21A
	tsa_entry 0x21B, pal=5
	tsa_entry 0x21C, pal=4
	tsa_entry 0x21D
