	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x0A0, pal=7
	tsa_entry 0x0A1, pal=4
	tsa_entry 0x0A2, pal=4
	tsa_entry 0x0A3, pal=1
	tsa_entry 0x0A4, pal=1
	tsa_entry 0x0A5, pal=5
	tsa_entry 0x0A6, pal=5
	tsa_entry 0x0A7, pal=5
	tsa_entry 0x0A8, pal=4
	tsa_entry 0x0A9, pal=5
	tsa_entry 0x0AA
	tsa_entry 0x0AB, pal=4
	tsa_entry 0x0AC
	tsa_entry 0x0AD, pal=4
	tsa_entry 0x0AE, pal=2
	tsa_entry 0x0AF, pal=4
	tsa_entry 0x0B0, pal=5
	tsa_entry 0x0B1, pal=5
	tsa_entry 0x0B2, pal=5
	tsa_entry 0x0B3, pal=5
	tsa_entry 0x0B4, pal=5
	tsa_entry 0x0B5, pal=4
	tsa_entry 0x0B6, pal=7
	tsa_entry 0x0B7, pal=7
	tsa_entry 0x0B8, pal=1
	tsa_entry 0x0B9, pal=4
	tsa_entry 0x0BA, pal=7
	tsa_entry 0x0BB, pal=7
	tsa_entry 0x0BC, pal=7
	tsa_entry 0x0BD, pal=2
