	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x160, pal=5
	tsa_entry 0x161, pal=4
	tsa_entry 0x162, pal=5
	tsa_entry 0x163, pal=5
	tsa_entry 0x164, pal=5
	tsa_entry 0x165, pal=7
	tsa_entry 0x166, pal=7
	tsa_entry 0x167, pal=4
	tsa_entry 0x168, pal=1
	tsa_entry 0x169, pal=6
	tsa_entry 0x16A, pal=6
	tsa_entry 0x16B, pal=5
	tsa_entry 0x16C, pal=5
	tsa_entry 0x16D, pal=5
	tsa_entry 0x16E, pal=4
	tsa_entry 0x16F, pal=4
	tsa_entry 0x170, pal=5
	tsa_entry 0x171, pal=5
	tsa_entry 0x172, pal=5
	tsa_entry 0x173, pal=2
	tsa_entry 0x174, pal=2
	tsa_entry 0x175, pal=6
	tsa_entry 0x176, pal=6
	tsa_entry 0x177, pal=5
	tsa_entry 0x178, pal=7
	tsa_entry 0x179, pal=3
	tsa_entry 0x17A, pal=3
	tsa_entry 0x17B, pal=7
	tsa_entry 0x17C, pal=2
	tsa_entry 0x17D, pal=6
