	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x040
	tsa_entry 0x041, pal=1
	tsa_entry 0x042, pal=5
	tsa_entry 0x043, pal=1
	tsa_entry 0x044
	tsa_entry 0x045
	tsa_entry 0x046
	tsa_entry 0x047, pal=4
	tsa_entry 0x048, pal=4
	tsa_entry 0x049, pal=4
	tsa_entry 0x04A, pal=7
	tsa_entry 0x04B, pal=1
	tsa_entry 0x04C, pal=2
	tsa_entry 0x04D, pal=7
	tsa_entry 0x04E
	tsa_entry 0x04F, pal=6
	tsa_entry 0x050
	tsa_entry 0x051, pal=7
	tsa_entry 0x052, pal=6
	tsa_entry 0x053, pal=6
	tsa_entry 0x054, pal=5
	tsa_entry 0x055, pal=4
	tsa_entry 0x056, pal=4
	tsa_entry 0x057, pal=2
	tsa_entry 0x058, pal=3
	tsa_entry 0x059, pal=3
	tsa_entry 0x05A, pal=3
	tsa_entry 0x05B
	tsa_entry 0x05C, pal=3
	tsa_entry 0x05D, pal=6
