	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x3A0, pal=4
	tsa_entry 0x3A1, pal=7
	tsa_entry 0x3A2
	tsa_entry 0x3A3, pal=1
	tsa_entry 0x3A4, pal=7
	tsa_entry 0x3A5, pal=4
	tsa_entry 0x3A6, pal=1
	tsa_entry 0x3A7, pal=7
	tsa_entry 0x3A8
	tsa_entry 0x3A9
	tsa_entry 0x3AA, pal=5
	tsa_entry 0x3AB, pal=1
	tsa_entry 0x3AC, pal=5
	tsa_entry 0x3AD, pal=5
	tsa_entry 0x3AE, pal=5
	tsa_entry 0x3AF, pal=5
	tsa_entry 0x3B0, pal=5
	tsa_entry 0x3B1, pal=5
	tsa_entry 0x3B2, pal=5
	tsa_entry 0x3B3, pal=1
	tsa_entry 0x3B4, pal=5
	tsa_entry 0x3B5, pal=7
	tsa_entry 0x3B6
	tsa_entry 0x3B7
	tsa_entry 0x3B8, pal=2
	tsa_entry 0x3B9, pal=7
	tsa_entry 0x3BA, pal=1
	tsa_entry 0x3BB
	tsa_entry 0x3BC, pal=7
	tsa_entry 0x3BD, pal=4
