	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x060
	tsa_entry 0x061, pal=4
	tsa_entry 0x062, pal=7
	tsa_entry 0x063, pal=7
	tsa_entry 0x064, pal=4
	tsa_entry 0x065
	tsa_entry 0x066, pal=4
	tsa_entry 0x067, pal=4
	tsa_entry 0x068
	tsa_entry 0x069, pal=7
	tsa_entry 0x06A
	tsa_entry 0x06B, pal=5
	tsa_entry 0x06C, pal=4
	tsa_entry 0x06D
	tsa_entry 0x06E, pal=1
	tsa_entry 0x06F, pal=5
	tsa_entry 0x070, pal=7
	tsa_entry 0x071
	tsa_entry 0x072, pal=1
	tsa_entry 0x073
	tsa_entry 0x074, pal=7
	tsa_entry 0x075, pal=7
	tsa_entry 0x076, pal=7
	tsa_entry 0x077, pal=4
	tsa_entry 0x078, pal=7
	tsa_entry 0x079, pal=3
	tsa_entry 0x07A, pal=7
	tsa_entry 0x07B, pal=4
	tsa_entry 0x07C, pal=7
	tsa_entry 0x07D, pal=7
