	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x3E0, pal=4
	tsa_entry 0x3E1, pal=1
	tsa_entry 0x3E2, pal=2
	tsa_entry 0x3E3, pal=3
	tsa_entry 0x3E4, pal=3
	tsa_entry 0x3E5, pal=7
	tsa_entry 0x3E6, pal=6
	tsa_entry 0x3E7, pal=3
	tsa_entry 0x3E8, pal=3
	tsa_entry 0x3E9, pal=1
	tsa_entry 0x3EA, pal=7
	tsa_entry 0x3EB, pal=1
	tsa_entry 0x3EC, pal=6
	tsa_entry 0x3ED, pal=4
	tsa_entry 0x3EE, pal=2
	tsa_entry 0x3EF, pal=2
	tsa_entry 0x3F0, pal=7
	tsa_entry 0x3F1
	tsa_entry 0x3F2
	tsa_entry 0x3F3, pal=4
	tsa_entry 0x3F4, pal=1
	tsa_entry 0x3F5, pal=5
	tsa_entry 0x3F6, pal=4
	tsa_entry 0x3F7, pal=4
	tsa_entry 0x3F8, pal=1
	tsa_entry 0x3F9, pal=5
	tsa_entry 0x3FA, pal=1
	tsa_entry 0x3FB, pal=5
	tsa_entry 0x3FC, pal=6
	tsa_entry 0x3FD, pal=6
