	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x360, pal=7
	tsa_entry 0x361, pal=4
	tsa_entry 0x362, pal=4
	tsa_entry 0x363, pal=7
	tsa_entry 0x364, pal=7
	tsa_entry 0x365, pal=6
	tsa_entry 0x366, pal=1
	tsa_entry 0x367, pal=3
	tsa_entry 0x368, pal=7
	tsa_entry 0x369
	tsa_entry 0x36A, pal=2
	tsa_entry 0x36B, pal=5
	tsa_entry 0x36C, pal=2
	tsa_entry 0x36D
	tsa_entry 0x36E, pal=7
	tsa_entry 0x36F, pal=6
	tsa_entry 0x370, pal=2
	tsa_entry 0x371, pal=2
	tsa_entry 0x372, pal=2
	tsa_entry 0x373, pal=6
	tsa_entry 0x374, pal=1
	tsa_entry 0x375, pal=6
	tsa_entry 0x376, pal=4
	tsa_entry 0x377, pal=4
	tsa_entry 0x378, pal=5
	tsa_entry 0x379, pal=5
	tsa_entry 0x37A, pal=5
	tsa_entry 0x37B, pal=5
	tsa_entry 0x37C, pal=5
	tsa_entry 0x37D, pal=5
