	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x240, pal=5
	tsa_entry 0x241
	tsa_entry 0x242, pal=7
	tsa_entry 0x243, pal=1
	tsa_entry 0x244, pal=5
	tsa_entry 0x245, pal=5
	tsa_entry 0x246, pal=5
	tsa_entry 0x247, pal=5
	tsa_entry 0x248, pal=1
	tsa_entry 0x249, pal=5
	tsa_entry 0x24A, pal=5
	tsa_entry 0x24B, pal=5
	tsa_entry 0x24C, pal=1
	tsa_entry 0x24D, pal=7
	tsa_entry 0x24E, pal=4
	tsa_entry 0x24F, pal=5
	tsa_entry 0x250, pal=1
	tsa_entry 0x251, pal=7
	tsa_entry 0x252, pal=1
	tsa_entry 0x253, pal=3
	tsa_entry 0x254, pal=7
	tsa_entry 0x255, pal=7
	tsa_entry 0x256, pal=7
	tsa_entry 0x257, pal=6
	tsa_entry 0x258, pal=1
	tsa_entry 0x259, pal=4
	tsa_entry 0x25A, pal=7
	tsa_entry 0x25B, pal=7
	tsa_entry 0x25C, pal=7
	tsa_entry 0x25D, pal=1
