	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x060, pal=7
	tsa_entry 0x061, pal=4
	tsa_entry 0x062, pal=4
	tsa_entry 0x063
	tsa_entry 0x064, pal=7
	tsa_entry 0x065, pal=7
	tsa_entry 0x066, pal=4
	tsa_entry 0x067, pal=4
	tsa_entry 0x068, pal=4
	tsa_entry 0x069, pal=4
	tsa_entry 0x06A, pal=4
	tsa_entry 0x06B, pal=7
	tsa_entry 0x06C, pal=4
	tsa_entry 0x06D, pal=7
	tsa_entry 0x06E, pal=4
	tsa_entry 0x06F, pal=7
	tsa_entry 0x070, pal=7
	tsa_entry 0x071, pal=4
	tsa_entry 0x072, pal=4
	tsa_entry 0x073, pal=7
	tsa_entry 0x074, pal=4
	tsa_entry 0x075, pal=7
	tsa_entry 0x076, pal=4
	tsa_entry 0x077, pal=7
	tsa_entry 0x078, pal=7
	tsa_entry 0x079, pal=4
	tsa_entry 0x07A, pal=4
	tsa_entry 0x07B, pal=7
	tsa_entry 0x07C, pal=4
	tsa_entry 0x07D, pal=4
