	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x040, pal=4
	tsa_entry 0x041, pal=4
	tsa_entry 0x042, pal=7
	tsa_entry 0x043, pal=4
	tsa_entry 0x044, pal=7
	tsa_entry 0x045, pal=7
	tsa_entry 0x046, pal=7
	tsa_entry 0x047, pal=4
	tsa_entry 0x048, pal=7
	tsa_entry 0x049, pal=4
	tsa_entry 0x04A, pal=7
	tsa_entry 0x04B, pal=7
	tsa_entry 0x04C, pal=7
	tsa_entry 0x04D, pal=7
	tsa_entry 0x04E
	tsa_entry 0x04F, pal=7
	tsa_entry 0x050
	tsa_entry 0x051, pal=4
	tsa_entry 0x052, pal=2
	tsa_entry 0x053, pal=4
	tsa_entry 0x054, pal=4
	tsa_entry 0x055, pal=7
	tsa_entry 0x056, pal=7
	tsa_entry 0x057, pal=7
	tsa_entry 0x058, pal=7
	tsa_entry 0x059, pal=4
	tsa_entry 0x05A, pal=7
	tsa_entry 0x05B, pal=4
	tsa_entry 0x05C
	tsa_entry 0x05D, pal=4
