	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x040, pal=4
	tsa_entry 0x041, pal=4
	tsa_entry 0x042, pal=4
	tsa_entry 0x043, pal=7
	tsa_entry 0x044, pal=7
	tsa_entry 0x045
	tsa_entry 0x046, pal=4
	tsa_entry 0x047, pal=7
	tsa_entry 0x048, pal=7
	tsa_entry 0x049, pal=7
	tsa_entry 0x04A, pal=4
	tsa_entry 0x04B, pal=7
	tsa_entry 0x04C, pal=7
	tsa_entry 0x04D, pal=1
	tsa_entry 0x04E, pal=7
	tsa_entry 0x04F, pal=4
	tsa_entry 0x050, pal=7
	tsa_entry 0x051, pal=4
	tsa_entry 0x052, pal=7
	tsa_entry 0x053, pal=7
	tsa_entry 0x054, pal=7
	tsa_entry 0x055, pal=7
	tsa_entry 0x056
	tsa_entry 0x057, pal=7
	tsa_entry 0x058, pal=7
	tsa_entry 0x059, pal=7
	tsa_entry 0x05A, pal=7
	tsa_entry 0x05B, pal=7
	tsa_entry 0x05C, pal=7
	tsa_entry 0x05D
