	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x2E0, pal=7
	tsa_entry 0x2E1, pal=4
	tsa_entry 0x2E2
	tsa_entry 0x2E3, pal=2
	tsa_entry 0x2E4, pal=7
	tsa_entry 0x2E5, pal=5
	tsa_entry 0x2E6, pal=1
	tsa_entry 0x2E7, pal=5
	tsa_entry 0x2E8, pal=5
	tsa_entry 0x2E9, pal=5
	tsa_entry 0x2EA, pal=4
	tsa_entry 0x2EB, pal=2
	tsa_entry 0x2EC, pal=2
	tsa_entry 0x2ED, pal=5
	tsa_entry 0x2EE, pal=5
	tsa_entry 0x2EF, pal=5
	tsa_entry 0x2F0, pal=5
	tsa_entry 0x2F1, pal=5
	tsa_entry 0x2F2, pal=5
	tsa_entry 0x2F3, pal=3
	tsa_entry 0x2F4, pal=6
	tsa_entry 0x2F5, pal=3
	tsa_entry 0x2F6, pal=6
	tsa_entry 0x2F7, pal=1
	tsa_entry 0x2F8, pal=4
	tsa_entry 0x2F9, pal=7
	tsa_entry 0x2FA, pal=4
	tsa_entry 0x2FB, pal=7
	tsa_entry 0x2FC, pal=5
	tsa_entry 0x2FD
