	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x3C0, pal=7
	tsa_entry 0x3C1, pal=7
	tsa_entry 0x3C2, pal=7
	tsa_entry 0x3C3, pal=7
	tsa_entry 0x3C4, pal=7
	tsa_entry 0x3C5, pal=7
	tsa_entry 0x3C6, pal=7
	tsa_entry 0x3C7, pal=4
	tsa_entry 0x3C8
	tsa_entry 0x3C9, pal=7
	tsa_entry 0x3CA, pal=5
	tsa_entry 0x3CB, pal=5
	tsa_entry 0x3CC, pal=5
	tsa_entry 0x3CD, pal=7
	tsa_entry 0x3CE, pal=5
	tsa_entry 0x3CF, pal=5
	tsa_entry 0x3D0, pal=5
	tsa_entry 0x3D1, pal=5
	tsa_entry 0x3D2, pal=5
	tsa_entry 0x3D3, pal=5
	tsa_entry 0x3D4, pal=5
	tsa_entry 0x3D5, pal=5
	tsa_entry 0x3D6, pal=1
	tsa_entry 0x3D7
	tsa_entry 0x3D8, pal=7
	tsa_entry 0x3D9, pal=4
	tsa_entry 0x3DA, pal=4
	tsa_entry 0x3DB, pal=7
	tsa_entry 0x3DC, pal=4
	tsa_entry 0x3DD, pal=7
