	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x360, pal=1
	tsa_entry 0x361, pal=2
	tsa_entry 0x362
	tsa_entry 0x363, pal=7
	tsa_entry 0x364
	tsa_entry 0x365, pal=2
	tsa_entry 0x366, pal=3
	tsa_entry 0x367, pal=7
	tsa_entry 0x368, pal=7
	tsa_entry 0x369, pal=7
	tsa_entry 0x36A
	tsa_entry 0x36B, pal=1
	tsa_entry 0x36C, pal=7
	tsa_entry 0x36D, pal=7
	tsa_entry 0x36E, pal=5
	tsa_entry 0x36F, pal=5
	tsa_entry 0x370, pal=5
	tsa_entry 0x371, pal=5
	tsa_entry 0x372, pal=5
	tsa_entry 0x373, pal=5
	tsa_entry 0x374, pal=5
	tsa_entry 0x375, pal=5
	tsa_entry 0x376, pal=5
	tsa_entry 0x377, pal=5
	tsa_entry 0x378, pal=5
	tsa_entry 0x379, pal=2
	tsa_entry 0x37A, pal=5
	tsa_entry 0x37B, pal=1
	tsa_entry 0x37C, pal=1
	tsa_entry 0x37D, pal=4
