"""Small committed public inventory/summary for the ``eventscripts`` table.

Metadata-only table -- there is no generated C to summarize alongside, so
this is purely a symbol/owner/kind/header roll call.
"""

from __future__ import annotations

from .schema import SCHEMA_ID, dependency_graph


def build_inventory(records):
    graph = dependency_graph()
    lines = []
    lines.append("# Generated-data inventory: eventscripts\n")
    lines.append("\n")
    lines.append("_Auto-generated by `python3 -m scripts.generated_data generate --table eventscripts`. "
                  "Do not edit by hand -- see docs/generated_data.md._\n")
    lines.append("\n")
    lines.append("- Schema: `{}`\n".format(SCHEMA_ID))
    lines.append("- Script count: {}\n".format(len(records)))
    lines.append("- Dependencies: {}\n".format(", ".join(graph.nodes())))
    lines.append("- Dependency graph digest (sha256): `{}`\n".format(graph.digest()))
    lines.append("\n")
    lines.append("| Owner | Symbol | Kind | Header |\n")
    lines.append("|---|---|---|---|\n")
    for record in sorted(records, key=lambda r: (r.owner, r.symbol)):
        lines.append("| {} | {} | {} | {} |\n".format(record.owner, record.symbol, record.kind, record.header))
    return "".join(lines)
