"""Committed public inventory/summary for the ``characters`` table."""

from __future__ import annotations

from collections import Counter

from .. import character_refs
from ..validators import extract_enum_constants
from .schema import (
    BMITEM_HEADER,
    BMUNIT_HEADER,
    CLASSES_HEADER,
    DESIGNATOR_MAX,
    DESIGNATOR_MIN,
    SCHEMA_ID,
    dependency_graph,
    read_character_attributes,
    read_unit_affinities,
)


def build_inventory(records):
    graph = dependency_graph()
    characters_enum = character_refs.read_character_designators()
    attribute_flags = read_character_attributes(BMUNIT_HEADER)
    weapon_types = extract_enum_constants(BMITEM_HEADER, name_prefix="ITYPE_")
    affinity_values = read_unit_affinities(BMUNIT_HEADER)
    default_classes = extract_enum_constants(CLASSES_HEADER, name_prefix="CLASS_")

    symbolic_count = sum(1 for r in records if not r.is_raw())
    raw_count = sum(1 for r in records if r.is_raw())

    designators = sorted(
        d for d in (r.designator(characters_enum) for r in records) if d is not None
    )
    covered = set(designators)
    full_domain = set(range(DESIGNATOR_MIN, DESIGNATOR_MAX + 1))
    # Designator 256 is the single unreachable padding slot (see the
    # module docstring) -- every other covered designator (1..255) is
    # reachable at runtime by a real `u8` character byte.
    reachable_count = sum(1 for d in covered if d != 256)
    dead_padding_count = sum(1 for d in covered if d == 256)
    missing_count = len(full_domain - covered)

    attribute_counts = Counter()
    for record in records:
        for name in record.attributes:
            attribute_counts[name] += 1

    affinity_counts = Counter(r.affinity for r in records if r.affinity is not None)

    weapon_type_counts = Counter()
    for record in records:
        for itype_name in record.base_ranks:
            weapon_type_counts[itype_name] += 1

    default_class_counts = Counter(r.default_class for r in records)

    support_data_count = sum(1 for r in records if r.support_data is not None)

    lines = []
    lines.append("# Generated-data inventory: characters\n")
    lines.append("\n")
    lines.append("_Auto-generated by `python3 -m scripts.generated_data generate --table characters`. "
                  "Do not edit by hand -- see docs/generated_data.md._\n")
    lines.append("\n")
    lines.append("- Schema: `{}`\n".format(SCHEMA_ID))
    lines.append("- Character record count: {}\n".format(len(records)))
    lines.append("- Symbolic (`CHARACTER_*`) records: {}\n".format(symbolic_count))
    lines.append("- Raw/generic-template records: {}\n".format(raw_count))
    lines.append("- Designator domain: {}..{}\n".format(DESIGNATOR_MIN, DESIGNATOR_MAX))
    lines.append("- Reachable designators (1..255, a real runtime `u8` character byte): {}\n".format(
        reachable_count
    ))
    lines.append("- Unreachable padding slot (designator 256): {}\n".format(dead_padding_count))
    lines.append("- Missing designators (coverage gap): {}\n".format(missing_count))
    lines.append("- Records with `supportData`: {}\n".format(support_data_count))
    lines.append("- Distinct `defaultClass` values referenced: {}\n".format(len(default_class_counts)))
    lines.append("- Dependencies: {}\n".format(", ".join(graph.nodes())))
    lines.append("- Dependency graph digest (sha256): `{}`\n".format(graph.digest()))
    lines.append("\n")

    lines.append("## Attribute (`CA_*`) usage\n")
    lines.append("\n")
    if attribute_counts:
        lines.append("| Attribute | Character count |\n")
        lines.append("|---|---|\n")
        for name in sorted(attribute_counts, key=lambda n: attribute_flags.get(n, 0)):
            lines.append("| {} | {} |\n".format(name, attribute_counts[name]))
    else:
        lines.append("_none_\n")
    lines.append("\n")

    lines.append("## Affinity (`UNIT_AFFIN_*`) usage\n")
    lines.append("\n")
    if affinity_counts:
        lines.append("| Affinity | Character count |\n")
        lines.append("|---|---|\n")
        for name in sorted(affinity_counts, key=lambda n: affinity_values.get(n, 0)):
            lines.append("| {} | {} |\n".format(name, affinity_counts[name]))
    else:
        lines.append("_none_\n")
    lines.append("\n")

    lines.append("## `baseRanks` weapon-type histogram\n")
    lines.append("\n")
    lines.append("| Weapon type | Character count |\n")
    lines.append("|---|---|\n")
    for itype_name in sorted(weapon_type_counts, key=lambda n: weapon_types.get(n, (1 << 30, None))[0]):
        lines.append("| {} | {} |\n".format(itype_name, weapon_type_counts[itype_name]))
    lines.append("\n")

    lines.append("## `defaultClass` usage\n")
    lines.append("\n")
    lines.append("| Class | Character count |\n")
    lines.append("|---|---|\n")
    for class_name in sorted(default_class_counts, key=lambda n: default_classes.get(n, (1 << 30, None))[0]):
        lines.append("| {} | {} |\n".format(class_name, default_class_counts[class_name]))

    return "".join(lines)
