"""Small committed public inventory/summary for the ``traps`` table."""

from __future__ import annotations

from .schema import SCHEMA_ID, dependency_graph


def build_inventory(records):
    graph = dependency_graph()
    total_entries = sum(len(r.entries) for r in records)
    lines = []
    lines.append("# Generated-data inventory: traps\n")
    lines.append("\n")
    lines.append("_Auto-generated by `python3 -m scripts.generated_data generate --table traps`. "
                  "Do not edit by hand -- see docs/generated_data.md._\n")
    lines.append("\n")
    lines.append("- Schema: `{}`\n".format(SCHEMA_ID))
    lines.append("- Trap array count: {}\n".format(len(records)))
    lines.append("- Total trap entry count: {}\n".format(total_entries))
    lines.append("- Dependencies: {}\n".format(", ".join(graph.nodes())))
    lines.append("- Dependency graph digest (sha256): `{}`\n".format(graph.digest()))
    lines.append("\n")
    lines.append("| Trap array symbol | Entry count |\n")
    lines.append("|---|---|\n")
    for record in sorted(records, key=lambda r: r.symbol):
        lines.append("| {} | {} |\n".format(record.symbol, len(record.entries)))
    return "".join(lines)
