	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x31D, pal=1
	tsa_entry 0x260
	tsa_entry 0x261, pal=2
	tsa_entry 0x262, pal=2
	tsa_entry 0x263
	tsa_entry 0x264, pal=2
	tsa_entry 0x265, pal=4
	tsa_entry 0x266, pal=2
	tsa_entry 0x267, pal=2
	tsa_entry 0x268
	tsa_entry 0x269, pal=2
	tsa_entry 0x26A, pal=1
	tsa_entry 0x26B
	tsa_entry 0x26C, pal=1
	tsa_entry 0x26D, pal=4
	tsa_entry 0x26E, pal=3
	tsa_entry 0x26F, pal=2
	tsa_entry 0x270, pal=3
	tsa_entry 0x271, pal=3
	tsa_entry 0x272, pal=3
	tsa_entry 0x273
	tsa_entry 0x274
	tsa_entry 0x275, pal=2
	tsa_entry 0x276, pal=4
	tsa_entry 0x277, pal=5
	tsa_entry 0x278, pal=3
	tsa_entry 0x279, pal=3
	tsa_entry 0x27A
	tsa_entry 0x27B
	tsa_entry 0x27C
	tsa_entry 0x27D, pal=2
	tsa_entry 0x240
	tsa_entry 0x241
	tsa_entry 0x242
	tsa_entry 0x243
	tsa_entry 0x244
	tsa_entry 0x245
	tsa_entry 0x246, pal=2
	tsa_entry 0x247
	tsa_entry 0x248
	tsa_entry 0x249
	tsa_entry 0x24A
	tsa_entry 0x24B
	tsa_entry 0x24C, pal=1
	tsa_entry 0x24D, pal=4
	tsa_entry 0x24E, pal=4
	tsa_entry 0x24F, pal=5
	tsa_entry 0x250, pal=4
	tsa_entry 0x251, pal=4
	tsa_entry 0x252, pal=4
	tsa_entry 0x253, pal=4
	tsa_entry 0x254, pal=4
	tsa_entry 0x255, pal=4
	tsa_entry 0x256, pal=5
	tsa_entry 0x257, pal=5
	tsa_entry 0x258, pal=5
	tsa_entry 0x259, pal=5
	tsa_entry 0x25A, pal=3
	tsa_entry 0x25B
	tsa_entry 0x25C
	tsa_entry 0x25D, pal=2
	tsa_entry 0x220
	tsa_entry 0x221
	tsa_entry 0x222
	tsa_entry 0x223
	tsa_entry 0x224
	tsa_entry 0x225
	tsa_entry 0x226, pal=1
	tsa_entry 0x227
	tsa_entry 0x228
	tsa_entry 0x229
	tsa_entry 0x22A
	tsa_entry 0x22B
	tsa_entry 0x22C, pal=1
	tsa_entry 0x22D, pal=4
	tsa_entry 0x22E, pal=4
	tsa_entry 0x22F, pal=4
	tsa_entry 0x230, pal=4
	tsa_entry 0x231, pal=4
	tsa_entry 0x232, pal=4
	tsa_entry 0x233, pal=4
	tsa_entry 0x234, pal=2
	tsa_entry 0x235, pal=4
	tsa_entry 0x236, pal=5
	tsa_entry 0x237, pal=5
	tsa_entry 0x238, pal=4
	tsa_entry 0x239, pal=5
	tsa_entry 0x23A, pal=3
	tsa_entry 0x23B, pal=1
	tsa_entry 0x23C, pal=2
	tsa_entry 0x23D, pal=2
	tsa_entry 0x200
	tsa_entry 0x201
	tsa_entry 0x202, pal=1
	tsa_entry 0x203, pal=1
	tsa_entry 0x204, pal=3
	tsa_entry 0x205, pal=1
	tsa_entry 0x206, pal=4
	tsa_entry 0x207, pal=1
	tsa_entry 0x208
	tsa_entry 0x209
	tsa_entry 0x20A
	tsa_entry 0x20B
	tsa_entry 0x20C, pal=1
	tsa_entry 0x20D, pal=1
	tsa_entry 0x20E, pal=4
	tsa_entry 0x20F, pal=4
	tsa_entry 0x210, pal=3
	tsa_entry 0x211, pal=3
	tsa_entry 0x212, pal=3
	tsa_entry 0x213, pal=1
	tsa_entry 0x214, pal=2
	tsa_entry 0x215, pal=4
	tsa_entry 0x216, pal=5
	tsa_entry 0x217, pal=5
	tsa_entry 0x218, pal=5
	tsa_entry 0x219, pal=4
	tsa_entry 0x21A
	tsa_entry 0x21B
	tsa_entry 0x21C, pal=2
	tsa_entry 0x21D, pal=2
	tsa_entry 0x1E0
	tsa_entry 0x1E1
	tsa_entry 0x1E2, pal=1
	tsa_entry 0x1E3, pal=3
	tsa_entry 0x1E4, pal=3
	tsa_entry 0x1E5, pal=3
	tsa_entry 0x1E6, pal=3
	tsa_entry 0x1E7, pal=3
	tsa_entry 0x1E8, pal=1
	tsa_entry 0x1E9
	tsa_entry 0x1EA
	tsa_entry 0x1EB, pal=2
	tsa_entry 0x1EC, pal=4
	tsa_entry 0x1ED, pal=4
	tsa_entry 0x1EE, pal=4
	tsa_entry 0x1EF, pal=2
	tsa_entry 0x1F0, pal=4
	tsa_entry 0x1F1, pal=4
	tsa_entry 0x1F2, pal=4
	tsa_entry 0x1F3, pal=4
	tsa_entry 0x1F4, pal=4
	tsa_entry 0x1F5, pal=4
	tsa_entry 0x1F6, pal=4
	tsa_entry 0x1F7, pal=5
	tsa_entry 0x1F8, pal=5
	tsa_entry 0x1F9, pal=2
	tsa_entry 0x1FA
	tsa_entry 0x1FB
	tsa_entry 0x1FC, pal=2
	tsa_entry 0x1FD, pal=2
	tsa_entry 0x1C0
	tsa_entry 0x1C1
	tsa_entry 0x1C2, pal=3
	tsa_entry 0x1C3, pal=3
	tsa_entry 0x1C4, pal=3
	tsa_entry 0x1C5, pal=3
	tsa_entry 0x1C6, pal=3
	tsa_entry 0x1C7, pal=3
	tsa_entry 0x1C8, pal=1
	tsa_entry 0x1C9
	tsa_entry 0x1CA, pal=4
	tsa_entry 0x1CB, pal=4
	tsa_entry 0x1CC, pal=4
	tsa_entry 0x1CD, pal=4
	tsa_entry 0x1CE, pal=4
	tsa_entry 0x1CF, pal=4
	tsa_entry 0x1D0, pal=4
	tsa_entry 0x1D1, pal=4
	tsa_entry 0x1D2, pal=4
	tsa_entry 0x1D3, pal=4
	tsa_entry 0x1D4, pal=4
	tsa_entry 0x1D5, pal=4
	tsa_entry 0x1D6, pal=3
	tsa_entry 0x1D7, pal=4
	tsa_entry 0x1D8, pal=5
	tsa_entry 0x1D9, pal=4
	tsa_entry 0x1DA
	tsa_entry 0x1DB, pal=2
	tsa_entry 0x1DC, pal=2
	tsa_entry 0x1DD, pal=2
	tsa_entry 0x1A0
	tsa_entry 0x1A1, pal=3
	tsa_entry 0x1A2, pal=1
	tsa_entry 0x1A3, pal=3
	tsa_entry 0x1A4, pal=3
	tsa_entry 0x1A5, pal=3
	tsa_entry 0x1A6, pal=3
	tsa_entry 0x1A7, pal=3
	tsa_entry 0x1A8, pal=1
	tsa_entry 0x1A9, pal=4
	tsa_entry 0x1AA, pal=4
	tsa_entry 0x1AB, pal=2
	tsa_entry 0x1AC
	tsa_entry 0x1AD, pal=1
	tsa_entry 0x1AE, pal=1
	tsa_entry 0x1AF, pal=3
	tsa_entry 0x1B0, pal=4
	tsa_entry 0x1B1, pal=1
	tsa_entry 0x1B2, pal=1
	tsa_entry 0x1B3, pal=2
	tsa_entry 0x1B4, pal=1
	tsa_entry 0x1B5, pal=5
	tsa_entry 0x1B6, pal=2
	tsa_entry 0x1B7, pal=1
	tsa_entry 0x1B8
	tsa_entry 0x1B9, pal=2
	tsa_entry 0x1BA, pal=2
	tsa_entry 0x1BB, pal=2
	tsa_entry 0x1BC, pal=2
	tsa_entry 0x1BD, pal=2
	tsa_entry 0x180
	tsa_entry 0x181, pal=3
	tsa_entry 0x182, pal=1
	tsa_entry 0x183, pal=3
	tsa_entry 0x184, pal=3
	tsa_entry 0x185, pal=3
	tsa_entry 0x186, pal=3
	tsa_entry 0x187, pal=3
	tsa_entry 0x188, pal=1
	tsa_entry 0x189, pal=1
	tsa_entry 0x18A
	tsa_entry 0x18B
	tsa_entry 0x18C
	tsa_entry 0x18D, pal=3
	tsa_entry 0x18E, pal=3
	tsa_entry 0x18F, pal=1
	tsa_entry 0x190, pal=3
	tsa_entry 0x191, pal=1
	tsa_entry 0x192, pal=3
	tsa_entry 0x193, pal=3
	tsa_entry 0x194, pal=3
	tsa_entry 0x195, pal=2
	tsa_entry 0x196, pal=4
	tsa_entry 0x197, pal=5
	tsa_entry 0x198, pal=5
	tsa_entry 0x199, pal=4
	tsa_entry 0x19A, pal=2
	tsa_entry 0x19B, pal=2
	tsa_entry 0x19C, pal=2
	tsa_entry 0x19D
	tsa_entry 0x160
	tsa_entry 0x161
	tsa_entry 0x162
	tsa_entry 0x163, pal=3
	tsa_entry 0x164, pal=3
	tsa_entry 0x165, pal=3
	tsa_entry 0x166, pal=3
	tsa_entry 0x167, pal=3
	tsa_entry 0x168
	tsa_entry 0x169
	tsa_entry 0x16A
	tsa_entry 0x16B
	tsa_entry 0x16C
	tsa_entry 0x16D, pal=3
	tsa_entry 0x16E, pal=3
	tsa_entry 0x16F, pal=3
	tsa_entry 0x170, pal=3
	tsa_entry 0x171, pal=1
	tsa_entry 0x172, pal=3
	tsa_entry 0x173, pal=1
	tsa_entry 0x174, pal=1
	tsa_entry 0x175, pal=3
	tsa_entry 0x176, pal=5
	tsa_entry 0x177, pal=5
	tsa_entry 0x178, pal=5
	tsa_entry 0x179, pal=5
	tsa_entry 0x17A, pal=2
	tsa_entry 0x17B, pal=2
	tsa_entry 0x17C, pal=2
	tsa_entry 0x17D
	tsa_entry 0x140
	tsa_entry 0x141
	tsa_entry 0x142
	tsa_entry 0x143, pal=3
	tsa_entry 0x144, pal=3
	tsa_entry 0x145, pal=3
	tsa_entry 0x146, pal=3
	tsa_entry 0x147
	tsa_entry 0x148, pal=2
	tsa_entry 0x149
	tsa_entry 0x14A
	tsa_entry 0x14B
	tsa_entry 0x14C
	tsa_entry 0x14D, pal=1
	tsa_entry 0x14E, pal=1
	tsa_entry 0x14F, pal=3
	tsa_entry 0x150, pal=3
	tsa_entry 0x151, pal=3
	tsa_entry 0x152, pal=3
	tsa_entry 0x153, pal=3
	tsa_entry 0x154, pal=1
	tsa_entry 0x155, pal=2
	tsa_entry 0x156, pal=3
	tsa_entry 0x157, pal=2
	tsa_entry 0x158, pal=4
	tsa_entry 0x159
	tsa_entry 0x15A, pal=2
	tsa_entry 0x15B
	tsa_entry 0x15C
	tsa_entry 0x15D
	tsa_entry 0x120
	tsa_entry 0x121
	tsa_entry 0x122
	tsa_entry 0x123
	tsa_entry 0x124
	tsa_entry 0x125
	tsa_entry 0x126
	tsa_entry 0x127
	tsa_entry 0x128
	tsa_entry 0x129
	tsa_entry 0x12A
	tsa_entry 0x12B
	tsa_entry 0x12C, pal=1
	tsa_entry 0x12D, pal=3
	tsa_entry 0x12E, pal=1
	tsa_entry 0x12F, pal=3
	tsa_entry 0x130, pal=1
	tsa_entry 0x131, pal=3
	tsa_entry 0x132, pal=3
	tsa_entry 0x133, pal=3
	tsa_entry 0x134, pal=2
	tsa_entry 0x135, pal=2
	tsa_entry 0x136, pal=1
	tsa_entry 0x137, pal=2
	tsa_entry 0x138, pal=2
	tsa_entry 0x139, pal=4
	tsa_entry 0x13A, pal=2
	tsa_entry 0x13B
	tsa_entry 0x13C
	tsa_entry 0x13D
	tsa_entry 0x100
	tsa_entry 0x101
	tsa_entry 0x102
	tsa_entry 0x103
	tsa_entry 0x104
	tsa_entry 0x105
	tsa_entry 0x106
	tsa_entry 0x107
	tsa_entry 0x108
	tsa_entry 0x109
	tsa_entry 0x10A
	tsa_entry 0x10B
	tsa_entry 0x10C, pal=1
	tsa_entry 0x10D, pal=4
	tsa_entry 0x10E, pal=3
	tsa_entry 0x10F, pal=1
	tsa_entry 0x110, pal=1
	tsa_entry 0x111, pal=3
	tsa_entry 0x112, pal=1
	tsa_entry 0x113, pal=2
	tsa_entry 0x114, pal=4
	tsa_entry 0x115, pal=3
	tsa_entry 0x116, pal=2
	tsa_entry 0x117, pal=2
	tsa_entry 0x118, pal=2
	tsa_entry 0x119, pal=2
	tsa_entry 0x11A, pal=2
	tsa_entry 0x11B, pal=2
	tsa_entry 0x11C
	tsa_entry 0x11D
	tsa_entry 0x0E0
	tsa_entry 0x0E1
	tsa_entry 0x0E2
	tsa_entry 0x0E3
	tsa_entry 0x0E4
	tsa_entry 0x0E5
	tsa_entry 0x0E6
	tsa_entry 0x0E7
	tsa_entry 0x0E8
	tsa_entry 0x0E9
	tsa_entry 0x0EA
	tsa_entry 0x0EB
	tsa_entry 0x0EC, pal=1
	tsa_entry 0x0ED, pal=4
	tsa_entry 0x0EE, pal=4
	tsa_entry 0x0EF, pal=1
	tsa_entry 0x0F0
	tsa_entry 0x0F1, pal=2
	tsa_entry 0x0F2, pal=2
	tsa_entry 0x0F3, pal=2
	tsa_entry 0x0F4, pal=3
	tsa_entry 0x0F5, pal=2
	tsa_entry 0x0F6, pal=2
	tsa_entry 0x0F7, pal=3
	tsa_entry 0x0F8, pal=3
	tsa_entry 0x0F9
	tsa_entry 0x0FA, pal=2
	tsa_entry 0x0FB, pal=2
	tsa_entry 0x0FC
	tsa_entry 0x0FD
	tsa_entry 0x0C0
	tsa_entry 0x0C1
	tsa_entry 0x0C2
	tsa_entry 0x0C3
	tsa_entry 0x0C4
	tsa_entry 0x0C5
	tsa_entry 0x0C6
	tsa_entry 0x0C7
	tsa_entry 0x0C8
	tsa_entry 0x0C9
	tsa_entry 0x0CA
	tsa_entry 0x0CB
	tsa_entry 0x0CC, pal=1
	tsa_entry 0x0CD, pal=4
	tsa_entry 0x0CE, pal=3
	tsa_entry 0x0CF, pal=1
	tsa_entry 0x0D0
	tsa_entry 0x0D1, pal=2
	tsa_entry 0x0D2, pal=2
	tsa_entry 0x0D3, pal=1
	tsa_entry 0x0D4, pal=2
	tsa_entry 0x0D5, pal=2
	tsa_entry 0x0D6, pal=2
	tsa_entry 0x0D7, pal=3
	tsa_entry 0x0D8, pal=2
	tsa_entry 0x0D9, pal=2
	tsa_entry 0x0DA, pal=1
	tsa_entry 0x0DB
	tsa_entry 0x0DC
	tsa_entry 0x0DD
	tsa_entry 0x0A0
	tsa_entry 0x0A1
	tsa_entry 0x0A2
	tsa_entry 0x0A3
	tsa_entry 0x0A4
	tsa_entry 0x0A5
	tsa_entry 0x0A6
	tsa_entry 0x0A7
	tsa_entry 0x0A8
	tsa_entry 0x0A9
	tsa_entry 0x0AA
	tsa_entry 0x0AB
	tsa_entry 0x0AC, pal=1
	tsa_entry 0x0AD, pal=4
	tsa_entry 0x0AE, pal=3
	tsa_entry 0x0AF, pal=1
	tsa_entry 0x0B0, pal=1
	tsa_entry 0x0B1, pal=3
	tsa_entry 0x0B2, pal=3
	tsa_entry 0x0B3
	tsa_entry 0x0B4, pal=2
	tsa_entry 0x0B5
	tsa_entry 0x0B6, pal=2
	tsa_entry 0x0B7, pal=2
	tsa_entry 0x0B8, pal=2
	tsa_entry 0x0B9
	tsa_entry 0x0BA
	tsa_entry 0x0BB
	tsa_entry 0x0BC
	tsa_entry 0x0BD, pal=2
	tsa_entry 0x080
	tsa_entry 0x081
	tsa_entry 0x082
	tsa_entry 0x083
	tsa_entry 0x084
	tsa_entry 0x085
	tsa_entry 0x086
	tsa_entry 0x087
	tsa_entry 0x088
	tsa_entry 0x089
	tsa_entry 0x08A
	tsa_entry 0x08B
	tsa_entry 0x08C, pal=1
	tsa_entry 0x08D, pal=4
	tsa_entry 0x08E, pal=1
	tsa_entry 0x08F, pal=1
	tsa_entry 0x090, pal=3
	tsa_entry 0x091, pal=3
	tsa_entry 0x092, pal=1
	tsa_entry 0x093
	tsa_entry 0x094, pal=2
	tsa_entry 0x095
	tsa_entry 0x096
	tsa_entry 0x097
	tsa_entry 0x098, pal=2
	tsa_entry 0x099, pal=2
	tsa_entry 0x09A
	tsa_entry 0x09B
	tsa_entry 0x09C
	tsa_entry 0x09D, pal=2
	tsa_entry 0x060, pal=2
	tsa_entry 0x061
	tsa_entry 0x062
	tsa_entry 0x063
	tsa_entry 0x064
	tsa_entry 0x065
	tsa_entry 0x066
	tsa_entry 0x067
	tsa_entry 0x068
	tsa_entry 0x069
	tsa_entry 0x06A
	tsa_entry 0x06B
	tsa_entry 0x06C, pal=1
	tsa_entry 0x06D, pal=4
	tsa_entry 0x06E, pal=1
	tsa_entry 0x06F, pal=1
	tsa_entry 0x070, pal=1
	tsa_entry 0x071, pal=1
	tsa_entry 0x072, pal=1
	tsa_entry 0x073
	tsa_entry 0x074, pal=2
	tsa_entry 0x075, pal=2
	tsa_entry 0x076
	tsa_entry 0x077, pal=2
	tsa_entry 0x078, pal=2
	tsa_entry 0x079, pal=2
	tsa_entry 0x07A, pal=2
	tsa_entry 0x07B
	tsa_entry 0x07C
	tsa_entry 0x07D, pal=2
	tsa_entry 0x040, pal=2
	tsa_entry 0x041
	tsa_entry 0x042
	tsa_entry 0x043
	tsa_entry 0x044
	tsa_entry 0x045
	tsa_entry 0x046, pal=1
	tsa_entry 0x047
	tsa_entry 0x048
	tsa_entry 0x049
	tsa_entry 0x04A
	tsa_entry 0x04B
	tsa_entry 0x04C, pal=1
	tsa_entry 0x04D, pal=1
	tsa_entry 0x04E, pal=1
	tsa_entry 0x04F, pal=1
	tsa_entry 0x050
	tsa_entry 0x051
	tsa_entry 0x052, pal=2
	tsa_entry 0x053, pal=3
	tsa_entry 0x054, pal=2
	tsa_entry 0x055, pal=2
	tsa_entry 0x056
	tsa_entry 0x057
	tsa_entry 0x058, pal=2
	tsa_entry 0x059
	tsa_entry 0x05A
	tsa_entry 0x05B
	tsa_entry 0x05C
	tsa_entry 0x05D, pal=2
	tsa_entry 0x020, pal=2
	tsa_entry 0x021
	tsa_entry 0x022
	tsa_entry 0x023
	tsa_entry 0x024
	tsa_entry 0x025
	tsa_entry 0x026
	tsa_entry 0x027
	tsa_entry 0x028
	tsa_entry 0x029
	tsa_entry 0x02A
	tsa_entry 0x02B
	tsa_entry 0x02C, pal=1
	tsa_entry 0x02D, pal=1
	tsa_entry 0x02E, pal=4
	tsa_entry 0x02F, pal=3
	tsa_entry 0x030
	tsa_entry 0x031
	tsa_entry 0x032
	tsa_entry 0x033
	tsa_entry 0x034, pal=2
	tsa_entry 0x035
	tsa_entry 0x036
	tsa_entry 0x037, pal=2
	tsa_entry 0x038
	tsa_entry 0x039
	tsa_entry 0x03A
	tsa_entry 0x03B
	tsa_entry 0x03C
	tsa_entry 0x03D
	tsa_entry 0x000, pal=2
	tsa_entry 0x001
	tsa_entry 0x002
	tsa_entry 0x003
	tsa_entry 0x004
	tsa_entry 0x005
	tsa_entry 0x006
	tsa_entry 0x007
	tsa_entry 0x008
	tsa_entry 0x009
	tsa_entry 0x00A
	tsa_entry 0x00B
	tsa_entry 0x00C
	tsa_entry 0x00D
	tsa_entry 0x00E, pal=1
	tsa_entry 0x00F, pal=1
	tsa_entry 0x010
	tsa_entry 0x011
	tsa_entry 0x012
	tsa_entry 0x013
	tsa_entry 0x014
	tsa_entry 0x015
	tsa_entry 0x016
	tsa_entry 0x017, pal=2
	tsa_entry 0x018
	tsa_entry 0x019
	tsa_entry 0x01A, pal=3
	tsa_entry 0x01B
	tsa_entry 0x01C
	tsa_entry 0x01D
