	.include "graphics/tsa.inc"

	.section .rodata

	tsa_entry 0x31D, pal=1
	tsa_entry 0x260, pal=3
	tsa_entry 0x261
	tsa_entry 0x262
	tsa_entry 0x263, pal=3
	tsa_entry 0x264, pal=2
	tsa_entry 0x265, pal=2
	tsa_entry 0x266, pal=2
	tsa_entry 0x267, pal=2
	tsa_entry 0x268, pal=2
	tsa_entry 0x269, pal=2
	tsa_entry 0x26A
	tsa_entry 0x26B
	tsa_entry 0x26C, pal=4
	tsa_entry 0x26D, pal=4
	tsa_entry 0x26E, pal=2
	tsa_entry 0x26F, pal=4
	tsa_entry 0x270, pal=4
	tsa_entry 0x271, pal=4
	tsa_entry 0x272, pal=4
	tsa_entry 0x273, pal=4
	tsa_entry 0x274, pal=4
	tsa_entry 0x275, pal=4
	tsa_entry 0x276, pal=4
	tsa_entry 0x277, pal=4
	tsa_entry 0x278, pal=4
	tsa_entry 0x279, pal=3
	tsa_entry 0x27A, pal=2
	tsa_entry 0x27B, pal=2
	tsa_entry 0x27C, pal=2
	tsa_entry 0x27D
	tsa_entry 0x240
	tsa_entry 0x241
	tsa_entry 0x242, pal=3
	tsa_entry 0x243
	tsa_entry 0x244
	tsa_entry 0x245, pal=2
	tsa_entry 0x246, pal=3
	tsa_entry 0x247, pal=2
	tsa_entry 0x248, pal=2
	tsa_entry 0x249, pal=3
	tsa_entry 0x24A, pal=3
	tsa_entry 0x24B
	tsa_entry 0x24C, pal=4
	tsa_entry 0x24D, pal=2
	tsa_entry 0x24E, pal=2
	tsa_entry 0x24F, pal=2
	tsa_entry 0x250, pal=4
	tsa_entry 0x251, pal=4
	tsa_entry 0x252, pal=4
	tsa_entry 0x253, pal=2
	tsa_entry 0x254, pal=5
	tsa_entry 0x255, pal=4
	tsa_entry 0x256, pal=4
	tsa_entry 0x257, pal=4
	tsa_entry 0x258, pal=4
	tsa_entry 0x259, pal=5
	tsa_entry 0x25A, pal=2
	tsa_entry 0x25B, pal=2
	tsa_entry 0x25C, pal=3
	tsa_entry 0x25D
	tsa_entry 0x220, pal=3
	tsa_entry 0x221
	tsa_entry 0x222, pal=3
	tsa_entry 0x223, pal=3
	tsa_entry 0x224, pal=3
	tsa_entry 0x225, pal=5
	tsa_entry 0x226, pal=3
	tsa_entry 0x227, pal=2
	tsa_entry 0x228, pal=2
	tsa_entry 0x229, pal=2
	tsa_entry 0x22A
	tsa_entry 0x22B
	tsa_entry 0x22C, pal=4
	tsa_entry 0x22D, pal=4
	tsa_entry 0x22E, pal=4
	tsa_entry 0x22F, pal=5
	tsa_entry 0x230, pal=4
	tsa_entry 0x231, pal=4
	tsa_entry 0x232, pal=4
	tsa_entry 0x233, pal=4
	tsa_entry 0x234, pal=4
	tsa_entry 0x235, pal=4
	tsa_entry 0x236, pal=4
	tsa_entry 0x237, pal=5
	tsa_entry 0x238
	tsa_entry 0x239, pal=5
	tsa_entry 0x23A, pal=5
	tsa_entry 0x23B, pal=2
	tsa_entry 0x23C, pal=2
	tsa_entry 0x23D, pal=2
	tsa_entry 0x200, pal=2
	tsa_entry 0x201
	tsa_entry 0x202
	tsa_entry 0x203, pal=3
	tsa_entry 0x204, pal=3
	tsa_entry 0x205, pal=5
	tsa_entry 0x206, pal=5
	tsa_entry 0x207, pal=3
	tsa_entry 0x208, pal=2
	tsa_entry 0x209, pal=2
	tsa_entry 0x20A
	tsa_entry 0x20B, pal=3
	tsa_entry 0x20C, pal=4
	tsa_entry 0x20D, pal=4
	tsa_entry 0x20E
	tsa_entry 0x20F, pal=4
	tsa_entry 0x210, pal=4
	tsa_entry 0x211, pal=4
	tsa_entry 0x212, pal=4
	tsa_entry 0x213, pal=4
	tsa_entry 0x214, pal=5
	tsa_entry 0x215
	tsa_entry 0x216, pal=5
	tsa_entry 0x217, pal=2
	tsa_entry 0x218, pal=2
	tsa_entry 0x219
	tsa_entry 0x21A, pal=3
	tsa_entry 0x21B, pal=2
	tsa_entry 0x21C, pal=2
	tsa_entry 0x21D, pal=5
	tsa_entry 0x1E0, pal=2
	tsa_entry 0x1E1, pal=2
	tsa_entry 0x1E2, pal=2
	tsa_entry 0x1E3, pal=2
	tsa_entry 0x1E4, pal=2
	tsa_entry 0x1E5, pal=5
	tsa_entry 0x1E6, pal=4
	tsa_entry 0x1E7, pal=4
	tsa_entry 0x1E8, pal=4
	tsa_entry 0x1E9, pal=2
	tsa_entry 0x1EA, pal=2
	tsa_entry 0x1EB, pal=2
	tsa_entry 0x1EC, pal=2
	tsa_entry 0x1ED, pal=4
	tsa_entry 0x1EE
	tsa_entry 0x1EF, pal=4
	tsa_entry 0x1F0, pal=4
	tsa_entry 0x1F1, pal=4
	tsa_entry 0x1F2, pal=4
	tsa_entry 0x1F3, pal=2
	tsa_entry 0x1F4, pal=4
	tsa_entry 0x1F5
	tsa_entry 0x1F6, pal=2
	tsa_entry 0x1F7, pal=2
	tsa_entry 0x1F8, pal=2
	tsa_entry 0x1F9
	tsa_entry 0x1FA
	tsa_entry 0x1FB, pal=2
	tsa_entry 0x1FC, pal=5
	tsa_entry 0x1FD, pal=2
	tsa_entry 0x1C0, pal=2
	tsa_entry 0x1C1, pal=2
	tsa_entry 0x1C2, pal=2
	tsa_entry 0x1C3, pal=2
	tsa_entry 0x1C4, pal=2
	tsa_entry 0x1C5, pal=2
	tsa_entry 0x1C6, pal=3
	tsa_entry 0x1C7, pal=4
	tsa_entry 0x1C8, pal=4
	tsa_entry 0x1C9, pal=2
	tsa_entry 0x1CA, pal=2
	tsa_entry 0x1CB, pal=5
	tsa_entry 0x1CC, pal=2
	tsa_entry 0x1CD, pal=5
	tsa_entry 0x1CE, pal=4
	tsa_entry 0x1CF, pal=4
	tsa_entry 0x1D0, pal=4
	tsa_entry 0x1D1, pal=4
	tsa_entry 0x1D2, pal=4
	tsa_entry 0x1D3, pal=4
	tsa_entry 0x1D4, pal=5
	tsa_entry 0x1D5, pal=5
	tsa_entry 0x1D6, pal=2
	tsa_entry 0x1D7, pal=5
	tsa_entry 0x1D8, pal=2
	tsa_entry 0x1D9, pal=2
	tsa_entry 0x1DA, pal=2
	tsa_entry 0x1DB, pal=2
	tsa_entry 0x1DC, pal=2
	tsa_entry 0x1DD, pal=2
	tsa_entry 0x1A0, pal=2
	tsa_entry 0x1A1, pal=2
	tsa_entry 0x1A2, pal=2
	tsa_entry 0x1A3, pal=1
	tsa_entry 0x1A4, pal=5
	tsa_entry 0x1A5, pal=5
	tsa_entry 0x1A6, pal=2
	tsa_entry 0x1A7, pal=5
	tsa_entry 0x1A8, pal=2
	tsa_entry 0x1A9, pal=2
	tsa_entry 0x1AA, pal=2
	tsa_entry 0x1AB, pal=5
	tsa_entry 0x1AC, pal=2
	tsa_entry 0x1AD, pal=2
	tsa_entry 0x1AE, pal=4
	tsa_entry 0x1AF, pal=4
	tsa_entry 0x1B0, pal=4
	tsa_entry 0x1B1, pal=4
	tsa_entry 0x1B2, pal=5
	tsa_entry 0x1B3, pal=3
	tsa_entry 0x1B4, pal=3
	tsa_entry 0x1B5, pal=5
	tsa_entry 0x1B6, pal=2
	tsa_entry 0x1B7, pal=2
	tsa_entry 0x1B8, pal=2
	tsa_entry 0x1B9, pal=2
	tsa_entry 0x1BA, pal=2
	tsa_entry 0x1BB, pal=2
	tsa_entry 0x1BC, pal=5
	tsa_entry 0x1BD, pal=5
	tsa_entry 0x180, pal=2
	tsa_entry 0x181, pal=2
	tsa_entry 0x182, pal=2
	tsa_entry 0x183, pal=3
	tsa_entry 0x184, pal=5
	tsa_entry 0x185, pal=4
	tsa_entry 0x186, pal=4
	tsa_entry 0x187, pal=2
	tsa_entry 0x188, pal=2
	tsa_entry 0x189, pal=2
	tsa_entry 0x18A, pal=2
	tsa_entry 0x18B, pal=2
	tsa_entry 0x18C, pal=2
	tsa_entry 0x18D, pal=2
	tsa_entry 0x18E, pal=2
	tsa_entry 0x18F, pal=5
	tsa_entry 0x190, pal=4
	tsa_entry 0x191, pal=2
	tsa_entry 0x192, pal=5
	tsa_entry 0x193, pal=5
	tsa_entry 0x194, pal=4
	tsa_entry 0x195, pal=2
	tsa_entry 0x196, pal=2
	tsa_entry 0x197, pal=2
	tsa_entry 0x198, pal=2
	tsa_entry 0x199, pal=2
	tsa_entry 0x19A, pal=2
	tsa_entry 0x19B, pal=2
	tsa_entry 0x19C, pal=2
	tsa_entry 0x19D, pal=2
	tsa_entry 0x160, pal=2
	tsa_entry 0x161, pal=2
	tsa_entry 0x162, pal=5
	tsa_entry 0x163, pal=2
	tsa_entry 0x164, pal=4
	tsa_entry 0x165, pal=4
	tsa_entry 0x166, pal=5
	tsa_entry 0x167, pal=2
	tsa_entry 0x168, pal=4
	tsa_entry 0x169, pal=4
	tsa_entry 0x16A, pal=1
	tsa_entry 0x16B, pal=5
	tsa_entry 0x16C, pal=2
	tsa_entry 0x16D, pal=2
	tsa_entry 0x16E, pal=5
	tsa_entry 0x16F, pal=2
	tsa_entry 0x170, pal=4
	tsa_entry 0x171, pal=4
	tsa_entry 0x172, pal=2
	tsa_entry 0x173, pal=5
	tsa_entry 0x174, pal=2
	tsa_entry 0x175, pal=2
	tsa_entry 0x176, pal=2
	tsa_entry 0x177, pal=5
	tsa_entry 0x178, pal=1
	tsa_entry 0x179, pal=1
	tsa_entry 0x17A, pal=5
	tsa_entry 0x17B, pal=2
	tsa_entry 0x17C, pal=2
	tsa_entry 0x17D, pal=2
	tsa_entry 0x140, pal=2
	tsa_entry 0x141
	tsa_entry 0x142
	tsa_entry 0x143
	tsa_entry 0x144, pal=4
	tsa_entry 0x145, pal=4
	tsa_entry 0x146, pal=2
	tsa_entry 0x147
	tsa_entry 0x148, pal=1
	tsa_entry 0x149
	tsa_entry 0x14A, pal=5
	tsa_entry 0x14B, pal=1
	tsa_entry 0x14C, pal=4
	tsa_entry 0x14D, pal=5
	tsa_entry 0x14E, pal=5
	tsa_entry 0x14F, pal=5
	tsa_entry 0x150, pal=4
	tsa_entry 0x151, pal=4
	tsa_entry 0x152, pal=4
	tsa_entry 0x153, pal=4
	tsa_entry 0x154, pal=2
	tsa_entry 0x155, pal=2
	tsa_entry 0x156, pal=5
	tsa_entry 0x157, pal=5
	tsa_entry 0x158, pal=2
	tsa_entry 0x159, pal=2
	tsa_entry 0x15A, pal=2
	tsa_entry 0x15B, pal=2
	tsa_entry 0x15C, pal=2
	tsa_entry 0x15D, pal=2
	tsa_entry 0x120
	tsa_entry 0x121
	tsa_entry 0x122
	tsa_entry 0x123
	tsa_entry 0x124
	tsa_entry 0x125, pal=1
	tsa_entry 0x126
	tsa_entry 0x127, pal=2
	tsa_entry 0x128
	tsa_entry 0x129, pal=5
	tsa_entry 0x12A, pal=5
	tsa_entry 0x12B, pal=5
	tsa_entry 0x12C, pal=1
	tsa_entry 0x12D, pal=3
	tsa_entry 0x12E, pal=5
	tsa_entry 0x12F, pal=1
	tsa_entry 0x130, pal=2
	tsa_entry 0x131, pal=2
	tsa_entry 0x132, pal=5
	tsa_entry 0x133, pal=2
	tsa_entry 0x134, pal=2
	tsa_entry 0x135, pal=5
	tsa_entry 0x136, pal=5
	tsa_entry 0x137, pal=2
	tsa_entry 0x138, pal=2
	tsa_entry 0x139, pal=2
	tsa_entry 0x13A, pal=2
	tsa_entry 0x13B, pal=5
	tsa_entry 0x13C, pal=2
	tsa_entry 0x13D, pal=2
	tsa_entry 0x100
	tsa_entry 0x101
	tsa_entry 0x102
	tsa_entry 0x103
	tsa_entry 0x104
	tsa_entry 0x105
	tsa_entry 0x106
	tsa_entry 0x107, pal=1
	tsa_entry 0x108, pal=1
	tsa_entry 0x109
	tsa_entry 0x10A, pal=3
	tsa_entry 0x10B, pal=5
	tsa_entry 0x10C, pal=5
	tsa_entry 0x10D, pal=2
	tsa_entry 0x10E, pal=2
	tsa_entry 0x10F, pal=5
	tsa_entry 0x110, pal=2
	tsa_entry 0x111, pal=2
	tsa_entry 0x112
	tsa_entry 0x113
	tsa_entry 0x114, pal=2
	tsa_entry 0x115, pal=2
	tsa_entry 0x116, pal=2
	tsa_entry 0x117, pal=2
	tsa_entry 0x118, pal=2
	tsa_entry 0x119, pal=2
	tsa_entry 0x11A, pal=2
	tsa_entry 0x11B, pal=2
	tsa_entry 0x11C, pal=2
	tsa_entry 0x11D, pal=2
	tsa_entry 0x0E0
	tsa_entry 0x0E1
	tsa_entry 0x0E2
	tsa_entry 0x0E3
	tsa_entry 0x0E4
	tsa_entry 0x0E5
	tsa_entry 0x0E6
	tsa_entry 0x0E7
	tsa_entry 0x0E8, pal=2
	tsa_entry 0x0E9, pal=2
	tsa_entry 0x0EA
	tsa_entry 0x0EB, pal=5
	tsa_entry 0x0EC, pal=4
	tsa_entry 0x0ED, pal=2
	tsa_entry 0x0EE, pal=3
	tsa_entry 0x0EF, pal=5
	tsa_entry 0x0F0, pal=1
	tsa_entry 0x0F1
	tsa_entry 0x0F2
	tsa_entry 0x0F3, pal=1
	tsa_entry 0x0F4, pal=2
	tsa_entry 0x0F5
	tsa_entry 0x0F6, pal=2
	tsa_entry 0x0F7, pal=2
	tsa_entry 0x0F8, pal=2
	tsa_entry 0x0F9, pal=2
	tsa_entry 0x0FA, pal=2
	tsa_entry 0x0FB, pal=2
	tsa_entry 0x0FC, pal=2
	tsa_entry 0x0FD, pal=2
	tsa_entry 0x0C0
	tsa_entry 0x0C1
	tsa_entry 0x0C2, pal=2
	tsa_entry 0x0C3, pal=2
	tsa_entry 0x0C4
	tsa_entry 0x0C5
	tsa_entry 0x0C6
	tsa_entry 0x0C7
	tsa_entry 0x0C8, pal=2
	tsa_entry 0x0C9, pal=5
	tsa_entry 0x0CA, pal=1
	tsa_entry 0x0CB, pal=1
	tsa_entry 0x0CC, pal=4
	tsa_entry 0x0CD, pal=5
	tsa_entry 0x0CE, pal=2
	tsa_entry 0x0CF, pal=1
	tsa_entry 0x0D0, pal=5
	tsa_entry 0x0D1, pal=2
	tsa_entry 0x0D2, pal=2
	tsa_entry 0x0D3, pal=2
	tsa_entry 0x0D4, pal=2
	tsa_entry 0x0D5
	tsa_entry 0x0D6, pal=2
	tsa_entry 0x0D7, pal=5
	tsa_entry 0x0D8, pal=2
	tsa_entry 0x0D9, pal=2
	tsa_entry 0x0DA, pal=2
	tsa_entry 0x0DB, pal=2
	tsa_entry 0x0DC, pal=2
	tsa_entry 0x0DD, pal=5
	tsa_entry 0x0A0
	tsa_entry 0x0A1, pal=2
	tsa_entry 0x0A2, pal=2
	tsa_entry 0x0A3, pal=2
	tsa_entry 0x0A4
	tsa_entry 0x0A5
	tsa_entry 0x0A6
	tsa_entry 0x0A7
	tsa_entry 0x0A8
	tsa_entry 0x0A9, pal=5
	tsa_entry 0x0AA
	tsa_entry 0x0AB, pal=5
	tsa_entry 0x0AC, pal=5
	tsa_entry 0x0AD, pal=2
	tsa_entry 0x0AE, pal=2
	tsa_entry 0x0AF, pal=5
	tsa_entry 0x0B0, pal=5
	tsa_entry 0x0B1, pal=3
	tsa_entry 0x0B2, pal=1
	tsa_entry 0x0B3
	tsa_entry 0x0B4, pal=2
	tsa_entry 0x0B5
	tsa_entry 0x0B6, pal=2
	tsa_entry 0x0B7, pal=2
	tsa_entry 0x0B8, pal=2
	tsa_entry 0x0B9, pal=2
	tsa_entry 0x0BA, pal=2
	tsa_entry 0x0BB, pal=2
	tsa_entry 0x0BC, pal=2
	tsa_entry 0x0BD, pal=2
	tsa_entry 0x080
	tsa_entry 0x081
	tsa_entry 0x082, pal=2
	tsa_entry 0x083
	tsa_entry 0x084
	tsa_entry 0x085
	tsa_entry 0x086, pal=2
	tsa_entry 0x087
	tsa_entry 0x088
	tsa_entry 0x089, pal=2
	tsa_entry 0x08A, pal=5
	tsa_entry 0x08B, pal=5
	tsa_entry 0x08C, pal=4
	tsa_entry 0x08D, pal=2
	tsa_entry 0x08E, pal=1
	tsa_entry 0x08F, pal=1
	tsa_entry 0x090, pal=4
	tsa_entry 0x091, pal=2
	tsa_entry 0x092
	tsa_entry 0x093
	tsa_entry 0x094
	tsa_entry 0x095
	tsa_entry 0x096
	tsa_entry 0x097, pal=2
	tsa_entry 0x098, pal=2
	tsa_entry 0x099, pal=2
	tsa_entry 0x09A, pal=2
	tsa_entry 0x09B, pal=5
	tsa_entry 0x09C, pal=2
	tsa_entry 0x09D, pal=2
	tsa_entry 0x060, pal=1
	tsa_entry 0x061, pal=2
	tsa_entry 0x062
	tsa_entry 0x063
	tsa_entry 0x064
	tsa_entry 0x065
	tsa_entry 0x066
	tsa_entry 0x067
	tsa_entry 0x068
	tsa_entry 0x069, pal=2
	tsa_entry 0x06A, pal=2
	tsa_entry 0x06B, pal=5
	tsa_entry 0x06C, pal=4
	tsa_entry 0x06D, pal=2
	tsa_entry 0x06E, pal=1
	tsa_entry 0x06F, pal=1
	tsa_entry 0x070, pal=1
	tsa_entry 0x071
	tsa_entry 0x072
	tsa_entry 0x073
	tsa_entry 0x074, pal=2
	tsa_entry 0x075, pal=2
	tsa_entry 0x076
	tsa_entry 0x077, pal=2
	tsa_entry 0x078, pal=2
	tsa_entry 0x079, pal=2
	tsa_entry 0x07A, pal=2
	tsa_entry 0x07B, pal=2
	tsa_entry 0x07C, pal=2
	tsa_entry 0x07D, pal=2
	tsa_entry 0x040
	tsa_entry 0x041
	tsa_entry 0x042
	tsa_entry 0x043
	tsa_entry 0x044
	tsa_entry 0x045
	tsa_entry 0x046
	tsa_entry 0x047, pal=2
	tsa_entry 0x048, pal=2
	tsa_entry 0x049, pal=2
	tsa_entry 0x04A, pal=5
	tsa_entry 0x04B, pal=2
	tsa_entry 0x04C, pal=5
	tsa_entry 0x04D, pal=2
	tsa_entry 0x04E, pal=2
	tsa_entry 0x04F
	tsa_entry 0x050
	tsa_entry 0x051, pal=5
	tsa_entry 0x052
	tsa_entry 0x053
	tsa_entry 0x054, pal=2
	tsa_entry 0x055
	tsa_entry 0x056, pal=2
	tsa_entry 0x057
	tsa_entry 0x058
	tsa_entry 0x059, pal=2
	tsa_entry 0x05A, pal=2
	tsa_entry 0x05B, pal=2
	tsa_entry 0x05C, pal=2
	tsa_entry 0x05D, pal=2
	tsa_entry 0x020
	tsa_entry 0x021
	tsa_entry 0x022
	tsa_entry 0x023
	tsa_entry 0x024
	tsa_entry 0x025
	tsa_entry 0x026
	tsa_entry 0x027
	tsa_entry 0x028
	tsa_entry 0x029, pal=3
	tsa_entry 0x02A, pal=2
	tsa_entry 0x02B, pal=2
	tsa_entry 0x02C, pal=2
	tsa_entry 0x02D, pal=2
	tsa_entry 0x02E, pal=2
	tsa_entry 0x02F
	tsa_entry 0x030
	tsa_entry 0x031, pal=2
	tsa_entry 0x032
	tsa_entry 0x033
	tsa_entry 0x034, pal=2
	tsa_entry 0x035
	tsa_entry 0x036
	tsa_entry 0x037, pal=2
	tsa_entry 0x038, pal=2
	tsa_entry 0x039, pal=2
	tsa_entry 0x03A, pal=2
	tsa_entry 0x03B, pal=2
	tsa_entry 0x03C, pal=2
	tsa_entry 0x03D, pal=2
	tsa_entry 0x000
	tsa_entry 0x001
	tsa_entry 0x002
	tsa_entry 0x003
	tsa_entry 0x004
	tsa_entry 0x005
	tsa_entry 0x006
	tsa_entry 0x007
	tsa_entry 0x008
	tsa_entry 0x009
	tsa_entry 0x00A, pal=2
	tsa_entry 0x00B, pal=2
	tsa_entry 0x00C
	tsa_entry 0x00D, pal=2
	tsa_entry 0x00E, pal=2
	tsa_entry 0x00F, pal=2
	tsa_entry 0x010, pal=5
	tsa_entry 0x011
	tsa_entry 0x012
	tsa_entry 0x013
	tsa_entry 0x014, pal=2
	tsa_entry 0x015, pal=2
	tsa_entry 0x016, pal=2
	tsa_entry 0x017, pal=2
	tsa_entry 0x018, pal=2
	tsa_entry 0x019, pal=2
	tsa_entry 0x01A, pal=2
	tsa_entry 0x01B, pal=2
	tsa_entry 0x01C, pal=2
	tsa_entry 0x01D, pal=2
