"""Committed public inventory/summary for the ``items`` table."""

from __future__ import annotations

from collections import Counter

from ..validators import extract_enum_constants
from .schema import BMITEM_HEADER, ITEMS_HEADER, SCHEMA_ID, dependency_graph, read_item_attributes


def build_inventory(records):
    graph = dependency_graph()
    items_enum = extract_enum_constants(ITEMS_HEADER, name_prefix="ITEM_")
    attribute_flags = read_item_attributes(BMITEM_HEADER)

    values = sorted(items_enum[r.item][0] for r in records if r.item in items_enum)
    weapon_type_counts = Counter(r.weapon_type for r in records)
    stat_bonus_counts = Counter(r.stat_bonuses for r in records if r.stat_bonuses is not None)
    effectiveness_counts = Counter(r.effectiveness for r in records if r.effectiveness is not None)
    attribute_counts = Counter()
    for record in records:
        for name in record.attributes:
            attribute_counts[name] += 1

    lines = []
    lines.append("# Generated-data inventory: items\n")
    lines.append("\n")
    lines.append("_Auto-generated by `python3 -m scripts.generated_data generate --table items`. "
                  "Do not edit by hand -- see docs/generated_data.md._\n")
    lines.append("\n")
    lines.append("- Schema: `{}`\n".format(SCHEMA_ID))
    lines.append("- Item record count: {}\n".format(len(records)))
    lines.append("- Index range: {}..{}\n".format(values[0] if values else "n/a", values[-1] if values else "n/a"))
    lines.append("- Dependencies: {}\n".format(", ".join(graph.nodes())))
    lines.append("- Dependency graph digest (sha256): `{}`\n".format(graph.digest()))
    lines.append("\n")

    lines.append("## Weapon-type histogram\n")
    lines.append("\n")
    lines.append("| Weapon type | Item count |\n")
    lines.append("|---|---|\n")
    for weapon_type, count in sorted(weapon_type_counts.items()):
        lines.append("| {} | {} |\n".format(weapon_type, count))
    lines.append("\n")

    lines.append("## Attribute (`IA_*`) usage\n")
    lines.append("\n")
    lines.append("| Attribute | Item count |\n")
    lines.append("|---|---|\n")
    for name in sorted(attribute_counts, key=lambda n: attribute_flags.get(n, 0)):
        lines.append("| {} | {} |\n".format(name, attribute_counts[name]))
    lines.append("\n")

    lines.append("## Pointer-symbol usage\n")
    lines.append("\n")
    lines.append("### `pStatBonuses` (`ItemBonus_*`)\n")
    lines.append("\n")
    if stat_bonus_counts:
        lines.append("| Symbol | Item count |\n")
        lines.append("|---|---|\n")
        for symbol, count in sorted(stat_bonus_counts.items()):
            lines.append("| {} | {} |\n".format(symbol, count))
    else:
        lines.append("_none_\n")
    lines.append("\n")

    lines.append("### `pEffectiveness` (`ItemEffectiveness_*`)\n")
    lines.append("\n")
    if effectiveness_counts:
        lines.append("| Symbol | Item count |\n")
        lines.append("|---|---|\n")
        for symbol, count in sorted(effectiveness_counts.items()):
            lines.append("| {} | {} |\n".format(symbol, count))
    else:
        lines.append("_none_\n")

    return "".join(lines)
