#include "global.h"

#include "localized_ui_graphics.h"

#if LOCALIZED_UI_GRAPHICS_CJK_ENABLED

/* Generated by scripts/localization/extract_ui_graphics.py. */
static const u8 sLocalizedUiJaTitleLogoPng[] = INCBIN_U8("graphics/localized_ui/ja/title/logo.4bpp.lz");
static const u8 sLocalizedUiJaTitleLabelsPng[] = INCBIN_U8("graphics/localized_ui/ja/title/labels.4bpp.lz");
static const u8 sLocalizedUiJaMenuMainExtraOptionsPng[] = INCBIN_U8("graphics/localized_ui/ja/menu/main_extra_options.4bpp.lz");
static const u8 sLocalizedUiJaPrologueSlide00Png[] = INCBIN_U8("graphics/localized_ui/ja/prologue/slide_00.4bpp.lz");
static const u8 sLocalizedUiJaPrologueSlide00TsaBin[] = INCBIN_U8("graphics/localized_ui/ja/prologue/slide_00.tsa.bin.lz");
static const u8 sLocalizedUiJaPrologueSlide01Png[] = INCBIN_U8("graphics/localized_ui/ja/prologue/slide_01.4bpp.lz");
static const u8 sLocalizedUiJaPrologueSlide01TsaBin[] = INCBIN_U8("graphics/localized_ui/ja/prologue/slide_01.tsa.bin.lz");
static const u8 sLocalizedUiJaPrologueSlide02Png[] = INCBIN_U8("graphics/localized_ui/ja/prologue/slide_02.4bpp.lz");
static const u8 sLocalizedUiJaPrologueSlide02TsaBin[] = INCBIN_U8("graphics/localized_ui/ja/prologue/slide_02.tsa.bin.lz");
static const u8 sLocalizedUiJaPrologueSlide03Png[] = INCBIN_U8("graphics/localized_ui/ja/prologue/slide_03.4bpp.lz");
static const u8 sLocalizedUiJaPrologueSlide03TsaBin[] = INCBIN_U8("graphics/localized_ui/ja/prologue/slide_03.tsa.bin.lz");
static const u8 sLocalizedUiJaPrologueSlide04Png[] = INCBIN_U8("graphics/localized_ui/ja/prologue/slide_04.4bpp.lz");
static const u8 sLocalizedUiJaPrologueSlide04TsaBin[] = INCBIN_U8("graphics/localized_ui/ja/prologue/slide_04.tsa.bin.lz");
static const u8 sLocalizedUiJaPrologueSlide05Png[] = INCBIN_U8("graphics/localized_ui/ja/prologue/slide_05.4bpp.lz");
static const u8 sLocalizedUiJaPrologueSlide05TsaBin[] = INCBIN_U8("graphics/localized_ui/ja/prologue/slide_05.tsa.bin.lz");
static const u8 sLocalizedUiJaPrologueSlide06Png[] = INCBIN_U8("graphics/localized_ui/ja/prologue/slide_06.4bpp.lz");
static const u8 sLocalizedUiJaPrologueSlide06TsaBin[] = INCBIN_U8("graphics/localized_ui/ja/prologue/slide_06.tsa.bin.lz");
static const u8 sLocalizedUiJaChapterAsset08A7E188Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A7E188.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8Bfb0Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8BFB0.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8DbfcPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8DBFC.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A7E504Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A7E504.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8C0EcPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8C0EC.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8De6CPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8DE6C.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A7E800Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A7E800.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8C1E4Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8C1E4.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8E080Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8E080.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A7Eb7CPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A7EB7C.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8C308Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8C308.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8E2EcPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8E2EC.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A7Ef88Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A7EF88.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8C424Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8C424.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8E600Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8E600.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A7F360Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A7F360.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8C534Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8C534.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8E8C8Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8E8C8.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A7F754Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A7F754.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8C734Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8C734.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8Eaf8Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8EAF8.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A7Faa4Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A7FAA4.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8C854Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8C854.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8Ed30Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8ED30.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A7Fe84Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A7FE84.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8C974Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8C974.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8EffcPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8EFFC.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8021CPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8021C.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8Ca74Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8CA74.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8F28CPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8F28C.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A80584Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A80584.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8Cb94Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8CB94.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8F4CcPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8F4CC.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A808BcPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A808BC.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8CcacPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8CCAC.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8F6F8Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8F6F8.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A81068Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A81068.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8Cf14Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8CF14.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8Fc68Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8FC68.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A813F8Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A813F8.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8D064Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8D064.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8Fec0Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8FEC0.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A81774Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A81774.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8D1B0Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8D1B0.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A900FcPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A900FC.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8306CPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8306C.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8D2F4Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8D2F4.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A911D0Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A911D0.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A833D4Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A833D4.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8D430Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8D430.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A91418Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A91418.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8383CPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8383C.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8D574Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8D574.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A91760Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A91760.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A83C0CPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A83C0C.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8D6AcPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8D6AC.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A919F8Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A919F8.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A83F64Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A83F64.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8D7F4Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8D7F4.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A91C28Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A91C28.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8436CPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8436C.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8D948Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8D948.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A91F08Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A91F08.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A84720Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A84720.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8Dab0Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8DAB0.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A92170Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A92170.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A81B1CPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A81B1C.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A90378Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A90378.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A81F28Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A81F28.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A9065CPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A9065C.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8258CPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8258C.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A90A98Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A90A98.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A829B4Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A829B4.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A90D84Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A90D84.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A82D58Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A82D58.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A90Ff0Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A90FF0.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A84BfcPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A84BFC.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A84F64Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A84F64.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A852E8Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A852E8.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A85670Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A85670.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A859E4Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A859E4.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A85D6CPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A85D6C.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A860F4Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A860F4.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A86460Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A86460.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A867E4Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A867E4.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A86B60Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A86B60.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A86Ef8Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A86EF8.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8729CPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8729C.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8765CPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8765C.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A87A14Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A87A14.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A87DbcPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A87DBC.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A88174Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A88174.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A88530Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A88530.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A888D0Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A888D0.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A88C8CPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A88C8C.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A89048Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A89048.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8B7F0Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8B7F0.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8B5DcPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8B5DC.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A80Ca0Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A80CA0.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8Cdf8Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8CDF8.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8F9C0Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8F9C0.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A82294Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A82294.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A90898Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A90898.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A89428Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A89428.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A89710Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A89710.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A899E8Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A899E8.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A89Cd8Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A89CD8.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A89F80Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A89F80.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8A260Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8A260.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8A5A0Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8A5A0.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8A85CPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8A85C.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8Ab8CPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8AB8C.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8Ae74Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8AE74.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8B168Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8B168.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8B39CPng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8B39C.4bpp.lz");
static const u8 sLocalizedUiJaChapterAsset08A8Bb88Png[] = INCBIN_U8("graphics/localized_ui/ja/chapter/asset_08A8BB88.4bpp.lz");
static const u8 sLocalizedUiJaChapterFramePng[] = INCBIN_U8("graphics/localized_ui/ja/chapter/frame.4bpp.lz");
static const u8 sLocalizedUiJaChapterTitleLayoutTsaBin[] = INCBIN_U8("graphics/localized_ui/ja/chapter/title_layout.tsa.bin.lz");

static const u8 sLocalizedUiZhHansTitleLogoPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/title/logo.4bpp.lz");
static const u8 sLocalizedUiZhHansTitleLabelsPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/title/labels.4bpp.lz");
static const u8 sLocalizedUiZhHansMenuMainExtraOptionsPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/menu/main_extra_options.4bpp.lz");
static const u8 sLocalizedUiZhHansPrologueSlide00Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/prologue/slide_00.4bpp.lz");
static const u8 sLocalizedUiZhHansPrologueSlide00TsaBin[] = INCBIN_U8("graphics/localized_ui/zh-Hans/prologue/slide_00.tsa.bin.lz");
static const u8 sLocalizedUiZhHansPrologueSlide01Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/prologue/slide_01.4bpp.lz");
static const u8 sLocalizedUiZhHansPrologueSlide01TsaBin[] = INCBIN_U8("graphics/localized_ui/zh-Hans/prologue/slide_01.tsa.bin.lz");
static const u8 sLocalizedUiZhHansPrologueSlide02Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/prologue/slide_02.4bpp.lz");
static const u8 sLocalizedUiZhHansPrologueSlide02TsaBin[] = INCBIN_U8("graphics/localized_ui/zh-Hans/prologue/slide_02.tsa.bin.lz");
static const u8 sLocalizedUiZhHansPrologueSlide03Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/prologue/slide_03.4bpp.lz");
static const u8 sLocalizedUiZhHansPrologueSlide03TsaBin[] = INCBIN_U8("graphics/localized_ui/zh-Hans/prologue/slide_03.tsa.bin.lz");
static const u8 sLocalizedUiZhHansPrologueSlide04Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/prologue/slide_04.4bpp.lz");
static const u8 sLocalizedUiZhHansPrologueSlide04TsaBin[] = INCBIN_U8("graphics/localized_ui/zh-Hans/prologue/slide_04.tsa.bin.lz");
static const u8 sLocalizedUiZhHansPrologueSlide05Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/prologue/slide_05.4bpp.lz");
static const u8 sLocalizedUiZhHansPrologueSlide05TsaBin[] = INCBIN_U8("graphics/localized_ui/zh-Hans/prologue/slide_05.tsa.bin.lz");
static const u8 sLocalizedUiZhHansPrologueSlide06Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/prologue/slide_06.4bpp.lz");
static const u8 sLocalizedUiZhHansPrologueSlide06TsaBin[] = INCBIN_U8("graphics/localized_ui/zh-Hans/prologue/slide_06.tsa.bin.lz");
static const u8 sLocalizedUiZhHansChapterAsset085Afb24Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085AFB24.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F0A78Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F0A78.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F2150Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F2150.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085Afe7CPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085AFE7C.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F0B90Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F0B90.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F23AcPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F23AC.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B0098Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B0098.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F0C70Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F0C70.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F24EcPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F24EC.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B046CPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B046C.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F0D60Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F0D60.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F27CcPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F27CC.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B0808Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B0808.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F0E48Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F0E48.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F2Aa8Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F2AA8.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B0A44Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B0A44.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F0F30Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F0F30.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F2C00Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F2C00.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B0E54Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B0E54.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F10BcPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F10BC.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F2E8CPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F2E8C.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B1128Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B1128.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F11AcPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F11AC.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F307CPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F307C.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B1464Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B1464.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F12A0Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F12A0.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F32D8Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F32D8.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B1780Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B1780.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F1380Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F1380.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F3510Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F3510.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B1A40Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B1A40.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F1468Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F1468.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F36F8Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F36F8.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B1D54Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B1D54.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F1554Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F1554.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F3920Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F3920.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B2438Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B2438.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F1744Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F1744.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F3E44Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F3E44.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B271CPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B271C.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F1840Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F1840.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F403CPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F403C.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B2A40Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B2A40.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F1940Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F1940.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F426CPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F426C.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B4060Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B4060.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F1A40Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F1A40.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F51E0Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F51E0.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B43A0Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B43A0.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F1B3CPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F1B3C.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F5444Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F5444.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B46E0Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B46E0.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F1C34Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F1C34.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F568CPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F568C.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B4A08Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B4A08.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F1D2CPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F1D2C.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F58C4Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F58C4.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B4Cf8Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B4CF8.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F1E28Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F1E28.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F5Ab4Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F5AB4.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B5050Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B5050.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F1F28Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F1F28.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F5D08Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F5D08.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B535CPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B535C.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F2038Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F2038.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F5F10Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F5F10.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B2D3CPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B2D3C.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F4478Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F4478.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B3108Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B3108.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F4770Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F4770.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B3690Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B3690.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F4B00Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F4B00.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B3A90Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B3A90.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F4E14Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F4E14.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B3Dd8Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B3DD8.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F5058Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F5058.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B569CPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B569C.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B59C0Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B59C0.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B5D00Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B5D00.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B6034Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B6034.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B636CPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B636C.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B669CPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B669C.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B69D8Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B69D8.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B6D0CPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B6D0C.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B7044Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B7044.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B7378Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B7378.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B76C0Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B76C0.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B79EcPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B79EC.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B7D2CPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B7D2C.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B8060Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B8060.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B8398Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B8398.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B86C8Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B86C8.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080Ed85CPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080ED85C.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080Edb98Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080EDB98.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080EdeccPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080EDECC.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080Ee204Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080EE204.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F04E0Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F04E0.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F0318Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F0318.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B2110Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B2110.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F1658Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F1658.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F3Be4Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F3BE4.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B33F0Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B33F0.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F4950Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F4950.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset085B8A00Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_085B8A00.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080Ee560Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080EE560.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080Ee868Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080EE868.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080Eeb1CPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080EEB1C.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080Eedb4Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080EEDB4.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080Ef070Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080EF070.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080Ef380Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080EF380.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080Ef618Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080EF618.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080Ef950Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080EF950.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080Efc58Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080EFC58.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080EfeccPng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080EFECC.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F0098Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F0098.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterAsset080F0758Png[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/asset_080F0758.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterFramePng[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/frame.4bpp.lz");
static const u8 sLocalizedUiZhHansChapterTitleLayoutTsaBin[] = INCBIN_U8("graphics/localized_ui/zh-Hans/chapter/title_layout.tsa.bin.lz");

static const struct LocalizedUiGraphicsSubtitleSlide sLocalizedUiJaSubtitle[] = {
    { sLocalizedUiJaPrologueSlide00Png, sLocalizedUiJaPrologueSlide00TsaBin, 335 },
    { sLocalizedUiJaPrologueSlide01Png, sLocalizedUiJaPrologueSlide01TsaBin, 280 },
    { sLocalizedUiJaPrologueSlide02Png, sLocalizedUiJaPrologueSlide02TsaBin, 120 },
    { sLocalizedUiJaPrologueSlide03Png, sLocalizedUiJaPrologueSlide03TsaBin, 280 },
    { sLocalizedUiJaPrologueSlide04Png, sLocalizedUiJaPrologueSlide04TsaBin, 330 },
    { sLocalizedUiJaPrologueSlide05Png, sLocalizedUiJaPrologueSlide05TsaBin, 300 },
    { sLocalizedUiJaPrologueSlide06Png, sLocalizedUiJaPrologueSlide06TsaBin, 250 },
};

static const struct LocalizedUiGraphicsChapterTitle sLocalizedUiJaChapterTitles[] = {
    { sLocalizedUiJaChapterAsset08A7E188Png, sLocalizedUiJaChapterAsset08A8Bfb0Png, sLocalizedUiJaChapterAsset08A8DbfcPng },
    { sLocalizedUiJaChapterAsset08A7E504Png, sLocalizedUiJaChapterAsset08A8C0EcPng, sLocalizedUiJaChapterAsset08A8De6CPng },
    { sLocalizedUiJaChapterAsset08A7E800Png, sLocalizedUiJaChapterAsset08A8C1E4Png, sLocalizedUiJaChapterAsset08A8E080Png },
    { sLocalizedUiJaChapterAsset08A7Eb7CPng, sLocalizedUiJaChapterAsset08A8C308Png, sLocalizedUiJaChapterAsset08A8E2EcPng },
    { sLocalizedUiJaChapterAsset08A7Ef88Png, sLocalizedUiJaChapterAsset08A8C424Png, sLocalizedUiJaChapterAsset08A8E600Png },
    { sLocalizedUiJaChapterAsset08A7F360Png, sLocalizedUiJaChapterAsset08A8C534Png, sLocalizedUiJaChapterAsset08A8E8C8Png },
    { sLocalizedUiJaChapterAsset08A7F754Png, sLocalizedUiJaChapterAsset08A8C734Png, sLocalizedUiJaChapterAsset08A8Eaf8Png },
    { sLocalizedUiJaChapterAsset08A7Faa4Png, sLocalizedUiJaChapterAsset08A8C854Png, sLocalizedUiJaChapterAsset08A8Ed30Png },
    { sLocalizedUiJaChapterAsset08A7Fe84Png, sLocalizedUiJaChapterAsset08A8C974Png, sLocalizedUiJaChapterAsset08A8EffcPng },
    { sLocalizedUiJaChapterAsset08A8021CPng, sLocalizedUiJaChapterAsset08A8Ca74Png, sLocalizedUiJaChapterAsset08A8F28CPng },
    { sLocalizedUiJaChapterAsset08A80584Png, sLocalizedUiJaChapterAsset08A8Cb94Png, sLocalizedUiJaChapterAsset08A8F4CcPng },
    { sLocalizedUiJaChapterAsset08A808BcPng, sLocalizedUiJaChapterAsset08A8CcacPng, sLocalizedUiJaChapterAsset08A8F6F8Png },
    { sLocalizedUiJaChapterAsset08A81068Png, sLocalizedUiJaChapterAsset08A8Cf14Png, sLocalizedUiJaChapterAsset08A8Fc68Png },
    { sLocalizedUiJaChapterAsset08A813F8Png, sLocalizedUiJaChapterAsset08A8D064Png, sLocalizedUiJaChapterAsset08A8Fec0Png },
    { sLocalizedUiJaChapterAsset08A81774Png, sLocalizedUiJaChapterAsset08A8D1B0Png, sLocalizedUiJaChapterAsset08A900FcPng },
    { sLocalizedUiJaChapterAsset08A8306CPng, sLocalizedUiJaChapterAsset08A8D2F4Png, sLocalizedUiJaChapterAsset08A911D0Png },
    { sLocalizedUiJaChapterAsset08A833D4Png, sLocalizedUiJaChapterAsset08A8D430Png, sLocalizedUiJaChapterAsset08A91418Png },
    { sLocalizedUiJaChapterAsset08A8383CPng, sLocalizedUiJaChapterAsset08A8D574Png, sLocalizedUiJaChapterAsset08A91760Png },
    { sLocalizedUiJaChapterAsset08A83C0CPng, sLocalizedUiJaChapterAsset08A8D6AcPng, sLocalizedUiJaChapterAsset08A919F8Png },
    { sLocalizedUiJaChapterAsset08A83F64Png, sLocalizedUiJaChapterAsset08A8D7F4Png, sLocalizedUiJaChapterAsset08A91C28Png },
    { sLocalizedUiJaChapterAsset08A8436CPng, sLocalizedUiJaChapterAsset08A8D948Png, sLocalizedUiJaChapterAsset08A91F08Png },
    { sLocalizedUiJaChapterAsset08A84720Png, sLocalizedUiJaChapterAsset08A8Dab0Png, sLocalizedUiJaChapterAsset08A92170Png },
    { sLocalizedUiJaChapterAsset08A84720Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A81B1CPng, sLocalizedUiJaChapterAsset08A8Cb94Png, sLocalizedUiJaChapterAsset08A90378Png },
    { sLocalizedUiJaChapterAsset08A81F28Png, sLocalizedUiJaChapterAsset08A8CcacPng, sLocalizedUiJaChapterAsset08A9065CPng },
    { sLocalizedUiJaChapterAsset08A8258CPng, sLocalizedUiJaChapterAsset08A8Cf14Png, sLocalizedUiJaChapterAsset08A90A98Png },
    { sLocalizedUiJaChapterAsset08A829B4Png, sLocalizedUiJaChapterAsset08A8D064Png, sLocalizedUiJaChapterAsset08A90D84Png },
    { sLocalizedUiJaChapterAsset08A82D58Png, sLocalizedUiJaChapterAsset08A8D1B0Png, sLocalizedUiJaChapterAsset08A90Ff0Png },
    { sLocalizedUiJaChapterAsset08A8306CPng, sLocalizedUiJaChapterAsset08A8D2F4Png, sLocalizedUiJaChapterAsset08A911D0Png },
    { sLocalizedUiJaChapterAsset08A833D4Png, sLocalizedUiJaChapterAsset08A8D430Png, sLocalizedUiJaChapterAsset08A91418Png },
    { sLocalizedUiJaChapterAsset08A8383CPng, sLocalizedUiJaChapterAsset08A8D574Png, sLocalizedUiJaChapterAsset08A91760Png },
    { sLocalizedUiJaChapterAsset08A83C0CPng, sLocalizedUiJaChapterAsset08A8D6AcPng, sLocalizedUiJaChapterAsset08A919F8Png },
    { sLocalizedUiJaChapterAsset08A83F64Png, sLocalizedUiJaChapterAsset08A8D7F4Png, sLocalizedUiJaChapterAsset08A91C28Png },
    { sLocalizedUiJaChapterAsset08A8436CPng, sLocalizedUiJaChapterAsset08A8D948Png, sLocalizedUiJaChapterAsset08A91F08Png },
    { sLocalizedUiJaChapterAsset08A84720Png, sLocalizedUiJaChapterAsset08A8Dab0Png, sLocalizedUiJaChapterAsset08A92170Png },
    { sLocalizedUiJaChapterAsset08A84720Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A84BfcPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A84F64Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A852E8Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A85670Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A859E4Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A85D6CPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A860F4Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A86460Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A867E4Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A86B60Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A86Ef8Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8729CPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8765CPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A87A14Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A87DbcPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A88174Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A88530Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A888D0Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A88C8CPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A89048Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8B7F0Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8B5DcPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8B5DcPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8B5DcPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8B5DcPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A80Ca0Png, sLocalizedUiJaChapterAsset08A8Cdf8Png, sLocalizedUiJaChapterAsset08A8F9C0Png },
    { sLocalizedUiJaChapterAsset08A82294Png, sLocalizedUiJaChapterAsset08A8Cdf8Png, sLocalizedUiJaChapterAsset08A90898Png },
    { sLocalizedUiJaChapterAsset08A8B5DcPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8B5DcPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8B5DcPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8B5DcPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8B5DcPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8B5DcPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8B5DcPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A89428Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A89710Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A899E8Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A89Cd8Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A89F80Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8A260Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8A5A0Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8A85CPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8Ab8CPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8B5DcPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8B5DcPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8B5DcPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8B5DcPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8B5DcPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8Ae74Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8B168Png, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8B39CPng, 0, 0 },
    { sLocalizedUiJaChapterAsset08A8Bb88Png, 0, 0 },
};

static const struct LocalizedUiGraphicsSubtitleSlide sLocalizedUiZhHansSubtitle[] = {
    { sLocalizedUiZhHansPrologueSlide00Png, sLocalizedUiZhHansPrologueSlide00TsaBin, 335 },
    { sLocalizedUiZhHansPrologueSlide01Png, sLocalizedUiZhHansPrologueSlide01TsaBin, 280 },
    { sLocalizedUiZhHansPrologueSlide02Png, sLocalizedUiZhHansPrologueSlide02TsaBin, 120 },
    { sLocalizedUiZhHansPrologueSlide03Png, sLocalizedUiZhHansPrologueSlide03TsaBin, 280 },
    { sLocalizedUiZhHansPrologueSlide04Png, sLocalizedUiZhHansPrologueSlide04TsaBin, 330 },
    { sLocalizedUiZhHansPrologueSlide05Png, sLocalizedUiZhHansPrologueSlide05TsaBin, 300 },
    { sLocalizedUiZhHansPrologueSlide06Png, sLocalizedUiZhHansPrologueSlide06TsaBin, 250 },
};

static const struct LocalizedUiGraphicsChapterTitle sLocalizedUiZhHansChapterTitles[] = {
    { sLocalizedUiZhHansChapterAsset085Afb24Png, sLocalizedUiZhHansChapterAsset080F0A78Png, sLocalizedUiZhHansChapterAsset080F2150Png },
    { sLocalizedUiZhHansChapterAsset085Afe7CPng, sLocalizedUiZhHansChapterAsset080F0B90Png, sLocalizedUiZhHansChapterAsset080F23AcPng },
    { sLocalizedUiZhHansChapterAsset085B0098Png, sLocalizedUiZhHansChapterAsset080F0C70Png, sLocalizedUiZhHansChapterAsset080F24EcPng },
    { sLocalizedUiZhHansChapterAsset085B046CPng, sLocalizedUiZhHansChapterAsset080F0D60Png, sLocalizedUiZhHansChapterAsset080F27CcPng },
    { sLocalizedUiZhHansChapterAsset085B0808Png, sLocalizedUiZhHansChapterAsset080F0E48Png, sLocalizedUiZhHansChapterAsset080F2Aa8Png },
    { sLocalizedUiZhHansChapterAsset085B0A44Png, sLocalizedUiZhHansChapterAsset080F0F30Png, sLocalizedUiZhHansChapterAsset080F2C00Png },
    { sLocalizedUiZhHansChapterAsset085B0E54Png, sLocalizedUiZhHansChapterAsset080F10BcPng, sLocalizedUiZhHansChapterAsset080F2E8CPng },
    { sLocalizedUiZhHansChapterAsset085B1128Png, sLocalizedUiZhHansChapterAsset080F11AcPng, sLocalizedUiZhHansChapterAsset080F307CPng },
    { sLocalizedUiZhHansChapterAsset085B1464Png, sLocalizedUiZhHansChapterAsset080F12A0Png, sLocalizedUiZhHansChapterAsset080F32D8Png },
    { sLocalizedUiZhHansChapterAsset085B1780Png, sLocalizedUiZhHansChapterAsset080F1380Png, sLocalizedUiZhHansChapterAsset080F3510Png },
    { sLocalizedUiZhHansChapterAsset085B1A40Png, sLocalizedUiZhHansChapterAsset080F1468Png, sLocalizedUiZhHansChapterAsset080F36F8Png },
    { sLocalizedUiZhHansChapterAsset085B1D54Png, sLocalizedUiZhHansChapterAsset080F1554Png, sLocalizedUiZhHansChapterAsset080F3920Png },
    { sLocalizedUiZhHansChapterAsset085B2438Png, sLocalizedUiZhHansChapterAsset080F1744Png, sLocalizedUiZhHansChapterAsset080F3E44Png },
    { sLocalizedUiZhHansChapterAsset085B271CPng, sLocalizedUiZhHansChapterAsset080F1840Png, sLocalizedUiZhHansChapterAsset080F403CPng },
    { sLocalizedUiZhHansChapterAsset085B2A40Png, sLocalizedUiZhHansChapterAsset080F1940Png, sLocalizedUiZhHansChapterAsset080F426CPng },
    { sLocalizedUiZhHansChapterAsset085B4060Png, sLocalizedUiZhHansChapterAsset080F1A40Png, sLocalizedUiZhHansChapterAsset080F51E0Png },
    { sLocalizedUiZhHansChapterAsset085B43A0Png, sLocalizedUiZhHansChapterAsset080F1B3CPng, sLocalizedUiZhHansChapterAsset080F5444Png },
    { sLocalizedUiZhHansChapterAsset085B46E0Png, sLocalizedUiZhHansChapterAsset080F1C34Png, sLocalizedUiZhHansChapterAsset080F568CPng },
    { sLocalizedUiZhHansChapterAsset085B4A08Png, sLocalizedUiZhHansChapterAsset080F1D2CPng, sLocalizedUiZhHansChapterAsset080F58C4Png },
    { sLocalizedUiZhHansChapterAsset085B4Cf8Png, sLocalizedUiZhHansChapterAsset080F1E28Png, sLocalizedUiZhHansChapterAsset080F5Ab4Png },
    { sLocalizedUiZhHansChapterAsset085B5050Png, sLocalizedUiZhHansChapterAsset080F1F28Png, sLocalizedUiZhHansChapterAsset080F5D08Png },
    { sLocalizedUiZhHansChapterAsset085B535CPng, sLocalizedUiZhHansChapterAsset080F2038Png, sLocalizedUiZhHansChapterAsset080F5F10Png },
    { sLocalizedUiZhHansChapterAsset085B535CPng, 0, 0 },
    { sLocalizedUiZhHansChapterAsset085B2D3CPng, sLocalizedUiZhHansChapterAsset080F1468Png, sLocalizedUiZhHansChapterAsset080F4478Png },
    { sLocalizedUiZhHansChapterAsset085B3108Png, sLocalizedUiZhHansChapterAsset080F1554Png, sLocalizedUiZhHansChapterAsset080F4770Png },
    { sLocalizedUiZhHansChapterAsset085B3690Png, sLocalizedUiZhHansChapterAsset080F1744Png, sLocalizedUiZhHansChapterAsset080F4B00Png },
    { sLocalizedUiZhHansChapterAsset085B3A90Png, sLocalizedUiZhHansChapterAsset080F1840Png, sLocalizedUiZhHansChapterAsset080F4E14Png },
    { sLocalizedUiZhHansChapterAsset085B3Dd8Png, sLocalizedUiZhHansChapterAsset080F1940Png, sLocalizedUiZhHansChapterAsset080F5058Png },
    { sLocalizedUiZhHansChapterAsset085B4060Png, sLocalizedUiZhHansChapterAsset080F1A40Png, sLocalizedUiZhHansChapterAsset080F51E0Png },
    { sLocalizedUiZhHansChapterAsset085B43A0Png, sLocalizedUiZhHansChapterAsset080F1B3CPng, sLocalizedUiZhHansChapterAsset080F5444Png },
    { sLocalizedUiZhHansChapterAsset085B46E0Png, sLocalizedUiZhHansChapterAsset080F1C34Png, sLocalizedUiZhHansChapterAsset080F568CPng },
    { sLocalizedUiZhHansChapterAsset085B4A08Png, sLocalizedUiZhHansChapterAsset080F1D2CPng, sLocalizedUiZhHansChapterAsset080F58C4Png },
    { sLocalizedUiZhHansChapterAsset085B4Cf8Png, sLocalizedUiZhHansChapterAsset080F1E28Png, sLocalizedUiZhHansChapterAsset080F5Ab4Png },
    { sLocalizedUiZhHansChapterAsset085B5050Png, sLocalizedUiZhHansChapterAsset080F1F28Png, sLocalizedUiZhHansChapterAsset080F5D08Png },
    { sLocalizedUiZhHansChapterAsset085B535CPng, sLocalizedUiZhHansChapterAsset080F2038Png, sLocalizedUiZhHansChapterAsset080F5F10Png },
    { sLocalizedUiZhHansChapterAsset085B535CPng, 0, 0 },
    { sLocalizedUiZhHansChapterAsset085B569CPng, 0, 0 },
    { sLocalizedUiZhHansChapterAsset085B59C0Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset085B5D00Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset085B6034Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset085B636CPng, 0, 0 },
    { sLocalizedUiZhHansChapterAsset085B669CPng, 0, 0 },
    { sLocalizedUiZhHansChapterAsset085B69D8Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset085B6D0CPng, 0, 0 },
    { sLocalizedUiZhHansChapterAsset085B7044Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset085B7378Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset085B76C0Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset085B79EcPng, 0, 0 },
    { sLocalizedUiZhHansChapterAsset085B7D2CPng, 0, 0 },
    { sLocalizedUiZhHansChapterAsset085B8060Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset085B8398Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset085B86C8Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080Ed85CPng, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080Edb98Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080EdeccPng, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080Ee204Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080F04E0Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080F0318Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080F0318Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080F0318Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080F0318Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset085B2110Png, sLocalizedUiZhHansChapterAsset080F1658Png, sLocalizedUiZhHansChapterAsset080F3Be4Png },
    { sLocalizedUiZhHansChapterAsset085B33F0Png, sLocalizedUiZhHansChapterAsset080F1658Png, sLocalizedUiZhHansChapterAsset080F4950Png },
    { sLocalizedUiZhHansChapterAsset080F0318Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080F0318Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080F0318Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080F0318Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080F0318Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080F0318Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080F0318Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset085B8A00Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080Ee560Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080Ee868Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080Eeb1CPng, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080Eedb4Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080Ef070Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080Ef380Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080Ef618Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080Ef950Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080F0318Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080F0318Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080F0318Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080F0318Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080F0318Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080Efc58Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080EfeccPng, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080F0098Png, 0, 0 },
    { sLocalizedUiZhHansChapterAsset080F0758Png, 0, 0 },
};

static const u16 sLocalizedUiTitleLogo[] = {
    16,
    0x0000, 0x8000, 0x0000, 0x4020, 0x8000, 0x0080,
    0x0000, 0x8020, 0x0004, 0x4020, 0x8020, 0x0084,
    0x0000, 0x8040, 0x0008, 0x4020, 0x8040, 0x0088,
    0x0000, 0x8060, 0x000C, 0x4020, 0x8060, 0x008C,
    0x0000, 0x8080, 0x0010, 0x4020, 0x8080, 0x0090,
    0x0000, 0x80A0, 0x0014, 0x4020, 0x80A0, 0x0094,
    0x0000, 0x80C0, 0x0018, 0x4020, 0x80C0, 0x0098,
    0x8000, 0x80E0, 0x001C, 0x0020, 0x40E0, 0x009C,
};
static const u16 sLocalizedUiTitleExtra[] = {
    4, 0x4000, 0x8000, 0x0000, 0x4000, 0x8020, 0x0004,
    0x4000, 0x8040, 0x0008, 0x4000, 0x8060, 0x000C,
};
static const u16 sLocalizedUiTitleSubtitle[] = {
    5, 0x4000, 0x8000, 0x0000, 0x4000, 0x8020, 0x0004,
    0x4000, 0x8040, 0x0008, 0x4000, 0x8060, 0x000C,
    0x0000, 0x4080, 0x0010,
};
static const u16 sLocalizedUiTitleBanner[] = {
    2, 0x4000, 0xC000, 0x0000, 0x4000, 0xC040, 0x0008,
};
static const u16 sLocalizedUiTitleCopyright[] = {
    7, 0x4000, 0x4000, 0x0000, 0x4000, 0x4020, 0x0004,
    0x4000, 0x4040, 0x0008, 0x4000, 0x4060, 0x000C,
    0x4000, 0x4080, 0x0010, 0x4000, 0x40A0, 0x0014,
    0x0000, 0x00C0, 0x0018,
};
static const u16 sLocalizedUiTitlePressStart[] = {
    3, 0x4000, 0x8000, 0x0000, 0x4000, 0x8020, 0x0004,
    0x0000, 0x4040, 0x0008,
};
static const struct LocalizedUiGraphicsTitleSprites sLocalizedUiTitleSprites = {
    sLocalizedUiTitleLogo, sLocalizedUiTitleExtra, sLocalizedUiTitleSubtitle,
    sLocalizedUiTitleBanner, sLocalizedUiTitleCopyright, sLocalizedUiTitlePressStart,
};

static ExpansionLocaleId LocalizedUiGraphics_CurrentCjkLocale(void)
{
    ExpansionLocaleId locale = ExpansionLocale_GetCurrent();

    if (locale == EXPANSION_LOCALE_JA || locale == EXPANSION_LOCALE_ZH_HANS)
        return locale;

    return EXPANSION_LOCALE_INVALID;
}

const struct LocalizedUiGraphicsTitle *LocalizedUiGraphics_GetTitle(void)
{
    static const struct LocalizedUiGraphicsTitle titleJa = {
        sLocalizedUiJaTitleLogoPng, sLocalizedUiJaTitleLabelsPng,
    };
    static const struct LocalizedUiGraphicsTitle titleZhHans = {
        sLocalizedUiZhHansTitleLogoPng, sLocalizedUiZhHansTitleLabelsPng,
    };

    switch (LocalizedUiGraphics_CurrentCjkLocale()) {
    case EXPANSION_LOCALE_JA:
        return &titleJa;
    case EXPANSION_LOCALE_ZH_HANS:
        return &titleZhHans;
    default:
        return 0;
    }
}

const u8 *LocalizedUiGraphics_GetSaveMenuOptions(void)
{
    switch (LocalizedUiGraphics_CurrentCjkLocale()) {
    case EXPANSION_LOCALE_JA:
        return sLocalizedUiJaMenuMainExtraOptionsPng;
    case EXPANSION_LOCALE_ZH_HANS:
        return sLocalizedUiZhHansMenuMainExtraOptionsPng;
    default:
        return 0;
    }
}

const struct LocalizedUiGraphicsSubtitleSlide *LocalizedUiGraphics_GetSubtitleSlides(void)
{
    switch (LocalizedUiGraphics_CurrentCjkLocale()) {
    case EXPANSION_LOCALE_JA:
        return sLocalizedUiJaSubtitle;
    case EXPANSION_LOCALE_ZH_HANS:
        return sLocalizedUiZhHansSubtitle;
    default:
        return 0;
    }
}

const struct LocalizedUiGraphicsChapterTitle *LocalizedUiGraphics_GetChapterTitle(u32 titleId)
{
    if (titleId >= LOCALIZED_UI_GRAPHICS_CHAPTER_TITLE_COUNT)
        return 0;

    switch (LocalizedUiGraphics_CurrentCjkLocale()) {
    case EXPANSION_LOCALE_JA:
        return &sLocalizedUiJaChapterTitles[titleId];
    case EXPANSION_LOCALE_ZH_HANS:
        return &sLocalizedUiZhHansChapterTitles[titleId];
    default:
        return 0;
    }
}

const u8 *LocalizedUiGraphics_GetChapterTitleFrame(void)
{
    switch (LocalizedUiGraphics_CurrentCjkLocale()) {
    case EXPANSION_LOCALE_JA:
        return sLocalizedUiJaChapterFramePng;
    case EXPANSION_LOCALE_ZH_HANS:
        return sLocalizedUiZhHansChapterFramePng;
    default:
        return 0;
    }
}

const u8 *LocalizedUiGraphics_GetChapterTitleTsa(void)
{
    switch (LocalizedUiGraphics_CurrentCjkLocale()) {
    case EXPANSION_LOCALE_JA:
        return sLocalizedUiJaChapterTitleLayoutTsaBin;
    case EXPANSION_LOCALE_ZH_HANS:
        return sLocalizedUiZhHansChapterTitleLayoutTsaBin;
    default:
        return 0;
    }
}

const struct LocalizedUiGraphicsTitleSprites *LocalizedUiGraphics_GetTitleSprites(void)
{
    return LocalizedUiGraphics_CurrentCjkLocale() == EXPANSION_LOCALE_INVALID
        ? 0 : &sLocalizedUiTitleSprites;
}

#endif /* LOCALIZED_UI_GRAPHICS_CJK_ENABLED */
