"""C89 header/source emitter for full-game localized catalogs."""

from __future__ import annotations

from typing import Iterable, List

from .constants import (
    FALLBACK_KIND_EXPLICIT_ENGLISH,
    FALLBACK_KIND_PROVIDER_UNAVAILABLE,
    FALLBACK_KIND_VALUES,
    LOCALE_IDS,
    NULL_OFFSET,
    NULL_ROOT_INDEX,
    OUTPUT_CONFIG_HEADER_NAME,
    OUTPUT_HEADER_NAME,
    PROVIDER_KIND_VALUES,
    TARGET_STORAGE_BYTES,
)
from .model import EnglishCatalogBundle, GameCatalogBuild, LocaleCatalogBundle
from scripts.localization.game_locales.fixed_width_labels import SURFACE_VALUES


def _locale_suffix(locale: str) -> str:
    if locale == "en":
        return "English"
    parts = locale.replace("-", "_").split("_")
    return "".join(part[:1].upper() + part[1:] for part in parts if part)


def _locale_macro(locale: str) -> str:
    return locale.replace("-", "_").upper()


def _hex_u32(value: int) -> str:
    return "0x%08Xu" % value


def _hex_u8(value: int) -> str:
    return "0x%02Xu" % value


def _wrap_values(values: Iterable[str], *, indent: str, per_line: int) -> List[str]:
    current: List[str] = []
    lines: List[str] = []
    for value in values:
        current.append(value)
        if len(current) == per_line:
            lines.append(indent + ", ".join(current) + ",")
            current = []
    if current:
        lines.append(indent + ", ".join(current) + ",")
    if not lines:
        lines.append(indent + "/* empty */")
    return lines


def render_config_header(build: GameCatalogBuild) -> str:
    max_decoded = max(
        bundle.catalog.budget.max_decoded_bytes
        for bundle in (build.english, *build.locales)
    )
    return "\n".join(
        [
            "/* Generated by scripts/localization/game_catalog -- do not edit. */",
            "#ifndef GUARD_LOCALIZED_GAME_TEXT_DATA_H",
            "#define GUARD_LOCALIZED_GAME_TEXT_DATA_H",
            "",
            "#define FE8_GAME_LOCALIZATION_DATA_PRESENT 1",
            "#define FE8_GAME_LOCALIZATION_TARGET_COUNT %uu" % build.target_count,
            "#define FE8_GAME_LOCALIZATION_MAX_DECODED_BYTES %uu" % max_decoded,
            "",
            "#endif /* GUARD_LOCALIZED_GAME_TEXT_DATA_H */",
            "",
        ]
    )


def render_header(build: GameCatalogBuild) -> str:
    enabled = set(build.enabled_locales)
    lines = [
        "/* Generated by scripts/localization/game_catalog -- do not edit. */",
        "#ifndef GUARD_GAME_LOCALIZATION_CATALOG_H",
        "#define GUARD_GAME_LOCALIZATION_CATALOG_H",
        "",
        '#include "global.h"',
        '#include "%s"' % OUTPUT_CONFIG_HEADER_NAME,
        "",
        "#ifndef SECTION",
        "#define SECTION(name) __attribute__((section(name)))",
        "#endif",
        "",
        "#ifndef GAME_LOCALIZATION_SECTION",
        '#define GAME_LOCALIZATION_SECTION SECTION(".locale_data")',
        "#endif",
        "",
        "#define GAME_LOCALIZATION_TARGET_COUNT %uu" % build.target_count,
        "#define GAME_LOCALIZATION_LOCALE_COUNT %uu" % len(LOCALE_IDS),
        "#define GAME_LOCALIZATION_ENABLED_LOCALE_COUNT %uu" % len(build.locales),
        "#define GAME_LOCALIZATION_COMPILED_LOCALE_COUNT %uu"
        % (len(build.locales) + 1),
        "#define GAME_LOCALIZATION_STORAGE_TARGET_BYTES 0x%04Xu" % TARGET_STORAGE_BYTES,
        "#define GAME_LOCALIZATION_NULL_OFFSET %s" % _hex_u32(NULL_OFFSET),
        "#define GAME_LOCALIZATION_NULL_ROOT_INDEX %s" % _hex_u32(NULL_ROOT_INDEX),
        "",
    ]
    for index, locale in enumerate(LOCALE_IDS):
        lines.append(
            "#define GAME_LOCALIZATION_LOCALE_%s %uu" % (_locale_macro(locale), index)
        )
    lines.extend(
        [
            "",
            "#define GAME_LOCALIZATION_PROVIDER_NONE 0u",
            "#define GAME_LOCALIZATION_PROVIDER_INDEXED 1u",
            "#define GAME_LOCALIZATION_PROVIDER_RAW 2u",
            "#define GAME_LOCALIZATION_PROVIDER_AUTHORED 3u",
            "",
            "#define GAME_LOCALIZATION_FALLBACK_NONE 0u",
            "#define GAME_LOCALIZATION_FALLBACK_EXPLICIT_ENGLISH 1u",
            "#define GAME_LOCALIZATION_FALLBACK_PROVIDER_UNAVAILABLE 2u",
            "",
            "struct GameLocalizationCatalogEntry",
            "{",
            "    const u8 *data;",
            "    u32 compressedSize;",
            "    u32 bitLength;",
            "    u32 maxDecodedBytes;",
            "    u8 present;",
            "    u8 providerKind;",
            "    u8 fallbackKind;",
            "    u8 reserved;",
            "};",
            "",
            "struct GameLocalizationLocaleCatalog",
            "{",
            "    const u32 *nodes;",
            "    u32 nodeCount;",
            "    u32 rootIndex;",
            "    const u8 *compressedBlob;",
            "    u32 compressedSize;",
            "    const struct GameLocalizationCatalogEntry *entries;",
            "    u32 entryCount;",
            "    u32 maxDecodedBytes;",
            "    u32 presentCount;",
            "    u32 explicitFallbackCount;",
            "    u32 providerUnavailableCount;",
            "};",
            "",
            "struct GameLocalizationDisplayAlias",
            "{",
            "    u16 targetId;",
            "    u8 surface;",
            "    u8 reserved;",
            "    const char *text;",
            "};",
            "",
        ]
    )
    english_max_decoded = build.english.catalog.budget.max_decoded_bytes
    english_assertion_bytes = max(TARGET_STORAGE_BYTES, english_max_decoded)
    lines.extend(
        [
            "#define GAME_LOCALIZATION_SHARED_ENGLISH_ENABLED 1u",
            "#define GAME_LOCALIZATION_ENGLISH_STORAGE_REQUIREMENT_BYTES %uu"
            % english_max_decoded,
            "#define GAME_LOCALIZATION_ENGLISH_STORAGE_ASSERTION_BYTES %uu"
            % english_assertion_bytes,
            "typedef char GameLocalizationStorageAssertEnglish[",
            "    (GAME_LOCALIZATION_ENGLISH_STORAGE_ASSERTION_BYTES",
            "        >= GAME_LOCALIZATION_ENGLISH_STORAGE_REQUIREMENT_BYTES)",
            "    ? 1 : -1];",
            "",
            "extern const u32 gGameLocalizationEnglishNodes[];",
            "extern const u8 gGameLocalizationEnglishCompressedBlob[];",
            "extern const struct GameLocalizationCatalogEntry",
            "    gGameLocalizationEnglishEntries[];",
            "extern const struct GameLocalizationLocaleCatalog",
            "    gGameLocalizationEnglishCatalog;",
            "",
        ]
    )
    for locale in LOCALE_IDS:
        suffix = _locale_suffix(locale)
        if locale in enabled:
            bundle = build.locale_bundle(locale)
            max_decoded = bundle.catalog.budget.max_decoded_bytes
            assertion_bytes = max(TARGET_STORAGE_BYTES, max_decoded)
            alias_count = sum(
                len(entries)
                for entries in build.display_aliases.get(locale, {}).values()
            )
        else:
            max_decoded = 0
            assertion_bytes = 0
            alias_count = 0
        lines.extend(
            [
                "#define GAME_LOCALIZATION_%s_ENABLED %uu"
                % (_locale_macro(locale), 1 if locale in enabled else 0),
                "#define GAME_LOCALIZATION_%s_STORAGE_REQUIREMENT_BYTES %uu"
                % (_locale_macro(locale), max_decoded),
                "#define GAME_LOCALIZATION_%s_STORAGE_ASSERTION_BYTES %uu"
                % (_locale_macro(locale), assertion_bytes),
                "typedef char GameLocalizationStorageAssert%s[" % suffix,
                "    (GAME_LOCALIZATION_%s_STORAGE_ASSERTION_BYTES"
                % _locale_macro(locale),
                "        >= GAME_LOCALIZATION_%s_STORAGE_REQUIREMENT_BYTES)"
                % _locale_macro(locale),
                "    ? 1 : -1];",
                "#define GAME_LOCALIZATION_%s_DISPLAY_ALIAS_COUNT %uu"
                % (_locale_macro(locale), alias_count),
                "",
            ]
        )
        if locale in enabled:
            lines.extend(
                [
                    "extern const u32 gGameLocalization%sNodes[];" % suffix,
                    "extern const u8 gGameLocalization%sCompressedBlob[];" % suffix,
                    "extern const struct GameLocalizationCatalogEntry gGameLocalization%sEntries[];"
                    % suffix,
                    "extern const struct GameLocalizationLocaleCatalog gGameLocalizationCatalog%s;"
                    % suffix,
                    "extern const struct GameLocalizationDisplayAlias",
                    "    gGameLocalization%sDisplayAliases[];" % suffix,
                    "",
                ]
            )
    lines.extend(
        [
            "extern const struct GameLocalizationLocaleCatalog *const",
            "    gGameLocalizationCatalogs[GAME_LOCALIZATION_LOCALE_COUNT];",
            "",
            "#endif /* GUARD_GAME_LOCALIZATION_CATALOG_H */",
            "",
        ]
    )
    return "\n".join(lines)


def _render_node_array(
    bundle: EnglishCatalogBundle | LocaleCatalogBundle,
) -> List[str]:
    suffix = _locale_suffix(bundle.locale)
    lines = [
        "const u32 GAME_LOCALIZATION_SECTION gGameLocalization%sNodes[] =" % suffix,
        "{",
    ]
    lines.extend(
        _wrap_values(
            (_hex_u32(node) for node in bundle.catalog.nodes), indent="    ", per_line=4
        )
    )
    lines.extend(["};", ""])
    return lines


def _render_blob_array(
    bundle: EnglishCatalogBundle | LocaleCatalogBundle,
) -> List[str]:
    suffix = _locale_suffix(bundle.locale)
    lines = [
        "const u8 GAME_LOCALIZATION_SECTION gGameLocalization%sCompressedBlob[] =" % suffix,
        "{",
    ]
    lines.extend(
        _wrap_values(
            (_hex_u8(value) for value in bundle.catalog.compressed_blob),
            indent="    ",
            per_line=12,
        )
    )
    lines.extend(["};", ""])
    return lines


def _render_entry_array(
    bundle: EnglishCatalogBundle | LocaleCatalogBundle,
) -> List[str]:
    suffix = _locale_suffix(bundle.locale)
    lines = [
        "const struct GameLocalizationCatalogEntry GAME_LOCALIZATION_SECTION",
        "    gGameLocalization%sEntries[] =" % suffix,
        "{",
    ]
    for meta, entry in zip(bundle.entries, bundle.catalog.entries):
        if bundle.locale == "en":
            provider_kind = PROVIDER_KIND_VALUES[None]
            fallback_kind = 0
        else:
            provider_kind = PROVIDER_KIND_VALUES[meta.locale_provider_kind]
            fallback_kind = FALLBACK_KIND_VALUES[meta.fallback_kind]
        data_pointer = (
            "(const u8 *)0"
            if entry.pointer_offset is None
            else "gGameLocalization%sCompressedBlob + %uu"
            % (suffix, entry.pointer_offset)
        )
        lines.append(
            "    { %s, %uu, %uu, %uu, %uu, %uu, %uu, 0u }, /* 0x%04X */"
            % (
                data_pointer,
                entry.compressed_size,
                entry.bit_length,
                entry.decoded_size,
                1 if bundle.locale == "en" or meta.present else 0,
                provider_kind,
                fallback_kind,
                meta.target_id,
            )
        )
    lines.extend(["};", ""])
    return lines


def _render_locale_catalog(
    bundle: EnglishCatalogBundle | LocaleCatalogBundle,
) -> List[str]:
    suffix = _locale_suffix(bundle.locale)
    catalog_name = (
        "gGameLocalizationEnglishCatalog"
        if bundle.locale == "en"
        else "gGameLocalizationCatalog%s" % suffix
    )
    if bundle.locale == "en":
        explicit_fallback_count = 0
        provider_unavailable_count = 0
    else:
        explicit_fallback_count = sum(
            1
            for meta in bundle.entries
            if meta.fallback_kind == FALLBACK_KIND_EXPLICIT_ENGLISH
        )
        provider_unavailable_count = sum(
            1
            for meta in bundle.entries
            if meta.fallback_kind == FALLBACK_KIND_PROVIDER_UNAVAILABLE
        )
    lines = [
        "const struct GameLocalizationLocaleCatalog GAME_LOCALIZATION_SECTION",
        "    %s =" % catalog_name,
        "{",
        "    gGameLocalization%sNodes," % suffix,
        "    %uu," % len(bundle.catalog.nodes),
        "    %s,"
        % (
            _hex_u32(NULL_ROOT_INDEX)
            if bundle.catalog.root_index is None
            else "%uu" % bundle.catalog.root_index
        ),
        "    gGameLocalization%sCompressedBlob," % suffix,
        "    %uu," % len(bundle.catalog.compressed_blob),
        "    gGameLocalization%sEntries," % suffix,
        "    %uu," % len(bundle.entries),
        "    %uu," % bundle.catalog.budget.max_decoded_bytes,
        "    %uu,"
        % (
            len(bundle.entries)
            if bundle.locale == "en"
            else sum(1 for meta in bundle.entries if meta.present)
        ),
        "    %uu," % explicit_fallback_count,
        "    %uu," % provider_unavailable_count,
        "};",
        "",
    ]
    return lines


def _render_display_aliases(build: GameCatalogBuild, locale: str) -> List[str]:
    suffix = _locale_suffix(locale)
    rows = []
    for surface, entries in sorted(
        build.display_aliases.get(locale, {}).items(),
        key=lambda item: SURFACE_VALUES[item[0]],
    ):
        for target_id, text in sorted(entries.items()):
            rows.append((surface, target_id, text))
    lines: List[str] = []
    for surface, target_id, text in rows:
        name = "sGameLocalization%sAlias%u_%04X" % (
            suffix,
            SURFACE_VALUES[surface],
            target_id,
        )
        lines.extend(
            [
                "static const u8 GAME_LOCALIZATION_SECTION %s[] =" % name,
                "{",
                *_wrap_values(
                    (
                        _hex_u8(value)
                        for value in text.encode("utf-8") + b"\0"
                    ),
                    indent="    ",
                    per_line=12,
                ),
                "};",
                "",
            ]
        )
    lines.extend(
        [
            "const struct GameLocalizationDisplayAlias GAME_LOCALIZATION_SECTION",
            "    gGameLocalization%sDisplayAliases[] =" % suffix,
            "{",
        ]
    )
    for surface, target_id, _ in rows:
        name = "sGameLocalization%sAlias%u_%04X" % (
            suffix,
            SURFACE_VALUES[surface],
            target_id,
        )
        lines.append(
            "    { 0x%04Xu, %uu, 0u, (const char *)%s },"
            % (target_id, SURFACE_VALUES[surface], name)
        )
    if not rows:
        lines.append("    { 0u, 0u, 0u, (const char *)0 },")
    lines.extend(["};", ""])
    return lines


def render_source(build: GameCatalogBuild) -> str:
    enabled = set(build.enabled_locales)
    lines = [
        "/* Generated by scripts/localization/game_catalog -- do not edit. */",
        '#include "global.h"',
        '#include "%s"' % OUTPUT_HEADER_NAME,
        "",
    ]
    lines.extend(_render_node_array(build.english))
    lines.extend(_render_blob_array(build.english))
    lines.extend(_render_entry_array(build.english))
    lines.extend(_render_locale_catalog(build.english))
    for bundle in build.locales:
        lines.extend(_render_node_array(bundle))
        lines.extend(_render_blob_array(bundle))
        lines.extend(_render_entry_array(bundle))
        lines.extend(_render_locale_catalog(bundle))
        lines.extend(_render_display_aliases(build, bundle.locale))
    lines.extend(
        [
            "const struct GameLocalizationLocaleCatalog *const GAME_LOCALIZATION_SECTION",
            "    gGameLocalizationCatalogs[GAME_LOCALIZATION_LOCALE_COUNT] =",
            "{",
        ]
    )
    for locale in LOCALE_IDS:
        if locale in enabled:
            lines.append("    &gGameLocalizationCatalog%s," % _locale_suffix(locale))
        else:
            lines.append("    (const struct GameLocalizationLocaleCatalog *)0,")
    lines.extend(["};", ""])
    return "\n".join(lines)
